LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/python3/CMakeLists.txt File Reference
/home/erik/prefix/default/src/soapysdr/python3/CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 2.8) project(SoapySDRPython3 CXX) enable_testing() find_package(SoapySDR NO_MODULE REQUIRED) list(APPEND CMAKE_MODULE_PATH $
find_package (SWIG) message(STATUS"SWIG_FOUND
print (get_python_lib(plat_specific=True, prefix=''))" OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE PYTHON3_INSTALL_DIR_SYSCONF) set(PYTHON3_INSTALL_DIR "$
CACHE STRING python3 install prefix message (STATUS"PYTHON3_INSTALL_DIR: \${prefix}/${PYTHON3_INSTALL_DIR}") find_package(Python3Libs) message(STATUS"PYTHON3LIBS_FOUND
message (STATUS"PYTHON3_INCLUDE_DIRS: ${PYTHON3_INCLUDE_DIRS}") message(STATUS"PYTHON3_LIBRARIES
set (PYTHON3_DEBUG_OK TRUE) if(WIN32 AND NOT PYTHON3_DEBUG_LIBRARY AND"$
STREQUAL Debug message (WARNING"WIN32 Debug mode requires PYTHON3_DEBUG_LIBRARY") set(PYTHON3_DEBUG_OK FALSE) endif() include(FeatureSummary) include(CMakeDependentOption) cmake_dependent_option(ENABLE_PYTHON3"Enable python bindings"ON"ENABLE_LIBRARY
BUILD_PYTHON3 OFF add_feature_info (Python3 ENABLE_PYTHON3"python3 bindings") if(NOT ENABLE_PYTHON3) return() endif() include(UseSWIG) include_directories($
include_directories (${PYTHON3_INCLUDE_DIRS}) configure_file($
Variables
SWIG_FOUND
PYTHON3INTERP_FOUND
PYTHON3LIBS_FOUND
PYTHON3_DEBUG_OK
Function Documentation
BUILD_PYTHON3 OFF add_feature_info (Python3 ENABLE_PYTHON3"python3 bindings")
Definition at line 59 of file CMakeLists.txt.
cmake_minimum_required (VERSION 2. 8)
Definition at line 4 of file CMakeLists.txt.
find_package (SWIG)
Definition at line 14 of file CMakeLists.txt.
include_directories (${PYTHON3_INCLUDE_DIRS})
Definition at line 69 of file CMakeLists.txt.
Referenced by endif(), set(), and target_link_libraries().
CACHE STRING python3 install prefix message (STATUS"PYTHON3_INSTALL_DIR: \${prefix}/${PYTHON3_INSTALL_DIR}")
Definition at line 34 of file CMakeLists.txt.
References PYTHON3LIBS_FOUND.
message (STATUS"PYTHON3_INCLUDE_DIRS: ${PYTHON3_INCLUDE_DIRS}")
Definition at line 41 of file CMakeLists.txt.
STREQUAL Debug message (WARNING"WIN32 Debug mode requires PYTHON3_DEBUG_LIBRARY")
print (get_python_lib(plat_specific=True, prefix=''))
Definition at line 29 of file CMakeLists.txt.
References install().
set (PYTHON3_DEBUG_OK TRUE)
Definition at line 47 of file CMakeLists.txt.
References mode.
Variable Documentation
PYTHON3_DEBUG_OK
Definition at line 58 of file CMakeLists.txt.
PYTHON3INTERP_FOUND
Definition at line 58 of file CMakeLists.txt.
PYTHON3LIBS_FOUND
Definition at line 58 of file CMakeLists.txt.
Referenced by message().
SWIG_FOUND
Definition at line 58 of file CMakeLists.txt.