LimeSuite-UML: dlgAbout_view Class Reference
dlgAbout_view Class Reference
Class dlgAbout_view.
#include <lms7suiteApp_gui.h>
Public Member Functions
dlgAbout_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("About"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE)
~dlgAbout_view ()
Protected Member Functions
virtual void OnInit (wxInitDialogEvent &event)
virtual void OnbtnClose (wxCommandEvent &event)
Protected Attributes
wxStaticBitmap * imgLogo
wxStaticText * ID_STATICTEXT1
wxStaticText * txtVersion
wxStaticText * ID_STATICTEXT4
wxStaticText * ID_STATICTEXT5
wxHyperlinkCtrl * ID_HYPERLINKCTRL1
wxButton * btnClose
Detailed Description
Class dlgAbout_view.
Definition at line 90 of file lms7suiteApp_gui.h.
Constructor & Destructor Documentation
dlgAbout_view::dlgAbout_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxT("About"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE)
Definition at line 160 of file lms7suiteApp_gui.cpp.
References btnClose, ID_HYPERLINKCTRL1, ID_STATICTEXT1, ID_STATICTEXT4, ID_STATICTEXT5, imgLogo, OnbtnClose(), OnInit(), and txtVersion.
dlgAbout_view::~dlgAbout_view ()
Definition at line 242 of file lms7suiteApp_gui.cpp.
References btnClose, OnbtnClose(), and OnInit().
Member Function Documentation
virtual void dlgAbout_view::OnbtnClose (wxCommandEvent & event) inline protected virtual
Reimplemented in dlgAbout.
Definition at line 105 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view(), and ~dlgAbout_view().
virtual void dlgAbout_view::OnInit (wxInitDialogEvent & event) inline protected virtual
Reimplemented in dlgAbout.
Definition at line 104 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view(), and ~dlgAbout_view().
Member Data Documentation
wxButton* dlgAbout_view::btnClose protected
Definition at line 101 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view(), and ~dlgAbout_view().
wxHyperlinkCtrl* dlgAbout_view::ID_HYPERLINKCTRL1 protected
Definition at line 100 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view().
wxStaticText* dlgAbout_view::ID_STATICTEXT1 protected
Definition at line 96 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view().
wxStaticText* dlgAbout_view::ID_STATICTEXT4 protected
Definition at line 98 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view().
wxStaticText* dlgAbout_view::ID_STATICTEXT5 protected
Definition at line 99 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view().
wxStaticBitmap* dlgAbout_view::imgLogo protected
Definition at line 95 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view(), and dlgAbout::OnInit().
wxStaticText* dlgAbout_view::txtVersion protected
Definition at line 97 of file lms7suiteApp_gui.h.
Referenced by dlgAbout_view(), and dlgAbout::OnInit().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7suiteApp_gui.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7suiteApp_gui.cpp