LimeSuite-UML: /home/erik/prefix/default/src/gr-radar-dev/docs/doxygen/CMakeLists.txt File Reference
/home/erik/prefix/default/src/gr-radar-dev/docs/doxygen/CMakeLists.txt File Reference
Functions
file (TO_NATIVE_PATH ${CMAKE_SOURCE_DIR}top_srcdir) file(TO_NATIVE_PATH $
abs_top_builddir set (HAVE_DOT ${DOXYGEN_DOT_FOUND}) set(enable_html_docs YES) set(enable_latex_docs NO) set(enable_xml_docs YES) configure_file($
Function Documentation
top_builddir file (TO_NATIVE_PATH ${CMAKE_SOURCE_DIR} top_srcdir)
Definition at line 23 of file CMakeLists.txt.
Referenced by endif(), find_package(), swig_doc::make_swig_interface_file(), INI< T, U, V >::parse(), INI< T, U, V >::parseBinary(), lime::LMS64CProtocol::ProgramUpdate(), INI< T, U, V >::save(), INI< T, U, V >::saveBinary(), INI< T, U, V >::saveBinaryExperimental(), and set().
abs_top_builddir set (HAVE_DOT ${DOXYGEN_DOT_FOUND})
Definition at line 28 of file CMakeLists.txt.
References install().