LimeSuite-UML: swig::traits_asptr_stdseq< Seq, T > Struct Template Reference
swig::traits_asptr_stdseq< Seq, T > Struct Template Reference
Public Types
typedef Seq sequence
typedef T value_type
typedef Seq sequence
typedef T value_type
Static Public Member Functions
static int asptr (PyObject *obj, sequence **seq)
static int asptr (PyObject *obj, sequence **seq)
Detailed Description
template<class Seq, class T = typename Seq::value_type>
struct swig::traits_asptr_stdseq< Seq, T >
Definition at line 4730 of file SoapySDRPYTHON_wrap.cxx.
Member Typedef Documentation
template<class Seq, class T = typename Seq::value_type> typedef Seq swig::traits_asptr_stdseq< Seq, T >::sequence
Definition at line 4595 of file radar_swigPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef Seq swig::traits_asptr_stdseq< Seq, T >::sequence
Definition at line 4731 of file SoapySDRPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef T swig::traits_asptr_stdseq< Seq, T >::value_type
Definition at line 4596 of file radar_swigPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef T swig::traits_asptr_stdseq< Seq, T >::value_type
Definition at line 4732 of file SoapySDRPYTHON_wrap.cxx.
Member Function Documentation
template<class Seq, class T = typename Seq::value_type> static int swig::traits_asptr_stdseq< Seq, T >::asptr (PyObject * obj, sequence ** seq) inline static
Definition at line 4598 of file radar_swigPYTHON_wrap.cxx.
References swig::assign(), swig::SwigPySequence_Cont< T >::check(), p(), SWIG_ConvertPtr, SWIG_ERROR, SWIG_NEWOBJ, SWIG_OK, SWIG_OLDOBJ, and SWIG_Python_GetSwigThis().
template<class Seq, class T = typename Seq::value_type> static int swig::traits_asptr_stdseq< Seq, T >::asptr (PyObject * obj, sequence ** seq) inline static
Definition at line 4734 of file SoapySDRPYTHON_wrap.cxx.
References swig::assign(), swig::SwigPySequence_Cont< T >::check(), p(), SWIG_ConvertPtr, SWIG_ERROR, SWIG_NEWOBJ, SWIG_OK, SWIG_OLDOBJ, and SWIG_Python_GetSwigThis().
The documentation for this struct was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDRPYTHON_wrap.cxx
/home/erik/prefix/default/src/gr-radar-dev/build/swig/radar_swigPYTHON_wrap.cxx