LimeSuite-UML: OpenGLGraph Class Reference
OpenGLGraph Class Reference
#include <OpenGLGraph.h>
Public Member Functions
OpenGLGraph (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size, long style, const wxString &name=wxEmptyString, const int *args=GLCanvasAttributes)
virtual ~OpenGLGraph ()
bool Initialize (int width, int height)
void Resize (int w, int h)
Changes graph view size.
void AddSerie (cDataSerie *serie)
Adds data serie to graph.
void RemoveSeries (unsigned int i)
Removes data serie from graph.
void SetInitialDisplayArea (float minx, float maxx, float miny, float maxy)
Sets initialy displayed data area, when resetting zoom it will be reset to this area.
void SetDisplayArea (float minx, float maxx, float miny, float maxy)
Sets visible area.
void ZoomY (float centerY, float spanY)
Changes Y axis center and span values.
void ZoomX (float centerX, float spanX)
Changes X axis center and span values.
void Zoom (float centerX, float centerY, float spanX, float spanY)
Changes X and Y axis center and span values.
void ZoomRect (int x1, int x2, int y1, int y2)
Zooms in area selected by window pixels.
void Pan (float dx, float dy)
Moves visible data area by set amount of pixels.
void SetDrawingMode (eDrawingMode mode)
Sets drawing mode (GLG_POINTS, GLG_LINE)
void Draw ()
Draw graph data series.
bool SaveConfig (char *file)
bool LoadConfig (char *file)
void SettingsChanged ()
Signals that settings have changed and needs to be reevaluated.
void OnMouseDown (int mouseButton, int X, int Y)
Handles mouse button pressing events.
void OnMouseUp (int mouseButton, int X, int Y)
Handles mouse button releasing events.
void OnMouseMove (int X, int Y)
Handles mouse moving events.
void ResetView ()
Resets displayed area to initial area.
void Fit ()
void SetMarker (int id, float xValue, bool enabled, bool show)
void GetMarker (int id, float &xValue, float &yValue, bool &enabled, bool &show)
int AddMarker (int posX)
Add marker at selected pixel.
int AddMarkerAtValue (float xValue)
Add marker at selected data x value.
void RemoveMarker ()
Removes last added marker.
void RemoveMarker (int id)
void MoveMarker (int markerID, int posX)
change marker position
void ChangeMarker (int markerID, float xValue)
change marker position
bool SearchPeak ()
void SetInfoMessage (const char *msg, unsigned int index)
void render (wxPaintEvent &evt)
void resized (wxSizeEvent &evt)
void mouseMoved (wxMouseEvent &event)
void mouseWheelMoved (wxMouseEvent &event)
void mouseReleased (wxMouseEvent &event)
void rightClick (wxMouseEvent &event)
void leftClick (wxMouseEvent &event)
void middleClick (wxMouseEvent &event)
void mouseLeftWindow (wxMouseEvent &event)
void keyPressed (wxKeyEvent &event)
void keyReleased (wxKeyEvent &event)
void onFit (wxCommandEvent &event)
void onMouseHelp (wxCommandEvent &event)
void onAddMarker (wxCommandEvent &event)
void onRemoveMarker (wxCommandEvent &event)
void onShowMarkersMenu (wxCommandEvent &event)
void onLockAspect (wxCommandEvent &event)
void onSearchPeak (wxCommandEvent &event)
void OnTimer (wxTimerEvent &event)
void onReset (wxCommandEvent &event)
Public Attributes
std::vector< cDataSerie * > series
GLG_settings settings
Static Public Attributes
static const int GLCanvasAttributes [8]
Private Member Functions
void UpdateInfoDisplay ()
void ShowMenu (int x, int y)
void setupViewport (int w, int h)
bool isInsideDataView (int X, int Y)
Checks if pixel is inside data view.
void dataViewPixelToValue (int x, int y, float &valX, float &valY)
Calculates value pointed by pixel in data view.
void DrawStaticElements ()
Draw static elements (background colors, titles, grid)
void DrawMarkers ()
Draw data markers.
void CalculateGrid ()
Calculates grid position and spacing values.
void switchToWindowView ()
Changes Opengl viewport area to whole window.
void switchToDataView ()
changes Opengl viewport area to data view region and changes scale
GLvoid glRenderText (float posx, float posy, float angle, float scale, unsigned int rgba, const char *fmt,...)
Prints text in defined position.
int TextWidthInPixels (const char *str)
Returns text string width in pixels.
int NumberWidthInPixels (float num, unsigned int prec=0)
Returns number text width in pixels.
int LineHeight ()
Returns line height in pixels.
float calcAxisGrid (GLG_settings st, bool xAxis)
int clickedOnMarker (int X, int Y)
Checks if mouse clicked on marker.
Private Attributes
bool oglOk
bool glInitialized
std::vector< std::string > info_msg
std::vector< std::string > info_msg_toDisplay
dlgMarkers * mMarkersDlg
wxMenu m_popmenu
wxGLContext * m_DrawingContext
eOGLGActionState m_actionState
bool viewChanged
bool initialized
sRect< float > initialDisplayArea
sRect< int > m_MouseCoord
float m_lastSpanX
float m_lastSpanY
GLFont * m_font
std::vector< OGLMarker > markers
int m_selectedMarker
unsigned m_maxMarkers
bool m_currentlyDrawing
wxTimer * m_timer
wxGLContext * m_glContext
Static Private Attributes
static const unsigned int mMarkerColors [] = {0x000000FF, 0x0000FFFF, 0xFF0000FF, 0xFF7F00FF, 0x007FFFFF, 0xFF00FFFF, 0x007F00FF, 0x00007FFF, 0x7F0000FF, 0x00FF00FF}
Friends
class dlgMarkers
Detailed Description
Definition at line 281 of file OpenGLGraph.h.
Constructor & Destructor Documentation
OpenGLGraph::OpenGLGraph (wxWindow * parent, wxWindowID id = -1, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0, const wxString & name = wxEmptyString, const int * args = GLCanvasAttributes)
Definition at line 60 of file OpenGLGraph.cpp.
References dlgMarkers::AddDeltas(), dlgMarkers::AddMarker(), dlgMarkers, h, i, info_msg, info_msg_toDisplay, initialized, GLG_settings::lock_aspect, m_actionState, m_font, m_glContext, m_maxMarkers, m_popmenu, m_selectedMarker, m_timer, markers, markers_timer_id, mMarkerColors, mMarkersDlg, OGLG_ADD_MARK, OGLG_FIT, OGLG_HELP_MOUSE, OGLG_IDLE, OGLG_LOCKASPECT, OGLG_REMOVE_MARKER, OGLG_RESET, OGLG_SEARCH_PEAK, OGLG_SHOW_MARKERS_MENU, dlgMarkers::parent_graph, settings, and setupViewport().
OpenGLGraph::~OpenGLGraph () virtual
Definition at line 116 of file OpenGLGraph.cpp.
References m_font, and m_timer.
Member Function Documentation
int OpenGLGraph::AddMarker (int posX)
Add marker at selected pixel.
Parameters
posX mouse x coordinate in graph window
Returns
marker id
Definition at line 1121 of file OpenGLGraph.cpp.
References OGLMarker::color, OGLMarker::dataValueIndex, GLG_settings::dataViewWidth, i, OGLMarker::id, GLG_settings::marginLeft, markers, mMarkerColors, OGLMarker::posX, OGLMarker::posY, series, settings, OGLMarker::show, OGLMarker::used, GLG_settings::visibleArea, sRect< T >::x1, and sRect< T >::x2.
Referenced by onAddMarker().
int OpenGLGraph::AddMarkerAtValue (float xValue)
Add marker at selected data x value.
Returns
marker id
Definition at line 1178 of file OpenGLGraph.cpp.
References OGLMarker::color, OGLMarker::dataValueIndex, i, OGLMarker::id, markers, mMarkerColors, mMarkersDlg, OGLMarker::posX, OGLMarker::posY, dlgMarkers::refreshMarkFreq, series, and OGLMarker::used.
Referenced by SearchPeak().
void OpenGLGraph::AddSerie (cDataSerie * serie)
Adds data serie to graph.
Definition at line 193 of file OpenGLGraph.cpp.
References series.
Referenced by fftviewer_frFFTviewer::fftviewer_frFFTviewer().
float OpenGLGraph::calcAxisGrid (GLG_settings st, bool xAxis) private
void OpenGLGraph::CalculateGrid () private
Calculates grid position and spacing values.
Definition at line 501 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, GLG_settings::dataViewWidth, format, GLFont::getTextSize(), GLG_settings::gridValuesHeight, GLG_settings::gridXlines, GLG_settings::gridXprec, GLG_settings::gridXspacing, GLG_settings::gridXstart, GLG_settings::gridYlines, GLG_settings::gridYprec, GLG_settings::gridYspacing, GLG_settings::gridYstart, int(), m_font, settings, SettingsChanged(), GLG_settings::staticGrid, GLG_settings::visibleArea, sRect< T >::x1, sRect< T >::x2, GLG_settings::xUnits, sRect< T >::y1, and sRect< T >::y2.
Referenced by DrawStaticElements().
void OpenGLGraph::ChangeMarker (int markerID, float xValue)
change marker position
Parameters
markerID index of marker to be moved
posX mouse x coordinate in graph window
Definition at line 1449 of file OpenGLGraph.cpp.
References OGLMarker::dataValueIndex, i, markers, OGLMarker::posX, OGLMarker::posY, and series.
Referenced by SetMarker().
int OpenGLGraph::clickedOnMarker (int X, int Y) private
Checks if mouse clicked on marker.
Parameters
X mouse x coorindate
Y mouse y coorindate
Returns
clicked marker index
Definition at line 1341 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, i, GLG_settings::marginBottom, markers, series, settings, GLG_settings::visibleArea, sRect< T >::y1, and sRect< T >::y2.
Referenced by OnMouseDown().
void OpenGLGraph::dataViewPixelToValue (int x, int y, float & valX, float & valY) private
Calculates value pointed by pixel in data view.
Parameters
x x coordinate of mouse pointer
y y coordinate of mouse pointer
&valX x axis data value pointed by mouse
&valY y axis data value pointed by mouse
x and y coordinate (0, 0) are at the data view lower left corner
Definition at line 1056 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, GLG_settings::dataViewWidth, settings, GLG_settings::visibleArea, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by MoveMarker(), and ZoomRect().
void OpenGLGraph::Draw ()
Draw graph data series.
Definition at line 638 of file OpenGLGraph.cpp.
References GLG_color::alpha, GLG_settings::backgroundColor, GLG_color::blue, DrawMarkers(), DrawStaticElements(), GL_ARRAY_BUFFER, GL_ARRAY_BUFFER_ARB, GL_COLOR, GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, GL_DYNAMIC_DRAW_ARB, GL_FLOAT, GL_LINE_STRIP, GL_POINTS, GL_VERTEX_ARRAY, glBegin(), glBindBufferARB, glBufferDataARB, glClear(), glClearColor(), glColor3f(), glDisableClientState(), glDrawArrays(), glEnableClientState(), glEnd(), GLEW_VERSION_1_5, glFlush(), GLG_POINTS, glGenBuffersARB, glLoadIdentity(), glPointSize(), glRenderText(), glVertex2d(), glVertex3f(), glVertexPointer(), GLG_settings::graphType, GLG_color::green, h, i, info_msg_toDisplay, Initialize(), initialized, m_actionState, m_glContext, m_MouseCoord, GLG_settings::marginBottom, GLG_settings::marginLeft, OGLG_ZOOMIN, oglOk, GLG_settings::pointsSize, GLG_color::red, series, settings, setupViewport(), switchToDataView(), switchToWindowView(), GLG_settings::useVBO, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by fftviewer_frFFTviewer::OnUpdatePlots(), and render().
void OpenGLGraph::DrawMarkers () private
Draw data markers.
Definition at line 1258 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, GLG_settings::dataViewWidth, GL_TRIANGLES, glBegin(), glColor4f(), glEnd(), glFlush(), glRenderText(), glVertex3f(), i, GLFont::lineHeight(), m_font, GLG_settings::marginBottom, GLG_settings::marginLeft, GLG_settings::marginRight, GLG_settings::marginTop, markers, GLG_settings::markersEnabled, mMarkerColors, series, settings, switchToWindowView(), GLG_settings::visibleArea, GLG_settings::windowHeight, GLG_settings::windowWidth, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by Draw().
void OpenGLGraph::DrawStaticElements () private
Draw static elements (background colors, titles, grid)
Definition at line 358 of file OpenGLGraph.cpp.
References GLG_color::alpha, GLG_color::blue, CalculateGrid(), GLG_settings::dataViewBackgroundColor, GLG_settings::dataViewHeight, GLG_settings::dataViewWidth, format, GLFont::getTextSize(), GL_LINES, GL_QUADS, glBegin(), glColor3f(), glColor4f(), glEnd(), glFlush(), glRenderText(), glVertex2d(), glVertex3d(), glVertex3f(), GLG_color::green, GLG_settings::gridColor, GLG_settings::gridXoffset, GLG_settings::gridXprec, GLG_settings::gridXspacing, GLG_settings::gridXstart, GLG_settings::gridYprec, GLG_settings::gridYspacing, GLG_settings::gridYstart, i, m_font, GLG_settings::marginBottom, GLG_settings::marginLeft, GLG_settings::marginRight, GLG_settings::marginTop, GLG_color::red, settings, GLG_settings::staticGrid, switchToDataView(), switchToWindowView(), GLG_settings::title, GLG_settings::titlesColor, GLG_settings::titleXaxis, GLG_settings::titleYaxis, viewChanged, GLG_settings::visibleArea, GLG_settings::windowHeight, GLG_settings::windowWidth, sRect< T >::x1, sRect< T >::x2, GLG_settings::xUnits, sRect< T >::y1, sRect< T >::y2, and GLG_settings::yUnits.
Referenced by Draw().
void OpenGLGraph::Fit ()
Definition at line 857 of file OpenGLGraph.cpp.
References i, series, and SetDisplayArea().
Referenced by onFit().
void OpenGLGraph::GetMarker (int id, float & xValue, float & yValue, bool & enabled, bool & show)
Definition at line 1687 of file OpenGLGraph.cpp.
References id, and markers.
GLvoid OpenGLGraph::glRenderText (float posx, float posy, float angle, float scale, unsigned int rgba, const char * fmt, ...) private
Prints text in defined position.
Parameters
posx x position of text lower left corner
posy y position of text lower left corner
angle angle in degrees counterclockwise to rotate text
scale font scaling
fmt text format and parameters
Definition at line 821 of file OpenGLGraph.cpp.
References ap, GL_TEXTURE_2D, glDisable(), glEnable(), glPopMatrix(), glPushMatrix(), glRotatef(), glTranslatef(), m_font, and GLFont::render_textWorldSpace().
Referenced by Draw(), DrawMarkers(), and DrawStaticElements().
bool OpenGLGraph::Initialize (int width, int height)
Definition at line 126 of file OpenGLGraph.cpp.
References GLG_color::alpha, GLG_settings::backgroundColor, GLG_color::blue, GLG_settings::fontSize, GL_ALPHA_TEST, GL_BLEND, GL_COLOR_BUFFER_BIT, GL_GEQUAL, GL_ONE_MINUS_SRC_ALPHA, GL_SRC_ALPHA, GL_TEXTURE_2D, GL_VERSION, glAlphaFunc(), glBlendFunc(), glClear(), glClearColor(), glEnable(), GLEW_OK, glewGetErrorString(), glewInit(), glewIsSupported(), glGetString(), GLG_color::green, initialized, GLFont::loadFromArray(), m_font, oglOk, GLG_color::red, Resize(), settings, standardStaticFont, and viewChanged.
Referenced by Draw().
bool OpenGLGraph::isInsideDataView (int X, int Y) private
Checks if pixel is inside data view.
Parameters
X mouse x coordinate
Y mouse y coordinate
Returns
false : pixel is outside data view
true : pixel is inside data view
Definition at line 1073 of file OpenGLGraph.cpp.
References GLG_settings::marginBottom, GLG_settings::marginLeft, GLG_settings::marginRight, GLG_settings::marginTop, settings, GLG_settings::windowHeight, and GLG_settings::windowWidth.
Referenced by OnMouseMove(), and OnMouseUp().
void OpenGLGraph::keyPressed (wxKeyEvent & event)
Definition at line 1556 of file OpenGLGraph.cpp.
void OpenGLGraph::keyReleased (wxKeyEvent & event)
Definition at line 1560 of file OpenGLGraph.cpp.
void OpenGLGraph::leftClick (wxMouseEvent & event)
Definition at line 1544 of file OpenGLGraph.cpp.
References OGLG_LEFT, and OnMouseDown().
Referenced by SetInfoMessage().
int OpenGLGraph::LineHeight () private
Returns line height in pixels.
Definition at line 1111 of file OpenGLGraph.cpp.
References GLFont::lineHeight(), and m_font.
bool OpenGLGraph::LoadConfig (char * file)
Definition at line 772 of file OpenGLGraph.cpp.
void OpenGLGraph::middleClick (wxMouseEvent & event)
Definition at line 1548 of file OpenGLGraph.cpp.
References OGLG_MIDDLE, and OnMouseDown().
Referenced by SetInfoMessage().
void OpenGLGraph::mouseLeftWindow (wxMouseEvent & event)
Definition at line 1552 of file OpenGLGraph.cpp.
Referenced by SetInfoMessage().
void OpenGLGraph::mouseMoved (wxMouseEvent & event)
Definition at line 1521 of file OpenGLGraph.cpp.
References OnMouseMove().
Referenced by SetInfoMessage().
void OpenGLGraph::mouseReleased (wxMouseEvent & event)
Definition at line 1531 of file OpenGLGraph.cpp.
References OGLG_LEFT, OGLG_MIDDLE, OGLG_RIGHT, and OnMouseUp().
Referenced by SetInfoMessage().
void OpenGLGraph::mouseWheelMoved (wxMouseEvent & event)
Definition at line 1526 of file OpenGLGraph.cpp.
Referenced by SetInfoMessage().
void OpenGLGraph::MoveMarker (int markerID, int posX)
change marker position
Parameters
markerID index of marker to be moved
posX mouse x coordinate in graph window
Definition at line 1379 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, dataViewPixelToValue(), GLG_settings::dataViewWidth, i, GLG_settings::marginBottom, GLG_settings::marginLeft, markers, mMarkersDlg, dlgMarkers::refreshMarkFreq, series, settings, GLG_settings::visibleArea, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by OnMouseMove().
int OpenGLGraph::NumberWidthInPixels (float num, unsigned int prec = 0) private
Returns number text width in pixels.
Parameters
num number
fontSize text height in pixels
prec number of decimal digits
Definition at line 1099 of file OpenGLGraph.cpp.
References format, and TextWidthInPixels().
void OpenGLGraph::onAddMarker (wxCommandEvent & event)
Definition at line 1579 of file OpenGLGraph.cpp.
References AddMarker(), m_MouseCoord, and sRect< T >::x2.
Referenced by SetInfoMessage().
void OpenGLGraph::onFit (wxCommandEvent & event)
Definition at line 1565 of file OpenGLGraph.cpp.
References Fit().
Referenced by SetInfoMessage().
void OpenGLGraph::onLockAspect (wxCommandEvent & event)
Definition at line 1598 of file OpenGLGraph.cpp.
References GLG_settings::lock_aspect, and settings.
Referenced by SetInfoMessage().
void OpenGLGraph::OnMouseDown (int mouseButton, int X, int Y)
Handles mouse button pressing events.
Parameters
mouseButton mouse button code
X x coordinate of mouse pointer inside graph window
Y y coordinate of mouse pointer inside graph window
Given mouse coordinates (0,0) are at top left corner of window
Definition at line 897 of file OpenGLGraph.cpp.
References clickedOnMarker(), m_actionState, m_lastSpanX, m_lastSpanY, m_MouseCoord, m_selectedMarker, OGLG_LEFT, OGLG_MIDDLE, OGLG_MOVE_MARKER, OGLG_PAN, OGLG_RIGHT, OGLG_SCALE, OGLG_ZOOMIN, settings, GLG_settings::visibleArea, GLG_settings::windowHeight, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by leftClick(), middleClick(), and rightClick().
void OpenGLGraph::onMouseHelp (wxCommandEvent & event)
Definition at line 1570 of file OpenGLGraph.cpp.
Referenced by SetInfoMessage().
void OpenGLGraph::OnMouseMove (int X, int Y)
Handles mouse moving events.
Parameters
X x coordinate of mouse pointer inside graph window
Y y coordinate of mouse pointer inside graph window
Given mouse coordinates (0,0) are at top left corner of window
Definition at line 990 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, GLG_settings::dataViewWidth, isInsideDataView(), m_actionState, m_lastSpanX, m_lastSpanY, m_MouseCoord, m_selectedMarker, MoveMarker(), OGLG_IDLE, OGLG_MOVE_MARKER, OGLG_PAN, OGLG_SCALE, OGLG_ZOOMIN, Pan(), settings, GLG_settings::visibleArea, GLG_settings::windowHeight, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, sRect< T >::y2, and Zoom().
Referenced by mouseMoved().
void OpenGLGraph::OnMouseUp (int mouseButton, int X, int Y)
Handles mouse button releasing events.
Parameters
mouseButton mouse button code
X x coordinate of mouse pointer inside graph window
Y y coordinate of mouse pointer inside graph window
Given mouse coordinates (0,0) are at top left corner of window
Definition at line 946 of file OpenGLGraph.cpp.
References isInsideDataView(), m_actionState, m_MouseCoord, OGLG_IDLE, OGLG_LEFT, OGLG_MIDDLE, OGLG_RIGHT, OGLG_ZOOMIN, ResetView(), ShowMenu(), sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, sRect< T >::y2, and ZoomRect().
Referenced by mouseReleased().
void OpenGLGraph::onRemoveMarker (wxCommandEvent & event)
Definition at line 1584 of file OpenGLGraph.cpp.
References RemoveMarker().
Referenced by SetInfoMessage().
void OpenGLGraph::onReset (wxCommandEvent & event)
Definition at line 1628 of file OpenGLGraph.cpp.
References ResetView().
Referenced by SetInfoMessage().
void OpenGLGraph::onSearchPeak (wxCommandEvent & event)
Definition at line 1621 of file OpenGLGraph.cpp.
References mMarkersDlg, dlgMarkers::refreshMarkFreq, and SearchPeak().
Referenced by SetInfoMessage().
void OpenGLGraph::onShowMarkersMenu (wxCommandEvent & event)
Definition at line 1590 of file OpenGLGraph.cpp.
References m_timer, mMarkersDlg, and dlgMarkers::refreshMarkFreq.
Referenced by SetInfoMessage().
void OpenGLGraph::OnTimer (wxTimerEvent & event)
Definition at line 1698 of file OpenGLGraph.cpp.
References mMarkersDlg, UpdateInfoDisplay(), and dlgMarkers::UpdateValues().
Referenced by SetInfoMessage().
void OpenGLGraph::Pan (float dx, float dy)
Moves visible data area by set amount of pixels.
Parameters
dx number of pixels to move on the x axis
dy number of pixels to move on the y axis
Definition at line 333 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, GLG_settings::dataViewWidth, settings, SettingsChanged(), GLG_settings::visibleArea, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by OnMouseMove().
void OpenGLGraph::RemoveMarker ()
Removes last added marker.
Definition at line 1231 of file OpenGLGraph.cpp.
References i, and markers.
Referenced by onRemoveMarker().
void OpenGLGraph::RemoveMarker (int id)
Definition at line 1242 of file OpenGLGraph.cpp.
References i, and markers.
void OpenGLGraph::RemoveSeries (unsigned int i)
Removes data serie from graph.
Parameters
i index of data serie
Definition at line 203 of file OpenGLGraph.cpp.
References i, and series.
void OpenGLGraph::render (wxPaintEvent & evt)
Definition at line 1508 of file OpenGLGraph.cpp.
References Draw().
Referenced by SetInfoMessage().
void OpenGLGraph::ResetView ()
Resets displayed area to initial area.
Definition at line 849 of file OpenGLGraph.cpp.
References initialDisplayArea, SetDisplayArea(), sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by OnMouseUp(), and onReset().
void OpenGLGraph::Resize (int w, int h)
Changes graph view size.
Parameters
w window width
h window height
Definition at line 175 of file OpenGLGraph.cpp.
References GLG_settings::dataViewHeight, GLG_settings::dataViewWidth, h, GLG_settings::marginBottom, GLG_settings::marginLeft, GLG_settings::marginRight, GLG_settings::marginTop, settings, SettingsChanged(), GLG_settings::windowHeight, and GLG_settings::windowWidth.
Referenced by Initialize(), and resized().
void OpenGLGraph::resized (wxSizeEvent & evt)
Definition at line 1513 of file OpenGLGraph.cpp.
References Resize().
Referenced by SetInfoMessage().
void OpenGLGraph::rightClick (wxMouseEvent & event)
Definition at line 1540 of file OpenGLGraph.cpp.
References OGLG_RIGHT, and OnMouseDown().
Referenced by SetInfoMessage().
bool OpenGLGraph::SaveConfig (char * file)
Definition at line 768 of file OpenGLGraph.cpp.
bool OpenGLGraph::SearchPeak ()
Definition at line 1634 of file OpenGLGraph.cpp.
References AddMarkerAtValue(), i, and series.
Referenced by onSearchPeak().
void OpenGLGraph::SetDisplayArea (float minx, float maxx, float miny, float maxy)
Sets visible area.
Parameters
minx minimal x value
maxx maximum x value
miny minimum y value
maxy maximum y value
Definition at line 229 of file OpenGLGraph.cpp.
References sRect< T >::set(), settings, SettingsChanged(), and GLG_settings::visibleArea.
Referenced by Fit(), ResetView(), SetInitialDisplayArea(), Zoom(), ZoomRect(), ZoomX(), and ZoomY().
void OpenGLGraph::SetDrawingMode (eDrawingMode mode)
Sets drawing mode (GLG_POINTS, GLG_LINE)
Definition at line 350 of file OpenGLGraph.cpp.
References GLG_settings::graphType, mode, and settings.
Referenced by fftviewer_frFFTviewer::fftviewer_frFFTviewer().
void OpenGLGraph::SetInfoMessage (const char * msg, unsigned int index)
Definition at line 1712 of file OpenGLGraph.cpp.
References info_msg, leftClick(), middleClick(), mouseLeftWindow(), mouseMoved(), mouseReleased(), mouseWheelMoved(), OGLG_ADD_MARK, OGLG_FIT, OGLG_HELP_MOUSE, OGLG_LOCKASPECT, OGLG_REMOVE_MARKER, OGLG_RESET, OGLG_SEARCH_PEAK, OGLG_SHOW_MARKERS_MENU, onAddMarker(), onFit(), onLockAspect(), onMouseHelp(), onRemoveMarker(), onReset(), onSearchPeak(), onShowMarkersMenu(), OnTimer(), render(), resized(), and rightClick().
void OpenGLGraph::SetInitialDisplayArea (float minx, float maxx, float miny, float maxy)
Sets initialy displayed data area, when resetting zoom it will be reset to this area.
Parameters
minx minimal x value
maxx maximum x value
miny minimum y value
maxy maximum y value
Definition at line 216 of file OpenGLGraph.cpp.
References initialDisplayArea, sRect< T >::set(), and SetDisplayArea().
Referenced by fftviewer_frFFTviewer::fftviewer_frFFTviewer(), fftviewer_frFFTviewer::OnFmtChange(), and fftviewer_frFFTviewer::SetNyquistFrequency().
void OpenGLGraph::SetMarker (int id, float xValue, bool enabled, bool show)
Definition at line 1677 of file OpenGLGraph.cpp.
References ChangeMarker(), enabled, id, and markers.
Referenced by dlgMarkers::OnMarkerChange().
void OpenGLGraph::SettingsChanged ()
Signals that settings have changed and needs to be reevaluated.
Definition at line 780 of file OpenGLGraph.cpp.
References viewChanged.
Referenced by CalculateGrid(), Pan(), Resize(), and SetDisplayArea().
void OpenGLGraph::setupViewport (int w, int h) private
Definition at line 1494 of file OpenGLGraph.cpp.
References GL_DEPTH_TEST, GL_MODELVIEW, GL_PROJECTION, glClearColor(), glEnable(), glLoadIdentity(), glMatrixMode(), glOrtho(), and glViewport().
Referenced by Draw(), and OpenGLGraph().
void OpenGLGraph::ShowMenu (int x, int y) private
Definition at line 1603 of file OpenGLGraph.cpp.
References m_popmenu, GLG_settings::markersEnabled, OGLG_ADD_MARK, OGLG_REMOVE_MARKER, OGLG_SEARCH_PEAK, OGLG_SHOW_MARKERS_MENU, and settings.
Referenced by OnMouseUp().
void OpenGLGraph::switchToDataView () private
changes Opengl viewport area to data view region and changes scale
Definition at line 800 of file OpenGLGraph.cpp.
References GL_MODELVIEW, GL_PROJECTION, glLoadIdentity(), glMatrixMode(), glOrtho(), glViewport(), GLG_settings::marginBottom, GLG_settings::marginLeft, GLG_settings::marginRight, GLG_settings::marginTop, settings, GLG_settings::visibleArea, GLG_settings::windowHeight, GLG_settings::windowWidth, sRect< T >::x1, sRect< T >::x2, sRect< T >::y1, and sRect< T >::y2.
Referenced by Draw(), and DrawStaticElements().
void OpenGLGraph::switchToWindowView () private
Changes Opengl viewport area to whole window.
Definition at line 788 of file OpenGLGraph.cpp.
References GL_MODELVIEW, GL_PROJECTION, glLoadIdentity(), glMatrixMode(), glOrtho(), glViewport(), settings, GLG_settings::windowHeight, and GLG_settings::windowWidth.
Referenced by Draw(), DrawMarkers(), and DrawStaticElements().
int OpenGLGraph::TextWidthInPixels (const char * str) private
Returns text string width in pixels.
Parameters
*std pointer to char array
fontSize font heigth in pixels
Definition at line 1088 of file OpenGLGraph.cpp.
References m_font, and GLFont::string_width().
Referenced by NumberWidthInPixels().
void OpenGLGraph::UpdateInfoDisplay () private
Definition at line 1704 of file OpenGLGraph.cpp.
References i, info_msg, and info_msg_toDisplay.
Referenced by OnTimer().
void OpenGLGraph::Zoom (float centerX, float centerY, float spanX, float spanY)
Changes X and Y axis center and span values.
Parameters
centerX X axis value that will be in the center of the window
centerY Y axis value that will be in the center of the window
spanX X axis span around center value
spanY Y axis span around center value
Definition at line 273 of file OpenGLGraph.cpp.
References GLG_settings::lock_aspect, SetDisplayArea(), and settings.
Referenced by OnMouseMove().
void OpenGLGraph::ZoomRect (int x1, int x2, int y1, int y2)
Zooms in area selected by window pixels.
Parameters
x1 first corner x pixel coordinate
x2 second corner x pixel coordinate
y1 first corner y pixel coordinate
y2 second corner y pixel coordinate
Coordinates (0;0) are at the lower left corner
Definition at line 300 of file OpenGLGraph.cpp.
References dataViewPixelToValue(), GLG_settings::marginBottom, GLG_settings::marginLeft, SetDisplayArea(), settings, and temp.
Referenced by OnMouseUp().
void OpenGLGraph::ZoomX (float centerX, float spanX)
Changes X axis center and span values.
Parameters
centerX X axis value that will be in the center of the window
spanX X axis span around center value
Definition at line 258 of file OpenGLGraph.cpp.
References SetDisplayArea(), settings, GLG_settings::visibleArea, sRect< T >::y1, and sRect< T >::y2.
void OpenGLGraph::ZoomY (float centerY, float spanY)
Changes Y axis center and span values.
Parameters
centerY Y axis value that will be in the center of the window
spanY Y axis span around center value
Definition at line 245 of file OpenGLGraph.cpp.
References SetDisplayArea(), settings, GLG_settings::visibleArea, sRect< T >::x1, and sRect< T >::x2.
Friends And Related Function Documentation
friend class dlgMarkers friend
Definition at line 283 of file OpenGLGraph.h.
Referenced by OpenGLGraph().
Member Data Documentation
const int OpenGLGraph::GLCanvasAttributes static
Initial value:
= {
    WX_GL_RGBA,
    WX_GL_DOUBLEBUFFER,
    WX_GL_DEPTH_SIZE, 16,
    WX_GL_STENCIL_SIZE, 0,
    0, 0 }
Definition at line 285 of file OpenGLGraph.h.
bool OpenGLGraph::glInitialized private
Definition at line 358 of file OpenGLGraph.h.
std::vector<std::string> OpenGLGraph::info_msg private
Definition at line 360 of file OpenGLGraph.h.
Referenced by OpenGLGraph(), SetInfoMessage(), and UpdateInfoDisplay().
std::vector<std::string> OpenGLGraph::info_msg_toDisplay private
Definition at line 361 of file OpenGLGraph.h.
Referenced by Draw(), OpenGLGraph(), and UpdateInfoDisplay().
sRect<float> OpenGLGraph::initialDisplayArea private
Definition at line 373 of file OpenGLGraph.h.
Referenced by ResetView(), and SetInitialDisplayArea().
bool OpenGLGraph::initialized private
Definition at line 372 of file OpenGLGraph.h.
Referenced by Draw(), Initialize(), and OpenGLGraph().
eOGLGActionState OpenGLGraph::m_actionState private
Definition at line 369 of file OpenGLGraph.h.
Referenced by Draw(), OnMouseDown(), OnMouseMove(), OnMouseUp(), and OpenGLGraph().
bool OpenGLGraph::m_currentlyDrawing private
Definition at line 402 of file OpenGLGraph.h.
wxGLContext* OpenGLGraph::m_DrawingContext private
Definition at line 368 of file OpenGLGraph.h.
GLFont* OpenGLGraph::m_font private
Definition at line 395 of file OpenGLGraph.h.
Referenced by CalculateGrid(), DrawMarkers(), DrawStaticElements(), glRenderText(), Initialize(), LineHeight(), OpenGLGraph(), TextWidthInPixels(), and ~OpenGLGraph().
wxGLContext* OpenGLGraph::m_glContext private
Definition at line 404 of file OpenGLGraph.h.
Referenced by Draw(), and OpenGLGraph().
float OpenGLGraph::m_lastSpanX private
Definition at line 375 of file OpenGLGraph.h.
Referenced by OnMouseDown(), and OnMouseMove().
float OpenGLGraph::m_lastSpanY private
Definition at line 376 of file OpenGLGraph.h.
Referenced by OnMouseDown(), and OnMouseMove().
unsigned OpenGLGraph::m_maxMarkers private
Definition at line 399 of file OpenGLGraph.h.
Referenced by OpenGLGraph().
sRect<int> OpenGLGraph::m_MouseCoord private
Definition at line 374 of file OpenGLGraph.h.
Referenced by Draw(), onAddMarker(), OnMouseDown(), OnMouseMove(), and OnMouseUp().
wxMenu OpenGLGraph::m_popmenu private
Definition at line 366 of file OpenGLGraph.h.
Referenced by OpenGLGraph(), and ShowMenu().
int OpenGLGraph::m_selectedMarker private
Definition at line 398 of file OpenGLGraph.h.
Referenced by OnMouseDown(), OnMouseMove(), and OpenGLGraph().
wxTimer* OpenGLGraph::m_timer private
Definition at line 403 of file OpenGLGraph.h.
Referenced by onShowMarkersMenu(), OpenGLGraph(), and ~OpenGLGraph().
std::vector<OGLMarker> OpenGLGraph::markers private
Definition at line 397 of file OpenGLGraph.h.
Referenced by dlgMarkers::AddDeltas(), dlgMarkers::AddMarker(), AddMarker(), AddMarkerAtValue(), ChangeMarker(), clickedOnMarker(), DrawMarkers(), GetMarker(), MoveMarker(), OpenGLGraph(), RemoveMarker(), SetMarker(), and dlgMarkers::UpdateValues().
const unsigned int OpenGLGraph::mMarkerColors = {0x000000FF, 0x0000FFFF, 0xFF0000FF, 0xFF7F00FF, 0x007FFFFF, 0xFF00FFFF, 0x007F00FF, 0x00007FFF, 0x7F0000FF, 0x00FF00FF} static private
Definition at line 362 of file OpenGLGraph.h.
Referenced by AddMarker(), AddMarkerAtValue(), DrawMarkers(), and OpenGLGraph().
dlgMarkers* OpenGLGraph::mMarkersDlg private
Definition at line 364 of file OpenGLGraph.h.
Referenced by AddMarkerAtValue(), MoveMarker(), onSearchPeak(), onShowMarkersMenu(), OnTimer(), and OpenGLGraph().
bool OpenGLGraph::oglOk private
Definition at line 357 of file OpenGLGraph.h.
Referenced by Draw(), and Initialize().
std::vector<cDataSerie*> OpenGLGraph::series
Definition at line 310 of file OpenGLGraph.h.
Referenced by AddMarker(), AddMarkerAtValue(), AddSerie(), ChangeMarker(), clickedOnMarker(), Draw(), DrawMarkers(), fftviewer_frFFTviewer::fftviewer_frFFTviewer(), Fit(), MoveMarker(), fftviewer_frFFTviewer::OnChannelVisibilityChange(), fftviewer_frFFTviewer::OnUpdatePlots(), RemoveSeries(), SearchPeak(), and dlgMarkers::UpdateValues().
GLG_settings OpenGLGraph::settings
Definition at line 312 of file OpenGLGraph.h.
Referenced by AddMarker(), CalculateGrid(), clickedOnMarker(), top_block.top_block::closeEvent(), dataViewPixelToValue(), Draw(), DrawMarkers(), DrawStaticElements(), fftviewer_frFFTviewer::fftviewer_frFFTviewer(), Initialize(), isInsideDataView(), MoveMarker(), onLockAspect(), OnMouseDown(), OnMouseMove(), OpenGLGraph(), Pan(), Resize(), SetDisplayArea(), SetDrawingMode(), ShowMenu(), switchToDataView(), switchToWindowView(), Zoom(), ZoomRect(), ZoomX(), and ZoomY().
bool OpenGLGraph::viewChanged private
Definition at line 371 of file OpenGLGraph.h.
Referenced by DrawStaticElements(), Initialize(), and SettingsChanged().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/oglGraph/OpenGLGraph.h
/home/erik/prefix/default/src/limesuite-dev/src/oglGraph/OpenGLGraph.cpp