LimeSuite-UML: lime::Streamer Class Reference
lime::Streamer Class Reference
#include <Streamer.h>
Public Member Functions
Streamer (FPGA *f, LMS7002M *chip, int id)
~Streamer ()
StreamChannel * SetupStream (const StreamConfig &config)
int GetStreamSize (bool tx)
uint64_t GetHardwareTimestamp (void)
void SetHardwareTimestamp (const uint64_t now)
uint64_t GetChirpTimePeriod (void)
uint64_t GetChirpTimeStamp (void)
int UpdateThreads (bool stopAll=false)
void ReceivePacketsLoop ()
Function dedicated for receiving data samples from board.
void TransmitPacketsLoop ()
Public Attributes
std::atomic< uint32_t > rxDataRate_Bps
std::atomic< uint32_t > txDataRate_Bps
IConnection * dataPort
std::thread rxThread
std::thread txThread
std::atomic< bool > terminateRx
std::atomic< bool > terminateTx
std::vector< StreamChannel > mRxStreams
std::vector< StreamChannel > mTxStreams
std::atomic< uint64_t > rxLastTimestamp
std::atomic< uint64_t > txLastTimestamp
std::atomic< uint64_t > chirpLastTimeStamp
std::atomic< uint64_t > chirpLastTimePeriod
uint64_t mTimestampOffset
int streamSize
unsigned txBatchSize
unsigned rxBatchSize
StreamConfig::StreamDataFormat dataLinkFormat
Private Member Functions
void AlignRxTSP ()
void AlignRxRF (bool restoreValues)
void AlignQuadrature (bool restoreValues)
void RstRxIQGen ()
double GetPhaseOffset (int bin)
Private Attributes
FPGA * fpga
LMS7002M * lms
int chipId
Detailed Description
Definition at line 127 of file Streamer.h.
Constructor & Destructor Documentation
lime::Streamer::Streamer (FPGA * f, LMS7002M * chip, int id)
Definition at line 156 of file Streamer.cpp.
References chipId, chirpLastTimePeriod, chirpLastTimeStamp, dataPort, fpga, lime::FPGA::GetConnection(), id, lms, mTimestampOffset, rxBatchSize, rxDataRate_Bps, rxLastTimestamp, streamSize, terminateRx, terminateTx, txBatchSize, and txDataRate_Bps.
lime::Streamer::~Streamer ()
Definition at line 177 of file Streamer.cpp.
References rxThread, terminateRx, terminateTx, and txThread.
Member Function Documentation
void lime::Streamer::AlignQuadrature (bool restoreValues) private
Definition at line 496 of file Streamer.cpp.
References lime::LMS7002M::BackupRegisterMap(), lime::LMS7002M::ChA, chipId, dataPort, fpga, freq, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetFrequencySX(), GetPhaseOffset(), lime::LMS7002M::GetSampleRate(), i, lms, LMS7_SEL_PATH_RFE, lime::LMS7002M::LoadDC_REG_IQ(), lime::LMS7002M::RBB, lime::LMS7002M::RestoreRegisterMap(), RstRxIQGen(), lime::LMS7002M::SetDefaults(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SPI_write(), lime::FPGA::StopStreaming(), lime::LMS7002M::TBB, lime::LMS7002M::TRF, val, lime::warning(), and lime::IConnection::WriteRegister().
Referenced by AlignRxRF().
void lime::Streamer::AlignRxRF (bool restoreValues) private
Definition at line 423 of file Streamer.cpp.
References AlignQuadrature(), AlignRxTSP(), lime::LMS7002M::BackupRegisterMap(), lime::LMS7002M::ChA, chipId, dataPort, fpga, lime::LMS7002M::Get_SPI_Reg_bits(), GetPhaseOffset(), lime::LMS7002M::GetSampleRate(), i, lms, LMS7_HBD_OVR_RXTSP, LMS7_PD_FDIV_O_CGEN, lime::LMS7002M::LoadDC_REG_IQ(), lime::LMS7002M::Modify_SPI_Reg_bits(), lime::LMS7002M::RBB, lime::IConnection::ReadRegisters(), lime::LMS7002M::RestoreRegisterMap(), lime::LMS7002M::RFE, lime::LMS7002M::SetDefaults(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SPI_read(), lime::LMS7002M::SPI_write(), lime::FPGA::StopStreaming(), lime::LMS7002M::TBB, lime::LMS7002M::TRF, val, lime::warning(), and lime::IConnection::WriteRegister().
Referenced by UpdateThreads().
void lime::Streamer::AlignRxTSP () private
Definition at line 319 of file Streamer.cpp.
References lime::IConnection::AbortReading(), chipId, dataPort, fpga, i, lime::IConnection::ReadLMS7002MSPI(), lime::IConnection::ReceiveData(), lime::IConnection::ResetStreamBuffers(), lime::FPGA::StartStreaming(), lime::FPGA::StopStreaming(), lime::warning(), lime::IConnection::WriteLMS7002MSPI(), and lime::IConnection::WriteRegister().
Referenced by AlignRxRF().
uint64_t lime::Streamer::GetChirpTimePeriod (void)
Definition at line 259 of file Streamer.cpp.
References chipId, chirpLastTimePeriod, dataPort, fpga, mTimestampOffset, lime::FPGA::ResetTimestamp(), rxThread, lime::FPGA::StopStreaming(), txThread, and lime::IConnection::WriteRegister().
uint64_t lime::Streamer::GetChirpTimeStamp (void)
Definition at line 276 of file Streamer.cpp.
References chipId, chirpLastTimeStamp, dataPort, fpga, mTimestampOffset, lime::FPGA::ResetTimestamp(), rxThread, lime::FPGA::StopStreaming(), txThread, and lime::IConnection::WriteRegister().
uint64_t lime::Streamer::GetHardwareTimestamp (void)
Definition at line 237 of file Streamer.cpp.
References chipId, dataPort, fpga, mTimestampOffset, lime::FPGA::ResetTimestamp(), rxLastTimestamp, rxThread, lime::FPGA::StopStreaming(), txThread, and lime::IConnection::WriteRegister().
double lime::Streamer::GetPhaseOffset (int bin) private
Definition at line 386 of file Streamer.cpp.
References lime::IConnection::AbortReading(), chipId, dataPort, fpga, lime::IConnection::ReceiveData(), lime::IConnection::ResetStreamBuffers(), lime::FPGA::StartStreaming(), lime::FPGA::StopStreaming(), and lime::warning().
Referenced by AlignQuadrature(), and AlignRxRF().
int lime::Streamer::GetStreamSize (bool tx)
Definition at line 223 of file Streamer.cpp.
References lime::StreamConfig::FMT_INT12, i, mRxStreams, mTxStreams, rxBatchSize, lime::samples12InPkt, lime::samples16InPkt, streamSize, and txBatchSize.
Referenced by lime::StreamChannel::GetStreamSize().
void lime::Streamer::ReceivePacketsLoop ()
Function dedicated for receiving data samples from board.
Parameters
stream a pointer to an active receiver stream
Definition at line 818 of file Streamer.cpp.
References lime::IConnection::AbortReading(), lime::IConnection::BeginDataReading(), c, chCount, lime::IConnection::CheckStreamSize(), chipId, chirpLastTimePeriod, chirpLastTimeStamp, lime::StreamChannel::Metadata::chirptime, lime::FPGA_DataPacket::counter, lime::dataLength, dataLinkFormat, dataPort, lime::error(), lime::IConnection::FinishDataReading(), lime::StreamChannel::Metadata::flags, lime::StreamConfig::FMT_INT12, lime::FPGA::FPGAPacketPayload2Samples(), lime::FPGA_DataPacket::ftr0, lime::FPGA_DataPacket::ftr1, lime::IConnection::GetBuffersCount(), i, ind, lime::StreamChannel::Metadata::lastchirp_timestamp, meta, mRxStreams, mTxStreams, lime::RingFIFO::OVERWRITE_OLD, port, lime::IConnection::ReadRegister(), lime::FPGA_DataPacket::reserved, rxBatchSize, rxDataRate_Bps, rxLastTimestamp, samples, lime::samples12InPkt, lime::samples16InPkt, streamSize, lime::RingFIFO::SYNC_TIMESTAMP, t1, t2, terminateRx, lime::StreamChannel::Metadata::timestamp, lime::IConnection::WaitForReading(), lime::warning(), and lime::IConnection::WriteRegisters().
Referenced by UpdateThreads().
void lime::Streamer::RstRxIQGen () private
Definition at line 293 of file Streamer.cpp.
References chipId, dataPort, lime::IConnection::ReadLMS7002MSPI(), and lime::IConnection::WriteLMS7002MSPI().
Referenced by AlignQuadrature().
void lime::Streamer::SetHardwareTimestamp (const uint64_t now)
Definition at line 254 of file Streamer.cpp.
References mTimestampOffset, and rxLastTimestamp.
StreamChannel * lime::Streamer::SetupStream (const StreamConfig & config)
Definition at line 188 of file Streamer.cpp.
References lime::LMS7002M::ChA, lime::StreamConfig::channelID, lime::error(), lime::LMS7002M::GetSampleRate(), lime::StreamConfig::isTx, lms, mRxStreams, mTxStreams, lime::StreamConfig::performanceLatency, rate, rxBatchSize, rxThread, streamSize, txBatchSize, txThread, UpdateThreads(), and lime::warning().
void lime::Streamer::TransmitPacketsLoop ()
Definition at line 675 of file Streamer.cpp.
References lime::IConnection::AbortSending(), lime::IConnection::BeginDataSending(), c, chCount, lime::IConnection::CheckStreamSize(), chipId, lime::FPGA_DataPacket::counter, dataLinkFormat, dataPort, lime::RingFIFO::END_BURST, lime::error(), lime::IConnection::FinishDataSending(), lime::StreamChannel::Metadata::flags, lime::StreamConfig::FMT_INT12, lime::IConnection::GetBuffersCount(), i, ind, int(), meta, mTxStreams, lime::FPGA_DataPacket::reserved, rxBatchSize, samples, lime::samples12InPkt, lime::samples16InPkt, lime::FPGA::Samples2FPGAPacketPayload(), src, streamSize, lime::RingFIFO::SYNC_TIMESTAMP, t1, t2, terminateTx, lime::StreamChannel::Metadata::timestamp, txDataRate_Bps, txLastTimestamp, lime::IConnection::WaitForSending(), and lime::warning().
Referenced by UpdateThreads().
int lime::Streamer::UpdateThreads (bool stopAll = false)
Definition at line 558 of file Streamer.cpp.
References AlignRxRF(), chipId, dataLinkFormat, dataPort, lime::StreamConfig::FMT_INT12, lime::StreamConfig::FMT_INT16, fpga, lime::LMS7002M::Get_SPI_Reg_bits(), i, lms, LMS7param, mode, mRxStreams, mTxStreams, lime::IConnection::ReadRegister(), ReceivePacketsLoop(), lime::IConnection::ResetStreamBuffers(), lime::FPGA::ResetTimestamp(), rxLastTimestamp, rxThread, lime::FPGA::StartStreaming(), lime::FPGA::StopStreaming(), terminateRx, terminateTx, TransmitPacketsLoop(), txThread, lime::IConnection::WriteRegister(), and lime::IConnection::WriteRegisters().
Referenced by SetupStream(), lime::StreamChannel::Start(), and lime::StreamChannel::Stop().
Member Data Documentation
int lime::Streamer::chipId private
Definition at line 171 of file Streamer.h.
Referenced by AlignQuadrature(), AlignRxRF(), AlignRxTSP(), GetChirpTimePeriod(), GetChirpTimeStamp(), GetHardwareTimestamp(), GetPhaseOffset(), ReceivePacketsLoop(), RstRxIQGen(), Streamer(), TransmitPacketsLoop(), and UpdateThreads().
std::atomic<uint64_t> lime::Streamer::chirpLastTimePeriod
Definition at line 155 of file Streamer.h.
Referenced by GetChirpTimePeriod(), ReceivePacketsLoop(), and Streamer().
std::atomic<uint64_t> lime::Streamer::chirpLastTimeStamp
Definition at line 154 of file Streamer.h.
Referenced by GetChirpTimeStamp(), ReceivePacketsLoop(), and Streamer().
StreamConfig::StreamDataFormat lime::Streamer::dataLinkFormat
Definition at line 160 of file Streamer.h.
Referenced by ReceivePacketsLoop(), TransmitPacketsLoop(), and UpdateThreads().
IConnection* lime::Streamer::dataPort
Definition at line 144 of file Streamer.h.
Referenced by AlignQuadrature(), AlignRxRF(), AlignRxTSP(), GetChirpTimePeriod(), GetChirpTimeStamp(), GetHardwareTimestamp(), GetPhaseOffset(), ReceivePacketsLoop(), RstRxIQGen(), Streamer(), TransmitPacketsLoop(), and UpdateThreads().
FPGA* lime::Streamer::fpga private
Definition at line 169 of file Streamer.h.
Referenced by AlignQuadrature(), AlignRxRF(), AlignRxTSP(), GetChirpTimePeriod(), GetChirpTimeStamp(), GetHardwareTimestamp(), GetPhaseOffset(), Streamer(), and UpdateThreads().
LMS7002M* lime::Streamer::lms private
Definition at line 170 of file Streamer.h.
Referenced by AlignQuadrature(), AlignRxRF(), SetupStream(), Streamer(), and UpdateThreads().
std::vector<StreamChannel> lime::Streamer::mRxStreams
Definition at line 150 of file Streamer.h.
Referenced by GetStreamSize(), ReceivePacketsLoop(), SetupStream(), and UpdateThreads().
uint64_t lime::Streamer::mTimestampOffset
Definition at line 156 of file Streamer.h.
Referenced by GetChirpTimePeriod(), GetChirpTimeStamp(), GetHardwareTimestamp(), SetHardwareTimestamp(), and Streamer().
std::vector<StreamChannel> lime::Streamer::mTxStreams
Definition at line 151 of file Streamer.h.
Referenced by GetStreamSize(), ReceivePacketsLoop(), SetupStream(), TransmitPacketsLoop(), and UpdateThreads().
unsigned lime::Streamer::rxBatchSize
Definition at line 159 of file Streamer.h.
Referenced by GetStreamSize(), ReceivePacketsLoop(), SetupStream(), Streamer(), and TransmitPacketsLoop().
std::atomic<uint32_t> lime::Streamer::rxDataRate_Bps
Definition at line 142 of file Streamer.h.
Referenced by lime::StreamChannel::GetInfo(), ReceivePacketsLoop(), and Streamer().
std::atomic<uint64_t> lime::Streamer::rxLastTimestamp
Definition at line 152 of file Streamer.h.
Referenced by GetHardwareTimestamp(), lime::StreamChannel::GetInfo(), ReceivePacketsLoop(), SetHardwareTimestamp(), Streamer(), and UpdateThreads().
std::thread lime::Streamer::rxThread
Definition at line 145 of file Streamer.h.
Referenced by GetChirpTimePeriod(), GetChirpTimeStamp(), GetHardwareTimestamp(), SetupStream(), UpdateThreads(), and ~Streamer().
int lime::Streamer::streamSize
Definition at line 157 of file Streamer.h.
Referenced by GetStreamSize(), ReceivePacketsLoop(), SetupStream(), Streamer(), and TransmitPacketsLoop().
std::atomic<bool> lime::Streamer::terminateRx
Definition at line 147 of file Streamer.h.
Referenced by ReceivePacketsLoop(), Streamer(), UpdateThreads(), and ~Streamer().
std::atomic<bool> lime::Streamer::terminateTx
Definition at line 148 of file Streamer.h.
Referenced by Streamer(), TransmitPacketsLoop(), UpdateThreads(), and ~Streamer().
unsigned lime::Streamer::txBatchSize
Definition at line 158 of file Streamer.h.
Referenced by GetStreamSize(), SetupStream(), and Streamer().
std::atomic<uint32_t> lime::Streamer::txDataRate_Bps
Definition at line 143 of file Streamer.h.
Referenced by lime::StreamChannel::GetInfo(), Streamer(), and TransmitPacketsLoop().
std::atomic<uint64_t> lime::Streamer::txLastTimestamp
Definition at line 153 of file Streamer.h.
Referenced by lime::StreamChannel::GetInfo(), and TransmitPacketsLoop().
std::thread lime::Streamer::txThread
Definition at line 146 of file Streamer.h.
Referenced by GetChirpTimePeriod(), GetChirpTimeStamp(), GetHardwareTimestamp(), SetupStream(), UpdateThreads(), and ~Streamer().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/protocols/Streamer.h
/home/erik/prefix/default/src/limesuite-dev/src/protocols/Streamer.cpp