LimeSuite-UML: lime::ConnectionFT601 Class Reference
lime::ConnectionFT601 Class Reference
#include <ConnectionFT601.h>
Classes
class USBTransferContext
Wrapper class for holding USB asynchronous transfers contexts.
Public Member Functions
ConnectionFT601 (void *arg)
ConnectionFT601 (void *ctx, const ConnectionHandle &handle)
Initializes port type and object necessary to communicate to usb device.
virtual ~ConnectionFT601 (void)
Closes connection to chip and deallocates used memory.
int Open (const std::string &serial, int vid, int pid)
Tries to open connected USB device and find communication endpoints.
void Close ()
Closes communication to device.
bool IsOpen ()
Returns connection status.
int GetOpenedIndex ()
int Write (const unsigned char *buffer, int length, int timeout_ms=100) override
Sends given data buffer to chip through USB port.
int Read (unsigned char *buffer, int length, int timeout_ms=100) override
Reads data coming from the chip through USB port.
int ProgramWrite (const char *data_src, size_t length, int prog_mode, int device, ProgrammingCallback callback) override
Uploads program to selected device.
DeviceInfo GetDeviceInfo (void) override
Public Member Functions inherited from lime::LMS64CProtocol
LMS64CProtocol (void)
virtual ~LMS64CProtocol (void)
int DeviceReset (int ind=0)
DeviceReset implemented by LMS64C.
int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size) override
TransactSPI implemented by LMS64C.
int WriteI2C (const int addr, const std::string &data)
WriteI2C implemented by LMS64C.
int ReadI2C (const int addr, const size_t numBytes, std::string &data)
ReadI2C implemented by LMS64C.
int WriteRegisters (const uint32_t *addrs, const uint32_t *data, const size_t size)
WriteRegisters (BRDSPI) implemented by LMS64C.
int ReadRegisters (const uint32_t *addrs, uint32_t *data, const size_t size)
ReadRegisters (BRDSPI) implemented by LMS64C.
virtual int TransferPacket (GenericPacket &pkt)
Transfers data between packet and connected device.
LMSinfo GetInfo ()
Returns connected device information.
FPGAinfo GetFPGAInfo ()
Returns information from FPGA gateware.
void VersionCheck ()
int ProgramUpdate (const bool download, IConnection::ProgrammingCallback callback) override
virtual int CustomParameterRead (const uint8_t *ids, double *values, const size_t count, std::string *units) override
Returns value of custom on board control.
virtual int CustomParameterWrite (const uint8_t *ids, const double *values, const size_t count, const std::string &units) override
Sets custom on board control to given value units.
virtual int GPIOWrite (const uint8_t *buffer, const size_t bufLength) override
Writes GPIO values to device.
virtual int GPIORead (uint8_t *buffer, const size_t bufLength) override
Reads GPIO values from device.
virtual int GPIODirWrite (const uint8_t *buffer, const size_t bufLength) override
Write GPIO direction control values to device.
virtual int GPIODirRead (uint8_t *buffer, const size_t bufLength) override
Read GPIO direction configuration from device.
int ProgramMCU (const uint8_t *buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback) override
Uploads program to MCU.
int WriteLMS7002MSPI (const uint32_t *writeData, size_t size, unsigned periphID=0) override
int ReadLMS7002MSPI (const uint32_t *writeData, uint32_t *readData, size_t size, unsigned periphID=0) override
Public Member Functions inherited from lime::IConnection
IConnection (void)
IConnection constructor.
virtual ~IConnection (void)
IConnection destructor.
const ConnectionHandle & GetHandle (void) const
Get the connection handle that was used to create this connection.
virtual int ReceiveData (char *buffer, int length, int epIndex, int timeout=100)
virtual int SendData (const char *buffer, int length, int epIndex, int timeout=100)
int WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
template<typename ReadType >
int ReadRegister (const uint32_t addr, ReadType &data)
Read a single device register.
void SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Protected Member Functions
int GetBuffersCount () const override
int CheckStreamSize (int size) const override
int BeginDataReading (char *buffer, uint32_t length, int ep) override
Starts asynchronous data reading from board.
bool WaitForReading (int contextHandle, unsigned int timeout_ms) override
Waits for asynchronous data reception.
int FinishDataReading (char *buffer, uint32_t length, int contextHandle) override
Finishes asynchronous data reading from board.
void AbortReading (int ep) override
Aborts reading operations.
int BeginDataSending (const char *buffer, uint32_t length, int ep) override
Starts asynchronous data Sending to board.
bool WaitForSending (int contextHandle, uint32_t timeout_ms) override
Waits for asynchronous data sending.
int FinishDataSending (const char *buffer, uint32_t length, int contextHandle) override
Finishes asynchronous data sending to board.
void AbortSending (int ep) override
Aborts sending operations.
int ResetStreamBuffers () override
Read raw stream data from device streaming port.
eConnectionType GetType (void)
implement in base class
int ReinitPipe (unsigned char ep)
Protected Attributes
USBTransferContext contexts [USB_MAX_CONTEXTS]
USBTransferContext contextsToSend [USB_MAX_CONTEXTS]
bool isConnected
FT_HANDLE mFTHandle
std::mutex mExtraUsbMutex
uint64_t mSerial
Protected Attributes inherited from lime::IConnection
std::function< void(bool, const unsigned char *, const unsigned int)> callback_logData
Static Protected Attributes
static const int USB_MAX_CONTEXTS = 16
static const int streamWrEp = 0x03
static const int streamRdEp = 0x83
static const int ctrlWrEp = 0x02
static const int ctrlRdEp = 0x82
Additional Inherited Members
Public Types inherited from lime::LMS64CProtocol
enum eConnectionType {
CONNECTION_UNDEFINED = -1, COM_PORT = 0, USB_PORT = 1, SPI_PORT = 2,
PCIE_PORT = 3, CONNECTION_TYPES_COUNT
}
Supported connection types.
enum eLMS_PROTOCOL { LMS_PROTOCOL_UNDEFINED = 0, LMS_PROTOCOL_DIGIC, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA }
enum ProgramWriteTarget { HPM, FX3, FPGA, PROGRAM_WRITE_TARGET_COUNT }
Public Types inherited from lime::IConnection
enum MCU_PROG_MODE { RESET = 0, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM }
typedef std::function< bool(int bsent, int btotal, const char *progressMsg)> ProgrammingCallback
Detailed Description
Definition at line 29 of file ConnectionFT601.h.
Constructor & Destructor Documentation
ConnectionFT601::ConnectionFT601 (void * arg)
Definition at line 26 of file ConnectionFT601.cpp.
ConnectionFT601::ConnectionFT601 (void * ctx, const ConnectionHandle & handle)
Initializes port type and object necessary to communicate to usb device.
Definition at line 40 of file ConnectionFT601.cpp.
References lime::ConnectionHandle::addr, lime::error(), and lime::ConnectionHandle::serial.
ConnectionFT601::~ConnectionFT601 (void) virtual
Closes connection to chip and deallocates used memory.
Definition at line 63 of file ConnectionFT601.cpp.
Member Function Documentation
void ConnectionFT601::AbortReading (int ep) override protected virtual
Aborts reading operations.
Reimplemented from lime::IConnection.
Definition at line 530 of file ConnectionFT601.cpp.
References i.
void ConnectionFT601::AbortSending (int ep) override protected virtual
Aborts sending operations.
Reimplemented from lime::IConnection.
Definition at line 674 of file ConnectionFT601.cpp.
References i.
int ConnectionFT601::BeginDataReading (char * buffer, uint32_t length, int ep) override protected virtual
Starts asynchronous data reading from board.
Parameters
*buffer buffer where to store received data
length number of bytes to read
Returns
handle of transfer context
Reimplemented from lime::IConnection.
Definition at line 421 of file ConnectionFT601.cpp.
References lime::error(), FT_IO_PENDING, FT_OK, i, and status.
int ConnectionFT601::BeginDataSending (const char * buffer, uint32_t length, int ep) override protected virtual
Starts asynchronous data Sending to board.
Parameters
*buffer buffer to send
length number of bytes to send
Returns
handle of transfer context
Reimplemented from lime::IConnection.
Definition at line 569 of file ConnectionFT601.cpp.
References lime::error(), FT_IO_PENDING, FT_OK, i, and status.
int ConnectionFT601::CheckStreamSize (int size) const override protected virtual
Reimplemented from lime::IConnection.
Definition at line 410 of file ConnectionFT601.cpp.
void ConnectionFT601::Close (void)
Closes communication to device.
Definition at line 225 of file ConnectionFT601.cpp.
int ConnectionFT601::FinishDataReading (char * buffer, uint32_t length, int contextHandle) override protected virtual
Finishes asynchronous data reading from board.
Parameters
buffer array where to store received data
length number of bytes to read
contextHandle handle of which context to finish
Returns
false failure, true number of bytes received
Reimplemented from lime::IConnection.
Definition at line 502 of file ConnectionFT601.cpp.
References FT_OK.
int ConnectionFT601::FinishDataSending (const char * buffer, uint32_t length, int contextHandle) override protected virtual
Finishes asynchronous data sending to board.
Parameters
buffer array where to store received data
length number of bytes to read
contextHandle handle of which context to finish
Returns
false failure, true number of bytes sent
Reimplemented from lime::IConnection.
Definition at line 646 of file ConnectionFT601.cpp.
References FT_OK.
int ConnectionFT601::GetBuffersCount () const override protected virtual
Reimplemented from lime::IConnection.
Definition at line 405 of file ConnectionFT601.cpp.
DeviceInfo ConnectionFT601::GetDeviceInfo (void) override virtual
Get information about a device for displaying helpful information or for making device-specific decisions.
Reimplemented from lime::LMS64CProtocol.
Definition at line 770 of file ConnectionFT601.cpp.
References lime::DeviceInfo::boardSerialNumber, and info.
int lime::ConnectionFT601::GetOpenedIndex ()
eConnectionType lime::ConnectionFT601::GetType (void) inline protected virtual
implement in base class
Implements lime::LMS64CProtocol.
Definition at line 98 of file ConnectionFT601.h.
References lime::LMS64CProtocol::USB_PORT.
bool ConnectionFT601::IsOpen (void) virtual
Returns connection status.
Returns
1-connection open, 0-connection closed.
Reimplemented from lime::IConnection.
Definition at line 245 of file ConnectionFT601.cpp.
int ConnectionFT601::Open (const std::string & serial, int vid, int pid)
Tries to open connected USB device and find communication endpoints.
Returns
Returns 0-Success, other-EndPoints not found or device didn't connect.
Definition at line 131 of file ConnectionFT601.cpp.
References lime::debug(), lime::error(), FT_FAILED, FT_OK, FT_OPEN_BY_SERIAL_NUMBER, i, and lime::ReportError().
int ConnectionFT601::ProgramWrite (const char * buffer, size_t length, int programmingMode, int index, ProgrammingCallback callback) override virtual
Uploads program to selected device.
Parameters
buffer binary program data
length buffer length
programmingMode to RAM, to FLASH, to EEPROM, etc..
index target device number
callback callback for progress reporting or early termination
Returns
the operation success state
Can be used to program MCU, FPGA, write external on board memory. This could be a quite long operation, use callback to get progress info or to terminate early
Reimplemented from lime::LMS64CProtocol.
Definition at line 730 of file ConnectionFT601.cpp.
References buffer, callback, device, and lime::error().
int ConnectionFT601::Read (unsigned char * buffer, int length, int timeout_ms = 100) override virtual
Reads data coming from the chip through USB port.
Parameters
buffer pointer to array where received data will be copied, array must be big enough to fit received data.
length number of bytes to read from chip.
timeout_ms timeout limit for operation in milliseconds
Returns
number of bytes received.
Implements lime::LMS64CProtocol.
Definition at line 321 of file ConnectionFT601.cpp.
References lime::error(), FT_IO_PENDING, FT_OK, and len.
int ConnectionFT601::ReinitPipe (unsigned char ep) protected
Definition at line 251 of file ConnectionFT601.cpp.
int ConnectionFT601::ResetStreamBuffers () override protected virtual
Read raw stream data from device streaming port.
Parameters
buffer read buffer pointer
length number of bytes to read
epIndex endpoint identifier?
timeout_ms timeout in milliseconds
Reimplemented from lime::IConnection.
Definition at line 704 of file ConnectionFT601.cpp.
References FT_OK.
bool ConnectionFT601::WaitForReading (int contextHandle, unsigned int timeout_ms) override protected virtual
Waits for asynchronous data reception.
Parameters
contextHandle handle of which context data to wait
timeout_ms number of miliseconds to wait
Returns
1-data received, 0-data not received
Reimplemented from lime::IConnection.
Definition at line 470 of file ConnectionFT601.cpp.
References t1, t2, and timeout_ms.
bool ConnectionFT601::WaitForSending (int contextHandle, uint32_t timeout_ms) override protected virtual
Waits for asynchronous data sending.
Parameters
contextHandle handle of which context data to wait
timeout_ms number of miliseconds to wait
Returns
1-data received, 0-data not received
Reimplemented from lime::IConnection.
Definition at line 615 of file ConnectionFT601.cpp.
References t1, t2, and timeout_ms.
int ConnectionFT601::Write (const unsigned char * buffer, int length, int timeout_ms = 100) override virtual
Sends given data buffer to chip through USB port.
Parameters
buffer data buffer, must not be longer than 64 bytes.
length given buffer size.
timeout_ms timeout limit for operation in milliseconds
Returns
number of bytes sent.
Implements lime::LMS64CProtocol.
Definition at line 266 of file ConnectionFT601.cpp.
References FT_IO_PENDING, FT_OK, and len.
Member Data Documentation
USBTransferContext lime::ConnectionFT601::contexts[USB_MAX_CONTEXTS] protected
Definition at line 102 of file ConnectionFT601.h.
USBTransferContext lime::ConnectionFT601::contextsToSend[USB_MAX_CONTEXTS] protected
Definition at line 103 of file ConnectionFT601.h.
const int ConnectionFT601::ctrlRdEp = 0x82 static protected
Definition at line 110 of file ConnectionFT601.h.
const int ConnectionFT601::ctrlWrEp = 0x02 static protected
Definition at line 109 of file ConnectionFT601.h.
bool lime::ConnectionFT601::isConnected protected
Definition at line 105 of file ConnectionFT601.h.
std::mutex lime::ConnectionFT601::mExtraUsbMutex protected
Definition at line 121 of file ConnectionFT601.h.
FT_HANDLE lime::ConnectionFT601::mFTHandle protected
Definition at line 112 of file ConnectionFT601.h.
uint64_t lime::ConnectionFT601::mSerial protected
Definition at line 122 of file ConnectionFT601.h.
const int ConnectionFT601::streamRdEp = 0x83 static protected
Definition at line 108 of file ConnectionFT601.h.
const int ConnectionFT601::streamWrEp = 0x03 static protected
Definition at line 107 of file ConnectionFT601.h.
const int lime::ConnectionFT601::USB_MAX_CONTEXTS = 16 static protected
Definition at line 100 of file ConnectionFT601.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFTDI/ConnectionFT601.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFTDI/ConnectionFT601.cpp