LimeSuite-UML: LMS7002_WXGUI Namespace Reference
LMS7002_WXGUI Namespace Reference
Typedefs
typedef std::pair< int, int > indexValuePair
typedef std::vector< indexValuePair > indexValueMap
Functions
void UpdateControlsByMap (wxPanel *panel, lms_device_t *lmsControl, const std::map< wxWindow *, LMS7Parameter > &wndId2param)
int index2value (int index, const indexValueMap &pairs)
int value2index (int value, const indexValueMap &pairs)
void UpdateTooltips (const std::map< wxWindow *, LMS7Parameter > &wndId2param, bool replace)
Changes given wxWidget controls tooltips to parameter descriptions.
Typedef Documentation
typedef std::vector< indexValuePair > LMS7002_WXGUI::indexValueMap
Definition at line 22 of file lms7002_gui_utilities.h.
typedef std::pair<int, int> LMS7002_WXGUI::indexValuePair
Definition at line 21 of file lms7002_gui_utilities.h.
Function Documentation
int LMS7002_WXGUI::index2value (int index, const indexValueMap & pairs)
Definition at line 106 of file lms7002_gui_utilities.cpp.
References i.
Referenced by lms7002_pnlGains_view::ParameterChangeHandler(), lms7002_pnlTRF_view::ParameterChangeHandler(), lms7002_pnlRFE_view::ParameterChangeHandler(), lms7002_pnlRxTSP_view::ParameterChangeHandler(), and lms7002_pnlTxTSP_view::ParameterChangeHandler().
void LMS7002_WXGUI::UpdateControlsByMap (wxPanel * panel, lms_device_t * lmsControl, const std::map< wxWindow *, LMS7Parameter > & wndId2param)
Definition at line 22 of file lms7002_gui_utilities.cpp.
References lms(), and lime::LMS7_Device::ReadParam().
Referenced by lms7002_pnlAFE_view::UpdateGUI(), lms7002_pnlLDO_view::UpdateGUI(), lms7002_pnlGains_view::UpdateGUI(), lms7002_pnlBIAS_view::UpdateGUI(), lms7002_pnlTRF_view::UpdateGUI(), lms7002_pnlXBUF_view::UpdateGUI(), lms7002_pnlCDS_view::UpdateGUI(), lms7002_pnlBIST_view::UpdateGUI(), lms7002_pnlLimeLightPAD_view::UpdateGUI(), lms7002_pnlRBB_view::UpdateGUI(), lms7002_pnlRFE_view::UpdateGUI(), lms7002_pnlTBB_view::UpdateGUI(), lms7002_pnlCalibrations_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateGUI(), lms7002_pnlCLKGEN_view::UpdateGUI(), lms7002_pnlRxTSP_view::UpdateGUI(), lms7002_pnlSX_view::UpdateGUI(), and lms7002_pnlR3_view::UpdateGUI().
void LMS7002_WXGUI::UpdateTooltips (const std::map< wxWindow *, LMS7Parameter > & wndId2param, bool replace)
Changes given wxWidget controls tooltips to parameter descriptions.
Parameters
wndId2Param wxWidgets controls and LMS parameters pairs
replace Replace all tooltips with new ones, or keep old ones and just add missing ones
Definition at line 126 of file lms7002_gui_utilities.cpp.
Referenced by lms7002_pnlAFE_view::lms7002_pnlAFE_view(), lms7002_pnlBIAS_view::lms7002_pnlBIAS_view(), lms7002_pnlBIST_view::lms7002_pnlBIST_view(), lms7002_pnlCalibrations_view::lms7002_pnlCalibrations_view(), lms7002_pnlCDS_view::lms7002_pnlCDS_view(), lms7002_pnlCLKGEN_view::lms7002_pnlCLKGEN_view(), lms7002_pnlGains_view::lms7002_pnlGains_view(), lms7002_pnlLDO_view::lms7002_pnlLDO_view(), lms7002_pnlLimeLightPAD_view::lms7002_pnlLimeLightPAD_view(), lms7002_pnlR3_view::lms7002_pnlR3_view(), lms7002_pnlRBB_view::lms7002_pnlRBB_view(), lms7002_pnlRFE_view::lms7002_pnlRFE_view(), lms7002_pnlRxTSP_view::lms7002_pnlRxTSP_view(), lms7002_pnlSX_view::lms7002_pnlSX_view(), lms7002_pnlTBB_view::lms7002_pnlTBB_view(), lms7002_pnlTRF_view::lms7002_pnlTRF_view(), lms7002_pnlTxTSP_view::lms7002_pnlTxTSP_view(), and lms7002_pnlXBUF_view::lms7002_pnlXBUF_view().
int LMS7002_WXGUI::value2index (int value, const indexValueMap & pairs)
Definition at line 114 of file lms7002_gui_utilities.cpp.
References i.
Referenced by lms7002_pnlGains_view::UpdateGUI(), lms7002_pnlTRF_view::UpdateGUI(), lms7002_pnlRFE_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateGUI(), and lms7002_pnlRxTSP_view::UpdateGUI().