LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/include/SoapySDR/Types.h File Reference
Types.h File Reference
Misc data type definitions used in the API.
#include <SoapySDR/Config.h>
#include <stddef.h>
Classes
struct SoapySDRRange
Definition for a min/max numeric range.
struct SoapySDRKwargs
Definition for a key/value string map.
struct SoapySDRArgInfo
Definition for argument info.
Enumerations
enum SoapySDRArgInfoType { SOAPY_SDR_ARG_INFO_BOOL, SOAPY_SDR_ARG_INFO_INT, SOAPY_SDR_ARG_INFO_FLOAT, SOAPY_SDR_ARG_INFO_STRING }
Possible data types for argument info.
Functions
SOAPY_SDR_API SoapySDRKwargs SoapySDRKwargs_fromString (const char *markup)
SOAPY_SDR_API char * SoapySDRKwargs_toString (const SoapySDRKwargs *args)
SOAPY_SDR_API void SoapySDRStrings_clear (char ***elems, const size_t length)
SOAPY_SDR_API void SoapySDRKwargs_set (SoapySDRKwargs *args, const char *key, const char *val)
SOAPY_SDR_API const char * SoapySDRKwargs_get (SoapySDRKwargs *args, const char *key)
SOAPY_SDR_API void SoapySDRKwargs_clear (SoapySDRKwargs *args)
SOAPY_SDR_API void SoapySDRKwargsList_clear (SoapySDRKwargs *args, const size_t length)
SOAPY_SDR_API void SoapySDRArgInfo_clear (SoapySDRArgInfo *info)
SOAPY_SDR_API void SoapySDRArgInfoList_clear (SoapySDRArgInfo *info, const size_t length)
Detailed Description
Misc data type definitions used in the API.
Copyright
Copyright (c) 2014-2017 Josh Blum SPDX-License-Identifier: BSL-1.0
Definition in file Types.h.
Enumeration Type Documentation
enum SoapySDRArgInfoType
Possible data types for argument info.
Enumerator
SOAPY_SDR_ARG_INFO_BOOL
SOAPY_SDR_ARG_INFO_INT
SOAPY_SDR_ARG_INFO_FLOAT
SOAPY_SDR_ARG_INFO_STRING
Definition at line 48 of file Types.h.
Function Documentation
SOAPY_SDR_API void SoapySDRArgInfo_clear (SoapySDRArgInfo * info)
Clear the contents of a argument info structure. This frees all the underlying memory and clears the members.
Definition at line 76 of file TypesC.cpp.
References SoapySDRArgInfo::description, SoapySDRArgInfo::key, SoapySDRArgInfo::name, SoapySDRArgInfo::numOptions, SoapySDRArgInfo::optionNames, SoapySDRArgInfo::options, SoapySDRStrings_clear(), SoapySDRArgInfo::units, and SoapySDRArgInfo::value.
Referenced by SoapySDRArgInfoList_clear().
SOAPY_SDR_API void SoapySDRArgInfoList_clear (SoapySDRArgInfo * info, const size_t length)
Clear a list of argument info structures. This frees all the underlying memory and clears the members.
Definition at line 100 of file TypesC.cpp.
References i, and SoapySDRArgInfo_clear().
Referenced by SoapySDR.SoapySDRArgInfoList::clear().
SOAPY_SDR_API void SoapySDRKwargs_clear (SoapySDRKwargs * args)
Clear the contents of a kwargs structure. This frees all the underlying memory and clears the members.
Definition at line 63 of file TypesC.cpp.
References SoapySDRKwargs::keys, SoapySDRKwargs::size, SoapySDRStrings_clear(), and SoapySDRKwargs::vals.
Referenced by SoapySDR.SoapySDRKwargs::clear(), and SoapySDRKwargsList_clear().
SOAPY_SDR_API SoapySDRKwargs SoapySDRKwargs_fromString (const char * markup)
Convert a markup string to a key-value map. The markup format is: "key0=value0, key1=value1"
Definition at line 11 of file TypesC.cpp.
References SoapySDR::KwargsFromString, and toKwargs().
SOAPY_SDR_API const char* SoapySDRKwargs_get (SoapySDRKwargs * args, const char * key)
Get a value given a key in a kwargs structure.
Returns
the string or NULL if not found
Definition at line 51 of file TypesC.cpp.
References i, SoapySDRKwargs::keys, SoapySDRKwargs::size, and SoapySDRKwargs::vals.
SOAPY_SDR_API void SoapySDRKwargs_set (SoapySDRKwargs * args, const char * key, const char * val)
Set a key/value pair in a kwargs structure.
Definition at line 31 of file TypesC.cpp.
References i, SoapySDRKwargs::keys, SoapySDRKwargs::size, and SoapySDRKwargs::vals.
Referenced by toKwargs().
SOAPY_SDR_API char* SoapySDRKwargs_toString (const SoapySDRKwargs * args)
Convert a key-value map to a markup string. The markup format is: "key0=value0, key1=value1"
Definition at line 16 of file TypesC.cpp.
References SoapySDR::KwargsToString, and toKwargs().
SOAPY_SDR_API void SoapySDRKwargsList_clear (SoapySDRKwargs * args, const size_t length)
Clear a list of kwargs structures. This frees all the underlying memory and clears the members.
Definition at line 70 of file TypesC.cpp.
References i, and SoapySDRKwargs_clear().
Referenced by SoapySDR.SoapySDRKwargsList::clear().
SOAPY_SDR_API void SoapySDRStrings_clear (char *** elems, const size_t length)
Clear the contents of a list of string Convenience call to deal with results that return a string list.
Definition at line 21 of file TypesC.cpp.
References i.
Referenced by SoapySDRArgInfo_clear(), and SoapySDRKwargs_clear().