LimeSuite-UML: lms7002_pnlCLKGEN_view Class Reference
lms7002_pnlCLKGEN_view Class Reference
Implementing pnlCLKGEN_view.
#include <lms7002_pnlCLKGEN_view.h>
Public Member Functions
void onbtnCalculateClick (wxCommandEvent &event)
void onbtnCalculateClick (wxSpinEvent &event)
void OnAutoPhase (wxCommandEvent &event)
lms7002_pnlCLKGEN_view (wxWindow *parent)
Constructor.
lms7002_pnlCLKGEN_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
void UpdateInterfaceFrequencies ()
Public Member Functions inherited from pnlCLKGEN_view
pnlCLKGEN_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlCLKGEN_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void ParameterChangeHandler (wxSpinEvent &event)
void onbtnTuneClick (wxCommandEvent &event)
void OnbtnReadComparators (wxCommandEvent &event)
void OnbtnUpdateCoarse (wxCommandEvent &event)
void OnShowVCOclicked (wxCommandEvent &event)
void UpdateCLKL ()
Protected Attributes
wxComboBox * cmbCMPLO_CTRL
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlCLKGEN_view
wxCheckBox * chkPD_CP_CGEN
wxCheckBox * chkPD_FDIV_FB_CGEN
wxCheckBox * chkPD_FDIV_O_CGEN
wxCheckBox * chkPD_SDM_CGEN
wxCheckBox * chkPD_VCO_CGEN
wxCheckBox * chkPD_VCO_COMP_CGEN
wxCheckBox * chkEN_G_CGEN
wxCheckBox * chkSPDUP_VCO_CGEN
wxCheckBox * chkRESET_N_CGEN
wxCheckBox * chkEN_COARSE_CKLGEN
wxCheckBox * chkEN_INTONLY_SDM_CGEN
wxCheckBox * chkEN_SDM_CLK_CGEN
wxCheckBox * chkREV_SDMCLK_CGEN
wxCheckBox * chkSX_DITHER_EN_CGEN
wxCheckBox * chkREV_CLKDAC_CGEN
wxCheckBox * chkREV_CLKADC_CGEN
wxCheckBox * chkREVPH_PFD_CGEN
wxCheckBox * chkCOARSE_START_CGEN
wxRadioBox * rgrSEL_SDMCLK_CGEN
wxStaticText * ID_STATICTEXT4
wxComboBox * cmbTST_CGEN
wxStaticText * ID_STATICTEXT13
wxComboBox * cmbCP2_CGEN
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbCP3_CGEN
wxStaticText * ID_STATICTEXT15
wxComboBox * cmbCZ_CGEN
wxRadioBox * cmbEN_ADCCLKH_CLKGN
wxStaticText * m_staticText369
wxStaticText * lblRxTSPfreq
wxStaticText * m_staticText367
wxStaticText * lblTxTSPfreq
wxStaticText * ID_STATICTEXT10
wxStaticText * ID_STATICTEXT18
wxStaticText * ID_STATICTEXT3
wxTextCtrl * txtFrequency
wxComboBox * cmbCLKH_OV_CLKL_CGEN
wxTextCtrl * txtFrequencyCLKL
wxStaticText * ID_STATICTEXT101
wxStaticText * ID_STATICTEXT102
wxCheckBox * chkAutoPhase
wxButton * btnCalculate
wxButton * btnTune
wxStaticText * ID_STATICTEXT7
wxStaticText * lblINT_SDM_CGEN
wxStaticText * ID_STATICTEXT23
wxStaticText * lblRefClk_MHz
wxStaticText * ID_STATICTEXT21
wxStaticText * lblFRAC_SDM_CGEN
wxStaticText * ID_STATICTEXT2
wxStaticText * lblDivider
wxStaticText * ID_STATICTEXT25
wxStaticText * lblRealOutFrequency
wxStaticText * ID_STATICTEXT161
wxStaticText * lblVCO_CMPHO_CGEN
wxStaticText * ID_STATICTEXT171
wxStaticText * lblVCO_CMPLO_CGEN
wxButton * btnUpdateValues1
wxStaticText * ID_STATICTEXT5
wxStaticText * lblCOARSE_STEPDONE_CGEN
wxStaticText * ID_STATICTEXT6
wxStaticText * lblCOARSEPLL_COMPO_CGEN
wxButton * btnUpdateCoarse
wxStaticText * ID_STATICTEXT20
NumericSlider * cmbCSW_VCO_CGEN
wxStaticText * ID_STATICTEXT9
NumericSlider * cmbICT_VCO_CGEN
wxButton * btnShowVCO
wxStaticText * ID_STATICTEXT16
NumericSlider * cmbIOFFSET_CP_CGEN
wxStaticText * ID_STATICTEXT17
NumericSlider * cmbIPULSE_CP_CGEN
wxFlexGridSizer * sizerR3
Additional Inherited Members
Public Attributes inherited from pnlCLKGEN_view
wxSpinCtrl * rxPhase
wxSpinCtrl * txPhase
Protected Types inherited from pnlCLKGEN_view
enum {
ID_PD_CP_CGEN = 2048, ID_PD_FDIV_FB_CGEN, ID_PD_FDIV_O_CGEN, ID_PD_SDM_CGEN,
ID_PD_VCO_CGEN, ID_PD_VCO_COMP_CGEN, ID_EN_G_CGEN, ID_SPDUP_VCO_CGEN,
ID_RESET_N_CGEN, ID_EN_COARSE_CKLGEN, ID_EN_INTONLY_SDM_CGEN, ID_EN_SDM_CLK_CGEN,
ID_REV_SDMCLK_CGEN, ID_SX_DITHER_EN_CGEN, ID_REV_CLKDAC_CGEN, ID_REV_CLKADC_CGEN,
ID_REVPH_PFD_CGEN, ID_COARSE_START_CGEN, ID_SEL_SDMCLK_CGEN, ID_TST_CGEN,
ID_CP2_CGEN, ID_CP3_CGEN, ID_CZ_CGEN, ID_EN_ADCCLKH_CLKGN,
ID_CLKH_OV_CLKL_CGEN, ID_GFIR1_N_TXTSP, ID_AUTO_PHASE, ID_INT_SDM_CGEN,
ID_FRAC_SDM_CGEN, ID_VCO_CMPHO_CGEN, ID_VCO_CMPLO_CGEN, ID_COARSE_STEPDONE_CGEN,
ID_COARSEPLL_COMPO_CGEN, ID_CSW_VCO_CGEN, ID_ICT_VCO_CGEN, ID_IOFFSET_CP_CGEN,
ID_IPULSE_CP_CGEN
}
Detailed Description
Implementing pnlCLKGEN_view.
Definition at line 17 of file lms7002_pnlCLKGEN_view.h.
Constructor & Destructor Documentation
lms7002_pnlCLKGEN_view::lms7002_pnlCLKGEN_view (wxWindow * parent)
Constructor.
Definition at line 13 of file lms7002_pnlCLKGEN_view.cpp.
lms7002_pnlCLKGEN_view::lms7002_pnlCLKGEN_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 20 of file lms7002_pnlCLKGEN_view.cpp.
References pnlCLKGEN_view::chkCOARSE_START_CGEN, pnlCLKGEN_view::chkEN_COARSE_CKLGEN, pnlCLKGEN_view::chkEN_G_CGEN, pnlCLKGEN_view::chkEN_INTONLY_SDM_CGEN, pnlCLKGEN_view::chkEN_SDM_CLK_CGEN, pnlCLKGEN_view::chkPD_CP_CGEN, pnlCLKGEN_view::chkPD_FDIV_FB_CGEN, pnlCLKGEN_view::chkPD_FDIV_O_CGEN, pnlCLKGEN_view::chkPD_SDM_CGEN, pnlCLKGEN_view::chkPD_VCO_CGEN, pnlCLKGEN_view::chkPD_VCO_COMP_CGEN, pnlCLKGEN_view::chkRESET_N_CGEN, pnlCLKGEN_view::chkREV_CLKADC_CGEN, pnlCLKGEN_view::chkREV_CLKDAC_CGEN, pnlCLKGEN_view::chkREV_SDMCLK_CGEN, pnlCLKGEN_view::chkREVPH_PFD_CGEN, pnlCLKGEN_view::chkSPDUP_VCO_CGEN, pnlCLKGEN_view::chkSX_DITHER_EN_CGEN, CLKH_OV_CLKL_CGEN, pnlCLKGEN_view::cmbCLKH_OV_CLKL_CGEN, cmbCMPLO_CTRL, pnlCLKGEN_view::cmbCP2_CGEN, pnlCLKGEN_view::cmbCP3_CGEN, pnlCLKGEN_view::cmbCSW_VCO_CGEN, pnlCLKGEN_view::cmbCZ_CGEN, pnlCLKGEN_view::cmbEN_ADCCLKH_CLKGN, pnlCLKGEN_view::cmbICT_VCO_CGEN, pnlCLKGEN_view::cmbIOFFSET_CP_CGEN, pnlCLKGEN_view::cmbIPULSE_CP_CGEN, pnlCLKGEN_view::cmbTST_CGEN, COARSE_START_CGEN, CP2_CGEN, CP3_CGEN, CSW_VCO_CGEN, CZ_CGEN, EN_ADCCLKH_CLKGN, EN_COARSE_CKLGEN, EN_G_CGEN, EN_INTONLY_SDM_CGEN, EN_SDM_CLK_CGEN, i, ICT_VCO_CGEN, INT_SDM_CGEN, IOFFSET_CP_CGEN, IPULSE_CP_CGEN, pnlCLKGEN_view::lblINT_SDM_CGEN, LMS7_CMPLO_CTRL_CGEN, LMS7param, ParameterChangeHandler(), PD_CP_CGEN, PD_FDIV_FB_CGEN, PD_FDIV_O_CGEN, PD_SDM_CGEN, PD_VCO_CGEN, PD_VCO_COMP_CGEN, RESET_N_CGEN, REV_CLKADC_CGEN, REV_CLKDAC_CGEN, REV_SDMCLK_CGEN, REVPH_PFD_CGEN, pnlCLKGEN_view::rgrSEL_SDMCLK_CGEN, SEL_SDMCLK_CGEN, pnlCLKGEN_view::sizerR3, SPDUP_VCO_CGEN, SX_DITHER_EN_CGEN, temp, TST_CGEN, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlCLKGEN_view::Initialize (lms_device_t * pControl)
Definition at line 105 of file lms7002_pnlCLKGEN_view.cpp.
References freq, pnlCLKGEN_view::lblRefClk_MHz, LMS_CLOCK_CGEN, LMS_CLOCK_REF, LMS_GetClockFreq(), lmsControl, and pnlCLKGEN_view::txtFrequency.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlCLKGEN_view::OnAutoPhase (wxCommandEvent & event) virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 157 of file lms7002_pnlCLKGEN_view.cpp.
References pnlCLKGEN_view::chkAutoPhase, pnlCLKGEN_view::rxPhase, and pnlCLKGEN_view::txPhase.
void lms7002_pnlCLKGEN_view::onbtnCalculateClick (wxCommandEvent & event) virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 193 of file lms7002_pnlCLKGEN_view.cpp.
References pnlCLKGEN_view::chkAutoPhase, device, freq, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetFrequencyCGEN(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, pnlCLKGEN_view::lblRealOutFrequency, lms(), LMS7param, lmsControl, lime::LOG_LEVEL_INFO, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), pnlCLKGEN_view::rxPhase, lime::LMS7002M::SetInterfaceFrequency(), status, pnlCLKGEN_view::txPhase, pnlCLKGEN_view::txtFrequency, and UpdateGUI().
void lms7002_pnlCLKGEN_view::onbtnCalculateClick (wxSpinEvent & event) virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 164 of file lms7002_pnlCLKGEN_view.cpp.
References device, freq, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetFrequencyCGEN(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, pnlCLKGEN_view::lblRealOutFrequency, lms(), LMS7param, lmsControl, lime::LOG_LEVEL_INFO, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), pnlCLKGEN_view::rxPhase, lime::LMS7002M::SetInterfaceFrequency(), pnlCLKGEN_view::txPhase, pnlCLKGEN_view::txtFrequency, and UpdateGUI().
void lms7002_pnlCLKGEN_view::OnbtnReadComparators (wxCommandEvent & event) protected virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 292 of file lms7002_pnlCLKGEN_view.cpp.
References pnlCLKGEN_view::lblVCO_CMPHO_CGEN, pnlCLKGEN_view::lblVCO_CMPLO_CGEN, LMS7param, LMS_ReadParam(), lmsControl, VCO_CMPHO_CGEN, and VCO_CMPLO_CGEN.
Referenced by onbtnTuneClick(), ParameterChangeHandler(), and UpdateGUI().
void lms7002_pnlCLKGEN_view::onbtnTuneClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 232 of file lms7002_pnlCLKGEN_view.cpp.
References pnlCLKGEN_view::chkAutoPhase, pnlCLKGEN_view::cmbCSW_VCO_CGEN, CSW_VCO_CGEN, device, lime::LMS7002M::Get_SPI_Reg_bits(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, lms(), LMS7param, LMS_ReadParam(), lmsControl, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), OnbtnReadComparators(), pnlCLKGEN_view::rxPhase, NumericSlider::SetValue(), status, lime::LMS7002M::TuneVCO(), pnlCLKGEN_view::txPhase, and lime::LMS7002M::VCO_CGEN.
void lms7002_pnlCLKGEN_view::OnbtnUpdateCoarse (wxCommandEvent & event) protected virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 313 of file lms7002_pnlCLKGEN_view.cpp.
References COARSE_STEPDONE, COARSEPLL_COMPO_CGEN, pnlCLKGEN_view::lblCOARSE_STEPDONE_CGEN, pnlCLKGEN_view::lblCOARSEPLL_COMPO_CGEN, LMS7param, LMS_ReadParam(), and lmsControl.
void lms7002_pnlCLKGEN_view::OnShowVCOclicked (wxCommandEvent & event) protected virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 332 of file lms7002_pnlCLKGEN_view.cpp.
References lmsControl.
void lms7002_pnlCLKGEN_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 125 of file lms7002_pnlCLKGEN_view.cpp.
References pnlCLKGEN_view::cmbCLKH_OV_CLKL_CGEN, pnlCLKGEN_view::cmbCSW_VCO_CGEN, pnlCLKGEN_view::cmbEN_ADCCLKH_CLKGN, LMS_WriteParam(), lmsControl, OnbtnReadComparators(), pnlCLKGEN_view::txtFrequency, pnlCLKGEN_view::txtFrequencyCLKL, UpdateCLKL(), UpdateInterfaceFrequencies(), and wndId2Enum.
Referenced by lms7002_pnlCLKGEN_view(), and ParameterChangeHandler().
void lms7002_pnlCLKGEN_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlCLKGEN_view.
Definition at line 116 of file lms7002_pnlCLKGEN_view.cpp.
References ParameterChangeHandler().
void lms7002_pnlCLKGEN_view::UpdateCLKL () protected
Definition at line 322 of file lms7002_pnlCLKGEN_view.cpp.
References pnlCLKGEN_view::cmbCLKH_OV_CLKL_CGEN, pnlCLKGEN_view::txtFrequency, and pnlCLKGEN_view::txtFrequencyCLKL.
Referenced by ParameterChangeHandler(), and UpdateGUI().
void lms7002_pnlCLKGEN_view::UpdateGUI ()
Definition at line 260 of file lms7002_pnlCLKGEN_view.cpp.
References DIV_OUTCH_CGEN, freq, pnlCLKGEN_view::lblDivider, pnlCLKGEN_view::lblFRAC_SDM_CGEN, pnlCLKGEN_view::lblRealOutFrequency, pnlCLKGEN_view::lblRefClk_MHz, LMS7param, LMS_CLOCK_CGEN, LMS_CLOCK_REF, LMS_GetClockFreq(), LMS_ReadParam(), lmsControl, OnbtnReadComparators(), pnlCLKGEN_view::txtFrequency, UpdateCLKL(), LMS7002_WXGUI::UpdateControlsByMap(), UpdateInterfaceFrequencies(), and wndId2Enum.
Referenced by onbtnCalculateClick(), and lms7002_mainPanel::UpdateVisiblePanel().
void lms7002_pnlCLKGEN_view::UpdateInterfaceFrequencies ()
Definition at line 283 of file lms7002_pnlCLKGEN_view.cpp.
References freq, pnlCLKGEN_view::lblRxTSPfreq, pnlCLKGEN_view::lblTxTSPfreq, LMS_CLOCK_RXTSP, LMS_CLOCK_TXTSP, LMS_GetClockFreq(), and lmsControl.
Referenced by ParameterChangeHandler(), and UpdateGUI().
Member Data Documentation
wxComboBox* lms7002_pnlCLKGEN_view::cmbCMPLO_CTRL protected
Definition at line 28 of file lms7002_pnlCLKGEN_view.h.
Referenced by lms7002_pnlCLKGEN_view().
lms_device_t* lms7002_pnlCLKGEN_view::lmsControl protected
Definition at line 42 of file lms7002_pnlCLKGEN_view.h.
Referenced by Initialize(), onbtnCalculateClick(), OnbtnReadComparators(), onbtnTuneClick(), OnbtnUpdateCoarse(), OnShowVCOclicked(), ParameterChangeHandler(), UpdateGUI(), and UpdateInterfaceFrequencies().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlCLKGEN_view::wndId2Enum protected
Definition at line 43 of file lms7002_pnlCLKGEN_view.h.
Referenced by lms7002_pnlCLKGEN_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlCLKGEN_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlCLKGEN_view.cpp