LimeSuite-UML: BoardLoopbackStore Class Reference
BoardLoopbackStore Class Reference
Public Member Functions
BoardLoopbackStore (lime::IConnection *port)
~BoardLoopbackStore ()
BoardLoopbackStore (lime::IConnection *port)
~BoardLoopbackStore ()
Private Attributes
lime::IConnection * port
int mLoopbackState
Static Private Attributes
static const uint32_t LoopbackCtrAddr = 0x0017
Detailed Description
Definition at line 24 of file LMS7002M_RxTxCalibrations.cpp.
Constructor & Destructor Documentation
BoardLoopbackStore::BoardLoopbackStore (lime::IConnection * port) inline
Definition at line 27 of file LMS7002M_RxTxCalibrations.cpp.
References lime::IConnection::ReadRegister(), and lime::ReportError().
BoardLoopbackStore::~BoardLoopbackStore () inline
Definition at line 32 of file LMS7002M_RxTxCalibrations.cpp.
References port, and lime::ReportError().
BoardLoopbackStore::BoardLoopbackStore (lime::IConnection * port) inline
Definition at line 72 of file main.cpp.
References lime::IConnection::ReadRegister().
BoardLoopbackStore::~BoardLoopbackStore () inline
Definition at line 77 of file main.cpp.
References port.
Member Data Documentation
static const uint32_t BoardLoopbackStore::LoopbackCtrAddr = 0x0017 static private
Definition at line 39 of file LMS7002M_RxTxCalibrations.cpp.
int BoardLoopbackStore::mLoopbackState private
Definition at line 40 of file LMS7002M_RxTxCalibrations.cpp.
lime::IConnection * BoardLoopbackStore::port private
Definition at line 38 of file LMS7002M_RxTxCalibrations.cpp.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_RxTxCalibrations.cpp
/home/erik/prefix/default/src/limesuite-dev/mcu_program/host_src/main.cpp