LimeSuite-UML: lms7002_pnlBIAS_view Class Reference
lms7002_pnlBIAS_view Class Reference
Implementing pnlBIAS_view.
#include <lms7002_pnlBIAS_view.h>
Public Member Functions
lms7002_pnlBIAS_view (wxWindow *parent)
Constructor.
lms7002_pnlBIAS_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlBIAS_view
pnlBIAS_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlBIAS_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void OnCalibrateRP_BIAS (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlBIAS_view
wxCheckBox * chkPD_FRP_BIAS
wxCheckBox * chkPD_F_BIAS
wxCheckBox * chkPD_PTRP_BIAS
wxCheckBox * chkPD_PT_BIAS
wxCheckBox * chkPD_BIAS_MASTER
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbMUX_BIAS_OUT
wxStaticText * ID_STATICTEXT2
wxComboBox * cmbRP_CALIB_BIAS
wxButton * btnCalibrateRP_BIAS
Additional Inherited Members
Protected Types inherited from pnlBIAS_view
enum {
ID_PD_FRP_BIAS = 2048, ID_PD_F_BIAS, ID_PD_PTRP_BIAS, ID_PD_PT_BIAS,
ID_PD_BIAS_MASTER, ID_MUX_BIAS_OUT, ID_RP_CALIB_BIAS
}
Detailed Description
Implementing pnlBIAS_view.
Definition at line 18 of file lms7002_pnlBIAS_view.h.
Constructor & Destructor Documentation
lms7002_pnlBIAS_view::lms7002_pnlBIAS_view (wxWindow * parent)
Constructor.
Definition at line 7 of file lms7002_pnlBIAS_view.cpp.
lms7002_pnlBIAS_view::lms7002_pnlBIAS_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 14 of file lms7002_pnlBIAS_view.cpp.
References pnlBIAS_view::chkPD_BIAS_MASTER, pnlBIAS_view::chkPD_F_BIAS, pnlBIAS_view::chkPD_FRP_BIAS, pnlBIAS_view::chkPD_PT_BIAS, pnlBIAS_view::chkPD_PTRP_BIAS, pnlBIAS_view::cmbMUX_BIAS_OUT, pnlBIAS_view::cmbRP_CALIB_BIAS, i, LMS7param, MUX_BIAS_OUT, PD_BIAS_MASTER, PD_F_BIAS, PD_FRP_BIAS, PD_PT_BIAS, PD_PTRP_BIAS, RP_CALIB_BIAS, temp, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlBIAS_view::Initialize (lms_device_t * pControl)
Definition at line 42 of file lms7002_pnlBIAS_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlBIAS_view::OnCalibrateRP_BIAS (wxCommandEvent & event) protected virtual
Reimplemented from pnlBIAS_view.
Definition at line 69 of file lms7002_pnlBIAS_view.cpp.
References lime::LMS7002M::CalibrateRP_BIAS(), lms(), lmsControl, and UpdateGUI().
void lms7002_pnlBIAS_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlBIAS_view.
Definition at line 48 of file lms7002_pnlBIAS_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlBIAS_view::UpdateGUI ()
Definition at line 64 of file lms7002_pnlBIAS_view.cpp.
References lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by OnCalibrateRP_BIAS(), and lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlBIAS_view::lmsControl protected
Definition at line 32 of file lms7002_pnlBIAS_view.h.
Referenced by Initialize(), OnCalibrateRP_BIAS(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlBIAS_view::wndId2Enum protected
Definition at line 33 of file lms7002_pnlBIAS_view.h.
Referenced by lms7002_pnlBIAS_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlBIAS_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlBIAS_view.cpp