LimeSuite-UML: lime::FPGA Class Reference
lime::FPGA Class Reference
#include <FPGA_common.h>
Classes
struct FPGA_PLL_clock
Public Member Functions
FPGA ()
virtual ~FPGA ()
void SetConnection (IConnection *conn)
IConnection * GetConnection () const
int StartStreaming ()
int StopStreaming ()
int ResetTimestamp ()
virtual int UploadWFM (const void *const *samples, uint8_t chCount, size_t sample_count, StreamConfig::StreamDataFormat format, int epIndex)
virtual int SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, double txPhase, double rxPhase, int ch=0)
Configures FPGA PLLs to LimeLight interface frequency.
virtual int SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, int ch=0)
Configures FPGA PLLs to LimeLight interface frequency.
double DetectRefClk (double fx3Clk=100e6)
Static Public Member Functions
static int FPGAPacketPayload2Samples (const uint8_t *buffer, int bufLen, bool mimo, bool compressed, complex16_t **samples)
Parses FPGA packet payload into samples.
static int Samples2FPGAPacketPayload (const complex16_t *const *samples, int samplesCount, bool mimo, bool compressed, uint8_t *buffer)
Protected Member Functions
int SetPllFrequency (uint8_t pllIndex, double inputFreq, FPGA_PLL_clock *outputs, uint8_t clockCount)
Configures board FPGA clocks.
int SetDirectClocking (int clockIndex)
Protected Attributes
IConnection * connection
Private Member Functions
virtual int ReadRawStreamData (char *buffer, unsigned length, int epIndex, int timeout_ms)
int SetPllClock (int clockIndex, int nSteps, bool waitLock, uint16_t &reg23val)
Detailed Description
Definition at line 17 of file FPGA_common.h.
Constructor & Destructor Documentation
lime::FPGA::FPGA () inline
Definition at line 21 of file FPGA_common.h.
virtual lime::FPGA::~FPGA () inline virtual
Definition at line 22 of file FPGA_common.h.
References chCount, format, sample_count, and samples.
Member Function Documentation
double lime::FPGA::DetectRefClk (double fx3Clk = 100e6)
Definition at line 805 of file FPGA_common.cpp.
References lime::debug(), i, and lime::info().
Referenced by lime::LMS7_Generic::LMS7_Generic(), and lime::LMS7_LimeSDR_mini::LMS7_LimeSDR_mini().
int lime::FPGA::FPGAPacketPayload2Samples (const uint8_t * buffer, int bufLen, bool mimo, bool compressed, complex16_t ** samples) static
Parses FPGA packet payload into samples.
Definition at line 427 of file FPGA_common.cpp.
References b, i, lime::complex16_t::i, and lime::complex16_t::q.
Referenced by lime::Streamer::ReceivePacketsLoop().
IConnection * lime::FPGA::GetConnection () const
Definition at line 39 of file FPGA_common.cpp.
Referenced by lime::Streamer::Streamer().
int lime::FPGA::ReadRawStreamData (char * buffer, unsigned length, int epIndex, int timeout_ms) private virtual
Reimplemented in lime::FPGA_Mini.
Definition at line 791 of file FPGA_common.cpp.
int lime::FPGA::ResetTimestamp ()
Definition at line 66 of file FPGA_common.cpp.
References lime::ReportError(), lime::SMPL_NR_CLR, and status.
Referenced by lime::Streamer::GetChirpTimePeriod(), lime::Streamer::GetChirpTimeStamp(), lime::Streamer::GetHardwareTimestamp(), and lime::Streamer::UpdateThreads().
int lime::FPGA::Samples2FPGAPacketPayload (const complex16_t *const * samples, int samplesCount, bool mimo, bool compressed, uint8_t * buffer) static
Definition at line 476 of file FPGA_common.cpp.
References b, lime::complex16_t::i, lime::complex16_t::q, and src.
Referenced by lime::Streamer::TransmitPacketsLoop().
void lime::FPGA::SetConnection (IConnection * conn)
Definition at line 34 of file FPGA_common.cpp.
Referenced by lime::LMS7_Generic::LMS7_Generic(), lime::LMS7_LimeSDR_mini::LMS7_LimeSDR_mini(), and lime::LMS7_qLimeSDR::LMS7_qLimeSDR().
int lime::FPGA::SetDirectClocking (int clockIndex) protected
Definition at line 405 of file FPGA_common.cpp.
References lime::ReportError().
Referenced by lime::FPGA_Mini::SetInterfaceFreq().
int lime::FPGA::SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, double txPhase, double rxPhase, int ch = 0) virtual
Configures FPGA PLLs to LimeLight interface frequency.
Reimplemented in lime::FPGA_Mini, and lime::FPGA_Q.
Definition at line 603 of file FPGA_common.cpp.
References lime::FPGA::FPGA_PLL_clock::index, lime::FPGA::FPGA_PLL_clock::outFrequency, lime::FPGA::FPGA_PLL_clock::phaseShift_deg, status, and val.
Referenced by lime::LMS7_Device::LoadConfig(), lime::LMS7_Device::SetFPGAInterfaceFreq(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_qLimeSDR::SetRate(), and lime::LMS7_Device::Synchronize().
int lime::FPGA::SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, int ch = 0) virtual
Configures FPGA PLLs to LimeLight interface frequency.
Reimplemented in lime::FPGA_Mini.
Definition at line 644 of file FPGA_common.cpp.
References lime::FPGA::FPGA_PLL_clock::findPhase, i, lime::FPGA::FPGA_PLL_clock::index, k, lime::FPGA::FPGA_PLL_clock::outFrequency, lime::FPGA::FPGA_PLL_clock::phaseShift_deg, status, and val.
int lime::FPGA::SetPllClock (int clockIndex, int nSteps, bool waitLock, uint16_t & reg23val) private
Definition at line 91 of file FPGA_common.cpp.
References lime::PHCFG_MODE, lime::PHCFG_UPDN, lime::ReportError(), t1, and t2.
int lime::FPGA::SetPllFrequency (uint8_t pllIndex, double inputFreq, FPGA_PLL_clock * clocks, uint8_t clockCount) protected
Configures board FPGA clocks.
Parameters
serPort communications port
pllIndex index of FPGA pll
clocks list of clocks to configure
clocksCount number of clocks to configure
Returns
0-success, other-failure
Definition at line 144 of file FPGA_common.cpp.
References coef, lime::debug(), error(), lime::error(), lime::FPGA::FPGA_PLL_clock::findPhase, freq, lime::GetDeviceName(), i, lime::FPGA::FPGA_PLL_clock::index, index, int(), lime::LMS_DEV_LIMESDR_QPCIE, lime::LMS_DEV_UNKNOWN, lime::FPGA::FPGA_PLL_clock::outFrequency, lime::FPGA::FPGA_PLL_clock::phaseShift_deg, lime::PHCFG_MODE, lime::PHCFG_UPDN, lime::FPGA::FPGA_PLL_clock::rd_actualFrequency, lime::ReportError(), t1, and t2.
Referenced by lime::FPGA_Mini::SetInterfaceFreq(), and lime::FPGA_Q::SetInterfaceFreq().
int lime::FPGA::StartStreaming ()
Definition at line 44 of file FPGA_common.cpp.
References lime::RX_EN, and status.
Referenced by lime::Streamer::AlignRxTSP(), lime::Streamer::GetPhaseOffset(), lime::FPGA_Mini::ReadRawStreamData(), and lime::Streamer::UpdateThreads().
int lime::FPGA::StopStreaming ()
Definition at line 55 of file FPGA_common.cpp.
References status, and lime::TX_EN.
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), lime::Streamer::AlignRxTSP(), lime::Streamer::GetChirpTimePeriod(), lime::Streamer::GetChirpTimeStamp(), lime::Streamer::GetHardwareTimestamp(), lime::Streamer::GetPhaseOffset(), lime::FPGA_Mini::ReadRawStreamData(), and lime::Streamer::UpdateThreads().
int lime::FPGA::UploadWFM (const void *const * samples, uint8_t chCount, size_t sample_count, StreamConfig::StreamDataFormat format, int epIndex) virtual
Reimplemented in lime::FPGA_Mini.
Definition at line 510 of file FPGA_common.cpp.
References chCount, lime::FPGA_DataPacket::counter, lime::FPGA_DataPacket::data, i, lime::complex16_t::i, lime::complex16_t::q, lime::ReportError(), lime::FPGA_DataPacket::reserved, sample_count, lime::samples12InPkt, lime::samples16InPkt, src, and lime::warning().
Referenced by lime::LMS7_Device::UploadWFM().
Member Data Documentation
IConnection* lime::FPGA::connection protected
Definition at line 56 of file FPGA_common.h.
Referenced by lime::FPGA_Mini::ReadRawStreamData(), and lime::FPGA_Mini::SetInterfaceFreq().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/FPGA_common/FPGA_common.h
/home/erik/prefix/default/src/limesuite-dev/src/FPGA_common/FPGA_common.cpp