LimeSuite-UML: swig::SwigPyIterator_T< OutIterator > Class Template Reference
swig::SwigPyIterator_T< OutIterator > Class Template Reference
Public Types
typedef OutIterator out_iterator
typedef std::iterator_traits< out_iterator >::value_type value_type
typedef SwigPyIterator_T< out_iterator > self_type
typedef OutIterator out_iterator
typedef std::iterator_traits< out_iterator >::value_type value_type
typedef SwigPyIterator_T< out_iterator > self_type
Public Member Functions
SwigPyIterator_T (out_iterator curr, PyObject *seq)
const out_iterator & get_current () const
bool equal (const SwigPyIterator &iter) const
ptrdiff_t distance (const SwigPyIterator &iter) const
SwigPyIterator_T (out_iterator curr, PyObject *seq)
const out_iterator & get_current () const
bool equal (const SwigPyIterator &iter) const
ptrdiff_t distance (const SwigPyIterator &iter) const
Public Member Functions inherited from swig::SwigPyIterator
virtual ~SwigPyIterator ()
virtual PyObject * value () const =0
virtual SwigPyIterator * incr (size_t n=1)=0
virtual SwigPyIterator * decr (size_t=1)
virtual SwigPyIterator * copy () const =0
PyObject * next ()
PyObject * __next__ ()
PyObject * previous ()
SwigPyIterator * advance (ptrdiff_t n)
bool operator== (const SwigPyIterator &x) const
bool operator!= (const SwigPyIterator &x) const
SwigPyIterator & operator+= (ptrdiff_t n)
SwigPyIterator & operator-= (ptrdiff_t n)
SwigPyIterator * operator+ (ptrdiff_t n) const
SwigPyIterator * operator- (ptrdiff_t n) const
ptrdiff_t operator- (const SwigPyIterator &x) const
virtual ~SwigPyIterator ()
virtual PyObject * value () const =0
virtual SwigPyIterator * incr (size_t n=1)=0
virtual SwigPyIterator * decr (size_t=1)
virtual SwigPyIterator * copy () const =0
PyObject * next ()
PyObject * __next__ ()
PyObject * previous ()
SwigPyIterator * advance (ptrdiff_t n)
bool operator== (const SwigPyIterator &x) const
bool operator!= (const SwigPyIterator &x) const
SwigPyIterator & operator+= (ptrdiff_t n)
SwigPyIterator & operator-= (ptrdiff_t n)
SwigPyIterator * operator+ (ptrdiff_t n) const
SwigPyIterator * operator- (ptrdiff_t n) const
ptrdiff_t operator- (const SwigPyIterator &x) const
Protected Attributes
out_iterator current
Additional Inherited Members
Static Public Member Functions inherited from swig::SwigPyIterator
static swig_type_info * descriptor ()
static swig_type_info * descriptor ()
Protected Member Functions inherited from swig::SwigPyIterator
SwigPyIterator (PyObject *seq)
SwigPyIterator (PyObject *seq)
Detailed Description
template<typename OutIterator>
class swig::SwigPyIterator_T< OutIterator >
Definition at line 4269 of file SoapySDRPYTHON_wrap.cxx.
Member Typedef Documentation
template<typename OutIterator> typedef OutIterator swig::SwigPyIterator_T< OutIterator >::out_iterator
Definition at line 3910 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator> typedef OutIterator swig::SwigPyIterator_T< OutIterator >::out_iterator
Definition at line 4272 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator> typedef SwigPyIterator_T<out_iterator> swig::SwigPyIterator_T< OutIterator >::self_type
Definition at line 3912 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator> typedef SwigPyIterator_T<out_iterator> swig::SwigPyIterator_T< OutIterator >::self_type
Definition at line 4274 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator> typedef std::iterator_traits<out_iterator>::value_type swig::SwigPyIterator_T< OutIterator >::value_type
Definition at line 3911 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator> typedef std::iterator_traits<out_iterator>::value_type swig::SwigPyIterator_T< OutIterator >::value_type
Definition at line 4273 of file SoapySDRPYTHON_wrap.cxx.
Constructor & Destructor Documentation
template<typename OutIterator> swig::SwigPyIterator_T< OutIterator >::SwigPyIterator_T (out_iterator curr, PyObject * seq) inline
Definition at line 4276 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator> swig::SwigPyIterator_T< OutIterator >::SwigPyIterator_T (out_iterator curr, PyObject * seq) inline
Definition at line 3914 of file radar_swigPYTHON_wrap.cxx.
Member Function Documentation
template<typename OutIterator> ptrdiff_t swig::SwigPyIterator_T< OutIterator >::distance (const SwigPyIterator & iter) const inline virtual
Reimplemented from swig::SwigPyIterator.
Definition at line 3935 of file radar_swigPYTHON_wrap.cxx.
References swig::SwigPyIterator_T< OutIterator >::get_current().
template<typename OutIterator> ptrdiff_t swig::SwigPyIterator_T< OutIterator >::distance (const SwigPyIterator & iter) const inline virtual
Reimplemented from swig::SwigPyIterator.
Definition at line 4297 of file SoapySDRPYTHON_wrap.cxx.
References swig::SwigPyIterator_T< OutIterator >::get_current().
template<typename OutIterator> bool swig::SwigPyIterator_T< OutIterator >::equal (const SwigPyIterator & iter) const inline virtual
Reimplemented from swig::SwigPyIterator.
Definition at line 3925 of file radar_swigPYTHON_wrap.cxx.
References swig::SwigPyIterator_T< OutIterator >::get_current().
template<typename OutIterator> bool swig::SwigPyIterator_T< OutIterator >::equal (const SwigPyIterator & iter) const inline virtual
Reimplemented from swig::SwigPyIterator.
Definition at line 4287 of file SoapySDRPYTHON_wrap.cxx.
References swig::SwigPyIterator_T< OutIterator >::get_current().
template<typename OutIterator> const out_iterator& swig::SwigPyIterator_T< OutIterator >::get_current () const inline
Definition at line 3919 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator> const out_iterator& swig::SwigPyIterator_T< OutIterator >::get_current () const inline
Definition at line 4281 of file SoapySDRPYTHON_wrap.cxx.
Referenced by swig::SwigPyIterator_T< OutIterator >::distance(), and swig::SwigPyIterator_T< OutIterator >::equal().
Member Data Documentation
template<typename OutIterator> out_iterator swig::SwigPyIterator_T< OutIterator >::current protected
Definition at line 4308 of file SoapySDRPYTHON_wrap.cxx.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDRPYTHON_wrap.cxx
/home/erik/prefix/default/src/gr-radar-dev/build/swig/radar_swigPYTHON_wrap.cxx