LimeSuite-UML: GLFont Class Reference
GLFont Class Reference
#include <GLFont.h>
Public Member Functions
GLFont ()
~GLFont ()
bool load (const char *file)
loads opengl font file
bool loadFromArray (const char *array, unsigned int size)
void render_textWorldSpace (const char *text, float x, float y, float scale, unsigned int rgba=0x00000000)
void render_textScreenSpace (const char *text, float x, float y, float scale, unsigned int rgba=0x00000000)
unsigned int lineHeight () const
unsigned int char_width (const char c) const
unsigned int string_width (const char *str) const
void getTextSize (const char *str, int &width, int &height, float fontSize)
unsigned int getTextureID ()
Public Attributes
int m_texwidth
int m_texheight
GLuint m_texID
GLuint m_vboID
GLGlyph * m_glyphs
const unsigned short m_glyphCount
unsigned char m_fontSize
Detailed Description
Definition at line 28 of file GLFont.h.
Constructor & Destructor Documentation
GLFont::GLFont ()
Definition at line 9 of file GLFont.cpp.
References m_fontSize, m_glyphCount, and m_glyphs.
GLFont::~GLFont ()
Definition at line 15 of file GLFont.cpp.
References m_glyphs.
Member Function Documentation
unsigned int GLFont::char_width (const char c) const
Definition at line 400 of file GLFont.cpp.
References m_glyphs.
void GLFont::getTextSize (const char * str, int & width, int & height, float fontSize)
Definition at line 413 of file GLFont.cpp.
References i, len, m_fontSize, and m_glyphs.
Referenced by OpenGLGraph::CalculateGrid(), and OpenGLGraph::DrawStaticElements().
unsigned int GLFont::getTextureID () inline
Definition at line 44 of file GLFont.h.
unsigned int GLFont::lineHeight () const
Definition at line 395 of file GLFont.cpp.
References m_fontSize.
Referenced by OpenGLGraph::DrawMarkers(), OpenGLGraph::LineHeight(), render_textScreenSpace(), and render_textWorldSpace().
bool GLFont::load (const char * file)
loads opengl font file
Parameters
file font file to load
Expected file structure: 12 bytes - "OpenGL Font" literal file header 1 byte - file version 16 bytes - reserved 1 byte - font size (max line height in pixels) 2 byte - glyph count glyphCount * 16 bytes - glyph definitions
2 bytes (ushort)- glyph id
2 bytes (ushort)- width
2 bytes (ushort)- height
2 bytes (ushort)- glyph x position in texture
2 bytes (ushort)- glyph y position in texture
2 bytes (short)- glyph x offset
2 bytes (short)- glyph y offset (height above line)
2 bytes (short)- glyph x advance (gap before glyph) 2 bytes - texture width in pixels 2 bytes - texture height in pixels 1 byte - texture bits per pixel (currently hardcoded 8 bits per pixel) width*height*bpp - texture data
Definition at line 44 of file GLFont.cpp.
References GLGlyph::advance_x, GL_ALPHA, GL_ALPHA8, GL_ARRAY_BUFFER, GL_CLAMP_TO_EDGE, GL_DYNAMIC_DRAW, GL_NEAREST, GL_TEXTURE0, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNSIGNED_BYTE, glActiveTexture, glBindBuffer, glBindTexture(), glBufferData, glDeleteTextures(), glEnable(), GLEW_VERSION_1_5, glewInit(), glGenBuffers, glGenTextures(), glTexImage2D(), glTexParameteri(), header, GLGlyph::height, i, GLGlyph::id, m_fontSize, m_glyphCount, m_glyphs, m_texheight, m_texID, m_texwidth, m_vboID, GLGlyph::offset_x, GLGlyph::offset_y, GLGlyph::u, GLGlyph::v, and GLGlyph::width.
bool GLFont::loadFromArray (const char * array, unsigned int size)
Definition at line 136 of file GLFont.cpp.
References GLGlyph::advance_x, GL_ALPHA, GL_ALPHA8, GL_ARRAY_BUFFER, GL_CLAMP_TO_EDGE, GL_DYNAMIC_DRAW, GL_NEAREST, GL_TEXTURE0, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNSIGNED_BYTE, glActiveTexture, glBindBuffer, glBindTexture(), glBufferData, glDeleteTextures(), glEnable(), GLEW_VERSION_1_5, glewInit(), glGenBuffers, glGenTextures(), glTexImage2D(), glTexParameteri(), header, GLGlyph::height, i, GLGlyph::id, m_fontSize, m_glyphCount, m_glyphs, m_texheight, m_texID, m_texwidth, m_vboID, GLGlyph::offset_x, GLGlyph::offset_y, GLGlyph::u, GLGlyph::v, and GLGlyph::width.
Referenced by OpenGLGraph::Initialize().
void GLFont::render_textScreenSpace (const char * text, float x, float y, float scale, unsigned int rgba = 0x00000000)
Definition at line 310 of file GLFont.cpp.
References GLGlyph::advance_x, GL_ALPHA_TEST, GL_ARRAY_BUFFER, GL_BLEND, GL_FLOAT, GL_GEQUAL, GL_ONE_MINUS_SRC_ALPHA, GL_SRC_ALPHA, GL_TEXTURE_2D, GL_TEXTURE_COORD_ARRAY, GL_TRIANGLE_STRIP, GL_VERTEX_ARRAY, glAlphaFunc(), glBegin(), glBindBuffer, glBindTexture(), glBlendFunc(), glColor3ub(), glDisableClientState(), glEnable(), glEnableClientState(), glEnd(), GLEW_VERSION_1_5, glFlush(), glTexCoord2f(), glTexCoordPointer(), glVertex3d(), glVertexPointer(), GLGlyph::height, lineHeight(), m_fontSize, m_glyphs, m_texheight, m_texID, m_texwidth, m_vboID, GLGlyph::offset_x, GLGlyph::offset_y, p(), GLGlyph::u, GLGlyph::v, and GLGlyph::width.
void GLFont::render_textWorldSpace (const char * text, float x, float y, float scale, unsigned int rgba = 0x00000000)
Definition at line 227 of file GLFont.cpp.
References GLGlyph::advance_x, GL_ALPHA_TEST, GL_ARRAY_BUFFER, GL_BLEND, GL_FLOAT, GL_GEQUAL, GL_ONE_MINUS_SRC_ALPHA, GL_SRC_ALPHA, GL_TEXTURE_2D, GL_TEXTURE_COORD_ARRAY, GL_TRIANGLE_STRIP, GL_VERTEX_ARRAY, glAlphaFunc(), glBegin(), glBindBuffer, glBindTexture(), glBlendFunc(), glColor3ub(), glDisableClientState(), glEnable(), glEnableClientState(), glEnd(), GLEW_VERSION_1_5, glFlush(), glTexCoord2f(), glTexCoordPointer(), glVertex3d(), glVertexPointer(), h, GLGlyph::height, lineHeight(), m_fontSize, m_glyphs, m_texheight, m_texID, m_texwidth, m_vboID, GLGlyph::offset_x, GLGlyph::offset_y, p(), GLGlyph::u, GLGlyph::v, and GLGlyph::width.
Referenced by OpenGLGraph::glRenderText().
unsigned int GLFont::string_width (const char * str) const
Definition at line 405 of file GLFont.cpp.
References GLGlyph::advance_x, i, and m_glyphs.
Referenced by OpenGLGraph::TextWidthInPixels().
Member Data Documentation
unsigned char GLFont::m_fontSize
Definition at line 52 of file GLFont.h.
Referenced by getTextSize(), GLFont(), lineHeight(), load(), loadFromArray(), render_textScreenSpace(), and render_textWorldSpace().
const unsigned short GLFont::m_glyphCount
Definition at line 51 of file GLFont.h.
Referenced by GLFont(), load(), and loadFromArray().
GLGlyph* GLFont::m_glyphs
Definition at line 50 of file GLFont.h.
Referenced by char_width(), getTextSize(), GLFont(), load(), loadFromArray(), render_textScreenSpace(), render_textWorldSpace(), string_width(), and ~GLFont().
int GLFont::m_texheight
Definition at line 47 of file GLFont.h.
Referenced by load(), loadFromArray(), render_textScreenSpace(), and render_textWorldSpace().
GLuint GLFont::m_texID
Definition at line 48 of file GLFont.h.
Referenced by load(), loadFromArray(), render_textScreenSpace(), and render_textWorldSpace().
int GLFont::m_texwidth
Definition at line 44 of file GLFont.h.
Referenced by load(), loadFromArray(), render_textScreenSpace(), and render_textWorldSpace().
GLuint GLFont::m_vboID
Definition at line 49 of file GLFont.h.
Referenced by load(), loadFromArray(), render_textScreenSpace(), and render_textWorldSpace().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/oglGraph/GLFont.h
/home/erik/prefix/default/src/limesuite-dev/src/oglGraph/GLFont.cpp