LimeSuite-UML: swig::traits_from_stdseq< Seq, T > Struct Template Reference
swig::traits_from_stdseq< Seq, T > Struct Template Reference
Public Types
typedef Seq sequence
typedef T value_type
typedef Seq::size_type size_type
typedef sequence::const_iterator const_iterator
typedef Seq sequence
typedef T value_type
typedef Seq::size_type size_type
typedef sequence::const_iterator const_iterator
Static Public Member Functions
static PyObject * from (const sequence &seq)
static PyObject * from (const sequence &seq)
Detailed Description
template<class Seq, class T = typename Seq::value_type>
struct swig::traits_from_stdseq< Seq, T >
Definition at line 4767 of file SoapySDRPYTHON_wrap.cxx.
Member Typedef Documentation
template<class Seq, class T = typename Seq::value_type> typedef sequence::const_iterator swig::traits_from_stdseq< Seq, T >::const_iterator
Definition at line 4635 of file radar_swigPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef sequence::const_iterator swig::traits_from_stdseq< Seq, T >::const_iterator
Definition at line 4771 of file SoapySDRPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef Seq swig::traits_from_stdseq< Seq, T >::sequence
Definition at line 4632 of file radar_swigPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef Seq swig::traits_from_stdseq< Seq, T >::sequence
Definition at line 4768 of file SoapySDRPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef Seq::size_type swig::traits_from_stdseq< Seq, T >::size_type
Definition at line 4634 of file radar_swigPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef Seq::size_type swig::traits_from_stdseq< Seq, T >::size_type
Definition at line 4770 of file SoapySDRPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef T swig::traits_from_stdseq< Seq, T >::value_type
Definition at line 4633 of file radar_swigPYTHON_wrap.cxx.
template<class Seq, class T = typename Seq::value_type> typedef T swig::traits_from_stdseq< Seq, T >::value_type
Definition at line 4769 of file SoapySDRPYTHON_wrap.cxx.
Member Function Documentation
template<class Seq, class T = typename Seq::value_type> static PyObject* swig::traits_from_stdseq< Seq, T >::from (const sequence & seq) inline static
Definition at line 4637 of file radar_swigPYTHON_wrap.cxx.
References swig::asptr(), swig_type_info::clientdata, swig::from(), i, SWIG_NewPointerObj, SWIG_POINTER_OWN, SWIGINTERN, swig::type_name(), and vector().
template<class Seq, class T = typename Seq::value_type> static PyObject* swig::traits_from_stdseq< Seq, T >::from (const sequence & seq) inline static
Definition at line 4773 of file SoapySDRPYTHON_wrap.cxx.
References swig::asptr(), swig_type_info::clientdata, swig::from(), i, SWIG_NewPointerObj, SWIG_POINTER_OWN, swig::type_name(), and vector().
The documentation for this struct was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDRPYTHON_wrap.cxx
/home/erik/prefix/default/src/gr-radar-dev/build/swig/radar_swigPYTHON_wrap.cxx