LimeSuite-UML: lms7002_pnlCDS_view Class Reference
lms7002_pnlCDS_view Class Reference
Implementing pnlCDS_view.
#include <lms7002_pnlCDS_view.h>
Public Member Functions
lms7002_pnlCDS_view (wxWindow *parent)
Constructor.
lms7002_pnlCDS_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlCDS_view
pnlCDS_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlCDS_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlCDS_view
wxCheckBox * chkCDSN_TXBTSP
wxCheckBox * chkCDSN_TXATSP
wxCheckBox * chkCDSN_RXBTSP
wxCheckBox * chkCDSN_RXATSP
wxCheckBox * chkCDSN_TXBLML
wxCheckBox * chkCDSN_TXALML
wxCheckBox * chkCDSN_RXBLML
wxCheckBox * chkCDSN_RXALML
wxCheckBox * chkCDSN_MCLK2
wxCheckBox * chkCDSN_MCLK1
wxRadioBox * rgrCDS_MCLK2
wxRadioBox * rgrCDS_MCLK1
wxRadioBox * rgrCDS_TXBTSP
wxRadioBox * rgrCDS_TXATSP
wxRadioBox * rgrCDS_RXBTSP
wxRadioBox * rgrCDS_RXATSP
wxRadioBox * rgrCDS_TXBLML
wxRadioBox * rgrCDS_TXALML
wxRadioBox * rgrCDS_RXBLML
wxRadioBox * rgrCDS_RXALML
Additional Inherited Members
Protected Types inherited from pnlCDS_view
enum {
ID_CDSN_TXBTSP = 2048, ID_CDSN_TXATSP, ID_CDSN_RXBTSP, ID_CDSN_RXATSP,
ID_CDSN_TXBLML, ID_CDSN_TXALML, ID_CDSN_RXBLML, ID_CDSN_RXALML,
ID_CDSN_MCLK2, ID_CDSN_MCLK1, ID_CDS_MCLK2, ID_CDS_MCLK1,
ID_CDS_TXBTSP, ID_CDS_TXATSP, ID_CDS_RXBTSP, ID_CDS_RXATSP,
ID_CDS_TXBLML, ID_CDS_TXALML, ID_CDS_RXBLML, ID_CDS_RXALML
}
Detailed Description
Implementing pnlCDS_view.
Definition at line 19 of file lms7002_pnlCDS_view.h.
Constructor & Destructor Documentation
lms7002_pnlCDS_view::lms7002_pnlCDS_view (wxWindow * parent)
Constructor.
Definition at line 7 of file lms7002_pnlCDS_view.cpp.
lms7002_pnlCDS_view::lms7002_pnlCDS_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 14 of file lms7002_pnlCDS_view.cpp.
References CDS_MCLK1, CDS_MCLK2, CDS_RXALML, CDS_RXATSP, CDS_RXBLML, CDS_RXBTSP, CDS_TXALML, CDS_TXATSP, CDS_TXBLML, CDS_TXBTSP, CDSN_MCLK1, CDSN_MCLK2, CDSN_RXALML, CDSN_RXATSP, CDSN_RXBLML, CDSN_RXBTSP, CDSN_TXALML, CDSN_TXATSP, CDSN_TXBLML, CDSN_TXBTSP, pnlCDS_view::chkCDSN_MCLK1, pnlCDS_view::chkCDSN_MCLK2, pnlCDS_view::chkCDSN_RXALML, pnlCDS_view::chkCDSN_RXATSP, pnlCDS_view::chkCDSN_RXBLML, pnlCDS_view::chkCDSN_RXBTSP, pnlCDS_view::chkCDSN_TXALML, pnlCDS_view::chkCDSN_TXATSP, pnlCDS_view::chkCDSN_TXBLML, pnlCDS_view::chkCDSN_TXBTSP, LMS7param, pnlCDS_view::rgrCDS_MCLK1, pnlCDS_view::rgrCDS_MCLK2, pnlCDS_view::rgrCDS_RXALML, pnlCDS_view::rgrCDS_RXATSP, pnlCDS_view::rgrCDS_RXBLML, pnlCDS_view::rgrCDS_RXBTSP, pnlCDS_view::rgrCDS_TXALML, pnlCDS_view::rgrCDS_TXATSP, pnlCDS_view::rgrCDS_TXBLML, pnlCDS_view::rgrCDS_TXBTSP, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlCDS_view::Initialize (lms_device_t * pControl)
Definition at line 41 of file lms7002_pnlCDS_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlCDS_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlCDS_view.
Definition at line 47 of file lms7002_pnlCDS_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlCDS_view::UpdateGUI ()
Definition at line 63 of file lms7002_pnlCDS_view.cpp.
References lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlCDS_view::lmsControl protected
Definition at line 32 of file lms7002_pnlCDS_view.h.
Referenced by Initialize(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlCDS_view::wndId2Enum protected
Definition at line 33 of file lms7002_pnlCDS_view.h.
Referenced by lms7002_pnlCDS_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlCDS_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlCDS_view.cpp