LimeSuite-UML: lime::LMS7_Device Class Reference
lime::LMS7_Device Class Reference
#include <lms7_device.h>
Classes
struct ChannelInfo
struct Range
Public Member Functions
virtual ~LMS7_Device ()
LMS7_Device (LMS7_Device *obj=nullptr)
lime::IConnection * GetConnection (unsigned chan=0)
lime::FPGA * GetFPGA ()
virtual int Init ()
virtual int EnableChannel (bool dir_tx, unsigned chan, bool enabled)
int Reset ()
virtual unsigned GetNumChannels (const bool tx=false) const
virtual int SetRate (double f_MHz, int oversample)
virtual int SetRate (bool tx, double f_MHz, unsigned oversample=0)
virtual int SetRate (unsigned ch, double rxRate, double txRate, unsigned oversample=0)
int SetFPGAInterfaceFreq (int interp=-1, int dec=-1, double txPhase=999, double rxPhase=999)
virtual double GetRate (bool tx, unsigned chan, double *rf_rate_Hz=NULL) const
virtual Range GetRateRange (bool dir=false, unsigned chan=0) const
virtual std::vector< std::string > GetPathNames (bool dir_tx, unsigned chan=0) const
virtual int SetPath (bool tx, unsigned chan, unsigned path)
int GetPath (bool tx, unsigned chan) const
virtual int SetFrequency (bool tx, unsigned chan, double f_Hz)
double GetFrequency (bool tx, unsigned chan) const
virtual Range GetFrequencyRange (bool tx) const
virtual Range GetRxPathBand (unsigned path, unsigned chan) const
virtual Range GetTxPathBand (unsigned path, unsigned chan) const
int SetLPF (bool tx, unsigned chan, bool en, double bandwidth=-1)
double GetLPFBW (bool tx, unsigned chan) const
Range GetLPFRange (bool tx, unsigned chan) const
int SetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, const double *coef, unsigned count)
int GetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, double *coef) const
int SetGFIR (bool tx, unsigned chan, lms_gfir_t filt, bool enabled)
int SetGain (bool dir_tx, unsigned chan, double value, const std::string &name="")
double GetGain (bool dir_tx, unsigned chan, const std::string &name="") const
Range GetGainRange (bool dir_tx, unsigned chan, const std::string &name="") const
int SetTestSignal (bool dir_tx, unsigned chan, lms_testsig_t sig, int16_t dc_i=0, int16_t dc_q=0)
int GetTestSignal (bool dir_tx, unsigned chan) const
int SetNCOFreq (bool tx, unsigned ch, int ind, double freq)
double GetNCOFreq (bool tx, unsigned ch, int ind) const
int SetNCOPhase (bool tx, unsigned ch, int ind, double phase)
double GetNCOPhase (bool tx, unsigned ch, int ind) const
int Calibrate (bool dir_tx, unsigned chan, double bw, unsigned flags)
virtual std::vector< std::string > GetProgramModes () const
virtual int Program (const std::string &mode, const char *data, size_t len, lime::IConnection::ProgrammingCallback callback) const
double GetClockFreq (unsigned clk_id, int channel=-1) const
int SetClockFreq (unsigned clk_id, double freq, int channel=-1)
lms_dev_info_t * GetInfo ()
int Synchronize (bool toChip) const
int SetLogCallback (void(*func)(const char *cstr, const unsigned int type))
int EnableCalibCache (bool enable)
double GetChipTemperature (int ind=-1) const
int LoadConfig (const char *filename, int ind=-1)
int SaveConfig (const char *filename, int ind=-1) const
int ReadLMSReg (uint16_t address, int ind=-1) const
int WriteLMSReg (uint16_t address, uint16_t val, int ind=-1) const
uint16_t ReadParam (const struct LMS7Parameter &param, int channel=-1, bool forceReadFromChip=false) const
int ReadParam (const std::string &param, int channel=-1, bool forceReadFromChip=false) const
int WriteParam (const struct LMS7Parameter &param, uint16_t val, int channel=-1)
int WriteParam (const std::string &param, uint16_t val, int channel=-1)
int SetActiveChip (unsigned ind)
lime::LMS7002M * GetLMS (int index=-1) const
int UploadWFM (const void **samples, uint8_t chCount, int sample_count, lime::StreamConfig::StreamDataFormat fmt) const
int ConfigureGFIR (bool tx, unsigned ch, bool enabled, double bandwidth)
lime::StreamChannel * SetupStream (const lime::StreamConfig &config)
int DestroyStream (lime::StreamChannel *streamID)
uint64_t GetHardwareTimestamp (void) const
void SetHardwareTimestamp (const uint64_t now)
uint64_t GetChirpTimePeriod (void) const
uint64_t GetChirpTimeStamp (void) const
int MCU_AGCStart (uint32_t wantedRSSI)
int MCU_AGCStop ()
Static Public Member Functions
static LMS7_Device * CreateDevice (const lime::ConnectionHandle &handle, LMS7_Device *obj=nullptr)
static std::vector< lime::ConnectionHandle > GetDeviceList ()
Protected Member Functions
lime::LMS7002M * SelectChannel (unsigned chan) const
int ConfigureTXLPF (bool enabled, int ch, double bandwidth)
Protected Attributes
lms_dev_info_t devInfo
std::vector< ChannelInfo > tx_channels
std::vector< ChannelInfo > rx_channels
lime::IConnection * connection
std::vector< lime::LMS7002M * > lms_list
unsigned lms_chip_id
std::vector< lime::Streamer * > mStreamers
lime::FPGA * fpga
Detailed Description
Definition at line 21 of file lms7_device.h.
Constructor & Destructor Documentation
lime::LMS7_Device::~LMS7_Device () virtual
Definition at line 93 of file lms7_device.cpp.
References connection, fpga, lime::ConnectionRegistry::freeConnection(), i, lms_list, and mStreamers.
lime::LMS7_Device::LMS7_Device (LMS7_Device * obj = nullptr)
Definition at line 72 of file lms7_device.cpp.
References connection, lime::ConnectionRegistry::freeConnection(), GetNumChannels(), lms(), lms_list, rx_channels, and tx_channels.
Member Function Documentation
int lime::LMS7_Device::Calibrate (bool dir_tx, unsigned chan, double bw, unsigned flags)
Definition at line 1244 of file lms7_device.cpp.
References lime::LMS7002M::CalibrateRx(), lime::LMS7002M::CalibrateTx(), lms(), SelectChannel(), lime::LMS7002M::SPI_read(), and lime::LMS7002M::SPI_write().
Referenced by LMS_Calibrate(), and SoapyLMS7::writeSetting().
int lime::LMS7_Device::ConfigureGFIR (bool tx, unsigned ch, bool enabled, double bandwidth)
Definition at line 122 of file lms7_device.cpp.
References CDS_RXALML, CDS_RXBLML, CDSN_RXALML, CDSN_RXBLML, coef, GenerateFilter(), lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetReferenceClk_TSP(), GFIR1_BYP_RXTSP, GFIR1_BYP_TXTSP, GFIR1_L_RXTSP, GFIR1_L_TXTSP, GFIR1_N_RXTSP, GFIR1_N_TXTSP, GFIR2_BYP_RXTSP, GFIR2_BYP_TXTSP, GFIR2_L_RXTSP, GFIR2_L_TXTSP, GFIR2_N_RXTSP, GFIR2_N_TXTSP, GFIR3_BYP_RXTSP, GFIR3_BYP_TXTSP, GFIR3_L_RXTSP, GFIR3_L_TXTSP, GFIR3_N_RXTSP, GFIR3_N_TXTSP, HBD_OVR_RXTSP, HBI_OVR_TXTSP, i, L, lms(), LMS7_LML1_SISODDR, LMS7param, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::LMS7002M::Rx, SelectChannel(), lime::LMS7002M::SetGFIRCoefficients(), and lime::LMS7002M::Tx.
Referenced by LMS_SetGFIRLPF(), and SoapyLMS7::writeSetting().
int lime::LMS7_Device::ConfigureTXLPF (bool enabled, int ch, double bandwidth) protected
Definition at line 273 of file lms7_device.cpp.
References lime::info(), lms(), LMS7param, lime::LMS7002M::Modify_SPI_Reg_bits(), PD_LPFH_TBB, PD_LPFLAD_TBB, PD_LPFS5_TBB, SelectChannel(), and lime::LMS7002M::TuneTxFilter().
LMS7_Device * lime::LMS7_Device::CreateDevice (const lime::ConnectionHandle & handle, LMS7_Device * obj = nullptr) static
Definition at line 39 of file lms7_device.cpp.
References connection, device, lime::ConnectionRegistry::freeConnection(), lime::GetDeviceName(), lime::info(), lime::LMS_DEV_LIMESDR_PCIE, lime::LMS_DEV_LIMESDR_QPCIE, lime::LMS_DEV_LIMESDRMINI, lime::LMS_DEV_UNKNOWN, lime::ConnectionRegistry::makeConnection(), and lime::ReportError().
Referenced by LimeSDRTest::Connect(), LMS_Open(), main(), and dlgConnectionSettings::OnConnect().
int lime::LMS7_Device::DestroyStream (lime::StreamChannel * streamID)
Definition at line 1774 of file lms7_device.cpp.
Referenced by LMS_DestroyStream().
int lime::LMS7_Device::EnableCalibCache (bool enable)
Definition at line 1632 of file lms7_device.cpp.
References i, and lms_list.
Referenced by LMS_EnableCalibCache().
int lime::LMS7_Device::EnableChannel (bool dir_tx, unsigned chan, bool enabled) virtual
Reimplemented in lime::LMS7_qLimeSDR.
Definition at line 1402 of file lms7_device.cpp.
References chan, lime::LMS7002M::EnableChannel(), lms(), LMS_SUCCESS, rx_channels, SelectChannel(), and tx_channels.
Referenced by lime::LMS7_qLimeSDR::EnableChannel(), LMS_EnableChannel(), and SoapyLMS7::~SoapyLMS7().
double lime::LMS7_Device::GetChipTemperature (int ind = -1) const
Definition at line 1639 of file lms7_device.cpp.
References lms_chip_id, and lms_list.
Referenced by LMS_GetChipTemperature(), and SoapyLMS7::readSensor().
uint64_t lime::LMS7_Device::GetChirpTimePeriod (void) const
Definition at line 1790 of file lms7_device.cpp.
References mStreamers.
Referenced by SoapyLMS7::readSensor().
uint64_t lime::LMS7_Device::GetChirpTimeStamp (void) const
Definition at line 1795 of file lms7_device.cpp.
References mStreamers.
Referenced by SoapyLMS7::readSensor().
double lime::LMS7_Device::GetClockFreq (unsigned clk_id, int channel = -1) const
Definition at line 1473 of file lms7_device.cpp.
References lms_chip_id, LMS_CLOCK_CGEN, LMS_CLOCK_EXTREF, LMS_CLOCK_REF, LMS_CLOCK_RXTSP, LMS_CLOCK_SXR, LMS_CLOCK_SXT, LMS_CLOCK_TXTSP, lms_list, lime::ReportError(), and lime::LMS7002M::Rx.
Referenced by SoapyLMS7::getFrequency(), SoapyLMS7::getFrequencyRange(), SoapyLMS7::getMasterClockRate(), and LMS_GetClockFreq().
lime::IConnection * lime::LMS7_Device::GetConnection (unsigned chan = 0)
Definition at line 105 of file lms7_device.cpp.
References connection.
Referenced by HPM7_wxgui::Initialize(), LMS_GetDeviceInfo(), LMS_GPIODirRead(), LMS_GPIODirWrite(), LMS_GPIORead(), LMS_GPIOWrite(), LMS_IsOpen(), LMS_ReadCustomBoardParam(), LMS_ReadFPGAReg(), LMS_TransferLMS64C(), LMS_WriteCustomBoardParam(), LMS_WriteFPGAReg(), SoapyLMS7::readGPIO(), SoapyLMS7::readGPIODir(), SoapyLMS7::readRegister(), SoapyLMS7::writeGPIO(), SoapyLMS7::writeGPIODir(), and SoapyLMS7::writeRegister().
std::vector< lime::ConnectionHandle > lime::LMS7_Device::GetDeviceList () static
Definition at line 34 of file lms7_device.cpp.
References lime::ConnectionRegistry::findConnections().
Referenced by LimeSDRTest::CheckDevice(), LimeSDRTest::Connect(), and dlgConnectionSettings::OnConnect().
lime::FPGA * lime::LMS7_Device::GetFPGA ()
Definition at line 110 of file lms7_device.cpp.
References fpga.
Referenced by ConfigureCGEN().
double lime::LMS7_Device::GetFrequency (bool tx, unsigned chan) const
Definition at line 1320 of file lms7_device.cpp.
References chan, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetFrequencySX(), lms(), LMS7_MAC, LMS7_PD_VCO, lms_list, lime::LMS7002M::Modify_SPI_Reg_bits(), rx_channels, and tx_channels.
Referenced by SoapyLMS7::getFrequency(), and LMS_GetLOFrequency().
LMS7_Device::Range lime::LMS7_Device::GetFrequencyRange (bool tx) const virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 1334 of file lms7_device.cpp.
Referenced by LMS_GetLOFrequencyRange().
double lime::LMS7_Device::GetGain (bool dir_tx, unsigned chan, const std::string & name = "") const
Definition at line 1066 of file lms7_device.cpp.
References lime::LMS7002M::GetRBBPGA_dB(), lime::LMS7002M::GetRFELNA_dB(), lime::LMS7002M::GetRFELoopbackLNA_dB(), lime::LMS7002M::GetRFETIA_dB(), lime::LMS7002M::GetTBBIAMP_dB(), lime::LMS7002M::GetTRFLoopbackPAD_dB(), lime::LMS7002M::GetTRFPAD_dB(), lms(), and SelectChannel().
Referenced by SoapyLMS7::getGain(), LMS_GetGaindB(), and LMS_GetNormalizedGain().
LMS7_Device::Range lime::LMS7_Device::GetGainRange (bool dir_tx, unsigned chan, const std::string & name = "") const
Definition at line 1090 of file lms7_device.cpp.
Referenced by SoapyLMS7::getGainRange(), LMS_GetNormalizedGain(), and LMS_SetNormalizedGain().
int lime::LMS7_Device::GetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, double * coef) const
Definition at line 922 of file lms7_device.cpp.
References lime::LMS7002M::GetGFIRCoefficients(), i, lms(), LMS_GFIR3, and SelectChannel().
Referenced by LMS_GetGFIRCoeff().
uint64_t lime::LMS7_Device::GetHardwareTimestamp (void) const
Definition at line 1780 of file lms7_device.cpp.
References mStreamers.
Referenced by SoapyLMS7::getHardwareTime().
lms_dev_info_t * lime::LMS7_Device::GetInfo ()
Definition at line 1578 of file lms7_device.cpp.
References lms_dev_info_t::boardSerialNumber, connection, lms_dev_info_t::deviceName, devInfo, lms_dev_info_t::expansionName, lms_dev_info_t::firmwareVersion, lms_dev_info_t::gatewareTargetBoard, lms_dev_info_t::gatewareVersion, lime::IConnection::GetDeviceInfo(), lms_dev_info_t::hardwareVersion, lime::info(), and lms_dev_info_t::protocolVersion.
Referenced by SoapyLMS7::getHardwareInfo(), SoapyLMS7::getHardwareKey(), LMS_GetDeviceInfo(), and main().
lime::LMS7002M * lime::LMS7_Device::GetLMS (int index = -1) const
Definition at line 1754 of file lms7_device.cpp.
References lms_chip_id, and lms_list.
Referenced by ConfigureCGEN(), LMS_SetNCOFrequency(), and SoapyLMS7::readSensor().
double lime::LMS7_Device::GetLPFBW (bool tx, unsigned chan) const
Definition at line 785 of file lms7_device.cpp.
References chan, rx_channels, and tx_channels.
Referenced by LMS_GetLPFBW().
LMS7_Device::Range lime::LMS7_Device::GetLPFRange (bool tx, unsigned chan) const
Definition at line 790 of file lms7_device.cpp.
Referenced by LMS_GetLPFBWRange(), and SetLPF().
double lime::LMS7_Device::GetNCOFreq (bool tx, unsigned ch, int ind) const
Definition at line 1206 of file lms7_device.cpp.
References freq, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetNCOFrequency(), lms(), LMS7_CMIX_SC_RXTSP, LMS7_CMIX_SC_TXTSP, LMS7_MASK, and SelectChannel().
Referenced by SoapyLMS7::getFrequency(), LMS_GetNCOFrequency(), and LMS_GetNCOPhase().
double lime::LMS7_Device::GetNCOPhase (bool tx, unsigned ch, int ind) const
Definition at line 1238 of file lms7_device.cpp.
References lime::LMS7002M::GetNCOPhaseOffset_Deg(), lms(), and SelectChannel().
Referenced by LMS_GetNCOPhase().
unsigned lime::LMS7_Device::GetNumChannels (const bool tx = false) const virtual
Reimplemented in lime::LMS7_LimeSDR_mini, and lime::LMS7_qLimeSDR.
Definition at line 299 of file lms7_device.cpp.
Referenced by SoapyLMS7::getNumChannels(), SoapyLMS7::listRegisterInterfaces(), LMS7_Device(), lime::LMS7_Generic::LMS7_Generic(), LMS_Calibrate(), LMS_GetAntennaList(), LMS_GetGaindB(), LMS_GetGFIRCoeff(), LMS_GetLOFrequency(), LMS_GetLPFBW(), LMS_GetNCOFrequency(), LMS_GetNCOIndex(), LMS_GetNCOPhase(), LMS_GetNormalizedGain(), LMS_GetNumChannels(), LMS_GetSampleRate(), LMS_GetTestSignal(), LMS_SetAntenna(), LMS_SetGaindB(), LMS_SetGFIR(), LMS_SetGFIRCoeff(), LMS_SetGFIRLPF(), LMS_SetLOFrequency(), LMS_SetLPF(), LMS_SetLPFBW(), LMS_SetNCOFrequency(), LMS_SetNCOIndex(), LMS_SetNCOPhase(), LMS_SetNormalizedGain(), LMS_SetTestSignal(), lime::LMS7_LimeSDR::SetRate(), SetRate(), SetupStream(), SoapyLMS7::writeSetting(), and SoapyLMS7::~SoapyLMS7().
int lime::LMS7_Device::GetPath (bool tx, unsigned chan) const
Definition at line 715 of file lms7_device.cpp.
References lime::LMS7002M::GetBandTRF(), lime::LMS7002M::GetPathRFE(), lms(), and SelectChannel().
Referenced by SoapyLMS7::getAntenna(), and LMS_GetAntenna().
std::vector< std::string > lime::LMS7_Device::GetPathNames (bool dir_tx, unsigned chan = 0) const virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 698 of file lms7_device.cpp.
Referenced by SoapyLMS7::getAntenna(), SoapyLMS7::listAntennas(), LMS_GetAntennaList(), and SoapyLMS7::setAntenna().
std::vector< std::string > lime::LMS7_Device::GetProgramModes () const virtual
Reimplemented in lime::LMS7_LimeSDR_PCIE, lime::LMS7_LimeSDR_mini, and lime::LMS7_LimeSDR.
Definition at line 1423 of file lms7_device.cpp.
References lime::program_mode::fpgaFlash, lime::program_mode::fpgaRAM, lime::program_mode::fpgaReset, lime::program_mode::fx3Flash, lime::program_mode::fx3RAM, lime::program_mode::fx3Reset, lime::program_mode::mcuEEPROM, lime::program_mode::mcuRAM, and lime::program_mode::mcuReset.
Referenced by LMS_GetProgramModes().
double lime::LMS7_Device::GetRate (bool tx, unsigned chan, double * rf_rate_Hz = NULL) const virtual
Reimplemented in lime::LMS7_qLimeSDR.
Definition at line 667 of file lms7_device.cpp.
References lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetReferenceClk_TSP(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, lms(), LMS7param, lime::LMS7002M::Rx, SelectChannel(), and lime::LMS7002M::Tx.
Referenced by lime::LMS7_qLimeSDR::GetRate(), SoapyLMS7::getSampleRate(), LMS_GetSampleRate(), lime::LMS7_LimeSDR_mini::SetFrequency(), and SetFrequency().
LMS7_Device::Range lime::LMS7_Device::GetRateRange (bool dir = false, unsigned chan = 0) const virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 693 of file lms7_device.cpp.
Referenced by LMS_GetSampleRateRange().
LMS7_Device::Range lime::LMS7_Device::GetRxPathBand (unsigned path, unsigned chan) const virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 723 of file lms7_device.cpp.
References LMS_PATH_LNAH, LMS_PATH_LNAL, and LMS_PATH_LNAW.
Referenced by LMS_GetAntennaBW().
int lime::LMS7_Device::GetTestSignal (bool dir_tx, unsigned chan) const
Definition at line 1149 of file lms7_device.cpp.
References lime::LMS7002M::Get_SPI_Reg_bits(), INSEL_RXTSP, INSEL_TXTSP, lms(), LMS7param, LMS_TESTSIG_DC, LMS_TESTSIG_NONE, SelectChannel(), TSGFC_RXTSP, TSGFC_TXTSP, TSGFCW_RXTSP, TSGFCW_TXTSP, TSGMODE_RXTSP, and TSGMODE_TXTSP.
Referenced by LMS_GetTestSignal().
LMS7_Device::Range lime::LMS7_Device::GetTxPathBand (unsigned path, unsigned chan) const virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 734 of file lms7_device.cpp.
References LMS_PATH_TX1, and LMS_PATH_TX2.
Referenced by LMS_GetAntennaBW().
int lime::LMS7_Device::Init () virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 1339 of file lms7_device.cpp.
References lime::LMS7002M::EnableChannel(), i, lms(), LMS7param, lms_list, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::LMS7002M::ResetChip(), SetFrequency(), SetRate(), lime::LMS7002M::SPI_write(), and val.
Referenced by LMS_Init(), and main().
int lime::LMS7_Device::LoadConfig (const char * filename, int ind = -1)
Definition at line 1644 of file lms7_device.cpp.
References fpga, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetFrequencyCGEN(), lime::LMS7002M::GetReferenceClk_TSP(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, lms(), LMS7param, lms_chip_id, lms_list, lime::LMS7002M::LoadConfig(), MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::LMS7002M::Rx, lime::FPGA::SetInterfaceFreq(), lime::LMS7002M::SetInterfaceFrequency(), and lime::LMS7002M::Tx.
Referenced by LMS_LoadConfig(), main(), and SoapyLMS7::writeSetting().
int lime::LMS7_Device::MCU_AGCStart (uint32_t wantedRSSI)
Definition at line 1800 of file lms7_device.cpp.
References lime::debug(), lime::info(), lms_chip_id, lms_list, MCU_FUNCTION_AGC, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, mcu_program_lms7_dc_iq_calibration_bin, lime::MCU_BD::MCU_REF_CLK, lime::MCU_BD::Program_MCU(), lime::MCU_BD::ReadMCUProgramID(), lime::MCU_BD::RunProcedure(), lime::MCU_BD::SetParameter(), and status.
Referenced by lms7002_pnlGains_view::OnAGCStateChange().
int lime::LMS7_Device::MCU_AGCStop ()
Definition at line 1824 of file lms7_device.cpp.
References lms_chip_id, lms_list, and lime::MCU_BD::RunProcedure().
Referenced by lms7002_pnlGains_view::OnAGCStateChange().
int lime::LMS7_Device::Program (const std::string & mode, const char * data, size_t len, lime::IConnection::ProgrammingCallback callback) const virtual
Reimplemented in lime::LMS7_LimeSDR.
Definition at line 1430 of file lms7_device.cpp.
References lime::program_mode::autoUpdate, lime::MCU_BD::callback, callback, lime::MCU_BD::cMaxFWSize, connection, lime::program_mode::fpgaFlash, lime::program_mode::fpgaRAM, lime::program_mode::fpgaReset, lime::program_mode::fx3Flash, lime::program_mode::fx3RAM, lime::program_mode::fx3Reset, lms(), lms_chip_id, lms_list, lime::program_mode::mcuEEPROM, lime::program_mode::mcuRAM, lime::program_mode::mcuReset, lime::MCU_BD::Program_MCU(), lime::IConnection::ProgramUpdate(), lime::IConnection::ProgramWrite(), and lime::ReportError().
Referenced by LMS_Program(), and lime::LMS7_LimeSDR::Program().
int lime::LMS7_Device::ReadLMSReg (uint16_t address, int ind = -1) const
Definition at line 1669 of file lms7_device.cpp.
References lms_chip_id, and lms_list.
Referenced by LMS_Calibrate(), LMS_GetChipTemperature(), LMS_GetNCOFrequency(), LMS_ReadLMSReg(), and SoapyLMS7::readRegister().
uint16_t lime::LMS7_Device::ReadParam (const struct LMS7Parameter & param, int channel = -1, bool forceReadFromChip = false) const
Definition at line 1679 of file lms7_device.cpp.
References LMS7Parameter::address, LMS7param, lms_chip_id, lms_list, and MAC.
Referenced by SoapyLMS7::getDCOffsetMode(), LMS_GetNCOIndex(), LMS_ReadParam(), SoapyLMS7::readSetting(), and LMS7002_WXGUI::UpdateControlsByMap().
int lime::LMS7_Device::ReadParam (const std::string & param, int channel = -1, bool forceReadFromChip = false) const
Definition at line 1692 of file lms7_device.cpp.
References LMS7Parameter::address, lime::LMS7002M::GetParam(), LMS7param, lms_chip_id, lms_list, LMS7Parameter::lsb, MAC, and LMS7Parameter::msb.
int lime::LMS7_Device::Reset ()
Definition at line 1391 of file lms7_device.cpp.
References i, lms(), lms_list, LMS_SUCCESS, and lime::LMS7002M::ResetChip().
Referenced by LMS_Reset().
int lime::LMS7_Device::SaveConfig (const char * filename, int ind = -1) const
Definition at line 1664 of file lms7_device.cpp.
References lms_chip_id, and lms_list.
Referenced by LMS_SaveConfig(), and SoapyLMS7::writeSetting().
lime::LMS7002M * lime::LMS7_Device::SelectChannel (unsigned chan) const protected
Definition at line 115 of file lms7_device.cpp.
References lms(), LMS7param, lms_list, MAC, and lime::LMS7002M::Modify_SPI_Reg_bits().
Referenced by Calibrate(), ConfigureGFIR(), ConfigureTXLPF(), EnableChannel(), GetGain(), GetGFIRCoef(), GetNCOFreq(), GetNCOPhase(), GetPath(), GetRate(), GetTestSignal(), SetGain(), SetGFIR(), SetGFIRCoef(), SetLPF(), SetNCOFreq(), SetNCOPhase(), SetPath(), and SetTestSignal().
int lime::LMS7_Device::SetActiveChip (unsigned ind)
Definition at line 1743 of file lms7_device.cpp.
References ind, lms_chip_id, lms_list, and lime::ReportError().
int lime::LMS7_Device::SetClockFreq (unsigned clk_id, double freq, int channel = -1)
Definition at line 1503 of file lms7_device.cpp.
References connection, lime::IConnection::CustomParameterRead(), lime::IConnection::CustomParameterWrite(), lime::LMS7002M::Get_SPI_Reg_bits(), lime::ADF4002::GetConfig(), lime::LMS7002M::GetReferenceClk_SX(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, i, lime::info(), lms(), LMS7param, lms_chip_id, LMS_CLOCK_CGEN, LMS_CLOCK_EXTREF, LMS_CLOCK_REF, LMS_CLOCK_RXTSP, LMS_CLOCK_SXR, LMS_CLOCK_SXT, LMS_CLOCK_TXTSP, lms_list, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::ReportError(), lime::LMS7002M::Rx, lime::ADF4002::SetDefaults(), SetFPGAInterfaceFreq(), lime::ADF4002::SetFrefFvco(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetInterfaceFrequency(), lime::LMS7002M::SetReferenceClk_SX(), lime::IConnection::TransactSPI(), lime::LMS7002M::TuneVCO(), lime::LMS7002M::Tx, val, lime::LMS7002M::VCO_CGEN, lime::LMS7002M::VCO_SXR, and lime::LMS7002M::VCO_SXT.
Referenced by SoapyLMS7::getFrequencyArgsInfo(), LMS_SetClockFreq(), and SoapyLMS7::setMasterClockRate().
int lime::LMS7_Device::SetFPGAInterfaceFreq (int interp = -1, int dec = -1, double txPhase = 999, double rxPhase = 999)
Definition at line 638 of file lms7_device.cpp.
References fpga, HBD_OVR_RXTSP, HBI_OVR_TXTSP, lms(), LMS7_LML1_SISODDR, LMS7_LML2_SISODDR, LMS7param, lms_chip_id, lms_list, lime::LMS7002M::Rx, lime::FPGA::SetInterfaceFreq(), and lime::LMS7002M::Tx.
Referenced by SetClockFreq(), lime::LMS7_LimeSDR::SetRate(), and SetRate().
int lime::LMS7_Device::SetFrequency (bool tx, unsigned chan, double f_Hz) virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 1258 of file lms7_device.cpp.
References chan, lime::LMS7002M::EnableSXTDD(), freq, GetRate(), lms(), lms_list, rate, rx_channels, lime::LMS7002M::SetFrequencySX(), SetNCOFreq(), SetRate(), and tx_channels.
Referenced by SoapyLMS7::getFrequencyArgsInfo(), Init(), and LMS_SetLOFrequency().
int lime::LMS7_Device::SetGain (bool dir_tx, unsigned chan, double value, const std::string & name = "")
Definition at line 995 of file lms7_device.cpp.
References G_LNA_RFE, G_PGA_RBB, G_TIA_RFE, lime::LMS7002M::GetTRFPAD_dB(), int(), lms(), LMS7param, lime::LMS7002M::Modify_SPI_Reg_bits(), RCC_CTL_PGA_RBB, SelectChannel(), lime::LMS7002M::SetRBBPGA_dB(), lime::LMS7002M::SetRFELNA_dB(), lime::LMS7002M::SetRFELoopbackLNA_dB(), lime::LMS7002M::SetRFETIA_dB(), lime::LMS7002M::SetTBBIAMP_dB(), lime::LMS7002M::SetTRFLoopbackPAD_dB(), and lime::LMS7002M::SetTRFPAD_dB().
Referenced by LMS_SetGaindB(), LMS_SetNormalizedGain(), and SoapyLMS7::setGain().
int lime::LMS7_Device::SetGFIR (bool tx, unsigned chan, lms_gfir_t filt, bool enabled)
Definition at line 940 of file lms7_device.cpp.
References CDS_RXALML, CDS_RXBLML, CDSN_RXALML, CDSN_RXBLML, lime::LMS7002M::Get_SPI_Reg_bits(), GFIR1_BYP_RXTSP, GFIR1_BYP_TXTSP, GFIR2_BYP_RXTSP, GFIR2_BYP_TXTSP, GFIR3_BYP_RXTSP, GFIR3_BYP_TXTSP, lms(), LMS7_LML1_SISODDR, LMS7param, LMS_GFIR1, LMS_GFIR2, LMS_GFIR3, lime::LMS7002M::Modify_SPI_Reg_bits(), and SelectChannel().
Referenced by LMS_SetGFIR().
int lime::LMS7_Device::SetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, const double * coef, unsigned count)
Definition at line 795 of file lms7_device.cpp.
References lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetReferenceClk_TSP(), GFIR1_L_RXTSP, GFIR1_L_TXTSP, GFIR1_N_RXTSP, GFIR1_N_TXTSP, GFIR2_L_RXTSP, GFIR2_L_TXTSP, GFIR2_N_RXTSP, GFIR2_N_TXTSP, GFIR3_L_RXTSP, GFIR3_L_TXTSP, GFIR3_N_RXTSP, GFIR3_N_TXTSP, HBD_OVR_RXTSP, HBI_OVR_TXTSP, i, L, lms(), LMS7param, LMS_GFIR1, LMS_GFIR2, LMS_GFIR3, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::ReportError(), lime::LMS7002M::Rx, SelectChannel(), lime::LMS7002M::SetGFIRCoefficients(), lime::LMS7002M::Tx, and lime::warning().
Referenced by LMS_SetGFIRCoeff().
void lime::LMS7_Device::SetHardwareTimestamp (const uint64_t now)
Definition at line 1785 of file lms7_device.cpp.
References mStreamers.
Referenced by SoapyLMS7::setHardwareTime().
int lime::LMS7_Device::SetLogCallback (void(*)(const char *cstr, const unsigned int type) func)
Definition at line 1625 of file lms7_device.cpp.
References i, and lms_list.
int lime::LMS7_Device::SetLPF (bool tx, unsigned chan, bool en, double bandwidth = -1)
Definition at line 744 of file lms7_device.cpp.
References bandwidth, chan, gain, GetLPFRange(), lime::LMS7002M::GetTBBIAMP_dB(), lime::info(), lms(), rx_channels, SelectChannel(), lime::LMS7002M::SetTBBIAMP_dB(), status, lime::LMS7002M::TuneRxFilter(), lime::LMS7002M::TuneTxFilter(), tx_channels, and lime::warning().
Referenced by LMS_SetLPF(), LMS_SetLPFBW(), and SoapyLMS7::setBandwidth().
int lime::LMS7_Device::SetNCOFreq (bool tx, unsigned ch, int ind, double freq)
Definition at line 1180 of file lms7_device.cpp.
References enable, lime::LMS7002M::Get_SPI_Reg_bits(), lms(), LMS7_CMIX_BYP_RXTSP, LMS7_CMIX_BYP_TXTSP, LMS7_CMIX_GAIN_RXTSP, LMS7_CMIX_GAIN_TXTSP, LMS7_CMIX_SC_RXTSP, LMS7_CMIX_SC_TXTSP, LMS7_MASK, LMS7_MODE_RX, LMS7_MODE_TX, LMS7_SEL_RX, LMS7_SEL_TX, lime::LMS7002M::Modify_SPI_Reg_bits(), SelectChannel(), and lime::LMS7002M::SetNCOFrequency().
Referenced by SoapyLMS7::getFrequencyArgsInfo(), LMS_SetNCOFrequency(), LMS_SetNCOPhase(), lime::LMS7_LimeSDR_mini::SetFrequency(), SetFrequency(), and SetRate().
int lime::LMS7_Device::SetNCOPhase (bool tx, unsigned ch, int ind, double phase)
Definition at line 1217 of file lms7_device.cpp.
References enable, lms(), LMS7_CMIX_BYP_RXTSP, LMS7_CMIX_BYP_TXTSP, LMS7_CMIX_GAIN_RXTSP, LMS7_CMIX_GAIN_TXTSP, LMS7_MODE_RX, LMS7_MODE_TX, LMS7_SEL_RX, LMS7_SEL_TX, lime::LMS7002M::Modify_SPI_Reg_bits(), SelectChannel(), and lime::LMS7002M::SetNCOPhaseOffset().
Referenced by LMS_SetNCOPhase().
int lime::LMS7_Device::SetPath (bool tx, unsigned chan, unsigned path) virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 706 of file lms7_device.cpp.
References lms(), SelectChannel(), lime::LMS7002M::SetBandTRF(), and lime::LMS7002M::SetPathRFE().
Referenced by LMS_SetAntenna(), and SoapyLMS7::setAntenna().
int lime::LMS7_Device::SetRate (double f_MHz, int oversample) virtual
Reimplemented in lime::LMS7_LimeSDR_mini, and lime::LMS7_LimeSDR.
Definition at line 304 of file lms7_device.cpp.
References lime::cgenMax, CLKH_OV_CLKL_CGEN, EN_ADCCLKH_CLKGN, lime::error(), lime::LMS7002M::GetFrequencyCGEN(), GetNumChannels(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, i, lms(), LMS7param, lms_chip_id, lms_list, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), oversample, rx_channels, SetFPGAInterfaceFreq(), lime::LMS7002M::SetFrequencyCGEN(), lime::LMS7002M::SetInterfaceFrequency(), SetNCOFreq(), and tx_channels.
Referenced by Init(), LMS_SetSampleRate(), LMS_SetSampleRateDir(), SetFrequency(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_qLimeSDR::SetRate(), SetRate(), and SoapyLMS7::setSampleRate().
int lime::LMS7_Device::SetRate (bool tx, double f_MHz, unsigned oversample = 0) virtual
Reimplemented in lime::LMS7_LimeSDR_mini.
Definition at line 372 of file lms7_device.cpp.
References lime::cgenMax, CLKH_OV_CLKL_CGEN, EN_ADCCLKH_CLKGN, lime::LMS7002M::Get_SPI_Reg_bits(), GetNumChannels(), lime::LMS7002M::GetReferenceClk_TSP(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, i, lms(), LMS7param, lms_list, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), oversample, lime::ReportError(), lime::LMS7002M::Rx, rx_channels, SetFPGAInterfaceFreq(), lime::LMS7002M::SetFrequencyCGEN(), lime::LMS7002M::SetInterfaceFrequency(), SetNCOFreq(), lime::LMS7002M::Tx, and tx_channels.
int lime::LMS7_Device::SetRate (unsigned ch, double rxRate, double txRate, unsigned oversample = 0) virtual
Reimplemented in lime::LMS7_qLimeSDR.
Definition at line 631 of file lms7_device.cpp.
References SetRate().
int lime::LMS7_Device::SetTestSignal (bool dir_tx, unsigned chan, lms_testsig_t sig, int16_t dc_i = 0, int16_t dc_q = 0)
Definition at line 1103 of file lms7_device.cpp.
References INSEL_RXTSP, INSEL_TXTSP, lms(), LMS7param, LMS_TESTSIG_DC, LMS_TESTSIG_NCODIV4, LMS_TESTSIG_NCODIV4F, LMS_TESTSIG_NCODIV8, LMS_TESTSIG_NCODIV8F, LMS_TESTSIG_NONE, lime::LMS7002M::LoadDC_REG_IQ(), lime::LMS7002M::Modify_SPI_Reg_bits(), SelectChannel(), TSGFC_RXTSP, TSGFC_TXTSP, TSGFCW_RXTSP, TSGFCW_TXTSP, TSGMODE_RXTSP, and TSGMODE_TXTSP.
Referenced by LMS_SetTestSignal(), and SoapyLMS7::writeSetting().
lime::StreamChannel * lime::LMS7_Device::SetupStream (const lime::StreamConfig & config)
Definition at line 1767 of file lms7_device.cpp.
References lime::StreamConfig::channelID, GetNumChannels(), and mStreamers.
Referenced by LMS_SetupStream().
int lime::LMS7_Device::Synchronize (bool toChip) const
Definition at line 1594 of file lms7_device.cpp.
References lime::LMS7002M::DownloadAll(), fpga, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetFrequencyCGEN(), lime::LMS7002M::GetReferenceClk_TSP(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, i, lms(), LMS7param, lms_list, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::LMS7002M::Rx, lime::FPGA::SetInterfaceFreq(), lime::LMS7002M::SetInterfaceFrequency(), lime::LMS7002M::Tx, and lime::LMS7002M::UploadAll().
Referenced by LMS_Synchronize().
int lime::LMS7_Device::UploadWFM (const void ** samples, uint8_t chCount, int sample_count, lime::StreamConfig::StreamDataFormat fmt) const
Definition at line 1759 of file lms7_device.cpp.
References fpga, lime::ReportError(), and lime::FPGA::UploadWFM().
Referenced by LMS_UploadWFM().
int lime::LMS7_Device::WriteLMSReg (uint16_t address, uint16_t val, int ind = -1) const
Definition at line 1674 of file lms7_device.cpp.
References lms_chip_id, and lms_list.
Referenced by LMS_WriteLMSReg(), and SoapyLMS7::writeRegister().
int lime::LMS7_Device::WriteParam (const struct LMS7Parameter & param, uint16_t val, int channel = -1)
Definition at line 1710 of file lms7_device.cpp.
References LMS7Parameter::address, LMS7param, lms_chip_id, lms_list, and MAC.
Referenced by LMS_SetNCOFrequency(), LMS_SetNCOIndex(), LMS_SetNCOPhase(), LMS_WriteParam(), SoapyLMS7::setDCOffsetMode(), and SoapyLMS7::writeSetting().
int lime::LMS7_Device::WriteParam (const std::string & param, uint16_t val, int channel = -1)
Definition at line 1724 of file lms7_device.cpp.
References LMS7Parameter::address, lime::LMS7002M::GetParam(), LMS7param, lms_chip_id, lms_list, LMS7Parameter::lsb, MAC, and LMS7Parameter::msb.
Member Data Documentation
lime::IConnection* lime::LMS7_Device::connection protected
Definition at line 115 of file lms7_device.h.
Referenced by CreateDevice(), GetConnection(), GetInfo(), lime::LMS7_LimeSDR_mini::Init(), LMS7_Device(), lime::LMS7_Generic::LMS7_Generic(), lime::LMS7_LimeSDR_mini::LMS7_LimeSDR_mini(), lime::LMS7_qLimeSDR::LMS7_qLimeSDR(), lime::LMS7_LimeSDR::Program(), Program(), SetClockFreq(), lime::LMS7_LimeSDR_mini::SetPath(), and ~LMS7_Device().
lms_dev_info_t lime::LMS7_Device::devInfo protected
Definition at line 112 of file lms7_device.h.
Referenced by GetInfo().
lime::FPGA* lime::LMS7_Device::fpga protected
Definition at line 121 of file lms7_device.h.
Referenced by GetFPGA(), lime::LMS7_Generic::LMS7_Generic(), lime::LMS7_LimeSDR_mini::LMS7_LimeSDR_mini(), lime::LMS7_qLimeSDR::LMS7_qLimeSDR(), LoadConfig(), SetFPGAInterfaceFreq(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_qLimeSDR::SetRate(), Synchronize(), UploadWFM(), and ~LMS7_Device().
unsigned lime::LMS7_Device::lms_chip_id protected
Definition at line 119 of file lms7_device.h.
Referenced by GetChipTemperature(), GetClockFreq(), GetLMS(), LoadConfig(), MCU_AGCStart(), MCU_AGCStop(), Program(), ReadLMSReg(), ReadParam(), SaveConfig(), SetActiveChip(), SetClockFreq(), SetFPGAInterfaceFreq(), SetRate(), WriteLMSReg(), and WriteParam().
std::vector<lime::LMS7002M*> lime::LMS7_Device::lms_list protected
Definition at line 116 of file lms7_device.h.
Referenced by EnableCalibCache(), GetChipTemperature(), GetClockFreq(), GetFrequency(), GetLMS(), lime::LMS7_LimeSDR_mini::Init(), Init(), LMS7_Device(), lime::LMS7_Generic::LMS7_Generic(), lime::LMS7_LimeSDR_mini::LMS7_LimeSDR_mini(), lime::LMS7_qLimeSDR::LMS7_qLimeSDR(), LoadConfig(), MCU_AGCStart(), MCU_AGCStop(), Program(), ReadLMSReg(), ReadParam(), Reset(), SaveConfig(), SelectChannel(), SetActiveChip(), SetClockFreq(), SetFPGAInterfaceFreq(), lime::LMS7_LimeSDR_mini::SetFrequency(), SetFrequency(), SetLogCallback(), lime::LMS7_LimeSDR_mini::SetPath(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), SetRate(), Synchronize(), WriteLMSReg(), WriteParam(), and ~LMS7_Device().
std::vector<lime::Streamer*> lime::LMS7_Device::mStreamers protected
Definition at line 120 of file lms7_device.h.
Referenced by GetChirpTimePeriod(), GetChirpTimeStamp(), GetHardwareTimestamp(), lime::LMS7_Generic::LMS7_Generic(), lime::LMS7_LimeSDR_mini::LMS7_LimeSDR_mini(), lime::LMS7_qLimeSDR::LMS7_qLimeSDR(), SetHardwareTimestamp(), SetupStream(), and ~LMS7_Device().
std::vector<ChannelInfo> lime::LMS7_Device::rx_channels protected
Definition at line 114 of file lms7_device.h.
Referenced by EnableChannel(), GetFrequency(), GetLPFBW(), LMS7_Device(), lime::LMS7_Generic::LMS7_Generic(), lime::LMS7_qLimeSDR::LMS7_qLimeSDR(), lime::LMS7_LimeSDR_mini::SetFrequency(), SetFrequency(), SetLPF(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), and SetRate().
std::vector<ChannelInfo> lime::LMS7_Device::tx_channels protected
Definition at line 113 of file lms7_device.h.
Referenced by EnableChannel(), GetFrequency(), GetLPFBW(), LMS7_Device(), lime::LMS7_Generic::LMS7_Generic(), lime::LMS7_qLimeSDR::LMS7_qLimeSDR(), lime::LMS7_LimeSDR_mini::SetFrequency(), SetFrequency(), SetLPF(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), and SetRate().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/API/lms7_device.h
/home/erik/prefix/default/src/limesuite-dev/src/API/lms7_device.cpp