LimeSuite-UML: lime::ConnectionRegistry Class Reference
lime::ConnectionRegistry Class Reference
#include <ConnectionRegistry.h>
Static Public Member Functions
static std::vector< ConnectionHandle > findConnections (const ConnectionHandle &hint=ConnectionHandle())
static IConnection * makeConnection (const ConnectionHandle &handle)
static void freeConnection (IConnection *conn)
static std::vector< std::string > moduleNames (void)
Get a list of available registry entry modules by name.
Detailed Description
The connection registry provides a way to register discovery methods and factories for known connections, and to query and instantiate available connections.
Definition at line 24 of file ConnectionRegistry.h.
Member Function Documentation
std::vector< ConnectionHandle > ConnectionRegistry::findConnections (const ConnectionHandle & hint = ConnectionHandle()) static
Discovery identifiers that can be used to create a connection. The hint may contain a connection type, serial number, ip address, etc.
Parameters
hint an optional connection handle with some fields filled-in
Returns
a list of handles which can be used to make a connection
Definition at line 33 of file ConnectionRegistry.cpp.
References __loadAllConnections(), lime::ConnectionHandle::module, and registryMutex().
Referenced by deviceTestTiming(), findDevices(), findIConnection(), lime::LMS7_Device::GetDeviceList(), LMS_GetDeviceList(), LMS_Open(), main(), programFirmware(), programGateware(), programUpdate(), and StreamingFixture::StreamingFixture().
void ConnectionRegistry::freeConnection (IConnection * conn) static
Free an connection created by makeConnection().
Definition at line 79 of file ConnectionRegistry.cpp.
References registryMutex().
Referenced by lime::LMS7_Device::CreateDevice(), deviceTestTiming(), lime::LMS7_Device::LMS7_Device(), main(), makeDevice(), programFirmware(), programGateware(), programUpdate(), StreamingFixture::StreamingFixture(), lime::LMS7_Device::~LMS7_Device(), and StreamingFixture::~StreamingFixture().
IConnection * ConnectionRegistry::makeConnection (const ConnectionHandle & handle) static
Create a connection from an identifying handle. Return a null pointer when no factories are available.
Parameters
handle a connection handle with fields filled-in
Returns
a pointer to a connection instance (or null)
Definition at line 54 of file ConnectionRegistry.cpp.
References __loadAllConnections(), lime::ConnectionHandle::module, and registryMutex().
Referenced by lime::LMS7_Device::CreateDevice(), deviceTestTiming(), main(), makeDevice(), programFirmware(), programGateware(), programUpdate(), and StreamingFixture::StreamingFixture().
std::vector< std::string > ConnectionRegistry::moduleNames (void) static
Get a list of available registry entry modules by name.
Definition at line 89 of file ConnectionRegistry.cpp.
References __loadAllConnections(), and registryMutex().
Referenced by printInfo().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/ConnectionRegistry.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/ConnectionRegistry.cpp