LimeSuite-UML: lms7002_pnlCalibrations_view Class Reference
lms7002_pnlCalibrations_view Class Reference
Implementing pnlCalibrations_view.
#include <lms7002_pnlCalibrations_view.h>
Public Member Functions
lms7002_pnlCalibrations_view (wxWindow *parent)
Constructor.
lms7002_pnlCalibrations_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlCalibrations_view
pnlCalibrations_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxTAB_TRAVERSAL)
~pnlCalibrations_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void ParameterChangeHandler (wxSpinEvent &event)
void OnbtnCalibrateRx (wxCommandEvent &event)
void OnbtnCalibrateTx (wxCommandEvent &event)
void OnbtnCalibrateAll (wxCommandEvent &event)
void OnCalibrationMethodChange (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlCalibrations_view
wxStaticText * ID_STATICTEXT51
NumericSlider * cmbGCORRI_RXTSP
wxStaticText * ID_STATICTEXT41
NumericSlider * cmbGCORRQ_RXTSP
wxButton * ID_BUTTON101
NumericSlider * cmbIQCORR_RXTSP
wxStaticText * ID_STATICTEXT161
wxStaticText * txtPhaseAlpha1
wxStaticText * ID_STATICTEXT6
NumericSlider * cmbDCOFFI_RFE
wxStaticText * ID_STATICTEXT7
NumericSlider * cmbDCOFFQ_RFE
wxCheckBox * chkEN_DCOFF_RXFE_RFE
wxCheckBox * chkDCMODE
wxButton * btnCalibrateRx
wxStaticText * ID_STATICTEXT5
NumericSlider * cmbGCORRI_TXTSP
wxStaticText * ID_STATICTEXT4
NumericSlider * cmbGCORRQ_TXTSP
wxButton * ID_BUTTON10
NumericSlider * cmbIQCORR_TXTSP
wxStaticText * ID_STATICTEXT16
wxStaticText * txtPhaseAlpha
wxStaticText * ID_STATICTEXT8
NumericSlider * cmbDCCORRI_TXTSP
wxStaticText * ID_STATICTEXT9
NumericSlider * cmbDCCORRQ_TXTSP
wxButton * btnCalibrateTx
wxButton * btnCalibrateAll
wxStaticText * m_staticText431
wxStaticText * lblCGENrefClk
wxStaticText * m_staticText372
wxTextCtrl * txtCalibrationBW
wxRadioBox * rgrCalibrationMethod
wxStaticText * lblCalibrationNote
Additional Inherited Members
Protected Types inherited from pnlCalibrations_view
enum {
ID_GCORRI_RXTSP = 2048, ID_GCORRQ_RXTSP, ID_IQCORR_RXTSP, ID_DCOFFI_RFE,
ID_DCOFFQ_RFE, ID_EN_DCOFF_RXFE_RFE, ID_DCMODE, ID_GCORRI_TXTSP,
ID_GCORRQ_TXTSP, ID_IQCORR_TXTSP, ID_DCCORRI_TXTSP, ID_DCCORRQ_TXTSP
}
Detailed Description
Implementing pnlCalibrations_view.
Definition at line 18 of file lms7002_pnlCalibrations_view.h.
Constructor & Destructor Documentation
lms7002_pnlCalibrations_view::lms7002_pnlCalibrations_view (wxWindow * parent)
Constructor.
Definition at line 10 of file lms7002_pnlCalibrations_view.cpp.
lms7002_pnlCalibrations_view::lms7002_pnlCalibrations_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 17 of file lms7002_pnlCalibrations_view.cpp.
References pnlCalibrations_view::chkDCMODE, pnlCalibrations_view::chkEN_DCOFF_RXFE_RFE, pnlCalibrations_view::cmbDCCORRI_TXTSP, pnlCalibrations_view::cmbDCCORRQ_TXTSP, pnlCalibrations_view::cmbDCOFFI_RFE, pnlCalibrations_view::cmbDCOFFQ_RFE, pnlCalibrations_view::cmbGCORRI_RXTSP, pnlCalibrations_view::cmbGCORRI_TXTSP, pnlCalibrations_view::cmbGCORRQ_RXTSP, pnlCalibrations_view::cmbGCORRQ_TXTSP, pnlCalibrations_view::cmbIQCORR_RXTSP, pnlCalibrations_view::cmbIQCORR_TXTSP, DCCORRI_TXTSP, DCCORRQ_TXTSP, DCMODE, DCOFFI_RFE, DCOFFQ_RFE, EN_DCOFF_RXFE_RFE, GCORRI_RXTSP, GCORRI_TXTSP, GCORRQ_RXTSP, GCORRQ_TXTSP, IQCORR_RXTSP, IQCORR_TXTSP, LMS7param, pnlCalibrations_view::rgrCalibrationMethod, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlCalibrations_view::Initialize (lms_device_t * pControl)
Definition at line 140 of file lms7002_pnlCalibrations_view.cpp.
References pnlCalibrations_view::chkDCMODE, LMS7param, LMS_ReadParam(), lmsControl, and MASK.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlCalibrations_view::OnbtnCalibrateAll (wxCommandEvent & event) protected virtual
Reimplemented from pnlCalibrations_view.
Definition at line 107 of file lms7002_pnlCalibrations_view.cpp.
References LMS7param, LMS_Calibrate(), LMS_CH_RX, LMS_CH_TX, LMS_GetLastErrorMessage(), LMS_ReadParam(), lmsControl, MAC, pnlCalibrations_view::rgrCalibrationMethod, status, pnlCalibrations_view::txtCalibrationBW, and UpdateGUI().
void lms7002_pnlCalibrations_view::OnbtnCalibrateRx (wxCommandEvent & event) protected virtual
Reimplemented from pnlCalibrations_view.
Definition at line 37 of file lms7002_pnlCalibrations_view.cpp.
References flags, LMS7param, LMS_Calibrate(), LMS_CH_RX, LMS_GetLastErrorMessage(), LMS_ReadParam(), lmsControl, lime::LOG_LEVEL_INFO, LMS7SuiteAppFrame::m_lmsSelection, MAC, pnlCalibrations_view::rgrCalibrationMethod, status, pnlCalibrations_view::txtCalibrationBW, and UpdateGUI().
void lms7002_pnlCalibrations_view::OnbtnCalibrateTx (wxCommandEvent & event) protected virtual
Reimplemented from pnlCalibrations_view.
Definition at line 73 of file lms7002_pnlCalibrations_view.cpp.
References LMS7param, LMS_Calibrate(), LMS_CH_TX, LMS_GetLastErrorMessage(), LMS_ReadParam(), lmsControl, lime::LOG_LEVEL_INFO, MAC, pnlCalibrations_view::rgrCalibrationMethod, status, pnlCalibrations_view::txtCalibrationBW, and UpdateGUI().
void lms7002_pnlCalibrations_view::OnCalibrationMethodChange (wxCommandEvent & event) protected virtual
Reimplemented from pnlCalibrations_view.
Definition at line 221 of file lms7002_pnlCalibrations_view.cpp.
References pnlCalibrations_view::lblCalibrationNote, and pnlCalibrations_view::rgrCalibrationMethod.
void lms7002_pnlCalibrations_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlCalibrations_view.
Definition at line 159 of file lms7002_pnlCalibrations_view.cpp.
References pnlCalibrations_view::cmbDCOFFI_RFE, pnlCalibrations_view::cmbDCOFFQ_RFE, LMS_WriteParam(), lmsControl, and wndId2Enum.
Referenced by ParameterChangeHandler().
void lms7002_pnlCalibrations_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlCalibrations_view.
Definition at line 150 of file lms7002_pnlCalibrations_view.cpp.
References ParameterChangeHandler().
void lms7002_pnlCalibrations_view::UpdateGUI ()
Definition at line 182 of file lms7002_pnlCalibrations_view.cpp.
References pnlCalibrations_view::cmbDCCORRI_TXTSP, pnlCalibrations_view::cmbDCCORRQ_TXTSP, pnlCalibrations_view::cmbDCOFFI_RFE, pnlCalibrations_view::cmbDCOFFQ_RFE, pnlCalibrations_view::cmbIQCORR_RXTSP, pnlCalibrations_view::cmbIQCORR_TXTSP, DCCORRI_TXTSP, DCCORRQ_TXTSP, DCOFFI_RFE, DCOFFQ_RFE, freq, IQCORR_RXTSP, IQCORR_TXTSP, pnlCalibrations_view::lblCGENrefClk, LMS7param, LMS_CLOCK_REF, LMS_GetClockFreq(), LMS_ReadParam(), lmsControl, NumericSlider::SetValue(), LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by OnbtnCalibrateAll(), OnbtnCalibrateRx(), OnbtnCalibrateTx(), and lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlCalibrations_view::lmsControl protected
Definition at line 37 of file lms7002_pnlCalibrations_view.h.
Referenced by Initialize(), OnbtnCalibrateAll(), OnbtnCalibrateRx(), OnbtnCalibrateTx(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlCalibrations_view::wndId2Enum protected
Definition at line 38 of file lms7002_pnlCalibrations_view.h.
Referenced by lms7002_pnlCalibrations_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlCalibrations_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlCalibrations_view.cpp