LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/lms7002m/goert.cpp File Reference
goert.cpp File Reference
#include <iostream>
#include "IConnection.h"
#include <stdio.h>
#include <math.h>
#include <limits.h>
#include <stdint.h>
#include <chrono>
#include "Logger.h"
#include <string.h>
Functions
void getGoertzelCoefficients (int k, int SP, int32_t *c, int32_t *s)
int loadGoertzelCoefficients (IConnection *dataPort, int32_t c)
int readGoertzelValues (IConnection *port, int64_t *real, int64_t *imag, int32_t c, int32_t s)
Retrieves Goertzel computed I and Q values for the k-th bin from the FPGA.
int computeGoertzel (IConnection *dataPort)
int64_t c64to48 (int64_t x)
static int64_t resize_int (int64_t x, int16_t n)
void checkForMinMax (int64_t lr, int64_t &lr_min, int64_t &lr_max)
void CalcGoertzelI (int x[][2], int64_t real[], int64_t imag[], int Sp)
void CalcGoertzelF (int x[][2], float real[], float imag[], int Sp)
int SelectGoertzelBin (IConnection *port, uint16_t bin, uint16_t samplesCount)
int CalculateGoertzelBin (IConnection *port, int64_t *real, int64_t *imag)
Variables
static const double PI = 3.14159265359
static const uint16_t C_COS_ADDR_MSB = 0x0081
static const uint16_t C_COS_ADDR_LSB = 0x0082
static const uint16_t C_CTRL_ADDR = 0x0080
static const uint16_t C_INT_ADDR_START = 0x0083
static const uint16_t C_INT_ADDR_STOP = 0x008E
static const int C_TRIG_LEN = 32
static int32_t cos_value = 1
static int32_t sin_value = 0
static int fftBin
Function Documentation
int64_t c64to48 (int64_t x)
Referenced by computeGoertzel().
void CalcGoertzelF (int x[][2], float real[], float imag[], int Sp)
Definition at line 264 of file goert.cpp.
References fftBin, i, PI, and temp.
void CalcGoertzelI (int x[][2], int64_t real[], int64_t imag[], int Sp)
Definition at line 155 of file goert.cpp.
References checkForMinMax(), fftBin, PI, resize_int(), and temp.
int CalculateGoertzelBin (IConnection * port, int64_t * real, int64_t * imag)
Definition at line 325 of file goert.cpp.
References computeGoertzel(), cos_value, readGoertzelValues(), lime::ReportError(), sin_value, and status.
void checkForMinMax (int64_t lr, int64_t & lr_min, int64_t & lr_max)
Definition at line 146 of file goert.cpp.
Referenced by CalcGoertzelI().
int computeGoertzel (IConnection * dataPort)
Definition at line 96 of file goert.cpp.
References c64to48(), C_CTRL_ADDR, lime::IConnection::ReadRegister(), lime::ReportError(), status, t1, t2, and lime::IConnection::WriteRegisters().
Referenced by CalculateGoertzelBin().
void getGoertzelCoefficients (int k, int SP, int32_t * c, int32_t * s)
Definition at line 29 of file goert.cpp.
References C_TRIG_LEN, PI, and SP.
Referenced by SelectGoertzelBin().
int loadGoertzelCoefficients (IConnection * dataPort, int32_t c)
Definition at line 41 of file goert.cpp.
References C_COS_ADDR_LSB, C_COS_ADDR_MSB, and lime::IConnection::WriteRegisters().
Referenced by SelectGoertzelBin().
int readGoertzelValues (IConnection * port, int64_t * real, int64_t * imag, int32_t c, int32_t s)
Retrieves Goertzel computed I and Q values for the k-th bin from the FPGA.
Parameters
port - LMS7002M data port for communications with FPGA
real - real value of the k-th bin
imag - imag value of the k-th bin
c - cosine value
s - sine value Note: FPGA has to be streaming samples to the FX3.
Definition at line 60 of file goert.cpp.
References C_INT_ADDR_START, C_INT_ADDR_STOP, C_TRIG_LEN, i, lime::IConnection::ReadRegisters(), lime::ReportError(), and status.
Referenced by CalculateGoertzelBin().
static int64_t resize_int (int64_t x, int16_t n) static
Definition at line 135 of file goert.cpp.
Referenced by CalcGoertzelI().
int SelectGoertzelBin (IConnection * port, uint16_t bin, uint16_t samplesCount)
Definition at line 316 of file goert.cpp.
References cos_value, getGoertzelCoefficients(), loadGoertzelCoefficients(), sin_value, and status.
Variable Documentation
const uint16_t C_COS_ADDR_LSB = 0x0082 static
Definition at line 19 of file goert.cpp.
Referenced by loadGoertzelCoefficients().
const uint16_t C_COS_ADDR_MSB = 0x0081 static
Definition at line 18 of file goert.cpp.
Referenced by loadGoertzelCoefficients().
const uint16_t C_CTRL_ADDR = 0x0080 static
Definition at line 20 of file goert.cpp.
Referenced by computeGoertzel().
const uint16_t C_INT_ADDR_START = 0x0083 static
Definition at line 21 of file goert.cpp.
Referenced by readGoertzelValues().
const uint16_t C_INT_ADDR_STOP = 0x008E static
Definition at line 22 of file goert.cpp.
Referenced by readGoertzelValues().
const int C_TRIG_LEN = 32 static
Definition at line 24 of file goert.cpp.
Referenced by getGoertzelCoefficients(), and readGoertzelValues().
int32_t cos_value = 1 static
Definition at line 26 of file goert.cpp.
Referenced by CalculateGoertzelBin(), and SelectGoertzelBin().
int fftBin static
Definition at line 153 of file goert.cpp.
Referenced by CalcGoertzelF(), and CalcGoertzelI().
const double PI = 3.14159265359 static
Definition at line 16 of file goert.cpp.
Referenced by CalcGoertzelF(), CalcGoertzelI(), GenerateWindowCoefficients(), getGoertzelCoefficients(), and FPGAcontrols_wxgui::OnbtnLoadOnetoneClick().
int32_t sin_value = 0 static
Definition at line 27 of file goert.cpp.
Referenced by CalculateGoertzelBin(), and SelectGoertzelBin().