LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/BuiltinConnections.in.cpp File Reference
BuiltinConnections.in.cpp File Reference
Macros
#define ENABLE_EVB7COM
#define ENABLE_FX3
#define ENABLE_STREAM_UNITE
#define ENABLE_NOVENARF7
#define ENABLE_FTDI
#define ENABLE_PCIE_XILLYBUS
Functions
void __loadConnectionEVB7COMEntry (void)
make a static-initialized entry in the registry
void __loadConnectionFX3Entry (void)
make a static-initialized entry in the registry
void __loadConnectionSTREAM_UNITEEntry (void)
make a static-initialized entry in the registry
void __loadConnectionNovenaRF7Entry (void)
make a static-initialized entry in the registry
void __loadConnectionFT601Entry (void)
make a static-initialized entry in the registry
void __loadConnectionXillybusEntry (void)
make a static-initialized entry in the registry
void __loadAllConnections (void)
Macro Definition Documentation
#define ENABLE_EVB7COM
Definition at line 6 of file BuiltinConnections.in.cpp.
Referenced by set().
#define ENABLE_FTDI
Definition at line 10 of file BuiltinConnections.in.cpp.
#define ENABLE_FX3
Definition at line 7 of file BuiltinConnections.in.cpp.
#define ENABLE_NOVENARF7
Definition at line 9 of file BuiltinConnections.in.cpp.
Referenced by set().
#define ENABLE_PCIE_XILLYBUS
Definition at line 11 of file BuiltinConnections.in.cpp.
Referenced by set().
#define ENABLE_STREAM_UNITE
Definition at line 8 of file BuiltinConnections.in.cpp.
Referenced by set().
Function Documentation
void __loadAllConnections (void)
Definition at line 20 of file BuiltinConnections.in.cpp.
References __loadConnectionEVB7COMEntry(), __loadConnectionFT601Entry(), __loadConnectionFX3Entry(), __loadConnectionNovenaRF7Entry(), __loadConnectionSTREAM_UNITEEntry(), and __loadConnectionXillybusEntry().
Referenced by lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::makeConnection(), and lime::ConnectionRegistry::moduleNames().
void __loadConnectionEVB7COMEntry (void)
make a static-initialized entry in the registry
Definition at line 17 of file ConnectionEVB7COMEntry.cpp.
Referenced by __loadAllConnections().
void __loadConnectionFT601Entry (void)
make a static-initialized entry in the registry
Definition at line 26 of file ConnectionFT601Entry.cpp.
Referenced by __loadAllConnections().
void __loadConnectionFX3Entry (void)
make a static-initialized entry in the registry
Definition at line 27 of file ConnectionFX3Entry.cpp.
Referenced by __loadAllConnections().
void __loadConnectionNovenaRF7Entry (void)
make a static-initialized entry in the registry
Definition at line 74 of file ConnectionNovenaRF7Entry.cpp.
Referenced by __loadAllConnections().
void __loadConnectionSTREAM_UNITEEntry (void)
make a static-initialized entry in the registry
Definition at line 13 of file ConnectionSTREAM_UNITEEntry.cpp.
Referenced by __loadAllConnections().
void __loadConnectionXillybusEntry (void)
make a static-initialized entry in the registry
Definition at line 15 of file ConnectionXillybusEntry.cpp.
Referenced by __loadAllConnections().