LimeSuite-UML: ADF4002_wxgui Class Reference
ADF4002_wxgui Class Reference
#include <ADF4002_wxgui.h>
Public Member Functions
ADF4002_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_(""), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int styles=wxDEFAULT_FRAME_STYLE, wxString idname="")
void Initialize (lms_device_t *pSerPort)
virtual ~ADF4002_wxgui ()
void SetGuiDefaults ()
Public Attributes
wxStaticText * StaticText10
wxButton * btnUpload
wxStaticText * StaticText9
wxRadioBox * rgrPDP_i
wxComboBox * cmbCS1_f
wxComboBox * cmbCS2_f
wxStaticText * StaticText13
wxStaticText * StaticText2
wxSpinCtrl * spinNCnt
wxStaticText * StaticText14
wxComboBox * cmbFL_i
wxStaticText * StaticText6
wxStaticText * StaticText19
wxStaticText * StaticText8
wxStaticText * StaticText11
wxComboBox * cmbLDP
wxStaticText * StaticText18
wxRadioBox * rgrPD1_f
wxButton * btnCalcSend
wxStaticText * StaticText1
wxRadioBox * rgrCPS_f
wxComboBox * cmbMOC_f
wxComboBox * cmbTC_i
wxStaticText * StaticText3
wxTextCtrl * txtFref
wxRadioBox * rgrPDP_f
wxComboBox * cmbFL_f
wxSpinCtrl * spinRCnt
wxComboBox * cmbMOC_i
wxRadioBox * rgrCPS_i
wxComboBox * cmbCS1_i
wxRadioBox * rgrPD2_f
wxStaticText * StaticText5
wxStaticText * StaticText7
wxComboBox * cmbCPG
wxStaticText * StaticText15
wxStaticText * StaticText12
wxRadioBox * rgrPD1_i
wxStaticText * lblFcomp
wxRadioBox * rgrCR_f
wxTextCtrl * txtFvco
wxStaticText * StaticText17
wxStaticText * StaticText4
wxComboBox * cmbTC_f
wxRadioBox * rgrCR_i
wxStaticText * lblFvco
wxStaticText * StaticText16
wxRadioBox * rgrPD2_i
wxComboBox * cmbCS2_i
wxComboBox * cmbABW
Static Protected Attributes
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_STATICTEXT3 = wxNewId()
static const long ID_COMBOBOX1 = wxNewId()
static const long ID_COMBOBOX2 = wxNewId()
static const long ID_SPINCTRL1 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_STATICTEXT5 = wxNewId()
static const long ID_COMBOBOX3 = wxNewId()
static const long ID_SPINCTRL2 = wxNewId()
static const long ID_STATICTEXT6 = wxNewId()
static const long ID_STATICTEXT7 = wxNewId()
static const long ID_COMBOBOX4 = wxNewId()
static const long ID_COMBOBOX5 = wxNewId()
static const long ID_STATICTEXT8 = wxNewId()
static const long ID_STATICTEXT9 = wxNewId()
static const long ID_COMBOBOX6 = wxNewId()
static const long ID_COMBOBOX7 = wxNewId()
static const long ID_STATICTEXT10 = wxNewId()
static const long ID_COMBOBOX8 = wxNewId()
static const long ID_RADIOBOX1 = wxNewId()
static const long ID_RADIOBOX2 = wxNewId()
static const long ID_RADIOBOX3 = wxNewId()
static const long ID_RADIOBOX4 = wxNewId()
static const long ID_RADIOBOX5 = wxNewId()
static const long ID_STATICTEXT17 = wxNewId()
static const long ID_STATICTEXT18 = wxNewId()
static const long ID_COMBOBOX9 = wxNewId()
static const long ID_COMBOBOX10 = wxNewId()
static const long ID_STATICTEXT19 = wxNewId()
static const long ID_STATICTEXT20 = wxNewId()
static const long ID_COMBOBOX11 = wxNewId()
static const long ID_COMBOBOX12 = wxNewId()
static const long ID_STATICTEXT21 = wxNewId()
static const long ID_COMBOBOX13 = wxNewId()
static const long ID_RADIOBOX6 = wxNewId()
static const long ID_RADIOBOX7 = wxNewId()
static const long ID_RADIOBOX8 = wxNewId()
static const long ID_RADIOBOX9 = wxNewId()
static const long ID_RADIOBOX10 = wxNewId()
static const long ID_STATICTEXT11 = wxNewId()
static const long ID_STATICTEXT12 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_TEXTCTRL2 = wxNewId()
static const long ID_STATICTEXT13 = wxNewId()
static const long ID_STATICTEXT14 = wxNewId()
static const long ID_STATICTEXT15 = wxNewId()
static const long ID_STATICTEXT16 = wxNewId()
static const long ID_BUTTON1 = wxNewId()
static const long ID_BUTTON2 = wxNewId()
Private Member Functions
void OnbtnCalcSendClick (wxCommandEvent &event)
void OnbtnUploadClick (wxCommandEvent &event)
Private Attributes
lime::ADF4002 * m_pModule
lms_device_t * lmsControl
Detailed Description
Definition at line 30 of file ADF4002_wxgui.h.
Constructor & Destructor Documentation
ADF4002_wxgui::ADF4002_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = _(""), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int styles = wxDEFAULT_FRAME_STYLE, wxString idname = "")
Definition at line 80 of file ADF4002_wxgui.cpp.
References OnbtnCalcSendClick(), and OnbtnUploadClick().
ADF4002_wxgui::~ADF4002_wxgui () virtual
Definition at line 433 of file ADF4002_wxgui.cpp.
Member Function Documentation
void ADF4002_wxgui::Initialize (lms_device_t * pSerPort)
Definition at line 421 of file ADF4002_wxgui.cpp.
References LMS_CLOCK_REF, LMS_GetClockFreq(), and lmsControl.
Referenced by LMS7SuiteAppFrame::OnShowADF4002(), and LMS7SuiteAppFrame::UpdateConnections().
void ADF4002_wxgui::OnbtnCalcSendClick (wxCommandEvent & event) private
Definition at line 474 of file ADF4002_wxgui.cpp.
References i, lmsControl, and status.
Referenced by ADF4002_wxgui().
void ADF4002_wxgui::OnbtnUploadClick (wxCommandEvent & event) private
Definition at line 549 of file ADF4002_wxgui.cpp.
References i, lmsControl, and status.
Referenced by ADF4002_wxgui().
void ADF4002_wxgui::SetGuiDefaults ()
Definition at line 438 of file ADF4002_wxgui.cpp.
Member Data Documentation
wxButton* ADF4002_wxgui::btnCalcSend
Definition at line 59 of file ADF4002_wxgui.h.
wxButton* ADF4002_wxgui::btnUpload
Definition at line 42 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbABW
Definition at line 90 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbCPG
Definition at line 75 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbCS1_f
Definition at line 45 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbCS1_i
Definition at line 71 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbCS2_f
Definition at line 46 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbCS2_i
Definition at line 89 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbFL_f
Definition at line 67 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbFL_i
Definition at line 51 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbLDP
Definition at line 56 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbMOC_f
Definition at line 62 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbMOC_i
Definition at line 69 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbTC_f
Definition at line 84 of file ADF4002_wxgui.h.
wxComboBox* ADF4002_wxgui::cmbTC_i
Definition at line 63 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_BUTTON1 = wxNewId() static protected
Definition at line 144 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_BUTTON2 = wxNewId() static protected
Definition at line 145 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX1 = wxNewId() static protected
Definition at line 99 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX10 = wxNewId() static protected
Definition at line 124 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX11 = wxNewId() static protected
Definition at line 127 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX12 = wxNewId() static protected
Definition at line 128 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX13 = wxNewId() static protected
Definition at line 130 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX2 = wxNewId() static protected
Definition at line 100 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX3 = wxNewId() static protected
Definition at line 104 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX4 = wxNewId() static protected
Definition at line 108 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX5 = wxNewId() static protected
Definition at line 109 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX6 = wxNewId() static protected
Definition at line 112 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX7 = wxNewId() static protected
Definition at line 113 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX8 = wxNewId() static protected
Definition at line 115 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_COMBOBOX9 = wxNewId() static protected
Definition at line 123 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX1 = wxNewId() static protected
Definition at line 116 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX10 = wxNewId() static protected
Definition at line 135 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX2 = wxNewId() static protected
Definition at line 117 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX3 = wxNewId() static protected
Definition at line 118 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX4 = wxNewId() static protected
Definition at line 119 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX5 = wxNewId() static protected
Definition at line 120 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX6 = wxNewId() static protected
Definition at line 131 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX7 = wxNewId() static protected
Definition at line 132 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX8 = wxNewId() static protected
Definition at line 133 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_RADIOBOX9 = wxNewId() static protected
Definition at line 134 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_SPINCTRL1 = wxNewId() static protected
Definition at line 101 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_SPINCTRL2 = wxNewId() static protected
Definition at line 105 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT1 = wxNewId() static protected
Definition at line 96 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT10 = wxNewId() static protected
Definition at line 114 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT11 = wxNewId() static protected
Definition at line 136 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT12 = wxNewId() static protected
Definition at line 137 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT13 = wxNewId() static protected
Definition at line 140 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT14 = wxNewId() static protected
Definition at line 141 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT15 = wxNewId() static protected
Definition at line 142 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT16 = wxNewId() static protected
Definition at line 143 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT17 = wxNewId() static protected
Definition at line 121 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT18 = wxNewId() static protected
Definition at line 122 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT19 = wxNewId() static protected
Definition at line 125 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT2 = wxNewId() static protected
Definition at line 97 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT20 = wxNewId() static protected
Definition at line 126 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT21 = wxNewId() static protected
Definition at line 129 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT3 = wxNewId() static protected
Definition at line 98 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT4 = wxNewId() static protected
Definition at line 102 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT5 = wxNewId() static protected
Definition at line 103 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT6 = wxNewId() static protected
Definition at line 106 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT7 = wxNewId() static protected
Definition at line 107 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT8 = wxNewId() static protected
Definition at line 110 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_STATICTEXT9 = wxNewId() static protected
Definition at line 111 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_TEXTCTRL1 = wxNewId() static protected
Definition at line 138 of file ADF4002_wxgui.h.
const long ADF4002_wxgui::ID_TEXTCTRL2 = wxNewId() static protected
Definition at line 139 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::lblFcomp
Definition at line 79 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::lblFvco
Definition at line 86 of file ADF4002_wxgui.h.
lms_device_t* ADF4002_wxgui::lmsControl private
Definition at line 150 of file ADF4002_wxgui.h.
lime::ADF4002* ADF4002_wxgui::m_pModule private
Definition at line 149 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrCPS_f
Definition at line 61 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrCPS_i
Definition at line 70 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrCR_f
Definition at line 80 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrCR_i
Definition at line 85 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrPD1_f
Definition at line 58 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrPD1_i
Definition at line 78 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrPD2_f
Definition at line 72 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrPD2_i
Definition at line 88 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrPDP_f
Definition at line 66 of file ADF4002_wxgui.h.
wxRadioBox* ADF4002_wxgui::rgrPDP_i
Definition at line 44 of file ADF4002_wxgui.h.
wxSpinCtrl* ADF4002_wxgui::spinNCnt
Definition at line 49 of file ADF4002_wxgui.h.
wxSpinCtrl* ADF4002_wxgui::spinRCnt
Definition at line 68 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText1
Definition at line 60 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText10
Definition at line 41 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText11
Definition at line 55 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText12
Definition at line 77 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText13
Definition at line 47 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText14
Definition at line 50 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText15
Definition at line 76 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText16
Definition at line 87 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText17
Definition at line 82 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText18
Definition at line 57 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText19
Definition at line 53 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText2
Definition at line 48 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText3
Definition at line 64 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText4
Definition at line 83 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText5
Definition at line 73 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText6
Definition at line 52 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText7
Definition at line 74 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText8
Definition at line 54 of file ADF4002_wxgui.h.
wxStaticText* ADF4002_wxgui::StaticText9
Definition at line 43 of file ADF4002_wxgui.h.
wxTextCtrl* ADF4002_wxgui::txtFref
Definition at line 65 of file ADF4002_wxgui.h.
wxTextCtrl* ADF4002_wxgui::txtFvco
Definition at line 81 of file ADF4002_wxgui.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ADF4002/ADF4002_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/ADF4002/ADF4002_wxgui.cpp