LimeSuite-UML: INI< T, U, V > Class Template Reference
INI< T, U, V > Class Template Reference
#include <INI.h>
Public Types
enum source_e { SOURCE_FILE, SOURCE_MEMORY }
typedef T section_t
typedef U key_t
typedef V value_t
typedef INI< section_t, key_t, value_t > ini_t
typedef std::map< key_t, value_t > keys_t
Type definition declarations.
typedef std::map< section_t, keys_t * > sections_t
typedef keys_t::iterator keysit_t
typedef sections_t::iterator sectionsit_t
typedef std::pair< key_t, value_t > keyspair_t
typedef std::pair< section_t, keys_t * > sectionspair_t
typedef char data_t
Public Member Functions
INI (const std::string filename, bool doParse)
Constuctor/Destructor.
INI (void *data, size_t dataSize, bool doParse)
~INI ()
keys_t & operator[] (section_t section)
Access Content.
bool create (const section_t section)
bool select (const section_t section)
bool set (const key_t key, const value_t value)
Set.
template<typename W , typename X >
bool set (const W key, const X value)
value_t get (const key_t key, value_t def=value_t())
Get.
value_t get (const section_t section, const key_t key, value_t def)
template<typename W , typename X >
X get (const W key, const X def=value_t())
template<typename W >
fini_string_t get (const W key, const fini_char_t *def="")
template<typename W , typename X , typename Y >
Y get (const W section, const X key, const Y def)
template<typename W , typename X >
fini_string_t get (const W section, const X key, const fini_char_t *def)
void parse (std::istream &file)
Functions.
bool parse ()
bool parseBinary ()
void clear ()
bool save (const std::string filename="")
Output.
bool saveBinary (const std::string filename="")
bool saveBinaryExperimental (std::string filename="")
void merge (ini_t &other, bool retainValues=true)
Public Attributes
std::string filename
Data members.
data_t * data
size_t dataSize
keys_t * current
sections_t sections
source_e source
Private Member Functions
void init (source_e source, bool doParse)
Functions.
void clean ()
void nake (const fini_char_t *)
void reserveSections ()
void reserveKeys (keys_t *current)
bool hasFileAssociation (std::string filename)
fini_string_t makeSection (const section_t &section)
Output.
fini_string_t makeKeyValue (const key_t &key, const value_t &value)
Detailed Description
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t>
class INI< T, U, V >
Definition at line 90 of file INI.h.
Member Typedef Documentation
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef char INI< T, U, V >::data_t
Definition at line 113 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef INI<section_t, key_t, value_t> INI< T, U, V >::ini_t
Definition at line 96 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef U INI< T, U, V >::key_t
Definition at line 94 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef std::map<key_t, value_t> INI< T, U, V >::keys_t
Type definition declarations.
Definition at line 103 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef keys_t::iterator INI< T, U, V >::keysit_t
Definition at line 107 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef std::pair<key_t, value_t> INI< T, U, V >::keyspair_t
Definition at line 110 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef T INI< T, U, V >::section_t
Definition at line 93 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef std::map<section_t, keys_t*> INI< T, U, V >::sections_t
Definition at line 104 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef sections_t::iterator INI< T, U, V >::sectionsit_t
Definition at line 108 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef std::pair<section_t, keys_t*> INI< T, U, V >::sectionspair_t
Definition at line 111 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> typedef V INI< T, U, V >::value_t
Definition at line 95 of file INI.h.
Member Enumeration Documentation
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> enum INI::source_e
Enumerator
SOURCE_FILE
SOURCE_MEMORY
Definition at line 115 of file INI.h.
Constructor & Destructor Documentation
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> INI< T, U, V >::INI (const std::string filename, bool doParse) inline
Constuctor/Destructor.
Definition at line 127 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> INI< T, U, V >::INI (void * data, size_t dataSize, bool doParse) inline
Definition at line 133 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> INI< T, U, V >::~INI () inline
Definition at line 138 of file INI.h.
Member Function Documentation
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::clean () inline private
Definition at line 536 of file INI.h.
References i.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::clear () inline
Definition at line 387 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::create (const section_t section) inline
Definition at line 156 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> value_t INI< T, U, V >::get (const key_t key, value_t def = value_t()) inline
Get.
Definition at line 198 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> value_t INI< T, U, V >::get (const section_t section, const key_t key, value_t def) inline
Definition at line 207 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> template<typename W , typename X > X INI< T, U, V >::get (const W key, const X def = value_t()) inline
Definition at line 216 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> template<typename W > fini_string_t INI< T, U, V >::get (const W key, const fini_char_t * def = "") inline
Definition at line 220 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> template<typename W , typename X , typename Y > Y INI< T, U, V >::get (const W section, const X key, const Y def) inline
Definition at line 224 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> template<typename W , typename X > fini_string_t INI< T, U, V >::get (const W section, const X key, const fini_char_t * def) inline
Definition at line 228 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::hasFileAssociation (std::string filename) inline private
Definition at line 564 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::init (source_e source, bool doParse) inline private
Functions.
Definition at line 526 of file INI.h.
References doxyxml.generated.compound::parse().
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> fini_string_t INI< T, U, V >::makeKeyValue (const key_t & key, const value_t & value) inline private
Definition at line 583 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> fini_string_t INI< T, U, V >::makeSection (const section_t & section) inline private
Output.
Definition at line 574 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::merge (ini_t & other, bool retainValues = true) inline
Definition at line 500 of file INI.h.
References i, and INI< T, U, V >::sections.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::nake (const fini_char_t *) inline private
Definition at line 545 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> keys_t& INI< T, U, V >::operator[] (section_t section) inline
Access Content.
Definition at line 145 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::parse (std::istream & file) inline
Functions.
Definition at line 232 of file INI.h.
References _T, CHAR_SIZE, FINI_BUFFER_SIZE, fini_strcpy, fini_strlen, fini_strncpy, fini_strtok, Converters::GetLine(), index, and len.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::parse () inline
Definition at line 320 of file INI.h.
References file(), and doxyxml.generated.compound::parse().
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::parseBinary () inline
Definition at line 348 of file INI.h.
References file(), and i.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::reserveKeys (keys_t * current) inline private
Definition at line 557 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> void INI< T, U, V >::reserveSections () inline private
Definition at line 550 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::save (const std::string filename = "") inline
Output.
Definition at line 395 of file INI.h.
References file(), fini_strlen, i, and temp.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::saveBinary (const std::string filename = "") inline
Definition at line 430 of file INI.h.
References file(), and i.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::saveBinaryExperimental (std::string filename = "") inline
Definition at line 465 of file INI.h.
References file(), Converters::GetDataSize(), and i.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::select (const section_t section) inline
Definition at line 170 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> bool INI< T, U, V >::set (const key_t key, const value_t value) inline
Set.
Definition at line 183 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> template<typename W , typename X > bool INI< T, U, V >::set (const W key, const X value) inline
Definition at line 194 of file INI.h.
Member Data Documentation
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> keys_t* INI< T, U, V >::current
Definition at line 121 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> data_t* INI< T, U, V >::data
Definition at line 119 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> size_t INI< T, U, V >::dataSize
Definition at line 120 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> std::string INI< T, U, V >::filename
Data members.
Definition at line 118 of file INI.h.
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> sections_t INI< T, U, V >::sections
Definition at line 122 of file INI.h.
Referenced by INI< T, U, V >::merge().
template<typename T = fini_string_t, typename U = fini_string_t, typename V = fini_string_t> source_e INI< T, U, V >::source
Definition at line 123 of file INI.h.
The documentation for this class was generated from the following file:
/home/erik/prefix/default/src/limesuite-dev/external/cpp-feather-ini-parser/INI.h