LimeSuite-UML: SoapySDR::Registry Class Reference
SoapySDR::Registry Class Reference
#include <Registry.hpp>
Public Member Functions
Registry (const std::string &name, const FindFunction &find, const MakeFunction &make, const std::string &abi)
~Registry (void)
Cleanup this registry entry.
Static Public Member Functions
static FindFunctions listFindFunctions (void)
static MakeFunctions listMakeFunctions (void)
Private Attributes
std::string _name
Detailed Description
A registry object loads device functions into the global registry.
Definition at line 40 of file Registry.hpp.
Constructor & Destructor Documentation
SoapySDR::Registry::Registry (const std::string & name, const FindFunction & find, const MakeFunction & make, const std::string & abi)
Register a SDR device find and make function.
Parameters
name a unique name to identify the entry
find the find function returns an arg list
make the make function returns a device sptr
abi this value must be SOAPY_SDR_ABI_VERSION
Definition at line 34 of file Registry.cpp.
References FunctionsEntry::find, getFunctionTable(), getLoaderResults(), getModuleLoading(), FunctionsEntry::make, FunctionsEntry::modulePath, SOAPY_SDR_ABI_VERSION, and string().
SoapySDR::Registry::~Registry (void)
Cleanup this registry entry.
Definition at line 62 of file Registry.cpp.
References getFunctionTable().
Member Function Documentation
SoapySDR::FindFunctions SoapySDR::Registry::listFindFunctions (void) static
List all loaded find functions.
Returns
a dictionary of registry entry names to find functions
Definition at line 72 of file Registry.cpp.
References getFunctionTable().
Referenced by checkDriver(), getDeviceCounts(), and printInfo().
SoapySDR::MakeFunctions SoapySDR::Registry::listMakeFunctions (void) static
List all loaded make functions.
Returns
a dictionary of registry entry names to make functions
Definition at line 82 of file Registry.cpp.
References getFunctionTable().
Referenced by getDeviceFromTable().
Member Data Documentation
std::string SoapySDR::Registry::_name private
Definition at line 69 of file Registry.hpp.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/soapysdr/include/SoapySDR/Registry.hpp
/home/erik/prefix/default/src/soapysdr/lib/Registry.cpp