LimeSuite-UML: LimeSDRTest_Mini Class Reference
LimeSDRTest_Mini Class Reference
#include <LimeSDRTest.h>
Private Member Functions
LimeSDRTest_Mini (lime::LMS7_Device *dev)
int ClockNetworkTest () override
int RFTest () override
Friends
class LimeSDRTest
Additional Inherited Members
Static Public Member Functions inherited from LimeSDRTest
static int RunTests (TestCallback cb, bool nonblock=true)
static int CheckDevice (std::string &str)
Protected Member Functions inherited from LimeSDRTest
LimeSDRTest (lime::LMS7_Device *dev)
virtual ~LimeSDRTest ()
int InitFPGATest (unsigned test, double timeout)
int GPIFClkTest ()
int VCTCXOTest ()
bool RunTest (float &peakval, float &peakFreq, int ch=0)
Static Protected Member Functions inherited from LimeSDRTest
static void UpdateStatus (int event, const char *msg=nullptr)
static std::string RFTestInfo (const RFTestData &data, bool passed)
Protected Attributes inherited from LimeSDRTest
lime::LMS7_Device * device
Detailed Description
Definition at line 78 of file LimeSDRTest.h.
Constructor & Destructor Documentation
LimeSDRTest_Mini::LimeSDRTest_Mini (lime::LMS7_Device * dev) inline private
Definition at line 81 of file LimeSDRTest.h.
References LimeSDRTest::ClockNetworkTest(), and LimeSDRTest::RFTest().
Member Function Documentation
int LimeSDRTest_Mini::ClockNetworkTest () override private virtual
Implements LimeSDRTest.
Definition at line 12 of file LimeSDRTest_Mini.cpp.
References LimeSDRTest::GPIFClkTest(), LMS_TEST_INFO, LimeSDRTest::UpdateStatus(), and LimeSDRTest::VCTCXOTest().
int LimeSDRTest_Mini::RFTest () override private virtual
Implements LimeSDRTest.
Definition at line 31 of file LimeSDRTest_Mini.cpp.
References device, freq, LMS_TEST_FAIL, LMS_TEST_INFO, LMS_TESTSIG_DC, LimeSDRTest::RFTestData::peakfreq, LimeSDRTest::RFTestData::peakval, LimeSDRTest::RFTestInfo(), LimeSDRTest::RunTest(), lime::LMS7002M::Rx, string(), lime::LMS7002M::Tx, and LimeSDRTest::UpdateStatus().
Friends And Related Function Documentation
friend class LimeSDRTest friend
Definition at line 80 of file LimeSDRTest.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/QuickTest/LimeSDRTest.h
/home/erik/prefix/default/src/limesuite-dev/QuickTest/LimeSDRTest_Mini.cpp