LimeSuite-UML: MCU_File Class Reference
MCU_File Class Reference
#include <MCU_File.h>
Public Member Functions
MCU_File (const char *fileName, const char *mode)
~MCU_File ()
bool FileOpened ()
void ReadBin (unsigned long limit)
void ReadHex (unsigned long limit)
bool GetByte (const unsigned long address, unsigned char &chr)
bool BitString (const unsigned long address, const unsigned char bits, const bool lEndian, string &str)
FILE * Handle ()
Public Attributes
vector< MemBlock > m_chunks
unsigned long m_top
Private Attributes
FILE * m_file
Detailed Description
Definition at line 20 of file MCU_File.h.
Constructor & Destructor Documentation
MCU_File::MCU_File (const char * fileName, const char * mode) inline explicit
Definition at line 23 of file MCU_File.h.
MCU_File::~MCU_File () inline
Definition at line 38 of file MCU_File.h.
Member Function Documentation
bool MCU_File::BitString (const unsigned long address, const unsigned char bits, const bool lEndian, string & str) inline
Definition at line 477 of file MCU_File.h.
References i.
bool MCU_File::FileOpened () inline
Definition at line 44 of file MCU_File.h.
Referenced by lms7002_pnlMCU_BD_view::GetProgramCode(), and lime::MCU_BD::GetProgramCode().
bool MCU_File::GetByte (const unsigned long address, unsigned char & chr) inline
Definition at line 458 of file MCU_File.h.
References address.
Referenced by lms7002_pnlMCU_BD_view::GetProgramCode(), and lime::MCU_BD::GetProgramCode().
FILE* MCU_File::Handle () inline
Definition at line 527 of file MCU_File.h.
void MCU_File::ReadBin (unsigned long limit) inline
Definition at line 50 of file MCU_File.h.
void MCU_File::ReadHex (unsigned long limit) inline
Definition at line 88 of file MCU_File.h.
References address, header, and i.
Referenced by lms7002_pnlMCU_BD_view::GetProgramCode(), and lime::MCU_BD::GetProgramCode().
Member Data Documentation
vector<MemBlock> MCU_File::m_chunks
Definition at line 527 of file MCU_File.h.
FILE* MCU_File::m_file private
Definition at line 531 of file MCU_File.h.
unsigned long MCU_File::m_top
Definition at line 529 of file MCU_File.h.
The documentation for this class was generated from the following file:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m_mcu/MCU_File.h