LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/oglGraph/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/oglGraph/CMakeLists.txt File Reference
Functions
set (oglGraph_src_files dlgMarkers.cpp GLFont.cpp OpenGLGraph.cpp glew/glew.c) include_directories(glew) include_directories(glew/GL) if(CMAKE_COMPILER_IS_GNUCXX) add_definitions(-Wno-narrowing) endif() add_library(oglGraph STATIC $
target_include_directories (oglGraph PUBLIC ${CMAKE_CURRENT_SOURCE_DIR}) if(APPLE) set(GL_LIBS"-framework OpenGL""-framework GLUT") elseif(UNIX) set(GL_LIBS GL) endif() if(UNIX) target_link_libraries(oglGraph $
Function Documentation
set (oglGraph_src_files dlgMarkers.cpp GLFont.cpp OpenGLGraph.cpp glew/glew. c)
Definition at line 1 of file CMakeLists.txt.
target_include_directories (oglGraph PUBLIC ${CMAKE_CURRENT_SOURCE_DIR})
Definition at line 17 of file CMakeLists.txt.
References elseif(), endif(), and target_link_libraries().
Referenced by set().