LimeSuite-UML: swig::SwigPyIterator Struct Reference
swig::SwigPyIterator Struct Reference abstract
Public Member Functions
virtual ~SwigPyIterator ()
virtual PyObject * value () const =0
virtual SwigPyIterator * incr (size_t n=1)=0
virtual SwigPyIterator * decr (size_t=1)
virtual ptrdiff_t distance (const SwigPyIterator &) const
virtual bool equal (const SwigPyIterator &) const
virtual SwigPyIterator * copy () const =0
PyObject * next ()
PyObject * __next__ ()
PyObject * previous ()
SwigPyIterator * advance (ptrdiff_t n)
bool operator== (const SwigPyIterator &x) const
bool operator!= (const SwigPyIterator &x) const
SwigPyIterator & operator+= (ptrdiff_t n)
SwigPyIterator & operator-= (ptrdiff_t n)
SwigPyIterator * operator+ (ptrdiff_t n) const
SwigPyIterator * operator- (ptrdiff_t n) const
ptrdiff_t operator- (const SwigPyIterator &x) const
virtual ~SwigPyIterator ()
virtual PyObject * value () const =0
virtual SwigPyIterator * incr (size_t n=1)=0
virtual SwigPyIterator * decr (size_t=1)
virtual ptrdiff_t distance (const SwigPyIterator &) const
virtual bool equal (const SwigPyIterator &) const
virtual SwigPyIterator * copy () const =0
PyObject * next ()
PyObject * __next__ ()
PyObject * previous ()
SwigPyIterator * advance (ptrdiff_t n)
bool operator== (const SwigPyIterator &x) const
bool operator!= (const SwigPyIterator &x) const
SwigPyIterator & operator+= (ptrdiff_t n)
SwigPyIterator & operator-= (ptrdiff_t n)
SwigPyIterator * operator+ (ptrdiff_t n) const
SwigPyIterator * operator- (ptrdiff_t n) const
ptrdiff_t operator- (const SwigPyIterator &x) const
Static Public Member Functions
static swig_type_info * descriptor ()
static swig_type_info * descriptor ()
Protected Member Functions
SwigPyIterator (PyObject *seq)
SwigPyIterator (PyObject *seq)
Private Attributes
SwigPtr_PyObject _seq
Detailed Description
Definition at line 3126 of file SoapySDRPYTHON_wrap.cxx.
Constructor & Destructor Documentation
swig::SwigPyIterator::SwigPyIterator (PyObject * seq) inline protected
Definition at line 3131 of file SoapySDRPYTHON_wrap.cxx.
virtual swig::SwigPyIterator::~SwigPyIterator () inline virtual
Definition at line 3136 of file SoapySDRPYTHON_wrap.cxx.
swig::SwigPyIterator::SwigPyIterator (PyObject * seq) inline protected
Definition at line 3185 of file radar_swigPYTHON_wrap.cxx.
virtual swig::SwigPyIterator::~SwigPyIterator () inline virtual
Definition at line 3190 of file radar_swigPYTHON_wrap.cxx.
Member Function Documentation
PyObject* swig::SwigPyIterator::__next__ () inline
Definition at line 3174 of file SoapySDRPYTHON_wrap.cxx.
PyObject* swig::SwigPyIterator::__next__ () inline
Definition at line 3228 of file radar_swigPYTHON_wrap.cxx.
SwigPyIterator* swig::SwigPyIterator::advance (ptrdiff_t n) inline
Definition at line 3188 of file SoapySDRPYTHON_wrap.cxx.
Referenced by _wrap_SwigPyIterator_advance(), operator+(), and operator-().
SwigPyIterator* swig::SwigPyIterator::advance (ptrdiff_t n) inline
Definition at line 3242 of file radar_swigPYTHON_wrap.cxx.
virtual SwigPyIterator* swig::SwigPyIterator::copy () const pure virtual
Implemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
virtual SwigPyIterator* swig::SwigPyIterator::copy () const pure virtual
Implemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
virtual SwigPyIterator* swig::SwigPyIterator::decr (size_t = 1) inline virtual
Reimplemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
Definition at line 3145 of file SoapySDRPYTHON_wrap.cxx.
Referenced by _wrap_SwigPyIterator_decr__SWIG_0(), and _wrap_SwigPyIterator_decr__SWIG_1().
virtual SwigPyIterator* swig::SwigPyIterator::decr (size_t = 1) inline virtual
Reimplemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
Definition at line 3199 of file radar_swigPYTHON_wrap.cxx.
static swig_type_info* swig::SwigPyIterator::descriptor () inline static
Definition at line 3228 of file SoapySDRPYTHON_wrap.cxx.
References SWIG_TypeQuery, and SWIGINTERN.
Referenced by _wrap_SoapySDRArgInfoList_begin(), _wrap_SoapySDRArgInfoList_end(), _wrap_SoapySDRArgInfoList_erase(), _wrap_SoapySDRArgInfoList_erase__SWIG_0(), _wrap_SoapySDRArgInfoList_erase__SWIG_1(), _wrap_SoapySDRArgInfoList_insert(), _wrap_SoapySDRArgInfoList_insert__SWIG_0(), _wrap_SoapySDRArgInfoList_insert__SWIG_1(), _wrap_SoapySDRArgInfoList_rbegin(), _wrap_SoapySDRArgInfoList_rend(), _wrap_SoapySDRDoubleList_begin(), _wrap_SoapySDRDoubleList_end(), _wrap_SoapySDRDoubleList_erase(), _wrap_SoapySDRDoubleList_erase__SWIG_0(), _wrap_SoapySDRDoubleList_erase__SWIG_1(), _wrap_SoapySDRDoubleList_insert(), _wrap_SoapySDRDoubleList_insert__SWIG_0(), _wrap_SoapySDRDoubleList_insert__SWIG_1(), _wrap_SoapySDRDoubleList_rbegin(), _wrap_SoapySDRDoubleList_rend(), _wrap_SoapySDRKwargs_begin(), _wrap_SoapySDRKwargs_end(), _wrap_SoapySDRKwargs_erase(), _wrap_SoapySDRKwargs_erase__SWIG_1(), _wrap_SoapySDRKwargs_erase__SWIG_2(), _wrap_SoapySDRKwargs_find(), _wrap_SoapySDRKwargs_lower_bound(), _wrap_SoapySDRKwargs_rbegin(), _wrap_SoapySDRKwargs_rend(), _wrap_SoapySDRKwargs_upper_bound(), _wrap_SoapySDRKwargsList_begin(), _wrap_SoapySDRKwargsList_end(), _wrap_SoapySDRKwargsList_erase(), _wrap_SoapySDRKwargsList_erase__SWIG_0(), _wrap_SoapySDRKwargsList_erase__SWIG_1(), _wrap_SoapySDRKwargsList_insert(), _wrap_SoapySDRKwargsList_insert__SWIG_0(), _wrap_SoapySDRKwargsList_insert__SWIG_1(), _wrap_SoapySDRKwargsList_rbegin(), _wrap_SoapySDRKwargsList_rend(), _wrap_SoapySDRRangeList_begin(), _wrap_SoapySDRRangeList_end(), _wrap_SoapySDRRangeList_erase(), _wrap_SoapySDRRangeList_erase__SWIG_0(), _wrap_SoapySDRRangeList_erase__SWIG_1(), _wrap_SoapySDRRangeList_insert(), _wrap_SoapySDRRangeList_insert__SWIG_0(), _wrap_SoapySDRRangeList_insert__SWIG_1(), _wrap_SoapySDRRangeList_rbegin(), _wrap_SoapySDRRangeList_rend(), _wrap_SoapySDRSizeList_begin(), _wrap_SoapySDRSizeList_end(), _wrap_SoapySDRSizeList_erase(), _wrap_SoapySDRSizeList_erase__SWIG_0(), _wrap_SoapySDRSizeList_erase__SWIG_1(), _wrap_SoapySDRSizeList_insert(), _wrap_SoapySDRSizeList_insert__SWIG_0(), _wrap_SoapySDRSizeList_insert__SWIG_1(), _wrap_SoapySDRSizeList_rbegin(), _wrap_SoapySDRSizeList_rend(), _wrap_SoapySDRStringList_begin(), _wrap_SoapySDRStringList_end(), _wrap_SoapySDRStringList_erase(), _wrap_SoapySDRStringList_erase__SWIG_0(), _wrap_SoapySDRStringList_erase__SWIG_1(), _wrap_SoapySDRStringList_insert(), _wrap_SoapySDRStringList_insert__SWIG_0(), _wrap_SoapySDRStringList_insert__SWIG_1(), _wrap_SoapySDRStringList_rbegin(), _wrap_SoapySDRStringList_rend(), _wrap_SoapySDRUnsignedList_begin(), _wrap_SoapySDRUnsignedList_end(), _wrap_SoapySDRUnsignedList_erase(), _wrap_SoapySDRUnsignedList_erase__SWIG_0(), _wrap_SoapySDRUnsignedList_erase__SWIG_1(), _wrap_SoapySDRUnsignedList_insert(), _wrap_SoapySDRUnsignedList_insert__SWIG_0(), _wrap_SoapySDRUnsignedList_insert__SWIG_1(), _wrap_SoapySDRUnsignedList_rbegin(), and _wrap_SoapySDRUnsignedList_rend().
static swig_type_info* swig::SwigPyIterator::descriptor () inline static
Definition at line 3282 of file radar_swigPYTHON_wrap.cxx.
References SWIG_TypeQuery.
virtual ptrdiff_t swig::SwigPyIterator::distance (const SwigPyIterator &) const inline virtual
Reimplemented in swig::SwigPyIterator_T< OutIterator >, and swig::SwigPyIterator_T< OutIterator >.
Definition at line 3151 of file SoapySDRPYTHON_wrap.cxx.
Referenced by operator-().
virtual ptrdiff_t swig::SwigPyIterator::distance (const SwigPyIterator &) const inline virtual
Reimplemented in swig::SwigPyIterator_T< OutIterator >, and swig::SwigPyIterator_T< OutIterator >.
Definition at line 3205 of file radar_swigPYTHON_wrap.cxx.
virtual bool swig::SwigPyIterator::equal (const SwigPyIterator &) const inline virtual
Reimplemented in swig::SwigPyIterator_T< OutIterator >, and swig::SwigPyIterator_T< OutIterator >.
Definition at line 3156 of file SoapySDRPYTHON_wrap.cxx.
virtual bool swig::SwigPyIterator::equal (const SwigPyIterator &) const inline virtual
Reimplemented in swig::SwigPyIterator_T< OutIterator >, and swig::SwigPyIterator_T< OutIterator >.
Definition at line 3210 of file radar_swigPYTHON_wrap.cxx.
virtual SwigPyIterator* swig::SwigPyIterator::incr (size_t n = 1) pure virtual
Implemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
Referenced by _wrap_SwigPyIterator_incr__SWIG_0(), and _wrap_SwigPyIterator_incr__SWIG_1().
virtual SwigPyIterator* swig::SwigPyIterator::incr (size_t n = 1) pure virtual
Implemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
PyObject* swig::SwigPyIterator::next () inline
Definition at line 3164 of file SoapySDRPYTHON_wrap.cxx.
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
PyObject* swig::SwigPyIterator::next () inline
Definition at line 3218 of file radar_swigPYTHON_wrap.cxx.
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
bool swig::SwigPyIterator::operator!= (const SwigPyIterator & x) const inline
Definition at line 3198 of file SoapySDRPYTHON_wrap.cxx.
References operator==().
bool swig::SwigPyIterator::operator!= (const SwigPyIterator & x) const inline
Definition at line 3252 of file radar_swigPYTHON_wrap.cxx.
References operator==().
SwigPyIterator* swig::SwigPyIterator::operator+ (ptrdiff_t n) const inline
Definition at line 3213 of file SoapySDRPYTHON_wrap.cxx.
References advance().
SwigPyIterator* swig::SwigPyIterator::operator+ (ptrdiff_t n) const inline
Definition at line 3267 of file radar_swigPYTHON_wrap.cxx.
References advance().
SwigPyIterator& swig::SwigPyIterator::operator+= (ptrdiff_t n) inline
Definition at line 3203 of file SoapySDRPYTHON_wrap.cxx.
SwigPyIterator& swig::SwigPyIterator::operator+= (ptrdiff_t n) inline
Definition at line 3257 of file radar_swigPYTHON_wrap.cxx.
SwigPyIterator* swig::SwigPyIterator::operator- (ptrdiff_t n) const inline
Definition at line 3218 of file SoapySDRPYTHON_wrap.cxx.
References advance().
ptrdiff_t swig::SwigPyIterator::operator- (const SwigPyIterator & x) const inline
Definition at line 3223 of file SoapySDRPYTHON_wrap.cxx.
References distance().
SwigPyIterator* swig::SwigPyIterator::operator- (ptrdiff_t n) const inline
Definition at line 3272 of file radar_swigPYTHON_wrap.cxx.
References advance().
ptrdiff_t swig::SwigPyIterator::operator- (const SwigPyIterator & x) const inline
Definition at line 3277 of file radar_swigPYTHON_wrap.cxx.
SwigPyIterator& swig::SwigPyIterator::operator-= (ptrdiff_t n) inline
Definition at line 3208 of file SoapySDRPYTHON_wrap.cxx.
SwigPyIterator& swig::SwigPyIterator::operator-= (ptrdiff_t n) inline
Definition at line 3262 of file radar_swigPYTHON_wrap.cxx.
bool swig::SwigPyIterator::operator== (const SwigPyIterator & x) const inline
Definition at line 3193 of file SoapySDRPYTHON_wrap.cxx.
bool swig::SwigPyIterator::operator== (const SwigPyIterator & x) const inline
Definition at line 3247 of file radar_swigPYTHON_wrap.cxx.
PyObject* swig::SwigPyIterator::previous () inline
Definition at line 3179 of file SoapySDRPYTHON_wrap.cxx.
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
PyObject* swig::SwigPyIterator::previous () inline
Definition at line 3233 of file radar_swigPYTHON_wrap.cxx.
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
virtual PyObject* swig::SwigPyIterator::value () const pure virtual
Implemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
virtual PyObject* swig::SwigPyIterator::value () const pure virtual
Implemented in swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, ValueType, FromOper >, swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >, and swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >.
Member Data Documentation
SwigPtr_PyObject swig::SwigPyIterator::_seq private
Definition at line 3128 of file SoapySDRPYTHON_wrap.cxx.
The documentation for this struct was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDRPYTHON_wrap.cxx
/home/erik/prefix/default/src/gr-radar-dev/build/swig/radar_swigPYTHON_wrap.cxx