LimeSuite-UML: Myriad7_wxgui Class Reference
Myriad7_wxgui Class Reference
#include <myriad7_wxgui.h>
Public Member Functions
Myriad7_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long styles=0)
void Initialize (lms_device_t *serPort)
virtual ~Myriad7_wxgui ()
virtual void UpdatePanel ()
void ParameterChangeHandler (wxCommandEvent &event)
Public Attributes
wxStaticText * StaticText2
wxComboBox * cmbGPIO2
wxStaticText * StaticText1
wxComboBox * cmbGPIO_1_0
Static Public Attributes
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_COMBOBOX1 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_COMBOBOX2 = wxNewId()
Protected Attributes
lms_device_t * lmsControl
Detailed Description
Definition at line 14 of file myriad7_wxgui.h.
Constructor & Destructor Documentation
Myriad7_wxgui::Myriad7_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long styles = 0)
Definition at line 26 of file myriad7_wxgui.cpp.
References _T, and ParameterChangeHandler().
Myriad7_wxgui::~Myriad7_wxgui () virtual
Definition at line 60 of file myriad7_wxgui.cpp.
Member Function Documentation
void Myriad7_wxgui::Initialize (lms_device_t * serPort)
Definition at line 64 of file myriad7_wxgui.cpp.
References lmsControl.
Referenced by LMS7SuiteAppFrame::OnShowMyriad7(), and LMS7SuiteAppFrame::UpdateConnections().
void Myriad7_wxgui::ParameterChangeHandler (wxCommandEvent & event)
Definition at line 69 of file myriad7_wxgui.cpp.
References LMS_GPIOWrite(), lmsControl, and status.
Referenced by Myriad7_wxgui().
void Myriad7_wxgui::UpdatePanel () virtual
Definition at line 87 of file myriad7_wxgui.cpp.
References lime::EXP_BOARD_MYRIAD7, lms_dev_info_t::expansionName, lime::GetExpansionBoardName(), lime::info(), LMS_GetDeviceInfo(), LMS_GPIORead(), lmsControl, and status.
Member Data Documentation
wxComboBox* Myriad7_wxgui::cmbGPIO2
Definition at line 24 of file myriad7_wxgui.h.
wxComboBox* Myriad7_wxgui::cmbGPIO_1_0
Definition at line 26 of file myriad7_wxgui.h.
const long Myriad7_wxgui::ID_COMBOBOX1 = wxNewId() static
Definition at line 29 of file myriad7_wxgui.h.
const long Myriad7_wxgui::ID_COMBOBOX2 = wxNewId() static
Definition at line 31 of file myriad7_wxgui.h.
const long Myriad7_wxgui::ID_STATICTEXT1 = wxNewId() static
Definition at line 28 of file myriad7_wxgui.h.
const long Myriad7_wxgui::ID_STATICTEXT2 = wxNewId() static
Definition at line 30 of file myriad7_wxgui.h.
lms_device_t* Myriad7_wxgui::lmsControl protected
Definition at line 35 of file myriad7_wxgui.h.
wxStaticText* Myriad7_wxgui::StaticText1
Definition at line 25 of file myriad7_wxgui.h.
wxStaticText* Myriad7_wxgui::StaticText2
Definition at line 23 of file myriad7_wxgui.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/myriad7/myriad7_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/myriad7/myriad7_wxgui.cpp