LimeSuite-UML: pnlMiniLog_view Class Reference
pnlMiniLog_view Class Reference
Class pnlMiniLog_view.
#include <utilities_gui.h>
Public Member Functions
pnlMiniLog_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxTAB_TRAVERSAL)
~pnlMiniLog_view ()
Public Attributes
wxCheckBox * chkLogData
Protected Member Functions
virtual void OnUpdateGUI (wxUpdateUIEvent &event)
virtual void OnBtnClearClicked (wxCommandEvent &event)
virtual void OnShowFullLog (wxCommandEvent &event)
virtual void OnLogDataClicked (wxCommandEvent &event)
virtual void onLogLvlChange (wxCommandEvent &event)
Protected Attributes
wxTextCtrl * txtMessageField
wxButton * btnClear
wxButton * btnFullLog
wxChoice * choiceLogLvl
Detailed Description
Class pnlMiniLog_view.
Definition at line 63 of file utilities_gui.h.
Constructor & Destructor Documentation
pnlMiniLog_view::pnlMiniLog_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(-1,-1), long style = wxTAB_TRAVERSAL)
Definition at line 86 of file utilities_gui.cpp.
References btnClear, btnFullLog, chkLogData, choiceLogLvl, OnBtnClearClicked(), OnLogDataClicked(), onLogLvlChange(), OnShowFullLog(), OnUpdateGUI(), and txtMessageField.
pnlMiniLog_view::~pnlMiniLog_view ()
Definition at line 153 of file utilities_gui.cpp.
References btnClear, btnFullLog, chkLogData, choiceLogLvl, OnBtnClearClicked(), OnLogDataClicked(), onLogLvlChange(), OnShowFullLog(), and OnUpdateGUI().
Member Function Documentation
virtual void pnlMiniLog_view::OnBtnClearClicked (wxCommandEvent & event) inline protected virtual
Reimplemented in pnlMiniLog.
Definition at line 75 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
virtual void pnlMiniLog_view::OnLogDataClicked (wxCommandEvent & event) inline protected virtual
Definition at line 77 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
virtual void pnlMiniLog_view::onLogLvlChange (wxCommandEvent & event) inline protected virtual
Reimplemented in pnlMiniLog.
Definition at line 78 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
virtual void pnlMiniLog_view::OnShowFullLog (wxCommandEvent & event) inline protected virtual
Reimplemented in pnlMiniLog.
Definition at line 76 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
virtual void pnlMiniLog_view::OnUpdateGUI (wxUpdateUIEvent & event) inline protected virtual
Reimplemented in pnlMiniLog.
Definition at line 74 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
Member Data Documentation
wxButton* pnlMiniLog_view::btnClear protected
Definition at line 69 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
wxButton* pnlMiniLog_view::btnFullLog protected
Definition at line 70 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
wxCheckBox* pnlMiniLog_view::chkLogData
Definition at line 82 of file utilities_gui.h.
Referenced by LMS7SuiteAppFrame::OnLogDataTransfer(), pnlMiniLog_view(), and ~pnlMiniLog_view().
wxChoice* pnlMiniLog_view::choiceLogLvl protected
Definition at line 71 of file utilities_gui.h.
Referenced by pnlMiniLog_view(), and ~pnlMiniLog_view().
wxTextCtrl* pnlMiniLog_view::txtMessageField protected
Definition at line 68 of file utilities_gui.h.
Referenced by pnlMiniLog::HandleMessage(), pnlMiniLog::OnBtnClearClicked(), pnlMiniLog::pnlMiniLog(), and pnlMiniLog_view().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/utilities_gui.h
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/utilities_gui.cpp