LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/protocols/LMS64CProtocol.cpp File Reference
LMS64CProtocol.cpp File Reference
Implementation of LMS64C protocol.
#include "Logger.h"
#include "LMS64CProtocol.h"
#include "Si5351C.h"
#include <chrono>
#include <iostream>
#include <assert.h>
#include <math.h>
#include <algorithm>
#include <iso646.h>
#include <ADCUnits.h>
#include <sstream>
Macros
#define LMS7002M_SPI_INDEX 0x10
arbitrary spi constants used to dispatch calls
#define ADF4002_SPI_INDEX 0x30
Functions
static int convertStatus (const int &status, const LMS64CProtocol::GenericPacket &pkt)
Variables
const int LMS_RST_DEACTIVATE = 0
CMD_LMS7002_RST options.
const int LMS_RST_ACTIVATE = 1
const int LMS_RST_PULSE = 2
Detailed Description
Implementation of LMS64C protocol.
Author
Lime Microsystems
Definition in file LMS64CProtocol.cpp.
Macro Definition Documentation
#define ADF4002_SPI_INDEX 0x30
Definition at line 27 of file LMS64CProtocol.cpp.
Referenced by lime::LMS64CProtocol::TransactSPI().
#define LMS7002M_SPI_INDEX 0x10
arbitrary spi constants used to dispatch calls
Definition at line 26 of file LMS64CProtocol.cpp.
Referenced by lime::LMS64CProtocol::TransactSPI().
Function Documentation
static int convertStatus (const int & status, const LMS64CProtocol::GenericPacket & pkt) static
Definition at line 29 of file LMS64CProtocol.cpp.
References lime::ReportError(), lime::LMS64CProtocol::GenericPacket::status, lime::status2string(), lime::STATUS_COMPLETED_CMD, and lime::STATUS_UNKNOWN_CMD.
Referenced by lime::LMS64CProtocol::DeviceReset(), lime::LMS64CProtocol::GPIODirRead(), lime::LMS64CProtocol::ReadLMS7002MSPI(), lime::LMS64CProtocol::ReadRegisters(), lime::LMS64CProtocol::ReadSi5351I2C(), lime::LMS64CProtocol::TransferPacket(), lime::LMS64CProtocol::WriteADF4002SPI(), lime::LMS64CProtocol::WriteLMS7002MSPI(), lime::LMS64CProtocol::WriteRegisters(), and lime::LMS64CProtocol::WriteSi5351I2C().
Variable Documentation
const int LMS_RST_ACTIVATE = 1
Definition at line 22 of file LMS64CProtocol.cpp.
const int LMS_RST_DEACTIVATE = 0
CMD_LMS7002_RST options.
Definition at line 21 of file LMS64CProtocol.cpp.
const int LMS_RST_PULSE = 2
Definition at line 23 of file LMS64CProtocol.cpp.
Referenced by lime::LMS64CProtocol::DeviceReset().