LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/SoapyLMS7/Registration.cpp File Reference
Registration.cpp File Reference
Soapy SDR + IConnection module registration.
#include "SoapyLMS7.h"
#include <SoapySDR/Registry.hpp>
#include <SoapySDR/Logger.hpp>
#include "Logger.h"
Functions
static void limeSuiteLogHandler (const lime::LogLevel level, const char *message)
static ConnectionHandle argsToHandle (const SoapySDR::Kwargs &args)
static SoapySDR::Kwargs handleToArgs (const ConnectionHandle &handle)
static SoapySDR::KwargsList findIConnection (const SoapySDR::Kwargs &matchArgs)
static SoapySDR::Device * makeIConnection (const SoapySDR::Kwargs &args)
Variables
static SoapySDR::Registry registerIConnection ("lime",&findIConnection,&makeIConnection, SOAPY_SDR_ABI_VERSION)
Detailed Description
Soapy SDR + IConnection module registration.
Author
Lime Microsystems (www.limemicro.com)
Definition in file Registration.cpp.
Function Documentation
static ConnectionHandle argsToHandle (const SoapySDR::Kwargs & args) static
Definition at line 26 of file Registration.cpp.
References lime::ConnectionHandle::addr, lime::ConnectionHandle::index, lime::ConnectionHandle::media, lime::ConnectionHandle::module, lime::ConnectionHandle::name, and lime::ConnectionHandle::serial.
Referenced by findIConnection(), and makeIConnection().
static SoapySDR::KwargsList findIConnection (const SoapySDR::Kwargs & matchArgs) static
Definition at line 59 of file Registration.cpp.
References argsToHandle(), lime::ConnectionRegistry::findConnections(), handleToArgs(), limeSuiteLogHandler(), and lime::registerLogHandler().
Referenced by makeIConnection().
static SoapySDR::Kwargs handleToArgs (const ConnectionHandle & handle) static
Definition at line 41 of file Registration.cpp.
References lime::ConnectionHandle::addr, args, if(), lime::ConnectionHandle::index, lime::ConnectionHandle::media, lime::ConnectionHandle::module, lime::ConnectionHandle::name, lime::ConnectionHandle::serial, and lime::ConnectionHandle::ToString().
Referenced by findIConnection().
static void limeSuiteLogHandler (const lime::LogLevel level, const char * message) static
Definition at line 14 of file Registration.cpp.
References SoapySDR::log, lime::LOG_LEVEL_CRITICAL, lime::LOG_LEVEL_DEBUG, lime::LOG_LEVEL_ERROR, lime::LOG_LEVEL_INFO, lime::LOG_LEVEL_WARNING, SOAPY_SDR_CRITICAL, SOAPY_SDR_DEBUG, SOAPY_SDR_ERROR, SOAPY_SDR_INFO, and SOAPY_SDR_WARNING.
Referenced by findIConnection(), and makeIConnection().
static SoapySDR::Device* makeIConnection (const SoapySDR::Kwargs & args) static
Definition at line 70 of file Registration.cpp.
References argsToHandle(), findIConnection(), limeSuiteLogHandler(), registerIConnection, lime::registerLogHandler(), and SOAPY_SDR_ABI_VERSION.
Variable Documentation
SoapySDR::Registry registerIConnection("lime",&findIConnection,&makeIConnection, SOAPY_SDR_ABI_VERSION) static
Referenced by makeIConnection().