LimeSuite-UML: SoapyLMS7 Class Reference
SoapyLMS7 Class Reference
#include <SoapyLMS7.h>
Public Member Functions
SoapyLMS7 (const lime::ConnectionHandle &handle, const SoapySDR::Kwargs &args)
~SoapyLMS7 (void)
std::string getDriverKey (void) const
std::string getHardwareKey (void) const
SoapySDR::Kwargs getHardwareInfo (void) const
size_t getNumChannels (const int direction) const
bool getFullDuplex (const int direction, const size_t channel) const
std::vector< std::string > getStreamFormats (const int direction, const size_t channel) const
std::string getNativeStreamFormat (const int direction, const size_t channel, double &fullScale) const
SoapySDR::ArgInfoList getStreamArgsInfo (const int direction, const size_t channel) const
SoapySDR::Stream * setupStream (const int direction, const std::string &format, const std::vector< size_t > &channels=std::vector< size_t >(), const SoapySDR::Kwargs &args=SoapySDR::Kwargs())
void closeStream (SoapySDR::Stream *stream)
size_t getStreamMTU (SoapySDR::Stream *stream) const
int activateStream (SoapySDR::Stream *stream, const int flags=0, const long long timeNs=0, const size_t numElems=0)
int deactivateStream (SoapySDR::Stream *stream, const int flags=0, const long long timeNs=0)
int readStream (SoapySDR::Stream *stream, void *const *buffs, const size_t numElems, int &flags, long long &timeNs, const long timeoutUs=100000)
int _readStreamAligned (IConnectionStream *stream, char *const *buffs, size_t numElems, uint64_t requestTime, lime::StreamChannel::Metadata &mdOut, const long timeoutMs)
int writeStream (SoapySDR::Stream *stream, const void *const *buffs, const size_t numElems, int &flags, const long long timeNs=0, const long timeoutUs=100000)
int readStreamStatus (SoapySDR::Stream *stream, size_t &chanMask, int &flags, long long &timeNs, const long timeoutUs=100000)
std::vector< std::string > listAntennas (const int direction, const size_t channel) const
void setAntenna (const int direction, const size_t channel, const std::string &name)
std::string getAntenna (const int direction, const size_t channel) const
bool hasDCOffsetMode (const int direction, const size_t channel) const
void setDCOffsetMode (const int direction, const size_t channel, const bool automatic)
bool getDCOffsetMode (const int direction, const size_t channel) const
bool hasDCOffset (const int direction, const size_t channel) const
bool hasIQBalance (const int direction, const size_t channel) const
std::vector< std::string > listGains (const int direction, const size_t channel) const
void setGain (const int direction, const size_t channel, const double value) override
double getGain (const int direction, const size_t channel) const
void setGain (const int direction, const size_t channel, const std::string &name, const double value)
double getGain (const int direction, const size_t channel, const std::string &name) const
SoapySDR::Range getGainRange (const int direction, const size_t channel) const
SoapySDR::Range getGainRange (const int direction, const size_t channel, const std::string &name) const
SoapySDR::ArgInfoList getFrequencyArgsInfo (const int direction, const size_t channel) const
void setFrequency (const int direction, const size_t channel, const double frequency, const SoapySDR::Kwargs &args=SoapySDR::Kwargs())
void setFrequency (const int direction, const size_t channel, const std::string &name, const double frequency, const SoapySDR::Kwargs &args=SoapySDR::Kwargs())
double getFrequency (const int direction, const size_t channel, const std::string &name) const
double getFrequency (const int direction, const size_t channel) const override
std::vector< std::string > listFrequencies (const int direction, const size_t channel) const
SoapySDR::RangeList getFrequencyRange (const int direction, const size_t channel) const
SoapySDR::RangeList getFrequencyRange (const int direction, const size_t channel, const std::string &name) const
void setSampleRate (const int direction, const size_t channel, const double rate)
double getSampleRate (const int direction, const size_t channel) const
std::vector< double > listSampleRates (const int direction, const size_t channel) const
SoapySDR::RangeList getSampleRateRange (const int direction, const size_t channel) const
void setBandwidth (const int direction, const size_t channel, const double bw)
double getBandwidth (const int direction, const size_t channel) const
SoapySDR::RangeList getBandwidthRange (const int direction, const size_t channel) const
void setMasterClockRate (const double rate)
double getMasterClockRate (void) const
SoapySDR::RangeList getMasterClockRates (void) const
bool hasHardwareTime (const std::string &what="") const
long long getHardwareTime (const std::string &what="") const
void setHardwareTime (const long long timeNs, const std::string &what="")
std::vector< std::string > listSensors (void) const
SoapySDR::ArgInfo getSensorInfo (const std::string &name) const
std::string readSensor (const std::string &name) const
std::vector< std::string > listSensors (const int direction, const size_t channel) const
SoapySDR::ArgInfo getSensorInfo (const int direction, const size_t channel, const std::string &name) const
std::string readSensor (const int direction, const size_t channel, const std::string &name) const
std::vector< std::string > listRegisterInterfaces (void) const
void writeRegister (const std::string &name, const unsigned addr, const unsigned value)
unsigned readRegister (const std::string &name, const unsigned addr) const
void writeRegister (const unsigned addr, const unsigned value)
unsigned readRegister (const unsigned addr) const
SoapySDR::ArgInfoList getSettingInfo (void) const
void writeSetting (const std::string &key, const std::string &value)
SoapySDR::ArgInfoList getSettingInfo (const int direction, const size_t channel) const
void writeSetting (const int direction, const size_t channel, const std::string &key, const std::string &value)
std::string readSetting (const std::string &key) const
std::string readSetting (const int direction, const size_t channel, const std::string &key) const
std::vector< std::string > listGPIOBanks (void) const
void writeGPIO (const std::string &bank, const unsigned value)
unsigned readGPIO (const std::string &bank) const
void writeGPIODir (const std::string &bank, const unsigned dir)
unsigned readGPIODir (const std::string &bank) const
Public Member Functions inherited from SoapySDR.Device
def __init__ (self, args, kwargs)
def getDriverKey (self)
def getHardwareKey (self)
def getHardwareInfo (self)
def setFrontendMapping (self, args)
def getFrontendMapping (self, args)
def getNumChannels (self, args)
def getChannelInfo (self, args)
def getFullDuplex (self, args)
def getStreamFormats (self, args)
def getNativeStreamFormat (self, args)
def getStreamArgsInfo (self, args)
def setupStream (self, args)
def closeStream (self, args)
def getStreamMTU (self, args)
def activateStream (self, args)
def deactivateStream (self, args)
def readStream (self, args)
def writeStream (self, args)
def readStreamStatus (self, args)
def getNumDirectAccessBuffers (self, args)
def getDirectAccessBufferAddrs (self, args)
def acquireReadBuffer (self, args)
def releaseReadBuffer (self, args)
def acquireWriteBuffer (self, args)
def releaseWriteBuffer (self, args)
def listAntennas (self, args)
def setAntenna (self, args)
def getAntenna (self, args)
def hasDCOffsetMode (self, args)
def setDCOffsetMode (self, args)
def getDCOffsetMode (self, args)
def hasDCOffset (self, args)
def setDCOffset (self, args)
def getDCOffset (self, args)
def hasIQBalance (self, args)
def setIQBalance (self, args)
def getIQBalance (self, args)
def hasFrequencyCorrection (self, args)
def setFrequencyCorrection (self, args)
def getFrequencyCorrection (self, args)
def listGains (self, args)
def hasGainMode (self, args)
def setGainMode (self, args)
def getGainMode (self, args)
def setGain (self, args)
def getGain (self, args)
def getGainRange (self, args)
def setFrequency (self, args)
def getFrequency (self, args)
def listFrequencies (self, args)
def getFrequencyRange (self, args)
def getFrequencyArgsInfo (self, args)
def setSampleRate (self, args)
def getSampleRate (self, args)
def listSampleRates (self, args)
def getSampleRateRange (self, args)
def setBandwidth (self, args)
def getBandwidth (self, args)
def listBandwidths (self, args)
def getBandwidthRange (self, args)
def setMasterClockRate (self, args)
def getMasterClockRate (self)
def getMasterClockRates (self)
def listClockSources (self)
def setClockSource (self, args)
def getClockSource (self)
def listTimeSources (self)
def setTimeSource (self, args)
def getTimeSource (self)
def hasHardwareTime (self, what="")
def getHardwareTime (self, what="")
def setHardwareTime (self, args)
def setCommandTime (self, args)
def listSensors (self, args)
def getSensorInfo (self, args)
def readSensor (self, args)
def listRegisterInterfaces (self)
def writeRegister (self, args)
def readRegister (self, args)
def writeRegisters (self, args)
def readRegisters (self, args)
def getSettingInfo (self, args)
def writeSetting (self, args)
def readSetting (self, args)
def listGPIOBanks (self)
def writeGPIO (self, args)
def readGPIO (self, args)
def writeGPIODir (self, args)
def readGPIODir (self, args)
def writeI2C (self, args)
def readI2C (self, args)
def transactSPI (self, args)
def listUARTs (self)
def writeUART (self, args)
def readUART (self, args)
def readStream__ (self, args)
def writeStream__ (self, args)
def readStreamStatus__ (self, args)
def __del__ (self)
def __str__ (self)
def readStream (self, stream, buffs, numElems, flags=0, timeoutUs=100000)
def writeStream (self, stream, buffs, numElems, flags=0, timeNs=0, timeoutUs=100000)
def readStreamStatus (self, stream, timeoutUs=100000)
def __new__ (cls, args, kwargs)
virtual ~Device (void)
virtual destructor for inheritance
virtual void setFrontendMapping (const int direction, const std::string &mapping)
virtual std::string getFrontendMapping (const int direction) const
virtual Kwargs getChannelInfo (const int direction, const size_t channel) const
virtual Stream * setupStream (const int direction, const std::string &format, const std::vector< size_t > &channels=std::vector< size_t >(), const Kwargs &args=Kwargs())
virtual void closeStream (Stream *stream)
virtual size_t getStreamMTU (Stream *stream) const
virtual int activateStream (Stream *stream, const int flags=0, const long long timeNs=0, const size_t numElems=0)
virtual int deactivateStream (Stream *stream, const int flags=0, const long long timeNs=0)
virtual int readStream (Stream *stream, void *const *buffs, const size_t numElems, int &flags, long long &timeNs, const long timeoutUs=100000)
virtual int writeStream (Stream *stream, const void *const *buffs, const size_t numElems, int &flags, const long long timeNs=0, const long timeoutUs=100000)
virtual int readStreamStatus (Stream *stream, size_t &chanMask, int &flags, long long &timeNs, const long timeoutUs=100000)
virtual size_t getNumDirectAccessBuffers (Stream *stream)
virtual int getDirectAccessBufferAddrs (Stream *stream, const size_t handle, void **buffs)
virtual int acquireReadBuffer (Stream *stream, size_t &handle, const void **buffs, int &flags, long long &timeNs, const long timeoutUs=100000)
virtual void releaseReadBuffer (Stream *stream, const size_t handle)
virtual int acquireWriteBuffer (Stream *stream, size_t &handle, void **buffs, const long timeoutUs=100000)
virtual void releaseWriteBuffer (Stream *stream, const size_t handle, const size_t numElems, int &flags, const long long timeNs=0)
virtual void setDCOffset (const int direction, const size_t channel, const std::complex< double > &offset)
virtual std::complex< double > getDCOffset (const int direction, const size_t channel) const
virtual void setIQBalance (const int direction, const size_t channel, const std::complex< double > &balance)
virtual std::complex< double > getIQBalance (const int direction, const size_t channel) const
virtual bool hasFrequencyCorrection (const int direction, const size_t channel) const
virtual void setFrequencyCorrection (const int direction, const size_t channel, const double value)
virtual double getFrequencyCorrection (const int direction, const size_t channel) const
virtual bool hasGainMode (const int direction, const size_t channel) const
virtual void setGainMode (const int direction, const size_t channel, const bool automatic)
virtual bool getGainMode (const int direction, const size_t channel) const
virtual void setFrequency (const int direction, const size_t channel, const double frequency, const Kwargs &args=Kwargs())
virtual void setFrequency (const int direction, const size_t channel, const std::string &name, const double frequency, const Kwargs &args=Kwargs())
virtual std::vector< double > listBandwidths (const int direction, const size_t channel) const
virtual std::vector< std::string > listClockSources (void) const
virtual void setClockSource (const std::string &source)
virtual std::string getClockSource (void) const
virtual std::vector< std::string > listTimeSources (void) const
virtual void setTimeSource (const std::string &source)
virtual std::string getTimeSource (void) const
virtual void setCommandTime (const long long timeNs, const std::string &what="")
virtual void writeRegisters (const std::string &name, const unsigned addr, const std::vector< unsigned > &value)
virtual std::vector< unsigned > readRegisters (const std::string &name, const unsigned addr, const size_t length) const
virtual void writeGPIO (const std::string &bank, const unsigned value, const unsigned mask)
virtual void writeGPIODir (const std::string &bank, const unsigned dir, const unsigned mask)
virtual void writeI2C (const int addr, const std::string &data)
virtual std::string readI2C (const int addr, const size_t numBytes)
virtual unsigned transactSPI (const int addr, const unsigned data, const size_t numBits)
virtual std::vector< std::string > listUARTs (void) const
virtual void writeUART (const std::string &which, const std::string &data)
virtual std::string readUART (const std::string &which, const long timeoutUs=100000) const
Public Attributes
std::map< size_t, int > _interps
std::map< size_t, int > _decims
std::map< int, std::map< size_t, double > > _actualBw
Private Attributes
const SoapySDR::Kwargs _deviceArgs
stash of constructor arguments
const std::string _moduleName
lime::LMS7_Device * lms7Device
double sampleRate
std::set< std::pair< int, size_t > > _channelsToCal
std::recursive_mutex _accessMutex
Additional Inherited Members
Static Public Member Functions inherited from SoapySDR.Device
static KwargsList enumerate (const Kwargs &args=Kwargs())
static KwargsList enumerate (const std::string &args)
static Device * make (const Kwargs &args=Kwargs())
static Device * make (const std::string &args)
static void unmake (Device *device)
Static Public Attributes inherited from SoapySDR.Device
enumerate
make
unmake
Detailed Description
Definition at line 23 of file SoapyLMS7.h.
Constructor & Destructor Documentation
SoapyLMS7::SoapyLMS7 (const lime::ConnectionHandle & handle, const SoapySDR::Kwargs & args)
Definition at line 34 of file Settings.cpp.
References _actualBw, _channelsToCal, DEFAULT_CLOCK_RATE, lms7Device, LMS_CLOCK_REF, SoapySDR::logf(), lime::ConnectionHandle::serialize(), setGain(), setMasterClockRate(), SOAPY_SDR_INFO, SOAPY_SDR_RX, SOAPY_SDR_TX, and lime::ConnectionHandle::ToString().
SoapyLMS7::~SoapyLMS7 (void)
Definition at line 81 of file Settings.cpp.
References lime::LMS7_Device::EnableChannel(), lime::LMS7_Device::GetNumChannels(), and lms7Device.
Member Function Documentation
int SoapyLMS7::_readStreamAligned (IConnectionStream * stream, char *const * buffs, size_t numElems, uint64_t requestTime, lime::StreamChannel::Metadata & mdOut, const long timeoutMs)
Definition at line 260 of file Streaming.cpp.
References IConnectionStream::elemSize, fastForward(), i, int(), SoapySDR::log, SOAPY_SDR_CORRUPTION, SOAPY_SDR_ERROR, SOAPY_SDR_STREAM_ERROR, SOAPY_SDR_TIMEOUT, status, IConnectionStream::streamID, and lime::StreamChannel::Metadata::timestamp.
int SoapyLMS7::activateStream (SoapySDR::Stream * stream, const int flags = 0, const long long timeNs = 0, const size_t numElems = 0)
Definition at line 192 of file Streaming.cpp.
References flags, i, SOAPY_SDR_STREAM_ERROR, SOAPY_SDR_TX, and status.
void SoapyLMS7::closeStream (SoapySDR::Stream * stream)
Definition at line 172 of file Streaming.cpp.
References i.
int SoapyLMS7::deactivateStream (SoapySDR::Stream * stream, const int flags = 0, const long long timeNs = 0)
Definition at line 228 of file Streaming.cpp.
References i, SOAPY_SDR_STREAM_ERROR, and status.
std::string SoapyLMS7::getAntenna (const int direction, const size_t channel) const virtual
Get the selected antenna on a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the name of an available antenna
Reimplemented from SoapySDR.Device.
Definition at line 165 of file Settings.cpp.
References _accessMutex, lime::LMS7_Device::GetPath(), lime::LMS7_Device::GetPathNames(), lms7Device, SOAPY_SDR_TX, and tx.
double SoapyLMS7::getBandwidth (const int direction, const size_t channel) const virtual
Get the baseband filter width of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the baseband filter width in Hz
Reimplemented from SoapySDR.Device.
Definition at line 432 of file Settings.cpp.
References _accessMutex, and _actualBw.
SoapySDR::RangeList SoapyLMS7::getBandwidthRange (const int direction, const size_t channel) const virtual
Get the range of possible baseband filter widths.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of bandwidth ranges in Hz
Reimplemented from SoapySDR.Device.
Definition at line 445 of file Settings.cpp.
References SOAPY_SDR_RX, and SOAPY_SDR_TX.
bool SoapyLMS7::getDCOffsetMode (const int direction, const size_t channel) const virtual
Get the automatic DC offset corrections mode.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true for automatic offset correction
Reimplemented from SoapySDR.Device.
Definition at line 193 of file Settings.cpp.
References _accessMutex, DC_BYP_RXTSP, lms7Device, LMS7param, lime::LMS7_Device::ReadParam(), and SOAPY_SDR_RX.
std::string SoapyLMS7::getDriverKey (void) const virtual
A key that uniquely identifies the device driver. This key identifies the underlying implementation. Serveral variants of a product may share a driver.
Reimplemented from SoapySDR.Device.
Definition at line 95 of file Settings.cpp.
References _moduleName.
Referenced by SoapySDR.Device::__str__().
double SoapyLMS7::getFrequency (const int direction, const size_t channel, const std::string & name) const virtual
Get the frequency of a tunable element in the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of a tunable element
Returns
the tunable element's frequency in Hz
Reimplemented from SoapySDR.Device.
Definition at line 310 of file Settings.cpp.
References _accessMutex, freq, lime::LMS7_Device::GetClockFreq(), lime::LMS7_Device::GetNCOFreq(), lms7Device, LMS_CLOCK_SXR, LMS_CLOCK_SXT, and SOAPY_SDR_TX.
double SoapyLMS7::getFrequency (const int direction, const size_t channel) const override virtual
Get the overall center frequency of the chain.
For RX, this specifies the down-conversion frequency.
For TX, this specifies the up-conversion frequency.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the center frequency in Hz
Reimplemented from SoapySDR.Device.
Definition at line 330 of file Settings.cpp.
References _accessMutex, lime::LMS7_Device::GetFrequency(), lms7Device, and SOAPY_SDR_TX.
SoapySDR::ArgInfoList SoapyLMS7::getFrequencyArgsInfo (const int direction, const size_t channel) const virtual
Query the argument info description for tune args.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of argument info structures
Reimplemented from SoapySDR.Device.
Definition at line 277 of file Settings.cpp.
References _accessMutex, _channelsToCal, args, dirName, frequency, SoapySDR.Device::getFrequencyArgsInfo(), lms7Device, LMS_CLOCK_SXR, LMS_CLOCK_SXT, SoapySDR::logf(), lime::LMS7_Device::SetClockFreq(), lime::LMS7_Device::SetFrequency(), setFrequency(), lime::LMS7_Device::SetNCOFreq(), SOAPY_SDR_DEBUG, SOAPY_SDR_TX, and string().
SoapySDR::RangeList SoapyLMS7::getFrequencyRange (const int direction, const size_t channel) const virtual
Get the range of overall frequency values.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of frequency ranges in Hz
Reimplemented from SoapySDR.Device.
Definition at line 362 of file Settings.cpp.
SoapySDR::RangeList SoapyLMS7::getFrequencyRange (const int direction, const size_t channel, const std::string & name) const virtual
Get the range of tunable values for the specified element.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of a tunable element
Returns
a list of frequency ranges in Hz
Reimplemented from SoapySDR.Device.
Definition at line 344 of file Settings.cpp.
References _accessMutex, lime::LMS7_Device::GetClockFreq(), lms7Device, LMS_CLOCK_RXTSP, LMS_CLOCK_TXTSP, and SOAPY_SDR_TX.
bool SoapyLMS7::getFullDuplex (const int direction, const size_t channel) const virtual
Find out if the specified channel is full or half duplex.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true for full duplex, false for half duplex
Reimplemented from SoapySDR.Device.
Definition at line 132 of file Settings.cpp.
double SoapyLMS7::getGain (const int direction, const size_t channel) const virtual
Get the overall value of the gain elements in a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the value of the gain in dB
Reimplemented from SoapySDR.Device.
Definition at line 240 of file Settings.cpp.
References lime::LMS7_Device::GetGain(), lms7Device, and SOAPY_SDR_TX.
Referenced by setGain().
double SoapyLMS7::getGain (const int direction, const size_t channel, const std::string & name) const virtual
Get the value of an individual amplification element in a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an amplification element
Returns
the value of the gain in dB
Reimplemented from SoapySDR.Device.
Definition at line 255 of file Settings.cpp.
References _accessMutex, lime::LMS7_Device::GetGain(), lms7Device, and SOAPY_SDR_TX.
SoapySDR::Range SoapyLMS7::getGainRange (const int direction, const size_t channel) const virtual
Get the overall range of possible gain values.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of gain ranges in dB
Reimplemented from SoapySDR.Device.
Definition at line 262 of file Settings.cpp.
References lime::LMS7_Device::GetGainRange(), lms7Device, lms_range_t::max, lms_range_t::min, range, and SOAPY_SDR_TX.
SoapySDR::Range SoapyLMS7::getGainRange (const int direction, const size_t channel, const std::string & name) const virtual
Get the range of possible gain values for a specific element.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an amplification element
Returns
a list of gain ranges in dB
Reimplemented from SoapySDR.Device.
Definition at line 268 of file Settings.cpp.
References lime::LMS7_Device::GetGainRange(), lms7Device, lms_range_t::max, lms_range_t::min, range, and SOAPY_SDR_TX.
SoapySDR::Kwargs SoapyLMS7::getHardwareInfo (void) const virtual
Query a dictionary of available device information. This dictionary can any number of values like vendor name, product name, revisions, serials... This information can be displayed to the user to help identify the instantiated device.
Reimplemented from SoapySDR.Device.
Definition at line 105 of file Settings.cpp.
References lime::LMS7_Device::GetInfo(), info, lms7Device, and string().
std::string SoapyLMS7::getHardwareKey (void) const virtual
A key that uniquely identifies the hardware. This key should be meaningful to the user to optimize for the underlying hardware.
Reimplemented from SoapySDR.Device.
Definition at line 100 of file Settings.cpp.
References lms_dev_info_t::deviceName, lime::LMS7_Device::GetInfo(), lms7Device, and string().
Referenced by SoapySDR.Device::__str__().
long long SoapyLMS7::getHardwareTime (const std::string & what = "") const virtual
Read the time from the hardware clock on the device. The what argument can refer to a specific time counter.
Parameters
what optional argument
Returns
the time in nanoseconds
Reimplemented from SoapySDR.Device.
Definition at line 495 of file Settings.cpp.
References lime::LMS7_Device::GetHardwareTimestamp(), lms7Device, sampleRate, and SoapySDR::ticksToTimeNs.
double SoapyLMS7::getMasterClockRate (void) const virtual
Get the master clock rate of the device.
Returns
the clock rate in Hz
Reimplemented from SoapySDR.Device.
Definition at line 471 of file Settings.cpp.
References _accessMutex, lime::LMS7_Device::GetClockFreq(), lms7Device, and LMS_CLOCK_CGEN.
SoapySDR::RangeList SoapyLMS7::getMasterClockRates (void) const virtual
Get the range of available master clock rates.
Returns
a list of clock rate ranges in Hz
Reimplemented from SoapySDR.Device.
Definition at line 477 of file Settings.cpp.
References MAX_CGEN_RATE, MIN_CGEN_RATE, and calc_fmcw_peaks::r.
std::string SoapyLMS7::getNativeStreamFormat (const int direction, const size_t channel, double & fullScale) const virtual
Get the hardware's native stream format for this channel. This is the format used by the underlying transport layer, and the direct buffer access API calls (when available).
Parameters
direction the channel direction RX or TX
channel an available channel on the device
[out] fullScale the maximum possible value
Returns
the native stream buffer format string
Reimplemented from SoapySDR.Device.
Definition at line 50 of file Streaming.cpp.
References SOAPY_SDR_CS16.
size_t SoapyLMS7::getNumChannels (const int direction) const virtual
Get a number of channels given the streaming direction
Reimplemented from SoapySDR.Device.
Definition at line 127 of file Settings.cpp.
References lime::LMS7_Device::GetNumChannels(), and lms7Device.
double SoapyLMS7::getSampleRate (const int direction, const size_t channel) const virtual
Get the baseband sample rate of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the sample rate in samples per second
Reimplemented from SoapySDR.Device.
Definition at line 381 of file Settings.cpp.
References _accessMutex, lime::LMS7_Device::GetRate(), lms7Device, and SOAPY_SDR_TX.
SoapySDR::RangeList SoapyLMS7::getSampleRateRange (const int direction, const size_t channel) const virtual
Get the range of possible baseband sample rates.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of sample rate ranges in samples per second
Reimplemented from SoapySDR.Device.
Definition at line 393 of file Settings.cpp.
References MAX_SAMP_RATE, and MIN_SAMP_RATE.
SoapySDR::ArgInfo SoapyLMS7::getSensorInfo (const std::string & key) const virtual
Get meta-information about a sensor. Example: displayable name, type, range.
Parameters
key the ID name of an available sensor
Returns
meta-information about a sensor
Reimplemented from SoapySDR.Device.
Definition at line 543 of file Settings.cpp.
References SoapySDR.ArgInfo::BOOL, SoapySDR.ArgInfo::description, SoapySDR.ArgInfo::FLOAT, info, SoapySDR.ArgInfo::INT, SoapySDR.ArgInfo::key, SoapySDR.ArgInfo::name, SoapySDR.ArgInfo::type, SoapySDR.ArgInfo::units, and SoapySDR.ArgInfo::value.
SoapySDR::ArgInfo SoapyLMS7::getSensorInfo (const int direction, const size_t channel, const std::string & key) const virtual
Get meta-information about a channel sensor. Example: displayable name, type, range.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the ID name of an available sensor
Returns
meta-information about a sensor
Reimplemented from SoapySDR.Device.
Definition at line 631 of file Settings.cpp.
References SoapySDR.ArgInfo::BOOL, SoapySDR.ArgInfo::description, info, SoapySDR.ArgInfo::key, SoapySDR.ArgInfo::name, SoapySDR.ArgInfo::type, and SoapySDR.ArgInfo::value.
SoapySDR::ArgInfoList SoapyLMS7::getSettingInfo (void) const virtual
Describe the allowed keys and values used for settings.
Returns
a list of argument info structures
Reimplemented from SoapySDR.Device.
Definition at line 713 of file Settings.cpp.
SoapySDR::ArgInfoList SoapyLMS7::getSettingInfo (const int direction, const size_t channel) const virtual
Describe the allowed keys and values used for channel settings.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of argument info structures
Reimplemented from SoapySDR.Device.
Definition at line 821 of file Settings.cpp.
References SoapySDR.ArgInfo::description, info, SoapySDR.ArgInfo::INT, SoapySDR.ArgInfo::key, SoapySDR.ArgInfo::name, SoapySDR.ArgInfo::range, and SoapySDR.ArgInfo::type.
SoapySDR::ArgInfoList SoapyLMS7::getStreamArgsInfo (const int direction, const size_t channel) const virtual
Query the argument info description for stream args.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of argument info structures
Reimplemented from SoapySDR.Device.
Definition at line 56 of file Streaming.cpp.
References SoapySDR.ArgInfo::BOOL, SoapySDR.ArgInfo::description, lime::info(), SoapySDR.ArgInfo::INT, SoapySDR.ArgInfo::key, SoapySDR.ArgInfo::name, SoapySDR.ArgInfo::optionNames, SoapySDR.ArgInfo::options, SOAPY_SDR_CS12, SOAPY_SDR_CS16, SoapySDR.ArgInfo::STRING, SoapySDR.ArgInfo::type, SoapySDR.ArgInfo::units, and SoapySDR.ArgInfo::value.
std::vector< std::string > SoapyLMS7::getStreamFormats (const int direction, const size_t channel) const virtual
Query a list of the available stream formats.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of allowed format strings. See setupStream() for the format syntax.
Reimplemented from SoapySDR.Device.
Definition at line 41 of file Streaming.cpp.
References SOAPY_SDR_CF32, SOAPY_SDR_CS12, and SOAPY_SDR_CS16.
size_t SoapyLMS7::getStreamMTU (SoapySDR::Stream * stream) const
Definition at line 186 of file Streaming.cpp.
bool SoapyLMS7::hasDCOffset (const int direction, const size_t channel) const virtual
Does the device support frontend DC offset correction?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true if DC offset corrections are supported
Reimplemented from SoapySDR.Device.
Definition at line 201 of file Settings.cpp.
bool SoapyLMS7::hasDCOffsetMode (const int direction, const size_t channel) const virtual
Does the device support automatic DC offset corrections?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true if automatic corrections are supported
Reimplemented from SoapySDR.Device.
Definition at line 181 of file Settings.cpp.
References SOAPY_SDR_RX.
bool SoapyLMS7::hasHardwareTime (const std::string & what = "") const virtual
Does this device have a hardware clock?
Parameters
what optional argument
Returns
true if the hardware clock exists
Reimplemented from SoapySDR.Device.
Definition at line 488 of file Settings.cpp.
bool SoapyLMS7::hasIQBalance (const int direction, const size_t channel) const virtual
Does the device support frontend IQ balance correction?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true if IQ balance corrections are supported
Reimplemented from SoapySDR.Device.
Definition at line 206 of file Settings.cpp.
std::vector< std::string > SoapyLMS7::listAntennas (const int direction, const size_t channel) const virtual
Get a list of available antennas to select on a given chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of available antenna names
Reimplemented from SoapySDR.Device.
Definition at line 141 of file Settings.cpp.
References lime::LMS7_Device::GetPathNames(), lms7Device, and SOAPY_SDR_TX.
std::vector< std::string > SoapyLMS7::listFrequencies (const int direction, const size_t channel) const virtual
List available tunable elements in the chain. Elements should be in order RF to baseband.
Parameters
direction the channel direction RX or TX
channel an available channel
Returns
a list of tunable elements by name
Reimplemented from SoapySDR.Device.
Definition at line 336 of file Settings.cpp.
std::vector< std::string > SoapyLMS7::listGains (const int direction, const size_t channel) const virtual
List available amplification elements. Elements should be in order RF to baseband.
Parameters
direction the channel direction RX or TX
channel an available channel
Returns
a list of gain string names
Reimplemented from SoapySDR.Device.
Definition at line 215 of file Settings.cpp.
References SOAPY_SDR_RX, and SOAPY_SDR_TX.
std::vector< std::string > SoapyLMS7::listGPIOBanks (void) const virtual
Get a list of available GPIO banks by name.
Reimplemented from SoapySDR.Device.
Definition at line 927 of file Settings.cpp.
std::vector< std::string > SoapyLMS7::listRegisterInterfaces (void) const virtual
Get a list of available register interfaces by name.
Returns
a list of available register interfaces
Reimplemented from SoapySDR.Device.
Definition at line 662 of file Settings.cpp.
References lime::LMS7_Device::GetNumChannels(), i, and lms7Device.
std::vector< double > SoapyLMS7::listSampleRates (const int direction, const size_t channel) const virtual
Get the range of possible baseband sample rates.
Deprecated:
replaced by getSampleRateRange()
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of possible rates in samples per second
Reimplemented from SoapySDR.Device.
Definition at line 388 of file Settings.cpp.
References MAX_SAMP_RATE, and MIN_SAMP_RATE.
std::vector< std::string > SoapyLMS7::listSensors (void) const virtual
List the available global readback sensors. A sensor can represent a reference lock, RSSI, temperature.
Returns
a list of available sensor string names
Reimplemented from SoapySDR.Device.
Definition at line 533 of file Settings.cpp.
std::vector< std::string > SoapyLMS7::listSensors (const int direction, const size_t channel) const virtual
List the available channel readback sensors. A sensor can represent a reference lock, RSSI, temperature.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of available sensor string names
Reimplemented from SoapySDR.Device.
Definition at line 624 of file Settings.cpp.
unsigned SoapyLMS7::readGPIO (const std::string & bank) const virtual
Readback the value of a GPIO bank.
Parameters
bank the name of an available bank
Returns
an integer representing GPIO bits
Reimplemented from SoapySDR.Device.
Definition at line 940 of file Settings.cpp.
References buffer, lime::LMS7_Device::GetConnection(), lime::GetLastErrorMessage(), lime::IConnection::GPIORead(), lms7Device, calc_fmcw_peaks::r, and string().
unsigned SoapyLMS7::readGPIODir (const std::string & bank) const virtual
Read the data direction of a GPIO bank. 1 bits represent outputs, 0 bits represent inputs.
Parameters
bank the name of an available bank
Returns
an integer representing data direction bits
Reimplemented from SoapySDR.Device.
Definition at line 954 of file Settings.cpp.
References buffer, lime::LMS7_Device::GetConnection(), lime::GetLastErrorMessage(), lime::IConnection::GPIODirRead(), lms7Device, calc_fmcw_peaks::r, and string().
unsigned SoapyLMS7::readRegister (const std::string & name, const unsigned addr) const virtual
Read a register on the device given the interface name.
Parameters
name the name of a available register interface
addr the register address
Returns
the register value
Reimplemented from SoapySDR.Device.
Definition at line 685 of file Settings.cpp.
References lms7Device, and lime::LMS7_Device::ReadLMSReg().
unsigned SoapyLMS7::readRegister (const unsigned addr) const virtual
Read a register on the device.
Deprecated:
replaced by readRegister(name)
Parameters
addr the register address
Returns
the register value
Reimplemented from SoapySDR.Device.
Definition at line 701 of file Settings.cpp.
References lime::LMS7_Device::GetConnection(), lms7Device, and lime::IConnection::ReadRegister().
std::string SoapyLMS7::readSensor (const std::string & key) const virtual
Readback a global sensor given the name. The value returned is a string which can represent a boolean ("true"/"false"), an integer, or float.
Parameters
key the ID name of an available sensor
Returns
the current value of the sensor
Reimplemented from SoapySDR.Device.
Definition at line 584 of file Settings.cpp.
References _accessMutex, lime::LMS7002M::GetCGENLocked(), lime::LMS7_Device::GetChipTemperature(), lime::LMS7_Device::GetChirpTimePeriod(), lime::LMS7_Device::GetChirpTimeStamp(), lime::LMS7_Device::GetLMS(), lms7Device, sampleRate, and SoapySDR::ticksToTimeNs.
std::string SoapyLMS7::readSensor (const int direction, const size_t channel, const std::string & key) const virtual
Readback a channel sensor given the name. The value returned is a string which can represent a boolean ("true"/"false"), an integer, or float.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the ID name of an available sensor
Returns
the current value of the sensor
Reimplemented from SoapySDR.Device.
Definition at line 645 of file Settings.cpp.
References _accessMutex, lime::LMS7_Device::GetLMS(), lime::LMS7002M::GetSXLocked(), lms7Device, and SOAPY_SDR_TX.
std::string SoapyLMS7::readSetting (const std::string & key) const virtual
Read an arbitrary setting on the device.
Parameters
key the setting identifier
Returns
the setting value
Reimplemented from SoapySDR.Device.
Definition at line 910 of file Settings.cpp.
References SOAPY_SDR_TX.
std::string SoapyLMS7::readSetting (const int direction, const size_t channel, const std::string & key) const virtual
Read an arbitrary channel setting on the device.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the setting identifier
Returns
the setting value
Reimplemented from SoapySDR.Device.
Definition at line 915 of file Settings.cpp.
References lms7Device, lime::LMS7_Device::ReadParam(), and val.
int SoapyLMS7::readStream (SoapySDR::Stream * stream, void *const * buffs, const size_t numElems, int & flags, long long & timeNs, const long timeoutUs = 100000)
Definition at line 329 of file Streaming.cpp.
References lime::RingFIFO::END_BURST, lime::StreamChannel::Metadata::flags, SoapySDR::logf(), SOAPY_SDR_END_BURST, SOAPY_SDR_ERROR, SOAPY_SDR_HAS_TIME, SOAPY_SDR_ONE_PACKET, SOAPY_SDR_STREAM_ERROR, SOAPY_SDR_TIME_ERROR, SOAPY_SDR_TIMEOUT, status, lime::RingFIFO::SYNC_TIMESTAMP, SoapySDR::ticksToTimeNs, SoapySDR::timeNsToTicks, and lime::StreamChannel::Metadata::timestamp.
int SoapyLMS7::readStreamStatus (SoapySDR::Stream * stream, size_t & chanMask, int & flags, long long & timeNs, const long timeoutUs = 100000)
Definition at line 450 of file Streaming.cpp.
References lime::StreamChannel::Info::droppedPackets, i, lime::StreamChannel::Info::overrun, SOAPY_SDR_HAS_TIME, SOAPY_SDR_OVERFLOW, SOAPY_SDR_TIME_ERROR, SOAPY_SDR_TIMEOUT, SOAPY_SDR_UNDERFLOW, SoapySDR::ticksToTimeNs, lime::StreamChannel::Info::timestamp, and lime::StreamChannel::Info::underrun.
void SoapyLMS7::setAntenna (const int direction, const size_t channel, const std::string & name) virtual
Set the selected antenna on a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an available antenna
Reimplemented from SoapySDR.Device.
Definition at line 146 of file Settings.cpp.
References _accessMutex, _channelsToCal, dirName, lime::LMS7_Device::GetPathNames(), lms7Device, SoapySDR::logf(), lime::LMS7_Device::SetPath(), SOAPY_SDR_DEBUG, SOAPY_SDR_TX, and tx.
void SoapyLMS7::setBandwidth (const int direction, const size_t channel, const double bw) virtual
Set the baseband filter width of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
bw the baseband filter width in Hz
Reimplemented from SoapySDR.Device.
Definition at line 402 of file Settings.cpp.
References _accessMutex, _actualBw, _channelsToCal, bw, dirName, lime::GetLastErrorMessage(), lms7Device, SoapySDR::logf(), lime::LMS7_Device::SetLPF(), SOAPY_SDR_DEBUG, SOAPY_SDR_ERROR, SOAPY_SDR_RX, and SOAPY_SDR_TX.
void SoapyLMS7::setDCOffsetMode (const int direction, const size_t channel, const bool automatic) virtual
Set the automatic DC offset corrections mode.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
automatic true for automatic offset correction
Reimplemented from SoapySDR.Device.
Definition at line 186 of file Settings.cpp.
References _accessMutex, DC_BYP_RXTSP, lms7Device, LMS7param, SOAPY_SDR_RX, and lime::LMS7_Device::WriteParam().
void SoapyLMS7::setFrequency (const int direction, const size_t channel, const double frequency, const SoapySDR::Kwargs & args = SoapySDR::Kwargs())
Referenced by getFrequencyArgsInfo().
void SoapyLMS7::setFrequency (const int direction, const size_t channel, const std::string & name, const double frequency, const SoapySDR::Kwargs & args = SoapySDR::Kwargs())
void SoapyLMS7::setGain (const int direction, const size_t channel, const double value) override virtual
Set the overall amplification in a chain. The gain will be distributed automatically across available element.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
value the new amplification value in dB
Reimplemented from SoapySDR.Device.
Definition at line 232 of file Settings.cpp.
References _accessMutex, dirName, getGain(), lms7Device, SoapySDR::logf(), lime::LMS7_Device::SetGain(), SOAPY_SDR_DEBUG, and SOAPY_SDR_TX.
Referenced by SoapyLMS7().
void SoapyLMS7::setGain (const int direction, const size_t channel, const std::string & name, const double value) virtual
Set the value of a amplification element in a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an amplification element
value the new amplification value in dB
Reimplemented from SoapySDR.Device.
Definition at line 245 of file Settings.cpp.
References _accessMutex, dirName, getGain(), int(), lms7Device, SoapySDR::logf(), lime::LMS7_Device::SetGain(), SOAPY_SDR_DEBUG, and SOAPY_SDR_TX.
void SoapyLMS7::setHardwareTime (const long long timeNs, const std::string & what = "") virtual
Write the time to the hardware clock on the device. The what argument can refer to a specific time counter.
Parameters
timeNs time in nanoseconds
what optional argument
Reimplemented from SoapySDR.Device.
Definition at line 512 of file Settings.cpp.
References lms7Device, sampleRate, lime::LMS7_Device::SetHardwareTimestamp(), and SoapySDR::timeNsToTicks.
void SoapyLMS7::setMasterClockRate (const double rate) virtual
Set the master clock rate of the device.
Parameters
rate the clock rate in Hz
Reimplemented from SoapySDR.Device.
Definition at line 466 of file Settings.cpp.
References lms7Device, LMS_CLOCK_CGEN, and lime::LMS7_Device::SetClockFreq().
Referenced by SoapyLMS7().
void SoapyLMS7::setSampleRate (const int direction, const size_t channel, const double rate) virtual
Set the baseband sample rate of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
rate the sample rate in samples per second
Reimplemented from SoapySDR.Device.
Definition at line 373 of file Settings.cpp.
References _accessMutex, lms7Device, rate, sampleRate, lime::LMS7_Device::SetRate(), and SOAPY_SDR_TX.
SoapySDR::Stream * SoapyLMS7::setupStream (const int direction, const std::string & format, const std::vector< size_t > & channels = std::vector<size_t>(), const SoapySDR::Kwargs & args = SoapySDR::Kwargs())
Definition at line 104 of file Streaming.cpp.
References lime::StreamConfig::bufferLength, lime::StreamConfig::channelID, lime::StreamConfig::FMT_FLOAT32, lime::StreamConfig::FMT_INT12, lime::StreamConfig::FMT_INT16, lime::StreamConfig::format, SoapySDR::formatToSize, lime::GetLastErrorMessage(), lime::StreamChannel::GetStreamSize(), i, lime::StreamConfig::isTx, lime::StreamConfig::performanceLatency, SOAPY_SDR_CF32, SOAPY_SDR_CS12, SOAPY_SDR_CS16, SOAPY_SDR_TX, stream, and string().
void SoapyLMS7::writeGPIO (const std::string & bank, const unsigned value) virtual
Write the value of a GPIO bank.
Parameters
bank the name of an available bank
value an integer representing GPIO bits
Reimplemented from SoapySDR.Device.
Definition at line 934 of file Settings.cpp.
References lime::LMS7_Device::GetConnection(), lime::GetLastErrorMessage(), lime::IConnection::GPIOWrite(), lms7Device, calc_fmcw_peaks::r, and string().
void SoapyLMS7::writeGPIODir (const std::string & bank, const unsigned dir) virtual
Write the data direction of a GPIO bank. 1 bits represent outputs, 0 bits represent inputs.
Parameters
bank the name of an available bank
dir an integer representing data direction bits
Reimplemented from SoapySDR.Device.
Definition at line 948 of file Settings.cpp.
References lime::LMS7_Device::GetConnection(), lime::GetLastErrorMessage(), lime::IConnection::GPIODirWrite(), lms7Device, calc_fmcw_peaks::r, and string().
void SoapyLMS7::writeRegister (const std::string & name, const unsigned addr, const unsigned value) virtual
Write a register on the device given the interface name. This can represent a register on a soft CPU, FPGA, IC; the interpretation is up the implementation to decide.
Parameters
name the name of a available register interface
addr the register address
value the register value
Reimplemented from SoapySDR.Device.
Definition at line 673 of file Settings.cpp.
References lms7Device, and lime::LMS7_Device::WriteLMSReg().
void SoapyLMS7::writeRegister (const unsigned addr, const unsigned value) virtual
Write a register on the device. This can represent a register on a soft CPU, FPGA, IC; the interpretation is up the implementation to decide.
Deprecated:
replaced by writeRegister(name)
Parameters
addr the register address
value the register value
Reimplemented from SoapySDR.Device.
Definition at line 694 of file Settings.cpp.
References lime::LMS7_Device::GetConnection(), lms7Device, and lime::IConnection::WriteRegister().
void SoapyLMS7::writeSetting (const std::string & key, const std::string & value) virtual
Write an arbitrary setting on the device. The interpretation is up the implementation.
Parameters
key the setting identifier
value the setting value
Reimplemented from SoapySDR.Device.
Definition at line 720 of file Settings.cpp.
References lime::LMS7_Device::GetNumChannels(), lms7Device, lime::LMS7_Device::LoadConfig(), lime::LMS7_Device::SaveConfig(), SOAPY_SDR_RX, and SOAPY_SDR_TX.
void SoapyLMS7::writeSetting (const int direction, const size_t channel, const std::string & key, const std::string & value) virtual
Write an arbitrary channel setting on the device. The interpretation is up the implementation.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the setting identifier
value the setting value
Reimplemented from SoapySDR.Device.
Definition at line 838 of file Settings.cpp.
References _accessMutex, _channelsToCal, bw, lime::LMS7_Device::Calibrate(), lime::LMS7_Device::ConfigureGFIR(), lime::GetLastErrorMessage(), lms7Device, LMS_TESTSIG_DC, LMS_TESTSIG_NCODIV4F, LMS_TESTSIG_NCODIV8F, LMS_TESTSIG_NONE, SoapySDR::logf(), lime::LMS7_Device::SetTestSignal(), SOAPY_SDR_INFO, SOAPY_SDR_TX, val, and lime::LMS7_Device::WriteParam().
int SoapyLMS7::writeStream (SoapySDR::Stream * stream, const void *const * buffs, const size_t numElems, int & flags, const long long timeNs = 0, const long timeoutUs = 100000)
Definition at line 411 of file Streaming.cpp.
References lime::RingFIFO::END_BURST, lime::StreamChannel::Metadata::flags, i, SoapySDR::logf(), SOAPY_SDR_CORRUPTION, SOAPY_SDR_END_BURST, SOAPY_SDR_ERROR, SOAPY_SDR_HAS_TIME, SOAPY_SDR_STREAM_ERROR, SOAPY_SDR_TIMEOUT, status, lime::RingFIFO::SYNC_TIMESTAMP, SoapySDR::timeNsToTicks, and lime::StreamChannel::Metadata::timestamp.
Member Data Documentation
std::recursive_mutex SoapyLMS7::_accessMutex mutable private
Definition at line 284 of file SoapyLMS7.h.
Referenced by getAntenna(), getBandwidth(), getDCOffsetMode(), getFrequency(), getFrequencyArgsInfo(), getFrequencyRange(), getGain(), getMasterClockRate(), getSampleRate(), readSensor(), setAntenna(), setBandwidth(), setDCOffsetMode(), setGain(), setSampleRate(), and writeSetting().
std::map<int, std::map<size_t, double> > SoapyLMS7::_actualBw
Definition at line 190 of file SoapyLMS7.h.
Referenced by getBandwidth(), setBandwidth(), and SoapyLMS7().
std::set<std::pair<int, size_t> > SoapyLMS7::_channelsToCal private
Definition at line 283 of file SoapyLMS7.h.
Referenced by getFrequencyArgsInfo(), setAntenna(), setBandwidth(), SoapyLMS7(), and writeSetting().
std::map<size_t, int> SoapyLMS7::_decims
Definition at line 176 of file SoapyLMS7.h.
const SoapySDR::Kwargs SoapyLMS7::_deviceArgs private
stash of constructor arguments
Definition at line 279 of file SoapyLMS7.h.
std::map<size_t, int> SoapyLMS7::_interps
Definition at line 175 of file SoapyLMS7.h.
const std::string SoapyLMS7::_moduleName private
Definition at line 280 of file SoapyLMS7.h.
Referenced by getDriverKey().
lime::LMS7_Device* SoapyLMS7::lms7Device private
Definition at line 281 of file SoapyLMS7.h.
Referenced by getAntenna(), getDCOffsetMode(), getFrequency(), getFrequencyArgsInfo(), getFrequencyRange(), getGain(), getGainRange(), getHardwareInfo(), getHardwareKey(), getHardwareTime(), getMasterClockRate(), getNumChannels(), getSampleRate(), listAntennas(), listRegisterInterfaces(), readGPIO(), readGPIODir(), readRegister(), readSensor(), readSetting(), setAntenna(), setBandwidth(), setDCOffsetMode(), setGain(), setHardwareTime(), setMasterClockRate(), setSampleRate(), SoapyLMS7(), writeGPIO(), writeGPIODir(), writeRegister(), writeSetting(), and ~SoapyLMS7().
double SoapyLMS7::sampleRate private
Definition at line 282 of file SoapyLMS7.h.
Referenced by getHardwareTime(), readSensor(), setHardwareTime(), and setSampleRate().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/SoapyLMS7/SoapyLMS7.h
/home/erik/prefix/default/src/limesuite-dev/SoapyLMS7/Settings.cpp
/home/erik/prefix/default/src/limesuite-dev/SoapyLMS7/Streaming.cpp