LimeSuite-UML: AppFrame_view Class Reference
AppFrame_view Class Reference
Class AppFrame_view.
#include <lms7suiteApp_gui.h>
Public Member Functions
AppFrame_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("Lime Suite GUI"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL)
~AppFrame_view ()
Protected Types
enum { idMenuQuit = 1000, idMenuAbout }
Protected Member Functions
virtual void OnClose (wxCloseEvent &event)
virtual void OnQuit (wxCommandEvent &event)
virtual void OnShowConnectionSettings (wxCommandEvent &event)
virtual void OnChangeCacheSettings (wxCommandEvent &event)
virtual void OnShowFFTviewer (wxCommandEvent &event)
virtual void OnShowADF4002 (wxCommandEvent &event)
virtual void OnShowSi5351C (wxCommandEvent &event)
virtual void OnShowPrograming (wxCommandEvent &event)
virtual void OnShowFPGAcontrols (wxCommandEvent &event)
virtual void OnShowDeviceInfo (wxCommandEvent &event)
virtual void OnShowSPI (wxCommandEvent &event)
virtual void OnShowBoardControls (wxCommandEvent &event)
virtual void OnAbout (wxCommandEvent &event)
Protected Attributes
wxMenuBar * mbar
wxMenu * fileMenu
wxMenu * mnuOptions
wxMenuItem * mnuCacheValues
wxMenu * mnuModules
wxMenu * helpMenu
wxStatusBar * statusBar
wxBoxSizer * bSizer6
wxScrolledWindow * m_scrolledWindow1
wxFlexGridSizer * contentSizer
lms7002_mainPanel * mContent
Detailed Description
Class AppFrame_view.
Definition at line 40 of file lms7suiteApp_gui.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
idMenuQuit
idMenuAbout
Definition at line 45 of file lms7suiteApp_gui.h.
Constructor & Destructor Documentation
AppFrame_view::AppFrame_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxT("Lime Suite GUI"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(-1,-1), long style = wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL)
Definition at line 24 of file lms7suiteApp_gui.cpp.
References bSizer6, contentSizer, fileMenu, helpMenu, idMenuAbout, idMenuQuit, m_scrolledWindow1, mbar, mContent, mnuCacheValues, mnuModules, mnuOptions, OnAbout(), OnChangeCacheSettings(), OnClose(), OnQuit(), OnShowADF4002(), OnShowBoardControls(), OnShowConnectionSettings(), OnShowDeviceInfo(), OnShowFFTviewer(), OnShowFPGAcontrols(), OnShowPrograming(), OnShowSi5351C(), OnShowSPI(), and statusBar.
Referenced by OnAbout().
AppFrame_view::~AppFrame_view ()
Definition at line 141 of file lms7suiteApp_gui.cpp.
References idMenuAbout, idMenuQuit, OnAbout(), OnChangeCacheSettings(), OnClose(), OnQuit(), OnShowADF4002(), OnShowBoardControls(), OnShowConnectionSettings(), OnShowDeviceInfo(), OnShowFFTviewer(), OnShowFPGAcontrols(), OnShowPrograming(), OnShowSi5351C(), and OnShowSPI().
Referenced by OnAbout().
Member Function Documentation
virtual void AppFrame_view::OnAbout (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 76 of file lms7suiteApp_gui.h.
References AppFrame_view(), and ~AppFrame_view().
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnChangeCacheSettings (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 67 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnClose (wxCloseEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 64 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnQuit (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 65 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowADF4002 (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 69 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowBoardControls (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 75 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowConnectionSettings (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 66 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowDeviceInfo (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 73 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowFFTviewer (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 68 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowFPGAcontrols (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 72 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowPrograming (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 71 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowSi5351C (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 70 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
virtual void AppFrame_view::OnShowSPI (wxCommandEvent & event) inline protected virtual
Reimplemented in LMS7SuiteAppFrame.
Definition at line 74 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and ~AppFrame_view().
Member Data Documentation
wxBoxSizer* AppFrame_view::bSizer6 protected
Definition at line 58 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and LMS7SuiteAppFrame::LMS7SuiteAppFrame().
wxFlexGridSizer* AppFrame_view::contentSizer protected
Definition at line 60 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view().
wxMenu* AppFrame_view::fileMenu protected
Definition at line 52 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view().
wxMenu* AppFrame_view::helpMenu protected
Definition at line 56 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view().
wxScrolledWindow* AppFrame_view::m_scrolledWindow1 protected
Definition at line 59 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and LMS7SuiteAppFrame::LMS7SuiteAppFrame().
wxMenuBar* AppFrame_view::mbar protected
Definition at line 51 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view().
lms7002_mainPanel* AppFrame_view::mContent protected
Definition at line 61 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), and LMS7SuiteAppFrame::UpdateConnections().
wxMenuItem* AppFrame_view::mnuCacheValues protected
Definition at line 54 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), LMS7SuiteAppFrame::LMS7SuiteAppFrame(), and LMS7SuiteAppFrame::OnControlBoardConnect().
wxMenu* AppFrame_view::mnuModules protected
Definition at line 55 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view().
wxMenu* AppFrame_view::mnuOptions protected
Definition at line 53 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view().
wxStatusBar* AppFrame_view::statusBar protected
Definition at line 57 of file lms7suiteApp_gui.h.
Referenced by AppFrame_view(), LMS7SuiteAppFrame::LMS7SuiteAppFrame(), and LMS7SuiteAppFrame::OnControlBoardConnect().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7suiteApp_gui.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7suiteApp_gui.cpp