LimeSuite-UML: lms7002_pnlTxTSP_view Class Reference
lms7002_pnlTxTSP_view Class Reference
Implementing pnlTxTSP_view.
#include <lms7002_pnlTxTSP_view.h>
Public Member Functions
lms7002_pnlTxTSP_view (wxWindow *parent)
Constructor.
lms7002_pnlTxTSP_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
void UpdateNCOinputs ()
Public Member Functions inherited from pnlTxTSP_view
pnlTxTSP_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlTxTSP_view ()
Protected Member Functions
void ParameterChangeHandler (wxSpinEvent &event)
void ParameterChangeHandler (wxCommandEvent &event)
void OnNCOSelectionChange (wxCommandEvent &event)
void onbtnReadBISTSignature (wxCommandEvent &event)
void OnbtnLoadDCIClick (wxCommandEvent &event)
void OnbtnLoadDCQClick (wxCommandEvent &event)
void onbtnGFIR1Coef (wxCommandEvent &event)
void onbtnGFIR2Coef (wxCommandEvent &event)
void onbtnGFIR3Coef (wxCommandEvent &event)
void OnbtnUploadNCOClick (wxCommandEvent &event)
void PHOinputChanged (wxCommandEvent &event)
void txtFCWPHOmodeAdditional_OnMouseWheel (wxMouseEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
std::vector< wxStaticText * > lblNCOangles
std::vector< wxRadioButton * > rgrNCOselections
std::vector< wxTextCtrl * > txtNCOinputs
Protected Attributes inherited from pnlTxTSP_view
wxCheckBox * chkEN_TXTSP
wxCheckBox * chkDC_BYP_TXTSP
wxCheckBox * chkGC_BYP_TXTSP
wxCheckBox * chkPH_BYP_TXTSP
wxCheckBox * chkCMIX_BYP_TXTSP
wxCheckBox * chkISINC_BYP_TXTSP
wxCheckBox * chkGFIR1_BYP_TXTSP
wxCheckBox * chkGFIR2_BYP_TXTSP
wxCheckBox * chkGFIR3_BYP_TXTSP
wxCheckBox * chkBSTART_TXTSP
wxStaticText * ID_STATICTEXT2
wxStaticText * lblBSTATE_TXTSP
wxStaticText * ID_STATICTEXT1
wxStaticText * lblBSIGI_TXTSP
wxStaticText * ID_STATICTEXT3
wxStaticText * lblBSIGQ_TXTSP
wxButton * btnReadBIST
wxFlexGridSizer * sizerNCOgrid
wxStaticText * tableTitleCol1
wxStaticText * tableTitleCol2
wxRadioButton * rgrSEL0
wxTextCtrl * txtFCWPHO0
wxStaticText * txtAnglePHO0
wxRadioButton * rgrSEL01
wxTextCtrl * txtFCWPHO01
wxStaticText * txtAnglePHO01
wxRadioButton * rgrSEL02
wxTextCtrl * txtFCWPHO02
wxStaticText * txtAnglePHO02
wxRadioButton * rgrSEL03
wxTextCtrl * txtFCWPHO03
wxStaticText * txtAnglePHO03
wxRadioButton * rgrSEL04
wxTextCtrl * txtFCWPHO04
wxStaticText * txtAnglePHO04
wxRadioButton * rgrSEL05
wxTextCtrl * txtFCWPHO05
wxStaticText * txtAnglePHO05
wxRadioButton * rgrSEL06
wxTextCtrl * txtFCWPHO06
wxStaticText * txtAnglePHO06
wxRadioButton * rgrSEL07
wxTextCtrl * txtFCWPHO07
wxStaticText * txtAnglePHO07
wxRadioButton * rgrSEL08
wxTextCtrl * txtFCWPHO08
wxStaticText * txtAnglePHO08
wxRadioButton * rgrSEL09
wxTextCtrl * txtFCWPHO09
wxStaticText * txtAnglePHO09
wxRadioButton * rgrSEL10
wxTextCtrl * txtFCWPHO10
wxStaticText * txtAnglePHO10
wxRadioButton * rgrSEL11
wxTextCtrl * txtFCWPHO11
wxStaticText * txtAnglePHO11
wxRadioButton * rgrSEL12
wxTextCtrl * txtFCWPHO12
wxStaticText * txtAnglePHO12
wxRadioButton * rgrSEL13
wxTextCtrl * txtFCWPHO13
wxStaticText * txtAnglePHO13
wxRadioButton * rgrSEL14
wxTextCtrl * txtFCWPHO14
wxStaticText * txtAnglePHO14
wxRadioButton * rgrSEL15
wxTextCtrl * txtFCWPHO15
wxStaticText * txtAnglePHO15
wxStaticText * ID_STATICTEXT21
wxStaticText * lblRefClk
wxButton * btnUploadNCO
wxRadioBox * rgrMODE_TX
wxStaticText * lblFCWPHOmodeName
wxTextCtrl * txtFCWPHOmodeAdditional
wxStaticText * ID_STATICTEXT25
wxComboBox * cmbDTHBIT_TX
wxCheckBox * chkTSGSWAPIQ_TXTSP
wxRadioBox * rgrTSGFCW_TXTSP
wxRadioBox * rgrTSGMODE_TXTSP
wxRadioBox * rgrINSEL_TXTSP
wxRadioBox * rgrTSGFC_TXTSP
wxStaticText * ID_STATICTEXT23
wxTextCtrl * txtDC_REG_TXTSP
wxButton * btnLoadDCI
wxButton * btnLoadDCQ
wxComboBox * cmbCMIX_SC_TXTSP
wxStaticText * ID_STATICTEXT24
wxComboBox * cmbCMIX_GAIN_TXTSP
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbHBI_OVR_TXTSP
wxStaticText * ID_STATICTEXT10
wxComboBox * cmbGFIR1_L_TXTSP
wxStaticText * ID_STATICTEXT11
wxSpinCtrl * cmbGFIR1_N_TXTSP
wxButton * btnGFIR1Coef
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbGFIR2_L_TXTSP
wxStaticText * ID_STATICTEXT13
wxSpinCtrl * cmbGFIR2_N_TXTSP
wxButton * btnGFIR2Coef
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbGFIR3_L_TXTSP
wxStaticText * ID_STATICTEXT15
wxSpinCtrl * cmbGFIR3_N_TXTSP
wxButton * btnGFIR3Coef
NumericSlider * cmbIQCORR_TXTSP
wxStaticText * ID_STATICTEXT16
wxStaticText * txtPhaseAlpha
wxStaticText * ID_STATICTEXT5
NumericSlider * cmbGCORRI_TXTSP
wxStaticText * ID_STATICTEXT4
NumericSlider * cmbGCORRQ_TXTSP
wxButton * ID_BUTTON10
wxStaticText * ID_STATICTEXT8
NumericSlider * cmbDCCORRI_TXTSP
wxStaticText * ID_STATICTEXT9
NumericSlider * cmbDCCORRQ_TXTSP
Additional Inherited Members
Protected Types inherited from pnlTxTSP_view
enum {
ID_EN_TXTSP = 2048, ID_DC_BYP_TXTSP, ID_GC_BYP_TXTSP, ID_PH_BYP_TXTSP,
ID_CMIX_BYP_TXTSP, ID_ISINC_BYP_TXTSP, ID_GFIR1_BYP_TXTSP, ID_GFIR2_BYP_TXTSP,
ID_GFIR3_BYP_TXTSP, ID_BSTART_TXTSP, ID_BSTATE_TXTSP, ID_BSIGI_TXTSP,
ID_BSIGQ_TXTSP, ID_MODE_TX, ID_DTHBIT_TX, ID_TSGSWAPIQ_TXTSP,
ID_TSGFCW_TXTSP, ID_TSGMODE_TXTSP, ID_INSEL_TXTSP, ID_TSGFC_TXTSP,
ID_DC_REG_TXTSP, ID_CMIX_SC_TXTSP, ID_CMIX_GAIN_TXTSP, ID_HBI_OVR_TXTSP,
ID_GFIR1_L_TXTSP, ID_GFIR1_N_TXTSP, ID_GFIR2_L_TXTSP, ID_GFIR2_N_TXTSP,
ID_GFIR3_L_TXTSP, ID_GFIR3_N_TXTSP, ID_IQCORR_TXTSP, ID_GCORRI_TXTSP,
ID_GCORRQ_TXTSP, ID_DCCORRI_TXTSP, ID_DCCORRQ_TXTSP
}
Detailed Description
Implementing pnlTxTSP_view.
Definition at line 18 of file lms7002_pnlTxTSP_view.h.
Constructor & Destructor Documentation
lms7002_pnlTxTSP_view::lms7002_pnlTxTSP_view (wxWindow * parent)
Constructor.
Definition at line 14 of file lms7002_pnlTxTSP_view.cpp.
lms7002_pnlTxTSP_view::lms7002_pnlTxTSP_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 21 of file lms7002_pnlTxTSP_view.cpp.
References BSTART_TXTSP, pnlTxTSP_view::chkBSTART_TXTSP, pnlTxTSP_view::chkCMIX_BYP_TXTSP, pnlTxTSP_view::chkDC_BYP_TXTSP, pnlTxTSP_view::chkEN_TXTSP, pnlTxTSP_view::chkGC_BYP_TXTSP, pnlTxTSP_view::chkGFIR1_BYP_TXTSP, pnlTxTSP_view::chkGFIR2_BYP_TXTSP, pnlTxTSP_view::chkGFIR3_BYP_TXTSP, pnlTxTSP_view::chkISINC_BYP_TXTSP, pnlTxTSP_view::chkPH_BYP_TXTSP, pnlTxTSP_view::chkTSGSWAPIQ_TXTSP, pnlTxTSP_view::cmbCMIX_GAIN_TXTSP, pnlTxTSP_view::cmbCMIX_SC_TXTSP, pnlTxTSP_view::cmbDCCORRI_TXTSP, pnlTxTSP_view::cmbDCCORRQ_TXTSP, pnlTxTSP_view::cmbDTHBIT_TX, pnlTxTSP_view::cmbGCORRI_TXTSP, pnlTxTSP_view::cmbGCORRQ_TXTSP, pnlTxTSP_view::cmbGFIR1_L_TXTSP, pnlTxTSP_view::cmbGFIR1_N_TXTSP, pnlTxTSP_view::cmbGFIR2_L_TXTSP, pnlTxTSP_view::cmbGFIR2_N_TXTSP, pnlTxTSP_view::cmbGFIR3_L_TXTSP, pnlTxTSP_view::cmbGFIR3_N_TXTSP, pnlTxTSP_view::cmbHBI_OVR_TXTSP, pnlTxTSP_view::cmbIQCORR_TXTSP, CMIX_BYP_TXTSP, CMIX_GAIN_TXTSP, cmix_gain_txtsp_IndexValuePairs, CMIX_SC_TXTSP, DC_BYP_TXTSP, DCCORRI_TXTSP, DCCORRQ_TXTSP, DTHBIT_TX, EN_TXTSP, GC_BYP_TXTSP, GCORRI_TXTSP, GCORRQ_TXTSP, GFIR1_BYP_TXTSP, GFIR1_L_TXTSP, GFIR1_N_TXTSP, GFIR2_BYP_TXTSP, GFIR2_L_TXTSP, GFIR2_N_TXTSP, GFIR3_BYP_TXTSP, GFIR3_L_TXTSP, GFIR3_N_TXTSP, HBI_OVR_TXTSP, hbi_ovr_txtsp_IndexValuePairs, i, INSEL_TXTSP, IQCORR_TXTSP, ISINC_BYP_TXTSP, lblNCOangles, LMS7param, MODE_TX, PH_BYP_TXTSP, pnlTxTSP_view::rgrINSEL_TXTSP, pnlTxTSP_view::rgrMODE_TX, rgrNCOselections, pnlTxTSP_view::rgrSEL0, pnlTxTSP_view::rgrSEL01, pnlTxTSP_view::rgrSEL02, pnlTxTSP_view::rgrSEL03, pnlTxTSP_view::rgrSEL04, pnlTxTSP_view::rgrSEL05, pnlTxTSP_view::rgrSEL06, pnlTxTSP_view::rgrSEL07, pnlTxTSP_view::rgrSEL08, pnlTxTSP_view::rgrSEL09, pnlTxTSP_view::rgrSEL10, pnlTxTSP_view::rgrSEL11, pnlTxTSP_view::rgrSEL12, pnlTxTSP_view::rgrSEL13, pnlTxTSP_view::rgrSEL14, pnlTxTSP_view::rgrSEL15, pnlTxTSP_view::rgrTSGFC_TXTSP, pnlTxTSP_view::rgrTSGFCW_TXTSP, pnlTxTSP_view::rgrTSGMODE_TXTSP, SEL_TX, temp, TSGFC_TXTSP, TSGFCW_TXTSP, tsgfcw_txtsp_IndexValuePairs, TSGMODE_TXTSP, TSGSWAPIQ_TXTSP, pnlTxTSP_view::txtAnglePHO0, pnlTxTSP_view::txtAnglePHO01, pnlTxTSP_view::txtAnglePHO02, pnlTxTSP_view::txtAnglePHO03, pnlTxTSP_view::txtAnglePHO04, pnlTxTSP_view::txtAnglePHO05, pnlTxTSP_view::txtAnglePHO06, pnlTxTSP_view::txtAnglePHO07, pnlTxTSP_view::txtAnglePHO08, pnlTxTSP_view::txtAnglePHO09, pnlTxTSP_view::txtAnglePHO10, pnlTxTSP_view::txtAnglePHO11, pnlTxTSP_view::txtAnglePHO12, pnlTxTSP_view::txtAnglePHO13, pnlTxTSP_view::txtAnglePHO14, pnlTxTSP_view::txtAnglePHO15, pnlTxTSP_view::txtFCWPHO0, pnlTxTSP_view::txtFCWPHO01, pnlTxTSP_view::txtFCWPHO02, pnlTxTSP_view::txtFCWPHO03, pnlTxTSP_view::txtFCWPHO04, pnlTxTSP_view::txtFCWPHO05, pnlTxTSP_view::txtFCWPHO06, pnlTxTSP_view::txtFCWPHO07, pnlTxTSP_view::txtFCWPHO08, pnlTxTSP_view::txtFCWPHO09, pnlTxTSP_view::txtFCWPHO10, pnlTxTSP_view::txtFCWPHO11, pnlTxTSP_view::txtFCWPHO12, pnlTxTSP_view::txtFCWPHO13, pnlTxTSP_view::txtFCWPHO14, pnlTxTSP_view::txtFCWPHO15, txtNCOinputs, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlTxTSP_view::Initialize (lms_device_t * pControl)
Definition at line 166 of file lms7002_pnlTxTSP_view.cpp.
References pnlTxTSP_view::cmbCMIX_GAIN_TXTSP, LMS7param, LMS_ReadParam(), lmsControl, MASK, and temp.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlTxTSP_view::onbtnGFIR1Coef (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 275 of file lms7002_pnlTxTSP_view.cpp.
References lms7002_dlgGFIR_Coefficients::GetCoefficients(), LMS7param, LMS_CH_TX, LMS_GetGFIRCoeff(), LMS_GFIR1, LMS_ReadParam(), LMS_SetGFIRCoeff(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, lms7002_dlgGFIR_Coefficients::SetCoefficients(), status, and UpdateGUI().
void lms7002_pnlTxTSP_view::onbtnGFIR2Coef (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 305 of file lms7002_pnlTxTSP_view.cpp.
References lms7002_dlgGFIR_Coefficients::GetCoefficients(), LMS7param, LMS_CH_TX, LMS_GetGFIRCoeff(), LMS_GFIR2, LMS_ReadParam(), LMS_SetGFIRCoeff(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, lms7002_dlgGFIR_Coefficients::SetCoefficients(), status, and UpdateGUI().
void lms7002_pnlTxTSP_view::onbtnGFIR3Coef (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 334 of file lms7002_pnlTxTSP_view.cpp.
References lms7002_dlgGFIR_Coefficients::GetCoefficients(), LMS7param, LMS_CH_TX, LMS_GetGFIRCoeff(), LMS_GFIR3, LMS_ReadParam(), LMS_SetGFIRCoeff(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, lms7002_dlgGFIR_Coefficients::SetCoefficients(), status, and UpdateGUI().
void lms7002_pnlTxTSP_view::OnbtnLoadDCIClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 255 of file lms7002_pnlTxTSP_view.cpp.
References DC_REG_TXTSP, LMS7param, LMS_WriteParam(), lmsControl, TSGDCLDI_TXTSP, and pnlTxTSP_view::txtDC_REG_TXTSP.
void lms7002_pnlTxTSP_view::OnbtnLoadDCQClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 265 of file lms7002_pnlTxTSP_view.cpp.
References DC_REG_TXTSP, LMS7param, LMS_WriteParam(), lmsControl, TSGDCLDQ_TXTSP, and pnlTxTSP_view::txtDC_REG_TXTSP.
void lms7002_pnlTxTSP_view::onbtnReadBISTSignature (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 244 of file lms7002_pnlTxTSP_view.cpp.
References BSIGI_TXTSP, BSIGQ_TXTSP, BSTATE_TXTSP, pnlTxTSP_view::lblBSIGI_TXTSP, pnlTxTSP_view::lblBSIGQ_TXTSP, pnlTxTSP_view::lblBSTATE_TXTSP, LMS7param, LMS_ReadParam(), and lmsControl.
void lms7002_pnlTxTSP_view::OnbtnUploadNCOClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 363 of file lms7002_pnlTxTSP_view.cpp.
References i, LMS7param, LMS_CH_TX, LMS_ReadParam(), LMS_SetNCOFrequency(), LMS_SetNCOPhase(), LMS_WriteParam(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, MODE_TX, pnlTxTSP_view::rgrMODE_TX, pnlTxTSP_view::txtFCWPHOmodeAdditional, txtNCOinputs, and UpdateGUI().
void lms7002_pnlTxTSP_view::OnNCOSelectionChange (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 231 of file lms7002_pnlTxTSP_view.cpp.
References i, LMS7param, LMS_WriteParam(), lmsControl, rgrNCOselections, and SEL_TX.
void lms7002_pnlTxTSP_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 183 of file lms7002_pnlTxTSP_view.cpp.
void lms7002_pnlTxTSP_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 192 of file lms7002_pnlTxTSP_view.cpp.
References pnlTxTSP_view::cmbCMIX_GAIN_TXTSP, pnlTxTSP_view::cmbHBI_OVR_TXTSP, pnlTxTSP_view::cmbIQCORR_TXTSP, cmix_gain_txtsp_IndexValuePairs, hbi_ovr_txtsp_IndexValuePairs, LMS7002_WXGUI::index2value(), LMS7_CMIX_GAIN_TXTSP_R3, LMS_WriteParam(), lmsControl, pnlTxTSP_view::rgrMODE_TX, pnlTxTSP_view::rgrTSGFCW_TXTSP, tsgfcw_txtsp_IndexValuePairs, pnlTxTSP_view::txtPhaseAlpha, UpdateNCOinputs(), and wndId2Enum.
void lms7002_pnlTxTSP_view::PHOinputChanged (wxCommandEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 488 of file lms7002_pnlTxTSP_view.cpp.
References freq, i, lblNCOangles, LMS7param, LMS_CH_TX, LMS_ReadParam(), LMS_SetNCOFrequency(), LMS_SetNCOPhase(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, pnlTxTSP_view::rgrMODE_TX, and pnlTxTSP_view::txtFCWPHOmodeAdditional.
void lms7002_pnlTxTSP_view::txtFCWPHOmodeAdditional_OnMouseWheel (wxMouseEvent & event) protected virtual
Reimplemented from pnlTxTSP_view.
Definition at line 527 of file lms7002_pnlTxTSP_view.cpp.
References pnlTxTSP_view::txtFCWPHOmodeAdditional.
void lms7002_pnlTxTSP_view::UpdateGUI ()
Definition at line 434 of file lms7002_pnlTxTSP_view.cpp.
References pnlTxTSP_view::cmbCMIX_GAIN_TXTSP, pnlTxTSP_view::cmbDCCORRI_TXTSP, pnlTxTSP_view::cmbDCCORRQ_TXTSP, pnlTxTSP_view::cmbHBI_OVR_TXTSP, pnlTxTSP_view::cmbIQCORR_TXTSP, CMIX_GAIN_TXTSP, cmix_gain_txtsp_IndexValuePairs, CMIX_GAIN_TXTSP_R3, DCCORRI_TXTSP, DCCORRQ_TXTSP, freq, HBI_OVR_TXTSP, hbi_ovr_txtsp_IndexValuePairs, IQCORR_TXTSP, pnlTxTSP_view::lblRefClk, LMS7param, LMS_CLOCK_TXTSP, LMS_GetClockFreq(), LMS_ReadParam(), lmsControl, MAC, MIMO_SISO, rgrNCOselections, pnlTxTSP_view::rgrTSGFCW_TXTSP, SEL_TX, NumericSlider::SetValue(), TSGFCW_TXTSP, tsgfcw_txtsp_IndexValuePairs, LMS7002_WXGUI::UpdateControlsByMap(), UpdateNCOinputs(), LMS7002_WXGUI::value2index(), and wndId2Enum.
Referenced by onbtnGFIR1Coef(), onbtnGFIR2Coef(), onbtnGFIR3Coef(), OnbtnUploadNCOClick(), and lms7002_mainPanel::UpdateVisiblePanel().
void lms7002_pnlTxTSP_view::UpdateNCOinputs ()
Definition at line 397 of file lms7002_pnlTxTSP_view.cpp.
References fcw, freq, i, pnlTxTSP_view::lblFCWPHOmodeName, LMS7param, LMS_CH_TX, LMS_GetNCOFrequency(), LMS_GetNCOPhase(), LMS_ReadParam(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, phase, pho, pnlTxTSP_view::rgrMODE_TX, pnlTxTSP_view::tableTitleCol1, pnlTxTSP_view::tableTitleCol2, pnlTxTSP_view::txtFCWPHOmodeAdditional, and txtNCOinputs.
Referenced by ParameterChangeHandler(), and UpdateGUI().
Member Data Documentation
std::vector<wxStaticText*> lms7002_pnlTxTSP_view::lblNCOangles protected
Definition at line 46 of file lms7002_pnlTxTSP_view.h.
Referenced by lms7002_pnlTxTSP_view(), and PHOinputChanged().
lms_device_t* lms7002_pnlTxTSP_view::lmsControl protected
Definition at line 43 of file lms7002_pnlTxTSP_view.h.
Referenced by Initialize(), onbtnGFIR1Coef(), onbtnGFIR2Coef(), onbtnGFIR3Coef(), OnbtnLoadDCIClick(), OnbtnLoadDCQClick(), onbtnReadBISTSignature(), OnbtnUploadNCOClick(), OnNCOSelectionChange(), ParameterChangeHandler(), PHOinputChanged(), UpdateGUI(), and UpdateNCOinputs().
std::vector<wxRadioButton*> lms7002_pnlTxTSP_view::rgrNCOselections protected
Definition at line 47 of file lms7002_pnlTxTSP_view.h.
Referenced by lms7002_pnlTxTSP_view(), OnNCOSelectionChange(), and UpdateGUI().
std::vector<wxTextCtrl*> lms7002_pnlTxTSP_view::txtNCOinputs protected
Definition at line 48 of file lms7002_pnlTxTSP_view.h.
Referenced by lms7002_pnlTxTSP_view(), OnbtnUploadNCOClick(), and UpdateNCOinputs().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlTxTSP_view::wndId2Enum protected
Definition at line 44 of file lms7002_pnlTxTSP_view.h.
Referenced by lms7002_pnlTxTSP_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlTxTSP_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlTxTSP_view.cpp