LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/examples/singleRX.cpp File Reference
singleRX.cpp File Reference
RX example.
#include "lime/LimeSuite.h"
#include <iostream>
#include <chrono>
Functions
int error ()
int main (int argc, char **argv)
Variables
lms_device_t * device = NULL
Detailed Description
RX example.
Author
Lime Microsystems (www.limemicro.com)
Definition in file singleRX.cpp.
Function Documentation
int error ()
Definition at line 18 of file singleRX.cpp.
References device, and LMS_Close().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 25 of file singleRX.cpp.
References buffer, lms_stream_t::channel, lms_stream_t::dataFmt, device, error(), lms_stream_status_t::fifoFilledCount, lms_stream_t::fifoSize, lms_stream_status_t::fifoSize, GNUPlotPipe::flush(), freq, gain, i, lms_stream_t::isTx, lms_stream_status_t::linkRate, list, LMS_Calibrate(), LMS_CH_RX, LMS_Close(), LMS_DestroyStream(), LMS_EnableChannel(), lms_stream_t::LMS_FMT_F32, LMS_GetAntenna(), LMS_GetAntennaList(), LMS_GetDeviceList(), LMS_GetGaindB(), LMS_GetLOFrequency(), LMS_GetLPFBWRange(), LMS_GetNormalizedGain(), LMS_GetSampleRate(), LMS_GetStreamStatus(), LMS_Init(), LMS_Open(), LMS_PATH_LNAW, LMS_RecvStream(), LMS_SetAntenna(), LMS_SetLOFrequency(), LMS_SetLPFBW(), LMS_SetNormalizedGain(), LMS_SetSampleRate(), LMS_SetTestSignal(), LMS_SetupStream(), LMS_StartStream(), LMS_StopStream(), LMS_TESTSIG_NCODIV8, lms_range_t::max, lms_range_t::min, range, rate, status, t1, t2, lms_stream_t::throughputVsLatency, GNUPlotPipe::write(), and GNUPlotPipe::writef().
Variable Documentation
lms_device_t* device = NULL
Definition at line 16 of file singleRX.cpp.
Referenced by error(), and main().