LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/examples/gpio_example.cpp File Reference
gpio_example.cpp File Reference
GPIO example.
#include <lime/LimeSuite.h>
#include <iostream>
#include <chrono>
#include <thread>
Functions
int error ()
void print_gpio (int gpio_val)
int main (int argc, char **argv)
Variables
lms_device_t * device = NULL
Detailed Description
GPIO example.
Author
Lime Microsystems (www.limemicro.com)
Definition in file gpio_example.cpp.
Function Documentation
int error ()
Definition at line 14 of file gpio_example.cpp.
References device, and LMS_Close().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 30 of file gpio_example.cpp.
References device, error(), i, list, LMS_GetDeviceList(), LMS_GPIODirWrite(), LMS_GPIORead(), LMS_GPIOWrite(), LMS_Open(), and print_gpio().
void print_gpio (int gpio_val)
Definition at line 21 of file gpio_example.cpp.
References i.
Referenced by main().
Variable Documentation
lms_device_t* device = NULL
Definition at line 12 of file gpio_example.cpp.
Referenced by error(), and main().