LimeSuite-UML: swig::traits_from< PyObject * > Struct Template Reference
swig::traits_from< PyObject * > Struct Template Reference
Public Types
typedef PyObject * value_type
typedef PyObject * value_type
Static Public Member Functions
static PyObject * from (const value_type &val)
static PyObject * from (const value_type &val)
Detailed Description
template<>
struct swig::traits_from< PyObject * >
Definition at line 3995 of file SoapySDRPYTHON_wrap.cxx.
Member Typedef Documentation
typedef PyObject* swig::traits_from< PyObject * >::value_type
Definition at line 3634 of file radar_swigPYTHON_wrap.cxx.
typedef PyObject* swig::traits_from< PyObject * >::value_type
Definition at line 3996 of file SoapySDRPYTHON_wrap.cxx.
Member Function Documentation
static PyObject* swig::traits_from< PyObject * >::from (const value_type & val) inline static
Definition at line 3635 of file radar_swigPYTHON_wrap.cxx.
References c, swig::cgetpos(), swig::check_index(), swig::delslice(), swig::getpos(), swig::getslice(), i, swig::setslice(), swig::slice_adjust(), and val.
static PyObject* swig::traits_from< PyObject * >::from (const value_type & val) inline static
Definition at line 3997 of file SoapySDRPYTHON_wrap.cxx.
References val.
The documentation for this struct was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDRPYTHON_wrap.cxx
/home/erik/prefix/default/src/gr-radar-dev/build/swig/radar_swigPYTHON_wrap.cxx