LimeSuite-UML: /home/erik/prefix/default/src/gr-radar-dev/lib/arg_helpers.h File Reference
arg_helpers.h File Reference
#include <iostream>
#include <vector>
#include <map>
#include <gnuradio/io_signature.h>
#include <boost/lexical_cast.hpp>
#include <boost/tokenizer.hpp>
#include <boost/foreach.hpp>
#include <ciso646>
Classes
struct is_nchan_argument
Typedefs
typedef std::map< std::string, std::string > dict_t
typedef std::pair< std::string, std::string > pair_t
Functions
std::string dict_to_args_string (const dict_t &d)
std::vector< std::string > args_to_vector (const std::string &args)
std::vector< std::string > params_to_vector (const std::string &params)
pair_t param_to_pair (const std::string &param)
dict_t params_to_dict (const std::string &params)
gr::io_signature::sptr args_to_io_signature (const std::string &args)
Typedef Documentation
typedef std::map< std::string, std::string > dict_t
Definition at line 35 of file arg_helpers.h.
typedef std::pair< std::string, std::string > pair_t
Definition at line 36 of file arg_helpers.h.
Function Documentation
gr::io_signature::sptr args_to_io_signature (const std::string & args) inline
Definition at line 121 of file arg_helpers.h.
References args_to_vector(), param_to_pair(), params_to_dict(), and string().
std::vector< std::string > args_to_vector (const std::string & args) inline
Definition at line 49 of file arg_helpers.h.
References string().
Referenced by args_to_io_signature().
std::string dict_to_args_string (const dict_t & d) inline
Definition at line 38 of file arg_helpers.h.
References string().
pair_t param_to_pair (const std::string & param) inline
Definition at line 77 of file arg_helpers.h.
Referenced by args_to_io_signature(), and params_to_dict().
dict_t params_to_dict (const std::string & params) inline
Definition at line 96 of file arg_helpers.h.
References param_to_pair(), params_to_vector(), and string().
Referenced by args_to_io_signature().
std::vector< std::string > params_to_vector (const std::string & params) inline
Definition at line 63 of file arg_helpers.h.
References string().
Referenced by params_to_dict().