LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/apps/SoapyRateTest.cpp File Reference
SoapyRateTest.cpp File Reference
#include <SoapySDR/Device.hpp>
#include <SoapySDR/Formats.hpp>
#include <SoapySDR/Errors.hpp>
#include <string>
#include <cstdlib>
#include <iostream>
#include <stdexcept>
#include <csignal>
#include <chrono>
#include <cstdio>
Functions
void sigIntHandler (const int)
void runRateTestStreamLoop (SoapySDR::Device *device, SoapySDR::Stream *stream, const int direction, const size_t numChans, const size_t elemSize)
int SoapySDRRateTest (const std::string &argStr, const double sampleRate, const std::string &channelStr, const std::string &directionStr)
Variables
static sig_atomic_t loopDone = false
Function Documentation
void runRateTestStreamLoop (SoapySDR::Device * device, SoapySDR::Stream * stream, const int direction, const size_t numChans, const size_t elemSize)
Definition at line 21 of file SoapyRateTest.cpp.
References SoapySDR.Device::activateStream(), SoapySDR.Device::deactivateStream(), SoapySDR::errToStr, flags, SoapySDR.Device::getStreamMTU(), i, loopDone, SoapySDR.Device::readStream(), SoapySDR.Device::readStreamStatus(), sigIntHandler(), SOAPY_SDR_OVERFLOW, SOAPY_SDR_RX, SOAPY_SDR_TIME_ERROR, SOAPY_SDR_TIMEOUT, SOAPY_SDR_TX, SOAPY_SDR_UNDERFLOW, and SoapySDR.Device::writeStream().
Referenced by SoapySDRRateTest().
void sigIntHandler (const int)
Definition at line 16 of file SoapyRateTest.cpp.
References loopDone.
Referenced by runRateTestStreamLoop().
int SoapySDRRateTest (const std::string & argStr, const double sampleRate, const std::string & channelStr, const std::string & directionStr)
Definition at line 117 of file SoapyRateTest.cpp.
References chan, SoapySDR.Device::closeStream(), device, format, SoapySDR::formatToSize, SoapySDR.Device::getNativeStreamFormat(), SoapySDR::KwargsFromString, SoapySDR.Device::make, runRateTestStreamLoop(), SoapySDR.Device::setSampleRate(), SoapySDR.Device::setupStream(), SOAPY_SDR_RX, SOAPY_SDR_TX, stream, and SoapySDR.Device::unmake.
Referenced by main().
Variable Documentation
sig_atomic_t loopDone = false static
Definition at line 15 of file SoapyRateTest.cpp.
Referenced by runRateTestStreamLoop(), and sigIntHandler().