LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/LimeUtil/LimeUtil.cpp File Reference
LimeUtil.cpp File Reference
Command line test app.
#include <VersionInfo.h>
#include <SystemResources.h>
#include <ConnectionRegistry.h>
#include <IConnection.h>
#include <iostream>
#include <cstdlib>
#include <ciso646>
#include <getopt.h>
#include <fstream>
#include "Logger.h"
#include "LMS64CProtocol.h"
Functions
int deviceTestTiming (const std::string &argStr)
int deviceCalSweep (const std::string &argStr, const double start, const double stop, const double step, const double bw, const std::string &dir, const std::string &chans)
static int printHelp (void)
static int printInfo (void)
static int findDevices (void)
static int makeDevice (void)
static int programUpdate (const std::string &argStr)
static int programGateware (const std::string &argStr)
static int programFirmware (const std::string &argStr)
int main (int argc, char *argv[])
Detailed Description
Command line test app.
Author
Lime Microsystems
Definition in file LimeUtil.cpp.
Function Documentation
int deviceCalSweep (const std::string & argStr, const double start, const double stop, const double step, const double bw, const std::string & dir, const std::string & chans)
Definition at line 14 of file LimeUtilCalSweep.cpp.
References device, dir_tx, freq, i, LMS_Calibrate(), LMS_CH_RX, LMS_CH_TX, LMS_Close(), LMS_EnableCalibCache(), LMS_EnableChannel(), LMS_GetLastErrorMessage(), LMS_GetNumChannels(), LMS_Open(), LMS_SetAntenna(), and LMS_SetLOFrequency().
Referenced by main().
int deviceTestTiming (const std::string & argStr)
Definition at line 25 of file LimeUtilTiming.cpp.
References lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::freeConnection(), i, lime::ConnectionRegistry::makeConnection(), lime::LMS7002M::SetConnection(), t1, and lime::LMS7002M::Tx.
Referenced by main().
static int findDevices (void) static
Definition at line 97 of file LimeUtil.cpp.
References lime::ConnectionRegistry::findConnections().
Referenced by main().
int main (int argc, char * argv[])
Definition at line 308 of file LimeUtil.cpp.
References bw, deviceCalSweep(), deviceTestTiming(), findDevices(), makeDevice(), printHelp(), printInfo(), programFirmware(), programGateware(), and programUpdate().
static int makeDevice (void) static
Definition at line 116 of file LimeUtil.cpp.
References lime::ConnectionRegistry::freeConnection(), lime::info(), and lime::ConnectionRegistry::makeConnection().
Referenced by main().
static int printHelp (void) static
Definition at line 34 of file LimeUtil.cpp.
Referenced by main().
static int printInfo (void) static
Definition at line 65 of file LimeUtil.cpp.
References lime::GetABIVersion(), lime::GetAPIVersion(), lime::getAppDataDirectory(), lime::GetBuildTimestamp(), lime::getConfigDirectory(), lime::getHomeDirectory(), lime::GetLibraryVersion(), lime::getLimeSuiteRoot(), lime::listImageSearchPaths(), and lime::ConnectionRegistry::moduleNames().
Referenced by main().
static int programFirmware (const std::string & argStr) static
Definition at line 251 of file LimeUtil.cpp.
References device, lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::freeConnection(), lime::LMS64CProtocol::FX3, lime::GetLastErrorMessage(), lime::ConnectionRegistry::makeConnection(), and status.
Referenced by main().
static int programGateware (const std::string & argStr) static
Definition at line 194 of file LimeUtil.cpp.
References device, lime::ConnectionRegistry::findConnections(), lime::LMS64CProtocol::FPGA, lime::ConnectionRegistry::freeConnection(), lime::GetLastErrorMessage(), lime::ConnectionRegistry::makeConnection(), and status.
Referenced by main().
static int programUpdate (const std::string & argStr) static
Definition at line 157 of file LimeUtil.cpp.
References lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::freeConnection(), lime::GetLastErrorMessage(), lime::ConnectionRegistry::makeConnection(), and status.
Referenced by main().