LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionFTDI/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFTDI/CMakeLists.txt File Reference
Functions
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ConnectionFTDI) if(WIN32) set(USB_FOUND TRUE) set(USB_INCLUDE_DIRS $
FTD3XXLibrary if (CMAKE_SIZEOF_VOID_P EQUAL 8) set(FTD3XX_LIB_DIR $
x64 else () set(FTD3XX_LIB_DIR $
Win32 endif () option(FTD3XX_STATIC"Use static libs for FTD3XX"TRUE) if(FTD3XX_STATIC) set(USB_LIBRARIES $
Static FTD3XX lib SetupAPI add_definitions (-DFTD3XX_STATIC) else() set(USB_LIBRARIES $
FTD3XX lib SetupAPI install (FILES ${FTD3XX_LIB_DIR}/FTD3XX.dll DESTINATION bin) endif() elseif(UNIX) find_package(libusb-1.0) set(USB_FOUND $
set (USB_INCLUDE_DIRS ${LIBUSB_1_INCLUDE_DIRS}) set(USB_LIBRARIES $
message (STATUS"USB_LIBRARIES: ${USB_LIBRARIES}") set(CONNECTION_FTDI_SOURCES $
Function Documentation
Static FTD3XX lib SetupAPI add_definitions (- DFTD3XX_STATIC)
Definition at line 24 of file CMakeLists.txt.
x64 else ()
Definition at line 14 of file CMakeLists.txt.
Win32 endif ()
Definition at line 16 of file CMakeLists.txt.
FTD3XXLibrary if (CMAKE_SIZEOF_VOID_P EQUAL 8)
Definition at line 12 of file CMakeLists.txt.
Referenced by handleToArgs(), init_radar_swig(), init_SoapySDR(), LMS_RecvStream(), LMS_SendStream(), lms7002_pnlMCU_BD_view::OnbtnStartProgrammingClick(), SearchBox(), SearchResults(), SWIG_Python_ConvertPtrAndOwn(), SWIG_Python_DestroyModule(), SWIG_Python_FixMethods(), SwigPyObject_dealloc(), and toString().
FTD3XX lib SetupAPI install (FILES ${FTD3XX_LIB_DIR}/FTD3XX.dll DESTINATION bin)
Definition at line 29 of file CMakeLists.txt.
References elseif(), endif(), and find_package().
Referenced by endif(), print(), set(), and target_compile_definitions().
message (STATUS"USB_LIBRARIES: ${USB_LIBRARIES}")
Definition at line 40 of file CMakeLists.txt.
Referenced by lime::LMS7002M::Log(), set(), and SoapySDR_vlogf().
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ ConnectionFTDI)
Definition at line 5 of file CMakeLists.txt.
set (USB_INCLUDE_DIRS ${LIBUSB_1_INCLUDE_DIRS})
Definition at line 35 of file CMakeLists.txt.
References endif(), and message().