LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/FactoryC.cpp File Reference
FactoryC.cpp File Reference
#include "ErrorHelpers.hpp"
#include "TypeHelpers.hpp"
#include <SoapySDR/Device.h>
#include <SoapySDR/Device.hpp>
#include <cstdlib>
#include <cstring>
Functions
SoapySDRKwargs * SoapySDRDevice_enumerate (const SoapySDRKwargs *args, size_t *length)
SoapySDRKwargs * SoapySDRDevice_enumerateStrArgs (const char *args, size_t *length)
SoapySDRDevice * SoapySDRDevice_make (const SoapySDRKwargs *args)
SoapySDRDevice * SoapySDRDevice_makeStrArgs (const char *args)
int SoapySDRDevice_unmake (SoapySDRDevice *device)
Function Documentation
SoapySDRKwargs* SoapySDRDevice_enumerate (const SoapySDRKwargs * args, size_t * length)
Enumerate a list of available devices on the system.
Parameters
args device construction key/value argument filters
[out] length the number of elements in the result.
Returns
a list of arguments strings, each unique to a device
Definition at line 13 of file FactoryC.cpp.
References __SOAPY_SDR_C_CATCH_RET, __SOAPY_SDR_C_TRY, SoapySDR.Device::enumerate, toKwargs(), and toKwargsList().
SoapySDRKwargs* SoapySDRDevice_enumerateStrArgs (const char * args, size_t * length)
Enumerate a list of available devices on the system. Markup format for args: "keyA=valA, keyB=valB".
Parameters
args a markup string of key/value argument filters
[out] length the number of elements in the result.
Returns
a list of arguments strings, each unique to a device
Definition at line 21 of file FactoryC.cpp.
References __SOAPY_SDR_C_CATCH_RET, __SOAPY_SDR_C_TRY, SoapySDR.Device::enumerate, and toKwargsList().
SoapySDRDevice* SoapySDRDevice_make (const SoapySDRKwargs * args)
Make a new Device object given device construction args. The device pointer will be stored in a table so subsequent calls with the same arguments will produce the same device. For every call to make, there should be a matched call to unmake.
Parameters
args device construction key/value argument map
Returns
a pointer to a new Device object
Definition at line 29 of file FactoryC.cpp.
References __SOAPY_SDR_C_CATCH_RET, __SOAPY_SDR_C_TRY, SoapySDR.Device::make, and toKwargs().
SoapySDRDevice* SoapySDRDevice_makeStrArgs (const char * args)
Make a new Device object given device construction args. The device pointer will be stored in a table so subsequent calls with the same arguments will produce the same device. For every call to make, there should be a matched call to unmake.
Parameters
args a markup string of key/value arguments
Returns
a pointer to a new Device object or null for error
Definition at line 36 of file FactoryC.cpp.
References __SOAPY_SDR_C_CATCH_RET, __SOAPY_SDR_C_TRY, and SoapySDR.Device::make.
int SoapySDRDevice_unmake (SoapySDRDevice * device)
Unmake or release a device object handle.
Parameters
device a pointer to a device object
Returns
0 for success or error code on failure
Definition at line 43 of file FactoryC.cpp.
References __SOAPY_SDR_C_CATCH, __SOAPY_SDR_C_TRY, and SoapySDR.Device::unmake.