LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/QuickTest/TestGUI.cpp File Reference
TestGUI.cpp File Reference
#include <vector>
#include <string>
#include <fstream>
#include "LimeSDRTest.h"
#include <iostream>
#include <getopt.h>
Functions
static int CB_FunctionCLI (int id, int event, const char *msg)
int main (int argc, char **argv)
Function Documentation
static int CB_FunctionCLI (int id, int event, const char * msg) static
Definition at line 301 of file TestGUI.cpp.
References LMS_TEST_LOGFILE, and string().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 315 of file TestGUI.cpp.
References CB_FunctionCLI(), getopt_long(), no_argument, LimeSDRTest::RunTests(), and testNames.