LimeSuite-UML: pnlLimeSDR Class Reference
pnlLimeSDR Class Reference
#include <pnlLimeSDR.h>
Public Member Functions
pnlLimeSDR (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int style=0, wxString name=wxEmptyString)
void Initialize (lms_device_t *pControl)
virtual ~pnlLimeSDR ()
virtual void UpdatePanel ()
void OnGPIOChange (wxCommandEvent &event)
void OnUsrGPIODirChange (wxCommandEvent &event)
void OnUsrGPIOChange (wxCommandEvent &event)
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
Protected Attributes
wxCheckBox * chkRFLB_A_EN
wxCheckBox * chkRFLB_B_EN
wxCheckBox * chkTX1_2_LB_SH
wxCheckBox * chkTX1_2_LB_AT
wxCheckBox * chkTX2_2_LB_SH
wxCheckBox * chkTX2_2_LB_AT
wxStaticText * gpioIn [16]
wxCheckBox * gpioDir [16]
wxCheckBox * gpioOut [16]
wxFlexGridSizer * controlsSizer
wxFlexGridSizer * mainSizer
lms_device_t * lmsControl
int gpioCnt
Detailed Description
Definition at line 17 of file pnlLimeSDR.h.
Constructor & Destructor Documentation
pnlLimeSDR::pnlLimeSDR (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int style = 0, wxString name = wxEmptyString)
Definition at line 22 of file pnlLimeSDR.cpp.
References lmsControl, OnGPIOChange(), OnReadAll(), and OnWriteAll().
pnlLimeSDR::~pnlLimeSDR () virtual
Definition at line 131 of file pnlLimeSDR.cpp.
References i, OnGPIOChange(), OnUsrGPIOChange(), and OnUsrGPIODirChange().
Member Function Documentation
void pnlLimeSDR::Initialize (lms_device_t * pControl)
Definition at line 68 of file pnlLimeSDR.cpp.
References lime::GetDeviceName(), i, lime::info(), lime::LMS_DEV_LIMESDR_PCIE, LMS_GetDeviceInfo(), lmsControl, OnUsrGPIOChange(), and OnUsrGPIODirChange().
Referenced by pnlBoardControls::SetupControls().
void pnlLimeSDR::OnGPIOChange (wxCommandEvent & event)
Definition at line 146 of file pnlLimeSDR.cpp.
References lime::error(), LMS_WriteFPGAReg(), and lmsControl.
Referenced by pnlLimeSDR(), and ~pnlLimeSDR().
void pnlLimeSDR::OnReadAll (wxCommandEvent & event)
Definition at line 238 of file pnlLimeSDR.cpp.
Referenced by pnlLimeSDR().
void pnlLimeSDR::OnUsrGPIOChange (wxCommandEvent & event)
Definition at line 178 of file pnlLimeSDR.cpp.
References lime::error(), i, LMS_GPIOWrite(), and lmsControl.
Referenced by Initialize(), and ~pnlLimeSDR().
void pnlLimeSDR::OnUsrGPIODirChange (wxCommandEvent & event)
Definition at line 162 of file pnlLimeSDR.cpp.
References swig::check(), lime::error(), i, LMS_GPIODirWrite(), and lmsControl.
Referenced by Initialize(), and ~pnlLimeSDR().
void pnlLimeSDR::OnWriteAll (wxCommandEvent & event)
Definition at line 243 of file pnlLimeSDR.cpp.
Referenced by pnlLimeSDR().
void pnlLimeSDR::UpdatePanel () virtual
Definition at line 192 of file pnlLimeSDR.cpp.
References lime::error(), i, LMS_GPIODirRead(), LMS_GPIORead(), LMS_ReadFPGAReg(), and lmsControl.
Member Data Documentation
wxCheckBox* pnlLimeSDR::chkRFLB_A_EN protected
Definition at line 32 of file pnlLimeSDR.h.
wxCheckBox* pnlLimeSDR::chkRFLB_B_EN protected
Definition at line 33 of file pnlLimeSDR.h.
wxCheckBox* pnlLimeSDR::chkTX1_2_LB_AT protected
Definition at line 35 of file pnlLimeSDR.h.
wxCheckBox* pnlLimeSDR::chkTX1_2_LB_SH protected
Definition at line 34 of file pnlLimeSDR.h.
wxCheckBox* pnlLimeSDR::chkTX2_2_LB_AT protected
Definition at line 37 of file pnlLimeSDR.h.
wxCheckBox* pnlLimeSDR::chkTX2_2_LB_SH protected
Definition at line 36 of file pnlLimeSDR.h.
wxFlexGridSizer* pnlLimeSDR::controlsSizer protected
Definition at line 41 of file pnlLimeSDR.h.
int pnlLimeSDR::gpioCnt protected
Definition at line 44 of file pnlLimeSDR.h.
wxCheckBox* pnlLimeSDR::gpioDir[16] protected
Definition at line 39 of file pnlLimeSDR.h.
wxStaticText* pnlLimeSDR::gpioIn[16] protected
Definition at line 38 of file pnlLimeSDR.h.
wxCheckBox* pnlLimeSDR::gpioOut[16] protected
Definition at line 40 of file pnlLimeSDR.h.
lms_device_t* pnlLimeSDR::lmsControl protected
Definition at line 43 of file pnlLimeSDR.h.
wxFlexGridSizer* pnlLimeSDR::mainSizer protected
Definition at line 42 of file pnlLimeSDR.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlLimeSDR.h
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlLimeSDR.cpp