LimeSuite-UML: MeasureDelay Namespace Reference
MeasureDelay Namespace Reference
Functions
def generate_cf32_pulse (numSamps, width=5, scaleFactor=0.3)
def measure_delay (args, rate, freq=None, rxBw=None, txBw=None, rxChan=0, txChan=0, rxAnt=None, txAnt=None, rxGain=None, txGain=None, clockRate=None, numTxSamps=200, numRxSamps=10000, dumpDir=None)
def main ()
Function Documentation
def MeasureDelay.generate_cf32_pulse (numSamps, width = 5, scaleFactor = 0.3)
Definition at line 13 of file MeasureDelay.py.
References measure_delay().
Referenced by measure_delay().
def MeasureDelay.main (void)
Definition at line 154 of file MeasureDelay.py.
References measure_delay().
def MeasureDelay.measure_delay (args, rate, freq = None, rxBw = None, txBw = None, rxChan = 0, txChan = 0, rxAnt = None, txAnt = None, rxGain = None, txGain = None, clockRate = None, numTxSamps = 200, numRxSamps = 10000, dumpDir = None)
Definition at line 34 of file MeasureDelay.py.
References generate_cf32_pulse(), len, print(), and range.
Referenced by generate_cf32_pulse(), and main().