LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/ConnectionHandle.cpp File Reference
ConnectionHandle.cpp File Reference
Represent a connection to a device.
#include "ConnectionHandle.h"
#include <cctype>
#include <string>
#include <map>
#include <iso646.h>
Functions
static std::string trim (const std::string &s)
static std::map< std::string, std::string > argsToMap (const std::string &args)
bool operator== (const ConnectionHandle &lhs, const ConnectionHandle &rhs)
Check two connection handles for equality.
Detailed Description
Represent a connection to a device.
Author
Lime Microsystems
Definition in file ConnectionHandle.cpp.
Function Documentation
static std::map<std::string, std::string> argsToMap (const std::string & args) static
Definition at line 25 of file ConnectionHandle.cpp.
References i, string(), trim(), and val.
Referenced by lime::ConnectionHandle::ConnectionHandle().
bool operator== (const ConnectionHandle & lhs, const ConnectionHandle & rhs)
Check two connection handles for equality.
Definition at line 112 of file ConnectionHandle.cpp.
References lime::ConnectionHandle::serialize().
Referenced by swig::SwigPyIterator::operator!=(), and swig::SwigPySequence_InputIterator< T, Reference >::operator!=().
static std::string trim (const std::string & s) static
Definition at line 17 of file ConnectionHandle.cpp.
References get_pic::s, and string().
Referenced by argsToMap().