LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/gfir_lms.c File Reference
gfir_lms.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include "lms.h"
#include "dfilter.h"
Macros
#define CPREC 16 /* Coefficients precision */
#define CSDPREC 16 /* CSD Coefficients precision */
Functions
int gfir_lms (struct dfilter *hr, struct dfilter *hi, struct dfilter *hcsd, int n, double w1, double w2, double a1, double a2, int cprec, int csdprec, double(*correction)())
void GenerateFilter (int n, double w1, double w2, double a1, double a2, double *coefs)
Macro Definition Documentation
#define CPREC 16 /* Coefficients precision */
Definition at line 20 of file gfir_lms.c.
Referenced by GenerateFilter().
#define CSDPREC 16 /* CSD Coefficients precision */
Definition at line 21 of file gfir_lms.c.
Referenced by GenerateFilter().
Function Documentation
void GenerateFilter (int n, double w1, double w2, double a1, double a2, double * coefs)
Definition at line 150 of file gfir_lms.c.
References dfilter::a, CPREC, CSDPREC, gfir_lms(), i, dfilter::n, and NONE.
Referenced by lime::LMS7_Device::ConfigureGFIR().
int gfir_lms (struct dfilter * hr, struct dfilter * hi, struct dfilter * hcsd, int n, double w1, double w2, double a1, double a2, int cprec, int csdprec, double (*)() correction)
Definition at line 24 of file gfir_lms.c.
References i, lms(), LMS_POINTS, and POSITIVE.
Referenced by GenerateFilter(), and set().