LimeSuite-UML: dlgViewSFR Class Reference
dlgViewSFR Class Reference
#include <dlgViewSFR.h>
Public Member Functions
dlgViewSFR (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize)
virtual ~dlgViewSFR ()
void InitGridData (const unsigned char *data)
Public Attributes
wxGrid * Grid1
Protected Member Functions
void StrArrayIni ()
Protected Attributes
wxArrayString strArray
Static Protected Attributes
static const long ID_GRID1 = wxNewId()
Detailed Description
Definition at line 17 of file dlgViewSFR.h.
Constructor & Destructor Documentation
dlgViewSFR::dlgViewSFR (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize)
Definition at line 19 of file dlgViewSFR.cpp.
References _T.
dlgViewSFR::~dlgViewSFR () virtual
Definition at line 36 of file dlgViewSFR.cpp.
Member Function Documentation
void dlgViewSFR::InitGridData (const unsigned char * data)
Definition at line 112 of file dlgViewSFR.cpp.
References Grid1, i, strArray, and StrArrayIni().
Referenced by lms7002_pnlMCU_BD_view::OnReadSFRfinished().
void dlgViewSFR::StrArrayIni () protected
Definition at line 40 of file dlgViewSFR.cpp.
References i, and strArray.
Referenced by InitGridData().
Member Data Documentation
wxGrid* dlgViewSFR::Grid1
Definition at line 24 of file dlgViewSFR.h.
Referenced by InitGridData().
const long dlgViewSFR::ID_GRID1 = wxNewId() static protected
Definition at line 27 of file dlgViewSFR.h.
wxArrayString dlgViewSFR::strArray protected
Definition at line 28 of file dlgViewSFR.h.
Referenced by InitGridData(), and StrArrayIni().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/dlgViewSFR.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/dlgViewSFR.cpp