LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/mcu_src/spi.c File Reference
spi.c File Reference
#include "spi.h"
#include "LMS7002_REGx51.h"
Functions
void Delay ()
void SPI_transferVariable (unsigned short value)
void SPI_transferVariable_slow (unsigned short value)
void SPI_write (const unsigned short spiAddrReg, const unsigned short spiDataReg)
void SPI_write_slow (const unsigned short spiAddrReg, const unsigned short spiDataReg)
unsigned short SPI_read_slow (const unsigned short spiAddrReg)
unsigned short SPI_read (const unsigned short spiAddrReg)
void Modify_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data)
uint16_t Get_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits)
Function Documentation
void Delay ()
Definition at line 4 of file spi.c.
References TF0, TH0, TL0, and TR0.
Referenced by SPI_read_slow(), and SPI_transferVariable_slow().
uint16_t Get_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits)
Definition at line 123 of file spi.c.
References SPI_read().
Referenced by lime::LMS7002M::CalibrateInternalADC(), lime::LMS7002M::CalibrateRP_BIAS(), CalibrateRx(), lime::LMS7002M::CalibrateRx(), CalibrateRxDCAuto(), CalibrateRxSetup(), CalibrateTx(), lime::LMS7002M::CalibrateTx(), CalibrateTxDCAuto(), CalibrateTxSetup(), ChangeUntilReachRSSI(), CheckSaturationRx(), CheckSaturationTxRx(), GetFrequencyCGEN(), GetFrequencySX(), GetReferenceClk_TSP_MHz(), lime::LMS7002M::GetRSSI(), IsPLLTuned(), ReadCMP(), RunAGC(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), lime::LMS7002M::SetConnection(), SetFrequencySX(), SetupCGEN(), TuneRxFilter(), TuneRxFilterSetup(), TuneTxFilter(), TuneTxFilterSetup(), and UpdateRSSIDelay().
void Modify_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data)
Definition at line 115 of file spi.c.
References SPI_read(), and SPI_write().
Referenced by BinarySearch(), lime::LMS7002M::CalibrateInternalADC(), CalibrateIQImbalance(), lime::LMS7002M::CalibrateRP_BIAS(), CalibrateRx(), CalibrateRxDCAuto(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxDCAuto(), CalibrateTxSetup(), ChangeUntilReachRSSI(), CheckSaturationRx(), CheckSaturationTxRx(), EnableMIMOBuffersIfNecessary(), FlipRisingEdge(), GetFrequencySX(), lime::LMS7002M::GetRSSI(), lime::LMS7002M::LoadDC_REG_IQ(), RunAGC(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), SetDefaultsSX(), SetFrequencyCGEN(), SetFrequencySX(), SetTxLPF_PDs(), SetupCGEN(), TuneRxFilter(), TuneRxFilterSetup(), TuneTxFilter(), TuneTxFilterSetup(), and TuneVCO().
unsigned short SPI_read (const unsigned short spiAddrReg)
Definition at line 92 of file spi.c.
References SPI_transferVariable(), ucSCLK, ucSDIN, ucSDOUT, and ucSEN.
Referenced by Get_SPI_Reg_bits(), and Modify_SPI_Reg_bits().
unsigned short SPI_read_slow (const unsigned short spiAddrReg)
Definition at line 67 of file spi.c.
References Delay(), SPI_transferVariable_slow(), ucSCLK, ucSDIN, ucSDOUT, and ucSEN.
void SPI_transferVariable (unsigned short value)
Definition at line 14 of file spi.c.
References ucSCLK, and ucSDIN.
Referenced by SPI_read(), and SPI_write().
void SPI_transferVariable_slow (unsigned short value)
Definition at line 27 of file spi.c.
References Delay(), ucSCLK, and ucSDIN.
Referenced by SPI_read_slow(), and SPI_write_slow().
void SPI_write (const unsigned short spiAddrReg, const unsigned short spiDataReg)
Definition at line 43 of file spi.c.
References SPI_transferVariable(), ucSCLK, ucSDIN, and ucSEN.
Referenced by Modify_SPI_Reg_bits().
void SPI_write_slow (const unsigned short spiAddrReg, const unsigned short spiDataReg)
Definition at line 55 of file spi.c.
References SPI_transferVariable_slow(), ucSCLK, ucSDIN, and ucSEN.