LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionNovenaRF7/ConnectionNovenaRF7_streaming.cpp File Reference
ConnectionNovenaRF7_streaming.cpp File Reference
#include "ConnectionNovenaRF7.h"
#include <stdio.h>
#include <stdlib.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <sys/stat.h>
#include <fstream>
#include <chrono>
#include <thread>
#include "IConnection.h"
#include "ErrorReporting.h"
Macros
#define IMX6_EIM_BASE_ADDR 0x021b8000
#define IMX6_EIM_CS0_BASE (0x00)
#define IMX6_EIM_CS1_BASE (0x18)
#define IMX6_EIM_CS2_BASE (0x30)
#define IMX6_EIM_CS3_BASE (0x48)
#define IMX6_EIM_WCR (0x90)
#define IMX6_EIM_WIAR (0x94)
#define IMX6_EIM_CS0_BASE_ADDR 0x08040000
#define IMX6_EIM_CS1_BASE_ADDR 0x0c040000
#define DATA_FIFO_ADDR (IMX6_EIM_CS1_BASE_ADDR + 0xf000)
Functions
int fpga_send (unsigned const int addr, const char *buf, const int len)
int fpga_read (unsigned const int addr, unsigned short *buf, const int len)
int readKernelMemory (long offset, int virtualized, int size)
int writeKernelMemory (long offset, long value, int virtualized, int size)
int prep_eim_burst ()
Variables
static const int cSPI_SPEED = 5000000
bool eim_configured = false
Macro Definition Documentation
#define DATA_FIFO_ADDR (IMX6_EIM_CS1_BASE_ADDR + 0xf000)
Definition at line 45 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_BASE_ADDR 0x021b8000
Definition at line 34 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_CS0_BASE (0x00)
Definition at line 35 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_CS0_BASE_ADDR 0x08040000
Definition at line 42 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_CS1_BASE (0x18)
Definition at line 36 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_CS1_BASE_ADDR 0x0c040000
Definition at line 43 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_CS2_BASE (0x30)
Definition at line 37 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_CS3_BASE (0x48)
Definition at line 38 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_WCR (0x90)
Definition at line 39 of file ConnectionNovenaRF7_streaming.cpp.
#define IMX6_EIM_WIAR (0x94)
Definition at line 40 of file ConnectionNovenaRF7_streaming.cpp.
Function Documentation
int fpga_read (unsigned const int addr, unsigned short * buf, const int len)
Definition at line 102 of file ConnectionNovenaRF7_streaming.cpp.
Referenced by lime::ConnectionNovenaRF7::ReceivePacketsLoop().
int fpga_send (unsigned const int addr, const char * buf, const int len)
Definition at line 63 of file ConnectionNovenaRF7_streaming.cpp.
References i.
int prep_eim_burst ()
Definition at line 241 of file ConnectionNovenaRF7_streaming.cpp.
References eim_configured, i, INT(), readKernelMemory(), SP, and writeKernelMemory().
Referenced by lime::ConnectionNovenaRF7::ReceivePacketsLoop().
int readKernelMemory (long offset, int virtualized, int size)
Definition at line 142 of file ConnectionNovenaRF7_streaming.cpp.
Referenced by prep_eim_burst(), and writeKernelMemory().
int writeKernelMemory (long offset, long value, int virtualized, int size)
Definition at line 216 of file ConnectionNovenaRF7_streaming.cpp.
References readKernelMemory().
Referenced by prep_eim_burst().
Variable Documentation
const int cSPI_SPEED = 5000000 static
Definition at line 50 of file ConnectionNovenaRF7_streaming.cpp.
bool eim_configured = false
Definition at line 61 of file ConnectionNovenaRF7_streaming.cpp.
Referenced by prep_eim_burst().