LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/QuickTest/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/QuickTest/CMakeLists.txt File Reference
Functions
cmake_dependent_option (ENABLE_QUICKTEST"LimeSDR quick test utility"ON"ENABLE_LIBRARY"OFF) add_feature_info(LimeQuickTest ENABLE_QUICKTEST"LimeSDR-QuickTest Utility") if(ENABLE_QUICKTEST) add_executable(LimeQuickTest LimeSDRTest.cpp LimeSDRTest_Mini.cpp LimeSDRTest_USB.cpp TestGUI.cpp resources/resource.rc $
external kissFFT kiss_fft c target_link_libraries (LimeQuickTest LimeSuite ${FLTK_LDFLAGS}${FLTK_LIBRARIES}${GLUT_LIBRARY}) set(FLTK_SKIP_FLUID true) find_package(FLTK) execute_process(COMMAND fltk-config--ldflags OUTPUT_VARIABLE FLTK_LDFLAGS OUTPUT_STRIP_TRAILING_WHITESPACE) if(FLTK_FOUND) include_directories($
target_compile_definitions (LimeQuickTest PRIVATE-DQUICKTEST_GUI) target_link_libraries(LimeQuickTest $
Function Documentation
cmake_dependent_option (ENABLE_QUICKTEST"LimeSDR quick test utility"ON"ENABLE_LIBRARY" OFF)
Definition at line 1 of file CMakeLists.txt.
Referenced by set().
target_compile_definitions (LimeQuickTest PRIVATE- DQUICKTEST_GUI)
Definition at line 24 of file CMakeLists.txt.
References endif(), and install().
Referenced by set().
external kissFFT kiss_fft c target_link_libraries (LimeQuickTest LimeSuite ${FLTK_LDFLAGS}${FLTK_LIBRARIES}${GLUT_LIBRARY})
Definition at line 12 of file CMakeLists.txt.
References find_package(), and include_directories().