LimeSuite-UML: lime::ConnectionFX3 Class Reference
lime::ConnectionFX3 Class Reference
#include <ConnectionFX3.h>
Public Member Functions
ConnectionFX3 (void *arg, const std::string &vidpid, const std::string &serial, const unsigned index)
Initializes port type and object necessary to communicate to usb device.
~ConnectionFX3 (void)
Closes connection to chip and deallocates used memory.
int Open (const std::string &vidpid, const std::string &serial, const unsigned index)
Tries to open connected USB device and find communication endpoints.
void Close ()
Closes communication to device.
bool IsOpen ()
Returns connection status.
int GetOpenedIndex ()
int Write (const unsigned char *buffer, int length, int timeout_ms=100) override
Sends given data buffer to chip through USB port.
int Read (unsigned char *buffer, int length, int timeout_ms=100) override
Reads data coming from the chip through USB port.
int ProgramWrite (const char *buffer, const size_t length, const int programmingMode, const int device, ProgrammingCallback callback) override
Uploads program to selected device.
Public Member Functions inherited from lime::LMS64CProtocol
LMS64CProtocol (void)
virtual ~LMS64CProtocol (void)
virtual DeviceInfo GetDeviceInfo (void)
int DeviceReset (int ind=0)
DeviceReset implemented by LMS64C.
int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size) override
TransactSPI implemented by LMS64C.
int WriteI2C (const int addr, const std::string &data)
WriteI2C implemented by LMS64C.
int ReadI2C (const int addr, const size_t numBytes, std::string &data)
ReadI2C implemented by LMS64C.
int WriteRegisters (const uint32_t *addrs, const uint32_t *data, const size_t size)
WriteRegisters (BRDSPI) implemented by LMS64C.
int ReadRegisters (const uint32_t *addrs, uint32_t *data, const size_t size)
ReadRegisters (BRDSPI) implemented by LMS64C.
virtual int TransferPacket (GenericPacket &pkt)
Transfers data between packet and connected device.
LMSinfo GetInfo ()
Returns connected device information.
FPGAinfo GetFPGAInfo ()
Returns information from FPGA gateware.
void VersionCheck ()
int ProgramUpdate (const bool download, IConnection::ProgrammingCallback callback) override
virtual int CustomParameterRead (const uint8_t *ids, double *values, const size_t count, std::string *units) override
Returns value of custom on board control.
virtual int CustomParameterWrite (const uint8_t *ids, const double *values, const size_t count, const std::string &units) override
Sets custom on board control to given value units.
virtual int GPIOWrite (const uint8_t *buffer, const size_t bufLength) override
Writes GPIO values to device.
virtual int GPIORead (uint8_t *buffer, const size_t bufLength) override
Reads GPIO values from device.
virtual int GPIODirWrite (const uint8_t *buffer, const size_t bufLength) override
Write GPIO direction control values to device.
virtual int GPIODirRead (uint8_t *buffer, const size_t bufLength) override
Read GPIO direction configuration from device.
int ProgramMCU (const uint8_t *buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback) override
Uploads program to MCU.
int WriteLMS7002MSPI (const uint32_t *writeData, size_t size, unsigned periphID=0) override
int ReadLMS7002MSPI (const uint32_t *writeData, uint32_t *readData, size_t size, unsigned periphID=0) override
Public Member Functions inherited from lime::IConnection
IConnection (void)
IConnection constructor.
virtual ~IConnection (void)
IConnection destructor.
const ConnectionHandle & GetHandle (void) const
Get the connection handle that was used to create this connection.
int WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
template<typename ReadType >
int ReadRegister (const uint32_t addr, ReadType &data)
Read a single device register.
void SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Protected Member Functions
int GetBuffersCount () const
int CheckStreamSize (int size) const
int SendData (const char *buffer, int length, int epIndex=0, int timeout=100) override
int ReceiveData (char *buffer, int length, int epIndex=0, int timeout=100) override
int BeginDataReading (char *buffer, uint32_t length, int ep) override
Starts asynchronous data reading from board.
bool WaitForReading (int contextHandle, unsigned int timeout_ms) override
Waits for asynchronous data reception.
int FinishDataReading (char *buffer, uint32_t length, int contextHandle) override
Finishes asynchronous data reading from board.
void AbortReading (int ep) override
Aborts reading operations.
int BeginDataSending (const char *buffer, uint32_t length, int ep) override
Starts asynchronous data Sending to board.
bool WaitForSending (int contextHandle, uint32_t timeout_ms) override
Waits for asynchronous data sending.
int FinishDataSending (const char *buffer, uint32_t length, int contextHandle) override
Finishes asynchronous data sending to board.
void AbortSending (int ep) override
Aborts sending operations.
int ResetStreamBuffers () override
Read raw stream data from device streaming port.
eConnectionType GetType (void)
implement in base class
Protected Attributes
USBTransferContext contexts [USB_MAX_CONTEXTS]
USBTransferContext contextsToSend [USB_MAX_CONTEXTS]
bool isConnected
CCyFX3Device * USBDevicePrimary
CCyControlEndPoint * InCtrlEndPt3
CCyControlEndPoint * OutCtrlEndPt3
CCyUSBEndPoint * InEndPt [MAX_EP_CNT]
CCyUSBEndPoint * OutEndPt [MAX_EP_CNT]
CCyUSBEndPoint * InCtrlBulkEndPt
CCyUSBEndPoint * OutCtrlBulkEndPt
std::set< uint8_t > commandsToBulkCtrl
bool bulkCtrlInProgress
bool bulkCtrlAvailable
std::mutex mExtraUsbMutex
Protected Attributes inherited from lime::IConnection
std::function< void(bool, const unsigned char *, const unsigned int)> callback_logData
Static Protected Attributes
static const int USB_MAX_CONTEXTS = 16
static const int MAX_EP_CNT = 16
static const uint8_t ctrlBulkOutAddr = 0x0F
static const uint8_t ctrlBulkInAddr = 0x8F
static const std::set< uint8_t > commandsToBulkCtrlHw1
static const std::set< uint8_t > commandsToBulkCtrlHw2
Additional Inherited Members
Public Types inherited from lime::LMS64CProtocol
enum eConnectionType {
CONNECTION_UNDEFINED = -1, COM_PORT = 0, USB_PORT = 1, SPI_PORT = 2,
PCIE_PORT = 3, CONNECTION_TYPES_COUNT
}
Supported connection types.
enum eLMS_PROTOCOL { LMS_PROTOCOL_UNDEFINED = 0, LMS_PROTOCOL_DIGIC, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA }
enum ProgramWriteTarget { HPM, FX3, FPGA, PROGRAM_WRITE_TARGET_COUNT }
Public Types inherited from lime::IConnection
enum MCU_PROG_MODE { RESET = 0, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM }
typedef std::function< bool(int bsent, int btotal, const char *progressMsg)> ProgrammingCallback
Detailed Description
Definition at line 85 of file ConnectionFX3.h.
Constructor & Destructor Documentation
ConnectionFX3::ConnectionFX3 (void * arg, const std::string & vidpid, const std::string & serial, const unsigned index)
Initializes port type and object necessary to communicate to usb device.
Definition at line 54 of file ConnectionFX3.cpp.
References lime::LMS64CProtocol::LMSinfo::device, lime::error(), lime::LMS64CProtocol::LMSinfo::hardware, i, info, lime::LMS_DEV_LIMESDR, status, and lime::warning().
ConnectionFX3::~ConnectionFX3 (void)
Closes connection to chip and deallocates used memory.
Definition at line 115 of file ConnectionFX3.cpp.
Member Function Documentation
void ConnectionFX3::AbortReading (int ep) override protected virtual
Aborts reading operations.
Reimplemented from lime::IConnection.
Definition at line 561 of file ConnectionFX3.cpp.
References i.
void ConnectionFX3::AbortSending (int ep) override protected virtual
Aborts sending operations.
Reimplemented from lime::IConnection.
Definition at line 694 of file ConnectionFX3.cpp.
References i.
int ConnectionFX3::BeginDataReading (char * buffer, uint32_t length, int ep) override protected virtual
Starts asynchronous data reading from board.
Parameters
*buffer buffer where to store received data
length number of bytes to read
streamBulkInAddr endpoint index?
Returns
handle of transfer context
Reimplemented from lime::IConnection.
Definition at line 454 of file ConnectionFX3.cpp.
References lime::error(), i, and status.
int ConnectionFX3::BeginDataSending (const char * buffer, uint32_t length, int ep) override protected virtual
Starts asynchronous data Sending to board.
Parameters
*buffer buffer to send
length number of bytes to send
streamBulkOutAddr endpoint index?
Returns
handle of transfer context
Reimplemented from lime::IConnection.
Definition at line 592 of file ConnectionFX3.cpp.
References lime::error(), i, and status.
int ConnectionFX3::CheckStreamSize (int size) const protected virtual
Reimplemented from lime::IConnection.
Definition at line 723 of file ConnectionFX3.cpp.
void ConnectionFX3::Close (void)
Closes communication to device.
Definition at line 284 of file ConnectionFX3.cpp.
References i.
int ConnectionFX3::FinishDataReading (char * buffer, uint32_t length, int contextHandle) override protected virtual
Finishes asynchronous data reading from board.
Parameters
buffer array where to store received data
length number of bytes to read
contextHandle handle of which context to finish
Returns
negative values failure, positive number of bytes received
Reimplemented from lime::IConnection.
Definition at line 536 of file ConnectionFX3.cpp.
References len, and status.
int ConnectionFX3::FinishDataSending (const char * buffer, uint32_t length, int contextHandle) override protected virtual
Finishes asynchronous data sending to board.
Parameters
buffer array where to store received data
length number of bytes to read, function changes this value to number of bytes acctually received
contextHandle handle of which context to finish
Returns
false failure, true number of bytes sent
Reimplemented from lime::IConnection.
Definition at line 670 of file ConnectionFX3.cpp.
References len.
int ConnectionFX3::GetBuffersCount () const protected virtual
Reimplemented from lime::IConnection.
Definition at line 718 of file ConnectionFX3.cpp.
int lime::ConnectionFX3::GetOpenedIndex ()
eConnectionType lime::ConnectionFX3::GetType (void) inline protected virtual
implement in base class
Implements lime::LMS64CProtocol.
Definition at line 118 of file ConnectionFX3.h.
bool ConnectionFX3::IsOpen (void) virtual
Returns connection status.
Returns
1-connection open, 0-connection closed.
Reimplemented from lime::IConnection.
Definition at line 316 of file ConnectionFX3.cpp.
int ConnectionFX3::Open (const std::string & vidpid, const std::string & serial, const unsigned index)
Tries to open connected USB device and find communication endpoints.
Returns
Returns 0-Success, other-EndPoints not found or device didn't connect.
Definition at line 126 of file ConnectionFX3.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_USB_FIFO_RST, CTR_R_INDEX, CTR_R_REQCODE, CTR_R_VALUE, CTR_W_INDEX, CTR_W_REQCODE, CTR_W_VALUE, device, lime::error(), i, lime::info(), len, lime::LMS64CProtocol::GenericPacket::outBuffer, and lime::ReportError().
int ConnectionFX3::ProgramWrite (const char * buffer, const size_t length, const int programmingMode, const int index, ProgrammingCallback callback) override virtual
Uploads program to selected device.
Parameters
buffer binary program data
length buffer length
programmingMode to RAM, to FLASH, to EEPROM, etc..
index target device number
callback callback for progress reporting or early termination
Returns
the operation success state
Can be used to program MCU, FPGA, write external on board memory. This could be a quite long operation, use callback to get progress info or to terminate early
Reimplemented from lime::LMS64CProtocol.
Definition at line 746 of file ConnectionFX3.cpp.
References lime::error(), filename, RAM, and lime::ReportError().
int ConnectionFX3::Read (unsigned char * buffer, int length, int timeout_ms = 100) override virtual
Reads data coming from the chip through USB port.
Parameters
buffer pointer to array where received data will be copied, array must be big enough to fit received data.
length number of bytes to read from chip.
timeout_ms timeout limit for operation in milliseconds
Returns
number of bytes received.
Implements lime::LMS64CProtocol.
Definition at line 375 of file ConnectionFX3.cpp.
References CTR_R_INDEX, CTR_R_REQCODE, CTR_R_VALUE, lime::error(), and len.
int ConnectionFX3::ReceiveData (char * buffer, int length, int epIndex = 0, int timeout = 100) override protected virtual
Reimplemented from lime::IConnection.
Definition at line 737 of file ConnectionFX3.cpp.
int ConnectionFX3::ResetStreamBuffers () override protected virtual
Read raw stream data from device streaming port.
Parameters
buffer read buffer pointer
length number of bytes to read
epIndex endpoint identifier?
timeout_ms timeout in milliseconds
Reimplemented from lime::IConnection.
Definition at line 798 of file ConnectionFX3.cpp.
References address, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_USB_FIFO_RST, lime::error(), i, index, len, lime::LMS64CProtocol::GenericPacket::outBuffer, and lime::ReportError().
int ConnectionFX3::SendData (const char * buffer, int length, int epIndex = 0, int timeout = 100) override protected virtual
Reimplemented from lime::IConnection.
Definition at line 728 of file ConnectionFX3.cpp.
bool ConnectionFX3::WaitForReading (int contextHandle, unsigned int timeout_ms) override protected virtual
Waits for asynchronous data reception.
Parameters
contextHandle handle of which context data to wait
timeout_ms number of miliseconds to wait
Returns
1-data received, 0-data not received
Reimplemented from lime::IConnection.
Definition at line 503 of file ConnectionFX3.cpp.
References status, t1, t2, and timeout_ms.
bool ConnectionFX3::WaitForSending (int contextHandle, uint32_t timeout_ms) override protected virtual
Waits for asynchronous data sending.
Parameters
contextHandle handle of which context data to wait
timeout_ms number of miliseconds to wait
Returns
1-data received, 0-data not received
Reimplemented from lime::IConnection.
Definition at line 638 of file ConnectionFX3.cpp.
References status, t1, t2, and timeout_ms.
int ConnectionFX3::Write (const unsigned char * buffer, int length, int timeout_ms = 100) override virtual
Sends given data buffer to chip through USB port.
Parameters
buffer data buffer, must not be longer than 64 bytes.
length given buffer size.
timeout_ms timeout limit for operation in milliseconds
Returns
number of bytes sent.
Implements lime::LMS64CProtocol.
Definition at line 331 of file ConnectionFX3.cpp.
References CTR_W_INDEX, CTR_W_REQCODE, CTR_W_VALUE, and len.
Member Data Documentation
bool lime::ConnectionFX3::bulkCtrlAvailable protected
Definition at line 153 of file ConnectionFX3.h.
bool lime::ConnectionFX3::bulkCtrlInProgress protected
Definition at line 152 of file ConnectionFX3.h.
std::set<uint8_t> lime::ConnectionFX3::commandsToBulkCtrl protected
Definition at line 151 of file ConnectionFX3.h.
const std::set< uint8_t > ConnectionFX3::commandsToBulkCtrlHw1 static protected
Initial value:
=
{
    CMD_BRDSPI_WR, CMD_BRDSPI_RD,
    CMD_LMS7002_WR, CMD_LMS7002_RD,
    CMD_LMS7002_RST,
}
Definition at line 149 of file ConnectionFX3.h.
const std::set< uint8_t > ConnectionFX3::commandsToBulkCtrlHw2 static protected
Initial value:
=
{
    CMD_BRDSPI_WR, CMD_BRDSPI_RD,
    CMD_LMS7002_WR, CMD_LMS7002_RD,
    CMD_ANALOG_VAL_WR, CMD_ANALOG_VAL_RD,
    CMD_ADF4002_WR,
    CMD_LMS7002_RST,
    CMD_GPIO_DIR_WR, CMD_GPIO_DIR_RD,
    CMD_GPIO_WR, CMD_GPIO_RD,
}
Definition at line 150 of file ConnectionFX3.h.
USBTransferContext lime::ConnectionFX3::contexts[USB_MAX_CONTEXTS] protected
Definition at line 122 of file ConnectionFX3.h.
USBTransferContext lime::ConnectionFX3::contextsToSend[USB_MAX_CONTEXTS] protected
Definition at line 123 of file ConnectionFX3.h.
const uint8_t ConnectionFX3::ctrlBulkInAddr = 0x8F static protected
Definition at line 148 of file ConnectionFX3.h.
const uint8_t ConnectionFX3::ctrlBulkOutAddr = 0x0F static protected
Definition at line 147 of file ConnectionFX3.h.
CCyUSBEndPoint* lime::ConnectionFX3::InCtrlBulkEndPt protected
Definition at line 138 of file ConnectionFX3.h.
CCyControlEndPoint* lime::ConnectionFX3::InCtrlEndPt3 protected
Definition at line 131 of file ConnectionFX3.h.
CCyUSBEndPoint* lime::ConnectionFX3::InEndPt[MAX_EP_CNT] protected
Definition at line 135 of file ConnectionFX3.h.
bool lime::ConnectionFX3::isConnected protected
Definition at line 125 of file ConnectionFX3.h.
const int lime::ConnectionFX3::MAX_EP_CNT = 16 static protected
Definition at line 128 of file ConnectionFX3.h.
std::mutex lime::ConnectionFX3::mExtraUsbMutex protected
Definition at line 154 of file ConnectionFX3.h.
CCyUSBEndPoint* lime::ConnectionFX3::OutCtrlBulkEndPt protected
Definition at line 139 of file ConnectionFX3.h.
CCyControlEndPoint* lime::ConnectionFX3::OutCtrlEndPt3 protected
Definition at line 132 of file ConnectionFX3.h.
CCyUSBEndPoint* lime::ConnectionFX3::OutEndPt[MAX_EP_CNT] protected
Definition at line 136 of file ConnectionFX3.h.
const int lime::ConnectionFX3::USB_MAX_CONTEXTS = 16 static protected
Definition at line 120 of file ConnectionFX3.h.
CCyFX3Device* lime::ConnectionFX3::USBDevicePrimary protected
Definition at line 129 of file ConnectionFX3.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFX3/ConnectionFX3.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFX3/ConnectionFX3.cpp