LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/lms7002m_controls.c File Reference
lms7002m_controls.c File Reference
#include "lms7002m_controls.h"
#include "spi.h"
#include "LMS7002M_parameters_compact.h"
#include "math.h"
#include "typedefs.h"
#include "mcu_defines.h"
#include "lms7002_regx51.h"
Macros
#define VERBOSE 0
Functions
uint16_t pow2 (const uint8_t power)
void SaveChipState (bool wr)
void SetDefaultsSX ()
void ClockLogicResets ()
float_type GetFrequencyCGEN ()
uint8_t SetFrequencyCGEN (float_type freq)
float_type GetReferenceClk_TSP_MHz (bool tx)
void SetNCOFrequency (const bool tx, const float freq, uint8_t index)
float_type GetFrequencySX (const bool Tx)
uint8_t SetFrequencySX (const bool tx, const float_type freq_Hz)
static uint8_t ReadCMP (const bool SX)
Performs VCO tuning operations for CLKGEN, SXR, SXT modules.
uint8_t TuneVCO (bool SX)
void WriteMaskedRegs (const RegisterBatch *regs)
uint8_t GetValueOf_c_ctl_pga_rbb (uint8_t g_pga_rbb)
void EnableChannelPowerControls ()
void EnableMIMOBuffersIfNecessary ()
Variables
uint16_t gComparatorDelayCounter = 0xFF00
float_type RefClk = 30.72e6
uint16_t x0020state
const uint16_t chipStateAddr []
uint16_t chipStateData [500]
Macro Definition Documentation
#define VERBOSE 0
Definition at line 19 of file lms7002m_controls.c.
Function Documentation
void ClockLogicResets ()
Definition at line 139 of file lms7002m_controls.c.
References SPI_read(), and SPI_write().
Referenced by RunAGC(), and SaveChipState().
void EnableChannelPowerControls ()
Definition at line 425 of file lms7002m_controls.c.
References SPI_read(), and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
void EnableMIMOBuffersIfNecessary ()
Definition at line 443 of file lms7002m_controls.c.
References EN_NEXTRX_RFE, EN_NEXTTX_TRF, MAC, Modify_SPI_Reg_bits(), SPI_read(), and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
float_type GetFrequencyCGEN ()
Definition at line 152 of file lms7002m_controls.c.
References DIV_OUTCH_CGEN, Get_SPI_Reg_bits(), MSB_LSB, and RefClk.
Referenced by GetReferenceClk_TSP_MHz(), and SetupCGEN().
float_type GetFrequencySX (const bool Tx)
Definition at line 209 of file lms7002m_controls.c.
References DIV_LOCH, EN_DIV2_DIVPROG, Get_SPI_Reg_bits(), MAC, Modify_SPI_Reg_bits(), MSB_LSB, pow2(), RefClk, SPI_read(), and SPI_write().
Referenced by CalibrateRx(), lime::LMS7002M::CalibrateRx(), CalibrateRxSetup(), lime::LMS7002M::CalibrateTx(), and CalibrateTxSetup().
float_type GetReferenceClk_TSP_MHz (bool tx)
Definition at line 191 of file lms7002m_controls.c.
References CLKH_OV_CLKL_CGEN, EN_ADCCLKH_CLKGN, Get_SPI_Reg_bits(), GetFrequencyCGEN(), and pow2().
Referenced by SetNCOFrequency(), and UpdateRSSIDelay().
uint8_t GetValueOf_c_ctl_pga_rbb (uint8_t g_pga_rbb)
Definition at line 414 of file lms7002m_controls.c.
Referenced by RunAGC(), and TuneRxFilterSetup().
uint16_t pow2 (const uint8_t power)
Definition at line 24 of file lms7002m_controls.c.
Referenced by GetFrequencySX(), GetReferenceClk_TSP_MHz(), RxFilterSearch(), SetFrequencySX(), and SetupCGEN().
static uint8_t ReadCMP (const bool SX) static
Performs VCO tuning operations for CLKGEN, SXR, SXT modules.
Parameters
module module selection for tuning 0-cgen, 1-SXR, 2-SXT
Returns
0-success, other-failure
Definition at line 289 of file lms7002m_controls.c.
References gComparatorDelayCounter, Get_SPI_Reg_bits(), MSB_LSB, TF0, TH0, TL0, and TR0.
Referenced by TuneVCO().
void SaveChipState (bool wr)
Definition at line 52 of file lms7002m_controls.c.
References address, chipStateAddr, chipStateData, ClockLogicResets(), i, ROM, SetDefaults(), SPI_read(), SPI_write(), SPI_write_batch(), and x0020state.
Referenced by CalibrateRx(), CalibrateTx(), TuneRxFilter(), and TuneTxFilter().
void SetDefaultsSX ()
Definition at line 127 of file lms7002m_controls.c.
References i, Modify_SPI_Reg_bits(), MSB_LSB, ROM, and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), and TuneRxFilterSetup().
uint8_t SetFrequencyCGEN (float_type freq)
Definition at line 160 of file lms7002m_controls.c.
References DIV_OUTCH_CGEN, freq, INT_SDM_CGEN, MCU_CGEN_TUNE_FAILED, Modify_SPI_Reg_bits(), MSB_LSB, RefClk, TuneVCO(), and VCO_CGEN.
Referenced by ConfigCGEN_ForLPF_IF(), and SetupCGEN().
uint8_t SetFrequencySX (const bool tx, const float_type freq_Hz)
Definition at line 224 of file lms7002m_controls.c.
References CSW_VCO, DIV_LOCH, EN_DIV2_DIVPROG, Get_SPI_Reg_bits(), INT_SDM, MAC, MCU_NO_ERROR, MCU_SXR_TUNE_FAILED, MCU_SXT_TUNE_FAILED, Modify_SPI_Reg_bits(), MSB_LSB, pow2(), RefClk, SEL_VCO, SPI_read(), SPI_write(), temp, and TuneVCO().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilter(), and TuneRxFilterSetup().
void SetNCOFrequency (const bool tx, const float freq, uint8_t index)
Definition at line 201 of file lms7002m_controls.c.
References fcw, GetReferenceClk_TSP_MHz(), and SPI_write().
Referenced by CalibrateRx(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxSetup(), CheckSaturationRx(), CheckSaturationTxRx(), TuneRxFilter(), TuneRxFilterSetup(), and TuneTxFilterSetup().
uint8_t TuneVCO (bool SX)
Definition at line 304 of file lms7002m_controls.c.
References gComparatorDelayCounter, MCU_ERROR, MCU_NO_ERROR, Modify_SPI_Reg_bits(), MSB_LSB, ReadCMP(), and RefClk.
Referenced by IsPLLTuned(), SetFrequencyCGEN(), and SetFrequencySX().
void WriteMaskedRegs (const RegisterBatch * regs)
Definition at line 398 of file lms7002m_controls.c.
References i, index, SPI_read(), and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
Variable Documentation
const uint16_t chipStateAddr[]
Definition at line 30 of file lms7002m_controls.c.
Referenced by SaveChipState().
uint16_t chipStateData[500]
Definition at line 50 of file lms7002m_controls.c.
Referenced by SaveChipState().
uint16_t gComparatorDelayCounter = 0xFF00
Definition at line 16 of file lms7002m_controls.c.
Referenced by ReadCMP(), and TuneVCO().
float_type RefClk = 30.72e6
Definition at line 22 of file lms7002m_controls.c.
Referenced by DCIQ(), Filters(), GetFrequencyCGEN(), GetFrequencySX(), GetRSSI(), LoadDC_REG_TX_IQ(), main(), SetFrequencyCGEN(), SetFrequencySX(), TuneVCO(), UpdateFreq(), and UpdateRSSIDelay().
uint16_t x0020state
Definition at line 29 of file lms7002m_controls.c.
Referenced by SaveChipState().