LimeSuite-UML: lime Namespace Reference
lime Namespace Reference
GUI for writing and reading analog controls.
Namespaces
program_mode
Classes
class ADF4002
struct complex16_t
class ConcurrentQueue
class ConnectionEVB7COM
class ConnectionEVB7COMEntry
class ConnectionFT601
class ConnectionFT601Entry
class ConnectionFX3
class ConnectionFX3Entry
class ConnectionHandle
class ConnectionNovenaRF7
class ConnectionNovenaRF7Entry
class ConnectionRegistry
class ConnectionRegistryEntry
class ConnectionSTREAM_UNITE
class ConnectionSTREAM_UNITEEntry
class ConnectionXillybus
class ConnectionXillybusEntry
struct DeviceInfo
class FPGA
struct FPGA_DataPacket
class FPGA_Mini
class FPGA_Q
class IConnection
class LMS64CProtocol
class LMS7002M
class LMS7002M_RegistersMap
class LMS7_Device
class LMS7_Generic
class LMS7_LimeSDR
class LMS7_LimeSDR_mini
class LMS7_LimeSDR_PCIE
class LMS7_qLimeSDR
class MCU_BD
class RingFIFO
struct RSSI_measurements
class SamplesPacket
struct Si5351_Channel
struct Si5351_PLL
class Si5351C
class StreamChannel
struct StreamConfig
class Streamer
class USBTransferContext
Wrapper class for holding USB asynchronous transfers contexts.
Typedefs
typedef double float_type
typedef void(* LogHandler) (const LogLevel level, const char *message)
Enumerations
enum LogLevel {
LOG_LEVEL_CRITICAL = 0, LOG_LEVEL_ERROR = 1, LOG_LEVEL_WARNING = 2, LOG_LEVEL_INFO = 3,
LOG_LEVEL_DEBUG = 4
}
enum eADC_UNITS {
RAW, VOLTAGE, CURRENT, RESISTANCE,
POWER, TEMPERATURE, ADC_UNITS_COUNT
}
enum eCMD_LMS {
CMD_GET_INFO = 0x00, CMD_LMS6002_RST = 0x10, CMD_SI5356_WR = 0x11, CMD_SI5356_RD = 0x12,
CMD_SI5351_WR = 0x13, CMD_SI5351_RD = 0x14, CMD_TFP410_WR = 0x15, CMD_TFP410_RD = 0x16,
CMD_LMS7002_RST = 0x20, CMD_LMS7002_WR = 0x21, CMD_LMS7002_RD = 0x22, CMD_LMS6002_WR = 0x23,
CMD_LMS6002_RD = 0x24, CMD_LMS_LNA = 0x2A, CMD_LMS_PA = 0x2B, CMD_PROG_MCU = 0x2C,
CMD_ADF4002_WR = 0x31, CMD_USB_FIFO_RST = 0x40, CMD_PE636040_WR = 0x41, CMD_PE636040_RD = 0x42,
CMD_GPIO_DIR_WR = 0x4F, CMD_GPIO_DIR_RD = 0x50, CMD_GPIO_WR = 0x51, CMD_GPIO_RD = 0x52,
CMD_ALTERA_FPGA_GW_WR = 0x53, CMD_ALTERA_FPGA_GW_RD = 0x54, CMD_BRDSPI_WR = 0x55, CMD_BRDSPI_RD = 0x56,
CMD_BRDSPI8_WR = 0x57, CMD_BRDSPI8_RD = 0x58, CMD_BRDCONF_WR = 0x5D, CMD_BRDCONF_RD = 0x5E,
CMD_ANALOG_VAL_WR = 0x61, CMD_ANALOG_VAL_RD = 0x62, CMD_MYRIAD_RST = 0x80, CMD_MYRIAD_WR = 0x81,
CMD_MYRIAD_RD = 0x82, CMD_MEMORY_WR = 0x8C, CMD_MEMORY_RD = 0x8D
}
enum eCMD_STATUS {
STATUS_UNDEFINED, STATUS_COMPLETED_CMD, STATUS_UNKNOWN_CMD, STATUS_BUSY_CMD,
STATUS_MANY_BLOCKS_CMD, STATUS_ERROR_CMD, STATUS_WRONG_ORDER_CMD, STATUS_RESOURCE_DENIED_CMD,
STATUS_COUNT
}
enum eLMS_DEV {
LMS_DEV_UNKNOWN, LMS_DEV_EVB6, LMS_DEV_DIGIGREEN, LMS_DEV_DIGIRED,
LMS_DEV_EVB7, LMS_DEV_ZIPPER, LMS_DEV_SOCKETBOARD, LMS_DEV_EVB7V2,
LMS_DEV_STREAM, LMS_DEV_NOVENA, LMS_DEV_DATASPARK, LMS_DEV_RFSPARK,
LMS_DEV_LMS6002USB, LMS_DEV_RFESPARK, LMS_DEV_LIMESDR, LMS_DEV_LIMESDR_PCIE,
LMS_DEV_LIMESDR_QPCIE, LMS_DEV_LIMESDRMINI, LMS_DEV_USTREAM, LMS_DEV_LIMESDR_SONY,
LMS_DEV_LIMESDR_USB_SP, LMS_DEV_LMS7002M_ULTIMATE_EVB, LMS_DEV_COUNT
}
enum eEXP_BOARD {
EXP_BOARD_UNKNOWN, EXP_BOARD_UNSUPPORTED, EXP_BOARD_NO, EXP_BOARD_MYRIAD1,
EXP_BOARD_MYRIAD2, EXP_BOARD_MYRIAD_NOVENA, EXP_BOARD_HPM1000, EXP_BOARD_MYRIAD7,
EXP_BOARD_HPM7, EXP_BOARD_MYRIAD7_NOVENA, EXP_BOARD_COUNT
}
enum eSi_CLOCK_INPUT { Si_CLKIN, Si_XTAL, Si_CMOS }
Functions
static void critical (const char *format,...)
Log a critical error message with formatting.
static void error (const char *format,...)
Log an error message with formatting.
static void warning (const char *format,...)
Log a warning message with formatting.
static void info (const char *format,...)
Log an information message with formatting.
static void debug (const char *format,...)
Log a debug message with formatting.
static void log (const LogLevel level, const char *format,...)
Log a message with formatting and specified logging level.
void log (const LogLevel level, const char *format, va_list argList)
void registerLogHandler (const LogHandler handler)
const char * logLevelToName (const LogLevel level)
Convert log level to a string name for printing.
const char * GetLastErrorMessage (void)
int ReportError (const int errnum)
int ReportError (const int errnum, const char *format,...)
int ReportError (const char *format,...)
int ReportError (const int errnum, const char *format, va_list argList)
static const char * adcUnits2string (const unsigned units)
static const char * status2string (const int status)
static const char * GetDeviceName (const eLMS_DEV device)
static const char * GetExpansionBoardName (const eEXP_BOARD board)
std::string getLimeSuiteRoot (void)
std::string getHomeDirectory (void)
std::string getAppDataDirectory (void)
std::string getConfigDirectory (void)
std::vector< std::string > listImageSearchPaths (void)
std::string locateImageResource (const std::string &name)
int downloadImageResource (const std::string &name)
std::string GetLibraryVersion (void)
std::string GetBuildTimestamp (void)
std::string GetAPIVersion (void)
std::string GetABIVersion (void)
Variables
const double cgenMax = 640e6
const int RX_EN = 1
const int TX_EN = 1 << 1
const int STREAM_LOAD = 1 << 2
const int SMPL_NR_CLR = 1
const int TXPCT_LOSS_CLR = 1 << 1
const uint16_t PLLCFG_START = 0x1
const uint16_t PHCFG_START = 0x2
const uint16_t PLLRST_START = 0x4
const uint16_t PHCFG_UPDN = 1 << 13
const uint16_t PHCFG_MODE = 1 << 14
const uint16_t busyAddr = 0x0021
static const char adc_units_text [][8] = {"", "V", "A", "Ohm", "W", "C"}
const int dataLength = 2016
const int samples12InPkt = dataLength*8/12/2
const int samples16InPkt = dataLength*8/16/2
static const char status_text [][32]
const char LMS_DEV_NAMES [][80]
const char EXP_BOARD_NAMES [][80]
class LIME_API LMS7_Device
Detailed Description
GUI for writing and reading analog controls.
Author
Lime Microsystems (www.limemicro.com)
Typedef Documentation
typedef double lime::float_type
Definition at line 39 of file LMS7002M.h.
typedef void(* lime::LogHandler) (const LogLevel level, const char *message)
Typedef for the registered log handler function.
Definition at line 57 of file Logger.h.
Enumeration Type Documentation
enum lime::eADC_UNITS
Enumerator
RAW
VOLTAGE
CURRENT
RESISTANCE
POWER
TEMPERATURE
ADC_UNITS_COUNT
Definition at line 10 of file ADCUnits.h.
enum lime::eCMD_LMS
Enumerator
CMD_GET_INFO
CMD_LMS6002_RST
CMD_SI5356_WR
Writes data to SI5356 synthesizer via I2C.
CMD_SI5356_RD
Reads data from SI5356 synthesizer via I2C.
CMD_SI5351_WR
Writes data to SI5351 synthesizer via I2C.
CMD_SI5351_RD
Reads data from SI5351 synthesizer via I2C.
CMD_TFP410_WR
PanelBus DVI (HDMI) Transmitter control.
CMD_TFP410_RD
PanelBus DVI (HDMI) Transmitter control.
CMD_LMS7002_RST
Sets new LMS7002M chips RESET pin level (0, 1, pulse)
CMD_LMS7002_WR
Writes data to LMS7002M chip via SPI.
CMD_LMS7002_RD
Reads data from LMS7002M chip via SPI.
CMD_LMS6002_WR
Writes data to LMS6002 chip via SPI.
CMD_LMS6002_RD
Reads data from LMS6002 chip via SPI.
CMD_LMS_LNA
CMD_LMS_PA
CMD_PROG_MCU
CMD_ADF4002_WR
Writes data to ADF4002 chip via SPI.
CMD_USB_FIFO_RST
CMD_PE636040_WR
CMD_PE636040_RD
CMD_GPIO_DIR_WR
CMD_GPIO_DIR_RD
CMD_GPIO_WR
CMD_GPIO_RD
CMD_ALTERA_FPGA_GW_WR
CMD_ALTERA_FPGA_GW_RD
CMD_BRDSPI_WR
CMD_BRDSPI_RD
CMD_BRDSPI8_WR
CMD_BRDSPI8_RD
CMD_BRDCONF_WR
CMD_BRDCONF_RD
CMD_ANALOG_VAL_WR
CMD_ANALOG_VAL_RD
CMD_MYRIAD_RST
CMD_MYRIAD_WR
CMD_MYRIAD_RD
CMD_MEMORY_WR
CMD_MEMORY_RD
Definition at line 10 of file LMS64CCommands.h.
enum lime::eCMD_STATUS
Enumerator
STATUS_UNDEFINED
STATUS_COMPLETED_CMD
STATUS_UNKNOWN_CMD
STATUS_BUSY_CMD
STATUS_MANY_BLOCKS_CMD
STATUS_ERROR_CMD
STATUS_WRONG_ORDER_CMD
STATUS_RESOURCE_DENIED_CMD
STATUS_COUNT
Definition at line 74 of file LMS64CCommands.h.
enum lime::eEXP_BOARD
Enumerator
EXP_BOARD_UNKNOWN
EXP_BOARD_UNSUPPORTED
EXP_BOARD_NO
EXP_BOARD_MYRIAD1
EXP_BOARD_MYRIAD2
EXP_BOARD_MYRIAD_NOVENA
EXP_BOARD_HPM1000
EXP_BOARD_MYRIAD7
EXP_BOARD_HPM7
EXP_BOARD_MYRIAD7_NOVENA
EXP_BOARD_COUNT
Definition at line 72 of file LMSBoards.h.
enum lime::eLMS_DEV
Enumerator
LMS_DEV_UNKNOWN
LMS_DEV_EVB6
LMS_DEV_DIGIGREEN
LMS_DEV_DIGIRED
LMS_DEV_EVB7
LMS_DEV_ZIPPER
LMS_DEV_SOCKETBOARD
LMS_DEV_EVB7V2
LMS_DEV_STREAM
LMS_DEV_NOVENA
LMS_DEV_DATASPARK
LMS_DEV_RFSPARK
LMS_DEV_LMS6002USB
LMS_DEV_RFESPARK
LMS_DEV_LIMESDR
LMS_DEV_LIMESDR_PCIE
LMS_DEV_LIMESDR_QPCIE
LMS_DEV_LIMESDRMINI
LMS_DEV_USTREAM
LMS_DEV_LIMESDR_SONY
LMS_DEV_LIMESDR_USB_SP
LMS_DEV_LMS7002M_ULTIMATE_EVB
LMS_DEV_COUNT
Definition at line 10 of file LMSBoards.h.
enum lime::eSi_CLOCK_INPUT
Enumerator
Si_CLKIN
Si_XTAL
Si_CMOS
Definition at line 16 of file Si5351C.h.
enum lime::LogLevel
Enumerator
LOG_LEVEL_CRITICAL
A critical error. The application might not be able to continue running successfully.
LOG_LEVEL_ERROR
An error. An operation did not complete successfully, but the application as a whole is not affected.
LOG_LEVEL_WARNING
A warning. An operation completed with an unexpected result.
LOG_LEVEL_INFO
An informational message, usually denoting the successful completion of an operation.
LOG_LEVEL_DEBUG
A debugging message, only shown in Debug configuration.
Definition at line 19 of file Logger.h.
Function Documentation
static const char* lime::adcUnits2string (const unsigned units) static
Definition at line 23 of file ADCUnits.h.
References ADC_UNITS_COUNT, and units.
Referenced by lime::LMS64CProtocol::CustomParameterRead(), pnlBoardControls::getBoardParams(), pnlBoardControls::OnCustomWrite(), and pnlBoardControls::pnlBoardControls().
static void lime::critical (const char * format, ...) inline static
Log a critical error message with formatting.
Definition at line 78 of file Logger.h.
References args, log(), and LOG_LEVEL_CRITICAL.
static void lime::debug (const char * format, ...) inline static
Log a debug message with formatting.
Definition at line 110 of file Logger.h.
References args, format, GetLastErrorMessage(), LIME_API, log(), LOG_LEVEL_DEBUG, and ReportError().
Referenced by lime::LMS7002M::CalibrateAnalogRSSI_DC_Offset(), lime::FPGA::DetectRefClk(), lime::LMS7002M::GetTemperature(), lime::LMS7002M::IsSynced(), lime::LMS7002M::Log(), lime::LMS7_Device::MCU_AGCStart(), lime::ConnectionFT601::Open(), lime::LMS7002M::SetFrequencyCGEN(), lime::LMS7002M::SetFrequencySX(), lime::MCU_BD::SetParameter(), lime::FPGA::SetPllFrequency(), lime::LMS7002M::TuneCGENVCO(), lime::LMS7002M::TuneRxFilter(), lime::LMS7002M::TuneTxFilter(), lime::LMS7002M::TuneVCO(), and lime::MCU_BD::WaitForMCU().
int lime::downloadImageResource (const std::string & name)
Download an image resource given only the file name. The resource will be downloaded in the user's application data directory.
Parameters
name a unique name for the resource file including file extension
Returns
0 for success or error code upon error
Definition at line 164 of file SystemResources.in.cpp.
References getAppDataDirectory(), ReportError(), get_pic::s, string(), and system.
Referenced by lime::LMS64CProtocol::ProgramUpdate().
static void lime::error (const char * format, ...) inline static
Log an error message with formatting.
Definition at line 86 of file Logger.h.
References args, log(), and LOG_LEVEL_ERROR.
Referenced by lime::ConnectionFT601::BeginDataReading(), lime::ConnectionFX3::BeginDataReading(), lime::ConnectionFT601::BeginDataSending(), lime::ConnectionFX3::BeginDataSending(), lime::LMS7002M::CalibrateInternalADC(), lime::LMS7002M::CalibrateRP_BIAS(), lime::LMS7002M::CalibrateTxGain(), lime::Si5351C::ConfigureClocks(), lime::ConnectionEVB7COM::ConnectionEVB7COM(), lime::ConnectionFT601::ConnectionFT601(), lime::ConnectionFT601Entry::ConnectionFT601Entry(), lime::ConnectionFX3::ConnectionFX3(), lime::ConnectionFX3Entry::ConnectionFX3Entry(), lime::LMS7002M::DownloadAll(), lime::ConnectionFT601Entry::enumerate(), lime::ConnectionFX3Entry::enumerate(), LMS_Close(), LMS_Open(), lime::LMS7002M::Log(), pnlLimeSDR::OnGPIOChange(), pnlLimeSDR::OnUsrGPIOChange(), pnlLimeSDR::OnUsrGPIODirChange(), lime::ConnectionFT601::Open(), lime::ConnectionFX3::Open(), lime::ConnectionFT601::ProgramWrite(), lime::ConnectionFX3::ProgramWrite(), lime::ConnectionFT601::Read(), lime::ConnectionFX3::Read(), lime::Streamer::ReceivePacketsLoop(), lime::LMS7002M::RegistersTest(), lime::ConnectionFX3::ResetStreamBuffers(), lime::Si5351C::SetClock(), lime::FPGA::SetPllFrequency(), lime::LMS7_Device::SetRate(), lime::Streamer::SetupStream(), lime::LMS7002M::SPI_read_batch(), lime::LMS7002M::SPI_write_batch(), lime::Streamer::TransmitPacketsLoop(), lime::LMS7002M::TuneCGENVCO(), lime::LMS7002M::TuneRxFilter(), lime::LMS7002M::TuneTxFilter(), pnlLimeSDR::UpdatePanel(), and lime::LMS7002M::UploadAll().
std::string lime::GetABIVersion (void)
Get the ABI/so version of the library.
Definition at line 33 of file VersionInfo.in.cpp.
std::string lime::GetAPIVersion (void)
Get the LimeSuite library API version as a string. The format of the version string is major.minor.increment, where the digits are taken directly from LIME_SUITE_API_VERSION.
Definition at line 23 of file VersionInfo.in.cpp.
References LIME_SUITE_API_VERSION, QUOTE, and string().
std::string lime::getAppDataDirectory (void)
Get the full path to the application data directory. On a unix system this is typically $HOME/.local/share. On a windows system this is typically USERPROFILE%. Also supports the APPDATA environment variable to override the default value.
Definition at line 109 of file SystemResources.in.cpp.
References getBareAppDataDirectory().
Referenced by downloadImageResource(), and listImageSearchPaths().
std::string lime::GetBuildTimestamp (void)
Get the date of the build in "%Y-%M-%d" format.
Definition at line 18 of file VersionInfo.in.cpp.
Referenced by dlgAbout::OnInit().
std::string lime::getConfigDirectory (void)
Get the full path to the library's configuration data directory.
Definition at line 114 of file SystemResources.in.cpp.
References getHomeDirectory().
static const char* lime::GetDeviceName (const eLMS_DEV device) inline static
Definition at line 64 of file LMSBoards.h.
References device, LMS_DEV_COUNT, and LMS_DEV_UNKNOWN.
Referenced by LimeSDRTest::Connect(), lime::LMS7_Device::CreateDevice(), pnlBoardControls::getBoardParams(), lime::LMS64CProtocol::GetDeviceInfo(), lime::IConnection::GetDeviceInfo(), GetExtLoopPair(), pnlLimeSDR::Initialize(), Si5351C_wxgui::ModifyClocksGUI(), LMS_Programing_wxgui::OnbtnOpenClick(), pnlBoardControls::OnUserChangedBoardType(), pnlBoardControls::pnlBoardControls(), lime::LMS64CProtocol::ProgramUpdate(), SetExtLoopback(), lime::FPGA::SetPllFrequency(), and pnlBoardControls::SetupControls().
static const char* lime::GetExpansionBoardName (const eEXP_BOARD board) inline static
Definition at line 102 of file LMSBoards.h.
References EXP_BOARD_COUNT, and EXP_BOARD_UNKNOWN.
Referenced by lime::LMS64CProtocol::GetDeviceInfo(), lime::IConnection::GetDeviceInfo(), and Myriad7_wxgui::UpdatePanel().
std::string lime::getHomeDirectory (void)
Get the full path to the user's home directory
Definition at line 66 of file SystemResources.in.cpp.
Referenced by getBareAppDataDirectory(), and getConfigDirectory().
const char * lime::GetLastErrorMessage (void)
Get the error code to string + any optional message reported.
Definition at line 43 of file Logger.cpp.
References _reportedErrorMessage.
Referenced by debug(), getModuleVersions(), LMS_GetLastErrorMessage(), SoapyLMS7::readGPIO(), SoapyLMS7::readGPIODir(), SoapyLMS7::setBandwidth(), SoapyLMS7::setupStream(), SoapyLMS7::writeGPIO(), SoapyLMS7::writeGPIODir(), and SoapyLMS7::writeSetting().
std::string lime::GetLibraryVersion (void)
Get the library version as a dotted string. The format is major.minor.patch.build-extra.
Definition at line 13 of file VersionInfo.in.cpp.
Referenced by LMS_GetLibraryVersion(), and dlgAbout::OnInit().
std::string lime::getLimeSuiteRoot (void)
Get the root installation directory for the library. Use the configured installation prefix for the library, or override with the LIME_SUITE_ROOT environment variable.
Definition at line 34 of file SystemResources.in.cpp.
References string().
Referenced by listImageSearchPaths().
static void lime::info (const char * format, ...) inline static
Log an information message with formatting.
Definition at line 102 of file Logger.h.
References args, log(), and LOG_LEVEL_INFO.
Referenced by lime::Si5351C::ConfigureClocks(), lime::LMS7_Device::ConfigureTXLPF(), LimeSDRTest::Connect(), lime::LMS7_Device::CreateDevice(), lime::FPGA::DetectRefClk(), lime::ConnectionSTREAM_UNITEEntry::enumerate(), lime::IConnection::GetDeviceInfo(), lime::LMS64CProtocol::GetFPGAInfo(), lime::ConnectionNovenaRF7::StreamChannel::GetInfo(), lime::LMS7_Device::GetInfo(), lime::StreamChannel::GetInfo(), lime::LMS64CProtocol::GetInfo(), SoapyLMS7::getStreamArgsInfo(), pnlLimeSDR::Initialize(), lime::LMS7002M::Log(), lime::LMS7_Device::MCU_AGCStart(), lime::ConnectionFX3::Open(), lime::LMS64CProtocol::ProgramUpdate(), lime::LMS7_Device::SetClockFreq(), lime::LMS7002M::SetFrequencySX(), lime::LMS7_Device::SetLPF(), Myriad7_wxgui::UpdatePanel(), and lime::LMS64CProtocol::VersionCheck().
std::vector< std::string > lime::listImageSearchPaths (void)
Get a list of directories to search for image resources. Directories are returned in the order of search priority. Priority goes to the LIME_SUITE_IMAGE_PATH environment variable, and then images in the user's application data directory, and finally images in the installation root directory.
Definition at line 121 of file SystemResources.in.cpp.
References getAppDataDirectory(), getLimeSuiteRoot(), and string().
Referenced by locateImageResource().
std::string lime::locateImageResource (const std::string & name)
Get the full file path to an image resource given only the file name.
Parameters
name a unique name for the resource file including file extension
Returns
the full filesystem path to the resource if it exists or empty
Definition at line 154 of file SystemResources.in.cpp.
References listImageSearchPaths(), and string().
Referenced by lime::LMS64CProtocol::ProgramUpdate().
static void lime::log (const LogLevel level, const char * format, ...) inline static
Log a message with formatting and specified logging level.
Definition at line 70 of file Logger.h.
References args.
Referenced by critical(), debug(), error(), info(), ReportError(), and warning().
void lime::log (const LogLevel level, const char * format, va_list argList)
Send a message to the registered logger.
Parameters
level a possible logging level
format a printf style format string
argList an argument list for the formatter
Definition at line 72 of file Logger.cpp.
const char * lime::logLevelToName (const LogLevel level)
Convert log level to a string name for printing.
Definition at line 84 of file Logger.cpp.
References LOG_LEVEL_CRITICAL, LOG_LEVEL_DEBUG, LOG_LEVEL_ERROR, LOG_LEVEL_INFO, and LOG_LEVEL_WARNING.
Referenced by pnlMiniLog::HandleMessage().
void lime::registerLogHandler (const LogHandler handler)
Register a new system log handler. Platforms should call this to replace the default stdio handler.
Definition at line 79 of file Logger.cpp.
Referenced by findIConnection(), LMS7SuiteAppFrame::LMS7SuiteAppFrame(), LMS_RegisterLogHandler(), main(), makeIConnection(), and LimeSDRTest::RunTests().
int lime::ReportError (const int errnum)
Report a typical errno style error. The resulting error message comes from strerror().
Parameters
errnum a recognized error code
Returns
a non-zero status code to return
Definition at line 48 of file Logger.cpp.
References errToStr().
Referenced by BoardLoopbackStore::BoardLoopbackStore(), CalculateGoertzelBin(), lime::LMS7002M::CalibrateAnalogRSSI_DC_Offset(), lime::LMS7002M::CalibrateInternalADC(), lime::LMS7002M::CalibrateRP_BIAS(), lime::LMS7002M::CalibrateRx(), lime::LMS7002M::CalibrateTx(), lime::ConnectionNovenaRF7::CloseStream(), computeGoertzel(), convertStatus(), lime::LMS7_Device::CreateDevice(), lime::IConnection::CustomParameterRead(), lime::IConnection::CustomParameterWrite(), debug(), lime::LMS64CProtocol::DeviceReset(), lime::IConnection::DeviceReset(), downloadImageResource(), lime::LMS7_Device::GetClockFreq(), lime::LMS7002M::GetGFIRCoefficients(), lime::LMS7002M::GetNCOFrequency(), lime::LMS7002M::GetNCOPhaseOffset_Deg(), lime::IConnection::GPIODirRead(), lime::IConnection::GPIODirWrite(), lime::IConnection::GPIORead(), lime::IConnection::GPIOWrite(), lime::ConnectionXillybus::IsOpen(), LMS_Calibrate(), LMS_DestroyStream(), LMS_Disconnect(), LMS_EnableCalibCache(), LMS_EnableChannel(), LMS_GetAntenna(), LMS_GetAntennaBW(), LMS_GetAntennaList(), LMS_GetChipTemperature(), LMS_GetClockFreq(), LMS_GetDeviceInfo(), LMS_GetGaindB(), LMS_GetGFIRCoeff(), LMS_GetLOFrequency(), LMS_GetLOFrequencyRange(), LMS_GetLPFBW(), LMS_GetLPFBWRange(), LMS_GetNCOFrequency(), LMS_GetNCOIndex(), LMS_GetNCOPhase(), LMS_GetNormalizedGain(), LMS_GetNumChannels(), LMS_GetProgramModes(), LMS_GetSampleRate(), LMS_GetSampleRateRange(), LMS_GetTestSignal(), LMS_GPIODirRead(), LMS_GPIODirWrite(), LMS_GPIORead(), LMS_GPIOWrite(), LMS_Init(), LMS_LoadConfig(), LMS_Program(), LMS_ReadCustomBoardParam(), LMS_ReadFPGAReg(), LMS_ReadLMSReg(), LMS_ReadParam(), LMS_Reset(), LMS_SaveConfig(), LMS_SetAntenna(), LMS_SetClockFreq(), LMS_SetGaindB(), LMS_SetGFIR(), LMS_SetGFIRCoeff(), LMS_SetGFIRLPF(), LMS_SetLOFrequency(), LMS_SetLPF(), LMS_SetLPFBW(), LMS_SetNCOFrequency(), LMS_SetNCOIndex(), LMS_SetNCOPhase(), LMS_SetNormalizedGain(), LMS_SetSampleRate(), LMS_SetSampleRateDir(), LMS_SetTestSignal(), LMS_SetupStream(), LMS_Synchronize(), LMS_TransferLMS64C(), LMS_WriteCustomBoardParam(), LMS_WriteFPGAReg(), LMS_WriteLMSReg(), LMS_WriteParam(), lime::LMS7002M::LoadConfig(), lime::LMS7002M::LoadConfigLegacyFile(), lime::ConnectionEVB7COM::Open(), lime::ConnectionXillybus::Open(), lime::ConnectionNovenaRF7::Open(), lime::ConnectionFT601::Open(), lime::ConnectionFX3::Open(), lime::LMS7_Device::Program(), lime::MCU_BD::Program_MCU(), lime::IConnection::ProgramMCU(), lime::LMS64CProtocol::ProgramUpdate(), lime::IConnection::ProgramUpdate(), lime::ConnectionFX3::ProgramWrite(), lime::LMS64CProtocol::ProgramWrite(), lime::IConnection::ProgramWrite(), lime::ConnectionXillybus::Read(), lime::LMS64CProtocol::ReadADF4002SPI(), readGoertzelValues(), lime::LMS64CProtocol::ReadI2C(), lime::IConnection::ReadI2C(), lime::IConnection::ReadRegisters(), lime::ConnectionXillybus::ReceiveData(), lime::LMS7002M::RegistersTestInterval(), ReportError(), lime::ConnectionFX3::ResetStreamBuffers(), lime::FPGA::ResetTimestamp(), lime::ConnectionXillybus::SendData(), lime::LMS7_Device::SetActiveChip(), lime::LMS7_Device::SetClockFreq(), lime::FPGA::SetDirectClocking(), SetExtLoopback(), lime::LMS7002M::SetFrequencyCGEN(), lime::LMS7002M::SetFrequencySX(), lime::LMS7_Device::SetGFIRCoef(), lime::LMS7002M::SetGFIRCoefficients(), lime::LMS7002M::SetNCOFrequency(), lime::LMS7002M::SetNCOPhaseOffset(), lime::FPGA::SetPllClock(), lime::FPGA::SetPllFrequency(), lime::LMS7_Device::SetRate(), lime::ConnectionNovenaRF7::SetupStream(), lime::LMS7002M::SPI_read(), lime::LMS64CProtocol::TransactSPI(), lime::IConnection::TransactSPI(), lime::LMS64CProtocol::TransferPacket(), lime::LMS7002M::TuneRxFilter(), lime::LMS7002M::TuneTxFilter(), lime::LMS7002M::TuneVCO(), lime::FPGA_Mini::UploadWFM(), lime::FPGA::UploadWFM(), lime::LMS7_Device::UploadWFM(), lime::ConnectionXillybus::Write(), lime::ConnectionEVB7COM::Write(), lime::LMS64CProtocol::WriteI2C(), lime::IConnection::WriteI2C(), lime::IConnection::WriteRegisters(), and BoardLoopbackStore::~BoardLoopbackStore().
int lime::ReportError (const int errnum, const char * format, ...) inline
Report an error as an integer code and a formatted message string.
Parameters
errnum a recognized error code
format a format string followed by args
Returns
a non-zero status code to return
Definition at line 161 of file Logger.h.
References ReportError(), and status.
int lime::ReportError (const char * format, ...) inline
Report an error as a formatted message string. The reported errnum is 0 - no relevant error code.
Parameters
format a format string followed by args
Returns
a non-zero status code to return
Definition at line 170 of file Logger.h.
References ReportError(), and status.
int lime::ReportError (const int errnum, const char * format, va_list argList)
Report an error as an integer code and message format arguments
Parameters
errnum a recognized error code
format a printf-style format string
argList the format string args as a va_list
Returns
a non-zero status code to return
Definition at line 53 of file Logger.cpp.
References _reportedErrorCode, _reportedErrorMessage, log(), LOG_LEVEL_ERROR, and MAX_MSG_LEN.
static const char* lime::status2string (const int status) inline static
Definition at line 99 of file LMS64CCommands.h.
References status, and STATUS_COUNT.
Referenced by convertStatus(), LMS_TransferLMS64C(), and lime::LMS64CProtocol::ProgramWrite().
static void lime::warning (const char * format, ...) inline static
Log a warning message with formatting.
Definition at line 94 of file Logger.h.
References args, log(), and LOG_LEVEL_WARNING.
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), lime::Streamer::AlignRxTSP(), lime::ConnectionFX3::ConnectionFX3(), lime::ConnectionXillybus::ConnectionXillybus(), lime::Streamer::GetPhaseOffset(), LMS_Disconnect(), LMS_IsOpen(), lime::LMS7002M::Log(), lime::Streamer::ReceivePacketsLoop(), lime::LMS7002M::ResetChip(), lime::LMS7_Device::SetGFIRCoef(), lime::LMS7_Device::SetLPF(), lime::LMS7_LimeSDR_mini::SetPath(), lime::Streamer::SetupStream(), lime::Streamer::TransmitPacketsLoop(), lime::FPGA::UploadWFM(), and lime::LMS64CProtocol::VersionCheck().
Variable Documentation
const char lime::adc_units_text[][8] = {"", "V", "A", "Ohm", "W", "C"} static
Definition at line 21 of file ADCUnits.h.
const uint16_t lime::busyAddr = 0x0021
Definition at line 31 of file FPGA_common.cpp.
const double lime::cgenMax = 640e6
Definition at line 7 of file device_constants.h.
Referenced by lime::LMS7_LimeSDR_mini::SetRate(), and lime::LMS7_Device::SetRate().
const int lime::dataLength = 2016
Definition at line 11 of file dataTypes.h.
Referenced by lime::Streamer::ReceivePacketsLoop().
const char lime::EXP_BOARD_NAMES[][80]
Definition at line 88 of file LMSBoards.h.
class LIME_API lime::LMS7_Device
Definition at line 19 of file SoapyLMS7.h.
Referenced by LMS7SuiteAppFrame::LMS7SuiteAppFrame(), and dlgConnectionSettings::OnDisconnect().
const char lime::LMS_DEV_NAMES[][80]
Definition at line 38 of file LMSBoards.h.
const uint16_t lime::PHCFG_MODE = 1 << 14
Definition at line 29 of file FPGA_common.cpp.
Referenced by lime::FPGA::SetPllClock(), and lime::FPGA::SetPllFrequency().
const uint16_t lime::PHCFG_START = 0x2
Definition at line 26 of file FPGA_common.cpp.
const uint16_t lime::PHCFG_UPDN = 1 << 13
Definition at line 28 of file FPGA_common.cpp.
Referenced by lime::FPGA::SetPllClock(), and lime::FPGA::SetPllFrequency().
const uint16_t lime::PLLCFG_START = 0x1
Definition at line 25 of file FPGA_common.cpp.
const uint16_t lime::PLLRST_START = 0x4
Definition at line 27 of file FPGA_common.cpp.
const int lime::RX_EN = 1
Definition at line 17 of file FPGA_common.cpp.
Referenced by lime::FPGA::StartStreaming().
const int lime::samples12InPkt = dataLength*8/12/2
Definition at line 32 of file dataTypes.h.
Referenced by lime::Streamer::GetStreamSize(), lime::Streamer::ReceivePacketsLoop(), TEST_F(), lime::Streamer::TransmitPacketsLoop(), and lime::FPGA::UploadWFM().
const int lime::samples16InPkt = dataLength*8/16/2
Definition at line 34 of file dataTypes.h.
Referenced by lime::Streamer::GetStreamSize(), lime::Streamer::ReceivePacketsLoop(), lime::Streamer::TransmitPacketsLoop(), and lime::FPGA::UploadWFM().
const int lime::SMPL_NR_CLR = 1
Definition at line 22 of file FPGA_common.cpp.
Referenced by lime::FPGA::ResetTimestamp().
const char lime::status_text[][32] static
Definition at line 87 of file LMS64CCommands.h.
const int lime::STREAM_LOAD = 1 << 2
Definition at line 19 of file FPGA_common.cpp.
const int lime::TX_EN = 1 << 1
Definition at line 18 of file FPGA_common.cpp.
Referenced by lime::FPGA::StopStreaming().
const int lime::TXPCT_LOSS_CLR = 1 << 1
Definition at line 23 of file FPGA_common.cpp.