LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/external/kissFFT/kiss_fft.h File Reference
kiss_fft.h File Reference
#include <stdlib.h>
#include <stdio.h>
#include <math.h>
#include <string.h>
Classes
struct kiss_fft_cpx
Macros
#define KISS_FFT_MALLOC malloc
#define KISS_FFT_FREE free
#define kiss_fft_scalar float
#define kiss_fft_free free
#define kiss_fftr_next_fast_size_real(n) (kiss_fft_next_fast_size(((n)+1)>>1)<<1)
Typedefs
typedef struct kiss_fft_state * kiss_fft_cfg
Functions
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void *mem, size_t *lenmem)
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout)
void kiss_fft_stride (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout, int fin_stride)
void kiss_fft_cleanup (void)
int kiss_fft_next_fast_size (int n)
Macro Definition Documentation
#define KISS_FFT_FREE free
Definition at line 33 of file kiss_fft.h.
#define kiss_fft_free free
Definition at line 102 of file kiss_fft.h.
Referenced by fftviewer_frFFTviewer::StreamingLoop().
#define KISS_FFT_MALLOC malloc
Definition at line 32 of file kiss_fft.h.
Referenced by kiss_fft_alloc().
#define kiss_fft_scalar float
Definition at line 47 of file kiss_fft.h.
#define kiss_fftr_next_fast_size_real (n) (kiss_fft_next_fast_size(((n)+1)>>1)<<1)
Definition at line 117 of file kiss_fft.h.
Typedef Documentation
typedef struct kiss_fft_state* kiss_fft_cfg
Definition at line 56 of file kiss_fft.h.
Function Documentation
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx * fin, kiss_fft_cpx * fout)
Definition at line 385 of file kiss_fft.c.
References kiss_fft_stride().
Referenced by endif(), LimeSDRTest::RunTest(), set(), and fftviewer_frFFTviewer::StreamingLoop().
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void * mem, size_t * lenmem)
Definition at line 339 of file kiss_fft.c.
References kiss_fft_state::factors, i, kiss_fft_state::inverse, kf_cexp, kf_factor(), KISS_FFT_MALLOC, kiss_fft_state::nfft, phase, and kiss_fft_state::twiddles.
Referenced by LimeSDRTest::RunTest(), and fftviewer_frFFTviewer::StreamingLoop().
void kiss_fft_cleanup (void)
Definition at line 391 of file kiss_fft.c.
int kiss_fft_next_fast_size (int n)
Definition at line 396 of file kiss_fft.c.
void kiss_fft_stride (kiss_fft_cfg cfg, const kiss_fft_cpx * fin, kiss_fft_cpx * fout, int fin_stride)
Definition at line 371 of file kiss_fft.c.
References kiss_fft_state::factors, kf_work(), KISS_FFT_TMP_ALLOC, KISS_FFT_TMP_FREE, and kiss_fft_state::nfft.
Referenced by kiss_fft().