LimeSuite-UML: LMS7SuiteAppFrame Class Reference
LMS7SuiteAppFrame Class Reference
Implementing AppFrame.
#include <lms7suiteAppFrame.h>
Public Member Functions
LMS7SuiteAppFrame (wxWindow *parent)
Constructor.
virtual ~LMS7SuiteAppFrame ()
Public Member Functions inherited from AppFrame_view
AppFrame_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("Lime Suite GUI"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL)
~AppFrame_view ()
Static Public Attributes
static int m_lmsSelection = 0
Protected Member Functions
void OnClose (wxCloseEvent &event)
void OnQuit (wxCommandEvent &event)
void OnShowConnectionSettings (wxCommandEvent &event)
void OnAbout (wxCommandEvent &event)
void OnControlBoardConnect (wxCommandEvent &event)
void OnDataBoardConnect (wxCommandEvent &event)
void HandleLMSevent (wxCommandEvent &event)
void OnFFTviewerClose (wxCloseEvent &event)
void OnShowFFTviewer (wxCommandEvent &event)
void OnADF4002Close (wxCloseEvent &event)
void OnShowADF4002 (wxCommandEvent &event)
void OnSi5351Close (wxCloseEvent &event)
void OnShowSi5351C (wxCommandEvent &event)
void OnProgramingClose (wxCloseEvent &event)
void OnShowPrograming (wxCommandEvent &event)
void OnHPM7Close (wxCloseEvent &event)
void OnShowHPM7 (wxCommandEvent &event)
void OnFPGAcontrolsClose (wxCloseEvent &event)
void OnShowFPGAcontrols (wxCommandEvent &event)
void OnMyriad7Close (wxCloseEvent &event)
void OnShowMyriad7 (wxCommandEvent &event)
void OnDeviceInfoClose (wxCloseEvent &event)
void OnShowDeviceInfo (wxCommandEvent &event)
void OnSPIClose (wxCloseEvent &event)
void OnShowSPI (wxCommandEvent &event)
void OnBoardControlsClose (wxCloseEvent &event)
void OnShowBoardControls (wxCommandEvent &event)
void OnChangeCacheSettings (wxCommandEvent &event)
void OnLmsChanged (wxCommandEvent &event)
void OnLogMessage (wxCommandEvent &event)
void UpdateConnections (lms_device_t *port)
Static Protected Member Functions
static void OnGlobalLogEvent (const lime::LogLevel level, const char *message)
static void OnLogEvent (const char *text, unsigned int type)
static void OnLogDataTransfer (bool Tx, const unsigned char *data, const unsigned int length)
Protected Attributes
lms_device_t * lmsControl
pnlMiniLog * mMiniLog
fftviewer_frFFTviewer * fftviewer
ADF4002_wxgui * adfGUI
Si5351C_wxgui * si5351gui
LMS_Programing_wxgui * programmer
HPM7_wxgui * hpm7
FPGAcontrols_wxgui * fpgaControls
Myriad7_wxgui * myriad7
dlgDeviceInfo * deviceInfo
SPI_wxgui * spi
pnlBoardControls * boardControlsGui
Protected Attributes inherited from AppFrame_view
wxMenuBar * mbar
wxMenu * fileMenu
wxMenu * mnuOptions
wxMenuItem * mnuCacheValues
wxMenu * mnuModules
wxMenu * helpMenu
wxStatusBar * statusBar
wxBoxSizer * bSizer6
wxScrolledWindow * m_scrolledWindow1
wxFlexGridSizer * contentSizer
lms7002_mainPanel * mContent
Static Protected Attributes
static const wxString cWindowTitle = _("LMS7Suite")
static const int cDeviceInfoCollumn = 1
static const int cDeviceVerRevMaskCollumn = 2
static LMS7SuiteAppFrame * obj_ptr =nullptr
Additional Inherited Members
Protected Types inherited from AppFrame_view
enum { idMenuQuit = 1000, idMenuAbout }
Detailed Description
Implementing AppFrame.
Definition at line 28 of file lms7suiteAppFrame.h.
Constructor & Destructor Documentation
LMS7SuiteAppFrame::LMS7SuiteAppFrame (wxWindow * parent)
Constructor.
Definition at line 138 of file lms7suiteAppFrame.cpp.
References adfGUI, boardControlsGui, AppFrame_view::bSizer6, deviceInfo, fftviewer, fpgaControls, HandleLMSevent(), hpm7, lime::LMS7_Device, lmsControl, AppFrame_view::m_scrolledWindow1, mMiniLog, AppFrame_view::mnuCacheValues, myriad7, obj_ptr, OnControlBoardConnect(), OnGlobalLogEvent(), OnLmsChanged(), OnLogMessage(), programmer, lime::registerLogHandler(), si5351gui, spi, AppFrame_view::statusBar, and UpdateConnections().
LMS7SuiteAppFrame::~LMS7SuiteAppFrame () virtual
Definition at line 187 of file lms7suiteAppFrame.cpp.
References HandleLMSevent(), LMS_Close(), lmsControl, and OnFFTviewerClose().
Member Function Documentation
void LMS7SuiteAppFrame::HandleLMSevent (wxCommandEvent & event) protected
Definition at line 51 of file lms7suiteAppFrame.cpp.
Referenced by LMS7SuiteAppFrame(), and ~LMS7SuiteAppFrame().
void LMS7SuiteAppFrame::OnAbout (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 221 of file lms7suiteAppFrame.cpp.
void LMS7SuiteAppFrame::OnADF4002Close (wxCloseEvent & event) protected
Definition at line 362 of file lms7suiteAppFrame.cpp.
References adfGUI.
Referenced by OnShowADF4002().
void LMS7SuiteAppFrame::OnBoardControlsClose (wxCloseEvent & event) protected
Definition at line 611 of file lms7suiteAppFrame.cpp.
References boardControlsGui.
Referenced by OnShowBoardControls().
void LMS7SuiteAppFrame::OnChangeCacheSettings (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 617 of file lms7suiteAppFrame.cpp.
References LMS_EnableCalibCache(), and lmsControl.
void LMS7SuiteAppFrame::OnClose (wxCloseEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 196 of file lms7suiteAppFrame.cpp.
void LMS7SuiteAppFrame::OnControlBoardConnect (wxCommandEvent & event) protected
Definition at line 253 of file lms7suiteAppFrame.cpp.
References boardControlsGui, lms_dev_info_t::deviceName, lms_dev_info_t::firmwareVersion, lms_dev_info_t::gatewareVersion, lime::LMS7002M::GetReferenceClk_SX(), lms_dev_info_t::hardwareVersion, info, lms(), LMS7param, LMS_EnableCalibCache(), LMS_GetDeviceInfo(), LMS_WriteParam(), lmsControl, lime::LOG_LEVEL_INFO, MAC, AppFrame_view::mnuCacheValues, Si5351C_wxgui::ModifyClocksGUI(), obj_ptr, OnLogDataTransfer(), lms_dev_info_t::protocolVersion, lime::LMS7002M::Rx, pnlBoardControls::SetupControls(), si5351gui, AppFrame_view::statusBar, and UpdateConnections().
Referenced by LMS7SuiteAppFrame(), and OnShowConnectionSettings().
void LMS7SuiteAppFrame::OnDataBoardConnect (wxCommandEvent & event) protected
Definition at line 298 of file lms7suiteAppFrame.cpp.
References lime::LOG_LEVEL_INFO.
Referenced by OnShowConnectionSettings().
void LMS7SuiteAppFrame::OnDeviceInfoClose (wxCloseEvent & event) protected
Definition at line 512 of file lms7suiteAppFrame.cpp.
References deviceInfo.
Referenced by OnShowDeviceInfo().
void LMS7SuiteAppFrame::OnFFTviewerClose (wxCloseEvent & event) protected
Definition at line 329 of file lms7suiteAppFrame.cpp.
References fftviewer, and fftviewer_frFFTviewer::StopStreaming().
Referenced by OnShowFFTviewer(), and ~LMS7SuiteAppFrame().
void LMS7SuiteAppFrame::OnFPGAcontrolsClose (wxCloseEvent & event) protected
Definition at line 466 of file lms7suiteAppFrame.cpp.
References fpgaControls.
Referenced by OnShowFPGAcontrols().
void LMS7SuiteAppFrame::OnGlobalLogEvent (const lime::LogLevel level, const char * message) static protected
Definition at line 102 of file lms7suiteAppFrame.cpp.
Referenced by LMS7SuiteAppFrame().
void LMS7SuiteAppFrame::OnHPM7Close (wxCloseEvent & event) protected
Definition at line 443 of file lms7suiteAppFrame.cpp.
References hpm7.
Referenced by OnShowHPM7().
void LMS7SuiteAppFrame::OnLmsChanged (wxCommandEvent & event) protected
Definition at line 357 of file lms7suiteAppFrame.cpp.
Referenced by LMS7SuiteAppFrame().
void LMS7SuiteAppFrame::OnLogDataTransfer (bool Tx, const unsigned char * data, const unsigned int length) static protected
Definition at line 561 of file lms7suiteAppFrame.cpp.
References pnlMiniLog_view::chkLogData, i, lime::LOG_LEVEL_INFO, mMiniLog, and obj_ptr.
Referenced by OnControlBoardConnect().
void LMS7SuiteAppFrame::OnLogEvent (const char * text, unsigned int type) static protected
Definition at line 113 of file lms7suiteAppFrame.cpp.
References lime::LOG_LEVEL_INFO.
void LMS7SuiteAppFrame::OnLogMessage (wxCommandEvent & event) protected
Definition at line 436 of file lms7suiteAppFrame.cpp.
References pnlMiniLog::HandleMessage(), and mMiniLog.
Referenced by LMS7SuiteAppFrame().
void LMS7SuiteAppFrame::OnMyriad7Close (wxCloseEvent & event) protected
Definition at line 489 of file lms7suiteAppFrame.cpp.
References myriad7.
Referenced by OnShowMyriad7().
void LMS7SuiteAppFrame::OnProgramingClose (wxCloseEvent & event) protected
Definition at line 412 of file lms7suiteAppFrame.cpp.
References programmer.
Referenced by OnShowPrograming().
void LMS7SuiteAppFrame::OnQuit (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 201 of file lms7suiteAppFrame.cpp.
void LMS7SuiteAppFrame::OnShowADF4002 (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 368 of file lms7suiteAppFrame.cpp.
References adfGUI, ADF4002_wxgui::Initialize(), lmsControl, and OnADF4002Close().
void LMS7SuiteAppFrame::OnShowBoardControls (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 592 of file lms7suiteAppFrame.cpp.
References boardControlsGui, pnlBoardControls::Initialize(), lmsControl, OnBoardControlsClose(), and pnlBoardControls::UpdatePanel().
void LMS7SuiteAppFrame::OnShowConnectionSettings (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 206 of file lms7suiteAppFrame.cpp.
References fftviewer, lmsControl, OnControlBoardConnect(), OnDataBoardConnect(), dlgConnectionSettings::SetConnectionManagers(), and fftviewer_frFFTviewer::StopStreaming().
void LMS7SuiteAppFrame::OnShowDeviceInfo (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 518 of file lms7suiteAppFrame.cpp.
References deviceInfo, dlgDeviceInfo::Initialize(), lmsControl, and OnDeviceInfoClose().
void LMS7SuiteAppFrame::OnShowFFTviewer (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 339 of file lms7suiteAppFrame.cpp.
References fftviewer, fftviewer_frFFTviewer::Initialize(), lmsControl, and OnFFTviewerClose().
void LMS7SuiteAppFrame::OnShowFPGAcontrols (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 471 of file lms7suiteAppFrame.cpp.
References fpgaControls, FPGAcontrols_wxgui::Initialize(), lmsControl, and OnFPGAcontrolsClose().
void LMS7SuiteAppFrame::OnShowHPM7 (wxCommandEvent & event) protected
Definition at line 448 of file lms7suiteAppFrame.cpp.
References hpm7, HPM7_wxgui::Initialize(), lmsControl, and OnHPM7Close().
void LMS7SuiteAppFrame::OnShowMyriad7 (wxCommandEvent & event) protected
Definition at line 494 of file lms7suiteAppFrame.cpp.
References Myriad7_wxgui::Initialize(), lmsControl, myriad7, and OnMyriad7Close().
void LMS7SuiteAppFrame::OnShowPrograming (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 418 of file lms7suiteAppFrame.cpp.
References lmsControl, OnProgramingClose(), programmer, and LMS_Programing_wxgui::SetConnection().
void LMS7SuiteAppFrame::OnShowSi5351C (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 392 of file lms7suiteAppFrame.cpp.
References lms_dev_info_t::deviceName, info, Si5351C_wxgui::Initialize(), LMS_GetDeviceInfo(), lmsControl, Si5351C_wxgui::ModifyClocksGUI(), OnSi5351Close(), and si5351gui.
void LMS7SuiteAppFrame::OnShowSPI (wxCommandEvent & event) protected virtual
Reimplemented from AppFrame_view.
Definition at line 542 of file lms7suiteAppFrame.cpp.
References SPI_wxgui::Initialize(), lmsControl, OnSPIClose(), and spi.
void LMS7SuiteAppFrame::OnSi5351Close (wxCloseEvent & event) protected
Definition at line 386 of file lms7suiteAppFrame.cpp.
References si5351gui.
Referenced by OnShowSi5351C().
void LMS7SuiteAppFrame::OnSPIClose (wxCloseEvent & event) protected
Definition at line 536 of file lms7suiteAppFrame.cpp.
References spi.
Referenced by OnShowSPI().
void LMS7SuiteAppFrame::UpdateConnections (lms_device_t * port) protected
Definition at line 227 of file lms7suiteAppFrame.cpp.
References adfGUI, boardControlsGui, deviceInfo, fftviewer, fpgaControls, hpm7, Myriad7_wxgui::Initialize(), dlgDeviceInfo::Initialize(), Si5351C_wxgui::Initialize(), HPM7_wxgui::Initialize(), FPGAcontrols_wxgui::Initialize(), SPI_wxgui::Initialize(), ADF4002_wxgui::Initialize(), lms7002_mainPanel::Initialize(), fftviewer_frFFTviewer::Initialize(), pnlBoardControls::Initialize(), lmsControl, AppFrame_view::mContent, myriad7, programmer, LMS_Programing_wxgui::SetConnection(), si5351gui, and spi.
Referenced by LMS7SuiteAppFrame(), and OnControlBoardConnect().
Member Data Documentation
ADF4002_wxgui* LMS7SuiteAppFrame::adfGUI protected
Definition at line 81 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnADF4002Close(), OnShowADF4002(), and UpdateConnections().
pnlBoardControls* LMS7SuiteAppFrame::boardControlsGui protected
Definition at line 91 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnBoardControlsClose(), OnControlBoardConnect(), OnShowBoardControls(), and UpdateConnections().
const int LMS7SuiteAppFrame::cDeviceInfoCollumn = 1 static protected
Definition at line 73 of file lms7suiteAppFrame.h.
const int LMS7SuiteAppFrame::cDeviceVerRevMaskCollumn = 2 static protected
Definition at line 74 of file lms7suiteAppFrame.h.
const wxString LMS7SuiteAppFrame::cWindowTitle = _("LMS7Suite") static protected
Definition at line 72 of file lms7suiteAppFrame.h.
dlgDeviceInfo* LMS7SuiteAppFrame::deviceInfo protected
Definition at line 89 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnDeviceInfoClose(), OnShowDeviceInfo(), and UpdateConnections().
fftviewer_frFFTviewer* LMS7SuiteAppFrame::fftviewer protected
Definition at line 79 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnFFTviewerClose(), OnShowConnectionSettings(), OnShowFFTviewer(), and UpdateConnections().
FPGAcontrols_wxgui* LMS7SuiteAppFrame::fpgaControls protected
Definition at line 87 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnFPGAcontrolsClose(), OnShowFPGAcontrols(), and UpdateConnections().
HPM7_wxgui* LMS7SuiteAppFrame::hpm7 protected
Definition at line 86 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnHPM7Close(), OnShowHPM7(), and UpdateConnections().
lms_device_t* LMS7SuiteAppFrame::lmsControl protected
Definition at line 77 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnChangeCacheSettings(), OnControlBoardConnect(), OnShowADF4002(), OnShowBoardControls(), OnShowConnectionSettings(), OnShowDeviceInfo(), OnShowFFTviewer(), OnShowFPGAcontrols(), OnShowHPM7(), OnShowMyriad7(), OnShowPrograming(), OnShowSi5351C(), OnShowSPI(), UpdateConnections(), and ~LMS7SuiteAppFrame().
int LMS7SuiteAppFrame::m_lmsSelection = 0 static
Definition at line 66 of file lms7suiteAppFrame.h.
Referenced by lms7002_pnlCalibrations_view::OnbtnCalibrateRx(), lms7002_pnlTxTSP_view::onbtnGFIR1Coef(), lms7002_pnlRxTSP_view::onbtnGFIR1Coef(), lms7002_pnlRxTSP_view::onbtnGFIR2Coef(), lms7002_pnlTxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR3Coef(), lms7002_pnlTxTSP_view::onbtnGFIR3Coef(), lms7002_pnlTBB_view::OnbtnTuneFilter(), lms7002_pnlRBB_view::OnbtnTuneFilter(), lms7002_pnlTxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlRxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlTxTSP_view::PHOinputChanged(), lms7002_pnlRxTSP_view::PHOinputChanged(), lms7002_pnlTxTSP_view::UpdateNCOinputs(), and lms7002_pnlRxTSP_view::UpdateNCOinputs().
pnlMiniLog* LMS7SuiteAppFrame::mMiniLog protected
Definition at line 78 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnLogDataTransfer(), and OnLogMessage().
Myriad7_wxgui* LMS7SuiteAppFrame::myriad7 protected
Definition at line 88 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnMyriad7Close(), OnShowMyriad7(), and UpdateConnections().
LMS7SuiteAppFrame * LMS7SuiteAppFrame::obj_ptr =nullptr static protected
Definition at line 80 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnControlBoardConnect(), and OnLogDataTransfer().
LMS_Programing_wxgui* LMS7SuiteAppFrame::programmer protected
Definition at line 85 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnProgramingClose(), OnShowPrograming(), and UpdateConnections().
Si5351C_wxgui* LMS7SuiteAppFrame::si5351gui protected
Definition at line 83 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnControlBoardConnect(), OnShowSi5351C(), OnSi5351Close(), and UpdateConnections().
SPI_wxgui* LMS7SuiteAppFrame::spi protected
Definition at line 90 of file lms7suiteAppFrame.h.
Referenced by LMS7SuiteAppFrame(), OnShowSPI(), OnSPIClose(), and UpdateConnections().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7suiteAppFrame.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7suiteAppFrame.cpp