LimeSuite-UML: pnlQSpark Class Reference
pnlQSpark Class Reference
#include <pnlQSpark.h>
Classes
struct Register
Public Member Functions
pnlQSpark (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int style=0, wxString name="")
void Initialize (lms_device_t *pControl)
virtual ~pnlQSpark ()
void OnbtnUpdateAll (wxCommandEvent &event)
void OnNcoFrequencyChanged (wxCommandEvent &event)
Public Attributes
wxComboBox * cmbVCXOcontrolVoltage
wxCheckBox * chkLB_1A
wxCheckBox * chkLB_1B
wxCheckBox * chkLB_2A
wxCheckBox * chkLB_2B
wxCheckBox * chkSH_1A
wxCheckBox * chkSH_1B
wxCheckBox * chkSH_2A
wxCheckBox * chkSH_2B
wxCheckBox * chkAT_1A
wxCheckBox * chkAT_1B
wxCheckBox * chkAT_2A
wxCheckBox * chkAT_2B
wxPanel * mPanelStreamPLL
wxTextCtrl * txtPllFreqRxMHz
wxStaticText * lblRealFreqTx
wxStaticText * lblRealFreqRx
wxTextCtrl * txtPllFreqTxMHz
wxTextCtrl * txtPhaseOffsetDeg
wxButton * btnConfigurePLL
wxCheckBox * chkEN_TXTSP
wxCheckBox * chkEN_RXTSP
wxCheckBox * chkRX_DCCORR_BYP
wxCheckBox * chkRX_PHCORR_BYP
wxCheckBox * chkRX_GCORR_BYP
wxCheckBox * chkTX_DCCORR_BYP
wxCheckBox * chkTX_PHCORR_BYP
wxCheckBox * chkTX_GCORR_BYP
wxSpinCtrl * spinTX_DCCORRI
wxSpinCtrl * spinTX_DCCORRQ
wxSpinCtrl * spinTX_GCORRQ
wxSpinCtrl * spinTX_GCORRI
wxSpinCtrl * spinTX_PHCORR
wxSpinCtrl * spinRX_GCORRQ
wxSpinCtrl * spinRX_GCORRI
wxSpinCtrl * spinRX_PHCORR
wxChoice * cmbInsel
wxRadioButton * rbChannelA
wxRadioButton * rbChannelB
wxTextCtrl * txtNcoFreq
Static Public Attributes
static const long ID_BUTTON_UPDATEALL
static const long ID_VCXOCV
Protected Member Functions
void OnConfigurePLL (wxCommandEvent &event)
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
void OnSwitchToChannelA (wxCommandEvent &event)
void OnSwitchToChannelB (wxCommandEvent &event)
void RegisterParameterChangeHandler (wxCommandEvent &event)
Protected Attributes
std::map< wxObject *, Register > controlsPtr2Registers
lms_device_t * lmsControl
Detailed Description
Definition at line 20 of file pnlQSpark.h.
Constructor & Destructor Documentation
pnlQSpark::pnlQSpark (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int style = 0, wxString name = "")
Definition at line 37 of file pnlQSpark.cpp.
References _T, btnConfigurePLL, chkAT_1A, chkAT_1B, chkAT_2A, chkAT_2B, chkEN_RXTSP, chkEN_TXTSP, chkLB_1A, chkLB_1B, chkLB_2A, chkLB_2B, chkRX_DCCORR_BYP, chkRX_GCORR_BYP, chkRX_PHCORR_BYP, chkSH_1A, chkSH_1B, chkSH_2A, chkSH_2B, chkTX_DCCORR_BYP, chkTX_GCORR_BYP, chkTX_PHCORR_BYP, cmbInsel, controlsPtr2Registers, lblRealFreqRx, lblRealFreqTx, lmsControl, mPanelStreamPLL, OnConfigurePLL(), OnNcoFrequencyChanged(), OnReadAll(), OnSwitchToChannelA(), OnSwitchToChannelB(), OnWriteAll(), rbChannelA, rbChannelB, pnlQSpark::Register::Register(), RegisterParameterChangeHandler(), spinRX_GCORRI, spinRX_GCORRQ, spinRX_PHCORR, spinTX_DCCORRI, spinTX_DCCORRQ, spinTX_GCORRI, spinTX_GCORRQ, spinTX_PHCORR, txtNcoFreq, txtPllFreqRxMHz, and txtPllFreqTxMHz.
pnlQSpark::~pnlQSpark () virtual
Definition at line 374 of file pnlQSpark.cpp.
References btnConfigurePLL, mPanelStreamPLL, and OnConfigurePLL().
Member Function Documentation
void pnlQSpark::Initialize (lms_device_t * pControl)
Definition at line 334 of file pnlQSpark.cpp.
References LMS_CH_RX, LMS_CH_TX, LMS_GetSampleRate(), LMS_WriteFPGAReg(), lmsControl, rbChannelB, txtPllFreqRxMHz, and txtPllFreqTxMHz.
Referenced by pnlBoardControls::SetupControls().
void pnlQSpark::OnbtnUpdateAll (wxCommandEvent & event)
Definition at line 379 of file pnlQSpark.cpp.
References pnlQSpark::Register::address, chkLB_1A, chkLB_1B, chkLB_2A, chkLB_2B, controlsPtr2Registers, fcw, i, LMS_ReadFPGAReg(), LMS_WriteFPGAReg(), lmsControl, pnlQSpark::Register::lsb, pnlQSpark::Register::msb, rbChannelB, txtNcoFreq, and txtPllFreqTxMHz.
Referenced by OnReadAll(), OnSwitchToChannelA(), and OnSwitchToChannelB().
void pnlQSpark::OnConfigurePLL (wxCommandEvent & event) protected
Definition at line 431 of file pnlQSpark.cpp.
References lmsControl, OnNcoFrequencyChanged(), txtPllFreqRxMHz, and txtPllFreqTxMHz.
Referenced by OnWriteAll(), pnlQSpark(), and ~pnlQSpark().
void pnlQSpark::OnNcoFrequencyChanged (wxCommandEvent & event)
Definition at line 451 of file pnlQSpark.cpp.
References fcw, i, LMS_WriteFPGAReg(), lmsControl, rbChannelB, txtNcoFreq, and txtPllFreqTxMHz.
Referenced by OnConfigurePLL(), OnWriteAll(), and pnlQSpark().
void pnlQSpark::OnReadAll (wxCommandEvent & event) protected
Definition at line 471 of file pnlQSpark.cpp.
References OnbtnUpdateAll().
Referenced by pnlQSpark().
void pnlQSpark::OnSwitchToChannelA (wxCommandEvent & event) protected
Definition at line 482 of file pnlQSpark.cpp.
References LMS_WriteFPGAReg(), lmsControl, and OnbtnUpdateAll().
Referenced by pnlQSpark().
void pnlQSpark::OnSwitchToChannelB (wxCommandEvent & event) protected
Definition at line 493 of file pnlQSpark.cpp.
References LMS_WriteFPGAReg(), lmsControl, and OnbtnUpdateAll().
Referenced by pnlQSpark().
void pnlQSpark::OnWriteAll (wxCommandEvent & event) protected
Definition at line 476 of file pnlQSpark.cpp.
References OnConfigurePLL(), and OnNcoFrequencyChanged().
Referenced by pnlQSpark().
void pnlQSpark::RegisterParameterChangeHandler (wxCommandEvent & event) protected
Definition at line 346 of file pnlQSpark.cpp.
References pnlQSpark::Register::address, chkLB_1A, chkLB_1B, chkLB_2A, chkLB_2B, controlsPtr2Registers, LMS_ReadFPGAReg(), LMS_WriteFPGAReg(), lmsControl, pnlQSpark::Register::lsb, pnlQSpark::Register::msb, and rbChannelB.
Referenced by pnlQSpark().
Member Data Documentation
wxButton* pnlQSpark::btnConfigurePLL
Definition at line 48 of file pnlQSpark.h.
Referenced by pnlQSpark(), and ~pnlQSpark().
wxCheckBox* pnlQSpark::chkAT_1A
Definition at line 37 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkAT_1B
Definition at line 38 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkAT_2A
Definition at line 39 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkAT_2B
Definition at line 40 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkEN_RXTSP
Definition at line 51 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkEN_TXTSP
Definition at line 50 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkLB_1A
Definition at line 29 of file pnlQSpark.h.
Referenced by OnbtnUpdateAll(), pnlQSpark(), and RegisterParameterChangeHandler().
wxCheckBox* pnlQSpark::chkLB_1B
Definition at line 30 of file pnlQSpark.h.
Referenced by OnbtnUpdateAll(), pnlQSpark(), and RegisterParameterChangeHandler().
wxCheckBox* pnlQSpark::chkLB_2A
Definition at line 31 of file pnlQSpark.h.
Referenced by OnbtnUpdateAll(), pnlQSpark(), and RegisterParameterChangeHandler().
wxCheckBox* pnlQSpark::chkLB_2B
Definition at line 32 of file pnlQSpark.h.
Referenced by OnbtnUpdateAll(), pnlQSpark(), and RegisterParameterChangeHandler().
wxCheckBox* pnlQSpark::chkRX_DCCORR_BYP
Definition at line 52 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkRX_GCORR_BYP
Definition at line 54 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkRX_PHCORR_BYP
Definition at line 53 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkSH_1A
Definition at line 33 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkSH_1B
Definition at line 34 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkSH_2A
Definition at line 35 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkSH_2B
Definition at line 36 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkTX_DCCORR_BYP
Definition at line 55 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkTX_GCORR_BYP
Definition at line 57 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxCheckBox* pnlQSpark::chkTX_PHCORR_BYP
Definition at line 56 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxChoice* pnlQSpark::cmbInsel
Definition at line 66 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxComboBox* pnlQSpark::cmbVCXOcontrolVoltage
Definition at line 27 of file pnlQSpark.h.
std::map<wxObject*, Register> pnlQSpark::controlsPtr2Registers protected
Definition at line 93 of file pnlQSpark.h.
Referenced by OnbtnUpdateAll(), pnlQSpark(), and RegisterParameterChangeHandler().
const long pnlQSpark::ID_BUTTON_UPDATEALL static
Definition at line 72 of file pnlQSpark.h.
const long pnlQSpark::ID_VCXOCV static
Definition at line 73 of file pnlQSpark.h.
wxStaticText* pnlQSpark::lblRealFreqRx
Definition at line 45 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxStaticText* pnlQSpark::lblRealFreqTx
Definition at line 44 of file pnlQSpark.h.
Referenced by pnlQSpark().
lms_device_t* pnlQSpark::lmsControl protected
Definition at line 97 of file pnlQSpark.h.
Referenced by Initialize(), OnbtnUpdateAll(), OnConfigurePLL(), OnNcoFrequencyChanged(), OnSwitchToChannelA(), OnSwitchToChannelB(), pnlQSpark(), and RegisterParameterChangeHandler().
wxPanel* pnlQSpark::mPanelStreamPLL
Definition at line 42 of file pnlQSpark.h.
Referenced by pnlQSpark(), and ~pnlQSpark().
wxRadioButton* pnlQSpark::rbChannelA
Definition at line 67 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxRadioButton* pnlQSpark::rbChannelB
Definition at line 68 of file pnlQSpark.h.
Referenced by Initialize(), OnbtnUpdateAll(), OnNcoFrequencyChanged(), pnlQSpark(), and RegisterParameterChangeHandler().
wxSpinCtrl* pnlQSpark::spinRX_GCORRI
Definition at line 64 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxSpinCtrl* pnlQSpark::spinRX_GCORRQ
Definition at line 63 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxSpinCtrl* pnlQSpark::spinRX_PHCORR
Definition at line 65 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxSpinCtrl* pnlQSpark::spinTX_DCCORRI
Definition at line 58 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxSpinCtrl* pnlQSpark::spinTX_DCCORRQ
Definition at line 59 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxSpinCtrl* pnlQSpark::spinTX_GCORRI
Definition at line 61 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxSpinCtrl* pnlQSpark::spinTX_GCORRQ
Definition at line 60 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxSpinCtrl* pnlQSpark::spinTX_PHCORR
Definition at line 62 of file pnlQSpark.h.
Referenced by pnlQSpark().
wxTextCtrl* pnlQSpark::txtNcoFreq
Definition at line 70 of file pnlQSpark.h.
Referenced by OnbtnUpdateAll(), OnNcoFrequencyChanged(), and pnlQSpark().
wxTextCtrl* pnlQSpark::txtPhaseOffsetDeg
Definition at line 47 of file pnlQSpark.h.
wxTextCtrl* pnlQSpark::txtPllFreqRxMHz
Definition at line 43 of file pnlQSpark.h.
Referenced by Initialize(), OnConfigurePLL(), and pnlQSpark().
wxTextCtrl* pnlQSpark::txtPllFreqTxMHz
Definition at line 46 of file pnlQSpark.h.
Referenced by Initialize(), OnbtnUpdateAll(), OnConfigurePLL(), OnNcoFrequencyChanged(), and pnlQSpark().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlQSpark.h
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlQSpark.cpp