LimeSuite-UML: lms7002_dlgGFIR_Coefficients Class Reference
lms7002_dlgGFIR_Coefficients Class Reference
Implementing dlgGFIR_Coefficients.
#include <lms7002_dlgGFIR_Coefficients.h>
Public Member Functions
lms7002_dlgGFIR_Coefficients (wxWindow *parent)
Constructor.
void SetCoefficients (const std::vector< double > &coefficients)
std::vector< double > GetCoefficients ()
Public Member Functions inherited from dlgGFIR_Coefficients
dlgGFIR_Coefficients (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("Coefficients"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE)
~dlgGFIR_Coefficients ()
Protected Member Functions
void OnLoadFromFile (wxCommandEvent &event)
void OnSaveToFile (wxCommandEvent &event)
void OnClearTable (wxCommandEvent &event)
void OnspinCoefCountChange (wxSpinEvent &event)
void OnBtnOkClick (wxCommandEvent &event)
void OnBtnCancelClick (wxCommandEvent &event)
Additional Inherited Members
Protected Attributes inherited from dlgGFIR_Coefficients
wxButton * btnLoadFromFile
wxButton * btnSaveToFile
wxButton * btnClearTable
wxStaticText * ID_STATICTEXT3
wxSpinCtrl * spinCoefCount
wxGrid * gridCoef
wxButton * btnOk
wxButton * btnCancel
Detailed Description
Implementing dlgGFIR_Coefficients.
Definition at line 15 of file lms7002_dlgGFIR_Coefficients.h.
Constructor & Destructor Documentation
lms7002_dlgGFIR_Coefficients::lms7002_dlgGFIR_Coefficients (wxWindow * parent)
Constructor.
Definition at line 6 of file lms7002_dlgGFIR_Coefficients.cpp.
Member Function Documentation
std::vector< double > lms7002_dlgGFIR_Coefficients::GetCoefficients ()
Definition at line 96 of file lms7002_dlgGFIR_Coefficients.cpp.
References dlgGFIR_Coefficients::gridCoef, i, and dlgGFIR_Coefficients::spinCoefCount.
Referenced by lms7002_pnlRxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR3Coef(), and lms7002_pnlTxTSP_view::onbtnGFIR3Coef().
void lms7002_dlgGFIR_Coefficients::OnBtnCancelClick (wxCommandEvent & event) protected virtual
Reimplemented from dlgGFIR_Coefficients.
Definition at line 114 of file lms7002_dlgGFIR_Coefficients.cpp.
void lms7002_dlgGFIR_Coefficients::OnBtnOkClick (wxCommandEvent & event) protected virtual
Reimplemented from dlgGFIR_Coefficients.
Definition at line 109 of file lms7002_dlgGFIR_Coefficients.cpp.
void lms7002_dlgGFIR_Coefficients::OnClearTable (wxCommandEvent & event) protected virtual
Reimplemented from dlgGFIR_Coefficients.
Definition at line 67 of file lms7002_dlgGFIR_Coefficients.cpp.
References dlgGFIR_Coefficients::gridCoef, i, and dlgGFIR_Coefficients::spinCoefCount.
void lms7002_dlgGFIR_Coefficients::OnLoadFromFile (wxCommandEvent & event) protected virtual
Reimplemented from dlgGFIR_Coefficients.
Definition at line 13 of file lms7002_dlgGFIR_Coefficients.cpp.
References Parser::getcoeffs(), dlgGFIR_Coefficients::gridCoef, i, and dlgGFIR_Coefficients::spinCoefCount.
void lms7002_dlgGFIR_Coefficients::OnSaveToFile (wxCommandEvent & event) protected virtual
Reimplemented from dlgGFIR_Coefficients.
Definition at line 50 of file lms7002_dlgGFIR_Coefficients.cpp.
References dlgGFIR_Coefficients::gridCoef, i, Parser::saveToFile(), and dlgGFIR_Coefficients::spinCoefCount.
void lms7002_dlgGFIR_Coefficients::OnspinCoefCountChange (wxSpinEvent & event) protected virtual
Reimplemented from dlgGFIR_Coefficients.
Definition at line 78 of file lms7002_dlgGFIR_Coefficients.cpp.
References dlgGFIR_Coefficients::gridCoef, and dlgGFIR_Coefficients::spinCoefCount.
void lms7002_dlgGFIR_Coefficients::SetCoefficients (const std::vector< double > & coefficients)
Definition at line 86 of file lms7002_dlgGFIR_Coefficients.cpp.
References dlgGFIR_Coefficients::gridCoef, i, and dlgGFIR_Coefficients::spinCoefCount.
Referenced by lms7002_pnlRxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR3Coef(), and lms7002_pnlTxTSP_view::onbtnGFIR3Coef().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_dlgGFIR_Coefficients.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_dlgGFIR_Coefficients.cpp