LimeSuite-UML: lime::LMS7_qLimeSDR Class Reference
lime::LMS7_qLimeSDR Class Reference
#include <qLimeSDR.h>
Public Member Functions
LMS7_qLimeSDR (lime::IConnection *conn, LMS7_Device *obj=nullptr)
unsigned GetNumChannels (const bool tx=false) const override
int EnableChannel (bool dir_tx, unsigned chan, bool enabled) override
double GetRate (bool tx, unsigned chan, double *rf_rate_Hz=NULL) const override
int SetRate (unsigned ch, double rxRate, double txRate, unsigned oversample=0) override
Public Member Functions inherited from lime::LMS7_Device
virtual ~LMS7_Device ()
LMS7_Device (LMS7_Device *obj=nullptr)
lime::IConnection * GetConnection (unsigned chan=0)
lime::FPGA * GetFPGA ()
virtual int Init ()
int Reset ()
virtual int SetRate (double f_MHz, int oversample)
virtual int SetRate (bool tx, double f_MHz, unsigned oversample=0)
int SetFPGAInterfaceFreq (int interp=-1, int dec=-1, double txPhase=999, double rxPhase=999)
virtual Range GetRateRange (bool dir=false, unsigned chan=0) const
virtual std::vector< std::string > GetPathNames (bool dir_tx, unsigned chan=0) const
virtual int SetPath (bool tx, unsigned chan, unsigned path)
int GetPath (bool tx, unsigned chan) const
virtual int SetFrequency (bool tx, unsigned chan, double f_Hz)
double GetFrequency (bool tx, unsigned chan) const
virtual Range GetFrequencyRange (bool tx) const
virtual Range GetRxPathBand (unsigned path, unsigned chan) const
virtual Range GetTxPathBand (unsigned path, unsigned chan) const
int SetLPF (bool tx, unsigned chan, bool en, double bandwidth=-1)
double GetLPFBW (bool tx, unsigned chan) const
Range GetLPFRange (bool tx, unsigned chan) const
int SetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, const double *coef, unsigned count)
int GetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, double *coef) const
int SetGFIR (bool tx, unsigned chan, lms_gfir_t filt, bool enabled)
int SetGain (bool dir_tx, unsigned chan, double value, const std::string &name="")
double GetGain (bool dir_tx, unsigned chan, const std::string &name="") const
Range GetGainRange (bool dir_tx, unsigned chan, const std::string &name="") const
int SetTestSignal (bool dir_tx, unsigned chan, lms_testsig_t sig, int16_t dc_i=0, int16_t dc_q=0)
int GetTestSignal (bool dir_tx, unsigned chan) const
int SetNCOFreq (bool tx, unsigned ch, int ind, double freq)
double GetNCOFreq (bool tx, unsigned ch, int ind) const
int SetNCOPhase (bool tx, unsigned ch, int ind, double phase)
double GetNCOPhase (bool tx, unsigned ch, int ind) const
int Calibrate (bool dir_tx, unsigned chan, double bw, unsigned flags)
virtual std::vector< std::string > GetProgramModes () const
virtual int Program (const std::string &mode, const char *data, size_t len, lime::IConnection::ProgrammingCallback callback) const
double GetClockFreq (unsigned clk_id, int channel=-1) const
int SetClockFreq (unsigned clk_id, double freq, int channel=-1)
lms_dev_info_t * GetInfo ()
int Synchronize (bool toChip) const
int SetLogCallback (void(*func)(const char *cstr, const unsigned int type))
int EnableCalibCache (bool enable)
double GetChipTemperature (int ind=-1) const
int LoadConfig (const char *filename, int ind=-1)
int SaveConfig (const char *filename, int ind=-1) const
int ReadLMSReg (uint16_t address, int ind=-1) const
int WriteLMSReg (uint16_t address, uint16_t val, int ind=-1) const
uint16_t ReadParam (const struct LMS7Parameter &param, int channel=-1, bool forceReadFromChip=false) const
int ReadParam (const std::string &param, int channel=-1, bool forceReadFromChip=false) const
int WriteParam (const struct LMS7Parameter &param, uint16_t val, int channel=-1)
int WriteParam (const std::string &param, uint16_t val, int channel=-1)
int SetActiveChip (unsigned ind)
lime::LMS7002M * GetLMS (int index=-1) const
int UploadWFM (const void **samples, uint8_t chCount, int sample_count, lime::StreamConfig::StreamDataFormat fmt) const
int ConfigureGFIR (bool tx, unsigned ch, bool enabled, double bandwidth)
lime::StreamChannel * SetupStream (const lime::StreamConfig &config)
int DestroyStream (lime::StreamChannel *streamID)
uint64_t GetHardwareTimestamp (void) const
void SetHardwareTimestamp (const uint64_t now)
uint64_t GetChirpTimePeriod (void) const
uint64_t GetChirpTimeStamp (void) const
int MCU_AGCStart (uint32_t wantedRSSI)
int MCU_AGCStop ()
Private Attributes
double dacRate
double adcRate
Additional Inherited Members
Static Public Member Functions inherited from lime::LMS7_Device
static LMS7_Device * CreateDevice (const lime::ConnectionHandle &handle, LMS7_Device *obj=nullptr)
static std::vector< lime::ConnectionHandle > GetDeviceList ()
Protected Member Functions inherited from lime::LMS7_Device
lime::LMS7002M * SelectChannel (unsigned chan) const
int ConfigureTXLPF (bool enabled, int ch, double bandwidth)
Protected Attributes inherited from lime::LMS7_Device
lms_dev_info_t devInfo
std::vector< ChannelInfo > tx_channels
std::vector< ChannelInfo > rx_channels
lime::IConnection * connection
std::vector< lime::LMS7002M * > lms_list
unsigned lms_chip_id
std::vector< lime::Streamer * > mStreamers
lime::FPGA * fpga
Detailed Description
Definition at line 16 of file qLimeSDR.h.
Constructor & Destructor Documentation
lime::LMS7_qLimeSDR::LMS7_qLimeSDR (lime::IConnection * conn, LMS7_Device * obj = nullptr)
Definition at line 13 of file qLimeSDR.cpp.
References lime::LMS7_Device::connection, lime::LMS7_Device::fpga, GetNumChannels(), i, lime::LMS7_Device::lms_list, lime::LMS7_Device::mStreamers, lime::LMS7_Device::rx_channels, lime::FPGA::SetConnection(), and lime::LMS7_Device::tx_channels.
Member Function Documentation
int lime::LMS7_qLimeSDR::EnableChannel (bool dir_tx, unsigned chan, bool enabled) override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 38 of file qLimeSDR.cpp.
References lime::LMS7_Device::EnableChannel().
unsigned lime::LMS7_qLimeSDR::GetNumChannels (const bool tx = false) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 33 of file qLimeSDR.cpp.
Referenced by LMS7_qLimeSDR().
double lime::LMS7_qLimeSDR::GetRate (bool tx, unsigned chan, double * rf_rate_Hz = NULL) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 56 of file qLimeSDR.cpp.
References adcRate, dacRate, and lime::LMS7_Device::GetRate().
int lime::LMS7_qLimeSDR::SetRate (unsigned ch, double rxRate, double txRate, unsigned oversample = 0) override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 45 of file qLimeSDR.cpp.
References adcRate, dacRate, lime::LMS7_Device::fpga, lime::FPGA::SetInterfaceFreq(), and lime::LMS7_Device::SetRate().
Member Data Documentation
double lime::LMS7_qLimeSDR::adcRate private
Definition at line 26 of file qLimeSDR.h.
Referenced by GetRate(), and SetRate().
double lime::LMS7_qLimeSDR::dacRate private
Definition at line 25 of file qLimeSDR.h.
Referenced by GetRate(), and SetRate().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/API/qLimeSDR.h
/home/erik/prefix/default/src/limesuite-dev/src/API/qLimeSDR.cpp