LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/lms.h File Reference
lms.h File Reference
#include <stdlib.h>
#include <math.h>
Macros
#define POSITIVE (1)
#define NEGATIVE (-1)
#define LMS_POINTS 4000
#define NONE One /* Constant */
#define ONE One /* as well */
#define INVSINC InvSinc /* Iverse sinc */
#define INVSINCS InvSincS /* Shifted Inverse Sinc */
#define RAISEDCOSINE 1
#define ROOTRAISEDCOSINE 2
Functions
double InvSinc ()
double InvSincS ()
double One ()
int lms (double *hr, double *hi, double *hcsd, int n, double *w, double *des, double *weight, int p, int cprec, int csdprec, int symmetry, int **bincode, int **csdcode, int **csdcoder)
Macro Definition Documentation
#define INVSINC InvSinc /* Iverse sinc */
Definition at line 31 of file lms.h.
#define INVSINCS InvSincS /* Shifted Inverse Sinc */
Definition at line 32 of file lms.h.
#define LMS_POINTS 4000
Definition at line 21 of file lms.h.
Referenced by gfir_lms().
#define NEGATIVE (-1)
Definition at line 17 of file lms.h.
Referenced by lms().
#define NONE One /* Constant */
Definition at line 29 of file lms.h.
Referenced by GenerateFilter().
#define ONE One /* as well */
Definition at line 30 of file lms.h.
#define POSITIVE (1)
Definition at line 16 of file lms.h.
Referenced by gfir_lms(), and lms().
#define RAISEDCOSINE 1
Definition at line 35 of file lms.h.
#define ROOTRAISEDCOSINE 2
Definition at line 36 of file lms.h.
Function Documentation
double InvSinc ()
double InvSincS ()
int lms (double * hr, double * hi, double * hcsd, int n, double * w, double * des, double * weight, int p, int cprec, int csdprec, int symmetry, int ** bincode, int ** csdcode, int ** csdcoder)
Definition at line 81 of file lms.c.
References dfilter::a, Case1F(), Case2F(), Case3F(), Case4F(), EVEN, free_ivector(), free_matrix(), free_vector(), i, index, ivector(), lubksb(), ludcmp(), matrix(), dfilter::n, NEGATIVE, ODD, POSITIVE, round2csd(), round2int(), and vector().
Referenced by lime::LMS7_Device::Calibrate(), ConfigureCGEN(), lime::LMS7_Device::ConfigureGFIR(), lime::LMS7_Device::ConfigureTXLPF(), lime::LMS7_Device::EnableChannel(), lime::LMS7_Device::GetFrequency(), lime::LMS7_Device::GetGain(), lime::LMS7_Device::GetGFIRCoef(), lime::LMS7_Device::GetNCOFreq(), lime::LMS7_Device::GetNCOPhase(), lime::LMS7_Device::GetPath(), lime::LMS7_Device::GetRate(), lime::LMS7_Device::GetTestSignal(), gfir_lms(), lime::LMS7_LimeSDR_mini::Init(), lime::LMS7_Device::Init(), dlgDeviceInfo::Initialize(), HPM7_wxgui::Initialize(), lms7002_dlgVCOfrequencies::lms7002_dlgVCOfrequencies(), lime::LMS7_Device::LMS7_Device(), LMS_Calibrate(), LMS_Close(), LMS_DestroyStream(), LMS_EnableCalibCache(), LMS_EnableChannel(), LMS_GetAntenna(), LMS_GetAntennaBW(), LMS_GetAntennaList(), LMS_GetChipTemperature(), LMS_GetClockFreq(), LMS_GetDeviceInfo(), LMS_GetGaindB(), LMS_GetGFIRCoeff(), LMS_GetLOFrequency(), LMS_GetLOFrequencyRange(), LMS_GetLPFBW(), LMS_GetLPFBWRange(), LMS_GetNCOFrequency(), LMS_GetNCOIndex(), LMS_GetNCOPhase(), LMS_GetNormalizedGain(), LMS_GetNumChannels(), LMS_GetProgramModes(), LMS_GetSampleRate(), LMS_GetSampleRateRange(), LMS_GetTestSignal(), LMS_GPIODirRead(), LMS_GPIODirWrite(), LMS_GPIORead(), LMS_GPIOWrite(), LMS_Init(), LMS_IsOpen(), LMS_LoadConfig(), LMS_Program(), LMS_ReadCustomBoardParam(), LMS_ReadFPGAReg(), LMS_ReadLMSReg(), LMS_ReadParam(), LMS_Reset(), LMS_SaveConfig(), LMS_SetAntenna(), LMS_SetClockFreq(), LMS_SetGaindB(), LMS_SetGFIR(), LMS_SetGFIRCoeff(), LMS_SetGFIRLPF(), LMS_SetLOFrequency(), LMS_SetLPF(), LMS_SetLPFBW(), LMS_SetNCOFrequency(), LMS_SetNCOIndex(), LMS_SetNCOPhase(), LMS_SetNormalizedGain(), LMS_SetSampleRate(), LMS_SetSampleRateDir(), LMS_SetTestSignal(), LMS_SetupStream(), LMS_Synchronize(), LMS_TransferLMS64C(), LMS_UploadWFM(), LMS_WriteCustomBoardParam(), LMS_WriteFPGAReg(), LMS_WriteLMSReg(), LMS_WriteParam(), lime::LMS7_Device::LoadConfig(), lms7002_pnlGains_view::OnAGCStateChange(), lms7002_pnlSX_view::OnbtnCalculateClick(), lms7002_pnlCLKGEN_view::onbtnCalculateClick(), lms7002_dlgVCOfrequencies::OnBtnOkClick(), lms7002_pnlCLKGEN_view::onbtnTuneClick(), lms7002_pnlTBB_view::OnbtnTuneTxGain(), lms7002_pnlR3_view::OnCalibrateAnalogRSSI(), lms7002_mainPanel::OnCalibrateInternalADC(), lms7002_pnlBIAS_view::OnCalibrateRP_BIAS(), LMS7SuiteAppFrame::OnControlBoardConnect(), lime::LMS7_Device::Program(), lime::LMS7_Device::Reset(), lime::LMS7_Device::SelectChannel(), set(), lime::LMS7_Device::SetClockFreq(), dlgConnectionSettings::SetConnectionManagers(), lime::LMS7_Device::SetFPGAInterfaceFreq(), lime::LMS7_LimeSDR_mini::SetFrequency(), lime::LMS7_Device::SetFrequency(), lime::LMS7_Device::SetGain(), lime::LMS7_Device::SetGFIR(), lime::LMS7_Device::SetGFIRCoef(), lime::LMS7_Device::SetLPF(), lime::LMS7_Device::SetNCOFreq(), lime::LMS7_Device::SetNCOPhase(), lime::LMS7_LimeSDR_mini::SetPath(), lime::LMS7_Device::SetPath(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_Device::SetRate(), lime::LMS7_Device::SetTestSignal(), lime::LMS7_Device::Synchronize(), LMS7002_WXGUI::UpdateControlsByMap(), and lms7002_pnlRxTSP_view::UpdateGUI().
double One ()