LimeSuite-UML: lime::FPGA_Mini Class Reference
lime::FPGA_Mini Class Reference
#include <FPGA_Mini.h>
Public Member Functions
FPGA_Mini ()
virtual ~FPGA_Mini ()
int SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, double txPhase, double rxPhase, int ch=0) override
Configures FPGA PLLs to LimeLight interface frequency.
int SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, int ch=0) override
Configures FPGA PLLs to LimeLight interface frequency.
int UploadWFM (const void *const *samples, uint8_t chCount, size_t sample_count, StreamConfig::StreamDataFormat format, int epIndex) override
Public Member Functions inherited from lime::FPGA
FPGA ()
virtual ~FPGA ()
void SetConnection (IConnection *conn)
IConnection * GetConnection () const
int StartStreaming ()
int StopStreaming ()
int ResetTimestamp ()
double DetectRefClk (double fx3Clk=100e6)
Private Member Functions
int ReadRawStreamData (char *buffer, unsigned length, int epIndex, int timeout_ms) override
Additional Inherited Members
Static Public Member Functions inherited from lime::FPGA
static int FPGAPacketPayload2Samples (const uint8_t *buffer, int bufLen, bool mimo, bool compressed, complex16_t **samples)
Parses FPGA packet payload into samples.
static int Samples2FPGAPacketPayload (const complex16_t *const *samples, int samplesCount, bool mimo, bool compressed, uint8_t *buffer)
Protected Member Functions inherited from lime::FPGA
int SetPllFrequency (uint8_t pllIndex, double inputFreq, FPGA_PLL_clock *outputs, uint8_t clockCount)
Configures board FPGA clocks.
int SetDirectClocking (int clockIndex)
Protected Attributes inherited from lime::FPGA
IConnection * connection
Detailed Description
Definition at line 15 of file FPGA_Mini.h.
Constructor & Destructor Documentation
lime::FPGA_Mini::FPGA_Mini ()
Definition at line 13 of file FPGA_Mini.cpp.
virtual lime::FPGA_Mini::~FPGA_Mini () inline virtual
Definition at line 19 of file FPGA_Mini.h.
References buffer, chCount, format, ReadRawStreamData(), sample_count, samples, SetInterfaceFreq(), timeout_ms, and UploadWFM().
Member Function Documentation
int lime::FPGA_Mini::ReadRawStreamData (char * buffer, unsigned length, int epIndex, int timeout_ms) override private virtual
Reimplemented from lime::FPGA.
Definition at line 161 of file FPGA_Mini.cpp.
References lime::IConnection::AbortReading(), lime::IConnection::BeginDataReading(), lime::FPGA::connection, lime::IConnection::FinishDataReading(), lime::IConnection::ResetStreamBuffers(), lime::FPGA::StartStreaming(), lime::FPGA::StopStreaming(), lime::IConnection::WaitForReading(), and lime::IConnection::WriteRegister().
Referenced by ~FPGA_Mini().
int lime::FPGA_Mini::SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, double txPhase, double rxPhase, int ch = 0) override virtual
Configures FPGA PLLs to LimeLight interface frequency.
Reimplemented from lime::FPGA.
Definition at line 16 of file FPGA_Mini.cpp.
References lime::FPGA::FPGA_PLL_clock::bypass, lime::FPGA::FPGA_PLL_clock::findPhase, lime::FPGA::FPGA_PLL_clock::index, lime::FPGA::FPGA_PLL_clock::outFrequency, lime::FPGA::FPGA_PLL_clock::phaseShift_deg, lime::FPGA::SetDirectClocking(), lime::FPGA::SetPllFrequency(), and status.
Referenced by SetInterfaceFreq(), and ~FPGA_Mini().
int lime::FPGA_Mini::SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, int ch = 0) override virtual
Configures FPGA PLLs to LimeLight interface frequency.
Reimplemented from lime::FPGA.
Definition at line 57 of file FPGA_Mini.cpp.
References lime::FPGA::connection, lime::FPGA::FPGA_PLL_clock::findPhase, i, lime::FPGA::FPGA_PLL_clock::index, lime::FPGA::FPGA_PLL_clock::outFrequency, lime::FPGA::FPGA_PLL_clock::phaseShift_deg, lime::IConnection::ReadLMS7002MSPI(), SetInterfaceFreq(), lime::FPGA::SetPllFrequency(), status, lime::IConnection::WriteLMS7002MSPI(), and lime::IConnection::WriteRegister().
int lime::FPGA_Mini::UploadWFM (const void *const * samples, uint8_t chCount, size_t sample_count, StreamConfig::StreamDataFormat format, int epIndex) override virtual
Reimplemented from lime::FPGA.
Definition at line 155 of file FPGA_Mini.cpp.
References lime::ReportError().
Referenced by ~FPGA_Mini().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/FPGA_common/FPGA_Mini.h
/home/erik/prefix/default/src/limesuite-dev/src/FPGA_common/FPGA_Mini.cpp