LimeSuite-UML: lms7002_mainPanel Class Reference
lms7002_mainPanel Class Reference
Implementing mainPanel.
#include <lms7002_mainPanel.h>
Public Member Functions
lms7002_mainPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
Constructor.
void UpdateVisiblePanel ()
~lms7002_mainPanel ()
void UpdateGUI ()
void Initialize (lms_device_t *pControl)
Public Member Functions inherited from mainPanel
mainPanel (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~mainPanel ()
Protected Member Functions
void OnNewProject (wxCommandEvent &event)
void OnOpenProject (wxCommandEvent &event)
void OnSaveProject (wxCommandEvent &event)
void OnUploadAll (wxCommandEvent &event)
void OnDownloadAll (wxCommandEvent &event)
void OnReset (wxCommandEvent &event)
void OnRegistersTest (wxCommandEvent &event)
void OnSwitchToChannelA (wxCommandEvent &event)
void OnSwitchToChannelB (wxCommandEvent &event)
void Onnotebook_modulesPageChanged (wxNotebookEvent &event)
void OnResetChip (wxCommandEvent &event)
void OnLoadDefault (wxCommandEvent &event)
void OnReadTemperature (wxCommandEvent &event)
void OnSyncABchecked (wxCommandEvent &event)
void OnEnableMIMOchecked (wxCommandEvent &event)
void OnCalibrateInternalADC (wxCommandEvent &event)
int GetLmsSelection ()
void OnLmsDeviceSelect (wxCommandEvent &event)
Protected Attributes
lms7002_pnlMCU_BD_view * mTabMCU
lms7002_pnlR3_view * mTabR3
lms_device_t * lmsControl
Protected Attributes inherited from mainPanel
wxButton * ID_BUTTON2
wxButton * ID_BUTTON3
wxComboBox * cmbLmsDevice
wxRadioButton * rbChannelA
wxRadioButton * rbChannelB
wxCheckBox * chkEnableMIMO
wxButton * btnDownloadAll
wxButton * btnUploadAll
wxButton * btnResetChip
wxButton * btnLoadDefault
wxStaticText * txtTemperature
wxButton * btnReadTemperature
wxNotebook * tabsNotebook
Additional Inherited Members
Public Attributes inherited from mainPanel
lms7002_pnlCalibrations_view * mTabCalibrations
lms7002_pnlRFE_view * mTabRFE
lms7002_pnlRBB_view * mTabRBB
lms7002_pnlTRF_view * mTabTRF
lms7002_pnlTBB_view * mTabTBB
lms7002_pnlAFE_view * mTabAFE
lms7002_pnlBIAS_view * mTabBIAS
lms7002_pnlLDO_view * mTabLDO
lms7002_pnlXBUF_view * mTabXBUF
lms7002_pnlCLKGEN_view * mTabCGEN
lms7002_pnlSX_view * mTabSXR
lms7002_pnlSX_view * mTabSXT
lms7002_pnlLimeLightPAD_view * mTabLimeLight
lms7002_pnlTxTSP_view * mTabTxTSP
lms7002_pnlRxTSP_view * mTabRxTSP
lms7002_pnlCDS_view * mTabCDS
lms7002_pnlBIST_view * mTabBIST
lms7002_pnlGains_view * mTabTrxGain
Protected Types inherited from mainPanel
enum {
ID_G_LNA_RFE = 2048, ID_BTN_CH_A, ID_BTN_CH_B, ID_BTN_CHIP_TO_GUI,
ID_BTN_RESET_CHIP, ID_TABS_NOTEBOOK, ID_TAB_CALIBRATIONS, ID_TAB_RFE,
ID_TAB_RBB, ID_TAB_TRF, ID_TAB_TBB, ID_TAB_AFE,
ID_TAB_BIAS, ID_TAB_LDO, ID_TAB_XBUF, ID_TAB_CGEN,
ID_TAB_SXR, ID_TAB_SXT, ID_TAB_LIMELIGHT, ID_TAB_TXTSP,
ID_TAB_RXTSP, ID_TAB_CDS, ID_TAB_BIST, ID_TAB_GAINS
}
Detailed Description
Implementing mainPanel.
Definition at line 19 of file lms7002_mainPanel.h.
Constructor & Destructor Documentation
lms7002_mainPanel::lms7002_mainPanel (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Constructor.
Definition at line 32 of file lms7002_mainPanel.cpp.
References mTabMCU, mTabR3, and mainPanel::tabsNotebook.
lms7002_mainPanel::~lms7002_mainPanel ()
Definition at line 43 of file lms7002_mainPanel.cpp.
Member Function Documentation
int lms7002_mainPanel::GetLmsSelection () protected
Definition at line 378 of file lms7002_mainPanel.cpp.
References mainPanel::cmbLmsDevice.
void lms7002_mainPanel::Initialize (lms_device_t * pControl)
Definition at line 129 of file lms7002_mainPanel.cpp.
References mainPanel::cmbLmsDevice, lms7002_pnlAFE_view::Initialize(), lms7002_pnlLDO_view::Initialize(), lms7002_pnlGains_view::Initialize(), lms7002_pnlXBUF_view::Initialize(), lms7002_pnlCDS_view::Initialize(), lms7002_pnlBIST_view::Initialize(), lms7002_pnlTRF_view::Initialize(), lms7002_pnlBIAS_view::Initialize(), lms7002_pnlTBB_view::Initialize(), lms7002_pnlRBB_view::Initialize(), lms7002_pnlRFE_view::Initialize(), lms7002_pnlLimeLightPAD_view::Initialize(), lms7002_pnlCalibrations_view::Initialize(), lms7002_pnlCLKGEN_view::Initialize(), lms7002_pnlTxTSP_view::Initialize(), lms7002_pnlSX_view::Initialize(), lms7002_pnlRxTSP_view::Initialize(), lms7002_pnlMCU_BD_view::Initialize(), lms7002_pnlR3_view::Initialize(), lmsControl, mainPanel::mTabAFE, mainPanel::mTabBIAS, mainPanel::mTabBIST, mainPanel::mTabCalibrations, mainPanel::mTabCDS, mainPanel::mTabCGEN, mainPanel::mTabLDO, mainPanel::mTabLimeLight, mTabMCU, mTabR3, mainPanel::mTabRBB, mainPanel::mTabRFE, mainPanel::mTabRxTSP, mainPanel::mTabSXR, mainPanel::mTabSXT, mainPanel::mTabTBB, mainPanel::mTabTRF, mainPanel::mTabTrxGain, mainPanel::mTabTxTSP, mainPanel::mTabXBUF, and UpdateGUI().
Referenced by LMS7SuiteAppFrame::UpdateConnections().
void lms7002_mainPanel::OnCalibrateInternalADC (wxCommandEvent & event) protected
Definition at line 370 of file lms7002_mainPanel.cpp.
References lime::LMS7002M::CalibrateInternalADC(), lms(), lmsControl, and status.
void lms7002_mainPanel::OnDownloadAll (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 303 of file lms7002_mainPanel.cpp.
References LMS_Synchronize(), lmsControl, status, and UpdateVisiblePanel().
void lms7002_mainPanel::OnEnableMIMOchecked (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 356 of file lms7002_mainPanel.cpp.
References mainPanel::chkEnableMIMO, enable, LMS7param, LMS_CH_RX, LMS_CH_TX, LMS_EnableChannel(), LMS_GetNumChannels(), LMS_ReadParam(), LMS_WriteParam(), lmsControl, MAC, and UpdateVisiblePanel().
void lms7002_mainPanel::OnLmsDeviceSelect (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 383 of file lms7002_mainPanel.cpp.
References mainPanel::cmbLmsDevice, LMS7param, LMS_WriteParam(), lmsControl, MAC, mainPanel::mTabSXR, mainPanel::mTabSXT, mainPanel::tabsNotebook, and UpdateVisiblePanel().
void lms7002_mainPanel::OnLoadDefault (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 174 of file lms7002_mainPanel.cpp.
References mainPanel::chkEnableMIMO, LMS_Init(), lmsControl, Onnotebook_modulesPageChanged(), and status.
void lms7002_mainPanel::OnNewProject (wxCommandEvent & event) protected
Definition at line 217 of file lms7002_mainPanel.cpp.
References LMS7param, LMS_Reset(), LMS_WriteParam(), lmsControl, MAC, mainPanel::rbChannelA, and UpdateGUI().
void lms7002_mainPanel::Onnotebook_modulesPageChanged (wxNotebookEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 265 of file lms7002_mainPanel.cpp.
References LMS7param, LMS_WriteParam(), lmsControl, MAC, mainPanel::mTabAFE, mainPanel::mTabBIAS, mainPanel::mTabBIST, mainPanel::mTabCDS, mainPanel::mTabCGEN, mainPanel::mTabLDO, mainPanel::mTabSXR, mainPanel::mTabSXT, mainPanel::mTabXBUF, mainPanel::rbChannelA, mainPanel::rbChannelB, mainPanel::tabsNotebook, and UpdateVisiblePanel().
Referenced by OnLoadDefault(), and OnResetChip().
void lms7002_mainPanel::OnOpenProject (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 225 of file lms7002_mainPanel.cpp.
References LMS7param, LMS_LoadConfig(), LMS_WriteParam(), lmsControl, MAC, mainPanel::rbChannelA, status, and UpdateGUI().
void lms7002_mainPanel::OnReadTemperature (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 322 of file lms7002_mainPanel.cpp.
References LMS_GetChipTemperature(), lmsControl, status, and mainPanel::txtTemperature.
void lms7002_mainPanel::OnRegistersTest (wxCommandEvent & event) protected
void lms7002_mainPanel::OnReset (wxCommandEvent & event) protected
void lms7002_mainPanel::OnResetChip (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 164 of file lms7002_mainPanel.cpp.
References mainPanel::chkEnableMIMO, LMS_Reset(), lmsControl, Onnotebook_modulesPageChanged(), and status.
void lms7002_mainPanel::OnSaveProject (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 243 of file lms7002_mainPanel.cpp.
References LMS_SaveConfig(), lmsControl, and status.
void lms7002_mainPanel::OnSwitchToChannelA (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 253 of file lms7002_mainPanel.cpp.
References LMS7param, LMS_WriteParam(), lmsControl, MAC, and UpdateVisiblePanel().
void lms7002_mainPanel::OnSwitchToChannelB (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 259 of file lms7002_mainPanel.cpp.
References LMS7param, LMS_WriteParam(), lmsControl, MAC, and UpdateVisiblePanel().
void lms7002_mainPanel::OnSyncABchecked (wxCommandEvent & event) protected
Definition at line 331 of file lms7002_mainPanel.cpp.
void lms7002_mainPanel::OnUploadAll (wxCommandEvent & event) protected virtual
Reimplemented from mainPanel.
Definition at line 311 of file lms7002_mainPanel.cpp.
References LMS_Synchronize(), lmsControl, status, and UpdateVisiblePanel().
void lms7002_mainPanel::UpdateGUI ()
Definition at line 188 of file lms7002_mainPanel.cpp.
References chan, LMS7param, LMS_ReadParam(), LMS_WriteParam(), lmsControl, MAC, mainPanel::rbChannelA, mainPanel::rbChannelB, t1, t2, and UpdateVisiblePanel().
Referenced by Initialize(), OnNewProject(), and OnOpenProject().
void lms7002_mainPanel::UpdateVisiblePanel ()
Definition at line 47 of file lms7002_mainPanel.cpp.
References mainPanel::ID_TAB_AFE, mainPanel::ID_TAB_BIAS, mainPanel::ID_TAB_BIST, mainPanel::ID_TAB_CALIBRATIONS, mainPanel::ID_TAB_CDS, mainPanel::ID_TAB_CGEN, mainPanel::ID_TAB_GAINS, mainPanel::ID_TAB_LDO, mainPanel::ID_TAB_LIMELIGHT, mainPanel::ID_TAB_RBB, mainPanel::ID_TAB_RFE, mainPanel::ID_TAB_RXTSP, mainPanel::ID_TAB_SXR, mainPanel::ID_TAB_SXT, mainPanel::ID_TAB_TBB, mainPanel::ID_TAB_TRF, mainPanel::ID_TAB_TXTSP, mainPanel::ID_TAB_XBUF, LMS_ReadLMSReg(), lmsControl, mainPanel::mTabAFE, mainPanel::mTabBIAS, mainPanel::mTabBIST, mainPanel::mTabCalibrations, mainPanel::mTabCDS, mainPanel::mTabCGEN, mainPanel::mTabLDO, mainPanel::mTabLimeLight, mTabMCU, mTabR3, mainPanel::mTabRBB, mainPanel::mTabRFE, mainPanel::mTabRxTSP, mainPanel::mTabSXR, mainPanel::mTabSXT, mainPanel::mTabTBB, mainPanel::mTabTRF, mainPanel::mTabTrxGain, mainPanel::mTabTxTSP, mainPanel::mTabXBUF, t1, t2, mainPanel::tabsNotebook, lms7002_pnlAFE_view::UpdateGUI(), lms7002_pnlLDO_view::UpdateGUI(), lms7002_pnlGains_view::UpdateGUI(), lms7002_pnlXBUF_view::UpdateGUI(), lms7002_pnlBIAS_view::UpdateGUI(), lms7002_pnlBIST_view::UpdateGUI(), lms7002_pnlCDS_view::UpdateGUI(), lms7002_pnlTRF_view::UpdateGUI(), lms7002_pnlLimeLightPAD_view::UpdateGUI(), lms7002_pnlRBB_view::UpdateGUI(), lms7002_pnlRFE_view::UpdateGUI(), lms7002_pnlTBB_view::UpdateGUI(), lms7002_pnlCalibrations_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateGUI(), lms7002_pnlCLKGEN_view::UpdateGUI(), lms7002_pnlSX_view::UpdateGUI(), lms7002_pnlRxTSP_view::UpdateGUI(), and lms7002_pnlR3_view::UpdateGUI().
Referenced by OnDownloadAll(), OnEnableMIMOchecked(), OnLmsDeviceSelect(), Onnotebook_modulesPageChanged(), OnSwitchToChannelA(), OnSwitchToChannelB(), OnUploadAll(), and UpdateGUI().
Member Data Documentation
lms_device_t* lms7002_mainPanel::lmsControl protected
Definition at line 52 of file lms7002_mainPanel.h.
Referenced by Initialize(), OnCalibrateInternalADC(), OnDownloadAll(), OnEnableMIMOchecked(), OnLmsDeviceSelect(), OnLoadDefault(), OnNewProject(), Onnotebook_modulesPageChanged(), OnOpenProject(), OnReadTemperature(), OnResetChip(), OnSaveProject(), OnSwitchToChannelA(), OnSwitchToChannelB(), OnUploadAll(), UpdateGUI(), and UpdateVisiblePanel().
lms7002_pnlMCU_BD_view* lms7002_mainPanel::mTabMCU protected
Definition at line 50 of file lms7002_mainPanel.h.
Referenced by Initialize(), lms7002_mainPanel(), and UpdateVisiblePanel().
lms7002_pnlR3_view* lms7002_mainPanel::mTabR3 protected
Definition at line 51 of file lms7002_mainPanel.h.
Referenced by Initialize(), lms7002_mainPanel(), and UpdateVisiblePanel().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_mainPanel.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_mainPanel.cpp