LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/recipes.c File Reference
recipes.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "recipes.h"
Macros
#define TINY 1.0e-20
Functions
void nrerror (char *error_text)
double * vector (int nl, int nh)
int * ivector (int nl, int nh)
void free_vector (double *v, int nl, int nh)
void free_ivector (int *v, int nl, int nh)
double ** matrix (int nrl, int nrh, int ncl, int nch)
void free_matrix (double **m, int nrl, int nrh, int ncl, int nch)
void nrerror (error_text)
int ludcmp (double **a, int n, int *indx, double *d)
void lubksb (double **a, int n, indx, b)
Macro Definition Documentation
#define TINY 1.0e-20
Definition at line 53 of file recipes.c.
Referenced by ludcmp().
Function Documentation
void free_ivector (int * v, int nl, int nh)
Definition at line 96 of file recipes.c.
Referenced by lms().
void free_matrix (double ** m, int nrl, int nrh, int ncl, int nch)
Definition at line 132 of file recipes.c.
References i.
Referenced by lms().
void free_vector (double * v, int nl, int nh)
Definition at line 86 of file recipes.c.
Referenced by lms(), and ludcmp().
int* ivector (int nl, int nh)
Definition at line 73 of file recipes.c.
References nrerror(), and calc_fmcw_peaks::v.
void lubksb (double ** a, int n, indx , b)
Definition at line 226 of file recipes.c.
References i, and dfilter::n.
Referenced by lms().
int ludcmp (double ** a, int n, int * indx, double* d)
Definition at line 163 of file recipes.c.
References free_vector(), i, k, dfilter::n, nrerror(), temp, TINY, and vector().
Referenced by lms().
double** matrix (int nrl, int nrh, int ncl, int nch)
Definition at line 107 of file recipes.c.
References i, dfilter::m, and nrerror().
void nrerror (char * error_text)
Referenced by ivector(), ludcmp(), matrix(), and vector().
void nrerror (error_text)
Definition at line 145 of file recipes.c.
double* vector (int nl, int nh)
Definition at line 60 of file recipes.c.
References nrerror(), and calc_fmcw_peaks::v.
Referenced by ludcmp().