LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/tests/TestTimeConversion.cpp File Reference
TestTimeConversion.cpp File Reference
#include <SoapySDR/Time.hpp>
#include <cstdlib>
#include <cstdio>
#include <cmath>
Functions
static bool loopbackTimeToTicks (const long long timeNs, const double rate)
static bool loopbackTicksToTime (const long long ticks, const double rate)
static unsigned rand256 (void)
static unsigned long long rand64bits (void)
int main (void)
Function Documentation
static bool loopbackTicksToTime (const long long ticks, const double rate) static
Definition at line 21 of file TestTimeConversion.cpp.
References SoapySDR::ticksToTimeNs, and SoapySDR::timeNsToTicks.
Referenced by main().
static bool loopbackTimeToTicks (const long long timeNs, const double rate) static
Definition at line 9 of file TestTimeConversion.cpp.
References SoapySDR::ticksToTimeNs, and SoapySDR::timeNsToTicks.
Referenced by main().
int main (void)
Definition at line 54 of file TestTimeConversion.cpp.
References i, loopbackTicksToTime(), loopbackTimeToTicks(), and rand64bits().
static unsigned rand256 (void) static
Definition at line 33 of file TestTimeConversion.cpp.
Referenced by rand64bits().
static unsigned long long rand64bits (void) static
Definition at line 44 of file TestTimeConversion.cpp.
References rand256().
Referenced by main().