LimeSuite-UML: lime::ConnectionSTREAM_UNITEEntry Class Reference
lime::ConnectionSTREAM_UNITEEntry Class Reference
#include <ConnectionSTREAM_UNITE.h>
Public Member Functions
ConnectionSTREAM_UNITEEntry (void)
~ConnectionSTREAM_UNITEEntry (void)
std::vector< ConnectionHandle > enumerate (const ConnectionHandle &hint)
IConnection * make (const ConnectionHandle &handle)
Public Member Functions inherited from lime::ConnectionFX3Entry
ConnectionFX3Entry (void)
virtual ~ConnectionFX3Entry (void)
Public Member Functions inherited from lime::ConnectionRegistryEntry
ConnectionRegistryEntry (const std::string &name)
virtual ~ConnectionRegistryEntry (void)
Unregister a connection type.
Additional Inherited Members
Protected Attributes inherited from lime::ConnectionFX3Entry
void * ctx
Detailed Description
Definition at line 29 of file ConnectionSTREAM_UNITE.h.
Constructor & Destructor Documentation
ConnectionSTREAM_UNITEEntry::ConnectionSTREAM_UNITEEntry (void)
Definition at line 18 of file ConnectionSTREAM_UNITEEntry.cpp.
ConnectionSTREAM_UNITEEntry::~ConnectionSTREAM_UNITEEntry (void)
Definition at line 24 of file ConnectionSTREAM_UNITEEntry.cpp.
Member Function Documentation
std::vector< ConnectionHandle > ConnectionSTREAM_UNITEEntry::enumerate (const ConnectionHandle & hint) virtual
A discovery function takes a connection handle hint and returns a list of identifiers that can be used to create connection with makeConnection().
Parameters
hint an optional connection handle with some fields filled-in
Returns
a list of handles which can be used to make a connection
Reimplemented from lime::ConnectionFX3Entry.
Definition at line 120 of file ConnectionSTREAM_UNITEEntry.cpp.
References lime::ConnectionHandle::addr, lime::DeviceInfo::deviceName, lime::ConnectionFX3Entry::enumerate(), FindAllComPorts(), lime::ConnectionHandle::index, lime::info(), lime::ConnectionHandle::media, lime::ConnectionHandle::module, lime::ConnectionHandle::name, and port.
IConnection * ConnectionSTREAM_UNITEEntry::make (const ConnectionHandle & handle) virtual
A factory function creates a connection from a connection handle.
Parameters
handle a connection handle with fields filled-in
Returns
a pointer to a connection instance
Reimplemented from lime::ConnectionFX3Entry.
Definition at line 167 of file ConnectionSTREAM_UNITEEntry.cpp.
References lime::ConnectionHandle::addr, lime::ConnectionFX3Entry::ctx, lime::ConnectionHandle::index, and lime::ConnectionHandle::serial.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionSTREAM_UNITE/ConnectionSTREAM_UNITE.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionSTREAM_UNITE/ConnectionSTREAM_UNITEEntry.cpp