LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/lms7002m_filters.h File Reference
lms7002m_filters.h File Reference
#include "typedefs.h"
Functions
uint8_t TuneTxFilterFixed (const float_type fixedBandwidth)
uint8_t TuneTxFilter (const float_type bandwidth)
uint8_t TuneRxFilter (const float_type rx_lpf_freq_RF)
uint8_t CalibrateRxFilter (const float_type rx_lpf_freq_RF)
Function Documentation
uint8_t CalibrateRxFilter (const float_type rx_lpf_freq_RF)
uint8_t TuneRxFilter (const float_type rx_lpf_freq_RF)
Definition at line 296 of file lms7002m_filters.c.
References CCOMP_TIA_RFE, CFB_TIA_RFE, CG_IAMP_TBB, ChangeUntilReachRSSI(), clamp(), G_RXLOOPB_RFE, G_TIA_RFE, Get_SPI_Reg_bits(), GetRSSI(), INPUT_CTL_PGA_RBB, int(), LMS7002M_Rx, MCU_CFB_TIA_RFE_LIMIT_REACHED, MCU_NO_ERROR, MCU_R_CTL_LPF_LIMIT_REACHED, MCU_RX_INVALID_TIA, Modify_SPI_Reg_bits(), MSB_LSB, R_CTL_LPF_RBB, RCOMP_TIA_RFE, ROM, RxFilterSearch(), SaveChipState(), SEARCH_NEED_TO_INCREASE, SEARCH_SUCCESS, SetFrequencySX(), SetNCOFrequency(), SPI_read(), SPI_write(), status, TuneRxFilterSetup(), and UpdateRSSIDelay().
Referenced by Filters(), and main().
uint8_t TuneTxFilter (const float_type bandwidth)
Definition at line 636 of file lms7002m_filters.c.
References C_CTL_PGA_RBB, CCAL_LPFLAD_TBB, CG_IAMP_TBB, ChangeUntilReachRSSI(), Get_SPI_Reg_bits(), MCU_NO_ERROR, MCU_TX_LPF_OUT_OF_RANGE, Modify_SPI_Reg_bits(), RCAL_LPFH_TBB, RCAL_LPFLAD_TBB, ROM, SaveChipState(), SearchTxFilterCCAL_RCAL(), SEL_RX, SEL_TX, SetTxLPF_PDs(), SPI_read(), SPI_write(), status, TuneTxFilterSetup(), TxLPF_RF_LimitHigh, TxLPF_RF_LimitLowMid, TxLPF_RF_LimitMidHigh, and UpdateRSSIDelay().
Referenced by Filters(), and main().
uint8_t TuneTxFilterFixed (const float_type fixedBandwidth)