LimeSuite-UML: FPGAcontrols_wxgui Class Reference
FPGAcontrols_wxgui Class Reference
#include <FPGAcontrols_wxgui.h>
Public Member Functions
FPGAcontrols_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long styles=0)
virtual void Initialize (lms_device_t *dataPort)
virtual ~FPGAcontrols_wxgui ()
int UploadFile (const wxString &filename)
int UploadFile (std::vector< int16_t > isamples, std::vector< int16_t > qsamples)
Public Attributes
wxButton * btnPlayWFM
wxButton * btnStopWFM
wxStaticText * lblProgressPercent
wxGauge * progressBar
wxBitmapButton * btnOpenWFM
wxToggleButton * btnLoadOnetone
wxStaticText * txtFilename
wxToggleButton * btnLoadCustom
wxToggleButton * btnLoadWCDMA
wxStaticText * txtDataRate
wxCheckBox * chkDigitalLoopbackEnable
wxCheckBox * chkMIMO
Protected Attributes
lms_device_t * lmsControl
wxTimer * mStreamingTimer
Static Protected Attributes
static const long ID_BUTTON6 = wxNewId()
static const long ID_BUTTON7 = wxNewId()
static const long ID_BUTTON8 = wxNewId()
static const long ID_BITMAPBUTTON1 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_STATICTEXT5 = wxNewId()
static const long ID_GAUGE1 = wxNewId()
static const long ID_BUTTON3 = wxNewId()
static const long ID_BUTTON4 = wxNewId()
static const long ID_STREAMING_TIMER = wxNewId()
Private Member Functions
void OnbtnUploadClick (wxCommandEvent &event)
void OnbtnOpenFileClick (wxCommandEvent &event)
void OnbtnMifClick (wxCommandEvent &event)
void OnbtnHexClick (wxCommandEvent &event)
void OnbtnPlayWFMClick (wxCommandEvent &event)
void OnbtnStopWFMClick (wxCommandEvent &event)
void OnbtnLoadOnetoneClick (wxCommandEvent &event)
void OnbtnLoadWCDMAClick (wxCommandEvent &event)
void OnbtnLoadCustomClick (wxCommandEvent &event)
void OnChkDigitalLoopbackEnableClick (wxCommandEvent &event)
Private Attributes
wxChoice * cmbDevice
Detailed Description
Definition at line 25 of file FPGAcontrols_wxgui.h.
Constructor & Destructor Documentation
FPGAcontrols_wxgui::FPGAcontrols_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long styles = 0)
Definition at line 49 of file FPGAcontrols_wxgui.cpp.
References _T, lmsControl, OnbtnLoadCustomClick(), OnbtnLoadOnetoneClick(), OnbtnLoadWCDMAClick(), OnbtnOpenFileClick(), OnbtnPlayWFMClick(), OnbtnStopWFMClick(), and OnChkDigitalLoopbackEnableClick().
FPGAcontrols_wxgui::~FPGAcontrols_wxgui () virtual
Definition at line 142 of file FPGAcontrols_wxgui.cpp.
Member Function Documentation
void FPGAcontrols_wxgui::Initialize (lms_device_t * dataPort) virtual
Definition at line 131 of file FPGAcontrols_wxgui.cpp.
References LMS_CH_TX, LMS_GetNumChannels(), and lmsControl.
Referenced by LMS7SuiteAppFrame::OnShowFPGAcontrols(), and LMS7SuiteAppFrame::UpdateConnections().
void FPGAcontrols_wxgui::OnbtnHexClick (wxCommandEvent & event) private
void FPGAcontrols_wxgui::OnbtnLoadCustomClick (wxCommandEvent & event) private
Definition at line 354 of file FPGAcontrols_wxgui.cpp.
Referenced by FPGAcontrols_wxgui().
void FPGAcontrols_wxgui::OnbtnLoadOnetoneClick (wxCommandEvent & event) private
Definition at line 306 of file FPGAcontrols_wxgui.cpp.
References i, and PI.
Referenced by FPGAcontrols_wxgui().
void FPGAcontrols_wxgui::OnbtnLoadWCDMAClick (wxCommandEvent & event) private
Definition at line 330 of file FPGAcontrols_wxgui.cpp.
References i, wcdma_wfm, and wcdma_wfm_len.
Referenced by FPGAcontrols_wxgui().
void FPGAcontrols_wxgui::OnbtnMifClick (wxCommandEvent & event) private
void FPGAcontrols_wxgui::OnbtnOpenFileClick (wxCommandEvent & event) private
Definition at line 205 of file FPGAcontrols_wxgui.cpp.
Referenced by FPGAcontrols_wxgui().
void FPGAcontrols_wxgui::OnbtnPlayWFMClick (wxCommandEvent & event) private
Definition at line 214 of file FPGAcontrols_wxgui.cpp.
References LMS_EnableTxWFM(), and lmsControl.
Referenced by FPGAcontrols_wxgui().
void FPGAcontrols_wxgui::OnbtnStopWFMClick (wxCommandEvent & event) private
Definition at line 219 of file FPGAcontrols_wxgui.cpp.
References LMS_EnableTxWFM(), and lmsControl.
Referenced by FPGAcontrols_wxgui().
void FPGAcontrols_wxgui::OnbtnUploadClick (wxCommandEvent & event) private
void FPGAcontrols_wxgui::OnChkDigitalLoopbackEnableClick (wxCommandEvent & event) private
Definition at line 368 of file FPGAcontrols_wxgui.cpp.
References address, LMS_ReadFPGAReg(), LMS_WriteFPGAReg(), and lmsControl.
Referenced by FPGAcontrols_wxgui().
int FPGAcontrols_wxgui::UploadFile (const wxString & filename)
Definition at line 224 of file FPGAcontrols_wxgui.cpp.
References lmsControl, and ReadWFM().
int FPGAcontrols_wxgui::UploadFile (std::vector< int16_t > isamples, std::vector< int16_t > qsamples)
Definition at line 249 of file FPGAcontrols_wxgui.cpp.
References c, chCount, i, lime::complex16_t::i, LMS_EnableTxWFM(), LMS_UploadWFM(), lmsControl, lime::complex16_t::q, src, and status.
Member Data Documentation
wxToggleButton* FPGAcontrols_wxgui::btnLoadCustom
Definition at line 41 of file FPGAcontrols_wxgui.h.
wxToggleButton* FPGAcontrols_wxgui::btnLoadOnetone
Definition at line 39 of file FPGAcontrols_wxgui.h.
wxToggleButton* FPGAcontrols_wxgui::btnLoadWCDMA
Definition at line 42 of file FPGAcontrols_wxgui.h.
wxBitmapButton* FPGAcontrols_wxgui::btnOpenWFM
Definition at line 38 of file FPGAcontrols_wxgui.h.
wxButton* FPGAcontrols_wxgui::btnPlayWFM
Definition at line 34 of file FPGAcontrols_wxgui.h.
wxButton* FPGAcontrols_wxgui::btnStopWFM
Definition at line 35 of file FPGAcontrols_wxgui.h.
wxCheckBox* FPGAcontrols_wxgui::chkDigitalLoopbackEnable
Definition at line 44 of file FPGAcontrols_wxgui.h.
wxCheckBox* FPGAcontrols_wxgui::chkMIMO
Definition at line 45 of file FPGAcontrols_wxgui.h.
wxChoice* FPGAcontrols_wxgui::cmbDevice private
Definition at line 60 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_BITMAPBUTTON1 = wxNewId() static protected
Definition at line 51 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_BUTTON3 = wxNewId() static protected
Definition at line 55 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_BUTTON4 = wxNewId() static protected
Definition at line 56 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_BUTTON6 = wxNewId() static protected
Definition at line 48 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_BUTTON7 = wxNewId() static protected
Definition at line 49 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_BUTTON8 = wxNewId() static protected
Definition at line 50 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_GAUGE1 = wxNewId() static protected
Definition at line 54 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_STATICTEXT2 = wxNewId() static protected
Definition at line 52 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_STATICTEXT5 = wxNewId() static protected
Definition at line 53 of file FPGAcontrols_wxgui.h.
const long FPGAcontrols_wxgui::ID_STREAMING_TIMER = wxNewId() static protected
Definition at line 57 of file FPGAcontrols_wxgui.h.
wxStaticText* FPGAcontrols_wxgui::lblProgressPercent
Definition at line 36 of file FPGAcontrols_wxgui.h.
lms_device_t* FPGAcontrols_wxgui::lmsControl protected
Definition at line 72 of file FPGAcontrols_wxgui.h.
wxTimer* FPGAcontrols_wxgui::mStreamingTimer protected
Definition at line 73 of file FPGAcontrols_wxgui.h.
wxGauge* FPGAcontrols_wxgui::progressBar
Definition at line 37 of file FPGAcontrols_wxgui.h.
wxStaticText* FPGAcontrols_wxgui::txtDataRate
Definition at line 43 of file FPGAcontrols_wxgui.h.
wxStaticText* FPGAcontrols_wxgui::txtFilename
Definition at line 40 of file FPGAcontrols_wxgui.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/FPGAcontrols_wxgui/FPGAcontrols_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/FPGAcontrols_wxgui/FPGAcontrols_wxgui.cpp