LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/host_src/main.cpp File Reference
main.cpp File Reference
#include <stdio.h>
#include "lms7002m_calibrations.h"
#include "lms7002m_controls.h"
#include "lms7002m_filters.h"
#include "spi.h"
#include "mcu.h"
#include "mcuHexBin.h"
#include "MCU_BD.h"
#include "LMSBoards.h"
#include "LMS7002M.h"
#include "IConnection.h"
#include "ConnectionRegistry.h"
#include <chrono>
#include <fstream>
#include <gnuPlotPipe.h>
#include <math.h>
#include "mcu_defines.h"
Classes
class BoardLoopbackStore
Functions
uint8_t GetExtLoopPair (lime::LMS7002M &ctr, bool calibratingTx)
int16_t ReadDCCorrector (bool tx, uint8_t channel)
int SetExtLoopback (lime::IConnection *port, uint8_t ch, bool enable)
uint8_t UploadMCUParameters (float ref, float bandwidth)
void DCIQ ()
void Filters ()
int main (int argc, char **argv)
Variables
lime::IConnection * serPort = nullptr
lime::LMS7002M lmsControl
static bool useMCU =1
static bool tx = 1
static bool filters = 0
static float FBW = 5e6
static bool extLoop = false
float RefClk
uint8_t extLoopbackPair
Function Documentation
void DCIQ ()
Definition at line 174 of file main.cpp.
References CalibrateRx(), CalibrateTx(), extLoop, extLoopbackPair, FBW, freq, GCORRI_RXTSP, GCORRI_TXTSP, GCORRQ_RXTSP, GCORRQ_TXTSP, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetConnection(), GetExtLoopPair(), IQCORR_RXTSP, IQCORR_TXTSP, LMS7param, lime::LMS7002M::LoadDC_REG_IQ(), MCU_EXT_LOOPBACK_PAIR, MCU_NO_ERROR, MCU_RunProcedure(), MCU_SetParameter(), MCU_WaitForStatus(), lime::LMS7002M::Modify_SPI_Reg_bits(), ReadDCCorrector(), RefClk, SetExtLoopback(), status, t1, t2, TSGMODE_TXTSP, tx, UploadMCUParameters(), and useMCU.
Referenced by main().
void Filters ()
Definition at line 268 of file main.cpp.
References C_CTL_LPFL_RBB, CCAL_LPFLAD_TBB, CCOMP_TIA_RFE, CFB_TIA_RFE, FBW, lime::LMS7002M::Get_SPI_Reg_bits(), LMS7param, lime::LMS7002M::LoadDC_REG_IQ(), MCU_NO_ERROR, MCU_RunProcedure(), MCU_WaitForStatus(), lime::LMS7002M::Modify_SPI_Reg_bits(), RCAL_LPFH_TBB, RCAL_LPFLAD_TBB, RCC_CTL_LPFH_RBB, RCC_CTL_LPFL_RBB, RCOMP_TIA_RFE, RefClk, status, t1, t2, TSGMODE_TXTSP, TuneRxFilter(), TuneTxFilter(), tx, UploadMCUParameters(), and useMCU.
Referenced by main().
uint8_t GetExtLoopPair (lime::LMS7002M & ctr, bool calibratingTx)
Definition at line 33 of file main.cpp.
References lime::DeviceInfo::deviceName, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetConnection(), lime::IConnection::GetDeviceInfo(), lime::GetDeviceName(), LMS7_SEL_BAND1_TRF, LMS7_SEL_BAND2_TRF, LMS7_SEL_PATH_RFE, lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDRMINI, and port.
Referenced by DCIQ().
int main (int argc, char ** argv)
Definition at line 317 of file main.cpp.
References DCIQ(), filename, filters, Filters(), lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::freeConnection(), lime::IConnection::GetDeviceInfo(), lime::LMS7002M::GetReferenceClk_SX(), i, info, lime::IConnection::IsOpen(), LMS7param, lime::LMS7002M::LoadConfig(), lime::ConnectionRegistry::makeConnection(), MCU_HEX2BIN(), MCU_UploadProgram(), lime::LMS7002M::Modify_SPI_Reg_bits(), RefClk, serPort, lime::LMS7002M::SetConnection(), lime::LMS7002M::SPI_write(), status, TSGMODE_TXTSP, tx, lime::LMS7002M::UploadAll(), and useMCU.
int16_t ReadDCCorrector (bool tx, uint8_t channel)
Definition at line 51 of file main.cpp.
References SPI_read(), and SPI_write().
Referenced by DCIQ().
int SetExtLoopback (lime::IConnection * port, uint8_t ch, bool enable)
Definition at line 88 of file main.cpp.
References lime::DeviceInfo::deviceName, lime::IConnection::GetDeviceInfo(), lime::GetDeviceName(), lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDRMINI, lime::IConnection::ReadLMS7002MSPI(), lime::IConnection::ReadRegister(), status, tx, and lime::IConnection::WriteRegister().
Referenced by DCIQ().
uint8_t UploadMCUParameters (float ref, float bandwidth)
Definition at line 164 of file main.cpp.
References MCU_BW, MCU_NO_ERROR, MCU_REF_CLK, MCU_SetParameter(), and status.
Referenced by DCIQ(), and Filters().
Variable Documentation
bool extLoop = false static
Definition at line 29 of file main.cpp.
Referenced by DCIQ().
uint8_t extLoopbackPair
Definition at line 83 of file lms7002m_calibrations.c.
Referenced by DCIQ().
float FBW = 5e6 static
Definition at line 28 of file main.cpp.
Referenced by DCIQ(), and Filters().
bool filters = 0 static
Definition at line 27 of file main.cpp.
Referenced by main().
lime::LMS7002M lmsControl
Definition at line 22 of file main.cpp.
Referenced by FPGAcontrols_wxgui::FPGAcontrols_wxgui(), pnlBuffers::Initialize(), pnluLimeSDR::Initialize(), Myriad7_wxgui::Initialize(), pnlLimeSDR::Initialize(), Si5351C_wxgui::Initialize(), FPGAcontrols_wxgui::Initialize(), ADF4002_wxgui::Initialize(), pnlUltimateEVB::Initialize(), fftviewer_frFFTviewer::Initialize(), LimeSDRTest::LMS7002mTest(), ADF4002_wxgui::OnbtnCalcSendClick(), Si5351C_wxgui::OnbtnClearStatusClick(), Si5351C_wxgui::OnbtnConfigureClockClick(), Si5351C_wxgui::OnbtnLoadFileClick(), FPGAcontrols_wxgui::OnbtnPlayWFMClick(), Si5351C_wxgui::OnbtnReadStatusClick(), Si5351C_wxgui::OnbtnResetToDefaultsClick(), FPGAcontrols_wxgui::OnbtnStopWFMClick(), ADF4002_wxgui::OnbtnUploadClick(), FPGAcontrols_wxgui::OnChkDigitalLoopbackEnableClick(), pnlLimeSDR::OnGPIOChange(), pnlBuffers::OnGPIOchanged(), pnluLimeSDR::OnLoopbackChange(), pnlUltimateEVB::OnReadAll(), pnlLimeSDR::OnUsrGPIOChange(), pnlLimeSDR::OnUsrGPIODirChange(), Myriad7_wxgui::ParameterChangeHandler(), pnlBuffers::pnlBuffers(), pnlLimeSDR::pnlLimeSDR(), pnluLimeSDR::pnluLimeSDR(), pnlUltimateEVB::pnlUltimateEVB(), Si5351C_wxgui::Si5351C_wxgui(), TEST_F(), pnlBuffers::UpdatePanel(), pnluLimeSDR::UpdatePanel(), Myriad7_wxgui::UpdatePanel(), pnlLimeSDR::UpdatePanel(), and FPGAcontrols_wxgui::UploadFile().
float RefClk
Definition at line 22 of file lms7002m_controls.c.
Referenced by DCIQ(), Filters(), and main().
lime::IConnection* serPort = nullptr
Definition at line 21 of file main.cpp.
Referenced by LMS7002M_Novena_wxgui::Initialize(), main(), and TEST_F().
bool tx = 1 static
Definition at line 26 of file main.cpp.
Referenced by DCIQ(), DEFUN_DLD(), Filters(), SoapyLMS7::getAntenna(), main(), SoapyLMS7::setAntenna(), and SetExtLoopback().
bool useMCU =1 static
Definition at line 25 of file main.cpp.
Referenced by DCIQ(), Filters(), and main().