LimeSuite-UML: SPI_wxgui Class Reference
SPI_wxgui Class Reference
Implementing SPI_view.
#include <SPI_wxgui.h>
Public Member Functions
SPI_wxgui (wxWindow *parent)
Constructor.
SPI_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long styles=0)
virtual void Initialize (lms_device_t *pCtrPort, const size_t devIndex=0)
Public Member Functions inherited from SPI_view
SPI_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("SPI"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL)
~SPI_view ()
Protected Member Functions
void onLMSwrite (wxCommandEvent &event)
void onLMSread (wxCommandEvent &event)
void onBoardWrite (wxCommandEvent &event)
void OnBoardRead (wxCommandEvent &event)
Protected Attributes
lms_device_t * ctrPort
int m_rficSpiAddr
Protected Attributes inherited from SPI_view
wxStaticText * ID_STATICTEXT1
wxTextCtrl * txtLMSwriteAddr
wxStaticText * ID_STATICTEXT9
wxTextCtrl * txtLMSwriteValue
wxButton * btnLMSwrite
wxButton * btnLMSread
wxStaticText * ID_STATICTEXT5
wxStaticText * lblLMSwriteStatus
wxStaticText * ID_STATICTEXT11
wxTextCtrl * txtLMSwriteAddr1
wxStaticText * ID_STATICTEXT91
wxTextCtrl * txtLMSwriteValue1
wxButton * btnLMSwrite1
wxButton * btnLMSread1
wxStaticText * ID_STATICTEXT51
wxStaticText * lblLMSwriteStatus1
wxStaticText * ID_STATICTEXT12
wxTextCtrl * txtLMSwriteAddr2
wxStaticText * ID_STATICTEXT92
wxTextCtrl * txtLMSwriteValue2
wxButton * btnLMSwrite2
wxButton * btnLMSread2
wxStaticText * ID_STATICTEXT52
wxStaticText * lblLMSwriteStatus2
wxStaticText * ID_STATICTEXT13
wxTextCtrl * txtLMSwriteAddr3
wxStaticText * ID_STATICTEXT93
wxTextCtrl * txtLMSwriteValue3
wxButton * btnLMSwrite3
wxButton * btnLMSread3
wxStaticText * ID_STATICTEXT53
wxStaticText * lblLMSwriteStatus3
wxStaticText * ID_STATICTEXT14
wxTextCtrl * txtLMSwriteAddr4
wxStaticText * ID_STATICTEXT94
wxTextCtrl * txtLMSwriteValue4
wxButton * btnLMSwrite4
wxButton * btnLMSread4
wxStaticText * ID_STATICTEXT54
wxStaticText * lblLMSwriteStatus4
wxStaticText * ID_STATICTEXT18
wxTextCtrl * txtLMSwriteAddr5
wxStaticText * ID_STATICTEXT95
wxTextCtrl * txtLMSwriteValue5
wxButton * btnLMSwrite5
wxButton * btnLMSread5
wxStaticText * ID_STATICTEXT55
wxStaticText * lblLMSwriteStatus5
wxStaticText * ID_STATICTEXT19
wxTextCtrl * txtLMSwriteAddr6
wxStaticText * ID_STATICTEXT96
wxTextCtrl * txtLMSwriteValue6
wxButton * btnLMSwrite6
wxButton * btnLMSread6
wxStaticText * ID_STATICTEXT56
wxStaticText * lblLMSwriteStatus6
wxStaticText * ID_STATICTEXT110
wxTextCtrl * txtLMSwriteAddr7
wxStaticText * ID_STATICTEXT97
wxTextCtrl * txtLMSwriteValue7
wxButton * btnLMSwrite7
wxButton * btnLMSread7
wxStaticText * ID_STATICTEXT57
wxStaticText * lblLMSwriteStatus7
wxStaticText * ID_STATICTEXT15
wxTextCtrl * txtBoardwriteAddr
wxStaticText * ID_STATICTEXT16
wxTextCtrl * txtBoardwriteValue
wxButton * ID_BUTTON24
wxButton * ID_BUTTON25
wxStaticText * ID_STATICTEXT17
wxStaticText * lblBoardwriteStatus
wxStaticText * ID_STATICTEXT151
wxTextCtrl * txtBoardwriteAddr1
wxStaticText * ID_STATICTEXT161
wxTextCtrl * txtBoardwriteValue1
wxButton * ID_BUTTON241
wxButton * ID_BUTTON251
wxStaticText * ID_STATICTEXT171
wxStaticText * lblBoardwriteStatus1
wxStaticText * ID_STATICTEXT152
wxTextCtrl * txtBoardwriteAddr2
wxStaticText * ID_STATICTEXT162
wxTextCtrl * txtBoardwriteValue2
wxButton * ID_BUTTON242
wxButton * ID_BUTTON252
wxStaticText * ID_STATICTEXT172
wxStaticText * lblBoardwriteStatus2
wxStaticText * ID_STATICTEXT153
wxTextCtrl * txtBoardwriteAddr3
wxStaticText * ID_STATICTEXT163
wxTextCtrl * txtBoardwriteValue3
wxButton * ID_BUTTON243
wxButton * ID_BUTTON253
wxStaticText * ID_STATICTEXT173
wxStaticText * lblBoardwriteStatus3
wxStaticText * ID_STATICTEXT154
wxTextCtrl * txtBoardwriteAddr4
wxStaticText * ID_STATICTEXT164
wxTextCtrl * txtBoardwriteValue4
wxButton * ID_BUTTON244
wxButton * ID_BUTTON254
wxStaticText * ID_STATICTEXT174
wxStaticText * lblBoardwriteStatus4
wxStaticText * ID_STATICTEXT155
wxTextCtrl * txtBoardwriteAddr5
wxStaticText * ID_STATICTEXT165
wxTextCtrl * txtBoardwriteValue5
wxButton * ID_BUTTON245
wxButton * ID_BUTTON255
wxStaticText * ID_STATICTEXT175
wxStaticText * lblBoardwriteStatus5
wxStaticText * ID_STATICTEXT156
wxTextCtrl * txtBoardwriteAddr6
wxStaticText * ID_STATICTEXT166
wxTextCtrl * txtBoardwriteValue6
wxButton * ID_BUTTON246
wxButton * ID_BUTTON256
wxStaticText * ID_STATICTEXT176
wxStaticText * lblBoardwriteStatus6
wxStaticText * ID_STATICTEXT157
wxTextCtrl * txtBoardwriteAddr7
wxStaticText * ID_STATICTEXT167
wxTextCtrl * txtBoardwriteValue7
wxButton * ID_BUTTON247
wxButton * ID_BUTTON257
wxStaticText * ID_STATICTEXT177
wxStaticText * lblBoardwriteStatus7
Detailed Description
Implementing SPI_view.
Definition at line 15 of file SPI_wxgui.h.
Constructor & Destructor Documentation
SPI_wxgui::SPI_wxgui (wxWindow * parent)
Constructor.
SPI_wxgui::SPI_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long styles = 0)
Definition at line 5 of file SPI_wxgui.cpp.
References ctrPort.
Member Function Documentation
void SPI_wxgui::Initialize (lms_device_t * pCtrPort, const size_t devIndex = 0) virtual
Definition at line 12 of file SPI_wxgui.cpp.
References ctrPort.
Referenced by LMS7SuiteAppFrame::OnShowSPI(), and LMS7SuiteAppFrame::UpdateConnections().
void SPI_wxgui::OnBoardRead (wxCommandEvent & event) protected virtual
Reimplemented from SPI_view.
Definition at line 129 of file SPI_wxgui.cpp.
References address, ctrPort, SPI_view::ID_BUTTON25, SPI_view::ID_BUTTON251, SPI_view::ID_BUTTON252, SPI_view::ID_BUTTON253, SPI_view::ID_BUTTON254, SPI_view::ID_BUTTON255, SPI_view::ID_BUTTON256, SPI_view::ID_BUTTON257, index, SPI_view::lblBoardwriteStatus, SPI_view::lblBoardwriteStatus1, SPI_view::lblBoardwriteStatus2, SPI_view::lblBoardwriteStatus3, SPI_view::lblBoardwriteStatus4, SPI_view::lblBoardwriteStatus5, SPI_view::lblBoardwriteStatus6, SPI_view::lblBoardwriteStatus7, LMS_ReadFPGAReg(), status, SPI_view::txtBoardwriteAddr, SPI_view::txtBoardwriteAddr1, SPI_view::txtBoardwriteAddr2, SPI_view::txtBoardwriteAddr3, SPI_view::txtBoardwriteAddr4, SPI_view::txtBoardwriteAddr5, SPI_view::txtBoardwriteAddr6, SPI_view::txtBoardwriteAddr7, SPI_view::txtBoardwriteValue, SPI_view::txtBoardwriteValue1, SPI_view::txtBoardwriteValue2, SPI_view::txtBoardwriteValue3, SPI_view::txtBoardwriteValue4, SPI_view::txtBoardwriteValue5, SPI_view::txtBoardwriteValue6, and SPI_view::txtBoardwriteValue7.
void SPI_wxgui::onBoardWrite (wxCommandEvent & event) protected virtual
Reimplemented from SPI_view.
Definition at line 92 of file SPI_wxgui.cpp.
References address, ctrPort, SPI_view::ID_BUTTON24, SPI_view::ID_BUTTON241, SPI_view::ID_BUTTON242, SPI_view::ID_BUTTON243, SPI_view::ID_BUTTON244, SPI_view::ID_BUTTON245, SPI_view::ID_BUTTON246, SPI_view::ID_BUTTON247, index, SPI_view::lblBoardwriteStatus, SPI_view::lblBoardwriteStatus1, SPI_view::lblBoardwriteStatus2, SPI_view::lblBoardwriteStatus3, SPI_view::lblBoardwriteStatus4, SPI_view::lblBoardwriteStatus5, SPI_view::lblBoardwriteStatus6, SPI_view::lblBoardwriteStatus7, LMS_WriteFPGAReg(), status, SPI_view::txtBoardwriteAddr, SPI_view::txtBoardwriteAddr1, SPI_view::txtBoardwriteAddr2, SPI_view::txtBoardwriteAddr3, SPI_view::txtBoardwriteAddr4, SPI_view::txtBoardwriteAddr5, SPI_view::txtBoardwriteAddr6, SPI_view::txtBoardwriteAddr7, SPI_view::txtBoardwriteValue, SPI_view::txtBoardwriteValue1, SPI_view::txtBoardwriteValue2, SPI_view::txtBoardwriteValue3, SPI_view::txtBoardwriteValue4, SPI_view::txtBoardwriteValue5, SPI_view::txtBoardwriteValue6, and SPI_view::txtBoardwriteValue7.
void SPI_wxgui::onLMSread (wxCommandEvent & event) protected virtual
Reimplemented from SPI_view.
Definition at line 55 of file SPI_wxgui.cpp.
References address, SPI_view::btnLMSread, SPI_view::btnLMSread1, SPI_view::btnLMSread2, SPI_view::btnLMSread3, SPI_view::btnLMSread4, SPI_view::btnLMSread5, SPI_view::btnLMSread6, SPI_view::btnLMSread7, ctrPort, index, SPI_view::lblLMSwriteStatus, SPI_view::lblLMSwriteStatus1, SPI_view::lblLMSwriteStatus2, SPI_view::lblLMSwriteStatus3, SPI_view::lblLMSwriteStatus4, SPI_view::lblLMSwriteStatus5, SPI_view::lblLMSwriteStatus6, SPI_view::lblLMSwriteStatus7, LMS_ReadLMSReg(), status, SPI_view::txtLMSwriteAddr, SPI_view::txtLMSwriteAddr1, SPI_view::txtLMSwriteAddr2, SPI_view::txtLMSwriteAddr3, SPI_view::txtLMSwriteAddr4, SPI_view::txtLMSwriteAddr5, SPI_view::txtLMSwriteAddr6, SPI_view::txtLMSwriteAddr7, SPI_view::txtLMSwriteValue, SPI_view::txtLMSwriteValue1, SPI_view::txtLMSwriteValue2, SPI_view::txtLMSwriteValue3, SPI_view::txtLMSwriteValue4, SPI_view::txtLMSwriteValue5, SPI_view::txtLMSwriteValue6, and SPI_view::txtLMSwriteValue7.
void SPI_wxgui::onLMSwrite (wxCommandEvent & event) protected virtual
Reimplemented from SPI_view.
Definition at line 21 of file SPI_wxgui.cpp.
References address, SPI_view::btnLMSwrite, SPI_view::btnLMSwrite1, SPI_view::btnLMSwrite2, SPI_view::btnLMSwrite3, SPI_view::btnLMSwrite4, SPI_view::btnLMSwrite5, SPI_view::btnLMSwrite6, SPI_view::btnLMSwrite7, ctrPort, index, SPI_view::lblLMSwriteStatus, SPI_view::lblLMSwriteStatus1, SPI_view::lblLMSwriteStatus2, SPI_view::lblLMSwriteStatus3, SPI_view::lblLMSwriteStatus4, SPI_view::lblLMSwriteStatus5, SPI_view::lblLMSwriteStatus6, SPI_view::lblLMSwriteStatus7, LMS_WriteLMSReg(), status, SPI_view::txtLMSwriteAddr, SPI_view::txtLMSwriteAddr1, SPI_view::txtLMSwriteAddr2, SPI_view::txtLMSwriteAddr3, SPI_view::txtLMSwriteAddr4, SPI_view::txtLMSwriteAddr5, SPI_view::txtLMSwriteAddr6, SPI_view::txtLMSwriteAddr7, SPI_view::txtLMSwriteValue, SPI_view::txtLMSwriteValue1, SPI_view::txtLMSwriteValue2, SPI_view::txtLMSwriteValue3, SPI_view::txtLMSwriteValue4, SPI_view::txtLMSwriteValue5, SPI_view::txtLMSwriteValue6, and SPI_view::txtLMSwriteValue7.
Member Data Documentation
lms_device_t* SPI_wxgui::ctrPort protected
Definition at line 32 of file SPI_wxgui.h.
Referenced by Initialize(), OnBoardRead(), onBoardWrite(), onLMSread(), onLMSwrite(), and SPI_wxgui().
int SPI_wxgui::m_rficSpiAddr protected
Definition at line 34 of file SPI_wxgui.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/SPI_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/SPI_wxgui.cpp