LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_RxTxCalibrations.cpp File Reference
LMS7002M_RxTxCalibrations.cpp File Reference
#include "LMS7002M.h"
#include <assert.h>
#include "MCU_BD.h"
#include "IConnection.h"
#include "mcu_programs.h"
#include <chrono>
#include <thread>
#include "Logger.h"
#include "LMSBoards.h"
Classes
class BoardLoopbackStore
Macros
#define LMS_VERBOSE_OUTPUT
#define verbose_printf(...)
Functions
static uint8_t GetExtLoopPair (lime::LMS7002M &ctr, bool calibratingTx)
static int16_t signextIqCorr (const uint16_t regVal)
static void WriteAnalogDC (lime::LMS7002M *lmsControl, const LMS7Parameter &param, int value)
static int16_t ReadAnalogDC (lime::LMS7002M *lmsControl, const LMS7Parameter &param)
static int SetExtLoopback (IConnection *port, uint8_t ch, bool enable, bool tx)
Variables
static const bool verboseEnabled = true
const double TrxCalib_RF_LimitLow = 2.5e6
const double TrxCalib_RF_LimitHigh = 120e6
static const char cSquaresLine []
static const char cDashLine []
Macro Definition Documentation
#define LMS_VERBOSE_OUTPUT
Definition at line 12 of file LMS7002M_RxTxCalibrations.cpp.
#define verbose_printf (...)
Value:
do { if (verboseEnabled) {\
        fprintf(stderr, __VA_ARGS__);\
    }} while (0)
Definition at line 78 of file LMS7002M_RxTxCalibrations.cpp.
Referenced by lime::LMS7002M::CalibrateRx(), and lime::LMS7002M::CalibrateTx().
Function Documentation
static uint8_t GetExtLoopPair (lime::LMS7002M & ctr, bool calibratingTx) static
Definition at line 43 of file LMS7002M_RxTxCalibrations.cpp.
References lime::DeviceInfo::deviceName, lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetConnection(), lime::IConnection::GetDeviceInfo(), lime::GetDeviceName(), LMS7_SEL_BAND1_TRF, LMS7_SEL_BAND2_TRF, LMS7_SEL_PATH_RFE, lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDRMINI, and port.
Referenced by lime::LMS7002M::CalibrateRx(), and lime::LMS7002M::CalibrateTx().
static int16_t ReadAnalogDC (lime::LMS7002M * lmsControl, const LMS7Parameter & param) static
Definition at line 98 of file LMS7002M_RxTxCalibrations.cpp.
References LMS7Parameter::address, lime::LMS7002M::SPI_read(), and lime::LMS7002M::SPI_write().
Referenced by lime::LMS7002M::CalibrateRx(), and lime::LMS7002M::CalibrateTx().
static int SetExtLoopback (IConnection * port, uint8_t ch, bool enable, bool tx) static
Definition at line 112 of file LMS7002M_RxTxCalibrations.cpp.
References lime::DeviceInfo::deviceName, lime::IConnection::GetDeviceInfo(), lime::GetDeviceName(), lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDRMINI, lime::IConnection::ReadLMS7002MSPI(), lime::IConnection::ReadRegister(), lime::ReportError(), status, and lime::IConnection::WriteRegister().
Referenced by lime::LMS7002M::CalibrateRx(), and lime::LMS7002M::CalibrateTx().
static int16_t signextIqCorr (const uint16_t regVal) inline static
Convert the 12-bit twos compliment register into a signed integer
Definition at line 64 of file LMS7002M_RxTxCalibrations.cpp.
Referenced by lime::LMS7002M::CalibrateRx(), and lime::LMS7002M::CalibrateTx().
static void WriteAnalogDC (lime::LMS7002M * lmsControl, const LMS7Parameter & param, int value) static
Definition at line 83 of file LMS7002M_RxTxCalibrations.cpp.
References LMS7Parameter::address, and lime::LMS7002M::SPI_write().
Variable Documentation
const char cDashLine[] static
Initial value:
=
    "------------------------------------------------------------\n"
Definition at line 75 of file LMS7002M_RxTxCalibrations.cpp.
const char cSquaresLine[] static
Initial value:
=
    "############################################################\n"
Definition at line 73 of file LMS7002M_RxTxCalibrations.cpp.
const double TrxCalib_RF_LimitHigh = 120e6
Definition at line 71 of file LMS7002M_RxTxCalibrations.cpp.
Referenced by lime::LMS7002M::CalibrateRx(), and lime::LMS7002M::CalibrateTx().
const double TrxCalib_RF_LimitLow = 2.5e6
Definition at line 70 of file LMS7002M_RxTxCalibrations.cpp.
Referenced by lime::LMS7002M::CalibrateRx(), and lime::LMS7002M::CalibrateTx().
const bool verboseEnabled = true static
Definition at line 16 of file LMS7002M_RxTxCalibrations.cpp.