LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/examples/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/examples/CMakeLists.txt File Reference
Functions
include (FeatureSummary) include(CMakeDependentOption) cmake_dependent_option(ENABLE_EXAMPLES"Enable library example programs"ON"ENABLE_LIBRARY"OFF) add_feature_info(LimeSuiteExamples ENABLE_EXAMPLES"LimeSuite library API examples") if(NOT ENABLE_EXAMPLES) return() endif() if(UNIX) find_package(Gnuplot) if(GNUPLOT_FOUND) add_definitions(-DUSE_GNU_PLOT) message(STATUS"GNUPlot Found") endif() endif() add_executable(basicRX basicRX.cpp) set_target_properties(basicRX PROPERTIES RUNTIME_OUTPUT_DIRECTORY"$
bin target_link_libraries (basicRX LimeSuite) add_executable(singleRX singleRX.cpp) set_target_properties(singleRX PROPERTIES RUNTIME_OUTPUT_DIRECTORY"$
bin target_link_libraries (singleRX LimeSuite) add_executable(dualRXTX dualRXTX.cpp) set_target_properties(dualRXTX PROPERTIES RUNTIME_OUTPUT_DIRECTORY"$
bin target_link_libraries (dualRXTX LimeSuite) add_executable(gpio_example gpio_example.cpp) set_target_properties(gpio_example PROPERTIES RUNTIME_OUTPUT_DIRECTORY"$
bin target_link_libraries (gpio_example LimeSuite) add_executable(basicTX basicTX.cpp) set_target_properties(basicTX PROPERTIES RUNTIME_OUTPUT_DIRECTORY"$
Function Documentation
include (FeatureSummary)
Definition at line 1 of file CMakeLists.txt.
bin target_link_libraries (basicRX LimeSuite)
Definition at line 19 of file CMakeLists.txt.
Referenced by cmake_policy(), endif(), set(), and target_include_directories().
bin target_link_libraries (singleRX LimeSuite)
Definition at line 23 of file CMakeLists.txt.
bin target_link_libraries (dualRXTX LimeSuite)
Definition at line 27 of file CMakeLists.txt.
bin target_link_libraries (gpio_example LimeSuite)
Definition at line 31 of file CMakeLists.txt.