LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/lms7002m_calibrations.h File Reference
lms7002m_calibrations.h File Reference
#include "typedefs.h"
Functions
int16_t ReadAnalogDC (const uint16_t addr)
void UpdateRSSIDelay ()
uint32_t GetRSSI ()
void LoadDC_REG_TX_IQ ()
uint8_t CalibrateTx (bool extLoopback)
uint8_t CalibrateTxExternalLoop ()
uint8_t CalibrateRx (bool extLoopback, bool dcOnly)
uint8_t CalibrateRxExternalLoop ()
void CalibrateRxDCAuto ()
uint8_t RunAGC (uint32_t wantedRSSI)
int16_t clamp (int16_t value, int16_t minBound, int16_t maxBound)
Function Documentation
uint8_t CalibrateRx (bool extLoopback, bool dcOnly)
Definition at line 1229 of file lms7002m_calibrations.c.
References bandwidthRF, CalibrateIQImbalance(), CalibrateRxDCAuto(), CalibrateRxSetup(), calibUserBwDivider, CheckSaturationRx(), CMIX_BYP_RXTSP, CMIX_SC_RXTSP, DCMODE, EN_INSHSW_LB1_RFE, EN_INSHSW_LB2_RFE, G_LNA_RFE, G_PGA_RBB, G_TIA_RFE, GCORRI_RXTSP, GCORRQ_RXTSP, Get_SPI_Reg_bits(), GetFrequencySX(), IQCORR_RXTSP, LMS7002M_Rx, MAC, MCU_NO_ERROR, MCU_PROCEDURE_DISABLED, Modify_SPI_Reg_bits(), MSB_LSB, offsetNCO, PD_DCDAC_RXA, PD_DCDAC_RXB, PD_LOCH_T2RBUF, PD_RLOOPB_1_RFE, PD_RLOOPB_2_RFE, PD_VCO, ReadAnalogDC(), SaveChipState(), SEL_PATH_RFE, SetNCOFrequency(), SPI_read(), SPI_write(), status, and UpdateRSSIDelay().
Referenced by DCIQ(), main(), and RunAGC().
void CalibrateRxDCAuto ()
Definition at line 412 of file lms7002m_calibrations.c.
References AdjustAutoDC(), DC_BYP_RXTSP, DCMODE, EN_G_TRF, GCORRQ_RXTSP, Get_SPI_Reg_bits(), GetRSSI(), MAC, Modify_SPI_Reg_bits(), PD_DCCMP_RXA, PD_DCCMP_RXB, PD_DCDAC_RXA, PD_DCDAC_RXB, ReadAnalogDC(), SPI_read(), and SPI_write().
Referenced by CalibrateRx(), and CalibrateTx().
uint8_t CalibrateRxExternalLoop ()
uint8_t CalibrateTx (bool extLoopback)
Definition at line 860 of file lms7002m_calibrations.c.
References bandwidthRF, CalibrateIQImbalance(), CalibrateRxDCAuto(), CalibrateTxDCAuto(), CalibrateTxSetup(), calibrationSXOffset_Hz, calibUserBwDivider, CG_IAMP_TBB, CheckSaturationTxRx(), DC_BYP_TXTSP, DCMODE, GCORRI_TXTSP, GCORRQ_TXTSP, Get_SPI_Reg_bits(), IQCORR_TXTSP, LMS7002M_Rx, LMS7002M_Tx, MCU_NO_ERROR, MCU_PROCEDURE_DISABLED, Modify_SPI_Reg_bits(), MSB_LSB, offsetNCO, PD_DCDAC_TXA, PD_DCDAC_TXB, ReadAnalogDC(), SaveChipState(), SEL_BAND1_TRF, SetNCOFrequency(), SPI_read(), SPI_write(), status, and UpdateRSSIDelay().
Referenced by DCIQ(), and main().
uint8_t CalibrateTxExternalLoop ()
int16_t clamp (int16_t value, int16_t minBound, int16_t maxBound)
Definition at line 85 of file lms7002m_calibrations.c.
Referenced by AdjustAutoDC(), CalibrateTxDCAuto(), ConfigCGEN_ForLPF_IF(), RunAGC(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), SetupCGEN(), TuneRxFilter(), TuneRxFilterSetup(), and TuneTxFilterSetup().
uint32_t GetRSSI ()
Definition at line 131 of file lms7002m_calibrations.c.
References CAPTURE, FlipRisingEdge(), RefClk, RSSIDelayCounter, SPI_read(), TF0, TH0, TL0, and TR0.
Referenced by AdjustAutoDC(), BinarySearch(), CalibrateIQImbalance(), CalibrateRxDCAuto(), CalibrateTxDCAuto(), ChangeUntilReachRSSI(), CheckSaturationRx(), CheckSaturationTxRx(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), TuneRxFilter(), and TxDcBinarySearch().
void LoadDC_REG_TX_IQ ()
Definition at line 107 of file lms7002m_calibrations.c.
References FlipRisingEdge(), RefClk, SPI_write(), TSGDCLDI_TXTSP, and TSGDCLDQ_TXTSP.
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
int16_t ReadAnalogDC (const uint16_t addr)
Definition at line 314 of file lms7002m_calibrations.c.
References SPI_read(), and SPI_write().
Referenced by AdjustAutoDC(), CalibrateRx(), CalibrateRxDCAuto(), CalibrateTx(), and CalibrateTxDCAuto().
uint8_t RunAGC (uint32_t wantedRSSI)
Definition at line 112 of file lms7002m_agc.c.
References AGC_BYP_RXTSP, AGC_gain_table, CalibrateRx(), CG_IAMP_TBB, CG_IAMP_TBB_R3, clamp(), ClockLogicResets(), CMIX_BYP_RXTSP, CMIX_GAIN_RXTSP, CMIX_GAIN_RXTSP_R3, GET_LNA_GAIN, GET_PGA_GAIN, Get_SPI_Reg_bits(), GetValueOf_c_ctl_pga_rbb(), hasStopped, ICT_TIAMAIN_RFE, ICT_TIAOUT_RFE, LOSS_LIN_TXPAD_TRF, LOSS_LIN_TXPAD_TRF_R3, LOSS_MAIN_TXPAD_TRF, LOSS_MAIN_TXPAD_TRF_R3, Modify_SPI_Reg_bits(), SPI_read(), SPI_write(), status, stopProcedure, StoreState(), TRX_GAIN_SRC, UpdateRSSIDelay(), and xdata.
Referenced by main().
void UpdateRSSIDelay ()
Definition at line 117 of file lms7002m_calibrations.c.
References AGC_AVG_RXTSP, Get_SPI_Reg_bits(), GetReferenceClk_TSP_MHz(), HBD_OVR_RXTSP, RefClk, and RSSIDelayCounter.
Referenced by CalibrateRx(), CalibrateTx(), RunAGC(), TuneRxFilter(), and TuneTxFilter().