LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/Registry.cpp File Reference
Registry.cpp File Reference
#include <SoapySDR/Registry.hpp>
Classes
struct FunctionsEntry
Typedefs
typedef std::map< std::string, FunctionsEntry > FunctionTable
Functions
static FunctionTable & getFunctionTable (void)
std::string & getModuleLoading (void)
share the module path during loadModule
std::map< std::string, SoapySDR::Kwargs > & getLoaderResults (void)
share registration errors during loadModule
Typedef Documentation
typedef std::map<std::string, FunctionsEntry> FunctionTable
Definition at line 16 of file Registry.cpp.
Function Documentation
static FunctionTable& getFunctionTable (void) static
Definition at line 18 of file Registry.cpp.
References getLoaderResults(), getModuleLoading(), and string().
Referenced by SoapySDR::Registry::listFindFunctions(), SoapySDR::Registry::listMakeFunctions(), SoapySDR::Registry::Registry(), and SoapySDR::Registry::~Registry().
std::map<std::string, SoapySDR::Kwargs>& getLoaderResults (void)
share registration errors during loadModule
Definition at line 187 of file Modules.cpp.
Referenced by getFunctionTable(), getModuleVersions(), and SoapySDR::Registry::Registry().
std::string& getModuleLoading (void)
share the module path during loadModule
Definition at line 180 of file Modules.cpp.
References string().
Referenced by getFunctionTable(), getModuleVersions(), and SoapySDR::Registry::Registry().