LimeSuite-UML: lime::LMS7_LimeSDR_mini Class Reference
lime::LMS7_LimeSDR_mini Class Reference
#include <LimeSDR_mini.h>
Public Member Functions
LMS7_LimeSDR_mini (lime::IConnection *conn, LMS7_Device *obj=nullptr)
int Init () override
int SetRate (bool tx, double f_Hz, unsigned oversample) override
int SetRate (double f_Hz, int oversample) override
unsigned GetNumChannels (const bool tx=false) const override
int SetFrequency (bool isTx, unsigned chan, double f_Hz) override
Range GetRxPathBand (unsigned path, unsigned chan) const override
Range GetTxPathBand (unsigned path, unsigned chan) const override
Range GetRateRange (bool dir=false, unsigned chan=0) const override
Range GetFrequencyRange (bool tx) const override
std::vector< std::string > GetPathNames (bool dir_tx, unsigned chan) const override
int SetPath (bool tx, unsigned chan, unsigned path) override
std::vector< std::string > GetProgramModes () const override
Public Member Functions inherited from lime::LMS7_Device
virtual ~LMS7_Device ()
LMS7_Device (LMS7_Device *obj=nullptr)
lime::IConnection * GetConnection (unsigned chan=0)
lime::FPGA * GetFPGA ()
virtual int EnableChannel (bool dir_tx, unsigned chan, bool enabled)
int Reset ()
virtual int SetRate (unsigned ch, double rxRate, double txRate, unsigned oversample=0)
int SetFPGAInterfaceFreq (int interp=-1, int dec=-1, double txPhase=999, double rxPhase=999)
virtual double GetRate (bool tx, unsigned chan, double *rf_rate_Hz=NULL) const
int GetPath (bool tx, unsigned chan) const
double GetFrequency (bool tx, unsigned chan) const
int SetLPF (bool tx, unsigned chan, bool en, double bandwidth=-1)
double GetLPFBW (bool tx, unsigned chan) const
Range GetLPFRange (bool tx, unsigned chan) const
int SetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, const double *coef, unsigned count)
int GetGFIRCoef (bool tx, unsigned chan, lms_gfir_t filt, double *coef) const
int SetGFIR (bool tx, unsigned chan, lms_gfir_t filt, bool enabled)
int SetGain (bool dir_tx, unsigned chan, double value, const std::string &name="")
double GetGain (bool dir_tx, unsigned chan, const std::string &name="") const
Range GetGainRange (bool dir_tx, unsigned chan, const std::string &name="") const
int SetTestSignal (bool dir_tx, unsigned chan, lms_testsig_t sig, int16_t dc_i=0, int16_t dc_q=0)
int GetTestSignal (bool dir_tx, unsigned chan) const
int SetNCOFreq (bool tx, unsigned ch, int ind, double freq)
double GetNCOFreq (bool tx, unsigned ch, int ind) const
int SetNCOPhase (bool tx, unsigned ch, int ind, double phase)
double GetNCOPhase (bool tx, unsigned ch, int ind) const
int Calibrate (bool dir_tx, unsigned chan, double bw, unsigned flags)
virtual int Program (const std::string &mode, const char *data, size_t len, lime::IConnection::ProgrammingCallback callback) const
double GetClockFreq (unsigned clk_id, int channel=-1) const
int SetClockFreq (unsigned clk_id, double freq, int channel=-1)
lms_dev_info_t * GetInfo ()
int Synchronize (bool toChip) const
int SetLogCallback (void(*func)(const char *cstr, const unsigned int type))
int EnableCalibCache (bool enable)
double GetChipTemperature (int ind=-1) const
int LoadConfig (const char *filename, int ind=-1)
int SaveConfig (const char *filename, int ind=-1) const
int ReadLMSReg (uint16_t address, int ind=-1) const
int WriteLMSReg (uint16_t address, uint16_t val, int ind=-1) const
uint16_t ReadParam (const struct LMS7Parameter &param, int channel=-1, bool forceReadFromChip=false) const
int ReadParam (const std::string &param, int channel=-1, bool forceReadFromChip=false) const
int WriteParam (const struct LMS7Parameter &param, uint16_t val, int channel=-1)
int WriteParam (const std::string &param, uint16_t val, int channel=-1)
int SetActiveChip (unsigned ind)
lime::LMS7002M * GetLMS (int index=-1) const
int UploadWFM (const void **samples, uint8_t chCount, int sample_count, lime::StreamConfig::StreamDataFormat fmt) const
int ConfigureGFIR (bool tx, unsigned ch, bool enabled, double bandwidth)
lime::StreamChannel * SetupStream (const lime::StreamConfig &config)
int DestroyStream (lime::StreamChannel *streamID)
uint64_t GetHardwareTimestamp (void) const
void SetHardwareTimestamp (const uint64_t now)
uint64_t GetChirpTimePeriod (void) const
uint64_t GetChirpTimeStamp (void) const
int MCU_AGCStart (uint32_t wantedRSSI)
int MCU_AGCStop ()
Additional Inherited Members
Static Public Member Functions inherited from lime::LMS7_Device
static LMS7_Device * CreateDevice (const lime::ConnectionHandle &handle, LMS7_Device *obj=nullptr)
static std::vector< lime::ConnectionHandle > GetDeviceList ()
Protected Member Functions inherited from lime::LMS7_Device
lime::LMS7002M * SelectChannel (unsigned chan) const
int ConfigureTXLPF (bool enabled, int ch, double bandwidth)
Protected Attributes inherited from lime::LMS7_Device
lms_dev_info_t devInfo
std::vector< ChannelInfo > tx_channels
std::vector< ChannelInfo > rx_channels
lime::IConnection * connection
std::vector< lime::LMS7002M * > lms_list
unsigned lms_chip_id
std::vector< lime::Streamer * > mStreamers
lime::FPGA * fpga
Detailed Description
Definition at line 14 of file LimeSDR_mini.h.
Constructor & Destructor Documentation
lime::LMS7_LimeSDR_mini::LMS7_LimeSDR_mini (lime::IConnection * conn, lime::LMS7_Device * obj = nullptr)
Definition at line 16 of file LimeSDR_mini.cpp.
References lime::LMS7_Device::connection, lime::FPGA::DetectRefClk(), lime::LMS7_Device::fpga, lime::LMS7_Device::lms_list, lime::LMS7_Device::mStreamers, and lime::FPGA::SetConnection().
Member Function Documentation
LMS7_Device::Range lime::LMS7_LimeSDR_mini::GetFrequencyRange (bool tx) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 277 of file LimeSDR_mini.cpp.
unsigned lime::LMS7_LimeSDR_mini::GetNumChannels (const bool tx = false) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 101 of file LimeSDR_mini.cpp.
std::vector< std::string > lime::LMS7_LimeSDR_mini::GetPathNames (bool dir_tx, unsigned chan) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 142 of file LimeSDR_mini.cpp.
std::vector< std::string > lime::LMS7_LimeSDR_mini::GetProgramModes () const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 265 of file LimeSDR_mini.cpp.
References lime::program_mode::autoUpdate, lime::program_mode::fpgaFlash, lime::program_mode::fpgaReset, lime::program_mode::mcuEEPROM, lime::program_mode::mcuRAM, and lime::program_mode::mcuReset.
LMS7_Device::Range lime::LMS7_LimeSDR_mini::GetRateRange (bool dir = false, unsigned chan = 0) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 272 of file LimeSDR_mini.cpp.
LMS7_Device::Range lime::LMS7_LimeSDR_mini::GetRxPathBand (unsigned path, unsigned chan) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 244 of file LimeSDR_mini.cpp.
References LMS_PATH_LNAH, and LMS_PATH_LNAW.
LMS7_Device::Range lime::LMS7_LimeSDR_mini::GetTxPathBand (unsigned path, unsigned chan) const override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 254 of file LimeSDR_mini.cpp.
References LMS_PATH_TX1, and LMS_PATH_TX2.
int lime::LMS7_LimeSDR_mini::Init () override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 32 of file LimeSDR_mini.cpp.
References lime::LMS7_Device::connection, lime::LMS7002M::EnableChannel(), i, lms(), LMS7param, lime::LMS7_Device::lms_list, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::IConnection::ReadRegister(), lime::LMS7002M::ResetChip(), SetFrequency(), SetRate(), lime::LMS7002M::SPI_write(), and val.
int lime::LMS7_LimeSDR_mini::SetFrequency (bool isTx, unsigned chan, double f_Hz) override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 106 of file LimeSDR_mini.cpp.
References lime::LMS7_Device::ChannelInfo::cF_offset_nco, lime::LMS7002M::EnableSXTDD(), lime::LMS7_Device::ChannelInfo::freq, lime::LMS7_Device::GetRate(), lms(), lime::LMS7_Device::lms_list, lime::LMS7_Device::rx_channels, lime::LMS7002M::SetFrequencySX(), lime::LMS7_Device::SetNCOFreq(), SetRate(), and lime::LMS7_Device::tx_channels.
Referenced by Init().
int lime::LMS7_LimeSDR_mini::SetPath (bool tx, unsigned chan, unsigned path) override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 150 of file LimeSDR_mini.cpp.
References lime::LMS7_Device::connection, EN_INSHSW_L_RFE, EN_INSHSW_W_RFE, lms(), LMS7param, lime::LMS7_Device::lms_list, LMS_PATH_LNAH, LMS_PATH_LNAL, LMS_PATH_LNAW, LMS_PATH_TX1, LMS_PATH_TX2, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::IConnection::ReadRegister(), SEL_BAND1_TRF, SEL_BAND2_TRF, SEL_PATH_RFE, lime::warning(), and lime::IConnection::WriteRegister().
int lime::LMS7_LimeSDR_mini::SetRate (bool tx, double f_Hz, unsigned oversample) override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 239 of file LimeSDR_mini.cpp.
Referenced by Init(), and SetFrequency().
int lime::LMS7_LimeSDR_mini::SetRate (double f_Hz, int oversample) override virtual
Reimplemented from lime::LMS7_Device.
Definition at line 205 of file LimeSDR_mini.cpp.
References lime::cgenMax, CLKH_OV_CLKL_CGEN, EN_ADCCLKH_CLKGN, lime::LMS7_Device::fpga, lime::LMS7002M::GetFrequencyCGEN(), lime::LMS7002M::GetReferenceClk_TSP(), lms(), LMS7_CDSN_RXALML, LMS7_LML1_SISODDR, LMS7_LML2_SISODDR, LMS7param, lime::LMS7_Device::lms_list, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::LMS7002M::Rx, lime::LMS7_Device::rx_channels, lime::LMS7002M::SetFrequencyCGEN(), lime::FPGA::SetInterfaceFreq(), lime::LMS7002M::SetInterfaceFrequency(), lime::LMS7_Device::SetRate(), lime::LMS7002M::Tx, and lime::LMS7_Device::tx_channels.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/API/LimeSDR_mini.h
/home/erik/prefix/default/src/limesuite-dev/src/API/LimeSDR_mini.cpp