LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/lms7002m/goertzel.h File Reference
goertzel.h File Reference
Namespaces
lime
GUI for writing and reading analog controls.
Functions
int SelectGoertzelBin (lime::IConnection *port, uint16_t bin, uint16_t samplesCount)
int CalculateGoertzelBin (lime::IConnection *dataPort, int64_t *real, int64_t *imag)
Function Documentation
int CalculateGoertzelBin (lime::IConnection * dataPort, int64_t * real, int64_t * imag)
Definition at line 325 of file goert.cpp.
References computeGoertzel(), cos_value, readGoertzelValues(), lime::ReportError(), sin_value, and status.
int SelectGoertzelBin (lime::IConnection * port, uint16_t bin, uint16_t samplesCount)
Definition at line 316 of file goert.cpp.
References cos_value, getGoertzelCoefficients(), loadGoertzelCoefficients(), sin_value, and status.