LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/VersionC.cpp File Reference
VersionC.cpp File Reference
#include <SoapySDR/Version.hpp>
Functions
const char * SoapySDR_getAPIVersion (void)
const char * SoapySDR_getABIVersion (void)
const char * SoapySDR_getLibVersion (void)
Function Documentation
const char* SoapySDR_getABIVersion (void)
Get the ABI version string that the library was built against. A client can compare SOAPY_SDR_ABI_VERSION to getABIVersion() to check for ABI incompatibility before using the library. If the values are not equal then the client code was compiled against a different ABI than the library.
Definition at line 14 of file VersionC.cpp.
References SoapySDR::getABIVersion, SoapySDR::SoapySDR_getABIVersion(), and string().
const char* SoapySDR_getAPIVersion (void)
Get the SoapySDR library API version as a string. The format of the version string is major.minor.increment, where the digits are taken directly from SOAPY_SDR_API_VERSION.
Definition at line 8 of file VersionC.cpp.
References SoapySDR::getAPIVersion, SoapySDR::SoapySDR_getAPIVersion(), and string().
const char* SoapySDR_getLibVersion (void)
Get the library version and build information string. The format of the version string is major.minor.patch-buildInfo. This function is commonly used to identify the software back-end to the user for command-line utilities and graphical applications.
Definition at line 20 of file VersionC.cpp.
References SoapySDR::getLibVersion, SoapySDR::SoapySDR_getLibVersion(), and string().