LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/lms7002m_agc.c File Reference
lms7002m_agc.c File Reference
#include "lms7002m_controls.h"
#include "spi.h"
#include "LMS7002M_parameters_compact.h"
#include "typedefs.h"
#include "mcu_defines.h"
#include "lms7002m_calibrations.h"
#include <math.h>
Macros
#define TABLE_ENTRY(gain_setting, gainLNA, gainPGA) (gainPGA << 4 | gainLNA)
#define GET_PGA_GAIN(value) ((value >> 4) & 0x1F)
#define GET_LNA_GAIN(value) ((value) & 0xF)
Functions
static void StoreState (bool write)
uint8_t RunAGC (uint32_t wantedRSSI)
Variables
bool hasStopped
bool stopProcedure
static uint16_t stateAddresses [] = {0x0081, 0x010F, 0x0126, 0x040A, 0x040C}
static uint16_t stateStorage [2 *sizeof(stateAddresses)/sizeof(uint16_t)]
static const uint16_t AGC_gain_table []
Macro Definition Documentation
#define GET_LNA_GAIN (value) ((value) & 0xF)
Definition at line 46 of file lms7002m_agc.c.
Referenced by RunAGC().
#define GET_PGA_GAIN (value) ((value >> 4) & 0x1F)
Definition at line 45 of file lms7002m_agc.c.
Referenced by RunAGC().
#define TABLE_ENTRY (gain_setting, gainLNA, gainPGA) (gainPGA << 4 | gainLNA)
Definition at line 44 of file lms7002m_agc.c.
Function Documentation
uint8_t RunAGC (uint32_t wantedRSSI)
Definition at line 112 of file lms7002m_agc.c.
References AGC_BYP_RXTSP, AGC_gain_table, CalibrateRx(), CG_IAMP_TBB, CG_IAMP_TBB_R3, clamp(), ClockLogicResets(), CMIX_BYP_RXTSP, CMIX_GAIN_RXTSP, CMIX_GAIN_RXTSP_R3, GET_LNA_GAIN, GET_PGA_GAIN, Get_SPI_Reg_bits(), GetValueOf_c_ctl_pga_rbb(), hasStopped, ICT_TIAMAIN_RFE, ICT_TIAOUT_RFE, LOSS_LIN_TXPAD_TRF, LOSS_LIN_TXPAD_TRF_R3, LOSS_MAIN_TXPAD_TRF, LOSS_MAIN_TXPAD_TRF_R3, Modify_SPI_Reg_bits(), SPI_read(), SPI_write(), status, stopProcedure, StoreState(), TRX_GAIN_SRC, UpdateRSSIDelay(), and xdata.
Referenced by main().
static void StoreState (bool write) static
Definition at line 23 of file lms7002m_agc.c.
References i, SPI_read(), SPI_write(), stateAddresses, and stateStorage.
Referenced by RunAGC().
Variable Documentation
const uint16_t AGC_gain_table[] static
Definition at line 47 of file lms7002m_agc.c.
Referenced by RunAGC().
bool hasStopped
Definition at line 11 of file main.c.
Referenced by main(), and RunAGC().
uint16_t stateAddresses[] = {0x0081, 0x010F, 0x0126, 0x040A, 0x040C} static
Definition at line 19 of file lms7002m_agc.c.
Referenced by StoreState().
uint16_t stateStorage[2 *sizeof(stateAddresses)/sizeof(uint16_t)] static
Definition at line 21 of file lms7002m_agc.c.
Referenced by StoreState().
bool stopProcedure
Definition at line 10 of file main.c.
Referenced by ext3_int(), main(), and RunAGC().