LimeSuite-UML: RFSpark_wxgui Class Reference
RFSpark_wxgui Class Reference
#include <RFSpark_wxgui.h>
Classes
struct ADCdata
struct ADCdataGUI
Public Member Functions
RFSpark_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=0)
virtual void Initialize (lms_device_t *pSerPort)
virtual ~RFSpark_wxgui ()
Protected Member Functions
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
Protected Attributes
std::vector< ADCdata > mADCdata
std::vector< ADCdataGUI > mADCgui
std::vector< wxCheckBox * > mGPIOboxes
lms_device_t * lmsControl
Static Protected Attributes
static const int mADCcount = 32
static const long ID_BTNREADADC = wxNewId()
static const long ID_BTNREADALLADC = wxNewId()
static const long ID_BTNWRITEGPIO = wxNewId()
static const long ID_BTNREADGPIO = wxNewId()
static const long ID_CMBSELECTADC = wxNewId()
Private Member Functions
void UpdateADClabels ()
void OnRefreshAllADC (wxCommandEvent &event)
void OnWriteGPIO (wxCommandEvent &event)
void OnReadGPIO (wxCommandEvent &event)
Detailed Description
Definition at line 19 of file RFSpark_wxgui.h.
Constructor & Destructor Documentation
RFSpark_wxgui::RFSpark_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = 0)
Definition at line 70 of file RFSpark_wxgui.cpp.
References _T, RFSpark_wxgui::ADCdata::channel, i, lmsControl, mADCcount, mADCdata, mADCgui, mGPIOboxes, OnReadAll(), OnWriteAll(), OnWriteGPIO(), RFSpark_wxgui::ADCdataGUI::title, RFSpark_wxgui::ADCdataGUI::units, RFSpark_wxgui::ADCdata::value, and RFSpark_wxgui::ADCdataGUI::value.
RFSpark_wxgui::~RFSpark_wxgui () virtual
Definition at line 170 of file RFSpark_wxgui.cpp.
Member Function Documentation
void RFSpark_wxgui::Initialize (lms_device_t * pSerPort) virtual
Definition at line 164 of file RFSpark_wxgui.cpp.
References lmsControl.
Referenced by pnlBoardControls::SetupControls().
void RFSpark_wxgui::OnReadAll (wxCommandEvent & event) protected
Definition at line 235 of file RFSpark_wxgui.cpp.
References OnReadGPIO(), and OnRefreshAllADC().
Referenced by RFSpark_wxgui().
void RFSpark_wxgui::OnReadGPIO (wxCommandEvent & event) private
Definition at line 217 of file RFSpark_wxgui.cpp.
References i, LMS_GPIORead(), lmsControl, and mGPIOboxes.
Referenced by OnReadAll().
void RFSpark_wxgui::OnRefreshAllADC (wxCommandEvent & event) private
Definition at line 184 of file RFSpark_wxgui.cpp.
References i, LMS_ReadCustomBoardParam(), lmsControl, mADCdata, units, UpdateADClabels(), and val.
Referenced by OnReadAll().
void RFSpark_wxgui::OnWriteAll (wxCommandEvent & event) protected
Definition at line 241 of file RFSpark_wxgui.cpp.
References OnWriteGPIO().
Referenced by RFSpark_wxgui().
void RFSpark_wxgui::OnWriteGPIO (wxCommandEvent & event) private
Definition at line 202 of file RFSpark_wxgui.cpp.
References i, LMS_GPIOWrite(), lmsControl, and mGPIOboxes.
Referenced by OnWriteAll(), and RFSpark_wxgui().
void RFSpark_wxgui::UpdateADClabels () private
Definition at line 175 of file RFSpark_wxgui.cpp.
References i, mADCdata, mADCgui, and units.
Referenced by OnRefreshAllADC().
Member Data Documentation
const long RFSpark_wxgui::ID_BTNREADADC = wxNewId() static protected
Definition at line 46 of file RFSpark_wxgui.h.
const long RFSpark_wxgui::ID_BTNREADALLADC = wxNewId() static protected
Definition at line 47 of file RFSpark_wxgui.h.
const long RFSpark_wxgui::ID_BTNREADGPIO = wxNewId() static protected
Definition at line 49 of file RFSpark_wxgui.h.
const long RFSpark_wxgui::ID_BTNWRITEGPIO = wxNewId() static protected
Definition at line 48 of file RFSpark_wxgui.h.
const long RFSpark_wxgui::ID_CMBSELECTADC = wxNewId() static protected
Definition at line 50 of file RFSpark_wxgui.h.
lms_device_t* RFSpark_wxgui::lmsControl protected
Definition at line 64 of file RFSpark_wxgui.h.
Referenced by Initialize(), OnReadGPIO(), OnRefreshAllADC(), OnWriteGPIO(), and RFSpark_wxgui().
const int RFSpark_wxgui::mADCcount = 32 static protected
Definition at line 45 of file RFSpark_wxgui.h.
Referenced by RFSpark_wxgui().
std::vector<ADCdata> RFSpark_wxgui::mADCdata protected
Definition at line 51 of file RFSpark_wxgui.h.
Referenced by OnRefreshAllADC(), RFSpark_wxgui(), and UpdateADClabels().
std::vector<ADCdataGUI> RFSpark_wxgui::mADCgui protected
Definition at line 52 of file RFSpark_wxgui.h.
Referenced by RFSpark_wxgui(), and UpdateADClabels().
std::vector<wxCheckBox*> RFSpark_wxgui::mGPIOboxes protected
Definition at line 53 of file RFSpark_wxgui.h.
Referenced by OnReadGPIO(), OnWriteGPIO(), and RFSpark_wxgui().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/RFSpark/RFSpark_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/RFSpark/RFSpark_wxgui.cpp