LimeSuite-UML: gr::radar::soapysdr_echotimer_stretch_impl Class Reference
gr::radar::soapysdr_echotimer_stretch_impl Class Reference
#include <soapysdr_echotimer_stretch_impl.h>
Public Member Functions
soapysdr_echotimer_stretch_impl (int samp_rate, float center_freq, int num_delay_samps, std::string args, std::string antenna_tx, float gain_tx, float bw_tx, float timeout_tx, float wait_tx, float lo_offset_tx, std::string antenna_rx, float gain_rx, float bw_rx, float timeout_rx, float wait_rx, float lo_offset_rx, const std::string &len_key)
~soapysdr_echotimer_stretch_impl ()
void send ()
void receive ()
void set_rx_gain (size_t chan, float gain)
void set_tx_gain (size_t chan, float gain)
int num_delay_samps ()
void set_num_delay_samps (int num_delay_samps)
float wait_rx ()
float wait_tx ()
void set_wait (float wait_rx, float wait_tx)
int work (int noutput_items, gr_vector_int &ninput_items, gr_vector_const_void_star &input_items, gr_vector_void_star &output_items)
Protected Member Functions
int calculate_output_stream_length (const gr_vector_int &ninput_items)
Private Attributes
volatile long long d_time_now_tx
volatile long long d_time_now_rx
volatile long long d_time_now_rx_HW
long long d_timeNs_tx
long long d_timeNs_rx
long long d_timeNs_rx_return
volatile long long d_wait_rx_TEST
long d_timeoutUs
pmt::pmt_t d_time_key
pmt::pmt_t d_time_val
pmt::pmt_t d_srcid
int d_num_delay_samps
std::string d_args
SoapySDR::Kwargs d_kw
int d_samp_rate
float d_center_freq
std::vector< std::string > d_listRegInterfaces
std::vector< std::string > d_GPIOBanks
volatile unsigned d_register
volatile unsigned d_value
volatile float d_time_packet
long long d_extra_work_time
int d_workNum
bool d_SendPacket
pmt::pmt_t DeadtimeKey = pmt::string_to_symbol("Deadtime")
volatile int firstPacket_Rx
volatile int firstPacket
int ERRORS
int Rx_Skip_Packets = 0
bool Chirp_Sync
std::vector< std::string > sensors
SoapySDR::Device * d_soapysdr_tx
SoapySDR::Device * d_soapysdr_rx
SoapySDR::Device * d_soapysdr
SoapySDR::Stream * d_tx_stream
SoapySDR::Stream * d_rx_stream
size_t d_chan_tx
size_t d_chan_rx
int d_flagsTx
int d_flagsRx
int d_flagsRx_return
float d_timeout_tx
float d_timeout_rx
float d_wait_tx
float d_wait_rx
double d_lo_offset_tx
double d_lo_offset_rx
std::string d_antenna_tx
std::string d_antenna_rx
float d_gain_tx
float d_gain_rx
float d_bw_tx
float d_bw_rx
volatile int d_num_rx_samps
volatile int d_num_tx_samps
gr::thread::thread d_thread_recv
gr_vector_void_star d_out_buffer
gr_complex * d_out_recv
int d_noutput_items_recv
gr::thread::thread d_thread_send
gr_vector_const_void_star d_in_buffer
int d_noutput_items_send
Additional Inherited Members
Public Types inherited from gr::radar::soapysdr_echotimer_stretch
typedef boost::shared_ptr< soapysdr_echotimer_stretch > sptr
Static Public Member Functions inherited from gr::radar::soapysdr_echotimer_stretch
static sptr make (int samp_rate, float center_freq, int num_delay_samps, std::string args="device args", std::string antenna_tx="BAND2", float gain_tx=0, float bw_tx=0, float timeout_tx=.1, float wait_tx=.001, float lo_offset_tx=0, std::string antenna_rx="LNAH", float gain_rx=0, float bw_rx=0, float timeout_rx=.1, float wait_rx=.001, float lo_offset_rx=0, const std::string &len_key="packet_len")
Return a shared_ptr to a new instance of radar::soapysdr_echotimer_stretch.
Detailed Description
Definition at line 41 of file soapysdr_echotimer_stretch_impl.h.
Constructor & Destructor Documentation
gr::radar::soapysdr_echotimer_stretch_impl::soapysdr_echotimer_stretch_impl (int samp_rate, float center_freq, int num_delay_samps, std::string args, std::string antenna_tx, float gain_tx, float bw_tx, float timeout_tx, float wait_tx, float lo_offset_tx, std::string antenna_rx, float gain_rx, float bw_rx, float timeout_rx, float wait_rx, float lo_offset_rx, const std::string & len_key)
Definition at line 55 of file soapysdr_echotimer_stretch_impl.cc.
References SoapySDR.Device::activateStream(), d_antenna_rx, d_antenna_tx, d_args, d_bw_rx, d_bw_tx, d_center_freq, d_chan_rx, d_chan_tx, d_extra_work_time, d_flagsRx_return, d_flagsTx, d_gain_rx, d_gain_tx, d_GPIOBanks, d_kw, d_listRegInterfaces, d_out_buffer, d_register, d_rx_stream, d_samp_rate, d_SendPacket, d_soapysdr, d_srcid, d_time_key, d_time_now_rx, d_time_now_tx, d_timeNs_rx, d_timeNs_rx_return, d_timeNs_tx, d_timeoutUs, d_tx_stream, d_value, d_workNum, firstPacket, firstPacket_Rx, SoapySDR.Device::getAntenna(), SoapySDR.Device::getBandwidth(), SoapySDR.Device::getDriverKey(), SoapySDR.Device::getFrequency(), SoapySDR.Device::getHardwareInfo(), SoapySDR.Device::getHardwareKey(), SoapySDR.Device::getMasterClockRate(), SoapySDR.Device::getNumChannels(), SoapySDR.Device::getSampleRate(), SoapySDR.Device::getStreamArgsInfo(), SoapySDR.Device::getStreamFormats(), SoapySDR.Device::hasHardwareTime(), i, SoapySDR::KwargsFromString, SoapySDR::KwargsToString, SoapySDR.Device::listGPIOBanks(), SoapySDR.Device::listRegisterInterfaces(), SoapySDR.Device::listSensors(), SoapySDR.Device::make, SoapySDR.Device::readRegister(), sensors, set_rx_gain(), set_tx_gain(), SoapySDR.Device::setAntenna(), SoapySDR.Device::setBandwidth(), SoapySDR.Device::setFrequency(), SoapySDR.Device::setHardwareTime(), SoapySDR.Device::setSampleRate(), SoapySDR.Device::setupStream(), sleep(), SOAPY_SDR_HAS_TIME, SOAPY_SDR_RX, SOAPY_SDR_TX, SoapySDR.Device::writeGPIO(), SoapySDR.Device::writeGPIODir(), and SoapySDR.Device::writeRegister().
gr::radar::soapysdr_echotimer_stretch_impl::~soapysdr_echotimer_stretch_impl ()
Definition at line 290 of file soapysdr_echotimer_stretch_impl.cc.
References SoapySDR.Device::closeStream(), d_listRegInterfaces, d_rx_stream, d_soapysdr, d_tx_stream, SoapySDR.Device::deactivateStream(), and SoapySDR.Device::writeRegister().
Member Function Documentation
int gr::radar::soapysdr_echotimer_stretch_impl::calculate_output_stream_length (const gr_vector_int & ninput_items) protected
Definition at line 300 of file soapysdr_echotimer_stretch_impl.cc.
int gr::radar::soapysdr_echotimer_stretch_impl::num_delay_samps () inline
Definition at line 129 of file soapysdr_echotimer_stretch_impl.h.
References d_num_delay_samps.
Referenced by set_num_delay_samps().
void gr::radar::soapysdr_echotimer_stretch_impl::receive ()
Definition at line 366 of file soapysdr_echotimer_stretch_impl.cc.
References SoapySDR.Device::activateStream(), d_flagsRx, d_noutput_items_recv, d_num_rx_samps, d_out_buffer, d_rx_stream, d_soapysdr, d_time_now_rx, d_timeNs_rx, d_timeNs_rx_return, d_timeout_rx, d_timeoutUs, d_wait_rx, SoapySDR.Device::readStream(), SOAPY_SDR_END_BURST, and SOAPY_SDR_HAS_TIME.
void gr::radar::soapysdr_echotimer_stretch_impl::send ()
Definition at line 323 of file soapysdr_echotimer_stretch_impl.cc.
References d_flagsTx, d_in_buffer, d_noutput_items_send, d_num_tx_samps, d_soapysdr, d_time_now_tx, d_timeNs_tx, d_timeout_tx, d_timeoutUs, d_tx_stream, d_wait_tx, SOAPY_SDR_END_BURST, SOAPY_SDR_HAS_TIME, and SoapySDR.Device::writeStream().
void gr::radar::soapysdr_echotimer_stretch_impl::set_num_delay_samps (int num_delay_samps) inline
Definition at line 130 of file soapysdr_echotimer_stretch_impl.h.
References num_delay_samps().
void gr::radar::soapysdr_echotimer_stretch_impl::set_rx_gain (size_t chan, float gain)
Definition at line 307 of file soapysdr_echotimer_stretch_impl.cc.
References d_soapysdr, SoapySDR.Device::getGain(), SoapySDR.Device::setGain(), and SOAPY_SDR_RX.
Referenced by soapysdr_echotimer_stretch_impl().
void gr::radar::soapysdr_echotimer_stretch_impl::set_tx_gain (size_t chan, float gain)
Definition at line 315 of file soapysdr_echotimer_stretch_impl.cc.
References d_soapysdr, SoapySDR.Device::getGain(), SoapySDR.Device::setGain(), and SOAPY_SDR_TX.
Referenced by soapysdr_echotimer_stretch_impl().
void gr::radar::soapysdr_echotimer_stretch_impl::set_wait (float wait_rx, float wait_tx) inline
Definition at line 134 of file soapysdr_echotimer_stretch_impl.h.
References wait_rx(), wait_tx(), and work().
float gr::radar::soapysdr_echotimer_stretch_impl::wait_rx () inline
Definition at line 132 of file soapysdr_echotimer_stretch_impl.h.
References d_wait_rx.
Referenced by set_wait().
float gr::radar::soapysdr_echotimer_stretch_impl::wait_tx () inline
Definition at line 133 of file soapysdr_echotimer_stretch_impl.h.
References d_wait_tx.
Referenced by set_wait().
int gr::radar::soapysdr_echotimer_stretch_impl::work (int noutput_items, gr_vector_int & ninput_items, gr_vector_const_void_star & input_items, gr_vector_void_star & output_items)
Definition at line 389 of file soapysdr_echotimer_stretch_impl.cc.
References Chirp_Sync, d_GPIOBanks, d_in_buffer, d_noutput_items_recv, d_noutput_items_send, d_num_delay_samps, d_out_buffer, d_out_recv, d_samp_rate, d_SendPacket, d_soapysdr, d_srcid, d_thread_recv, d_thread_send, d_time_key, d_time_now_rx, d_time_now_tx, d_time_packet, d_time_val, DeadtimeKey, firstPacket, firstPacket_Rx, SoapySDR.Device::getHardwareTime(), SoapySDR.Device::readGPIO(), SoapySDR.Device::readSensor(), and Rx_Skip_Packets.
Referenced by set_wait().
Member Data Documentation
bool gr::radar::soapysdr_echotimer_stretch_impl::Chirp_Sync private
Definition at line 75 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
std::string gr::radar::soapysdr_echotimer_stretch_impl::d_antenna_rx private
Definition at line 90 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
std::string gr::radar::soapysdr_echotimer_stretch_impl::d_antenna_tx private
Definition at line 90 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
std::string gr::radar::soapysdr_echotimer_stretch_impl::d_args private
Definition at line 57 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
float gr::radar::soapysdr_echotimer_stretch_impl::d_bw_rx private
Definition at line 92 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
float gr::radar::soapysdr_echotimer_stretch_impl::d_bw_tx private
Definition at line 92 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
float gr::radar::soapysdr_echotimer_stretch_impl::d_center_freq private
Definition at line 60 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
size_t gr::radar::soapysdr_echotimer_stretch_impl::d_chan_rx private
Definition at line 84 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
size_t gr::radar::soapysdr_echotimer_stretch_impl::d_chan_tx private
Definition at line 84 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
long long gr::radar::soapysdr_echotimer_stretch_impl::d_extra_work_time private
Definition at line 67 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
int gr::radar::soapysdr_echotimer_stretch_impl::d_flagsRx private
Definition at line 85 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive().
int gr::radar::soapysdr_echotimer_stretch_impl::d_flagsRx_return private
Definition at line 85 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
int gr::radar::soapysdr_echotimer_stretch_impl::d_flagsTx private
Definition at line 85 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send(), and soapysdr_echotimer_stretch_impl().
float gr::radar::soapysdr_echotimer_stretch_impl::d_gain_rx private
Definition at line 91 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
float gr::radar::soapysdr_echotimer_stretch_impl::d_gain_tx private
Definition at line 91 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
std::vector<std::string> gr::radar::soapysdr_echotimer_stretch_impl::d_GPIOBanks private
Definition at line 63 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and work().
gr_vector_const_void_star gr::radar::soapysdr_echotimer_stretch_impl::d_in_buffer private
Definition at line 105 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send(), and work().
SoapySDR::Kwargs gr::radar::soapysdr_echotimer_stretch_impl::d_kw private
Definition at line 58 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
std::vector<std::string> gr::radar::soapysdr_echotimer_stretch_impl::d_listRegInterfaces private
Definition at line 62 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and ~soapysdr_echotimer_stretch_impl().
double gr::radar::soapysdr_echotimer_stretch_impl::d_lo_offset_rx private
Definition at line 89 of file soapysdr_echotimer_stretch_impl.h.
double gr::radar::soapysdr_echotimer_stretch_impl::d_lo_offset_tx private
Definition at line 89 of file soapysdr_echotimer_stretch_impl.h.
int gr::radar::soapysdr_echotimer_stretch_impl::d_noutput_items_recv private
Definition at line 101 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), and work().
int gr::radar::soapysdr_echotimer_stretch_impl::d_noutput_items_send private
Definition at line 106 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send(), and work().
int gr::radar::soapysdr_echotimer_stretch_impl::d_num_delay_samps private
Definition at line 55 of file soapysdr_echotimer_stretch_impl.h.
Referenced by num_delay_samps(), and work().
volatile int gr::radar::soapysdr_echotimer_stretch_impl::d_num_rx_samps private
Definition at line 94 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive().
volatile int gr::radar::soapysdr_echotimer_stretch_impl::d_num_tx_samps private
Definition at line 94 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send().
gr_vector_void_star gr::radar::soapysdr_echotimer_stretch_impl::d_out_buffer private
Definition at line 98 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), soapysdr_echotimer_stretch_impl(), and work().
gr_complex* gr::radar::soapysdr_echotimer_stretch_impl::d_out_recv private
Definition at line 100 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
volatile unsigned gr::radar::soapysdr_echotimer_stretch_impl::d_register private
Definition at line 64 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
SoapySDR::Stream * gr::radar::soapysdr_echotimer_stretch_impl::d_rx_stream private
Definition at line 82 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), soapysdr_echotimer_stretch_impl(), and ~soapysdr_echotimer_stretch_impl().
int gr::radar::soapysdr_echotimer_stretch_impl::d_samp_rate private
Definition at line 59 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and work().
bool gr::radar::soapysdr_echotimer_stretch_impl::d_SendPacket private
Definition at line 69 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and work().
SoapySDR::Device * gr::radar::soapysdr_echotimer_stretch_impl::d_soapysdr private
Definition at line 81 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), send(), set_rx_gain(), set_tx_gain(), soapysdr_echotimer_stretch_impl(), work(), and ~soapysdr_echotimer_stretch_impl().
SoapySDR::Device * gr::radar::soapysdr_echotimer_stretch_impl::d_soapysdr_rx private
Definition at line 81 of file soapysdr_echotimer_stretch_impl.h.
SoapySDR::Device* gr::radar::soapysdr_echotimer_stretch_impl::d_soapysdr_tx private
Definition at line 81 of file soapysdr_echotimer_stretch_impl.h.
pmt::pmt_t gr::radar::soapysdr_echotimer_stretch_impl::d_srcid private
Definition at line 53 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and work().
gr::thread::thread gr::radar::soapysdr_echotimer_stretch_impl::d_thread_recv private
Definition at line 97 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
gr::thread::thread gr::radar::soapysdr_echotimer_stretch_impl::d_thread_send private
Definition at line 104 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
pmt::pmt_t gr::radar::soapysdr_echotimer_stretch_impl::d_time_key private
Definition at line 53 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and work().
volatile long long gr::radar::soapysdr_echotimer_stretch_impl::d_time_now_rx private
Definition at line 48 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), soapysdr_echotimer_stretch_impl(), and work().
volatile long long gr::radar::soapysdr_echotimer_stretch_impl::d_time_now_rx_HW private
Definition at line 48 of file soapysdr_echotimer_stretch_impl.h.
volatile long long gr::radar::soapysdr_echotimer_stretch_impl::d_time_now_tx private
Definition at line 48 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send(), soapysdr_echotimer_stretch_impl(), and work().
volatile float gr::radar::soapysdr_echotimer_stretch_impl::d_time_packet private
Definition at line 66 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
pmt::pmt_t gr::radar::soapysdr_echotimer_stretch_impl::d_time_val private
Definition at line 53 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
long long gr::radar::soapysdr_echotimer_stretch_impl::d_timeNs_rx private
Definition at line 49 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), and soapysdr_echotimer_stretch_impl().
long long gr::radar::soapysdr_echotimer_stretch_impl::d_timeNs_rx_return private
Definition at line 50 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), and soapysdr_echotimer_stretch_impl().
long long gr::radar::soapysdr_echotimer_stretch_impl::d_timeNs_tx private
Definition at line 49 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send(), and soapysdr_echotimer_stretch_impl().
float gr::radar::soapysdr_echotimer_stretch_impl::d_timeout_rx private
Definition at line 87 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive().
float gr::radar::soapysdr_echotimer_stretch_impl::d_timeout_tx private
Definition at line 87 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send().
long gr::radar::soapysdr_echotimer_stretch_impl::d_timeoutUs private
Definition at line 52 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), send(), and soapysdr_echotimer_stretch_impl().
SoapySDR::Stream* gr::radar::soapysdr_echotimer_stretch_impl::d_tx_stream private
Definition at line 82 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send(), soapysdr_echotimer_stretch_impl(), and ~soapysdr_echotimer_stretch_impl().
volatile unsigned gr::radar::soapysdr_echotimer_stretch_impl::d_value private
Definition at line 65 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
float gr::radar::soapysdr_echotimer_stretch_impl::d_wait_rx private
Definition at line 88 of file soapysdr_echotimer_stretch_impl.h.
Referenced by receive(), and wait_rx().
volatile long long gr::radar::soapysdr_echotimer_stretch_impl::d_wait_rx_TEST private
Definition at line 51 of file soapysdr_echotimer_stretch_impl.h.
float gr::radar::soapysdr_echotimer_stretch_impl::d_wait_tx private
Definition at line 88 of file soapysdr_echotimer_stretch_impl.h.
Referenced by send(), and wait_tx().
int gr::radar::soapysdr_echotimer_stretch_impl::d_workNum private
Definition at line 68 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
pmt::pmt_t gr::radar::soapysdr_echotimer_stretch_impl::DeadtimeKey = pmt::string_to_symbol("Deadtime") private
Definition at line 70 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
int gr::radar::soapysdr_echotimer_stretch_impl::ERRORS private
Definition at line 73 of file soapysdr_echotimer_stretch_impl.h.
volatile int gr::radar::soapysdr_echotimer_stretch_impl::firstPacket private
Definition at line 72 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and work().
volatile int gr::radar::soapysdr_echotimer_stretch_impl::firstPacket_Rx private
Definition at line 71 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl(), and work().
int gr::radar::soapysdr_echotimer_stretch_impl::Rx_Skip_Packets = 0 private
Definition at line 74 of file soapysdr_echotimer_stretch_impl.h.
Referenced by work().
std::vector<std::string> gr::radar::soapysdr_echotimer_stretch_impl::sensors private
Definition at line 76 of file soapysdr_echotimer_stretch_impl.h.
Referenced by soapysdr_echotimer_stretch_impl().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/gr-radar-dev/lib/soapysdr_echotimer_stretch_impl.h
/home/erik/prefix/default/src/gr-radar-dev/lib/soapysdr_echotimer_stretch_impl.cc