LimeSuite-UML: LimeSDRTest Class Reference
LimeSDRTest Class Reference abstract
#include <LimeSDRTest.h>
Classes
struct RFTestData
Static Public Member Functions
static int RunTests (TestCallback cb, bool nonblock=true)
static int CheckDevice (std::string &str)
Protected Member Functions
LimeSDRTest (lime::LMS7_Device *dev)
virtual ~LimeSDRTest ()
int InitFPGATest (unsigned test, double timeout)
int GPIFClkTest ()
int VCTCXOTest ()
bool RunTest (float &peakval, float &peakFreq, int ch=0)
Static Protected Member Functions
static void UpdateStatus (int event, const char *msg=nullptr)
static std::string RFTestInfo (const RFTestData &data, bool passed)
Protected Attributes
lime::LMS7_Device * device
Private Types
typedef std::function< int(int testID, int event, const char *msg)> TestCallback
Private Member Functions
int FPGA_EEPROM_Test ()
virtual int ClockNetworkTest ()=0
virtual int RFTest ()=0
int LMS7002mTest ()
int Reg_write (uint16_t address, uint16_t data)
uint16_t Reg_read (uint16_t address)
int Perform_tests ()
int TransferLMS64C (unsigned char *packet)
Static Private Member Functions
static LimeSDRTest * Connect ()
static void OnLogEvent (const lime::LogLevel level, const char *message)
Static Private Attributes
static int step = 0
static TestCallback callback = nullptr
static std::atomic< bool > running
static std::chrono::steady_clock::time_point tp_start
Detailed Description
Definition at line 29 of file LimeSDRTest.h.
Member Typedef Documentation
typedef std::function<int(int testID, int event, const char* msg)> LimeSDRTest::TestCallback private
Definition at line 31 of file LimeSDRTest.h.
Constructor & Destructor Documentation
LimeSDRTest::LimeSDRTest (lime::LMS7_Device * dev) protected
Definition at line 21 of file LimeSDRTest.cpp.
References device.
LimeSDRTest::~LimeSDRTest () protected virtual
Definition at line 27 of file LimeSDRTest.cpp.
References device.
Member Function Documentation
int LimeSDRTest::CheckDevice (std::string & str) static
Definition at line 493 of file LimeSDRTest.cpp.
References lime::LMS7_Device::GetDeviceList().
virtual int LimeSDRTest::ClockNetworkTest () private pure virtual
Implemented in LimeSDRTest_USB, and LimeSDRTest_Mini.
Referenced by LimeSDRTest_Mini::LimeSDRTest_Mini(), and LimeSDRTest_USB::LimeSDRTest_USB().
LimeSDRTest * LimeSDRTest::Connect () static private
Definition at line 48 of file LimeSDRTest.cpp.
References lime::LMS7_Device::CreateDevice(), lime::LMS7_Device::GetDeviceList(), lime::GetDeviceName(), lime::info(), lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDRMINI, LMS_TEST_FAIL, LMS_TEST_INFO, LMS_TEST_LOGFILE, and string().
int LimeSDRTest::FPGA_EEPROM_Test () private
Definition at line 115 of file LimeSDRTest.cpp.
References lime::CMD_MEMORY_RD, and LMS_TEST_INFO.
int LimeSDRTest::GPIFClkTest () protected
Definition at line 217 of file LimeSDRTest.cpp.
References device, LMS_TEST_INFO, and string().
Referenced by LimeSDRTest_Mini::ClockNetworkTest(), and LimeSDRTest_USB::ClockNetworkTest().
int LimeSDRTest::InitFPGATest (unsigned test, double timeout) protected
Definition at line 181 of file LimeSDRTest.cpp.
References device, LMS_TEST_INFO, and string().
Referenced by LimeSDRTest_USB::ADF4002Test(), and LimeSDRTest_USB::Si5351CTest().
int LimeSDRTest::LMS7002mTest () private
Definition at line 138 of file LimeSDRTest.cpp.
References device, LMS_TEST_INFO, lmsControl, lime::LMS7002M::RegistersTest(), lime::LMS7002M::ResetChip(), lime::LMS7002M::SPI_read(), lime::LMS7002M::SPI_write(), status, and val.
void LimeSDRTest::OnLogEvent (const lime::LogLevel level, const char * message) static private
Definition at line 42 of file LimeSDRTest.cpp.
References LMS_TEST_INFO.
Referenced by RunTests().
int LimeSDRTest::Perform_tests () private
Definition at line 413 of file LimeSDRTest.cpp.
References callback, LMS_TEST_FAIL, LMS_TEST_INFO, LMS_TEST_SUCCESS, status, and string().
Referenced by RunTests().
uint16_t LimeSDRTest::Reg_read (uint16_t address) private
Definition at line 304 of file LimeSDRTest.cpp.
References device, and status.
int LimeSDRTest::Reg_write (uint16_t address, uint16_t data) private
Definition at line 295 of file LimeSDRTest.cpp.
References device, and status.
virtual int LimeSDRTest::RFTest () private pure virtual
Implemented in LimeSDRTest_USB, and LimeSDRTest_Mini.
Referenced by LimeSDRTest_Mini::LimeSDRTest_Mini(), and LimeSDRTest_USB::LimeSDRTest_USB().
std::string LimeSDRTest::RFTestInfo (const RFTestData & data, bool passed) static protected
Definition at line 401 of file LimeSDRTest.cpp.
References buffer, LimeSDRTest::RFTestData::ch, LimeSDRTest::RFTestData::peakfreq, LimeSDRTest::RFTestData::peakval, LimeSDRTest::RFTestData::rxfreq, string(), and LimeSDRTest::RFTestData::txfreq.
Referenced by LimeSDRTest_Mini::RFTest(), and LimeSDRTest_USB::RFTest().
bool LimeSDRTest::RunTest (float & peakval, float & peakFreq, int ch = 0) protected
Definition at line 317 of file LimeSDRTest.cpp.
References device, i, kiss_fft_cpx::i, kiss_fft(), kiss_fft_alloc(), LMS7_LML1_SISODDR, LMS_TEST_INFO, swig_doc::output, calc_fmcw_peaks::r, and kiss_fft_cpx::r.
Referenced by LimeSDRTest_Mini::RFTest(), and LimeSDRTest_USB::RFTest().
int LimeSDRTest::RunTests (TestCallback cb, bool nonblock = true) static
Definition at line 460 of file LimeSDRTest.cpp.
References callback, LMS_TEST_FAIL, LMS_TEST_INFO, OnLogEvent(), Perform_tests(), lime::registerLogHandler(), and string().
Referenced by main().
int LimeSDRTest::TransferLMS64C (unsigned char * packet) private
Definition at line 91 of file LimeSDRTest.cpp.
References device, LMS_TEST_FAIL, stream, and string().
void LimeSDRTest::UpdateStatus (int event, const char * msg = nullptr) static protected
Definition at line 36 of file LimeSDRTest.cpp.
References callback.
Referenced by LimeSDRTest_USB::ADF4002Test(), LimeSDRTest_Mini::ClockNetworkTest(), LimeSDRTest_USB::ClockNetworkTest(), LimeSDRTest_Mini::RFTest(), LimeSDRTest_USB::RFTest(), and LimeSDRTest_USB::Si5351CTest().
int LimeSDRTest::VCTCXOTest () protected
Definition at line 240 of file LimeSDRTest.cpp.
References device, id, LMS_TEST_INFO, string(), units, and val.
Referenced by LimeSDRTest_Mini::ClockNetworkTest(), and LimeSDRTest_USB::ClockNetworkTest().
Member Data Documentation
LimeSDRTest::TestCallback LimeSDRTest::callback = nullptr static private
Definition at line 69 of file LimeSDRTest.h.
lime::LMS7_Device* LimeSDRTest::device protected
Definition at line 56 of file LimeSDRTest.h.
std::atomic< bool > LimeSDRTest::running static private
Definition at line 73 of file LimeSDRTest.h.
int LimeSDRTest::step = 0 static private
Definition at line 68 of file LimeSDRTest.h.
Referenced by SoapySDR.Range::__str__().
std::chrono::steady_clock::time_point LimeSDRTest::tp_start static private
Definition at line 74 of file LimeSDRTest.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/QuickTest/LimeSDRTest.h
/home/erik/prefix/default/src/limesuite-dev/QuickTest/LimeSDRTest.cpp