LimeSuite-UML: lime::Si5351C Class Reference
lime::Si5351C Class Reference
#include <Si5351C.h>
Classes
struct StatusBits
Public Types
enum Status { SUCCESS, FAILED }
Public Member Functions
StatusBits GetStatusBits ()
Status ClearStatus ()
Si5351C ()
~Si5351C ()
void Initialize (IConnection *mng)
Sets connection manager to use for data transferring Si5351C.
bool LoadRegValuesFromFile (std::string FName)
Loads register values for Si5356A from file.
void SetPLL (unsigned char id, unsigned long CLKIN_Hz, int CLK_SRC)
Sets PLL input frequency.
void SetClock (unsigned char id, unsigned long fOut_Hz, bool enabled=true, bool inverted=false)
Sets output clock parameters.
Status UploadConfiguration ()
Sends Configuration to Si5351C.
Status ConfigureClocks ()
Modifies register map with clock settings.
void Reset ()
Resets configuration registers to default values.
Private Member Functions
void FindVCO (Si5351_Channel *clocks, Si5351_PLL *plls, const unsigned long Fmin, const unsigned long Fmax)
Calculates multisynth dividers and VCO frequencies.
Private Attributes
IConnection * device
int addrSi5351
Si5351_PLL PLL [2]
Si5351_Channel CLK [8]
unsigned char m_newConfiguration [255]
Static Private Attributes
static const unsigned char m_defaultConfiguration []
Default configuration.
Detailed Description
Definition at line 48 of file Si5351C.h.
Member Enumeration Documentation
enum lime::Si5351C::Status
Enumerator
SUCCESS
FAILED
Definition at line 51 of file Si5351C.h.
Constructor & Destructor Documentation
Si5351C::Si5351C ()
Definition at line 279 of file Si5351C.cpp.
References device, and i.
Si5351C::~Si5351C ()
Definition at line 290 of file Si5351C.cpp.
Member Function Documentation
Si5351C::Status Si5351C::ClearStatus ()
Definition at line 844 of file Si5351C.cpp.
References device, and status.
Referenced by Si5351C_wxgui::OnbtnClearStatusClick().
Si5351C::Status Si5351C::ConfigureClocks ()
Modifies register map with clock settings.
Returns
true if success
Definition at line 626 of file Si5351C.cpp.
References lime::error(), i, lime::info(), and realToFrac().
Referenced by Si5351C_wxgui::OnbtnConfigureClockClick().
void Si5351C::FindVCO (Si5351_Channel * clocks, Si5351_PLL * plls, const unsigned long Fmin, const unsigned long Fmax) private
Calculates multisynth dividers and VCO frequencies.
Parameters
clocks output clocks configuration
plls plls configurations
Fmin lowest VCO frequency
Fmax highest VCO frequency
Definition at line 385 of file Si5351C.cpp.
References lime::Si5351_PLL::feedbackDivider, freq, i, lime::Si5351_Channel::int_mode, lime::Si5351_Channel::multisynthDivider, lime::Si5351_Channel::outputFreqHz, lime::Si5351_Channel::pllSource, lime::Si5351_Channel::powered, and lime::Si5351_PLL::VCO_Hz.
Si5351C::StatusBits Si5351C::GetStatusBits ()
Definition at line 818 of file Si5351C.cpp.
References device, lime::Si5351C::StatusBits::lol_a, lime::Si5351C::StatusBits::lol_a_stky, lime::Si5351C::StatusBits::lol_b, lime::Si5351C::StatusBits::lol_b_stky, lime::Si5351C::StatusBits::los, lime::Si5351C::StatusBits::los_stky, status, lime::Si5351C::StatusBits::sys_init, and lime::Si5351C::StatusBits::sys_init_stky.
Referenced by Si5351C_wxgui::OnbtnReadStatusClick().
void Si5351C::Initialize (IConnection * mng)
Sets connection manager to use for data transferring Si5351C.
Parameters
mng connection manager for data transferring
Definition at line 342 of file Si5351C.cpp.
References device.
Referenced by Si5351C_wxgui::OnbtnClearStatusClick(), Si5351C_wxgui::OnbtnConfigureClockClick(), Si5351C_wxgui::OnbtnLoadFileClick(), Si5351C_wxgui::OnbtnReadStatusClick(), and Si5351C_wxgui::OnbtnResetToDefaultsClick().
bool Si5351C::LoadRegValuesFromFile (std::string FName)
Loads register values for Si5356A from file.
Parameters
FName input filename
Definition at line 353 of file Si5351C.cpp.
References len.
Referenced by Si5351C_wxgui::OnbtnLoadFileClick().
void Si5351C::Reset ()
Resets configuration registers to default values.
Definition at line 809 of file Si5351C.cpp.
References i.
Referenced by Si5351C_wxgui::OnbtnResetToDefaultsClick().
void Si5351C::SetClock (unsigned char id, unsigned long fOut_Hz, bool enabled = true, bool inverted = false)
Sets output clock parameters.
Parameters
id clock id 0-CLK0 1-CLK1 ...
fOut_Hz output frequency in Hz
enabled is this output powered
inverted invert clock
Definition at line 779 of file Si5351C.cpp.
References enabled, lime::error(), and id.
Referenced by Si5351C_wxgui::OnbtnConfigureClockClick().
void Si5351C::SetPLL (unsigned char id, unsigned long CLKIN_Hz, int CLK_SRC)
Sets PLL input frequency.
Parameters
id PLL id 0-PLLA 1-PLLB
CLKIN_Hz clock input in Hz
Definition at line 798 of file Si5351C.cpp.
References id.
Referenced by Si5351C_wxgui::OnbtnConfigureClockClick().
Si5351C::Status Si5351C::UploadConfiguration ()
Sends Configuration to Si5351C.
Definition at line 297 of file Si5351C.cpp.
References device, i, and status.
Referenced by Si5351C_wxgui::OnbtnConfigureClockClick(), Si5351C_wxgui::OnbtnLoadFileClick(), and Si5351C_wxgui::OnbtnResetToDefaultsClick().
Member Data Documentation
int lime::Si5351C::addrSi5351 private
Definition at line 91 of file Si5351C.h.
Si5351_Channel lime::Si5351C::CLK[8] private
Definition at line 94 of file Si5351C.h.
IConnection* lime::Si5351C::device private
Definition at line 90 of file Si5351C.h.
const unsigned char Si5351C::m_defaultConfiguration static private
Default configuration.
Definition at line 96 of file Si5351C.h.
unsigned char lime::Si5351C::m_newConfiguration[255] private
Definition at line 97 of file Si5351C.h.
Si5351_PLL lime::Si5351C::PLL[2] private
Definition at line 93 of file Si5351C.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/Si5351C/Si5351C.h
/home/erik/prefix/default/src/limesuite-dev/src/Si5351C/Si5351C.cpp