LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/build/lib/Modules.cpp File Reference
Modules.cpp File Reference
#include <SoapySDR/Modules.hpp>
#include <SoapySDR/Logger.hpp>
#include <SoapySDR/Version.hpp>
#include <vector>
#include <string>
#include <cstdlib>
#include <sstream>
#include <map>
#include <dlfcn.h>
#include <glob.h>
Functions
std::string getEnvImpl (const char *name)
static std::vector< std::string > searchModulePath (const std::string &path)
std::map< std::string, void * > & getModuleHandles (void)
std::string & getModuleLoading (void)
share the module path during loadModule
std::map< std::string, SoapySDR::Kwargs > & getLoaderResults (void)
share registration errors during loadModule
std::map< std::string, std::string > & getModuleVersions (void)
void lateLoadNullDevice (void)
Function Documentation
std::string getEnvImpl (const char * name)
Definition at line 23 of file Modules.cpp.
Referenced by getEnvImpl(), and searchModulePath().
std::map<std::string, SoapySDR::Kwargs>& getLoaderResults (void)
share registration errors during loadModule
Definition at line 187 of file Modules.cpp.
Referenced by getModuleVersions().
std::map<std::string, void *>& getModuleHandles (void)
Definition at line 173 of file Modules.cpp.
Referenced by getModuleVersions().
std::string& getModuleLoading (void)
share the module path during loadModule
Definition at line 180 of file Modules.cpp.
Referenced by getModuleVersions().
std::map<std::string, std::string>& getModuleVersions (void)
Definition at line 193 of file Modules.cpp.
References BOOL(), lime::GetLastErrorMessage(), SoapySDR::getLoaderResult, getLoaderResults(), getModuleHandles(), getModuleLoading(), SoapySDR::getModuleVersion, i, lateLoadNullDevice(), SoapySDR::listModules, SoapySDR::loadModule, SoapySDR::loadModules, SoapySDR::logf(), LPVOID(), SoapySDR::SOAPY_SDR_ERROR, status, string(), and SoapySDR::unloadModule.
void lateLoadNullDevice (void)
lateLoadNullDevice() is called by loadModules() to load the null device on-demand/not statically. This works around an issue when a loading module is linked against an older copy of SoapySDR which also tries to load its null device into the running copy of the library.
Definition at line 54 of file NullDevice.cpp.
Referenced by getModuleVersions().
static std::vector<std::string> searchModulePath (const std::string & path) static
Definition at line 74 of file Modules.cpp.
References SoapySDR::getABIVersion, getEnvImpl(), SoapySDR::getRootPath, HANDLE(), i, SoapySDR::listModules, SoapySDR::listSearchPaths, SoapySDR::logf(), modules, SOAPY_SDR_ERROR, and string().