LimeSuite-UML: swig Namespace Reference
swig Namespace Reference
Classes
struct from_key_oper
struct from_oper
struct from_value_oper
struct noconst_traits
struct noconst_traits< const Type >
struct pointer_category
struct stop_iteration
class SwigPtr_PyObject
struct SwigPyIterator
class SwigPyIterator_T
class SwigPyIteratorClosed_T
class SwigPyIteratorOpen_T
struct SwigPyMapIterator_T
struct SwigPyMapKeyIterator_T
struct SwigPyMapValueITerator_T
struct SwigPySequence_ArrowProxy
struct SwigPySequence_Cont
struct SwigPySequence_InputIterator
struct SwigPySequence_Ref
struct SwigVar_PyObject
struct traits
struct traits< double >
struct traits< float >
struct traits< int >
struct traits< PyObject * >
struct traits< size_t >
struct traits< SoapySDR::ArgInfo >
struct traits< SoapySDR::Range >
struct traits< std::map< std::string, std::string, std::less< std::string >, std::allocator< std::pair< std::string const, std::string > > > >
struct traits< std::pair< std::string, std::string > >
struct traits< std::string >
struct traits< std::vector< double, std::allocator< double > > >
struct traits< std::vector< float, std::allocator< float > > >
struct traits< std::vector< int, std::allocator< int > > >
struct traits< std::vector< size_t, std::allocator< size_t > > >
struct traits< std::vector< SoapySDR::ArgInfo, std::allocator< SoapySDR::ArgInfo > > >
struct traits< std::vector< SoapySDR::Range, std::allocator< SoapySDR::Range > > >
struct traits< std::vector< std::map< std::string, std::string, std::less< std::string >, std::allocator< std::pair< std::string const, std::string > > >, std::allocator< std::map< std::string, std::string, std::less< std::string >, std::allocator< std::pair< std::string const, std::string > > > > > >
struct traits< std::vector< std::string, std::allocator< std::string > > >
struct traits< std::vector< unsigned int, std::allocator< unsigned int > > >
struct traits< Type * >
struct traits< unsigned int >
struct traits_as
struct traits_as< Type *, pointer_category >
struct traits_as< Type, pointer_category >
struct traits_as< Type, value_category >
struct traits_asptr
struct traits_asptr< std::map< K, T, Compare, Alloc > >
struct traits_asptr< std::pair< T, U > >
struct traits_asptr< std::vector< T > >
struct traits_asptr_stdseq
struct traits_asval
struct traits_asval< double >
struct traits_asval< float >
struct traits_asval< int >
struct traits_asval< PyObject * >
struct traits_asval< size_t >
struct traits_asval< std::string >
struct traits_asval< Type * >
struct traits_asval< unsigned int >
struct traits_check
struct traits_check< PyObject *, value_category >
struct traits_check< Type, pointer_category >
struct traits_check< Type, value_category >
struct traits_from
struct traits_from< const Type * >
struct traits_from< double >
struct traits_from< float >
struct traits_from< int >
struct traits_from< PyObject * >
struct traits_from< size_t >
struct traits_from< std::map< K, T, Compare, Alloc > >
struct traits_from< std::pair< T, U > >
struct traits_from< std::string >
struct traits_from< std::vector< T > >
struct traits_from< Type * >
struct traits_from< unsigned int >
struct traits_from_ptr
struct traits_from_stdseq
struct traits_info
struct value_category
Functions
template<class Type >
const char * type_name ()
template<class Type >
swig_type_info * type_info ()
template<class Type >
PyObject * from (const Type &val)
template<class Type >
PyObject * from_ptr (Type *val, int owner)
template<class Type >
int asptr (PyObject *obj, Type **vptr)
template<class Type >
int asval (PyObject *obj, Type *val)
template<class Type >
Type as (PyObject *obj, bool te=false)
template<class Type >
bool check (PyObject *obj)
template<class Difference >
size_t check_index (Difference i, size_t size, bool insert=false)
template<class Difference >
void slice_adjust (Difference i, Difference j, Py_ssize_t step, size_t size, Difference &ii, Difference &jj, bool insert=false)
template<class Sequence , class Difference >
Sequence::iterator getpos (Sequence *self, Difference i)
template<class Sequence , class Difference >
Sequence::const_iterator cgetpos (const Sequence *self, Difference i)
template<class Sequence , class Difference >
Sequence * getslice (const Sequence *self, Difference i, Difference j, Py_ssize_t step)
template<class Sequence , class Difference , class InputSeq >
void setslice (Sequence *self, Difference i, Difference j, Py_ssize_t step, const InputSeq &is=InputSeq())
template<class Sequence , class Difference >
void delslice (Sequence *self, Difference i, Difference j, Py_ssize_t step)
template<typename OutIter >
SwigPyIterator * make_output_iterator (const OutIter &current, const OutIter &begin, const OutIter &end, PyObject *seq=0)
template<typename OutIter >
SwigPyIterator * make_output_iterator (const OutIter &current, PyObject *seq=0)
template<class SwigPySeq , class Seq >
void assign (const SwigPySeq &swigpyseq, Seq *seq)
template<typename OutIter >
SwigPyIterator * make_output_key_iterator (const OutIter &current, const OutIter &begin, const OutIter &end, PyObject *seq=0)
template<typename OutIter >
SwigPyIterator * make_output_value_iterator (const OutIter &current, const OutIter &begin, const OutIter &end, PyObject *seq=0)
template<class SwigPySeq , class K , class T , class Compare , class Alloc >
void assign (const SwigPySeq &swigpyseq, std::map< K, T, Compare, Alloc > *map)
Function Documentation
template<class Type > Type swig::as (PyObject * obj, bool te = false) inline
Definition at line 3897 of file SoapySDRPYTHON_wrap.cxx.
Referenced by swig::traits_as< Type *, pointer_category >::as().
template<class Type > int swig::asptr (PyObject * obj, Type ** vptr) inline
Definition at line 3789 of file SoapySDRPYTHON_wrap.cxx.
Referenced by _wrap_crop_matrix_vcvc_make(), _wrap_crop_matrix_vcvc_sptr_make(), _wrap_crop_matrix_vcvc_sptr_set_processor_affinity(), _wrap_Device_enumerate(), _wrap_Device_enumerate__SWIG_0(), _wrap_Device_make(), _wrap_Device_make__SWIG_0(), _wrap_Device_readStream__(), _wrap_Device_setFrequency(), _wrap_Device_setFrequency__SWIG_0(), _wrap_Device_setFrequency__SWIG_2(), _wrap_Device_setupStream(), _wrap_Device_setupStream__SWIG_0(), _wrap_Device_setupStream__SWIG_1(), _wrap_Device_writeRegisters(), _wrap_Device_writeStream__(), _wrap_estimator_cw_sptr_set_processor_affinity(), _wrap_estimator_fmcw_sptr_set_processor_affinity(), _wrap_estimator_fsk_sptr_set_processor_affinity(), _wrap_estimator_ofdm_make(), _wrap_estimator_ofdm_sptr_make(), _wrap_estimator_ofdm_sptr_set_processor_affinity(), _wrap_estimator_rcs_sptr_set_processor_affinity(), _wrap_estimator_sync_pulse_c_sptr_set_processor_affinity(), _wrap_find_max_peak_c_make(), _wrap_find_max_peak_c_set_max_freq(), _wrap_find_max_peak_c_sptr_make(), _wrap_find_max_peak_c_sptr_set_max_freq(), _wrap_find_max_peak_c_sptr_set_processor_affinity(), _wrap_gpio_source_s_sptr_set_processor_affinity(), _wrap_msg_gate_make(), _wrap_msg_gate_sptr_make(), _wrap_msg_gate_sptr_set_processor_affinity(), _wrap_msg_manipulator_make(), _wrap_msg_manipulator_set_const_add(), _wrap_msg_manipulator_set_const_mult(), _wrap_msg_manipulator_sptr_make(), _wrap_msg_manipulator_sptr_set_const_add(), _wrap_msg_manipulator_sptr_set_const_mult(), _wrap_msg_manipulator_sptr_set_processor_affinity(), _wrap_new_SoapySDRArgInfoList(), _wrap_new_SoapySDRArgInfoList__SWIG_1(), _wrap_new_SoapySDRDoubleList(), _wrap_new_SoapySDRDoubleList__SWIG_1(), _wrap_new_SoapySDRKwargs(), _wrap_new_SoapySDRKwargs__SWIG_2(), _wrap_new_SoapySDRKwargsList(), _wrap_new_SoapySDRKwargsList__SWIG_1(), _wrap_new_SoapySDRKwargsList__SWIG_3(), _wrap_new_SoapySDRRangeList(), _wrap_new_SoapySDRRangeList__SWIG_1(), _wrap_new_SoapySDRSizeList(), _wrap_new_SoapySDRSizeList__SWIG_1(), _wrap_new_SoapySDRStringList(), _wrap_new_SoapySDRStringList__SWIG_1(), _wrap_new_SoapySDRUnsignedList(), _wrap_new_SoapySDRUnsignedList__SWIG_1(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_set_processor_affinity(), _wrap_ofdm_divide_vcvc_make(), _wrap_ofdm_divide_vcvc_sptr_make(), _wrap_ofdm_divide_vcvc_sptr_set_processor_affinity(), _wrap_os_cfar_2d_vc_make(), _wrap_os_cfar_2d_vc_set_samp_compare(), _wrap_os_cfar_2d_vc_set_samp_protect(), _wrap_os_cfar_2d_vc_sptr_make(), _wrap_os_cfar_2d_vc_sptr_set_processor_affinity(), _wrap_os_cfar_2d_vc_sptr_set_samp_compare(), _wrap_os_cfar_2d_vc_sptr_set_samp_protect(), _wrap_os_cfar_c_sptr_set_processor_affinity(), _wrap_print_results_sptr_set_processor_affinity(), _wrap_qtgui_scatter_plot_make(), _wrap_qtgui_scatter_plot_sptr_make(), _wrap_qtgui_scatter_plot_sptr_set_processor_affinity(), _wrap_qtgui_spectrogram_plot_make(), _wrap_qtgui_spectrogram_plot_sptr_make(), _wrap_qtgui_spectrogram_plot_sptr_set_processor_affinity(), _wrap_qtgui_time_plot_make(), _wrap_qtgui_time_plot_sptr_make(), _wrap_qtgui_time_plot_sptr_set_processor_affinity(), _wrap_signal_generator_cw_c_make(), _wrap_signal_generator_cw_c_sptr_make(), _wrap_signal_generator_cw_c_sptr_set_processor_affinity(), _wrap_signal_generator_fmcw_c_sptr_set_processor_affinity(), _wrap_signal_generator_fsk_c_sptr_set_processor_affinity(), _wrap_signal_generator_sync_pulse_c_make(), _wrap_signal_generator_sync_pulse_c_sptr_make(), _wrap_signal_generator_sync_pulse_c_sptr_set_processor_affinity(), _wrap_soapysdr_echotimer_sptr_set_processor_affinity(), _wrap_soapysdr_echotimer_stretch_sptr_set_processor_affinity(), _wrap_SoapySDRArgInfoList___delitem__(), _wrap_SoapySDRArgInfoList___getitem__(), _wrap_SoapySDRArgInfoList___setitem__(), _wrap_SoapySDRArgInfoList___setitem____SWIG_0(), _wrap_SoapySDRArgInfoList___setslice__(), _wrap_SoapySDRArgInfoList___setslice____SWIG_0(), _wrap_SoapySDRArgInfoList_erase(), _wrap_SoapySDRArgInfoList_insert(), _wrap_SoapySDRArgInfoList_resize(), _wrap_SoapySDRDoubleList___delitem__(), _wrap_SoapySDRDoubleList___getitem__(), _wrap_SoapySDRDoubleList___setitem__(), _wrap_SoapySDRDoubleList___setitem____SWIG_0(), _wrap_SoapySDRDoubleList___setslice__(), _wrap_SoapySDRDoubleList___setslice____SWIG_0(), _wrap_SoapySDRDoubleList_erase(), _wrap_SoapySDRDoubleList_insert(), _wrap_SoapySDRDoubleList_resize(), _wrap_SoapySDRKwargs___setitem__(), _wrap_SoapySDRKwargs_erase(), _wrap_SoapySDRKwargsList___delitem__(), _wrap_SoapySDRKwargsList___getitem__(), _wrap_SoapySDRKwargsList___setitem__(), _wrap_SoapySDRKwargsList___setitem____SWIG_0(), _wrap_SoapySDRKwargsList___setitem____SWIG_2(), _wrap_SoapySDRKwargsList___setslice__(), _wrap_SoapySDRKwargsList___setslice____SWIG_0(), _wrap_SoapySDRKwargsList_append(), _wrap_SoapySDRKwargsList_assign(), _wrap_SoapySDRKwargsList_erase(), _wrap_SoapySDRKwargsList_insert(), _wrap_SoapySDRKwargsList_insert__SWIG_0(), _wrap_SoapySDRKwargsList_insert__SWIG_1(), _wrap_SoapySDRKwargsList_push_back(), _wrap_SoapySDRKwargsList_resize(), _wrap_SoapySDRKwargsList_resize__SWIG_1(), _wrap_SoapySDRRangeList___delitem__(), _wrap_SoapySDRRangeList___getitem__(), _wrap_SoapySDRRangeList___setitem__(), _wrap_SoapySDRRangeList___setitem____SWIG_0(), _wrap_SoapySDRRangeList___setslice__(), _wrap_SoapySDRRangeList___setslice____SWIG_0(), _wrap_SoapySDRRangeList_erase(), _wrap_SoapySDRRangeList_insert(), _wrap_SoapySDRRangeList_resize(), _wrap_SoapySDRSizeList___delitem__(), _wrap_SoapySDRSizeList___getitem__(), _wrap_SoapySDRSizeList___setitem__(), _wrap_SoapySDRSizeList___setitem____SWIG_0(), _wrap_SoapySDRSizeList___setslice__(), _wrap_SoapySDRSizeList___setslice____SWIG_0(), _wrap_SoapySDRSizeList_erase(), _wrap_SoapySDRSizeList_insert(), _wrap_SoapySDRSizeList_resize(), _wrap_SoapySDRStringList___delitem__(), _wrap_SoapySDRStringList___getitem__(), _wrap_SoapySDRStringList___setitem__(), _wrap_SoapySDRStringList___setitem____SWIG_0(), _wrap_SoapySDRStringList___setslice__(), _wrap_SoapySDRStringList___setslice____SWIG_0(), _wrap_SoapySDRStringList_erase(), _wrap_SoapySDRStringList_insert(), _wrap_SoapySDRStringList_resize(), _wrap_SoapySDRUnsignedList___delitem__(), _wrap_SoapySDRUnsignedList___getitem__(), _wrap_SoapySDRUnsignedList___setitem__(), _wrap_SoapySDRUnsignedList___setitem____SWIG_0(), _wrap_SoapySDRUnsignedList___setslice__(), _wrap_SoapySDRUnsignedList___setslice____SWIG_0(), _wrap_SoapySDRUnsignedList_erase(), _wrap_SoapySDRUnsignedList_insert(), _wrap_SoapySDRUnsignedList_resize(), _wrap_split_cc_make(), _wrap_split_cc_sptr_make(), _wrap_split_cc_sptr_set_processor_affinity(), _wrap_split_fsk_cc_sptr_set_processor_affinity(), _wrap_static_target_simulator_cc_make(), _wrap_static_target_simulator_cc_setup_targets(), _wrap_static_target_simulator_cc_sptr_make(), _wrap_static_target_simulator_cc_sptr_set_processor_affinity(), _wrap_static_target_simulator_cc_sptr_setup_targets(), _wrap_tracking_singletarget_sptr_set_processor_affinity(), _wrap_transpose_matrix_vcvc_sptr_set_processor_affinity(), _wrap_trigger_command_make(), _wrap_trigger_command_sptr_make(), _wrap_trigger_command_sptr_set_processor_affinity(), _wrap_ts_fft_cc_sptr_set_processor_affinity(), _wrap_usrp_echotimer_cc_sptr_set_processor_affinity(), swig::traits_as< Type, pointer_category >::as(), swig::traits_as< Type *, pointer_category >::as(), swig::traits_asptr< Type >::asptr(), assign(), swig::traits_asval< Type >::asval(), swig::traits_asval< Type * >::asval(), swig::traits_check< Type, pointer_category >::check(), swig::traits_from_stdseq< Seq, T >::from(), and SWIG_AsVal_std_string().
template<class SwigPySeq , class Seq > void swig::assign (const SwigPySeq & swigpyseq, Seq * seq) inline
Definition at line 4720 of file SoapySDRPYTHON_wrap.cxx.
Referenced by swig::traits_asptr_stdseq< Seq, T >::asptr(), and swig::traits_from< float >::from().
template<class SwigPySeq , class K , class T , class Compare , class Alloc > void swig::assign (const SwigPySeq & swigpyseq, std::map< K, T, Compare, Alloc > * map) inline
Definition at line 5196 of file SoapySDRPYTHON_wrap.cxx.
References asptr(), swig_type_info::clientdata, from(), i, int(), p(), SWIG_ConvertPtr, SWIG_ERROR, SWIG_InternalNewPointerObj, SWIG_IsOK, SWIG_POINTER_OWN, SWIG_PYTHON_THREAD_BEGIN_BLOCK, SWIG_PYTHON_THREAD_END_BLOCK, type_name(), and val.
Referenced by _wrap_SoapySDRArgInfoList_assign(), _wrap_SoapySDRDoubleList_assign(), _wrap_SoapySDRKwargsList_assign(), _wrap_SoapySDRRangeList_assign(), _wrap_SoapySDRSizeList_assign(), _wrap_SoapySDRStringList_assign(), _wrap_SoapySDRUnsignedList_assign(), and swig::traits_asptr_stdseq< Seq, T >::asptr().
template<class Type > int swig::asval (PyObject * obj, Type * val) inline
Definition at line 3834 of file SoapySDRPYTHON_wrap.cxx.
Referenced by swig::traits_as< Type, value_category >::as(), swig::traits_asval< Type * >::asval(), swig::traits_check< Type, value_category >::check(), and SWIG_AsVal_std_string().
template<class Sequence , class Difference > Sequence::const_iterator swig::cgetpos (const Sequence * self, Difference i) inline
Definition at line 4066 of file SoapySDRPYTHON_wrap.cxx.
References check_index().
Referenced by swig::traits_from< PyObject * >::from(), std_vector_Sl_double_Sg____getitem____SWIG_1(), std_vector_Sl_size_t_Sg____getitem____SWIG_1(), std_vector_Sl_SoapySDR_ArgInfo_Sg____getitem____SWIG_1(), std_vector_Sl_SoapySDR_Kwargs_Sg____getitem____SWIG_1(), std_vector_Sl_SoapySDR_Range_Sg____getitem____SWIG_1(), std_vector_Sl_std_string_Sg____getitem____SWIG_1(), and std_vector_Sl_unsigned_SS_int_Sg____getitem____SWIG_1().
template<class Type > bool swig::check (PyObject * obj) inline
Definition at line 3918 of file SoapySDRPYTHON_wrap.cxx.
References SWIG_PYTHON_THREAD_BEGIN_BLOCK, and SWIG_PYTHON_THREAD_END_BLOCK.
Referenced by swig::traits_check< Type, pointer_category >::check(), DEFUN_DLD(), pnlLimeSDR::OnUsrGPIODirChange(), and LimeSDRTest_USB::Si5351CTest().
template<class Difference > size_t swig::check_index (Difference i, size_t size, bool insert = false) inline
Definition at line 4008 of file SoapySDRPYTHON_wrap.cxx.
References i.
Referenced by cgetpos(), swig::traits_from< PyObject * >::from(), and getpos().
template<class Sequence , class Difference > void swig::delslice (Sequence * self, Difference i, Difference j, Py_ssize_t step) inline
Definition at line 4183 of file SoapySDRPYTHON_wrap.cxx.
References c, and slice_adjust().
Referenced by swig::traits_from< PyObject * >::from(), std_vector_Sl_double_Sg____delitem____SWIG_1(), std_vector_Sl_double_Sg____delslice__(), std_vector_Sl_double_Sg____setitem____SWIG_1(), std_vector_Sl_size_t_Sg____delitem____SWIG_1(), std_vector_Sl_size_t_Sg____delslice__(), std_vector_Sl_size_t_Sg____setitem____SWIG_1(), std_vector_Sl_SoapySDR_ArgInfo_Sg____delitem____SWIG_1(), std_vector_Sl_SoapySDR_ArgInfo_Sg____delslice__(), std_vector_Sl_SoapySDR_ArgInfo_Sg____setitem____SWIG_1(), std_vector_Sl_SoapySDR_Kwargs_Sg____delitem____SWIG_1(), std_vector_Sl_SoapySDR_Kwargs_Sg____delslice__(), std_vector_Sl_SoapySDR_Kwargs_Sg____setitem____SWIG_1(), std_vector_Sl_SoapySDR_Range_Sg____delitem____SWIG_1(), std_vector_Sl_SoapySDR_Range_Sg____delslice__(), std_vector_Sl_SoapySDR_Range_Sg____setitem____SWIG_1(), std_vector_Sl_std_string_Sg____delitem____SWIG_1(), std_vector_Sl_std_string_Sg____delslice__(), std_vector_Sl_std_string_Sg____setitem____SWIG_1(), std_vector_Sl_unsigned_SS_int_Sg____delitem____SWIG_1(), std_vector_Sl_unsigned_SS_int_Sg____delslice__(), and std_vector_Sl_unsigned_SS_int_Sg____setitem____SWIG_1().
template<class Type > PyObject * swig::from (const Type & val) inline
Definition at line 3764 of file SoapySDRPYTHON_wrap.cxx.
Referenced by _wrap_crop_matrix_vcvc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_crop_matrix_vcvc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_crop_matrix_vcvc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_crop_matrix_vcvc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_crop_matrix_vcvc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_crop_matrix_vcvc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_crop_matrix_vcvc_sptr_processor_affinity(), _wrap_Device_enumerate__SWIG_0(), _wrap_Device_enumerate__SWIG_1(), _wrap_Device_enumerate__SWIG_2(), _wrap_Device_getBandwidthRange(), _wrap_Device_getChannelInfo(), _wrap_Device_getFrequencyArgsInfo(), _wrap_Device_getFrequencyRange__SWIG_0(), _wrap_Device_getFrequencyRange__SWIG_1(), _wrap_Device_getHardwareInfo(), _wrap_Device_getMasterClockRates(), _wrap_Device_getSampleRateRange(), _wrap_Device_getSettingInfo__SWIG_0(), _wrap_Device_getSettingInfo__SWIG_1(), _wrap_Device_getStreamArgsInfo(), _wrap_Device_getStreamFormats(), _wrap_Device_listAntennas(), _wrap_Device_listBandwidths(), _wrap_Device_listClockSources(), _wrap_Device_listFrequencies(), _wrap_Device_listGains(), _wrap_Device_listGPIOBanks(), _wrap_Device_listRegisterInterfaces(), _wrap_Device_listSampleRates(), _wrap_Device_listSensors__SWIG_0(), _wrap_Device_listSensors__SWIG_1(), _wrap_Device_listTimeSources(), _wrap_Device_listUARTs(), _wrap_Device_readRegisters(), _wrap_estimator_cw_sptr_pc_input_buffers_full__SWIG_1(), _wrap_estimator_cw_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_estimator_cw_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_estimator_cw_sptr_pc_output_buffers_full__SWIG_1(), _wrap_estimator_cw_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_estimator_cw_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_estimator_cw_sptr_processor_affinity(), _wrap_estimator_fmcw_sptr_pc_input_buffers_full__SWIG_1(), _wrap_estimator_fmcw_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_estimator_fmcw_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_estimator_fmcw_sptr_pc_output_buffers_full__SWIG_1(), _wrap_estimator_fmcw_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_estimator_fmcw_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_estimator_fmcw_sptr_processor_affinity(), _wrap_estimator_fsk_sptr_pc_input_buffers_full__SWIG_1(), _wrap_estimator_fsk_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_estimator_fsk_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_estimator_fsk_sptr_pc_output_buffers_full__SWIG_1(), _wrap_estimator_fsk_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_estimator_fsk_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_estimator_fsk_sptr_processor_affinity(), _wrap_estimator_ofdm_sptr_pc_input_buffers_full__SWIG_1(), _wrap_estimator_ofdm_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_estimator_ofdm_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_estimator_ofdm_sptr_pc_output_buffers_full__SWIG_1(), _wrap_estimator_ofdm_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_estimator_ofdm_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_estimator_ofdm_sptr_processor_affinity(), _wrap_estimator_rcs_sptr_pc_input_buffers_full__SWIG_1(), _wrap_estimator_rcs_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_estimator_rcs_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_estimator_rcs_sptr_pc_output_buffers_full__SWIG_1(), _wrap_estimator_rcs_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_estimator_rcs_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_estimator_rcs_sptr_processor_affinity(), _wrap_estimator_sync_pulse_c_sptr_pc_input_buffers_full__SWIG_1(), _wrap_estimator_sync_pulse_c_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_estimator_sync_pulse_c_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_estimator_sync_pulse_c_sptr_pc_output_buffers_full__SWIG_1(), _wrap_estimator_sync_pulse_c_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_estimator_sync_pulse_c_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_estimator_sync_pulse_c_sptr_processor_affinity(), _wrap_find_max_peak_c_sptr_pc_input_buffers_full__SWIG_1(), _wrap_find_max_peak_c_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_find_max_peak_c_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_find_max_peak_c_sptr_pc_output_buffers_full__SWIG_1(), _wrap_find_max_peak_c_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_find_max_peak_c_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_find_max_peak_c_sptr_processor_affinity(), _wrap_getLoaderResult(), _wrap_gpio_source_s_sptr_pc_input_buffers_full__SWIG_1(), _wrap_gpio_source_s_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_gpio_source_s_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_gpio_source_s_sptr_pc_output_buffers_full__SWIG_1(), _wrap_gpio_source_s_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_gpio_source_s_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_gpio_source_s_sptr_processor_affinity(), _wrap_listModules__SWIG_0(), _wrap_listModules__SWIG_1(), _wrap_listSearchPaths(), _wrap_msg_gate_sptr_pc_input_buffers_full__SWIG_1(), _wrap_msg_gate_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_msg_gate_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_msg_gate_sptr_pc_output_buffers_full__SWIG_1(), _wrap_msg_gate_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_msg_gate_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_msg_gate_sptr_processor_affinity(), _wrap_msg_manipulator_sptr_pc_input_buffers_full__SWIG_1(), _wrap_msg_manipulator_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_msg_manipulator_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_msg_manipulator_sptr_pc_output_buffers_full__SWIG_1(), _wrap_msg_manipulator_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_msg_manipulator_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_msg_manipulator_sptr_processor_affinity(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_processor_affinity(), _wrap_ofdm_divide_vcvc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_ofdm_divide_vcvc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_ofdm_divide_vcvc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_ofdm_divide_vcvc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_ofdm_divide_vcvc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_ofdm_divide_vcvc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_ofdm_divide_vcvc_sptr_processor_affinity(), _wrap_os_cfar_2d_vc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_os_cfar_2d_vc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_os_cfar_2d_vc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_os_cfar_2d_vc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_os_cfar_2d_vc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_os_cfar_2d_vc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_os_cfar_2d_vc_sptr_processor_affinity(), _wrap_os_cfar_c_sptr_pc_input_buffers_full__SWIG_1(), _wrap_os_cfar_c_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_os_cfar_c_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_os_cfar_c_sptr_pc_output_buffers_full__SWIG_1(), _wrap_os_cfar_c_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_os_cfar_c_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_os_cfar_c_sptr_processor_affinity(), _wrap_print_results_sptr_pc_input_buffers_full__SWIG_1(), _wrap_print_results_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_print_results_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_print_results_sptr_pc_output_buffers_full__SWIG_1(), _wrap_print_results_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_print_results_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_print_results_sptr_processor_affinity(), _wrap_qtgui_scatter_plot_sptr_pc_input_buffers_full__SWIG_1(), _wrap_qtgui_scatter_plot_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_qtgui_scatter_plot_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_qtgui_scatter_plot_sptr_pc_output_buffers_full__SWIG_1(), _wrap_qtgui_scatter_plot_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_qtgui_scatter_plot_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_qtgui_scatter_plot_sptr_processor_affinity(), _wrap_qtgui_spectrogram_plot_sptr_pc_input_buffers_full__SWIG_1(), _wrap_qtgui_spectrogram_plot_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_qtgui_spectrogram_plot_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_qtgui_spectrogram_plot_sptr_pc_output_buffers_full__SWIG_1(), _wrap_qtgui_spectrogram_plot_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_qtgui_spectrogram_plot_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_qtgui_spectrogram_plot_sptr_processor_affinity(), _wrap_qtgui_time_plot_sptr_pc_input_buffers_full__SWIG_1(), _wrap_qtgui_time_plot_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_qtgui_time_plot_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_qtgui_time_plot_sptr_pc_output_buffers_full__SWIG_1(), _wrap_qtgui_time_plot_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_qtgui_time_plot_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_qtgui_time_plot_sptr_processor_affinity(), _wrap_signal_generator_cw_c_sptr_pc_input_buffers_full__SWIG_1(), _wrap_signal_generator_cw_c_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_signal_generator_cw_c_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_signal_generator_cw_c_sptr_pc_output_buffers_full__SWIG_1(), _wrap_signal_generator_cw_c_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_signal_generator_cw_c_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_signal_generator_cw_c_sptr_processor_affinity(), _wrap_signal_generator_fmcw_c_sptr_pc_input_buffers_full__SWIG_1(), _wrap_signal_generator_fmcw_c_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_signal_generator_fmcw_c_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_signal_generator_fmcw_c_sptr_pc_output_buffers_full__SWIG_1(), _wrap_signal_generator_fmcw_c_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_signal_generator_fmcw_c_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_signal_generator_fmcw_c_sptr_processor_affinity(), _wrap_signal_generator_fsk_c_sptr_pc_input_buffers_full__SWIG_1(), _wrap_signal_generator_fsk_c_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_signal_generator_fsk_c_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_signal_generator_fsk_c_sptr_pc_output_buffers_full__SWIG_1(), _wrap_signal_generator_fsk_c_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_signal_generator_fsk_c_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_signal_generator_fsk_c_sptr_processor_affinity(), _wrap_signal_generator_sync_pulse_c_sptr_pc_input_buffers_full__SWIG_1(), _wrap_signal_generator_sync_pulse_c_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_signal_generator_sync_pulse_c_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_signal_generator_sync_pulse_c_sptr_pc_output_buffers_full__SWIG_1(), _wrap_signal_generator_sync_pulse_c_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_signal_generator_sync_pulse_c_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_signal_generator_sync_pulse_c_sptr_processor_affinity(), _wrap_soapysdr_echotimer_sptr_pc_input_buffers_full__SWIG_1(), _wrap_soapysdr_echotimer_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_soapysdr_echotimer_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_soapysdr_echotimer_sptr_pc_output_buffers_full__SWIG_1(), _wrap_soapysdr_echotimer_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_soapysdr_echotimer_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_soapysdr_echotimer_sptr_processor_affinity(), _wrap_soapysdr_echotimer_stretch_sptr_pc_input_buffers_full__SWIG_1(), _wrap_soapysdr_echotimer_stretch_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_soapysdr_echotimer_stretch_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_soapysdr_echotimer_stretch_sptr_pc_output_buffers_full__SWIG_1(), _wrap_soapysdr_echotimer_stretch_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_soapysdr_echotimer_stretch_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_soapysdr_echotimer_stretch_sptr_processor_affinity(), _wrap_SoapySDRKwargsList___getitem____SWIG_1(), _wrap_SoapySDRKwargsList_back(), _wrap_SoapySDRKwargsList_front(), _wrap_SoapySDRKwargsList_pop(), _wrap_split_cc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_split_cc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_split_cc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_split_cc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_split_cc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_split_cc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_split_cc_sptr_processor_affinity(), _wrap_split_fsk_cc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_split_fsk_cc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_split_fsk_cc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_split_fsk_cc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_split_fsk_cc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_split_fsk_cc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_split_fsk_cc_sptr_processor_affinity(), _wrap_static_target_simulator_cc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_static_target_simulator_cc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_static_target_simulator_cc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_static_target_simulator_cc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_static_target_simulator_cc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_static_target_simulator_cc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_static_target_simulator_cc_sptr_processor_affinity(), _wrap_tracking_singletarget_sptr_pc_input_buffers_full__SWIG_1(), _wrap_tracking_singletarget_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_tracking_singletarget_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_tracking_singletarget_sptr_pc_output_buffers_full__SWIG_1(), _wrap_tracking_singletarget_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_tracking_singletarget_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_tracking_singletarget_sptr_processor_affinity(), _wrap_transpose_matrix_vcvc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_transpose_matrix_vcvc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_transpose_matrix_vcvc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_transpose_matrix_vcvc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_transpose_matrix_vcvc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_transpose_matrix_vcvc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_transpose_matrix_vcvc_sptr_processor_affinity(), _wrap_trigger_command_sptr_pc_input_buffers_full__SWIG_1(), _wrap_trigger_command_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_trigger_command_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_trigger_command_sptr_pc_output_buffers_full__SWIG_1(), _wrap_trigger_command_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_trigger_command_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_trigger_command_sptr_processor_affinity(), _wrap_ts_fft_cc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_ts_fft_cc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_ts_fft_cc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_ts_fft_cc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_ts_fft_cc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_ts_fft_cc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_ts_fft_cc_sptr_processor_affinity(), _wrap_usrp_echotimer_cc_sptr_pc_input_buffers_full__SWIG_1(), _wrap_usrp_echotimer_cc_sptr_pc_input_buffers_full_avg__SWIG_1(), _wrap_usrp_echotimer_cc_sptr_pc_input_buffers_full_var__SWIG_1(), _wrap_usrp_echotimer_cc_sptr_pc_output_buffers_full__SWIG_1(), _wrap_usrp_echotimer_cc_sptr_pc_output_buffers_full_avg__SWIG_1(), _wrap_usrp_echotimer_cc_sptr_pc_output_buffers_full_var__SWIG_1(), _wrap_usrp_echotimer_cc_sptr_processor_affinity(), assign(), swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::decr(), swig::traits_from< Type >::from(), swig::traits_from< Type * >::from(), swig::traits_from< const Type * >::from(), swig::traits_from_stdseq< Seq, T >::from(), from_ptr(), swig::from_oper< ValueType >::operator()(), swig::from_key_oper< ValueType >::operator()(), swig::from_value_oper< ValueType >::operator()(), std_map_Sl_std_string_Sc_std_string_Sg__items(), std_map_Sl_std_string_Sc_std_string_Sg__keys(), std_map_Sl_std_string_Sc_std_string_Sg__values(), string(), SWIG_AsVal_std_string(), swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::value(), and swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >::value().
template<class Type > PyObject * swig::from_ptr (Type * val, int owner) inline
Definition at line 3769 of file SoapySDRPYTHON_wrap.cxx.
References from().
Referenced by swig::traits_from< const Type * >::from().
template<class Sequence , class Difference > Sequence::iterator swig::getpos (Sequence * self, Difference i) inline
Definition at line 4058 of file SoapySDRPYTHON_wrap.cxx.
References check_index().
Referenced by swig::traits_from< PyObject * >::from(), std_vector_Sl_double_Sg____delitem____SWIG_0(), std_vector_Sl_double_Sg____setitem____SWIG_2(), std_vector_Sl_size_t_Sg____delitem____SWIG_0(), std_vector_Sl_size_t_Sg____setitem____SWIG_2(), std_vector_Sl_SoapySDR_ArgInfo_Sg____delitem____SWIG_0(), std_vector_Sl_SoapySDR_ArgInfo_Sg____setitem____SWIG_2(), std_vector_Sl_SoapySDR_Kwargs_Sg____delitem____SWIG_0(), std_vector_Sl_SoapySDR_Kwargs_Sg____setitem____SWIG_2(), std_vector_Sl_SoapySDR_Range_Sg____delitem____SWIG_0(), std_vector_Sl_SoapySDR_Range_Sg____setitem____SWIG_2(), std_vector_Sl_std_string_Sg____delitem____SWIG_0(), std_vector_Sl_std_string_Sg____setitem____SWIG_2(), std_vector_Sl_unsigned_SS_int_Sg____delitem____SWIG_0(), and std_vector_Sl_unsigned_SS_int_Sg____setitem____SWIG_2().
template<class Sequence , class Difference > Sequence * swig::getslice (const Sequence * self, Difference i, Difference j, Py_ssize_t step) inline
Definition at line 4074 of file SoapySDRPYTHON_wrap.cxx.
References c, and slice_adjust().
Referenced by swig::traits_from< PyObject * >::from(), std_vector_Sl_double_Sg____getitem____SWIG_0(), std_vector_Sl_double_Sg____getslice__(), std_vector_Sl_size_t_Sg____getitem____SWIG_0(), std_vector_Sl_size_t_Sg____getslice__(), std_vector_Sl_SoapySDR_ArgInfo_Sg____getitem____SWIG_0(), std_vector_Sl_SoapySDR_ArgInfo_Sg____getslice__(), std_vector_Sl_SoapySDR_Kwargs_Sg____getitem____SWIG_0(), std_vector_Sl_SoapySDR_Kwargs_Sg____getslice__(), std_vector_Sl_SoapySDR_Range_Sg____getitem____SWIG_0(), std_vector_Sl_SoapySDR_Range_Sg____getslice__(), std_vector_Sl_std_string_Sg____getitem____SWIG_0(), std_vector_Sl_std_string_Sg____getslice__(), std_vector_Sl_unsigned_SS_int_Sg____getitem____SWIG_0(), and std_vector_Sl_unsigned_SS_int_Sg____getslice__().
template<typename OutIter > SwigPyIterator * swig::make_output_iterator (const OutIter & current, const OutIter & begin, const OutIter & end, PyObject * seq = 0) inline
Definition at line 4426 of file SoapySDRPYTHON_wrap.cxx.
Referenced by _wrap_SoapySDRArgInfoList_begin(), _wrap_SoapySDRArgInfoList_end(), _wrap_SoapySDRArgInfoList_erase__SWIG_0(), _wrap_SoapySDRArgInfoList_erase__SWIG_1(), _wrap_SoapySDRArgInfoList_insert__SWIG_0(), _wrap_SoapySDRArgInfoList_rbegin(), _wrap_SoapySDRArgInfoList_rend(), _wrap_SoapySDRDoubleList_begin(), _wrap_SoapySDRDoubleList_end(), _wrap_SoapySDRDoubleList_erase__SWIG_0(), _wrap_SoapySDRDoubleList_erase__SWIG_1(), _wrap_SoapySDRDoubleList_insert__SWIG_0(), _wrap_SoapySDRDoubleList_rbegin(), _wrap_SoapySDRDoubleList_rend(), _wrap_SoapySDRKwargs_begin(), _wrap_SoapySDRKwargs_end(), _wrap_SoapySDRKwargs_find(), _wrap_SoapySDRKwargs_lower_bound(), _wrap_SoapySDRKwargs_rbegin(), _wrap_SoapySDRKwargs_rend(), _wrap_SoapySDRKwargs_upper_bound(), _wrap_SoapySDRKwargsList_begin(), _wrap_SoapySDRKwargsList_end(), _wrap_SoapySDRKwargsList_erase__SWIG_0(), _wrap_SoapySDRKwargsList_erase__SWIG_1(), _wrap_SoapySDRKwargsList_insert__SWIG_0(), _wrap_SoapySDRKwargsList_rbegin(), _wrap_SoapySDRKwargsList_rend(), _wrap_SoapySDRRangeList_begin(), _wrap_SoapySDRRangeList_end(), _wrap_SoapySDRRangeList_erase__SWIG_0(), _wrap_SoapySDRRangeList_erase__SWIG_1(), _wrap_SoapySDRRangeList_insert__SWIG_0(), _wrap_SoapySDRRangeList_rbegin(), _wrap_SoapySDRRangeList_rend(), _wrap_SoapySDRSizeList_begin(), _wrap_SoapySDRSizeList_end(), _wrap_SoapySDRSizeList_erase__SWIG_0(), _wrap_SoapySDRSizeList_erase__SWIG_1(), _wrap_SoapySDRSizeList_insert__SWIG_0(), _wrap_SoapySDRSizeList_rbegin(), _wrap_SoapySDRSizeList_rend(), _wrap_SoapySDRStringList_begin(), _wrap_SoapySDRStringList_end(), _wrap_SoapySDRStringList_erase__SWIG_0(), _wrap_SoapySDRStringList_erase__SWIG_1(), _wrap_SoapySDRStringList_insert__SWIG_0(), _wrap_SoapySDRStringList_rbegin(), _wrap_SoapySDRStringList_rend(), _wrap_SoapySDRUnsignedList_begin(), _wrap_SoapySDRUnsignedList_end(), _wrap_SoapySDRUnsignedList_erase__SWIG_0(), _wrap_SoapySDRUnsignedList_erase__SWIG_1(), _wrap_SoapySDRUnsignedList_insert__SWIG_0(), _wrap_SoapySDRUnsignedList_rbegin(), _wrap_SoapySDRUnsignedList_rend(), swig::SwigPyIteratorClosed_T< OutIterator, typename OutIterator::value_type, FromOper >::decr(), std_map_Sl_std_string_Sc_std_string_Sg__iterator(), std_vector_Sl_double_Sg__iterator(), std_vector_Sl_size_t_Sg__iterator(), std_vector_Sl_SoapySDR_ArgInfo_Sg__iterator(), std_vector_Sl_SoapySDR_Kwargs_Sg__iterator(), std_vector_Sl_SoapySDR_Range_Sg__iterator(), std_vector_Sl_std_string_Sg__iterator(), and std_vector_Sl_unsigned_SS_int_Sg__iterator().
template<typename OutIter > SwigPyIterator * swig::make_output_iterator (const OutIter & current, PyObject * seq = 0) inline
Definition at line 4433 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIter > SwigPyIterator* swig::make_output_key_iterator (const OutIter & current, const OutIter & begin, const OutIter & end, PyObject * seq = 0) inline
Definition at line 5168 of file SoapySDRPYTHON_wrap.cxx.
Referenced by std_map_Sl_std_string_Sc_std_string_Sg__key_iterator().
template<typename OutIter > SwigPyIterator* swig::make_output_value_iterator (const OutIter & current, const OutIter & begin, const OutIter & end, PyObject * seq = 0) inline
Definition at line 5186 of file SoapySDRPYTHON_wrap.cxx.
Referenced by std_map_Sl_std_string_Sc_std_string_Sg__value_iterator().
template<class Sequence , class Difference , class InputSeq > void swig::setslice (Sequence * self, Difference i, Difference j, Py_ssize_t step, const InputSeq & is = InputSeq()) inline
Definition at line 4117 of file SoapySDRPYTHON_wrap.cxx.
References c, and slice_adjust().
Referenced by swig::traits_from< PyObject * >::from(), std_vector_Sl_double_Sg____setitem____SWIG_0(), std_vector_Sl_double_Sg____setslice____SWIG_0(), std_vector_Sl_size_t_Sg____setitem____SWIG_0(), std_vector_Sl_size_t_Sg____setslice____SWIG_0(), std_vector_Sl_SoapySDR_ArgInfo_Sg____setitem____SWIG_0(), std_vector_Sl_SoapySDR_ArgInfo_Sg____setslice____SWIG_0(), std_vector_Sl_SoapySDR_Kwargs_Sg____setitem____SWIG_0(), std_vector_Sl_SoapySDR_Kwargs_Sg____setslice____SWIG_0(), std_vector_Sl_SoapySDR_Range_Sg____setitem____SWIG_0(), std_vector_Sl_SoapySDR_Range_Sg____setslice____SWIG_0(), std_vector_Sl_std_string_Sg____setitem____SWIG_0(), std_vector_Sl_std_string_Sg____setslice____SWIG_0(), std_vector_Sl_unsigned_SS_int_Sg____setitem____SWIG_0(), and std_vector_Sl_unsigned_SS_int_Sg____setslice____SWIG_0().
template<class Difference > void swig::slice_adjust (Difference i, Difference j, Py_ssize_t step, size_t size, Difference & ii, Difference & jj, bool insert = false)
Definition at line 4022 of file SoapySDRPYTHON_wrap.cxx.
References i.
Referenced by delslice(), swig::traits_from< PyObject * >::from(), getslice(), and setslice().
template<class Type > swig_type_info * swig::type_info () inline
Definition at line 3705 of file SoapySDRPYTHON_wrap.cxx.
Referenced by swig::traits_info< Type >::type_info().
template<class Type > const char * swig::type_name () inline
Definition at line 3688 of file SoapySDRPYTHON_wrap.cxx.
Referenced by assign(), swig::traits_from_stdseq< Seq, T >::from(), swig::traits_from< int >::from(), swig::traits_from< size_t >::from(), swig::traits_from< double >::from(), std_map_Sl_std_string_Sc_std_string_Sg__erase__SWIG_2(), std_vector_Sl_SoapySDR_ArgInfo_Sg__insert__SWIG_1(), SWIG_AsVal_std_string(), swig::traits< SoapySDR::ArgInfo >::type_name(), and swig::traits< SoapySDR::Range >::type_name().