LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/TypesC.cpp File Reference
TypesC.cpp File Reference
#include "TypeHelpers.hpp"
#include <SoapySDR/Types.h>
#include <cstdlib>
#include <cstring>
Functions
SoapySDRKwargs SoapySDRKwargs_fromString (const char *markup)
char * SoapySDRKwargs_toString (const SoapySDRKwargs *args)
void SoapySDRStrings_clear (char ***elems, const size_t length)
void SoapySDRKwargs_set (SoapySDRKwargs *args, const char *key, const char *val)
const char * SoapySDRKwargs_get (SoapySDRKwargs *args, const char *key)
void SoapySDRKwargs_clear (SoapySDRKwargs *args)
void SoapySDRKwargsList_clear (SoapySDRKwargs *args, const size_t length)
void SoapySDRArgInfo_clear (SoapySDRArgInfo *info)
void SoapySDRArgInfoList_clear (SoapySDRArgInfo *info, const size_t length)
Function Documentation
void SoapySDRArgInfo_clear (SoapySDRArgInfo * info)
Clear the contents of a argument info structure. This frees all the underlying memory and clears the members.
Definition at line 76 of file TypesC.cpp.
References SoapySDRArgInfo::description, SoapySDRArgInfo::key, SoapySDRArgInfo::name, SoapySDRArgInfo::numOptions, SoapySDRArgInfo::optionNames, SoapySDRArgInfo::options, SoapySDRStrings_clear(), SoapySDRArgInfo::units, and SoapySDRArgInfo::value.
Referenced by SoapySDRArgInfoList_clear().
void SoapySDRArgInfoList_clear (SoapySDRArgInfo * info, const size_t length)
Clear a list of argument info structures. This frees all the underlying memory and clears the members.
Definition at line 100 of file TypesC.cpp.
References i, and SoapySDRArgInfo_clear().
Referenced by SoapySDR.SoapySDRArgInfoList::clear().
void SoapySDRKwargs_clear (SoapySDRKwargs * args)
Clear the contents of a kwargs structure. This frees all the underlying memory and clears the members.
Definition at line 63 of file TypesC.cpp.
References SoapySDRKwargs::keys, SoapySDRKwargs::size, SoapySDRStrings_clear(), and SoapySDRKwargs::vals.
Referenced by SoapySDR.SoapySDRKwargs::clear(), and SoapySDRKwargsList_clear().
SoapySDRKwargs SoapySDRKwargs_fromString (const char * markup)
Convert a markup string to a key-value map. The markup format is: "key0=value0, key1=value1"
Definition at line 11 of file TypesC.cpp.
References SoapySDR::KwargsFromString, and toKwargs().
const char* SoapySDRKwargs_get (SoapySDRKwargs * args, const char * key)
Get a value given a key in a kwargs structure.
Returns
the string or NULL if not found
Definition at line 51 of file TypesC.cpp.
References i, SoapySDRKwargs::keys, SoapySDRKwargs::size, and SoapySDRKwargs::vals.
void SoapySDRKwargs_set (SoapySDRKwargs * args, const char * key, const char * val)
Set a key/value pair in a kwargs structure.
Definition at line 31 of file TypesC.cpp.
References i, SoapySDRKwargs::keys, SoapySDRKwargs::size, and SoapySDRKwargs::vals.
Referenced by toKwargs().
char* SoapySDRKwargs_toString (const SoapySDRKwargs * args)
Convert a key-value map to a markup string. The markup format is: "key0=value0, key1=value1"
Definition at line 16 of file TypesC.cpp.
References SoapySDR::KwargsToString, and toKwargs().
void SoapySDRKwargsList_clear (SoapySDRKwargs * args, const size_t length)
Clear a list of kwargs structures. This frees all the underlying memory and clears the members.
Definition at line 70 of file TypesC.cpp.
References i, and SoapySDRKwargs_clear().
Referenced by SoapySDR.SoapySDRKwargsList::clear().
void SoapySDRStrings_clear (char *** elems, const size_t length)
Clear the contents of a list of string Convenience call to deal with results that return a string list.
Definition at line 21 of file TypesC.cpp.
References i.
Referenced by SoapySDRArgInfo_clear(), and SoapySDRKwargs_clear().