LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/CMakeLists.txt File Reference
Functions
set (LIME_SUITE_PUBLIC_HEADERS lime/LimeSuite.h VersionInfo.h Logger.h SystemResources.h LimeSuiteConfig.h ADF4002/ADF4002.h lms7002m_mcu/MCU_BD.h lms7002m_mcu/MCU_File.h ConnectionRegistry/IConnection.h ConnectionRegistry/ConnectionHandle.h ConnectionRegistry/ConnectionRegistry.h lms7002m/LMS7002M.h lms7002m/LMS7002M_RegistersMap.h lime/LMS7002M_parameters.h protocols/Streamer.h protocols/ADCUnits.h protocols/LMS64CCommands.h protocols/LMS64CProtocol.h protocols/LMSBoards.h protocols/dataTypes.h protocols/fifo.h Si5351C/Si5351C.h FPGA_common/FPGA_common.h API/lms7_device.h) include(FeatureSummary) include(CMakeDependentOption) cmake_dependent_option(ENABLE_HEADERS"Enable install headers"ON"TRUE"OFF) add_feature_info(LimeSuiteHeaders ENABLE_HEADERS"The lime suite headers") if(ENABLE_HEADERS) install(FILES $
DESTINATION include lime endif () set(LIME_SUITE_SOURCES Logger.cpp ADF4002/ADF4002.cpp lms7002m_mcu/MCU_BD.cpp ConnectionRegistry/IConnection.cpp ConnectionRegistry/ConnectionHandle.cpp ConnectionRegistry/ConnectionRegistry.cpp lms7002m/LMS7002M_RegistersMap.cpp lms7002m/LMS7002M_parameters.cpp lms7002m/LMS7002M.cpp lms7002m/LMS7002M_RxTxCalibrations.cpp lms7002m/LMS7002M_BaseCalibrations.cpp lms7002m/goert.cpp lms7002m/mcu_dc_iq_calibration.cpp lms7002m/LMS7002M_filtersCalibration.cpp lms7002m/LMS7002M_gainCalibrations.cpp protocols/LMS64CProtocol.cpp protocols/Streamer.cpp protocols/ConnectionImages.cpp Si5351C/Si5351C.cpp $
external kissFFT kiss_fft c API lms7_api cpp API lms7_device cpp API LmsGeneric cpp API qLimeSDR cpp API LimeSDR_mini cpp API LimeSDR cpp FPGA_common FPGA_common cpp FPGA_common FPGA_Mini cpp FPGA_common FPGA_Q cpp windowFunction cpp set (LIME_SUITE_INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}API lime GFIR protocols ConnectionRegistry lms7002m_mcu ADF4002 Si5351C lms7002m LTEpackets FPGA_common lms7002m_mcu ${PROJECT_SOURCE_DIR}/external/cpp-feather-ini-parser HPM7 ${PROJECT_SOURCE_DIR}/external/kissFFT/) configure_file($
Function Documentation
endif ()
Definition at line 40 of file CMakeLists.txt.
References kiss_fft().
Referenced by cmake_policy(), install(), set(), SwigPyObject_TypeOnce(), SwigPyPacked_TypeOnce(), target_compile_definitions(), and target_include_directories().
set (LIME_SUITE_PUBLIC_HEADERS lime/LimeSuite.h VersionInfo.h Logger.h SystemResources.h LimeSuiteConfig.h ADF4002/ADF4002.h lms7002m_mcu/MCU_BD.h lms7002m_mcu/MCU_File.h ConnectionRegistry/IConnection.h ConnectionRegistry/ConnectionHandle.h ConnectionRegistry/ConnectionRegistry.h lms7002m/LMS7002M.h lms7002m/LMS7002M_RegistersMap.h lime/LMS7002M_parameters.h protocols/Streamer.h protocols/ADCUnits.h protocols/LMS64CCommands.h protocols/LMS64CProtocol.h protocols/LMSBoards.h protocols/dataTypes.h protocols/fifo.h Si5351C/Si5351C.h FPGA_common/FPGA_common.h API/lms7_device. h)
Definition at line 4 of file CMakeLists.txt.
References include().
Referenced by radar_swig::_swig_setattr_nondynamic_method(), doxyxml.base.Base::get_member(), swig_doc::make_swig_interface_file(), and doxyxml.base.Base::process_memberdefs().
external kissFFT kiss_fft c API lms7_api cpp API lms7_device cpp API LmsGeneric cpp API qLimeSDR cpp API LimeSDR_mini cpp API LimeSDR cpp FPGA_common FPGA_common cpp FPGA_common FPGA_Mini cpp FPGA_common FPGA_Q cpp windowFunction cpp set (LIME_SUITE_INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}API lime GFIR protocols ConnectionRegistry lms7002m_mcu ADF4002 Si5351C lms7002m LTEpackets FPGA_common lms7002m_mcu ${PROJECT_SOURCE_DIR}/external/cpp-feather-ini-parser HPM7 ${PROJECT_SOURCE_DIR}/external/kissFFT/)
Definition at line 78 of file CMakeLists.txt.
References add_feature_info(), add_library(), cmake_dependent_option(), endif(), file(), find_package(), include(), include_directories(), install(), kiss_fft(), list(), message(), top_block::parser, pthread, target_compile_definitions(), target_include_directories(), target_link_libraries(), and target_sources().