LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/rounding.h File Reference
rounding.h File Reference
Functions
void round2int (double *a, double *b, int n, int cprec)
void round2csd (double *a, double *b, int n, int cprec, int csdprec, int **bincode, int **csdcode, int **csdcoder)
Function Documentation
void round2csd (double * a, double * b, int n, int cprec, int csdprec, int ** bincode, int ** csdcode, int ** csdcoder)
Definition at line 35 of file rounding.c.
References csd2int(), i, int(), int2csd(), k, and dfilter::n.
Referenced by lms().
void round2int (double * a, double * b, int n, int cprec)
Definition at line 20 of file rounding.c.
References i, int(), k, and dfilter::n.
Referenced by lms().