LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/SoapyLMS7/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/SoapyLMS7/CMakeLists.txt File Reference
Functions
find_package (SoapySDR CONFIG) include(FeatureSummary) include(CMakeDependentOption) cmake_dependent_option(ENABLE_SOAPY_LMS7"Enable LMS7 SoapySDR bindings"ON"ENABLE_LIBRARY
Function Documentation
find_package (SoapySDR CONFIG)
Referenced by install(), set(), and target_link_libraries().