LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/apps/msvc/getopt.h File Reference
getopt.h File Reference
#include <crtdefs.h>
#include <errno.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>
#include <stdio.h>
#include <windows.h>
Classes
struct option
Macros
#define __GETOPT_H__
DISCLAIMER This file has no copyright assigned and is placed in the Public Domain.
#define REPLACE_GETOPT /* use this getopt as the system getopt(3) */
#define optreset __mingw_optreset
#define PRINT_ERROR ((opterr) && (*options != ':'))
#define FLAG_PERMUTE 0x01 /* permute non-options to the end of argv */
#define FLAG_ALLARGS 0x02 /* treat non-options as args to option "-1" */
#define FLAG_LONGONLY 0x04 /* operate as getopt_long_only */
#define BADCH (int)'?'
#define BADARG ((*options == ':') ? (int)':' : (int)'?')
#define INORDER (int)1
#define __progname __argv[0]
#define EMSG ""
#define __GETOPT_LONG_H__
#define IDENTICAL_INTERPRETATION(_x, _y)
#define HAVE_DECL_GETOPT 1
Enumerations
enum { no_argument = 0, required_argument, optional_argument }
Functions
static int getopt_internal (int, char *const *, const char *, const struct option *, int *, int)
static int parse_long_options (char *const *, const char *, const struct option *, int *, int)
static int gcd (int, int)
static void permute_args (int, int, int, char *const *)
static void _vwarnx (const char *fmt, va_list ap)
static void warnx (const char *fmt,...)
int getopt (int nargc, char *const *nargv, const char *options)
int getopt_long (int nargc, char *const *nargv, const char *options, const struct option *long_options, int *idx)
int getopt_long_only (int nargc, char *const *nargv, const char *options, const struct option *long_options, int *idx)
Variables
int opterr = 1
int optind = 1
int optopt = '?'
int __mingw_optreset
char * optarg
static char * place = ""
static int nonopt_start = -1
static int nonopt_end = -1
static const char recargchar [] = "option requires an argument -- %c"
static const char recargstring [] = "option requires an argument -- %s"
static const char ambig [] = "ambiguous option -- %.*s"
static const char noarg [] = "option doesn't take an argument -- %.*s"
static const char illoptchar [] = "unknown option -- %c"
static const char illoptstring [] = "unknown option -- %s"
Macro Definition Documentation
#define __GETOPT_H__
DISCLAIMER This file has no copyright assigned and is placed in the Public Domain.
This file is part of the mingw-w64 runtime package.
The mingw-w64 runtime package and its code is distributed in the hope that it will be useful but WITHOUT ANY WARRANTY. ALL WARRANTIES, EXPRESSED OR IMPLIED ARE HEREBY DISCLAIMED. This includes but is not limited to warranties of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Definition at line 15 of file getopt.h.
#define __GETOPT_LONG_H__
Definition at line 216 of file getopt.h.
#define __progname __argv[0]
Definition at line 61 of file getopt.h.
#define BADARG ((*options == ':') ? (int)':' : (int)'?')
Definition at line 57 of file getopt.h.
Referenced by getopt_internal(), and parse_long_options().
#define BADCH (int)'?'
Definition at line 56 of file getopt.h.
Referenced by getopt_internal(), and parse_long_options().
#define EMSG ""
Definition at line 69 of file getopt.h.
Referenced by getopt_internal().
#define FLAG_ALLARGS 0x02 /* treat non-options as args to option "-1" */
Definition at line 52 of file getopt.h.
Referenced by getopt_internal().
#define FLAG_LONGONLY 0x04 /* operate as getopt_long_only */
Definition at line 53 of file getopt.h.
Referenced by getopt_internal(), and getopt_long_only().
#define FLAG_PERMUTE 0x01 /* permute non-options to the end of argv */
Definition at line 51 of file getopt.h.
Referenced by getopt_internal(), getopt_long(), and getopt_long_only().
#define HAVE_DECL_GETOPT 1
Definition at line 600 of file getopt.h.
#define IDENTICAL_INTERPRETATION (_x, _y)
Value:
(long_options[(_x)].has_arg == long_options[(_y)].has_arg &&    \
     long_options[(_x)].flag == long_options[(_y)].flag &&          \
     long_options[(_x)].val == long_options[(_y)].val)
Referenced by parse_long_options().
#define INORDER (int)1
Definition at line 58 of file getopt.h.
Referenced by getopt_internal().
#define optreset __mingw_optreset
Definition at line 37 of file getopt.h.
Referenced by getopt(), and getopt_internal().
#define PRINT_ERROR ((opterr) && (*options != ':'))
Definition at line 49 of file getopt.h.
Referenced by getopt_internal(), and parse_long_options().
#define REPLACE_GETOPT /* use this getopt as the system getopt(3) */
Definition at line 30 of file getopt.h.
Enumeration Type Documentation
anonymous enum
Enumerator
no_argument
required_argument
optional_argument
Definition at line 230 of file getopt.h.
Function Documentation
static void _vwarnx (const char * fmt, va_list ap) static
Definition at line 94 of file getopt.h.
References void().
Referenced by warnx().
static int gcd (int a, int b) static
Definition at line 115 of file getopt.h.
References b, and c.
Referenced by permute_args().
int getopt (int nargc, char *const * nargv, const char * options)
Definition at line 174 of file getopt.h.
References getopt_internal(), and optreset.
static int getopt_internal (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx, int flags) static
Definition at line 371 of file getopt.h.
References BADARG, BADCH, EMSG, FLAG_ALLARGS, FLAG_LONGONLY, FLAG_PERMUTE, illoptchar, INORDER, nonopt_end, nonopt_start, optarg, optind, optopt, optreset, parse_long_options(), permute_args(), place, PRINT_ERROR, recargchar, and warnx().
Referenced by getopt(), getopt_long(), and getopt_long_only().
int getopt_long (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx)
Definition at line 568 of file getopt.h.
References FLAG_PERMUTE, and getopt_internal().
int getopt_long_only (int nargc, char *const * nargv, const char * options, const struct option * long_options, int * idx)
Definition at line 581 of file getopt.h.
References FLAG_LONGONLY, FLAG_PERMUTE, and getopt_internal().
static int parse_long_options (char *const * nargv, const char * options, const struct option * long_options, int * idx, int short_too) static
Definition at line 243 of file getopt.h.
References ambig, BADARG, BADCH, option::flag, option::has_arg, i, IDENTICAL_INTERPRETATION, illoptstring, option::name, no_argument, noarg, optarg, optind, optional_argument, optopt, place, PRINT_ERROR, recargstring, required_argument, option::val, and warnx().
Referenced by getopt_internal().
static void permute_args (int panonopt_start, int panonopt_end, int opt_end, char *const * nargv) static
Definition at line 135 of file getopt.h.
References gcd(), and i.
Referenced by getopt_internal().
static void warnx (const char * fmt, ...) static
Definition at line 103 of file getopt.h.
References _vwarnx(), and ap.
Referenced by getopt_internal(), and parse_long_options().
Variable Documentation
int __mingw_optreset
Definition at line 38 of file getopt.h.
const char ambig[] = "ambiguous option -- %.*s" static
Definition at line 88 of file getopt.h.
Referenced by parse_long_options().
const char illoptchar[] = "unknown option -- %c" static
Definition at line 90 of file getopt.h.
Referenced by getopt_internal().
const char illoptstring[] = "unknown option -- %s" static
Definition at line 91 of file getopt.h.
Referenced by parse_long_options().
const char noarg[] = "option doesn't take an argument -- %.*s" static
Definition at line 89 of file getopt.h.
Referenced by parse_long_options().
int nonopt_end = -1 static
Definition at line 83 of file getopt.h.
Referenced by getopt_internal().
int nonopt_start = -1 static
Definition at line 82 of file getopt.h.
Referenced by getopt_internal().
char* optarg
Definition at line 39 of file getopt.h.
int opterr = 1
Definition at line 33 of file getopt.h.
int optind = 1
Definition at line 34 of file getopt.h.
int optopt = '?'
Definition at line 35 of file getopt.h.
char* place = "" static
Definition at line 79 of file getopt.h.
Referenced by getopt_internal(), and parse_long_options().
const char recargchar[] = "option requires an argument -- %c" static
Definition at line 86 of file getopt.h.
Referenced by getopt_internal().
const char recargstring[] = "option requires an argument -- %s" static
Definition at line 87 of file getopt.h.
Referenced by parse_long_options().