LimeSuite-UML: lime::ConnectionSTREAM_UNITE Class Reference
lime::ConnectionSTREAM_UNITE Class Reference
#include <ConnectionSTREAM_UNITE.h>
Public Member Functions
ConnectionSTREAM_UNITE (void *ctx, const std::string &vidpid, const std::string &serial, const unsigned index, const char *comPortName=nullptr)
virtual ~ConnectionSTREAM_UNITE (void)
virtual DeviceInfo GetDeviceInfo (void) override
virtual int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size) override
Bulk SPI write/read transaction.
virtual int DeviceReset (int ind=0) override
virtual int TransferPacket (GenericPacket &pkt) override
Transfers data between packet and connected device.
Public Member Functions inherited from lime::ConnectionFX3
ConnectionFX3 (void *arg, const std::string &vidpid, const std::string &serial, const unsigned index)
Initializes port type and object necessary to communicate to usb device.
~ConnectionFX3 (void)
Closes connection to chip and deallocates used memory.
int Open (const std::string &vidpid, const std::string &serial, const unsigned index)
Tries to open connected USB device and find communication endpoints.
void Close ()
Closes communication to device.
bool IsOpen ()
Returns connection status.
int GetOpenedIndex ()
int Write (const unsigned char *buffer, int length, int timeout_ms=100) override
Sends given data buffer to chip through USB port.
int Read (unsigned char *buffer, int length, int timeout_ms=100) override
Reads data coming from the chip through USB port.
int ProgramWrite (const char *buffer, const size_t length, const int programmingMode, const int device, ProgrammingCallback callback) override
Uploads program to selected device.
Public Member Functions inherited from lime::LMS64CProtocol
LMS64CProtocol (void)
virtual ~LMS64CProtocol (void)
int DeviceReset (int ind=0)
DeviceReset implemented by LMS64C.
int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size) override
TransactSPI implemented by LMS64C.
int WriteI2C (const int addr, const std::string &data)
WriteI2C implemented by LMS64C.
int ReadI2C (const int addr, const size_t numBytes, std::string &data)
ReadI2C implemented by LMS64C.
int WriteRegisters (const uint32_t *addrs, const uint32_t *data, const size_t size)
WriteRegisters (BRDSPI) implemented by LMS64C.
int ReadRegisters (const uint32_t *addrs, uint32_t *data, const size_t size)
ReadRegisters (BRDSPI) implemented by LMS64C.
LMSinfo GetInfo ()
Returns connected device information.
FPGAinfo GetFPGAInfo ()
Returns information from FPGA gateware.
void VersionCheck ()
int ProgramUpdate (const bool download, IConnection::ProgrammingCallback callback) override
virtual int CustomParameterRead (const uint8_t *ids, double *values, const size_t count, std::string *units) override
Returns value of custom on board control.
virtual int CustomParameterWrite (const uint8_t *ids, const double *values, const size_t count, const std::string &units) override
Sets custom on board control to given value units.
virtual int GPIOWrite (const uint8_t *buffer, const size_t bufLength) override
Writes GPIO values to device.
virtual int GPIORead (uint8_t *buffer, const size_t bufLength) override
Reads GPIO values from device.
virtual int GPIODirWrite (const uint8_t *buffer, const size_t bufLength) override
Write GPIO direction control values to device.
virtual int GPIODirRead (uint8_t *buffer, const size_t bufLength) override
Read GPIO direction configuration from device.
int ProgramMCU (const uint8_t *buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback) override
Uploads program to MCU.
int WriteLMS7002MSPI (const uint32_t *writeData, size_t size, unsigned periphID=0) override
int ReadLMS7002MSPI (const uint32_t *writeData, uint32_t *readData, size_t size, unsigned periphID=0) override
Public Member Functions inherited from lime::IConnection
IConnection (void)
IConnection constructor.
virtual ~IConnection (void)
IConnection destructor.
const ConnectionHandle & GetHandle (void) const
Get the connection handle that was used to create this connection.
int WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
template<typename ReadType >
int ReadRegister (const uint32_t addr, ReadType &data)
Read a single device register.
void SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Protected Attributes
ConnectionEVB7COM * comPort
Protected Attributes inherited from lime::ConnectionFX3
USBTransferContext contexts [USB_MAX_CONTEXTS]
USBTransferContext contextsToSend [USB_MAX_CONTEXTS]
bool isConnected
CCyFX3Device * USBDevicePrimary
CCyControlEndPoint * InCtrlEndPt3
CCyControlEndPoint * OutCtrlEndPt3
CCyUSBEndPoint * InEndPt [MAX_EP_CNT]
CCyUSBEndPoint * OutEndPt [MAX_EP_CNT]
CCyUSBEndPoint * InCtrlBulkEndPt
CCyUSBEndPoint * OutCtrlBulkEndPt
std::set< uint8_t > commandsToBulkCtrl
bool bulkCtrlInProgress
bool bulkCtrlAvailable
std::mutex mExtraUsbMutex
Protected Attributes inherited from lime::IConnection
std::function< void(bool, const unsigned char *, const unsigned int)> callback_logData
Additional Inherited Members
Public Types inherited from lime::LMS64CProtocol
enum eConnectionType {
CONNECTION_UNDEFINED = -1, COM_PORT = 0, USB_PORT = 1, SPI_PORT = 2,
PCIE_PORT = 3, CONNECTION_TYPES_COUNT
}
Supported connection types.
enum eLMS_PROTOCOL { LMS_PROTOCOL_UNDEFINED = 0, LMS_PROTOCOL_DIGIC, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA }
enum ProgramWriteTarget { HPM, FX3, FPGA, PROGRAM_WRITE_TARGET_COUNT }
Public Types inherited from lime::IConnection
enum MCU_PROG_MODE { RESET = 0, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM }
typedef std::function< bool(int bsent, int btotal, const char *progressMsg)> ProgrammingCallback
Protected Member Functions inherited from lime::ConnectionFX3
int GetBuffersCount () const
int CheckStreamSize (int size) const
int SendData (const char *buffer, int length, int epIndex=0, int timeout=100) override
int ReceiveData (char *buffer, int length, int epIndex=0, int timeout=100) override
int BeginDataReading (char *buffer, uint32_t length, int ep) override
Starts asynchronous data reading from board.
bool WaitForReading (int contextHandle, unsigned int timeout_ms) override
Waits for asynchronous data reception.
int FinishDataReading (char *buffer, uint32_t length, int contextHandle) override
Finishes asynchronous data reading from board.
void AbortReading (int ep) override
Aborts reading operations.
int BeginDataSending (const char *buffer, uint32_t length, int ep) override
Starts asynchronous data Sending to board.
bool WaitForSending (int contextHandle, uint32_t timeout_ms) override
Waits for asynchronous data sending.
int FinishDataSending (const char *buffer, uint32_t length, int contextHandle) override
Finishes asynchronous data sending to board.
void AbortSending (int ep) override
Aborts sending operations.
int ResetStreamBuffers () override
Read raw stream data from device streaming port.
eConnectionType GetType (void)
implement in base class
Static Protected Attributes inherited from lime::ConnectionFX3
static const int USB_MAX_CONTEXTS = 16
static const int MAX_EP_CNT = 16
static const uint8_t ctrlBulkOutAddr = 0x0F
static const uint8_t ctrlBulkInAddr = 0x8F
static const std::set< uint8_t > commandsToBulkCtrlHw1
static const std::set< uint8_t > commandsToBulkCtrlHw2
Detailed Description
Definition at line 15 of file ConnectionSTREAM_UNITE.h.
Constructor & Destructor Documentation
lime::ConnectionSTREAM_UNITE::ConnectionSTREAM_UNITE (void * ctx, const std::string & vidpid, const std::string & serial, const unsigned index, const char * comPortName = nullptr)
Definition at line 13 of file ConnectionSTREAM_UNITE.cpp.
References comPort, and lime::ConnectionEVB7COM::IsOpen().
lime::ConnectionSTREAM_UNITE::~ConnectionSTREAM_UNITE (void) virtual
Definition at line 28 of file ConnectionSTREAM_UNITE.cpp.
References comPort.
Member Function Documentation
int lime::ConnectionSTREAM_UNITE::DeviceReset (int ind = 0) override virtual
Perform reset sequence on the device. Typically this will reset the RFIC using a GPIO, and possibly other ICs located on the device.
Reimplemented from lime::IConnection.
Definition at line 56 of file ConnectionSTREAM_UNITE.cpp.
References comPort, lime::LMS64CProtocol::DeviceReset(), and status.
DeviceInfo lime::ConnectionSTREAM_UNITE::GetDeviceInfo (void) override virtual
Get information about a device for displaying helpful information or for making device-specific decisions.
Reimplemented from lime::LMS64CProtocol.
Definition at line 34 of file ConnectionSTREAM_UNITE.cpp.
References comPort, lime::DeviceInfo::deviceName, and lime::LMS64CProtocol::GetDeviceInfo().
int lime::ConnectionSTREAM_UNITE::TransactSPI (const int addr, const uint32_t * writeData, uint32_t * readData, const size_t size) override virtual
Bulk SPI write/read transaction.
The transactSPI function is capable of bulk writes and bulk reads of SPI registers in an arbitrary IC (up to 32-bits per transaction).
The readData parameter may be NULL to indicate a write-only operation, the underlying implementation may be able to optimize out the readback.
Parameters
addr the SPI device address
writeData SPI bits to write out
[out] readData stores readback data
size the number of SPI transactions
Returns
the transaction success state
Reimplemented from lime::IConnection.
Definition at line 46 of file ConnectionSTREAM_UNITE.cpp.
References comPort, and lime::LMS64CProtocol::TransactSPI().
int lime::ConnectionSTREAM_UNITE::TransferPacket (GenericPacket & pkt) override virtual
Transfers data between packet and connected device.
Transfer a packet over the underlying transport layer. TransferPacket performs a request/response using the GenericPacket data structure. Some implementations will cast to LMS64CProtocol and directly use the TransferPacket() API call.
Parameters
pkt packet containing output data and to receive incomming data
Returns
0: success, other: failure
Reimplemented from lime::LMS64CProtocol.
Definition at line 67 of file ConnectionSTREAM_UNITE.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_LMS7002_RD, lime::CMD_LMS7002_WR, lime::CMD_PROG_MCU, comPort, and lime::LMS64CProtocol::TransferPacket().
Member Data Documentation
ConnectionEVB7COM* lime::ConnectionSTREAM_UNITE::comPort protected
Definition at line 26 of file ConnectionSTREAM_UNITE.h.
Referenced by ConnectionSTREAM_UNITE(), DeviceReset(), GetDeviceInfo(), TransactSPI(), TransferPacket(), and ~ConnectionSTREAM_UNITE().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionSTREAM_UNITE/ConnectionSTREAM_UNITE.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionSTREAM_UNITE/ConnectionSTREAM_UNITE.cpp