LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/TypeHelpers.hpp File Reference
TypeHelpers.hpp File Reference
#include <SoapySDR/Config.hpp>
#include <SoapySDR/Types.hpp>
#include <SoapySDR/Types.h>
#include <vector>
#include <string>
#include <cstdlib>
#include <cstring>
Functions
static char ** toStrArray (const std::vector< std::string > &strs, size_t *length)
static SoapySDRRange toRange (const SoapySDR::Range &range)
static SoapySDRRange * toRangeList (const SoapySDR::RangeList &ranges, size_t *length)
static double * toNumericList (const std::vector< double > &values, size_t *length)
static SoapySDR::Kwargs toKwargs (const SoapySDRKwargs *args)
static SoapySDRKwargs toKwargs (const SoapySDR::Kwargs &args)
static SoapySDRKwargs * toKwargsList (const SoapySDR::KwargsList &args, size_t *length)
static SoapySDRArgInfo toArgInfo (const SoapySDR::ArgInfo &info)
static SoapySDRArgInfo * toArgInfoList (const SoapySDR::ArgInfoList &infos, size_t *length)
static std::vector< unsigned > toNumericVector (const unsigned *values, size_t length)
static unsigned * toNumericList (const std::vector< unsigned > &values, size_t *length)
Function Documentation
static SoapySDRArgInfo toArgInfo (const SoapySDR::ArgInfo & info) inline static
Definition at line 82 of file TypeHelpers.hpp.
References SoapySDRArgInfo::description, SoapySDR.ArgInfo::description, SoapySDRArgInfo::key, SoapySDR.ArgInfo::key, SoapySDRArgInfo::name, SoapySDR.ArgInfo::name, SoapySDRArgInfo::numOptions, SoapySDRArgInfo::optionNames, SoapySDR.ArgInfo::optionNames, SoapySDRArgInfo::options, SoapySDR.ArgInfo::options, SoapySDRArgInfo::range, SoapySDR.ArgInfo::range, toRange(), toStrArray(), SoapySDRArgInfo::type, SoapySDR.ArgInfo::type, SoapySDRArgInfo::units, and SoapySDR.ArgInfo::units.
Referenced by SoapySDRDevice_getChannelSensorInfo(), SoapySDRDevice_getSensorInfo(), and toArgInfoList().
static SoapySDRArgInfo* toArgInfoList (const SoapySDR::ArgInfoList & infos, size_t * length) inline static
Definition at line 97 of file TypeHelpers.hpp.
References i, and toArgInfo().
Referenced by SoapySDRDevice_getChannelSettingInfo(), SoapySDRDevice_getFrequencyArgsInfo(), SoapySDRDevice_getSettingInfo(), and SoapySDRDevice_getStreamArgsInfo().
static SoapySDR::Kwargs toKwargs (const SoapySDRKwargs * args) inline static
Definition at line 52 of file TypeHelpers.hpp.
References i, SoapySDRKwargs::keys, SoapySDRKwargs::size, and SoapySDRKwargs::vals.
Referenced by SoapySDR_getLoaderResult(), SoapySDRDevice_enumerate(), SoapySDRDevice_getChannelInfo(), SoapySDRDevice_getHardwareInfo(), SoapySDRDevice_make(), SoapySDRDevice_setFrequency(), SoapySDRDevice_setFrequencyComponent(), SoapySDRDevice_setupStream(), SoapySDRKwargs_fromString(), SoapySDRKwargs_toString(), and toKwargsList().
static SoapySDRKwargs toKwargs (const SoapySDR::Kwargs & args) inline static
Definition at line 63 of file TypeHelpers.hpp.
References SoapySDRKwargs_set().
static SoapySDRKwargs* toKwargsList (const SoapySDR::KwargsList & args, size_t * length) inline static
Definition at line 74 of file TypeHelpers.hpp.
References i, and toKwargs().
Referenced by SoapySDRDevice_enumerate(), and SoapySDRDevice_enumerateStrArgs().
static double* toNumericList (const std::vector< double > & values, size_t * length) inline static
Definition at line 44 of file TypeHelpers.hpp.
References i.
Referenced by SoapySDRDevice_listBandwidths(), SoapySDRDevice_listSampleRates(), and SoapySDRDevice_readRegisters().
static unsigned* toNumericList (const std::vector< unsigned > & values, size_t * length) inline static
Definition at line 115 of file TypeHelpers.hpp.
References i.
static std::vector<unsigned> toNumericVector (const unsigned * values, size_t length) inline static
Definition at line 108 of file TypeHelpers.hpp.
References i.
Referenced by SoapySDRDevice_writeRegisters().
static SoapySDRRange toRange (const SoapySDR::Range & range) inline static
Definition at line 27 of file TypeHelpers.hpp.
References SoapySDRRange::maximum, SoapySDR.Range::maximum(), SoapySDRRange::minimum, SoapySDR.Range::minimum(), SoapySDRRange::step, and SoapySDR.Range::step().
Referenced by SoapySDRDevice_getGainElementRange(), SoapySDRDevice_getGainRange(), toArgInfo(), and toRangeList().
static SoapySDRRange* toRangeList (const SoapySDR::RangeList & ranges, size_t * length) inline static
Definition at line 36 of file TypeHelpers.hpp.
References i, and toRange().
Referenced by SoapySDRDevice_getBandwidthRange(), SoapySDRDevice_getFrequencyRange(), SoapySDRDevice_getFrequencyRangeComponent(), SoapySDRDevice_getMasterClockRates(), and SoapySDRDevice_getSampleRateRange().
static char** toStrArray (const std::vector< std::string > & strs, size_t * length) inline static
Definition at line 16 of file TypeHelpers.hpp.
References i.
Referenced by SoapySDR_listModules(), SoapySDR_listModulesPath(), SoapySDR_listSearchPaths(), SoapySDRDevice_getStreamFormats(), SoapySDRDevice_listAntennas(), SoapySDRDevice_listChannelSensors(), SoapySDRDevice_listClockSources(), SoapySDRDevice_listFrequencies(), SoapySDRDevice_listGains(), SoapySDRDevice_listGPIOBanks(), SoapySDRDevice_listRegisterInterfaces(), SoapySDRDevice_listSensors(), SoapySDRDevice_listTimeSources(), SoapySDRDevice_listUARTs(), and toArgInfo().