LimeSuite-UML: /home/erik/prefix/default/src/gr-radar-dev/lib/CMakeLists.txt File Reference
/home/erik/prefix/default/src/gr-radar-dev/lib/CMakeLists.txt File Reference
Functions
set (QTGUI_MOC_HEADERS scatter_plot.h time_plot.h spectrogram_plot.h) include(GrPlatform) include_directories($
link_directories (${Boost_LIBRARY_DIRS}) list(APPEND radar_sources $
scatter_plot cc time_plot cc spectrogram_plot cc signal_generator_cw_c_impl cc signal_generator_fmcw_c_impl cc split_cc_impl cc os_cfar_c_impl cc ts_fft_cc_impl cc estimator_cw_impl cc print_results_impl cc static_target_simulator_cc_impl cc signal_generator_fsk_c_impl cc split_fsk_cc_impl cc estimator_fsk_impl cc usrp_echotimer_cc_impl cc estimator_fmcw_impl cc signal_generator_sync_pulse_c_impl cc estimator_sync_pulse_c_impl cc find_max_peak_c_impl cc qtgui_scatter_plot_impl cc qtgui_time_plot_impl cc tracking_singletarget_impl cc msg_gate_impl cc msg_manipulator_impl cc ofdm_cyclic_prefix_remover_cvc_impl cc transpose_matrix_vcvc_impl cc qtgui_spectrogram_plot_impl cc crop_matrix_vcvc_impl cc ofdm_divide_vcvc_impl cc os_cfar_2d_vc_impl cc estimator_ofdm_impl cc estimator_rcs_impl cc trigger_command_impl cc soapysdr_echotimer_impl cc gpio_source_s_impl cc soapysdr_echotimer_stretch_impl cc set (radar_sources"${radar_sources}"PARENT_SCOPE) if(NOT radar_sources) return() endif(NOT radar_sources) add_library(gnuradio-radar SHARED $
target_link_libraries (gnuradio-radar ${Boost_LIBRARIES}${GNURADIO_ALL_LIBRARIES}${FFTW3F_LIBRARIES}${QWT_LIBRARIES}${QT_LIBRARIES}${UHD_LIBRARIES}${SOAPY_SDR_LIBRARY}${VOLK_LIBRARIES}) set_target_properties(gnuradio-radar PROPERTIES DEFINE_SYMBOL"gnuradio_radar_EXPORTS") if(APPLE) set_target_properties(gnuradio-radar PROPERTIES INSTALL_NAME_DIR"$
lib endif (APPLE) install(TARGETS gnuradio-radar LIBRARY DESTINATION lib $
Function Documentation
lib endif (APPLE)
Definition at line 104 of file CMakeLists.txt.
References file(), include(), include_directories(), list(), radar, and target_link_libraries().
link_directories (${Boost_LIBRARY_DIRS})
Definition at line 38 of file CMakeLists.txt.
References list().
set (QTGUI_MOC_HEADERS scatter_plot.h time_plot.h spectrogram_plot. h)
Definition at line 23 of file CMakeLists.txt.
References include(), and include_directories().
scatter_plot cc time_plot cc spectrogram_plot cc signal_generator_cw_c_impl cc signal_generator_fmcw_c_impl cc split_cc_impl cc os_cfar_c_impl cc ts_fft_cc_impl cc estimator_cw_impl cc print_results_impl cc static_target_simulator_cc_impl cc signal_generator_fsk_c_impl cc split_fsk_cc_impl cc estimator_fsk_impl cc usrp_echotimer_cc_impl cc estimator_fmcw_impl cc signal_generator_sync_pulse_c_impl cc estimator_sync_pulse_c_impl cc find_max_peak_c_impl cc qtgui_scatter_plot_impl cc qtgui_time_plot_impl cc tracking_singletarget_impl cc msg_gate_impl cc msg_manipulator_impl cc ofdm_cyclic_prefix_remover_cvc_impl cc transpose_matrix_vcvc_impl cc qtgui_spectrogram_plot_impl cc crop_matrix_vcvc_impl cc ofdm_divide_vcvc_impl cc os_cfar_2d_vc_impl cc estimator_ofdm_impl cc estimator_rcs_impl cc trigger_command_impl cc soapysdr_echotimer_impl cc gpio_source_s_impl cc soapysdr_echotimer_stretch_impl cc set (radar_sources"${radar_sources}" PARENT_SCOPE)
Definition at line 79 of file CMakeLists.txt.
target_link_libraries (gnuradio-radar ${Boost_LIBRARIES}${GNURADIO_ALL_LIBRARIES}${FFTW3F_LIBRARIES}${QWT_LIBRARIES}${QT_LIBRARIES}${UHD_LIBRARIES}${SOAPY_SDR_LIBRARY}${VOLK_LIBRARIES})
Definition at line 88 of file CMakeLists.txt.
References radar.