LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/octave/rx_2ch.m File Reference
rx_2ch.m File Reference
Functions
LoadLimeSuite LimeInitialize ()
open first device LimeLoadConfig ('trxTest.ini')
samples to read (64K) fifoSize
read samples from RX channel end stop streaming LimeStopStreaming ()
stop streaming LimeDestroy ()
close device plot samples figure (1) plot(real(samplesCh0))
figure (2) plot(real(samplesCh1))
Variables
clear all
load configuration from file use LimeSuiteGUI to create configuration file readCnt = 1024*64
start RX from channels and receive samples
start RX from channels and receive overwrite the same array for i
read samples from RX channel samplesCh1 = LimeReceiveSamples(readCnt,1)
Function Documentation
close device plot samples figure (1)
figure (2)
stop streaming LimeDestroy ()
LoadLimeSuite LimeInitialize ()
open first device LimeLoadConfig ('trxTest.ini')
read samples from RX channel end stop streaming LimeStopStreaming ()
samples to read (64K)
Referenced by main(), lime::ConnectionXillybus::Read(), lime::ConnectionEVB7COM::Read(), lime::ConnectionXillybus::ReceiveData(), and lime::ConnectionNovenaRF7::Write().
Variable Documentation
clear all
Definition at line 1 of file rx_2ch.m.
start RX from channels and receive overwrite the same array for i
Initial value:
=1:16
    samplesCh0 = LimeReceiveSamples(readCnt,0)
Definition at line 16 of file rx_2ch.m.
load configuration from file use LimeSuiteGUI to create configuration file readCnt = 1024*64
Definition at line 10 of file rx_2ch.m.
start RX from channels and receive samples
Definition at line 15 of file rx_2ch.m.
read samples from RX channel samplesCh1 = LimeReceiveSamples(readCnt,1)
Definition at line 18 of file rx_2ch.m.