LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/apps/SoapySDRProbe.cpp File Reference
SoapySDRProbe.cpp File Reference
#include <SoapySDR/Device.hpp>
#include <sstream>
Functions
template<typename Type >
std::string toString (const std::vector< Type > &options)
std::string toString (const SoapySDR::Range &range)
std::string toString (const SoapySDR::RangeList &range, const double scale)
std::string toString (const std::vector< double > &nums, const double scale)
std::string toString (const SoapySDR::ArgInfo &argInfo, const std::string indent=" ")
std::string toString (const SoapySDR::ArgInfoList &argInfos)
static std::string probeChannel (SoapySDR::Device *device, const int dir, const size_t chan)
std::string SoapySDRDeviceProbe (SoapySDR::Device *device)
Function Documentation
static std::string probeChannel (SoapySDR::Device * device, const int dir, const size_t chan) static
Definition at line 119 of file SoapySDRProbe.cpp.
References dirName, SoapySDR.Device::getBandwidthRange(), SoapySDR.Device::getChannelInfo(), SoapySDR.Device::getFrequencyArgsInfo(), SoapySDR.Device::getFrequencyRange(), SoapySDR.Device::getFullDuplex(), SoapySDR.Device::getGainRange(), SoapySDR.Device::getNativeStreamFormat(), SoapySDR.Device::getSampleRateRange(), SoapySDR.Device::getSettingInfo(), SoapySDR.Device::getStreamArgsInfo(), SoapySDR.Device::getStreamFormats(), SoapySDR.Device::hasDCOffset(), SoapySDR.Device::hasDCOffsetMode(), SoapySDR.Device::hasGainMode(), SoapySDR.Device::hasIQBalance(), i, info, SoapySDR.Device::listAntennas(), SoapySDR.Device::listFrequencies(), SoapySDR.Device::listGains(), SoapySDR.Device::listSensors(), SOAPY_SDR_TX, string(), and toString().
Referenced by SoapySDRDeviceProbe().
std::string SoapySDRDeviceProbe (SoapySDR::Device * device)
Definition at line 208 of file SoapySDRProbe.cpp.
References chan, SoapySDR.Device::getDriverKey(), SoapySDR.Device::getHardwareInfo(), SoapySDR.Device::getHardwareKey(), SoapySDR.Device::getNumChannels(), SoapySDR.Device::getSettingInfo(), SoapySDR.Device::hasHardwareTime(), SoapySDR.Device::listClockSources(), SoapySDR.Device::listGPIOBanks(), SoapySDR.Device::listRegisterInterfaces(), SoapySDR.Device::listSensors(), SoapySDR.Device::listTimeSources(), SoapySDR.Device::listUARTs(), probeChannel(), SOAPY_SDR_RX, SOAPY_SDR_TX, string(), and toString().
Referenced by probeDevice().
template<typename Type > std::string toString (const std::vector< Type > & options)
Definition at line 9 of file SoapySDRProbe.cpp.
References i.
Referenced by createIndent(), probeChannel(), SoapySDRDeviceProbe(), and toString().
std::string toString (const SoapySDR::Range & range)
Definition at line 21 of file SoapySDRProbe.cpp.
References SoapySDR.Range::maximum(), SoapySDR.Range::minimum(), and SoapySDR.Range::step().
std::string toString (const SoapySDR::RangeList & range, const double scale)
Definition at line 30 of file SoapySDRProbe.cpp.
References i.
std::string toString (const std::vector< double > & nums, const double scale)
Definition at line 48 of file SoapySDRProbe.cpp.
References i.
std::string toString (const SoapySDR::ArgInfo & argInfo, const std::string indent = " ")
Definition at line 66 of file SoapySDRProbe.cpp.
References SoapySDR.ArgInfo::BOOL, SoapySDR.ArgInfo::description, SoapySDR.ArgInfo::FLOAT, if(), SoapySDR.ArgInfo::INT, SoapySDR.ArgInfo::key, SoapySDR.ArgInfo::name, SoapySDR.ArgInfo::options, SoapySDR.ArgInfo::range, string(), SoapySDR.ArgInfo::STRING, toString(), SoapySDR.ArgInfo::type, SoapySDR.ArgInfo::units, and SoapySDR.ArgInfo::value.
std::string toString (const SoapySDR::ArgInfoList & argInfos)
Definition at line 107 of file SoapySDRProbe.cpp.
References i, and toString().