LimeSuite-UML: lms7002_pnlSX_view Class Reference
lms7002_pnlSX_view Class Reference
Implementing pnlSX_view.
#include <lms7002_pnlSX_view.h>
Public Member Functions
lms7002_pnlSX_view (wxWindow *parent)
Constructor.
lms7002_pnlSX_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlSX_view
pnlSX_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlSX_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void ParameterChangeHandler (wxSpinEvent &event)
void OnbtnReadComparators (wxCommandEvent &event)
void OnbtnChangeRefClkClick (wxCommandEvent &event)
void OnbtnCalculateClick (wxCommandEvent &event)
void OnbtnTuneClick (wxCommandEvent &event)
void OnShowVCOclicked (wxCommandEvent &event)
void OnEnableRefSpurCancelation (wxCommandEvent &event)
Protected Member Functions inherited from pnlSX_view
virtual void OnDIV2PrescalerChange (wxCommandEvent &event)
Protected Attributes
wxComboBox * cmbRZ_CTRL
wxComboBox * cmbCMPLO_CTRL
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlSX_view
wxCheckBox * chkPD_FBDIV
wxCheckBox * chkPD_LOCH_T2RBUF
wxCheckBox * chkPD_CP
wxCheckBox * chkPD_FDIV
wxCheckBox * chkPD_SDM
wxCheckBox * chkPD_VCO_COMP
wxCheckBox * chkPD_VCO
wxCheckBox * chkEN_G
wxCheckBox * chkEN_DIR_SXRSXT
wxCheckBox * chkRESET_N
wxCheckBox * chkSPDUP_VCO
wxCheckBox * chkBYPLDO_VCO
wxCheckBox * chkEN_COARSEPLL
wxCheckBox * chkCURLIM_VCO
wxCheckBox * chkREVPH_PFD
wxCheckBox * chkEN_INTONLY_SDM
wxCheckBox * chkEN_SDM_CLK
wxCheckBox * chkREV_SDMCLK
wxCheckBox * chkSX_DITHER_EN
wxCheckBox * chkEN_DIV2_DIVPROGenabled
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbTST_SX
wxStaticText * ID_STATICTEXT4
wxSpinCtrl * ctrPW_DIV2_LOCH
wxStaticText * ID_STATICTEXT5
wxSpinCtrl * ctrPW_DIV4_LOCH
wxStaticText * ID_STATICTEXT6
wxSpinCtrl * ctrDIV_LOCH
wxStaticText * ID_STATICTEXT18
wxComboBox * cmbCP2_PLL
wxStaticText * ID_STATICTEXT19
wxComboBox * cmbCP3_PLL
wxStaticText * ID_STATICTEXT20
wxComboBox * cmbCZ
wxRadioBox * rgrSEL_VCO
wxTextCtrl * txtFrequency
wxButton * btnCalculate
wxButton * btnTune
wxButton * ID_BUTTON5
wxPanel * pnlRefClkSpur
wxStaticBoxSizer * RefClkSpurSizer
wxCheckBox * chkEnableRefSpurCancelation
wxStaticText * m_staticText359
wxTextCtrl * txtRefSpurBW
wxStaticText * ID_STATICTEXT2
wxStaticText * lblINT_SDM
wxStaticText * ID_STATICTEXT21
wxStaticText * lblFRAC_SDM
wxStaticText * ID_STATICTEXT25
wxStaticText * lblRealOutFrequency
wxStaticText * ID_STATICTEXT23
wxStaticText * lblDivider
wxStaticText * ID_STATICTEXT30
wxStaticText * lblEN_DIV2_DIVPROG
wxButton * btnChangeRefClk
wxStaticText * lblRefClk_MHz
wxStaticText * ID_STATICTEXT16
wxStaticText * lblVCO_CMPHO
wxStaticText * ID_STATICTEXT17
wxStaticText * lblVCO_CMPLO
wxButton * btnUpdateValues
wxStaticText * ID_STATICTEXT1
NumericSlider * ctrCSW_VCO
wxStaticText * ID_STATICTEXT10
NumericSlider * cmbICT_VCO
wxButton * btnShowVCOparams
wxStaticText * ID_STATICTEXT9
wxComboBox * cmbVDIV_VCO
wxStaticText * ID_STATICTEXT13
wxComboBox * cmbIPULSE_CP
wxStaticText * ID_STATICTEXT8
wxComboBox * cmbSEL_SDMCLK
wxStaticText * ID_STATICTEXT11
wxComboBox * cmbRSEL_LDO_VCO
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbIOFFSET_CP
wxFlexGridSizer * sizerR3
Additional Inherited Members
Protected Types inherited from pnlSX_view
enum {
ID_PD_FBDIV = 2048, ID_PD_LOCH_T2RBUF, ID_PD_CP, ID_PD_FDIV,
ID_PD_SDM, ID_PD_VCO_COMP, ID_PD_VCO, ID_EN_G,
ID_EN_DIR_SXRSXT, ID_RESET_N, ID_SPDUP_VCO, ID_BYPLDO_VCO,
ID_EN_COARSEPLL, ID_CURLIM_VCO, ID_REVPH_PFD, ID_EN_INTONLY_SDM,
ID_EN_SDM_CLK, ID_REV_SDMCLK, ID_SX_DITHER_EN, ID_EN_DIV2_DIVPROGenabled,
ID_TST_SX, ID_PW_DIV2_LOCH, ID_PW_DIV4_LOCH, ID_DIV_LOCH,
ID_CP2_PLL, ID_CP3_PLL, ID_CZ, ID_SEL_VCO,
ID_EN_DIV2_DIVPROG, ID_VCO_CMPHO, ID_VCO_CMPLO, ID_CSW_VCO,
ID_ICT_VCO, ID_BTN_SHOW_VCO, ID_VDIV_VCO, ID_IPULSE_CP,
ID_SEL_SDMCLK, ID_RSEL_LDO_VCO, ID_IOFFSET_CP
}
Detailed Description
Implementing pnlSX_view.
Definition at line 18 of file lms7002_pnlSX_view.h.
Constructor & Destructor Documentation
lms7002_pnlSX_view::lms7002_pnlSX_view (wxWindow * parent)
Constructor.
lms7002_pnlSX_view::lms7002_pnlSX_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 20 of file lms7002_pnlSX_view.cpp.
References BYPLDO_VCO, pnlSX_view::chkBYPLDO_VCO, pnlSX_view::chkCURLIM_VCO, pnlSX_view::chkEN_COARSEPLL, pnlSX_view::chkEN_DIR_SXRSXT, pnlSX_view::chkEN_DIV2_DIVPROGenabled, pnlSX_view::chkEN_G, pnlSX_view::chkEN_INTONLY_SDM, pnlSX_view::chkEN_SDM_CLK, pnlSX_view::chkPD_CP, pnlSX_view::chkPD_FBDIV, pnlSX_view::chkPD_FDIV, pnlSX_view::chkPD_LOCH_T2RBUF, pnlSX_view::chkPD_SDM, pnlSX_view::chkPD_VCO, pnlSX_view::chkPD_VCO_COMP, pnlSX_view::chkRESET_N, pnlSX_view::chkREV_SDMCLK, pnlSX_view::chkREVPH_PFD, pnlSX_view::chkSPDUP_VCO, pnlSX_view::chkSX_DITHER_EN, cmbCMPLO_CTRL, pnlSX_view::cmbCP2_PLL, pnlSX_view::cmbCP3_PLL, pnlSX_view::cmbCZ, pnlSX_view::cmbICT_VCO, pnlSX_view::cmbIOFFSET_CP, pnlSX_view::cmbIPULSE_CP, pnlSX_view::cmbRSEL_LDO_VCO, cmbRZ_CTRL, pnlSX_view::cmbSEL_SDMCLK, pnlSX_view::cmbTST_SX, pnlSX_view::cmbVDIV_VCO, CP2_PLL, CP3_PLL, CSW_VCO, pnlSX_view::ctrCSW_VCO, pnlSX_view::ctrDIV_LOCH, pnlSX_view::ctrPW_DIV2_LOCH, pnlSX_view::ctrPW_DIV4_LOCH, CURLIM_VCO, CZ, DIV_LOCH, EN_COARSEPLL, EN_DIR_SXRSXT, EN_DIV2_DIVPROG, EN_G, EN_INTONLY_SDM, EN_SDM_CLK, i, ICT_VCO, INT_SDM, IOFFSET_CP, IPULSE_CP, pnlSX_view::lblEN_DIV2_DIVPROG, pnlSX_view::lblINT_SDM, LMS7_CMPLO_CTRL_SX, LMS7_RZ_CTRL, LMS7param, ParameterChangeHandler(), PD_CP, PD_FBDIV, PD_FDIV, PD_LOCH_T2RBUF, PD_SDM, PD_VCO, PD_VCO_COMP, pnlSX_view::pnlRefClkSpur, PW_DIV2_LOCH, PW_DIV4_LOCH, RESET_N, REV_SDMCLK, REVPH_PFD, pnlSX_view::rgrSEL_VCO, RSEL_LDO_VCO, SEL_SDMCLK, SEL_VCO, showRefClkSpurCancelation, pnlSX_view::sizerR3, SPDUP_VCO, SX_DITHER_EN, temp, TST_SX, pnlSX_view::txtRefSpurBW, LMS7002_WXGUI::UpdateTooltips(), VDIV_VCO, and wndId2Enum.
Member Function Documentation
void lms7002_pnlSX_view::Initialize (lms_device_t * pControl)
Definition at line 414 of file lms7002_pnlSX_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlSX_view::OnbtnCalculateClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 499 of file lms7002_pnlSX_view.cpp.
References pnlSX_view::chkEnableRefSpurCancelation, pnlSX_view::lblRefClk_MHz, lms(), LMS7param, LMS_CLOCK_REF, LMS_ReadParam(), LMS_SetClockFreq(), lmsControl, lime::LOG_LEVEL_INFO, MAC, lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetFrequencySXWithSpurCancelation(), status, pnlSX_view::txtFrequency, pnlSX_view::txtRefSpurBW, and UpdateGUI().
void lms7002_pnlSX_view::OnbtnChangeRefClkClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 471 of file lms7002_pnlSX_view.cpp.
References freq, LMS7param, LMS_CLOCK_REF, LMS_CLOCK_SXR, LMS_CLOCK_SXT, LMS_GetClockFreq(), LMS_ReadParam(), LMS_SetClockFreq(), lmsControl, MAC, status, pnlSX_view::txtFrequency, and UpdateGUI().
void lms7002_pnlSX_view::OnbtnReadComparators (wxCommandEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 451 of file lms7002_pnlSX_view.cpp.
References pnlSX_view::lblVCO_CMPHO, pnlSX_view::lblVCO_CMPLO, LMS7param, LMS_ReadParam(), lmsControl, VCO_CMPHO, and VCO_CMPLO.
Referenced by ParameterChangeHandler(), and UpdateGUI().
void lms7002_pnlSX_view::OnbtnTuneClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 539 of file lms7002_pnlSX_view.cpp.
References LMS7param, LMS_CLOCK_SXR, LMS_CLOCK_SXT, LMS_ReadParam(), LMS_SetClockFreq(), lmsControl, MAC, status, and UpdateGUI().
void lms7002_pnlSX_view::OnEnableRefSpurCancelation (wxCommandEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 615 of file lms7002_pnlSX_view.cpp.
References pnlSX_view::chkEnableRefSpurCancelation, CMIX_BYP_RXTSP, CMIX_GAIN_RXTSP, i, LMS7param, LMS_ReadParam(), LMS_WriteParam(), lmsControl, MAC, SEL_RX, pnlSX_view::txtRefSpurBW, and UpdateGUI().
void lms7002_pnlSX_view::OnShowVCOclicked (wxCommandEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 608 of file lms7002_pnlSX_view.cpp.
References lmsControl.
void lms7002_pnlSX_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 429 of file lms7002_pnlSX_view.cpp.
References pnlSX_view::ctrCSW_VCO, LMS_WriteParam(), lmsControl, OnbtnReadComparators(), and wndId2Enum.
Referenced by lms7002_pnlSX_view(), and ParameterChangeHandler().
void lms7002_pnlSX_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlSX_view.
Definition at line 420 of file lms7002_pnlSX_view.cpp.
References ParameterChangeHandler().
void lms7002_pnlSX_view::UpdateGUI ()
Definition at line 550 of file lms7002_pnlSX_view.cpp.
References pnlSX_view::chkEnableRefSpurCancelation, pnlSX_view::chkPD_LOCH_T2RBUF, CMIX_SC_RXTSP, DIV_LOCH, freq, pnlSX_view::lblDivider, pnlSX_view::lblFRAC_SDM, pnlSX_view::lblRealOutFrequency, pnlSX_view::lblRefClk_MHz, LMS7param, LMS_CLOCK_REF, LMS_CLOCK_SXR, LMS_CLOCK_SXT, LMS_GetClockFreq(), LMS_GetNCOFrequency(), LMS_ReadParam(), lmsControl, MAC, MIMO_SISO, OnbtnReadComparators(), pnlSX_view::txtFrequency, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by OnbtnCalculateClick(), OnbtnChangeRefClkClick(), OnbtnTuneClick(), OnEnableRefSpurCancelation(), and lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
wxComboBox* lms7002_pnlSX_view::cmbCMPLO_CTRL protected
Definition at line 32 of file lms7002_pnlSX_view.h.
Referenced by lms7002_pnlSX_view().
wxComboBox* lms7002_pnlSX_view::cmbRZ_CTRL protected
Definition at line 31 of file lms7002_pnlSX_view.h.
Referenced by lms7002_pnlSX_view().
lms_device_t* lms7002_pnlSX_view::lmsControl protected
Definition at line 41 of file lms7002_pnlSX_view.h.
Referenced by Initialize(), OnbtnCalculateClick(), OnbtnChangeRefClkClick(), OnbtnReadComparators(), OnbtnTuneClick(), OnEnableRefSpurCancelation(), OnShowVCOclicked(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlSX_view::wndId2Enum protected
Definition at line 42 of file lms7002_pnlSX_view.h.
Referenced by lms7002_pnlSX_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlSX_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlSX_view.cpp