LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/lms7002m_controls.h File Reference
lms7002m_controls.h File Reference
#include "typedefs.h"
Classes
struct RegisterBatch
Macros
#define LMS7002M_Rx 0
#define LMS7002M_Tx 1
Enumerations
enum VCO_ID { VCO_CGEN = 0, VCO_SXR, VCO_SXT }
Functions
void SaveChipState (bool wr)
void SetDefaults (uint16_t start, uint16_t end)
void SetDefaultsSX ()
void ClockLogicResets ()
void SetNCOFrequency (const bool tx, const float freq_Hz, uint8_t index)
float_type GetReferenceClk_TSP_MHz (bool tx)
float_type GetFrequencyCGEN ()
uint8_t SetFrequencyCGEN (const float_type freq)
float_type GetFrequencySX (const bool Tx)
uint8_t SetFrequencySX (const bool Tx, const float_type freq)
void EnableChannelPowerControls ()
void EnableMIMOBuffersIfNecessary ()
uint8_t TuneVCO (bool SX)
uint16_t pow2 (const uint8_t power)
void WriteMaskedRegs (const RegisterBatch *regs)
uint8_t GetValueOf_c_ctl_pga_rbb (uint8_t g_pga_rbb)
Macro Definition Documentation
#define LMS7002M_Rx 0
Definition at line 4 of file lms7002m_controls.h.
Referenced by CalibrateRx(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxSetup(), CheckSaturationRx(), CheckSaturationTxRx(), TuneRxFilter(), TuneRxFilterSetup(), and TuneTxFilterSetup().
#define LMS7002M_Tx 1
Definition at line 5 of file lms7002m_controls.h.
Referenced by CalibrateRxSetup(), CalibrateTx(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
Enumeration Type Documentation
enum VCO_ID
Enumerator
VCO_CGEN
VCO_SXR
VCO_SXT
Definition at line 29 of file lms7002m_controls.h.
Function Documentation
void ClockLogicResets ()
Definition at line 139 of file lms7002m_controls.c.
References SPI_read(), and SPI_write().
Referenced by RunAGC(), and SaveChipState().
void EnableChannelPowerControls ()
Definition at line 425 of file lms7002m_controls.c.
References SPI_read(), and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
void EnableMIMOBuffersIfNecessary ()
Definition at line 443 of file lms7002m_controls.c.
References EN_NEXTRX_RFE, EN_NEXTTX_TRF, MAC, Modify_SPI_Reg_bits(), SPI_read(), and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
float_type GetFrequencyCGEN ()
Definition at line 152 of file lms7002m_controls.c.
References DIV_OUTCH_CGEN, Get_SPI_Reg_bits(), MSB_LSB, and RefClk.
Referenced by GetReferenceClk_TSP_MHz(), and SetupCGEN().
float_type GetFrequencySX (const bool Tx)
Definition at line 209 of file lms7002m_controls.c.
References DIV_LOCH, EN_DIV2_DIVPROG, Get_SPI_Reg_bits(), MAC, Modify_SPI_Reg_bits(), MSB_LSB, pow2(), RefClk, SPI_read(), and SPI_write().
Referenced by CalibrateRx(), lime::LMS7002M::CalibrateRx(), CalibrateRxSetup(), lime::LMS7002M::CalibrateTx(), and CalibrateTxSetup().
float_type GetReferenceClk_TSP_MHz (bool tx)
Definition at line 191 of file lms7002m_controls.c.
References CLKH_OV_CLKL_CGEN, EN_ADCCLKH_CLKGN, Get_SPI_Reg_bits(), GetFrequencyCGEN(), and pow2().
Referenced by SetNCOFrequency(), and UpdateRSSIDelay().
uint8_t GetValueOf_c_ctl_pga_rbb (uint8_t g_pga_rbb)
Definition at line 414 of file lms7002m_controls.c.
Referenced by RunAGC(), and TuneRxFilterSetup().
uint16_t pow2 (const uint8_t power)
Definition at line 24 of file lms7002m_controls.c.
Referenced by GetFrequencySX(), GetReferenceClk_TSP_MHz(), RxFilterSearch(), SetFrequencySX(), and SetupCGEN().
void SaveChipState (bool wr)
Definition at line 52 of file lms7002m_controls.c.
References address, chipStateAddr, chipStateData, ClockLogicResets(), i, ROM, SetDefaults(), SPI_read(), SPI_write(), SPI_write_batch(), and x0020state.
Referenced by CalibrateRx(), CalibrateTx(), TuneRxFilter(), and TuneTxFilter().
void SetDefaults (uint16_t start, uint16_t end)
Referenced by SaveChipState(), TuneRxFilterSetup(), and TuneTxFilterSetup().
void SetDefaultsSX ()
Definition at line 127 of file lms7002m_controls.c.
References i, Modify_SPI_Reg_bits(), MSB_LSB, ROM, and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), and TuneRxFilterSetup().
uint8_t SetFrequencyCGEN (const float_type freq)
Definition at line 160 of file lms7002m_controls.c.
References DIV_OUTCH_CGEN, freq, INT_SDM_CGEN, MCU_CGEN_TUNE_FAILED, Modify_SPI_Reg_bits(), MSB_LSB, RefClk, TuneVCO(), and VCO_CGEN.
Referenced by ConfigCGEN_ForLPF_IF(), and SetupCGEN().
uint8_t SetFrequencySX (const bool Tx, const float_type freq)
Definition at line 224 of file lms7002m_controls.c.
References CSW_VCO, DIV_LOCH, EN_DIV2_DIVPROG, Get_SPI_Reg_bits(), INT_SDM, MAC, MCU_NO_ERROR, MCU_SXR_TUNE_FAILED, MCU_SXT_TUNE_FAILED, Modify_SPI_Reg_bits(), MSB_LSB, pow2(), RefClk, SEL_VCO, SPI_read(), SPI_write(), temp, and TuneVCO().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilter(), and TuneRxFilterSetup().
void SetNCOFrequency (const bool tx, const float freq_Hz, uint8_t index)
Definition at line 201 of file lms7002m_controls.c.
References fcw, GetReferenceClk_TSP_MHz(), and SPI_write().
Referenced by CalibrateRx(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxSetup(), CheckSaturationRx(), CheckSaturationTxRx(), TuneRxFilter(), TuneRxFilterSetup(), and TuneTxFilterSetup().
uint8_t TuneVCO (bool SX)
Definition at line 304 of file lms7002m_controls.c.
References gComparatorDelayCounter, MCU_ERROR, MCU_NO_ERROR, Modify_SPI_Reg_bits(), MSB_LSB, ReadCMP(), and RefClk.
Referenced by IsPLLTuned(), SetFrequencyCGEN(), and SetFrequencySX().
void WriteMaskedRegs (const RegisterBatch * regs)
Definition at line 398 of file lms7002m_controls.c.
References i, index, SPI_read(), and SPI_write().
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().