LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/recipes.h File Reference
recipes.h File Reference
Functions
int ludcmp (double **a, int n, int *indx, double *d)
void lubksb (double **a, int n, int *indx, double *b)
void free_vector (double *v, int nl, int nh)
void free_ivector (int *v, int nl, int nh)
void free_matrix (double **m, int nrl, int nrh, int ncl, int nch)
Function Documentation
void free_ivector (int * v, int nl, int nh)
Definition at line 96 of file recipes.c.
Referenced by lms().
void free_matrix (double ** m, int nrl, int nrh, int ncl, int nch)
Definition at line 132 of file recipes.c.
References i.
Referenced by lms().
void free_vector (double * v, int nl, int nh)
Definition at line 86 of file recipes.c.
Referenced by lms(), and ludcmp().
void lubksb (double ** a, int n, int * indx, double * b)
int ludcmp (double ** a, int n, int * indx, double * d)
Definition at line 163 of file recipes.c.
References free_vector(), i, dfilter::n, nrerror(), temp, TINY, and vector().
Referenced by lms().