LimeSuite-UML: lms7002_pnlAFE_view Class Reference
lms7002_pnlAFE_view Class Reference
Implementing pnlAFE_view.
#include <lms7002_pnlAFE_view.h>
Public Member Functions
lms7002_pnlAFE_view (wxWindow *parent)
Constructor.
lms7002_pnlAFE_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlAFE_view
pnlAFE_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlAFE_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlAFE_view
wxCheckBox * chkPD_AFE
wxCheckBox * chkPD_RX_AFE1
wxCheckBox * chkPD_RX_AFE2
wxCheckBox * chkPD_TX_AFE1
wxCheckBox * chkPD_TX_AFE2
wxCheckBox * chkEN_G_AFE
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbISEL_DAC_AFE
wxStaticText * ID_STATICTEXT2
wxComboBox * cmbMUX_AFE_1
wxStaticText * ID_STATICTEXT3
wxComboBox * cmbMUX_AFE_2
wxRadioBox * rgrMODE_INTERLEAVE_AFE
Additional Inherited Members
Protected Types inherited from pnlAFE_view
enum {
ID_PD_AFE = 2048, ID_PD_RX_AFE1, ID_PD_RX_AFE2, ID_PD_TX_AFE1,
ID_PD_TX_AFE2, ID_EN_G_AFE, ID_ISEL_DAC_AFE, ID_MUX_AFE_1,
ID_MUX_AFE_2, ID_MODE_INTERLEAVE_AFE
}
Detailed Description
Implementing pnlAFE_view.
Definition at line 17 of file lms7002_pnlAFE_view.h.
Constructor & Destructor Documentation
lms7002_pnlAFE_view::lms7002_pnlAFE_view (wxWindow * parent)
Constructor.
Definition at line 6 of file lms7002_pnlAFE_view.cpp.
lms7002_pnlAFE_view::lms7002_pnlAFE_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 13 of file lms7002_pnlAFE_view.cpp.
References pnlAFE_view::chkEN_G_AFE, pnlAFE_view::chkPD_AFE, pnlAFE_view::chkPD_RX_AFE1, pnlAFE_view::chkPD_RX_AFE2, pnlAFE_view::chkPD_TX_AFE1, pnlAFE_view::chkPD_TX_AFE2, pnlAFE_view::cmbISEL_DAC_AFE, pnlAFE_view::cmbMUX_AFE_1, pnlAFE_view::cmbMUX_AFE_2, EN_G_AFE, i, ISEL_DAC_AFE, LMS7param, MODE_INTERLEAVE_AFE, MUX_AFE_1, MUX_AFE_2, PD_AFE, PD_RX_AFE1, PD_RX_AFE2, PD_TX_AFE1, PD_TX_AFE2, pnlAFE_view::rgrMODE_INTERLEAVE_AFE, temp, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlAFE_view::Initialize (lms_device_t * pControl)
Definition at line 52 of file lms7002_pnlAFE_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlAFE_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlAFE_view.
Definition at line 58 of file lms7002_pnlAFE_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlAFE_view::UpdateGUI ()
Definition at line 74 of file lms7002_pnlAFE_view.cpp.
References lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlAFE_view::lmsControl protected
Definition at line 30 of file lms7002_pnlAFE_view.h.
Referenced by Initialize(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlAFE_view::wndId2Enum protected
Definition at line 31 of file lms7002_pnlAFE_view.h.
Referenced by lms7002_pnlAFE_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlAFE_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlAFE_view.cpp