LimeSuite-UML: pnluLimeSDR Class Reference
pnluLimeSDR Class Reference
#include <pnluLimeSDR.h>
Public Member Functions
pnluLimeSDR (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int style=0, wxString name=wxEmptyString)
void Initialize (lms_device_t *pControl)
virtual ~pnluLimeSDR ()
virtual void UpdatePanel ()
void OnLoopbackChange (wxCommandEvent &event)
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
Protected Attributes
wxCheckBox * chkTxLBSH
wxCheckBox * chkTxLBAT
wxChoice * cmbRxPath
wxChoice * cmbTxPath
wxStaticText * txtLB
lms_device_t * lmsControl
Detailed Description
Definition at line 12 of file pnluLimeSDR.h.
Constructor & Destructor Documentation
pnluLimeSDR::pnluLimeSDR (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int style = 0, wxString name = wxEmptyString)
Definition at line 19 of file pnluLimeSDR.cpp.
References lmsControl, OnLoopbackChange(), and OnReadAll().
pnluLimeSDR::~pnluLimeSDR () virtual
Definition at line 72 of file pnluLimeSDR.cpp.
References OnLoopbackChange().
Member Function Documentation
void pnluLimeSDR::Initialize (lms_device_t * pControl)
Definition at line 67 of file pnluLimeSDR.cpp.
References lmsControl.
Referenced by pnlBoardControls::SetupControls().
void pnluLimeSDR::OnLoopbackChange (wxCommandEvent & event)
Definition at line 80 of file pnluLimeSDR.cpp.
References LMS_WriteFPGAReg(), and lmsControl.
Referenced by pnluLimeSDR(), and ~pnluLimeSDR().
void pnluLimeSDR::OnReadAll (wxCommandEvent & event)
Definition at line 109 of file pnluLimeSDR.cpp.
Referenced by pnluLimeSDR().
void pnluLimeSDR::OnWriteAll (wxCommandEvent & event)
Definition at line 114 of file pnluLimeSDR.cpp.
void pnluLimeSDR::UpdatePanel () virtual
Definition at line 93 of file pnluLimeSDR.cpp.
References LMS_ReadFPGAReg(), and lmsControl.
Member Data Documentation
wxCheckBox* pnluLimeSDR::chkTxLBAT protected
Definition at line 26 of file pnluLimeSDR.h.
wxCheckBox* pnluLimeSDR::chkTxLBSH protected
Definition at line 25 of file pnluLimeSDR.h.
wxChoice* pnluLimeSDR::cmbRxPath protected
Definition at line 27 of file pnluLimeSDR.h.
wxChoice* pnluLimeSDR::cmbTxPath protected
Definition at line 28 of file pnluLimeSDR.h.
lms_device_t* pnluLimeSDR::lmsControl protected
Definition at line 30 of file pnluLimeSDR.h.
wxStaticText* pnluLimeSDR::txtLB protected
Definition at line 29 of file pnluLimeSDR.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnluLimeSDR.h
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnluLimeSDR.cpp