LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/CMakeLists.txt File Reference
/home/erik/prefix/default/src/soapysdr/lib/CMakeLists.txt File Reference
Functions
include (FeatureSummary) include(CMakeDependentOption) cmake_dependent_option(ENABLE_LIBRARY"Enable runtime library"ON"TRUE"OFF) add_feature_info(Library ENABLE_LIBRARY"runtime library v$
if (NOT ENABLE_LIBRARY) return() endif() list(APPEND SOAPY_SDR_SOURCES Device.cpp Factory.cpp Registry.cpp Types.cpp NullDevice.cpp Logger.cpp Errors.cpp Formats.cpp ConverterRegistry.cpp DefaultConverters.cpp) list(APPEND SOAPY_SDR_LIBRARIES $
if (CMAKE_COMPILER_IS_GNUCXX) list(APPEND SOAPY_SDR_LIBRARIES-pthread) endif() include_directories($
include list (APPEND SOAPY_SDR_SOURCES ${CMAKE_CURRENT_BINARY_DIR}/Modules.cpp) configure_file($
Function Documentation
if (NOT ENABLE_LIBRARY)
Definition at line 8 of file CMakeLists.txt.
if (CMAKE_COMPILER_IS_GNUCXX)
Definition at line 35 of file CMakeLists.txt.
include (FeatureSummary)
Definition at line 4 of file CMakeLists.txt.
Referenced by endif(), find_package(), and set().
include list (APPEND SOAPY_SDR_SOURCES ${CMAKE_CURRENT_BINARY_DIR}/Modules. cpp)
Definition at line 41 of file CMakeLists.txt.
Referenced by endif(), link_directories(), and set().