LimeSuite-UML: lime::ConnectionNovenaRF7 Class Reference
lime::ConnectionNovenaRF7 Class Reference
#include <ConnectionNovenaRF7.h>
Classes
class StreamChannel
struct ThreadData
Public Member Functions
ConnectionNovenaRF7 ()
~ConnectionNovenaRF7 ()
int Open (const char *spiDevPath)
Opens connection to first found chip.
void Close ()
Closes connection to chip.
bool IsOpen ()
Returns whether chip is connected.
int Write (const unsigned char *buffer, int length, int timeout_ms=0)
Sends data through SPI port.
int Read (unsigned char *buffer, int length, int timeout_ms=0)
Reads data from SPI port.
eConnectionType GetType (void)
implement in base class
void UpdateExternalBandSelect (const size_t channel, const int trfBand, const int rfePath)
int SetupStream (size_t &streamID, const StreamConfig &config)
int CloseStream (const size_t streamID)
size_t GetStreamSize (const size_t streamID)
int ControlStream (const size_t streamID, const bool enable)
int ReadStream (const size_t streamID, void *buffs, const size_t length, const long timeout_ms, StreamMetadata &metadata)
int WriteStream (const size_t streamID, const void *buffs, const size_t length, const long timeout_ms, const StreamMetadata &metadata)
int ReadStreamStatus (const size_t streamID, const long timeout_ms, StreamMetadata &metadata)
Public Member Functions inherited from lime::LMS64CProtocol
LMS64CProtocol (void)
virtual ~LMS64CProtocol (void)
virtual DeviceInfo GetDeviceInfo (void)
int DeviceReset (int ind=0)
DeviceReset implemented by LMS64C.
int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size) override
TransactSPI implemented by LMS64C.
int WriteI2C (const int addr, const std::string &data)
WriteI2C implemented by LMS64C.
int ReadI2C (const int addr, const size_t numBytes, std::string &data)
ReadI2C implemented by LMS64C.
int WriteRegisters (const uint32_t *addrs, const uint32_t *data, const size_t size)
WriteRegisters (BRDSPI) implemented by LMS64C.
int ReadRegisters (const uint32_t *addrs, uint32_t *data, const size_t size)
ReadRegisters (BRDSPI) implemented by LMS64C.
virtual int TransferPacket (GenericPacket &pkt)
Transfers data between packet and connected device.
LMSinfo GetInfo ()
Returns connected device information.
FPGAinfo GetFPGAInfo ()
Returns information from FPGA gateware.
void VersionCheck ()
int ProgramUpdate (const bool download, IConnection::ProgrammingCallback callback) override
virtual int ProgramWrite (const char *buffer, const size_t length, const int programmingMode, const int device, ProgrammingCallback callback=nullptr)
Uploads program to selected device.
virtual int CustomParameterRead (const uint8_t *ids, double *values, const size_t count, std::string *units) override
Returns value of custom on board control.
virtual int CustomParameterWrite (const uint8_t *ids, const double *values, const size_t count, const std::string &units) override
Sets custom on board control to given value units.
virtual int GPIOWrite (const uint8_t *buffer, const size_t bufLength) override
Writes GPIO values to device.
virtual int GPIORead (uint8_t *buffer, const size_t bufLength) override
Reads GPIO values from device.
virtual int GPIODirWrite (const uint8_t *buffer, const size_t bufLength) override
Write GPIO direction control values to device.
virtual int GPIODirRead (uint8_t *buffer, const size_t bufLength) override
Read GPIO direction configuration from device.
int ProgramMCU (const uint8_t *buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback) override
Uploads program to MCU.
int WriteLMS7002MSPI (const uint32_t *writeData, size_t size, unsigned periphID=0) override
int ReadLMS7002MSPI (const uint32_t *writeData, uint32_t *readData, size_t size, unsigned periphID=0) override
Public Member Functions inherited from lime::IConnection
IConnection (void)
IConnection constructor.
virtual ~IConnection (void)
IConnection destructor.
const ConnectionHandle & GetHandle (void) const
Get the connection handle that was used to create this connection.
virtual int ResetStreamBuffers ()
Read raw stream data from device streaming port.
virtual int GetBuffersCount () const
virtual int CheckStreamSize (int size) const
virtual int ReceiveData (char *buffer, int length, int epIndex, int timeout=100)
virtual int SendData (const char *buffer, int length, int epIndex, int timeout=100)
virtual int BeginDataSending (const char *buffer, uint32_t length, int ep)
virtual bool WaitForSending (int contextHandle, uint32_t timeout_ms)
virtual int FinishDataSending (const char *buffer, uint32_t length, int contextHandle)
virtual void AbortSending (int ep)
virtual int BeginDataReading (char *buffer, uint32_t length, int ep)
virtual bool WaitForReading (int contextHandle, unsigned int timeout_ms)
virtual int FinishDataReading (char *buffer, uint32_t length, int contextHandle)
virtual void AbortReading (int ep)
int WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
template<typename ReadType >
int ReadRegister (const uint32_t addr, ReadType &data)
Read a single device register.
void SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Static Public Attributes
static const int cSPI_BUF_SIZE = 128
static const int cSPI_SPEED_HZ = 2000000
Protected Member Functions
int UpdateThreads ()
Static Protected Member Functions
static void ReceivePacketsLoop (const ThreadData args)
static void TransmitPacketsLoop (const ThreadData args)
Protected Attributes
std::thread rxThread
std::atomic< bool > rxRunning
std::atomic< bool > terminateRx
std::atomic< uint32_t > rxDataRate_Bps
std::vector< StreamChannel * > mRxStreams
std::vector< unsigned char > rxbuf
int fd
std::fstream m_SEN
Protected Attributes inherited from lime::IConnection
std::function< void(bool, const unsigned char *, const unsigned int)> callback_logData
Additional Inherited Members
Public Types inherited from lime::LMS64CProtocol
enum eConnectionType {
CONNECTION_UNDEFINED = -1, COM_PORT = 0, USB_PORT = 1, SPI_PORT = 2,
PCIE_PORT = 3, CONNECTION_TYPES_COUNT
}
Supported connection types.
enum eLMS_PROTOCOL { LMS_PROTOCOL_UNDEFINED = 0, LMS_PROTOCOL_DIGIC, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA }
enum ProgramWriteTarget { HPM, FX3, FPGA, PROGRAM_WRITE_TARGET_COUNT }
Public Types inherited from lime::IConnection
enum MCU_PROG_MODE { RESET = 0, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM }
typedef std::function< bool(int bsent, int btotal, const char *progressMsg)> ProgrammingCallback
Detailed Description
Definition at line 20 of file ConnectionNovenaRF7.h.
Constructor & Destructor Documentation
ConnectionNovenaRF7::ConnectionNovenaRF7 (void)
Definition at line 29 of file ConnectionNovenaRF7.cpp.
ConnectionNovenaRF7::~ConnectionNovenaRF7 (void)
Definition at line 52 of file ConnectionNovenaRF7.cpp.
Member Function Documentation
void ConnectionNovenaRF7::Close (void)
Closes connection to chip.
Definition at line 113 of file ConnectionNovenaRF7.cpp.
int ConnectionNovenaRF7::CloseStream (const size_t streamID)
Definition at line 555 of file ConnectionNovenaRF7_streaming.cpp.
References i, lime::ReportError(), and stream.
Referenced by GetType().
int ConnectionNovenaRF7::ControlStream (const size_t streamID, const bool enable)
Definition at line 577 of file ConnectionNovenaRF7_streaming.cpp.
References stream.
Referenced by GetType().
size_t ConnectionNovenaRF7::GetStreamSize (const size_t streamID)
Definition at line 572 of file ConnectionNovenaRF7_streaming.cpp.
Referenced by GetType().
eConnectionType lime::ConnectionNovenaRF7::GetType (void) inline virtual
implement in base class
Implements lime::LMS64CProtocol.
Definition at line 58 of file ConnectionNovenaRF7.h.
References CloseStream(), lime::ConnectionNovenaRF7::StreamChannel::config, ControlStream(), enable, GetStreamSize(), ReadStream(), ReadStreamStatus(), SetupStream(), lime::LMS64CProtocol::SPI_PORT, timeout_ms, UpdateExternalBandSelect(), and WriteStream().
bool ConnectionNovenaRF7::IsOpen (void) virtual
Returns whether chip is connected.
Returns
chip is connected
Reimplemented from lime::IConnection.
Definition at line 124 of file ConnectionNovenaRF7.cpp.
int ConnectionNovenaRF7::Open (const char * spiDevPath)
Opens connection to first found chip.
Returns
0-success
Definition at line 60 of file ConnectionNovenaRF7.cpp.
References mode, and lime::ReportError().
int ConnectionNovenaRF7::Read (unsigned char * buffer, int length, int timeout_ms = 0) virtual
Reads data from SPI port.
Parameters
buffer pointer to data buffer for receiving
length number of bytes to read
timeout_ms timeout limit for operation in milliseconds
Returns
Number of bytes received
Implements lime::LMS64CProtocol.
Definition at line 180 of file ConnectionNovenaRF7.cpp.
References int().
int ConnectionNovenaRF7::ReadStream (const size_t streamID, void * buffs, const size_t length, const long timeout_ms, StreamMetadata & metadata)
Definition at line 521 of file ConnectionNovenaRF7_streaming.cpp.
References meta, status, lms_stream_meta_t::timestamp, and lms_stream_status_t::timestamp.
Referenced by GetType().
int ConnectionNovenaRF7::ReadStreamStatus (const size_t streamID, const long timeout_ms, StreamMetadata & metadata)
Definition at line 588 of file ConnectionNovenaRF7_streaming.cpp.
References lime::StreamChannel::Info::droppedPackets, info, lime::StreamChannel::Info::timestamp, and lime::StreamChannel::Info::underrun.
Referenced by GetType().
void ConnectionNovenaRF7::ReceivePacketsLoop (const ThreadData args) static protected
Definition at line 398 of file ConnectionNovenaRF7_streaming.cpp.
References bb, buffer, lime::ConnectionNovenaRF7::ThreadData::channels, lime::ConnectionNovenaRF7::ThreadData::dataPort, lime::ConnectionNovenaRF7::ThreadData::dataRate_Bps, fpga_read(), meta, p(), prep_eim_burst(), lime::IConnection::ReadRegister(), samples, t1, t2, lime::ConnectionNovenaRF7::ThreadData::terminate, lms_stream_meta_t::timestamp, and lime::IConnection::WriteRegister().
int ConnectionNovenaRF7::SetupStream (size_t & streamID, const StreamConfig & config)
Definition at line 539 of file ConnectionNovenaRF7_streaming.cpp.
References lime::ConnectionNovenaRF7::StreamChannel::config, lime::StreamConfig::isTx, lime::ReportError(), and stream.
Referenced by GetType().
static void lime::ConnectionNovenaRF7::TransmitPacketsLoop (const ThreadData args) static protected
void ConnectionNovenaRF7::UpdateExternalBandSelect (const size_t channel, const int trfBand, const int rfePath)
Definition at line 195 of file ConnectionNovenaRF7.cpp.
Referenced by GetType().
int ConnectionNovenaRF7::UpdateThreads () protected
Definition at line 227 of file ConnectionNovenaRF7.cpp.
References args, lime::ConnectionNovenaRF7::ThreadData::channels, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_USB_FIFO_RST, lime::ConnectionNovenaRF7::ThreadData::dataPort, lime::ConnectionNovenaRF7::ThreadData::dataRate_Bps, i, lime::LMS64CProtocol::GenericPacket::outBuffer, ReadRegister(), lime::ConnectionNovenaRF7::ThreadData::terminate, and WriteRegister().
Referenced by lime::ConnectionNovenaRF7::StreamChannel::Start(), and lime::ConnectionNovenaRF7::StreamChannel::Stop().
int ConnectionNovenaRF7::Write (const unsigned char * buffer, int length, int timeout_ms = 0) virtual
Sends data through SPI port.
Parameters
buffer data buffer to send
length size of data buffer
timeout_ms timeout limit for operation in milliseconds
Returns
Number of bytes sent
Implements lime::LMS64CProtocol.
Definition at line 135 of file ConnectionNovenaRF7.cpp.
References i, and read().
int ConnectionNovenaRF7::WriteStream (const size_t streamID, const void * buffs, const size_t length, const long timeout_ms, const StreamMetadata & metadata)
Definition at line 534 of file ConnectionNovenaRF7_streaming.cpp.
Referenced by GetType().
Member Data Documentation
const int ConnectionNovenaRF7::cSPI_BUF_SIZE = 128 static
Definition at line 45 of file ConnectionNovenaRF7.h.
const int ConnectionNovenaRF7::cSPI_SPEED_HZ = 2000000 static
Definition at line 46 of file ConnectionNovenaRF7.h.
int lime::ConnectionNovenaRF7::fd protected
Definition at line 96 of file ConnectionNovenaRF7.h.
std::fstream lime::ConnectionNovenaRF7::m_SEN protected
Definition at line 97 of file ConnectionNovenaRF7.h.
std::vector<StreamChannel*> lime::ConnectionNovenaRF7::mRxStreams protected
Definition at line 93 of file ConnectionNovenaRF7.h.
std::vector<unsigned char> lime::ConnectionNovenaRF7::rxbuf protected
Definition at line 95 of file ConnectionNovenaRF7.h.
std::atomic<uint32_t> lime::ConnectionNovenaRF7::rxDataRate_Bps protected
Definition at line 92 of file ConnectionNovenaRF7.h.
Referenced by lime::ConnectionNovenaRF7::StreamChannel::GetInfo().
std::atomic<bool> lime::ConnectionNovenaRF7::rxRunning protected
Definition at line 90 of file ConnectionNovenaRF7.h.
std::thread lime::ConnectionNovenaRF7::rxThread protected
Definition at line 89 of file ConnectionNovenaRF7.h.
std::atomic<bool> lime::ConnectionNovenaRF7::terminateRx protected
Definition at line 91 of file ConnectionNovenaRF7.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionNovenaRF7/ConnectionNovenaRF7.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionNovenaRF7/ConnectionNovenaRF7.cpp
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionNovenaRF7/ConnectionNovenaRF7_streaming.cpp