LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/lms.c File Reference
lms.c File Reference
#include "lms.h"
#include "recipes.h"
#include "rounding.h"
Macros
#define EVEN 0
#define ODD 1
Functions
double * vector ()
int * ivector ()
double ** matrix ()
double Case1F (double w, int i)
double Case2F (double w, int i)
double Case3F (double w, int i)
double Case4F (double w, int i)
int lms (double *hr, double *hi, double *hcsd, int n, double *w, double *des, double *weight, int p, int cprec, int csdprec, int symmetry, int **bincode, int **csdcode, int **csdcoder)
Macro Definition Documentation
#define EVEN 0
Definition at line 23 of file lms.c.
Referenced by lms().
#define ODD 1
Definition at line 24 of file lms.c.
Referenced by lms().
Function Documentation
double Case1F (double w, int i)
Definition at line 41 of file lms.c.
Referenced by lms().
double Case2F (double w, int i)
Definition at line 46 of file lms.c.
Referenced by lms().
double Case3F (double w, int i)
Definition at line 51 of file lms.c.
Referenced by lms().
double Case4F (double w, int i)
Definition at line 56 of file lms.c.
Referenced by lms().
int* ivector ()
Referenced by lms().
int lms (double * hr, double * hi, double * hcsd, int n, double * w, double * des, double * weight, int p, int cprec, int csdprec, int symmetry, int ** bincode, int ** csdcode, int ** csdcoder)
Definition at line 81 of file lms.c.
References dfilter::a, Case1F(), Case2F(), Case3F(), Case4F(), EVEN, free_ivector(), free_matrix(), free_vector(), i, index, ivector(), k, L, lubksb(), ludcmp(), matrix(), dfilter::n, NEGATIVE, ODD, p(), POSITIVE, round2csd(), round2int(), and vector().
Referenced by lime::LMS7_Device::Calibrate(), ConfigureCGEN(), lime::LMS7_Device::ConfigureGFIR(), lime::LMS7_Device::ConfigureTXLPF(), lime::LMS7_Device::EnableChannel(), lime::LMS7_Device::GetFrequency(), lime::LMS7_Device::GetGain(), lime::LMS7_Device::GetGFIRCoef(), lime::LMS7_Device::GetNCOFreq(), lime::LMS7_Device::GetNCOPhase(), lime::LMS7_Device::GetPath(), lime::LMS7_Device::GetRate(), lime::LMS7_Device::GetTestSignal(), gfir_lms(), lime::LMS7_LimeSDR_mini::Init(), lime::LMS7_Device::Init(), dlgDeviceInfo::Initialize(), HPM7_wxgui::Initialize(), lms7002_dlgVCOfrequencies::lms7002_dlgVCOfrequencies(), lime::LMS7_Device::LMS7_Device(), LMS_Calibrate(), LMS_Close(), LMS_DestroyStream(), LMS_EnableCalibCache(), LMS_EnableChannel(), LMS_GetAntenna(), LMS_GetAntennaBW(), LMS_GetAntennaList(), LMS_GetChipTemperature(), LMS_GetClockFreq(), LMS_GetDeviceInfo(), LMS_GetGaindB(), LMS_GetGFIRCoeff(), LMS_GetLOFrequency(), LMS_GetLOFrequencyRange(), LMS_GetLPFBW(), LMS_GetLPFBWRange(), LMS_GetNCOFrequency(), LMS_GetNCOIndex(), LMS_GetNCOPhase(), LMS_GetNormalizedGain(), LMS_GetNumChannels(), LMS_GetProgramModes(), LMS_GetSampleRate(), LMS_GetSampleRateRange(), LMS_GetTestSignal(), LMS_GPIODirRead(), LMS_GPIODirWrite(), LMS_GPIORead(), LMS_GPIOWrite(), LMS_Init(), LMS_IsOpen(), LMS_LoadConfig(), LMS_Program(), LMS_ReadCustomBoardParam(), LMS_ReadFPGAReg(), LMS_ReadLMSReg(), LMS_ReadParam(), LMS_Reset(), LMS_SaveConfig(), LMS_SetAntenna(), LMS_SetClockFreq(), LMS_SetGaindB(), LMS_SetGFIR(), LMS_SetGFIRCoeff(), LMS_SetGFIRLPF(), LMS_SetLOFrequency(), LMS_SetLPF(), LMS_SetLPFBW(), LMS_SetNCOFrequency(), LMS_SetNCOIndex(), LMS_SetNCOPhase(), LMS_SetNormalizedGain(), LMS_SetSampleRate(), LMS_SetSampleRateDir(), LMS_SetTestSignal(), LMS_SetupStream(), LMS_Synchronize(), LMS_TransferLMS64C(), LMS_UploadWFM(), LMS_WriteCustomBoardParam(), LMS_WriteFPGAReg(), LMS_WriteLMSReg(), LMS_WriteParam(), lime::LMS7_Device::LoadConfig(), lms7002_pnlGains_view::OnAGCStateChange(), lms7002_pnlSX_view::OnbtnCalculateClick(), lms7002_pnlCLKGEN_view::onbtnCalculateClick(), lms7002_dlgVCOfrequencies::OnBtnOkClick(), lms7002_pnlCLKGEN_view::onbtnTuneClick(), lms7002_pnlTBB_view::OnbtnTuneTxGain(), lms7002_pnlR3_view::OnCalibrateAnalogRSSI(), lms7002_mainPanel::OnCalibrateInternalADC(), lms7002_pnlBIAS_view::OnCalibrateRP_BIAS(), LMS7SuiteAppFrame::OnControlBoardConnect(), lime::LMS7_Device::Program(), lime::LMS7_Device::Reset(), lime::LMS7_Device::SelectChannel(), set(), lime::LMS7_Device::SetClockFreq(), dlgConnectionSettings::SetConnectionManagers(), lime::LMS7_Device::SetFPGAInterfaceFreq(), lime::LMS7_LimeSDR_mini::SetFrequency(), lime::LMS7_Device::SetFrequency(), lime::LMS7_Device::SetGain(), lime::LMS7_Device::SetGFIR(), lime::LMS7_Device::SetGFIRCoef(), lime::LMS7_Device::SetLPF(), lime::LMS7_Device::SetNCOFreq(), lime::LMS7_Device::SetNCOPhase(), lime::LMS7_LimeSDR_mini::SetPath(), lime::LMS7_Device::SetPath(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_Device::SetRate(), lime::LMS7_Device::SetTestSignal(), lime::LMS7_Device::Synchronize(), LMS7002_WXGUI::UpdateControlsByMap(), and lms7002_pnlRxTSP_view::UpdateGUI().
double** matrix ()
Referenced by lms().
double* vector ()
Referenced by _wrap_crop_matrix_vcvc_sptr_set_processor_affinity(), _wrap_Device_readStream__(), _wrap_Device_setupStream(), _wrap_Device_setupStream__SWIG_0(), _wrap_Device_setupStream__SWIG_1(), _wrap_Device_writeStream__(), _wrap_estimator_cw_sptr_set_processor_affinity(), _wrap_estimator_fmcw_sptr_set_processor_affinity(), _wrap_estimator_fsk_sptr_set_processor_affinity(), _wrap_estimator_ofdm_sptr_set_processor_affinity(), _wrap_estimator_rcs_sptr_set_processor_affinity(), _wrap_estimator_sync_pulse_c_sptr_set_processor_affinity(), _wrap_find_max_peak_c_sptr_set_processor_affinity(), _wrap_gpio_source_s_sptr_set_processor_affinity(), _wrap_msg_gate_sptr_set_processor_affinity(), _wrap_msg_manipulator_sptr_set_processor_affinity(), _wrap_new_SoapySDRArgInfoList(), _wrap_new_SoapySDRDoubleList(), _wrap_new_SoapySDRKwargsList(), _wrap_new_SoapySDRKwargsList__SWIG_3(), _wrap_new_SoapySDRRangeList(), _wrap_new_SoapySDRSizeList(), _wrap_new_SoapySDRStringList(), _wrap_new_SoapySDRUnsignedList(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_set_processor_affinity(), _wrap_ofdm_divide_vcvc_sptr_set_processor_affinity(), _wrap_os_cfar_2d_vc_sptr_set_processor_affinity(), _wrap_os_cfar_c_sptr_set_processor_affinity(), _wrap_print_results_sptr_set_processor_affinity(), _wrap_qtgui_scatter_plot_sptr_set_processor_affinity(), _wrap_qtgui_spectrogram_plot_sptr_set_processor_affinity(), _wrap_qtgui_time_plot_sptr_set_processor_affinity(), _wrap_signal_generator_cw_c_sptr_set_processor_affinity(), _wrap_signal_generator_fmcw_c_sptr_set_processor_affinity(), _wrap_signal_generator_fsk_c_sptr_set_processor_affinity(), _wrap_signal_generator_sync_pulse_c_sptr_set_processor_affinity(), _wrap_soapysdr_echotimer_sptr_set_processor_affinity(), _wrap_soapysdr_echotimer_stretch_sptr_set_processor_affinity(), _wrap_SoapySDRArgInfoList___delitem__(), _wrap_SoapySDRArgInfoList___getitem__(), _wrap_SoapySDRArgInfoList___setitem__(), _wrap_SoapySDRArgInfoList___setitem____SWIG_0(), _wrap_SoapySDRArgInfoList___setslice__(), _wrap_SoapySDRArgInfoList___setslice____SWIG_0(), _wrap_SoapySDRArgInfoList_erase(), _wrap_SoapySDRArgInfoList_insert(), _wrap_SoapySDRArgInfoList_resize(), _wrap_SoapySDRDoubleList___delitem__(), _wrap_SoapySDRDoubleList___getitem__(), _wrap_SoapySDRDoubleList___setitem__(), _wrap_SoapySDRDoubleList___setitem____SWIG_0(), _wrap_SoapySDRDoubleList___setslice__(), _wrap_SoapySDRDoubleList___setslice____SWIG_0(), _wrap_SoapySDRDoubleList_erase(), _wrap_SoapySDRDoubleList_insert(), _wrap_SoapySDRDoubleList_resize(), _wrap_SoapySDRKwargsList___bool__(), _wrap_SoapySDRKwargsList___delitem__(), _wrap_SoapySDRKwargsList___getitem__(), _wrap_SoapySDRKwargsList___getitem____SWIG_1(), _wrap_SoapySDRKwargsList___len__(), _wrap_SoapySDRKwargsList___nonzero__(), _wrap_SoapySDRKwargsList___setitem__(), _wrap_SoapySDRKwargsList___setitem____SWIG_0(), _wrap_SoapySDRKwargsList___setslice__(), _wrap_SoapySDRKwargsList___setslice____SWIG_0(), _wrap_SoapySDRKwargsList_assign(), _wrap_SoapySDRKwargsList_erase(), _wrap_SoapySDRKwargsList_get_allocator(), _wrap_SoapySDRKwargsList_insert(), _wrap_SoapySDRKwargsList_push_back(), _wrap_SoapySDRKwargsList_resize(), _wrap_SoapySDRKwargsList_resize__SWIG_1(), _wrap_SoapySDRRangeList___delitem__(), _wrap_SoapySDRRangeList___getitem__(), _wrap_SoapySDRRangeList___setitem__(), _wrap_SoapySDRRangeList___setitem____SWIG_0(), _wrap_SoapySDRRangeList___setslice__(), _wrap_SoapySDRRangeList___setslice____SWIG_0(), _wrap_SoapySDRRangeList_erase(), _wrap_SoapySDRRangeList_insert(), _wrap_SoapySDRRangeList_resize(), _wrap_SoapySDRSizeList___delitem__(), _wrap_SoapySDRSizeList___getitem__(), _wrap_SoapySDRSizeList___setitem__(), _wrap_SoapySDRSizeList___setitem____SWIG_0(), _wrap_SoapySDRSizeList___setslice__(), _wrap_SoapySDRSizeList___setslice____SWIG_0(), _wrap_SoapySDRSizeList_erase(), _wrap_SoapySDRSizeList_insert(), _wrap_SoapySDRSizeList_resize(), _wrap_SoapySDRStringList___delitem__(), _wrap_SoapySDRStringList___getitem__(), _wrap_SoapySDRStringList___setitem__(), _wrap_SoapySDRStringList___setitem____SWIG_0(), _wrap_SoapySDRStringList___setslice__(), _wrap_SoapySDRStringList___setslice____SWIG_0(), _wrap_SoapySDRStringList_erase(), _wrap_SoapySDRStringList_insert(), _wrap_SoapySDRStringList_resize(), _wrap_SoapySDRUnsignedList___delitem__(), _wrap_SoapySDRUnsignedList___getitem__(), _wrap_SoapySDRUnsignedList___setitem__(), _wrap_SoapySDRUnsignedList___setitem____SWIG_0(), _wrap_SoapySDRUnsignedList___setslice__(), _wrap_SoapySDRUnsignedList___setslice____SWIG_0(), _wrap_SoapySDRUnsignedList_erase(), _wrap_SoapySDRUnsignedList_insert(), _wrap_SoapySDRUnsignedList_resize(), _wrap_split_cc_sptr_set_processor_affinity(), _wrap_split_fsk_cc_sptr_set_processor_affinity(), _wrap_static_target_simulator_cc_sptr_set_processor_affinity(), _wrap_tracking_singletarget_sptr_set_processor_affinity(), _wrap_transpose_matrix_vcvc_sptr_set_processor_affinity(), _wrap_trigger_command_sptr_set_processor_affinity(), _wrap_ts_fft_cc_sptr_set_processor_affinity(), _wrap_usrp_echotimer_cc_sptr_set_processor_affinity(), swig::traits_from_stdseq< Seq, T >::from(), swig::traits_from< int >::from(), swig::traits_from< size_t >::from(), swig::traits_from< double >::from(), lms(), std_map_Sl_std_string_Sc_std_string_Sg__erase__SWIG_2(), std_vector_Sl_SoapySDR_ArgInfo_Sg__insert__SWIG_1(), SWIG_AsVal_std_string(), swig::traits< SoapySDR::ArgInfo >::type_name(), and swig::traits< SoapySDR::Range >::type_name().