LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/host_src/spi.cpp File Reference
spi.cpp File Reference
#include "spi.h"
#include "IConnection.h"
#include <ciso646>
#include <vector>
#include <string>
#include <fstream>
Functions
void SPI_write (unsigned short spiAddrReg, unsigned short spiDataReg)
unsigned short SPI_read (unsigned short spiAddrReg)
void Modify_SPI_Reg_bits_WrOnly (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data, const uint16_t spiDataReg)
void Modify_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data)
uint16_t Get_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits)
void SPI_read_batch (const uint16_t *addr, uint16_t *values, uint8_t cnt)
void SPI_write_batch (const uint16_t *addr, const uint16_t *values, uint8_t cnt)
int BeginBatch (const char *name)
void EndBatch ()
void Modify_SPI_Reg_mask (const uint16_t *addr, const uint16_t *values, const uint16_t *masks, uint8_t cnt)
Modifies given registers with values applied using masks.
Variables
lime::IConnection * serPort
bool batchActive = false
std::string bName
std::vector< uint16_t > bAddr
std::vector< uint16_t > bData
std::vector< uint16_t > bMask
uint32_t readCnt = 0
uint32_t writeCnt = 0
Function Documentation
int BeginBatch (const char * name)
Definition at line 142 of file spi.cpp.
References batchActive, and bName.
Referenced by TuneRxFilterSetup(), and TuneTxFilterSetup().
void EndBatch ()
Definition at line 154 of file spi.cpp.
References bName, i, temp, and val.
Referenced by TuneRxFilterSetup(), and TuneTxFilterSetup().
uint16_t Get_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits)
Definition at line 94 of file spi.cpp.
References SPI_read().
void Modify_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data)
Definition at line 65 of file spi.cpp.
References batchActive, i, SPI_read(), and SPI_write().
void Modify_SPI_Reg_bits_WrOnly (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data, const uint16_t spiDataReg)
Definition at line 37 of file spi.cpp.
References batchActive, i, and SPI_write().
void Modify_SPI_Reg_mask (const uint16_t * addr, const uint16_t * values, const uint16_t * masks, uint8_t cnt)
Modifies given registers with values applied using masks.
Parameters
addr array of register addresses
masks array of applied masks
values array of values to be written
start starting index of given arrays
stop end index of given arrays
Definition at line 244 of file spi.cpp.
References i, SPI_read(), and SPI_write().
unsigned short SPI_read (unsigned short spiAddrReg)
Definition at line 28 of file spi.cpp.
References readCnt, and lime::IConnection::TransactSPI().
Referenced by Get_SPI_Reg_bits(), Modify_SPI_Reg_bits(), and Modify_SPI_Reg_mask().
void SPI_read_batch (const uint16_t * addr, uint16_t * values, uint8_t cnt)
Definition at line 100 of file spi.cpp.
References i, readCnt, and lime::IConnection::TransactSPI().
void SPI_write (unsigned short spiAddrReg, unsigned short spiDataReg)
Definition at line 21 of file spi.cpp.
References lime::IConnection::TransactSPI(), and writeCnt.
Referenced by Modify_SPI_Reg_bits(), Modify_SPI_Reg_bits_WrOnly(), and Modify_SPI_Reg_mask().
void SPI_write_batch (const uint16_t * addr, const uint16_t * values, uint8_t cnt)
Definition at line 111 of file spi.cpp.
References batchActive, i, lime::IConnection::TransactSPI(), and writeCnt.
Referenced by MCU_RunProcedure(), MCU_UploadProgram(), and SaveChipState().
Variable Documentation
std::vector<uint16_t> bAddr
Definition at line 13 of file spi.cpp.
bool batchActive = false
Definition at line 7 of file spi.cpp.
Referenced by BeginBatch(), Modify_SPI_Reg_bits(), Modify_SPI_Reg_bits_WrOnly(), and SPI_write_batch().
std::vector<uint16_t> bData
Definition at line 14 of file spi.cpp.
std::vector<uint16_t> bMask
Definition at line 15 of file spi.cpp.
std::string bName
Definition at line 12 of file spi.cpp.
Referenced by BeginBatch(), and EndBatch().
uint32_t readCnt = 0
Definition at line 17 of file spi.cpp.
Referenced by SPI_read(), and SPI_read_batch().
lime::IConnection* serPort
Definition at line 21 of file main.cpp.
Referenced by LMS7002M_Novena_wxgui::Initialize(), main(), and TEST_F().
uint32_t writeCnt = 0
Definition at line 18 of file spi.cpp.
Referenced by SPI_write(), and SPI_write_batch().