LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/Factory.cpp File Reference
Factory.cpp File Reference
#include <SoapySDR/Device.hpp>
#include <SoapySDR/Registry.hpp>
#include <SoapySDR/Modules.hpp>
#include <stdexcept>
#include <iostream>
#include <mutex>
Typedefs
typedef std::map< SoapySDR::Kwargs, SoapySDR::Device * > DeviceTable
typedef std::map< SoapySDR::Device *, size_t > DeviceCounts
Functions
static std::recursive_mutex & getFactoryMutex (void)
static DeviceTable & getDeviceTable (void)
static DeviceCounts & getDeviceCounts (void)
static SoapySDR::Device * getDeviceFromTable (const SoapySDR::Kwargs &args)
Typedef Documentation
typedef std::map<SoapySDR::Device *, size_t> DeviceCounts
Definition at line 25 of file Factory.cpp.
typedef std::map<SoapySDR::Kwargs, SoapySDR::Device *> DeviceTable
Definition at line 17 of file Factory.cpp.
Function Documentation
static DeviceCounts& getDeviceCounts (void) static
Definition at line 27 of file Factory.cpp.
References args, SoapySDR.Device::enumerate, getFactoryMutex(), i, SoapySDR::KwargsFromString, SoapySDR::Registry::listFindFunctions(), SoapySDR::loadModules, and string().
Referenced by getDeviceFromTable().
static SoapySDR::Device* getDeviceFromTable (const SoapySDR::Kwargs & args) static
Definition at line 68 of file Factory.cpp.
References args, device, SoapySDR.Device::enumerate, getDeviceCounts(), getDeviceTable(), getFactoryMutex(), SoapySDR::KwargsFromString, SoapySDR::Registry::listMakeFunctions(), SoapySDR.Device::make, string(), and SoapySDR.Device::unmake.
static DeviceTable& getDeviceTable (void) static
Definition at line 19 of file Factory.cpp.
Referenced by getDeviceFromTable().
static std::recursive_mutex& getFactoryMutex (void) static
Definition at line 11 of file Factory.cpp.
Referenced by getDeviceCounts(), and getDeviceFromTable().