LimeSuite-UML: dlgDeviceInfo Class Reference
dlgDeviceInfo Class Reference
Implementing dlgDeviceInfo_view.
#include <dlgDeviceInfo.h>
Public Member Functions
dlgDeviceInfo (wxWindow *parent)
Constructor.
dlgDeviceInfo (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long styles=0)
virtual void Initialize (lms_device_t *lms)
Public Member Functions inherited from dlgDeviceInfo_view
dlgDeviceInfo_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("Device Info"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE)
~dlgDeviceInfo_view ()
Protected Member Functions
void OnGetInfo (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
Protected Attributes inherited from dlgDeviceInfo_view
wxButton * btnGetInfo
wxStaticText * m_staticText6
wxStaticText * lblDeviceCtr
wxStaticText * m_staticText8
wxStaticText * lblExpansionCtr
wxStaticText * m_staticText10
wxStaticText * lblFirmwareCtr
wxStaticText * m_staticText12
wxStaticText * lblHardwareCtr
wxStaticText * m_staticText14
wxStaticText * lblProtocolCtr
wxStaticText * m_staticText41
wxStaticText * lblGatewareCtr
wxStaticText * m_staticText45
wxStaticText * lblGatewareTargetCtr
Detailed Description
Implementing dlgDeviceInfo_view.
Definition at line 13 of file dlgDeviceInfo.h.
Constructor & Destructor Documentation
dlgDeviceInfo::dlgDeviceInfo (wxWindow * parent)
Constructor.
dlgDeviceInfo::dlgDeviceInfo (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long styles = 0)
Definition at line 4 of file dlgDeviceInfo.cpp.
References lmsControl.
Member Function Documentation
void dlgDeviceInfo::Initialize (lms_device_t * lms) virtual
Definition at line 12 of file dlgDeviceInfo.cpp.
References lms(), and lmsControl.
Referenced by LMS7SuiteAppFrame::OnShowDeviceInfo(), and LMS7SuiteAppFrame::UpdateConnections().
void dlgDeviceInfo::OnGetInfo (wxCommandEvent & event) protected virtual
Reimplemented from dlgDeviceInfo_view.
Definition at line 17 of file dlgDeviceInfo.cpp.
References lms_dev_info_t::deviceName, lms_dev_info_t::expansionName, lms_dev_info_t::firmwareVersion, lms_dev_info_t::gatewareTargetBoard, lms_dev_info_t::gatewareVersion, lms_dev_info_t::hardwareVersion, info, dlgDeviceInfo_view::lblDeviceCtr, dlgDeviceInfo_view::lblExpansionCtr, dlgDeviceInfo_view::lblFirmwareCtr, dlgDeviceInfo_view::lblGatewareCtr, dlgDeviceInfo_view::lblGatewareTargetCtr, dlgDeviceInfo_view::lblHardwareCtr, dlgDeviceInfo_view::lblProtocolCtr, LMS_GetDeviceInfo(), lmsControl, and lms_dev_info_t::protocolVersion.
Member Data Documentation
lms_device_t* dlgDeviceInfo::lmsControl protected
Definition at line 25 of file dlgDeviceInfo.h.
Referenced by dlgDeviceInfo(), Initialize(), and OnGetInfo().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/dlgDeviceInfo.h
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/dlgDeviceInfo.cpp