LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/CMakeLists.txt File Reference
/home/erik/prefix/default/src/soapysdr/CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 2.8.7) project(SoapySDR) enable_language(CXX) enable_testing() file(READ"$
Changelog txt changelog_txt string (REGEX MATCH"Release ([0-9]+\\.[0-9]+\\.[0-9]+) \\("CHANGELOG_MATCH"${changelog_txt}") if(NOT CHANGELOG_MATCH) message(FATAL_ERROR"Failed to extract version number from Changelog.txt") endif(NOT CHANGELOG_MATCH) set(SOAPY_SDR_LIBVER"$
if (NOT SOAPY_SDR_EXTVER) include($
cmake Modules GetGitRevisionDescription cmake get_git_head_revision (GITREFSPEC GITHASH) if(GITHASH) string(SUBSTRING"$
GITHASH set (SOAPY_SDR_EXTVER"g${GITHASH}") else(GITHASH) set(SOAPY_SDR_EXTVER"unknown") endif(GITHASH) endif() set(SOAPY_SDR_VERSION"$
Function Documentation
cmake_minimum_required (VERSION 2.8. 7)
Definition at line 4 of file CMakeLists.txt.
cmake Modules GetGitRevisionDescription cmake get_git_head_revision (GITREFSPEC GITHASH)
Definition at line 22 of file CMakeLists.txt.
if (NOT SOAPY_SDR_EXTVER)
Definition at line 20 of file CMakeLists.txt.
GITHASH set (SOAPY_SDR_EXTVER"g${GITHASH}")
Definition at line 25 of file CMakeLists.txt.
References enabled, features, SoapySDR::getRootPath, install(), rpath, so, SOAPY_SDR_ABI_VERSION, and calc_fmcw_peaks::v.
Changelog txt changelog_txt string ()
Definition at line 14 of file CMakeLists.txt.
References swig::from().
Referenced by _wrap_ArgInfo_description_get(), _wrap_ArgInfo_description_set(), _wrap_ArgInfo_key_get(), _wrap_ArgInfo_key_set(), _wrap_ArgInfo_name_get(), _wrap_ArgInfo_name_set(), _wrap_ArgInfo_units_get(), _wrap_ArgInfo_units_set(), _wrap_ArgInfo_value_get(), _wrap_ArgInfo_value_set(), _wrap_crop_matrix_vcvc_make(), _wrap_crop_matrix_vcvc_sptr_alias(), _wrap_crop_matrix_vcvc_sptr_make(), _wrap_crop_matrix_vcvc_sptr_name(), _wrap_crop_matrix_vcvc_sptr_set_block_alias(), _wrap_crop_matrix_vcvc_sptr_symbol_name(), _wrap_Device_enumerate(), _wrap_Device_enumerate__SWIG_0(), _wrap_Device_enumerate__SWIG_1(), _wrap_Device_enumerate__SWIG_2(), _wrap_Device_getAntenna(), _wrap_Device_getClockSource(), _wrap_Device_getDriverKey(), _wrap_Device_getFrequency(), _wrap_Device_getFrequency__SWIG_1(), _wrap_Device_getFrequencyRange(), _wrap_Device_getFrequencyRange__SWIG_1(), _wrap_Device_getFrontendMapping(), _wrap_Device_getGain(), _wrap_Device_getGain__SWIG_1(), _wrap_Device_getGainRange(), _wrap_Device_getGainRange__SWIG_1(), _wrap_Device_getHardwareKey(), _wrap_Device_getHardwareTime(), _wrap_Device_getHardwareTime__SWIG_0(), _wrap_Device_getNativeStreamFormat(), _wrap_Device_getSensorInfo(), _wrap_Device_getSensorInfo__SWIG_0(), _wrap_Device_getSensorInfo__SWIG_1(), _wrap_Device_getTimeSource(), _wrap_Device_hasHardwareTime(), _wrap_Device_hasHardwareTime__SWIG_0(), _wrap_Device_make(), _wrap_Device_make__SWIG_0(), _wrap_Device_make__SWIG_2(), _wrap_Device_readGPIO(), _wrap_Device_readGPIODir(), _wrap_Device_readI2C(), _wrap_Device_readRegister(), _wrap_Device_readRegister__SWIG_0(), _wrap_Device_readRegisters(), _wrap_Device_readSensor(), _wrap_Device_readSensor__SWIG_0(), _wrap_Device_readSensor__SWIG_1(), _wrap_Device_readSetting(), _wrap_Device_readSetting__SWIG_0(), _wrap_Device_readSetting__SWIG_1(), _wrap_Device_readUART(), _wrap_Device_readUART__SWIG_0(), _wrap_Device_readUART__SWIG_1(), _wrap_Device_setAntenna(), _wrap_Device_setClockSource(), _wrap_Device_setCommandTime(), _wrap_Device_setCommandTime__SWIG_0(), _wrap_Device_setFrequency(), _wrap_Device_setFrequency__SWIG_2(), _wrap_Device_setFrequency__SWIG_3(), _wrap_Device_setFrontendMapping(), _wrap_Device_setGain(), _wrap_Device_setGain__SWIG_1(), _wrap_Device_setHardwareTime(), _wrap_Device_setHardwareTime__SWIG_0(), _wrap_Device_setTimeSource(), _wrap_Device_setupStream(), _wrap_Device_setupStream__SWIG_0(), _wrap_Device_setupStream__SWIG_1(), _wrap_Device_setupStream__SWIG_2(), _wrap_Device_writeGPIO(), _wrap_Device_writeGPIO__SWIG_0(), _wrap_Device_writeGPIO__SWIG_1(), _wrap_Device_writeGPIODir(), _wrap_Device_writeGPIODir__SWIG_0(), _wrap_Device_writeGPIODir__SWIG_1(), _wrap_Device_writeI2C(), _wrap_Device_writeRegister(), _wrap_Device_writeRegister__SWIG_0(), _wrap_Device_writeRegisters(), _wrap_Device_writeSetting(), _wrap_Device_writeSetting__SWIG_0(), _wrap_Device_writeSetting__SWIG_1(), _wrap_Device_writeUART(), _wrap_estimator_cw_sptr_alias(), _wrap_estimator_cw_sptr_name(), _wrap_estimator_cw_sptr_set_block_alias(), _wrap_estimator_cw_sptr_symbol_name(), _wrap_estimator_fmcw_sptr_alias(), _wrap_estimator_fmcw_sptr_name(), _wrap_estimator_fmcw_sptr_set_block_alias(), _wrap_estimator_fmcw_sptr_symbol_name(), _wrap_estimator_fsk_sptr_alias(), _wrap_estimator_fsk_sptr_name(), _wrap_estimator_fsk_sptr_set_block_alias(), _wrap_estimator_fsk_sptr_symbol_name(), _wrap_estimator_ofdm_make(), _wrap_estimator_ofdm_sptr_alias(), _wrap_estimator_ofdm_sptr_make(), _wrap_estimator_ofdm_sptr_name(), _wrap_estimator_ofdm_sptr_set_block_alias(), _wrap_estimator_ofdm_sptr_symbol_name(), _wrap_estimator_rcs_sptr_alias(), _wrap_estimator_rcs_sptr_name(), _wrap_estimator_rcs_sptr_set_block_alias(), _wrap_estimator_rcs_sptr_symbol_name(), _wrap_estimator_sync_pulse_c_make(), _wrap_estimator_sync_pulse_c_sptr_alias(), _wrap_estimator_sync_pulse_c_sptr_make(), _wrap_estimator_sync_pulse_c_sptr_name(), _wrap_estimator_sync_pulse_c_sptr_set_block_alias(), _wrap_estimator_sync_pulse_c_sptr_symbol_name(), _wrap_find_max_peak_c_make(), _wrap_find_max_peak_c_sptr_alias(), _wrap_find_max_peak_c_sptr_make(), _wrap_find_max_peak_c_sptr_name(), _wrap_find_max_peak_c_sptr_set_block_alias(), _wrap_find_max_peak_c_sptr_symbol_name(), _wrap_formatToSize(), _wrap_getABIVersion(), _wrap_getAPIVersion(), _wrap_getLibVersion(), _wrap_getLoaderResult(), _wrap_getModuleVersion(), _wrap_getRootPath(), _wrap_gpio_source_s_make(), _wrap_gpio_source_s_sptr_alias(), _wrap_gpio_source_s_sptr_make(), _wrap_gpio_source_s_sptr_name(), _wrap_gpio_source_s_sptr_set_block_alias(), _wrap_gpio_source_s_sptr_symbol_name(), _wrap_KwargsFromString(), _wrap_KwargsToString(), _wrap_listModules(), _wrap_listModules__SWIG_1(), _wrap_loadModule(), _wrap_log(), _wrap_msg_gate_sptr_alias(), _wrap_msg_gate_sptr_name(), _wrap_msg_gate_sptr_set_block_alias(), _wrap_msg_gate_sptr_symbol_name(), _wrap_msg_manipulator_sptr_alias(), _wrap_msg_manipulator_sptr_name(), _wrap_msg_manipulator_sptr_set_block_alias(), _wrap_msg_manipulator_sptr_symbol_name(), _wrap_new_ModuleVersion(), _wrap_new_SoapySDRKwargs(), _wrap_new_SoapySDRKwargsList(), _wrap_new_SoapySDRKwargsList__SWIG_3(), _wrap_new_SoapySDRStringList(), _wrap_new_SoapySDRStringList__SWIG_3(), _wrap_ofdm_cyclic_prefix_remover_cvc_make(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_alias(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_make(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_name(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_set_block_alias(), _wrap_ofdm_cyclic_prefix_remover_cvc_sptr_symbol_name(), _wrap_ofdm_divide_vcvc_make(), _wrap_ofdm_divide_vcvc_sptr_alias(), _wrap_ofdm_divide_vcvc_sptr_make(), _wrap_ofdm_divide_vcvc_sptr_name(), _wrap_ofdm_divide_vcvc_sptr_set_block_alias(), _wrap_ofdm_divide_vcvc_sptr_symbol_name(), _wrap_os_cfar_2d_vc_make(), _wrap_os_cfar_2d_vc_sptr_alias(), _wrap_os_cfar_2d_vc_sptr_make(), _wrap_os_cfar_2d_vc_sptr_name(), _wrap_os_cfar_2d_vc_sptr_set_block_alias(), _wrap_os_cfar_2d_vc_sptr_symbol_name(), _wrap_os_cfar_c_make(), _wrap_os_cfar_c_sptr_alias(), _wrap_os_cfar_c_sptr_make(), _wrap_os_cfar_c_sptr_name(), _wrap_os_cfar_c_sptr_set_block_alias(), _wrap_os_cfar_c_sptr_symbol_name(), _wrap_print_results_make(), _wrap_print_results_sptr_alias(), _wrap_print_results_sptr_make(), _wrap_print_results_sptr_name(), _wrap_print_results_sptr_set_block_alias(), _wrap_print_results_sptr_symbol_name(), _wrap_qtgui_scatter_plot_make(), _wrap_qtgui_scatter_plot_sptr_alias(), _wrap_qtgui_scatter_plot_sptr_make(), _wrap_qtgui_scatter_plot_sptr_name(), _wrap_qtgui_scatter_plot_sptr_set_block_alias(), _wrap_qtgui_scatter_plot_sptr_symbol_name(), _wrap_qtgui_spectrogram_plot_make(), _wrap_qtgui_spectrogram_plot_sptr_alias(), _wrap_qtgui_spectrogram_plot_sptr_make(), _wrap_qtgui_spectrogram_plot_sptr_name(), _wrap_qtgui_spectrogram_plot_sptr_set_block_alias(), _wrap_qtgui_spectrogram_plot_sptr_symbol_name(), _wrap_qtgui_time_plot_make(), _wrap_qtgui_time_plot_sptr_alias(), _wrap_qtgui_time_plot_sptr_make(), _wrap_qtgui_time_plot_sptr_name(), _wrap_qtgui_time_plot_sptr_set_block_alias(), _wrap_qtgui_time_plot_sptr_symbol_name(), _wrap_signal_generator_cw_c_make(), _wrap_signal_generator_cw_c_sptr_alias(), _wrap_signal_generator_cw_c_sptr_make(), _wrap_signal_generator_cw_c_sptr_name(), _wrap_signal_generator_cw_c_sptr_set_block_alias(), _wrap_signal_generator_cw_c_sptr_symbol_name(), _wrap_signal_generator_fmcw_c_make(), _wrap_signal_generator_fmcw_c_sptr_alias(), _wrap_signal_generator_fmcw_c_sptr_make(), _wrap_signal_generator_fmcw_c_sptr_name(), _wrap_signal_generator_fmcw_c_sptr_set_block_alias(), _wrap_signal_generator_fmcw_c_sptr_symbol_name(), _wrap_signal_generator_fsk_c_make(), _wrap_signal_generator_fsk_c_sptr_alias(), _wrap_signal_generator_fsk_c_sptr_make(), _wrap_signal_generator_fsk_c_sptr_name(), _wrap_signal_generator_fsk_c_sptr_set_block_alias(), _wrap_signal_generator_fsk_c_sptr_symbol_name(), _wrap_signal_generator_sync_pulse_c_make(), _wrap_signal_generator_sync_pulse_c_sptr_alias(), _wrap_signal_generator_sync_pulse_c_sptr_make(), _wrap_signal_generator_sync_pulse_c_sptr_name(), _wrap_signal_generator_sync_pulse_c_sptr_set_block_alias(), _wrap_signal_generator_sync_pulse_c_sptr_symbol_name(), _wrap_soapysdr_echotimer_make(), _wrap_soapysdr_echotimer_sptr_alias(), _wrap_soapysdr_echotimer_sptr_make(), _wrap_soapysdr_echotimer_sptr_name(), _wrap_soapysdr_echotimer_sptr_set_block_alias(), _wrap_soapysdr_echotimer_sptr_symbol_name(), _wrap_soapysdr_echotimer_stretch_make(), _wrap_soapysdr_echotimer_stretch_sptr_alias(), _wrap_soapysdr_echotimer_stretch_sptr_make(), _wrap_soapysdr_echotimer_stretch_sptr_name(), _wrap_soapysdr_echotimer_stretch_sptr_set_block_alias(), _wrap_soapysdr_echotimer_stretch_sptr_symbol_name(), _wrap_SoapySDRKwargs___contains__(), _wrap_SoapySDRKwargs___delitem__(), _wrap_SoapySDRKwargs___getitem__(), _wrap_SoapySDRKwargs___setitem__(), _wrap_SoapySDRKwargs___setitem____SWIG_0(), _wrap_SoapySDRKwargs___setitem____SWIG_1(), _wrap_SoapySDRKwargs_count(), _wrap_SoapySDRKwargs_erase(), _wrap_SoapySDRKwargs_erase__SWIG_0(), _wrap_SoapySDRKwargs_find(), _wrap_SoapySDRKwargs_has_key(), _wrap_SoapySDRKwargs_lower_bound(), _wrap_SoapySDRKwargs_upper_bound(), _wrap_SoapySDRKwargsList___bool__(), _wrap_SoapySDRKwargsList___delitem__(), _wrap_SoapySDRKwargsList___getitem__(), _wrap_SoapySDRKwargsList___getitem____SWIG_1(), _wrap_SoapySDRKwargsList___len__(), _wrap_SoapySDRKwargsList___nonzero__(), _wrap_SoapySDRKwargsList___setitem__(), _wrap_SoapySDRKwargsList___setitem____SWIG_0(), _wrap_SoapySDRKwargsList___setitem____SWIG_2(), _wrap_SoapySDRKwargsList___setslice__(), _wrap_SoapySDRKwargsList___setslice____SWIG_0(), _wrap_SoapySDRKwargsList_append(), _wrap_SoapySDRKwargsList_assign(), _wrap_SoapySDRKwargsList_erase(), _wrap_SoapySDRKwargsList_get_allocator(), _wrap_SoapySDRKwargsList_insert(), _wrap_SoapySDRKwargsList_insert__SWIG_0(), _wrap_SoapySDRKwargsList_insert__SWIG_1(), _wrap_SoapySDRKwargsList_push_back(), _wrap_SoapySDRKwargsList_resize(), _wrap_SoapySDRKwargsList_resize__SWIG_1(), _wrap_SoapySDRStringList___delitem__(), _wrap_SoapySDRStringList___getitem__(), _wrap_SoapySDRStringList___setitem__(), _wrap_SoapySDRStringList___setitem____SWIG_0(), _wrap_SoapySDRStringList___setitem____SWIG_2(), _wrap_SoapySDRStringList___setslice__(), _wrap_SoapySDRStringList___setslice____SWIG_0(), _wrap_SoapySDRStringList_append(), _wrap_SoapySDRStringList_assign(), _wrap_SoapySDRStringList_erase(), _wrap_SoapySDRStringList_insert(), _wrap_SoapySDRStringList_insert__SWIG_0(), _wrap_SoapySDRStringList_insert__SWIG_1(), _wrap_SoapySDRStringList_push_back(), _wrap_SoapySDRStringList_resize(), _wrap_SoapySDRStringList_resize__SWIG_1(), _wrap_split_cc_make(), _wrap_split_cc_sptr_alias(), _wrap_split_cc_sptr_make(), _wrap_split_cc_sptr_name(), _wrap_split_cc_sptr_set_block_alias(), _wrap_split_cc_sptr_symbol_name(), _wrap_split_fsk_cc_make(), _wrap_split_fsk_cc_sptr_alias(), _wrap_split_fsk_cc_sptr_make(), _wrap_split_fsk_cc_sptr_name(), _wrap_split_fsk_cc_sptr_set_block_alias(), _wrap_split_fsk_cc_sptr_symbol_name(), _wrap_static_target_simulator_cc_make(), _wrap_static_target_simulator_cc_sptr_alias(), _wrap_static_target_simulator_cc_sptr_make(), _wrap_static_target_simulator_cc_sptr_name(), _wrap_static_target_simulator_cc_sptr_set_block_alias(), _wrap_static_target_simulator_cc_sptr_symbol_name(), _wrap_tracking_singletarget_make(), _wrap_tracking_singletarget_sptr_alias(), _wrap_tracking_singletarget_sptr_make(), _wrap_tracking_singletarget_sptr_name(), _wrap_tracking_singletarget_sptr_set_block_alias(), _wrap_tracking_singletarget_sptr_symbol_name(), _wrap_transpose_matrix_vcvc_make(), _wrap_transpose_matrix_vcvc_sptr_alias(), _wrap_transpose_matrix_vcvc_sptr_make(), _wrap_transpose_matrix_vcvc_sptr_name(), _wrap_transpose_matrix_vcvc_sptr_set_block_alias(), _wrap_transpose_matrix_vcvc_sptr_symbol_name(), _wrap_trigger_command_make(), _wrap_trigger_command_sptr_alias(), _wrap_trigger_command_sptr_make(), _wrap_trigger_command_sptr_name(), _wrap_trigger_command_sptr_set_block_alias(), _wrap_trigger_command_sptr_symbol_name(), _wrap_ts_fft_cc_make(), _wrap_ts_fft_cc_sptr_alias(), _wrap_ts_fft_cc_sptr_make(), _wrap_ts_fft_cc_sptr_name(), _wrap_ts_fft_cc_sptr_set_block_alias(), _wrap_ts_fft_cc_sptr_symbol_name(), _wrap_unloadModule(), _wrap_usrp_echotimer_cc_make(), _wrap_usrp_echotimer_cc_sptr_alias(), _wrap_usrp_echotimer_cc_sptr_make(), _wrap_usrp_echotimer_cc_sptr_name(), _wrap_usrp_echotimer_cc_sptr_set_block_alias(), _wrap_usrp_echotimer_cc_sptr_symbol_name(), LimeSDRTest_USB::ADF4002Test(), args_to_io_signature(), args_to_vector(), argsToMap(), CB_FunctionCLI(), lime::Si5351C::ClearStatus(), LimeSDRTest::Connect(), DEFUN_DLD(), dict_to_args_string(), lime::downloadImageResource(), lime::ConnectionFT601Entry::enumerate(), lime::ConnectionFX3Entry::enumerate(), lime::GetAPIVersion(), getDefaultLogLevel(), getDeviceCounts(), getDeviceFromTable(), lime::ConnectionSTREAM_UNITE::GetDeviceInfo(), getEnvImpl(), SoapySDR.Device::getFrequency(), SoapyLMS7::getFrequencyArgsInfo(), getFunctionTable(), SoapyLMS7::getHardwareInfo(), SoapyLMS7::getHardwareKey(), lime::getLimeSuiteRoot(), getModuleLoading(), getModuleVersions(), lime::LMS7002M::GetParam(), lime::Si5351C::GetStatusBits(), LimeSDRTest::GPIFClkTest(), LimeSDRTest::InitFPGATest(), lime::listImageSearchPaths(), SoapySDR::ConverterRegistry::listSourceFormats(), SoapySDR::ConverterRegistry::listTargetFormats(), LMS_Program(), LMS_ReadCustomBoardParam(), LMS_WriteCustomBoardParam(), lime::locateImageResource(), main(), swig::traits< Type * >::make_ptr_name(), Si5351C_wxgui::OnbtnLoadFileClick(), NumericSlider::OnSpinnerChangeEnter(), lime::ConnectionEVB7COM::Open(), lime::ConnectionFT601::Open(), lime::ConnectionFX3::Open(), params_to_dict(), params_to_vector(), LimeSDRTest::Perform_tests(), printInfo(), probeChannel(), programmingCallbackStream(), lime::LMS64CProtocol::ProgramUpdate(), SoapyLMS7::readGPIO(), SoapyLMS7::readGPIODir(), SoapySDR::Registry::Registry(), LimeSDRTest_Mini::RFTest(), LimeSDRTest_USB::RFTest(), LimeSDRTest::RFTestInfo(), LimeSDRTest::RunTests(), gr::radar::scatter_plot::scatter_plot(), searchModulePath(), lime::ConnectionHandle::serialize(), SoapySDR.Device::setFrequency(), SoapyLMS7::setupStream(), LimeSDRTest_USB::Si5351CTest(), SoapySDR_getABIVersion(), SoapySDR_getAPIVersion(), SoapySDR_getLibVersion(), SoapySDR_getRootPath(), SoapySDRDevice_readI2C(), SoapySDRDevice_writeI2C(), SoapySDRDeviceProbe(), gr::radar::spectrogram_plot::spectrogram_plot(), SWIG_AsPtr_std_string(), SWIG_AsVal_std_string(), gr::radar::time_plot::time_plot(), toString(), lime::ConnectionHandle::ToString(), LimeSDRTest::TransferLMS64C(), trim(), swig::traits< Type * >::type_name(), lime::Si5351C::UploadConfiguration(), LimeSDRTest::VCTCXOTest(), SoapyLMS7::writeGPIO(), and SoapyLMS7::writeGPIODir().