LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/lms7002m_filters.c File Reference
lms7002m_filters.c File Reference
#include "lms7002m_controls.h"
#include "lms7002m_calibrations.h"
#include "lms7002m_filters.h"
#include "LMS7002M_parameters_compact.h"
#include "spi.h"
#include <math.h>
#include "mcu_defines.h"
Classes
struct ReachRSSIparams
Macros
#define BATCH_RX_SETUP 1
#define BATCH_TX_SETUP 1
Enumerations
enum { SEARCH_SUCCESS = 0, SEARCH_NEED_TO_DECREASE, SEARCH_NEED_TO_INCREASE }
Functions
static uint8_t ConfigCGEN_ForLPF_IF (float IF_Hz)
static uint8_t RxFilterSearch (const uint16_t addr, const uint8_t msblsb, const uint16_t rssi_3dB, const uint16_t stepLimit)
uint8_t TuneRxFilterSetup (const float_type rx_lpf_IF)
static bool ChangeUntilReachRSSI (const ReachRSSIparams *param, uint16_t rssiTarget)
uint8_t TuneRxFilter (const float_type rx_lpf_freq_RF)
static void SetTxLPF_PDs (float lpf_IF)
uint8_t TuneTxFilterSetup (const float_type tx_lpf_IF)
static uint8_t SearchTxFilterCCAL_RCAL (uint16_t addr, uint8_t msblsb)
uint8_t TuneTxFilter (const float_type tx_lpf_freq_RF)
Variables
static const float_type RxLPF_RF_LimitLow = 1.4e6
static const float_type RxLPF_RF_LimitHigh = 130e6
static const float_type TxLPF_RF_LimitLow = 5e6
static const float_type TxLPF_RF_LimitLowMid = 40e6
static const float_type TxLPF_RF_LimitMidHigh = 50e6
static const float_type TxLPF_RF_LimitHigh = 130e6
Macro Definition Documentation
#define BATCH_RX_SETUP 1
#define BATCH_TX_SETUP 1
Enumeration Type Documentation
anonymous enum
Enumerator
SEARCH_SUCCESS
SEARCH_NEED_TO_DECREASE
SEARCH_NEED_TO_INCREASE
Definition at line 9 of file lms7002m_filters.c.
Function Documentation
static bool ChangeUntilReachRSSI (const ReachRSSIparams * param, uint16_t rssiTarget) static
Definition at line 280 of file lms7002m_filters.c.
References gain, Get_SPI_Reg_bits(), GetRSSI(), and Modify_SPI_Reg_bits().
Referenced by SearchTxFilterCCAL_RCAL(), TuneRxFilter(), and TuneTxFilter().
static uint8_t ConfigCGEN_ForLPF_IF (float IF_Hz) static
Definition at line 26 of file lms7002m_filters.c.
References clamp(), and SetFrequencyCGEN().
Referenced by TuneRxFilterSetup(), and TuneTxFilterSetup().
static uint8_t RxFilterSearch (const uint16_t addr, const uint8_t msblsb, const uint16_t rssi_3dB, const uint16_t stepLimit) static
Definition at line 32 of file lms7002m_filters.c.
References clamp(), Get_SPI_Reg_bits(), GetRSSI(), Modify_SPI_Reg_bits(), pow2(), SEARCH_NEED_TO_DECREASE, and SEARCH_NEED_TO_INCREASE.
Referenced by TuneRxFilter().
static uint8_t SearchTxFilterCCAL_RCAL (uint16_t addr, uint8_t msblsb) static
Definition at line 579 of file lms7002m_filters.c.
References CCAL_LPFLAD_TBB, ChangeUntilReachRSSI(), clamp(), Get_SPI_Reg_bits(), GetRSSI(), MCU_NO_ERROR, MCU_RCAL_LPF_LIMIT_REACHED, Modify_SPI_Reg_bits(), calc_fsk_peaks::R, ROM, SEL_RX, and SEL_TX.
Referenced by TuneTxFilter().
static void SetTxLPF_PDs (float lpf_IF) static
Definition at line 432 of file lms7002m_filters.c.
References Modify_SPI_Reg_bits(), R5_LPF_BYP_TBB, SPI_read(), SPI_write(), and TxLPF_RF_LimitLowMid.
Referenced by TuneTxFilter(), and TuneTxFilterSetup().
uint8_t TuneRxFilter (const float_type rx_lpf_freq_RF)
Definition at line 296 of file lms7002m_filters.c.
References CCOMP_TIA_RFE, CFB_TIA_RFE, CG_IAMP_TBB, ChangeUntilReachRSSI(), clamp(), G_RXLOOPB_RFE, G_TIA_RFE, Get_SPI_Reg_bits(), GetRSSI(), INPUT_CTL_PGA_RBB, int(), LMS7002M_Rx, MCU_CFB_TIA_RFE_LIMIT_REACHED, MCU_NO_ERROR, MCU_R_CTL_LPF_LIMIT_REACHED, MCU_RX_INVALID_TIA, Modify_SPI_Reg_bits(), MSB_LSB, R_CTL_LPF_RBB, RCOMP_TIA_RFE, ROM, RxFilterSearch(), SaveChipState(), SEARCH_NEED_TO_INCREASE, SEARCH_SUCCESS, SetFrequencySX(), SetNCOFrequency(), SPI_read(), SPI_write(), status, TuneRxFilterSetup(), and UpdateRSSIDelay().
Referenced by Filters(), and main().
uint8_t TuneRxFilterSetup (const float_type rx_lpf_IF)
Definition at line 65 of file lms7002m_filters.c.
References AGC_AVG_RXTSP, AGC_MODE_RXTSP, BeginBatch(), CG_IAMP_TBB, clamp(), CMIX_BYP_RXTSP, CMIX_GAIN_RXTSP, CMIX_SC_RXTSP, CMIX_SC_TXTSP, ConfigCGEN_ForLPF_IF(), EN_G_XBUF, EN_INSHSW_LB2_RFE, EN_LOOPB_TXPAD_TRF, EnableChannelPowerControls(), EnableMIMOBuffersIfNecessary(), EndBatch(), G_PGA_RBB, G_RXLOOPB_RFE, G_TIA_RFE, Get_SPI_Reg_bits(), GetValueOf_c_ctl_pga_rbb(), GFIR1_BYP_RXTSP, GFIR1_BYP_TXTSP, GFIR2_BYP_RXTSP, GFIR2_BYP_TXTSP, GFIR3_BYP_RXTSP, GFIR3_BYP_TXTSP, HBD_OVR_RXTSP, ICT_IAMP_FRP_TBB, ICT_IAMP_GG_FRP_TBB, ICT_PGA_IN_RBB, ICT_PGA_OUT_RBB, ICT_VCO_CGEN, INPUT_CTL_PGA_RBB, INSEL_TXTSP, L_LOOPB_TXPAD_TRF, LMS7002M_Rx, LMS7002M_Tx, LoadDC_REG_TX_IQ(), MAC, MCU_NO_ERROR, MCU_RX_INVALID_TIA, MCU_RX_LPF_OUT_OF_RANGE, Modify_SPI_Reg_bits(), MSB_LSB, PD_MXLOBUF_RFE, PD_QGEN_RFE, PD_RLOOPB_2_RFE, PD_RX_AFE2, PD_XBUF_RX, PD_XBUF_TX, RCOMP_TIA_RFE, RFB_TIA_RFE, ROM, RxLPF_RF_LimitHigh, RxLPF_RF_LimitLow, SECTION_AFE, SECTION_CGEN, SECTION_RBB, SECTION_RFE, SECTION_RxNCO, SECTION_RxTSP, SECTION_TBB, SECTION_TRF, SECTION_TxNCO, SECTION_TxTSP, SEL_BAND1_TRF, SEL_BAND2_TRF, SEL_PATH_RFE, SetDefaults(), SetDefaultsSX(), SetFrequencySX(), SetNCOFrequency(), SPI_read(), SPI_write(), status, TSGMODE_TXTSP, and WriteMaskedRegs().
Referenced by TuneRxFilter().
uint8_t TuneTxFilter (const float_type tx_lpf_freq_RF)
Definition at line 636 of file lms7002m_filters.c.
References C_CTL_PGA_RBB, CCAL_LPFLAD_TBB, CG_IAMP_TBB, ChangeUntilReachRSSI(), Get_SPI_Reg_bits(), MCU_NO_ERROR, MCU_TX_LPF_OUT_OF_RANGE, Modify_SPI_Reg_bits(), RCAL_LPFH_TBB, RCAL_LPFLAD_TBB, ROM, SaveChipState(), SearchTxFilterCCAL_RCAL(), SEL_RX, SEL_TX, SetTxLPF_PDs(), SPI_read(), SPI_write(), status, TuneTxFilterSetup(), TxLPF_RF_LimitHigh, TxLPF_RF_LimitLowMid, TxLPF_RF_LimitMidHigh, and UpdateRSSIDelay().
Referenced by Filters(), and main().
uint8_t TuneTxFilterSetup (const float_type tx_lpf_IF)
Definition at line 445 of file lms7002m_filters.c.
References AGC_AVG_RXTSP, AGC_MODE_RXTSP, BeginBatch(), CG_IAMP_TBB, clamp(), CMIX_SC_RXTSP, ConfigCGEN_ForLPF_IF(), EN_G_RFE, EN_G_TRF, EN_G_XBUF, EnableChannelPowerControls(), EnableMIMOBuffersIfNecessary(), EndBatch(), freq, G_PGA_RBB, Get_SPI_Reg_bits(), HBD_OVR_RXTSP, ICT_VCO_CGEN, INPUT_CTL_PGA_RBB, INSEL_TXTSP, ISEL_DAC_AFE, LMS7002M_Rx, LMS7002M_Tx, LoadDC_REG_TX_IQ(), LOOPB_TBB, MAC, MCU_NO_ERROR, Modify_SPI_Reg_bits(), PD_LPFL_RBB, PD_RX_AFE2, PD_TX_AFE2, PD_VCO, PD_XBUF_RX, PD_XBUF_TX, RCAL_LPFH_TBB, RCAL_LPFLAD_TBB, RCC_CTL_PGA_RBB, ROM, SECTION_AFE, SECTION_CGEN, SECTION_RBB, SECTION_RxNCO, SECTION_RxTSP, SECTION_TBB, SECTION_TxNCO, SECTION_TxTSP, SetDefaults(), SetNCOFrequency(), SetTxLPF_PDs(), SPI_read(), SPI_write(), status, TSGMODE_TXTSP, TxLPF_RF_LimitLowMid, and WriteMaskedRegs().
Referenced by TuneTxFilter().
Variable Documentation
const float_type RxLPF_RF_LimitHigh = 130e6 static
Definition at line 18 of file lms7002m_filters.c.
Referenced by TuneRxFilterSetup().
const float_type RxLPF_RF_LimitLow = 1.4e6 static
Definition at line 17 of file lms7002m_filters.c.
Referenced by TuneRxFilterSetup().
const float_type TxLPF_RF_LimitHigh = 130e6 static
Definition at line 24 of file lms7002m_filters.c.
Referenced by TuneTxFilter().
const float_type TxLPF_RF_LimitLow = 5e6 static
Definition at line 21 of file lms7002m_filters.c.
const float_type TxLPF_RF_LimitLowMid = 40e6 static
Definition at line 22 of file lms7002m_filters.c.
Referenced by SetTxLPF_PDs(), TuneTxFilter(), and TuneTxFilterSetup().
const float_type TxLPF_RF_LimitMidHigh = 50e6 static
Definition at line 23 of file lms7002m_filters.c.
Referenced by TuneTxFilter().