LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/LimeUtil/LimeUtilCalSweep.cpp File Reference
LimeUtilCalSweep.cpp File Reference
#include "lime/LimeSuite.h"
#include <iostream>
#include <cstdlib>
#include <cstddef>
#include <string>
#include <vector>
Functions
int deviceCalSweep (const std::string &argStr, const double start, const double stop, const double step, const double bw, const std::string &dirStr, const std::string &chansStr)
Function Documentation
int deviceCalSweep (const std::string & argStr, const double start, const double stop, const double step, const double bw, const std::string & dirStr, const std::string & chansStr)
Definition at line 14 of file LimeUtilCalSweep.cpp.
References device, dir_tx, freq, i, LMS_Calibrate(), LMS_CH_RX, LMS_CH_TX, LMS_Close(), LMS_EnableCalibCache(), LMS_EnableChannel(), LMS_GetLastErrorMessage(), LMS_GetNumChannels(), LMS_Open(), LMS_SetAntenna(), and LMS_SetLOFrequency().
Referenced by main().