LimeSuite-UML: lms7002_pnlLimeLightPAD_view Class Reference
lms7002_pnlLimeLightPAD_view Class Reference
Implementing pnlLimeLightPAD_view.
#include <lms7002_pnlLimeLightPAD_view.h>
Public Member Functions
lms7002_pnlLimeLightPAD_view (wxWindow *parent)
Constructor.
lms7002_pnlLimeLightPAD_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlLimeLightPAD_view
pnlLimeLightPAD_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlLimeLightPAD_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void ParameterChangeHandler (wxSpinEvent &event)
void onbtnReadVerRevMask (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlLimeLightPAD_view
wxNotebook * ID_NOTEBOOK1
wxPanel * ID_PANEL1
wxCheckBox * chkSDA_PE
wxCheckBox * chkSCL_PE
wxCheckBox * chkRX_CLK_PE
wxCheckBox * chkSDIO_PE
wxCheckBox * chkSDO_PE
wxCheckBox * chkTX_CLK_PE
wxCheckBox * chkSEN_PE
wxCheckBox * chkDIQ1_PE
wxCheckBox * chkTXNRX1_PE
wxCheckBox * chkSCLK_PE
wxCheckBox * chkDIQ2_PE
wxCheckBox * chkTXNRX2_PE
wxCheckBox * chkIQ_SEL_EN_1_PE
wxCheckBox * chkFCLK1_PE
wxCheckBox * chkMCLK1_PE
wxCheckBox * chkIQ_SEL_EN_2_PE
wxCheckBox * chkFCLK2_PE
wxCheckBox * chkMCLK2_PE
wxCheckBox * chkSRST_RXFIFO
wxCheckBox * chkSRST_TXFIFO
wxCheckBox * chkLRST_TX_A
wxCheckBox * chkLRST_TX_B
wxCheckBox * chkLRST_RX_A
wxCheckBox * chkLRST_RX_B
wxCheckBox * chkMRST_TX_A
wxCheckBox * chkMRST_TX_B
wxCheckBox * chkMRST_RX_A
wxCheckBox * chkMRST_RX_B
wxCheckBox * chkRXEN_A
wxCheckBox * chkTXEN_A
wxCheckBox * chkRXEN_B
wxCheckBox * chkTXEN_B
wxCheckBox * chkMIMO_SISO
wxCheckBox * chkMOD_EN
wxRadioBox * rgrLML_FIDM1
wxRadioBox * rgrLML_FIDM2
wxRadioBox * rgrLML_MODE1
wxRadioBox * rgrLML_MODE2
wxRadioBox * rgrLML_TXNRXIQ1
wxRadioBox * rgrLML_TXNRXIQ2
wxCheckBox * chkLML1_TRXIQPULSE
wxCheckBox * chkLML2_TRXIQPULSE
wxCheckBox * chkLML1_SISODDR
wxCheckBox * chkLML2_SISODDR
wxRadioBox * rgrSDA_DS
wxRadioBox * rgrSCL_DS
wxRadioBox * rgrSDIO_DS
wxRadioBox * rgrDIQ2_DS
wxRadioBox * rgrDIQ1_DS
wxRadioBox * rgrRX_MUX
wxRadioBox * rgrTX_MUX
wxRadioBox * rgrSPIMODE
wxStaticText * ID_STATICTEXT36
wxStaticText * lblVER
wxStaticText * ID_STATICTEXT38
wxStaticText * lblREV
wxStaticText * ID_STATICTEXT40
wxStaticText * lblMASK
wxButton * btnReadVerRevMask
wxPanel * ID_PANEL2
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbLML1_S3S
wxStaticText * ID_STATICTEXT2
wxComboBox * cmbLML1_S2S
wxStaticText * ID_STATICTEXT3
wxComboBox * cmbLML1_S1S
wxStaticText * ID_STATICTEXT4
wxComboBox * cmbLML1_S0S
wxStaticText * ID_STATICTEXT9
wxComboBox * cmbLML2_S3S
wxStaticText * ID_STATICTEXT10
wxComboBox * cmbLML2_S2S
wxStaticText * ID_STATICTEXT11
wxComboBox * cmbLML2_S1S
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbLML2_S0S
wxStaticText * ID_STATICTEXT5
wxComboBox * cmbLML1_BQP
wxStaticText * ID_STATICTEXT6
wxComboBox * cmbLML1_BIP
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbLML1_AQP
wxStaticText * ID_STATICTEXT8
wxComboBox * cmbLML1_AIP
wxStaticText * ID_STATICTEXT13
wxComboBox * cmbLML2_BQP
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbLML2_BIP
wxStaticText * ID_STATICTEXT15
wxComboBox * cmbLML2_AQP
wxStaticText * ID_STATICTEXT16
wxComboBox * cmbLML2_AIP
wxStaticText * ID_STATICTEXT25
wxComboBox * cmbTXRDCLK_MUX
wxStaticText * ID_STATICTEXT26
wxComboBox * cmbTXWRCLK_MUX
wxStaticText * ID_STATICTEXT27
wxComboBox * cmbRXRDCLK_MUX
wxStaticText * ID_STATICTEXT28
wxComboBox * cmbRXWRCLK_MUX
wxStaticText * ID_STATICTEXT29
wxComboBox * cmbMCLK2SRC
wxStaticText * ID_STATICTEXT30
wxComboBox * cmbMCLK1SRC
wxCheckBox * chkTXDIVEN
wxSpinCtrl * cmbTXTSPCLKA_DIV
wxCheckBox * chkRXDIVEN
wxSpinCtrl * cmbRXTSPCLKA_DIV
wxStaticText * ID_STATICTEXT37
wxSpinCtrl * cmbMCLK1DLY
wxStaticText * ID_STATICTEXT39
wxSpinCtrl * cmbMCLK2DLY
wxCheckBox * chkFCLK1_INV
wxCheckBox * chkFCLK2_INV
wxCheckBox * chkMCLK1_INV
wxCheckBox * chkMCLK2_INV
wxStaticText * ID_STATICTEXT301
wxComboBox * cmbFCLK1_DLY
wxStaticText * ID_STATICTEXT302
wxComboBox * cmbFCLK2_DLY
wxStaticText * ID_STATICTEXT303
wxComboBox * cmbMCLK1_DLY
wxStaticText * ID_STATICTEXT304
wxComboBox * cmbMCLK2_DLY
wxStaticText * ID_STATICTEXT17
wxSpinCtrl * cmbLML1_TX_PST
wxStaticText * ID_STATICTEXT18
wxSpinCtrl * cmbLML1_TX_PRE
wxStaticText * ID_STATICTEXT19
wxSpinCtrl * cmbLML1_RX_PST
wxStaticText * ID_STATICTEXT20
wxSpinCtrl * cmbLML1_RX_PRE
wxStaticText * ID_STATICTEXT21
wxSpinCtrl * cmbLML2_TX_PST
wxStaticText * ID_STATICTEXT22
wxSpinCtrl * cmbLML2_TX_PRE
wxStaticText * ID_STATICTEXT23
wxSpinCtrl * cmbLML2_RX_PST
wxStaticText * ID_STATICTEXT24
wxSpinCtrl * cmbLML2_RX_PRE
wxRadioBox * rgrDIQDIRCTR1
wxRadioBox * rgrDIQDIR1
wxRadioBox * rgrENABLEDIRCTR1
wxRadioBox * rgrENABLEDIR1
wxRadioBox * rgrDIQDIRCTR2
wxRadioBox * rgrDIQDIR2
wxRadioBox * rgrENABLEDIRCTR2
wxRadioBox * rgrENABLEDIR2
Additional Inherited Members
Protected Types inherited from pnlLimeLightPAD_view
enum {
ID_SDA_PE = 2048, ID_SCL_PE, ID_RX_CLK_PE, ID_SDIO_PE,
ID_SDO_PE, ID_TX_CLK_PE, ID_SEN_PE, ID_DIQ1_PE,
ID_TXNRX1_PE, ID_SCLK_PE, ID_DIQ2_PE, ID_TXNRX2_PE,
ID_IQ_SEL_EN_1_PE, ID_FCLK1_PE, ID_MCLK1_PE, ID_IQ_SEL_EN_2_PE,
ID_FCLK2_PE, ID_MCLK2_PE, ID_SRST_RXFIFO, ID_SRST_TXFIFO,
ID_LRST_TX_A, ID_LRST_TX_B, ID_LRST_RX_A, ID_LRST_RX_B,
ID_MRST_TX_A, ID_MRST_TX_B, ID_MRST_RX_A, ID_MRST_RX_B,
ID_RXEN_A, ID_TXEN_A, ID_RXEN_B, ID_TXEN_B,
ID_MIMO_SISO, ID_MOD_EN, ID_LML_FIDM1, ID_LML_FIDM2,
ID_LML_MODE1, ID_LML_MODE2, ID_LML_TXNRXIQ1, ID_LML_TXNRXIQ2,
ID_SDA_DS, ID_SCL_DS, ID_SDIO_DS, ID_DIQ2_DS,
ID_DIQ1_DS, ID_RX_MUX, ID_TX_MUX, ID_SPIMODE,
ID_VER, ID_REV, ID_MASK, ID_LML1_S3S,
ID_LML1_S2S, ID_LML1_S1S, ID_LML1_S0S, ID_LML2_S3S,
ID_LML2_S2S, ID_LML2_S1S, ID_LML2_S0S, ID_LML1_BQP,
ID_LML1_BIP, ID_LML1_AQP, ID_LML1_AIP, ID_LML2_BQP,
ID_LML2_BIP, ID_LML2_AQP, ID_LML2_AIP, ID_TXRDCLK_MUX,
ID_TXWRCLK_MUX, ID_RXRDCLK_MUX, ID_RXWRCLK_MUX, ID_MCLK2SRC,
ID_MCLK1SRC, ID_TXDIVEN, ID_TXTSPCLKA_DIV, ID_RXDIVEN,
ID_RXTSPCLKA_DIV, ID_MCLK1DLY, ID_MCLK2DLY, ID_FCLK1_INV,
ID_FCLK2_INV, ID_FCLK1DLY, ID_FCLK2DLY, ID_LML1_TX_PST,
ID_LML1_TX_PRE, ID_LML1_RX_PST, ID_LML1_RX_PRE, ID_LML2_TX_PST,
ID_LML2_TX_PRE, ID_LML2_RX_PST, ID_LML2_RX_PRE, ID_DIQDIRCTR1,
ID_DIQDIR1, ID_ENABLEDIRCTR1, ID_ENABLEDIR1, ID_DIQDIRCTR2,
ID_DIQDIR2, ID_ENABLEDIRCTR2, ID_ENABLEDIR2
}
Detailed Description
Implementing pnlLimeLightPAD_view.
Definition at line 18 of file lms7002_pnlLimeLightPAD_view.h.
Constructor & Destructor Documentation
lms7002_pnlLimeLightPAD_view::lms7002_pnlLimeLightPAD_view (wxWindow * parent)
Constructor.
Definition at line 6 of file lms7002_pnlLimeLightPAD_view.cpp.
lms7002_pnlLimeLightPAD_view::lms7002_pnlLimeLightPAD_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 13 of file lms7002_pnlLimeLightPAD_view.cpp.
References pnlLimeLightPAD_view::chkDIQ1_PE, pnlLimeLightPAD_view::chkDIQ2_PE, pnlLimeLightPAD_view::chkFCLK1_INV, pnlLimeLightPAD_view::chkFCLK1_PE, pnlLimeLightPAD_view::chkFCLK2_INV, pnlLimeLightPAD_view::chkFCLK2_PE, pnlLimeLightPAD_view::chkIQ_SEL_EN_1_PE, pnlLimeLightPAD_view::chkIQ_SEL_EN_2_PE, pnlLimeLightPAD_view::chkLML1_SISODDR, pnlLimeLightPAD_view::chkLML1_TRXIQPULSE, pnlLimeLightPAD_view::chkLML2_SISODDR, pnlLimeLightPAD_view::chkLML2_TRXIQPULSE, pnlLimeLightPAD_view::chkLRST_RX_A, pnlLimeLightPAD_view::chkLRST_RX_B, pnlLimeLightPAD_view::chkLRST_TX_A, pnlLimeLightPAD_view::chkLRST_TX_B, pnlLimeLightPAD_view::chkMCLK1_INV, pnlLimeLightPAD_view::chkMCLK1_PE, pnlLimeLightPAD_view::chkMCLK2_INV, pnlLimeLightPAD_view::chkMCLK2_PE, pnlLimeLightPAD_view::chkMIMO_SISO, pnlLimeLightPAD_view::chkMOD_EN, pnlLimeLightPAD_view::chkMRST_RX_A, pnlLimeLightPAD_view::chkMRST_RX_B, pnlLimeLightPAD_view::chkMRST_TX_A, pnlLimeLightPAD_view::chkMRST_TX_B, pnlLimeLightPAD_view::chkRX_CLK_PE, pnlLimeLightPAD_view::chkRXDIVEN, pnlLimeLightPAD_view::chkRXEN_A, pnlLimeLightPAD_view::chkRXEN_B, pnlLimeLightPAD_view::chkSCL_PE, pnlLimeLightPAD_view::chkSCLK_PE, pnlLimeLightPAD_view::chkSDA_PE, pnlLimeLightPAD_view::chkSDIO_PE, pnlLimeLightPAD_view::chkSDO_PE, pnlLimeLightPAD_view::chkSEN_PE, pnlLimeLightPAD_view::chkSRST_RXFIFO, pnlLimeLightPAD_view::chkSRST_TXFIFO, pnlLimeLightPAD_view::chkTX_CLK_PE, pnlLimeLightPAD_view::chkTXDIVEN, pnlLimeLightPAD_view::chkTXEN_A, pnlLimeLightPAD_view::chkTXEN_B, pnlLimeLightPAD_view::chkTXNRX1_PE, pnlLimeLightPAD_view::chkTXNRX2_PE, pnlLimeLightPAD_view::cmbFCLK1_DLY, pnlLimeLightPAD_view::cmbFCLK2_DLY, pnlLimeLightPAD_view::cmbLML1_AIP, pnlLimeLightPAD_view::cmbLML1_AQP, pnlLimeLightPAD_view::cmbLML1_BIP, pnlLimeLightPAD_view::cmbLML1_BQP, pnlLimeLightPAD_view::cmbLML1_RX_PRE, pnlLimeLightPAD_view::cmbLML1_RX_PST, pnlLimeLightPAD_view::cmbLML1_S0S, pnlLimeLightPAD_view::cmbLML1_S1S, pnlLimeLightPAD_view::cmbLML1_S2S, pnlLimeLightPAD_view::cmbLML1_S3S, pnlLimeLightPAD_view::cmbLML1_TX_PRE, pnlLimeLightPAD_view::cmbLML1_TX_PST, pnlLimeLightPAD_view::cmbLML2_AIP, pnlLimeLightPAD_view::cmbLML2_AQP, pnlLimeLightPAD_view::cmbLML2_BIP, pnlLimeLightPAD_view::cmbLML2_BQP, pnlLimeLightPAD_view::cmbLML2_RX_PRE, pnlLimeLightPAD_view::cmbLML2_RX_PST, pnlLimeLightPAD_view::cmbLML2_S0S, pnlLimeLightPAD_view::cmbLML2_S1S, pnlLimeLightPAD_view::cmbLML2_S2S, pnlLimeLightPAD_view::cmbLML2_S3S, pnlLimeLightPAD_view::cmbLML2_TX_PRE, pnlLimeLightPAD_view::cmbLML2_TX_PST, pnlLimeLightPAD_view::cmbMCLK1_DLY, pnlLimeLightPAD_view::cmbMCLK1DLY, pnlLimeLightPAD_view::cmbMCLK1SRC, pnlLimeLightPAD_view::cmbMCLK2_DLY, pnlLimeLightPAD_view::cmbMCLK2DLY, pnlLimeLightPAD_view::cmbMCLK2SRC, pnlLimeLightPAD_view::cmbRXRDCLK_MUX, pnlLimeLightPAD_view::cmbRXTSPCLKA_DIV, pnlLimeLightPAD_view::cmbRXWRCLK_MUX, pnlLimeLightPAD_view::cmbTXRDCLK_MUX, pnlLimeLightPAD_view::cmbTXTSPCLKA_DIV, pnlLimeLightPAD_view::cmbTXWRCLK_MUX, DIQ1_DS, DIQ1_PE, DIQ2_DS, DIQ2_PE, DIQDIR1, DIQDIR2, DIQDIRCTR1, DIQDIRCTR2, ENABLEDIR1, ENABLEDIR2, ENABLEDIRCTR1, ENABLEDIRCTR2, FCLK1_INV, FCLK1_PE, FCLK2_INV, FCLK2_PE, IQ_SEL_EN_1_PE, IQ_SEL_EN_2_PE, LML1_AIP, LML1_AQP, LML1_BB2RF_PRE, LML1_BB2RF_PST, LML1_BIP, LML1_BQP, LML1_FIDM, LML1_MODE, LML1_RF2BB_PRE, LML1_RF2BB_PST, LML1_S0S, LML1_S1S, LML1_S2S, LML1_S3S, LML1_TXNRXIQ, LML2_AIP, LML2_AQP, LML2_BB2RF_PRE, LML2_BB2RF_PST, LML2_BIP, LML2_BQP, LML2_FIDM, LML2_MODE, LML2_RF2BB_PRE, LML2_RF2BB_PST, LML2_S0S, LML2_S1S, LML2_S2S, LML2_S3S, LML2_TXNRXIQ, LMS7param, LRST_RX_A, LRST_RX_B, LRST_TX_A, MCLK1_PE, MCLK1DLY, MCLK1SRC, MCLK2_PE, MCLK2DLY, MCLK2SRC, MIMO_SISO, MOD_EN, MRST_RX_A, MRST_RX_B, MRST_TX_A, MRST_TX_B, pnlLimeLightPAD_view::rgrDIQ1_DS, pnlLimeLightPAD_view::rgrDIQ2_DS, pnlLimeLightPAD_view::rgrDIQDIR1, pnlLimeLightPAD_view::rgrDIQDIR2, pnlLimeLightPAD_view::rgrDIQDIRCTR1, pnlLimeLightPAD_view::rgrDIQDIRCTR2, pnlLimeLightPAD_view::rgrENABLEDIR1, pnlLimeLightPAD_view::rgrENABLEDIR2, pnlLimeLightPAD_view::rgrENABLEDIRCTR1, pnlLimeLightPAD_view::rgrENABLEDIRCTR2, pnlLimeLightPAD_view::rgrLML_FIDM1, pnlLimeLightPAD_view::rgrLML_FIDM2, pnlLimeLightPAD_view::rgrLML_MODE1, pnlLimeLightPAD_view::rgrLML_MODE2, pnlLimeLightPAD_view::rgrLML_TXNRXIQ1, pnlLimeLightPAD_view::rgrLML_TXNRXIQ2, pnlLimeLightPAD_view::rgrRX_MUX, pnlLimeLightPAD_view::rgrSCL_DS, pnlLimeLightPAD_view::rgrSDA_DS, pnlLimeLightPAD_view::rgrSDIO_DS, pnlLimeLightPAD_view::rgrSPIMODE, pnlLimeLightPAD_view::rgrTX_MUX, RX_CLK_PE, RX_MUX, RXDIVEN, RXEN_A, RXEN_B, RXRDCLK_MUX, RXTSPCLKA_DIV, RXWRCLK_MUX, SCL_DS, SCL_PE, SCLK_PE, SDA_DS, SDA_PE, SDIO_DS, SDIO_PE, SDO_PE, SEN_PE, SPIMODE, SRST_RXFIFO, SRST_TXFIFO, TX_CLK_PE, TX_MUX, TXDIVEN, TXEN_A, TXEN_B, TXNRX1_PE, TXNRX2_PE, TXRDCLK_MUX, TXTSPCLKA_DIV, TXWRCLK_MUX, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlLimeLightPAD_view::Initialize (lms_device_t * pControl)
Definition at line 125 of file lms7002_pnlLimeLightPAD_view.cpp.
References pnlLimeLightPAD_view::chkLML1_SISODDR, pnlLimeLightPAD_view::chkLML1_TRXIQPULSE, pnlLimeLightPAD_view::chkLML2_SISODDR, pnlLimeLightPAD_view::chkLML2_TRXIQPULSE, pnlLimeLightPAD_view::chkMCLK1_INV, pnlLimeLightPAD_view::chkMCLK2_INV, pnlLimeLightPAD_view::cmbFCLK1_DLY, pnlLimeLightPAD_view::cmbFCLK2_DLY, pnlLimeLightPAD_view::cmbMCLK1_DLY, pnlLimeLightPAD_view::cmbMCLK2_DLY, LMS7param, LMS_ReadParam(), lmsControl, and MASK.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlLimeLightPAD_view::onbtnReadVerRevMask (wxCommandEvent & event) protected virtual
Reimplemented from pnlLimeLightPAD_view.
Definition at line 170 of file lms7002_pnlLimeLightPAD_view.cpp.
References pnlLimeLightPAD_view::lblMASK, pnlLimeLightPAD_view::lblREV, pnlLimeLightPAD_view::lblVER, LMS7param, LMS_ReadParam(), lmsControl, MASK, REV, and VER.
void lms7002_pnlLimeLightPAD_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlLimeLightPAD_view.
Definition at line 154 of file lms7002_pnlLimeLightPAD_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
Referenced by ParameterChangeHandler().
void lms7002_pnlLimeLightPAD_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlLimeLightPAD_view.
Definition at line 145 of file lms7002_pnlLimeLightPAD_view.cpp.
References ParameterChangeHandler().
void lms7002_pnlLimeLightPAD_view::UpdateGUI ()
Definition at line 184 of file lms7002_pnlLimeLightPAD_view.cpp.
References i, LMS7_MASK, LMS_ReadParam(), lmsControl, pnlLimeLightPAD_view::rgrDIQ1_DS, pnlLimeLightPAD_view::rgrDIQ2_DS, pnlLimeLightPAD_view::rgrSCL_DS, pnlLimeLightPAD_view::rgrSDA_DS, pnlLimeLightPAD_view::rgrSDIO_DS, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlLimeLightPAD_view::lmsControl protected
Definition at line 33 of file lms7002_pnlLimeLightPAD_view.h.
Referenced by Initialize(), onbtnReadVerRevMask(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlLimeLightPAD_view::wndId2Enum protected
Definition at line 34 of file lms7002_pnlLimeLightPAD_view.h.
Referenced by lms7002_pnlLimeLightPAD_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlLimeLightPAD_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlLimeLightPAD_view.cpp