LimeSuite-UML: SoapySDR.Device Class Reference
SoapySDR.Device Class Reference
#include <Device.hpp>
Public Member Functions
def __init__ (self, args, kwargs)
def getDriverKey (self)
def getHardwareKey (self)
def getHardwareInfo (self)
def setFrontendMapping (self, args)
def getFrontendMapping (self, args)
def getNumChannels (self, args)
def getChannelInfo (self, args)
def getFullDuplex (self, args)
def getStreamFormats (self, args)
def getNativeStreamFormat (self, args)
def getStreamArgsInfo (self, args)
def setupStream (self, args)
def closeStream (self, args)
def getStreamMTU (self, args)
def activateStream (self, args)
def deactivateStream (self, args)
def readStream (self, args)
def writeStream (self, args)
def readStreamStatus (self, args)
def getNumDirectAccessBuffers (self, args)
def getDirectAccessBufferAddrs (self, args)
def acquireReadBuffer (self, args)
def releaseReadBuffer (self, args)
def acquireWriteBuffer (self, args)
def releaseWriteBuffer (self, args)
def listAntennas (self, args)
def setAntenna (self, args)
def getAntenna (self, args)
def hasDCOffsetMode (self, args)
def setDCOffsetMode (self, args)
def getDCOffsetMode (self, args)
def hasDCOffset (self, args)
def setDCOffset (self, args)
def getDCOffset (self, args)
def hasIQBalance (self, args)
def setIQBalance (self, args)
def getIQBalance (self, args)
def hasFrequencyCorrection (self, args)
def setFrequencyCorrection (self, args)
def getFrequencyCorrection (self, args)
def listGains (self, args)
def hasGainMode (self, args)
def setGainMode (self, args)
def getGainMode (self, args)
def setGain (self, args)
def getGain (self, args)
def getGainRange (self, args)
def setFrequency (self, args)
def getFrequency (self, args)
def listFrequencies (self, args)
def getFrequencyRange (self, args)
def getFrequencyArgsInfo (self, args)
def setSampleRate (self, args)
def getSampleRate (self, args)
def listSampleRates (self, args)
def getSampleRateRange (self, args)
def setBandwidth (self, args)
def getBandwidth (self, args)
def listBandwidths (self, args)
def getBandwidthRange (self, args)
def setMasterClockRate (self, args)
def getMasterClockRate (self)
def getMasterClockRates (self)
def listClockSources (self)
def setClockSource (self, args)
def getClockSource (self)
def listTimeSources (self)
def setTimeSource (self, args)
def getTimeSource (self)
def hasHardwareTime (self, what="")
def getHardwareTime (self, what="")
def setHardwareTime (self, args)
def setCommandTime (self, args)
def listSensors (self, args)
def getSensorInfo (self, args)
def readSensor (self, args)
def listRegisterInterfaces (self)
def writeRegister (self, args)
def readRegister (self, args)
def writeRegisters (self, args)
def readRegisters (self, args)
def getSettingInfo (self, args)
def writeSetting (self, args)
def readSetting (self, args)
def listGPIOBanks (self)
def writeGPIO (self, args)
def readGPIO (self, args)
def writeGPIODir (self, args)
def readGPIODir (self, args)
def writeI2C (self, args)
def readI2C (self, args)
def transactSPI (self, args)
def listUARTs (self)
def writeUART (self, args)
def readUART (self, args)
def readStream__ (self, args)
def writeStream__ (self, args)
def readStreamStatus__ (self, args)
def __del__ (self)
def __str__ (self)
def readStream (self, stream, buffs, numElems, flags=0, timeoutUs=100000)
def writeStream (self, stream, buffs, numElems, flags=0, timeNs=0, timeoutUs=100000)
def readStreamStatus (self, stream, timeoutUs=100000)
def __new__ (cls, args, kwargs)
virtual ~Device (void)
virtual destructor for inheritance
virtual std::string getDriverKey (void) const
virtual std::string getHardwareKey (void) const
virtual Kwargs getHardwareInfo (void) const
virtual void setFrontendMapping (const int direction, const std::string &mapping)
virtual std::string getFrontendMapping (const int direction) const
virtual size_t getNumChannels (const int direction) const
virtual Kwargs getChannelInfo (const int direction, const size_t channel) const
virtual bool getFullDuplex (const int direction, const size_t channel) const
virtual std::vector< std::string > getStreamFormats (const int direction, const size_t channel) const
virtual std::string getNativeStreamFormat (const int direction, const size_t channel, double &fullScale) const
virtual ArgInfoList getStreamArgsInfo (const int direction, const size_t channel) const
virtual Stream * setupStream (const int direction, const std::string &format, const std::vector< size_t > &channels=std::vector< size_t >(), const Kwargs &args=Kwargs())
virtual void closeStream (Stream *stream)
virtual size_t getStreamMTU (Stream *stream) const
virtual int activateStream (Stream *stream, const int flags=0, const long long timeNs=0, const size_t numElems=0)
virtual int deactivateStream (Stream *stream, const int flags=0, const long long timeNs=0)
virtual int readStream (Stream *stream, void *const *buffs, const size_t numElems, int &flags, long long &timeNs, const long timeoutUs=100000)
virtual int writeStream (Stream *stream, const void *const *buffs, const size_t numElems, int &flags, const long long timeNs=0, const long timeoutUs=100000)
virtual int readStreamStatus (Stream *stream, size_t &chanMask, int &flags, long long &timeNs, const long timeoutUs=100000)
virtual size_t getNumDirectAccessBuffers (Stream *stream)
virtual int getDirectAccessBufferAddrs (Stream *stream, const size_t handle, void **buffs)
virtual int acquireReadBuffer (Stream *stream, size_t &handle, const void **buffs, int &flags, long long &timeNs, const long timeoutUs=100000)
virtual void releaseReadBuffer (Stream *stream, const size_t handle)
virtual int acquireWriteBuffer (Stream *stream, size_t &handle, void **buffs, const long timeoutUs=100000)
virtual void releaseWriteBuffer (Stream *stream, const size_t handle, const size_t numElems, int &flags, const long long timeNs=0)
virtual std::vector< std::string > listAntennas (const int direction, const size_t channel) const
virtual void setAntenna (const int direction, const size_t channel, const std::string &name)
virtual std::string getAntenna (const int direction, const size_t channel) const
virtual bool hasDCOffsetMode (const int direction, const size_t channel) const
virtual void setDCOffsetMode (const int direction, const size_t channel, const bool automatic)
virtual bool getDCOffsetMode (const int direction, const size_t channel) const
virtual bool hasDCOffset (const int direction, const size_t channel) const
virtual void setDCOffset (const int direction, const size_t channel, const std::complex< double > &offset)
virtual std::complex< double > getDCOffset (const int direction, const size_t channel) const
virtual bool hasIQBalance (const int direction, const size_t channel) const
virtual void setIQBalance (const int direction, const size_t channel, const std::complex< double > &balance)
virtual std::complex< double > getIQBalance (const int direction, const size_t channel) const
virtual bool hasFrequencyCorrection (const int direction, const size_t channel) const
virtual void setFrequencyCorrection (const int direction, const size_t channel, const double value)
virtual double getFrequencyCorrection (const int direction, const size_t channel) const
virtual std::vector< std::string > listGains (const int direction, const size_t channel) const
virtual bool hasGainMode (const int direction, const size_t channel) const
virtual void setGainMode (const int direction, const size_t channel, const bool automatic)
virtual bool getGainMode (const int direction, const size_t channel) const
virtual void setGain (const int direction, const size_t channel, const double value)
virtual void setGain (const int direction, const size_t channel, const std::string &name, const double value)
virtual double getGain (const int direction, const size_t channel) const
virtual double getGain (const int direction, const size_t channel, const std::string &name) const
virtual Range getGainRange (const int direction, const size_t channel) const
virtual Range getGainRange (const int direction, const size_t channel, const std::string &name) const
virtual void setFrequency (const int direction, const size_t channel, const double frequency, const Kwargs &args=Kwargs())
virtual void setFrequency (const int direction, const size_t channel, const std::string &name, const double frequency, const Kwargs &args=Kwargs())
virtual double getFrequency (const int direction, const size_t channel) const
virtual double getFrequency (const int direction, const size_t channel, const std::string &name) const
virtual std::vector< std::string > listFrequencies (const int direction, const size_t channel) const
virtual RangeList getFrequencyRange (const int direction, const size_t channel) const
virtual RangeList getFrequencyRange (const int direction, const size_t channel, const std::string &name) const
virtual ArgInfoList getFrequencyArgsInfo (const int direction, const size_t channel) const
virtual void setSampleRate (const int direction, const size_t channel, const double rate)
virtual double getSampleRate (const int direction, const size_t channel) const
virtual std::vector< double > listSampleRates (const int direction, const size_t channel) const
virtual RangeList getSampleRateRange (const int direction, const size_t channel) const
virtual void setBandwidth (const int direction, const size_t channel, const double bw)
virtual double getBandwidth (const int direction, const size_t channel) const
virtual std::vector< double > listBandwidths (const int direction, const size_t channel) const
virtual RangeList getBandwidthRange (const int direction, const size_t channel) const
virtual void setMasterClockRate (const double rate)
virtual double getMasterClockRate (void) const
virtual RangeList getMasterClockRates (void) const
virtual std::vector< std::string > listClockSources (void) const
virtual void setClockSource (const std::string &source)
virtual std::string getClockSource (void) const
virtual std::vector< std::string > listTimeSources (void) const
virtual void setTimeSource (const std::string &source)
virtual std::string getTimeSource (void) const
virtual bool hasHardwareTime (const std::string &what="") const
virtual long long getHardwareTime (const std::string &what="") const
virtual void setHardwareTime (const long long timeNs, const std::string &what="")
virtual void setCommandTime (const long long timeNs, const std::string &what="")
virtual std::vector< std::string > listSensors (void) const
virtual ArgInfo getSensorInfo (const std::string &key) const
virtual std::string readSensor (const std::string &key) const
virtual std::vector< std::string > listSensors (const int direction, const size_t channel) const
virtual ArgInfo getSensorInfo (const int direction, const size_t channel, const std::string &key) const
virtual std::string readSensor (const int direction, const size_t channel, const std::string &key) const
virtual std::vector< std::string > listRegisterInterfaces (void) const
virtual void writeRegister (const std::string &name, const unsigned addr, const unsigned value)
virtual unsigned readRegister (const std::string &name, const unsigned addr) const
virtual void writeRegister (const unsigned addr, const unsigned value)
virtual unsigned readRegister (const unsigned addr) const
virtual void writeRegisters (const std::string &name, const unsigned addr, const std::vector< unsigned > &value)
virtual std::vector< unsigned > readRegisters (const std::string &name, const unsigned addr, const size_t length) const
virtual ArgInfoList getSettingInfo (void) const
virtual void writeSetting (const std::string &key, const std::string &value)
virtual std::string readSetting (const std::string &key) const
virtual ArgInfoList getSettingInfo (const int direction, const size_t channel) const
virtual void writeSetting (const int direction, const size_t channel, const std::string &key, const std::string &value)
virtual std::string readSetting (const int direction, const size_t channel, const std::string &key) const
virtual std::vector< std::string > listGPIOBanks (void) const
virtual void writeGPIO (const std::string &bank, const unsigned value)
virtual void writeGPIO (const std::string &bank, const unsigned value, const unsigned mask)
virtual unsigned readGPIO (const std::string &bank) const
virtual void writeGPIODir (const std::string &bank, const unsigned dir)
virtual void writeGPIODir (const std::string &bank, const unsigned dir, const unsigned mask)
virtual unsigned readGPIODir (const std::string &bank) const
virtual void writeI2C (const int addr, const std::string &data)
virtual std::string readI2C (const int addr, const size_t numBytes)
virtual unsigned transactSPI (const int addr, const unsigned data, const size_t numBits)
virtual std::vector< std::string > listUARTs (void) const
virtual void writeUART (const std::string &which, const std::string &data)
virtual std::string readUART (const std::string &which, const long timeoutUs=100000) const
Static Public Member Functions
static KwargsList enumerate (const Kwargs &args=Kwargs())
static KwargsList enumerate (const std::string &args)
static Device * make (const Kwargs &args=Kwargs())
static Device * make (const std::string &args)
static void unmake (Device *device)
Static Public Attributes
enumerate
make
unmake
Static Private Attributes
dictionary __swig_setmethods__ = {}
__setattr__ = lambdaself,name,value:_swig_setattr(self, Device, name, value)
dictionary __swig_getmethods__ = {}
__getattr__ = lambdaself,name:_swig_getattr(self, Device, name)
__repr__ = _swig_repr
__swig_destroy__ = _SoapySDR.delete_Device
__del__ = lambdaself:None;
Detailed Description
Abstraction for an SDR tranceiver device - configuration and streaming.
Definition at line 749 of file SoapySDR.py.
Constructor & Destructor Documentation
def SoapySDR.Device.__init__ (self, args, kwargs)
Definition at line 754 of file SoapySDR.py.
def SoapySDR.Device.__del__ (self)
Definition at line 863 of file SoapySDR.py.
References SoapySDR.Device.__del__.
SoapySDR.Device::~Device (void) virtual
virtual destructor for inheritance
Definition at line 10 of file Device.cpp.
Member Function Documentation
def SoapySDR.Device.__new__ (cls, args, kwargs)
Definition at line 902 of file SoapySDR.py.
References SoapySDR.Device.make.
def SoapySDR.Device.__str__ (self)
Definition at line 866 of file SoapySDR.py.
References SoapyLMS7.getDriverKey(), SoapySDR.Device.getDriverKey(), SoapyLMS7.getHardwareKey(), and SoapySDR.Device.getHardwareKey().
int SoapySDR.Device::acquireReadBuffer (Stream * stream, size_t & handle, const void ** buffs, int & flags, long long & timeNs, const long timeoutUs = 100000) virtual
Acquire direct buffers from a receive stream. This call is part of the direct buffer access API.
The buffs array will be filled with a stream pointer for each channel. Each pointer can be read up to the number of return value elements.
The handle will be set by the implementation so that the caller may later release access to the buffers with releaseReadBuffer(). Handle represents an index into the internal scatter/gather table such that handle is between 0 and num direct buffers - 1.
Parameters
stream the opaque pointer to a stream handle
handle an index value used in the release() call
buffs an array of void* buffers num chans in size
flags optional flag indicators about the result
timeNs the buffer's timestamp in nanoseconds
timeoutUs the timeout in microseconds
Returns
the number of elements read per buffer or error code
Definition at line 134 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.acquireReadBuffer (self, args)
Definition at line 785 of file SoapySDR.py.
Referenced by SoapySDRDevice_acquireReadBuffer().
int SoapySDR.Device::acquireWriteBuffer (Stream * stream, size_t & handle, void ** buffs, const long timeoutUs = 100000) virtual
Acquire direct buffers from a transmit stream. This call is part of the direct buffer access API.
The buffs array will be filled with a stream pointer for each channel. Each pointer can be written up to the number of return value elements.
The handle will be set by the implementation so that the caller may later release access to the buffers with releaseWriteBuffer(). Handle represents an index into the internal scatter/gather table such that handle is between 0 and num direct buffers - 1.
Parameters
stream the opaque pointer to a stream handle
handle an index value used in the release() call
buffs an array of void* buffers num chans in size
timeoutUs the timeout in microseconds
Returns
the number of available elements per buffer or error
Definition at line 144 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.acquireWriteBuffer (self, args)
Definition at line 787 of file SoapySDR.py.
Referenced by SoapySDRDevice_acquireWriteBuffer().
int SoapySDR.Device::activateStream (Stream * stream, const int flags = 0, const long long timeNs = 0, const size_t numElems = 0) virtual
Activate a stream. Call activate to prepare a stream before using read/write(). The implementation control switches or stimulate data flow.
The timeNs is only valid when the flags have SOAPY_SDR_HAS_TIME. The numElems count can be used to request a finite burst size. The SOAPY_SDR_END_BURST flag can signal end on the finite burst. Not all implementations will support the full range of options. In this case, the implementation returns SOAPY_SDR_NOT_SUPPORTED.
Parameters
stream the opaque pointer to a stream handle
flags optional flag indicators about the stream
timeNs optional activation time in nanoseconds
numElems optional element count for burst control
Returns
0 for success or error code on failure
Definition at line 96 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.activateStream (self, args)
Definition at line 778 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_stretch_impl.receive(), gr::radar::soapysdr_echotimer_impl.receive(), runRateTestStreamLoop(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_activateStream().
void SoapySDR.Device::closeStream (Stream * stream) virtual
Close an open stream created by setupStream The implementation may change switches or power-down components.
Parameters
stream the opaque pointer to a stream handle
Definition at line 85 of file Device.cpp.
def SoapySDR.Device.closeStream (self, args)
Definition at line 776 of file SoapySDR.py.
Referenced by SoapySDRDevice_closeStream(), SoapySDRRateTest(), gr::radar::soapysdr_echotimer_impl.~soapysdr_echotimer_impl(), and gr::radar::soapysdr_echotimer_stretch_impl.~soapysdr_echotimer_stretch_impl().
int SoapySDR.Device::deactivateStream (Stream * stream, const int flags = 0, const long long timeNs = 0) virtual
Deactivate a stream. Call deactivate when not using using read/write(). The implementation control switches or halt data flow.
The timeNs is only valid when the flags have SOAPY_SDR_HAS_TIME. Not all implementations will support the full range of options. In this case, the implementation returns SOAPY_SDR_NOT_SUPPORTED.
Parameters
stream the opaque pointer to a stream handle
flags optional flag indicators about the stream
timeNs optional deactivation time in nanoseconds
Returns
0 for success or error code on failure
Definition at line 101 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.deactivateStream (self, args)
Definition at line 779 of file SoapySDR.py.
Referenced by runRateTestStreamLoop(), SoapySDRDevice_deactivateStream(), gr::radar::soapysdr_echotimer_impl.~soapysdr_echotimer_impl(), and gr::radar::soapysdr_echotimer_stretch_impl.~soapysdr_echotimer_stretch_impl().
static KwargsList SoapySDR.Device.enumerate (const Kwargs & args = Kwargs()) static
Enumerate a list of available devices on the system.
Parameters
args device construction key/value argument filters
Returns
a list of argument maps, each unique to a device
static KwargsList SoapySDR.Device.enumerate (const std::string & args) static
Enumerate a list of available devices on the system. Markup format for args: "keyA=valA, keyB=valB".
Parameters
args a markup string of key/value argument filters
Returns
a list of argument maps, each unique to a device
std::string SoapySDR.Device::getAntenna (const int direction, const size_t channel) const virtual
Get the selected antenna on a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the name of an available antenna
Reimplemented in SoapyLMS7.
Definition at line 167 of file Device.cpp.
def SoapySDR.Device.getAntenna (self, args)
Definition at line 791 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_getAntenna().
def SoapySDR.Device.getBandwidth (self, args)
Definition at line 821 of file SoapySDR.py.
Referenced by SoapySDR.Device.getFrequencyRange(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_getBandwidth().
double SoapySDR.Device::getBandwidth (const int direction, const size_t channel) const virtual
Get the baseband filter width of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the baseband filter width in Hz
Reimplemented in SoapyLMS7.
Definition at line 530 of file Device.cpp.
def SoapySDR.Device.getBandwidthRange (self, args)
Definition at line 823 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_getBandwidthRange().
SoapySDR::RangeList SoapySDR.Device::getBandwidthRange (const int direction, const size_t channel) const virtual
Get the range of possible baseband filter widths.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of bandwidth ranges in Hz
Reimplemented in SoapyLMS7.
Definition at line 540 of file Device.cpp.
References bw, and SoapySDR.Device::listBandwidths().
SoapySDR::Kwargs SoapySDR.Device::getChannelInfo (const int direction, const size_t channel) const virtual
Query a dictionary of available channel information. This dictionary can any number of values like decoder type, version, available functions... This information can be displayed to the user to help identify the instantiated channel.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
channel information
Definition at line 51 of file Device.cpp.
def SoapySDR.Device.getChannelInfo (self, args)
Definition at line 770 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_getChannelInfo().
def SoapySDR.Device.getClockSource (self)
Definition at line 829 of file SoapySDR.py.
References SoapySDR.Device.getClockSource().
Referenced by SoapySDRDevice_getClockSource().
std::string SoapySDR.Device::getClockSource (void) const virtual
Get the clock source of the device
Returns
the name of a clock source
Definition at line 579 of file Device.cpp.
Referenced by SoapySDR.Device::getClockSource().
std::complex< double > SoapySDR.Device::getDCOffset (const int direction, const size_t channel) const virtual
Get the frontend DC offset correction.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the relative correction (1.0 max)
Definition at line 201 of file Device.cpp.
def SoapySDR.Device.getDCOffset (self, args)
Definition at line 797 of file SoapySDR.py.
Referenced by SoapySDRDevice_getDCOffset().
bool SoapySDR.Device::getDCOffsetMode (const int direction, const size_t channel) const virtual
Get the automatic DC offset corrections mode.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true for automatic offset correction
Reimplemented in SoapyLMS7.
Definition at line 186 of file Device.cpp.
def SoapySDR.Device.getDCOffsetMode (self, args)
Definition at line 794 of file SoapySDR.py.
Referenced by SoapySDRDevice_getDCOffsetMode().
int SoapySDR.Device::getDirectAccessBufferAddrs (Stream * stream, const size_t handle, void ** buffs) virtual
Get the buffer addresses for a scatter/gather table entry. When the underlying DMA implementation uses scatter/gather then this call provides the user addresses for that table.
Example: The caller may query the DMA memory addresses once after stream creation to pre-allocate a re-usable ring-buffer.
Parameters
stream the opaque pointer to a stream handle
handle an index value between 0 and num direct buffers - 1
buffs an array of void* buffers num chans in size
Returns
0 for success or error code when not supported
Definition at line 129 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.getDirectAccessBufferAddrs (self, args)
Definition at line 784 of file SoapySDR.py.
Referenced by SoapySDRDevice_getDirectAccessBufferAddrs().
std::string SoapySDR.Device::getDriverKey (void) const virtual
A key that uniquely identifies the device driver. This key identifies the underlying implementation. Serveral variants of a product may share a driver.
Reimplemented in SoapyLMS7, and NullDevice.
Definition at line 18 of file Device.cpp.
Referenced by SoapySDR.Device::getDriverKey().
def SoapySDR.Device.getDriverKey (self)
Definition at line 764 of file SoapySDR.py.
References SoapySDR.Device.getDriverKey().
Referenced by SoapySDR.Device.__str__(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_getDriverKey(), and SoapySDRDeviceProbe().
double SoapySDR.Device::getFrequency (const int direction, const size_t channel) const virtual
Get the overall center frequency of the chain.
For RX, this specifies the down-conversion frequency.
For TX, this specifies the up-conversion frequency.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the center frequency in Hz
Reimplemented in SoapyLMS7.
Definition at line 385 of file Device.cpp.
References freq, SoapySDR.Device::getFrequency(), SoapySDR.Device::listFrequencies(), and string().
double SoapySDR.Device::getFrequency (const int direction, const size_t channel, const std::string & name) const virtual
Get the frequency of a tunable element in the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of a tunable element
Returns
the tunable element's frequency in Hz
Reimplemented in SoapyLMS7.
Definition at line 399 of file Device.cpp.
def SoapySDR.Device.getFrequency (self, args)
Definition at line 812 of file SoapySDR.py.
Referenced by SoapySDR.Device.getFrequency(), SoapySDR.Device.getFrequencyCorrection(), SoapySDR.Device.setFrequency(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_getFrequency(), and SoapySDRDevice_getFrequencyComponent().
SoapySDR::ArgInfoList SoapySDR.Device::getFrequencyArgsInfo (const int direction, const size_t channel) const virtual
Query the argument info description for tune args.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of argument info structures
Reimplemented in SoapyLMS7.
Definition at line 450 of file Device.cpp.
References args, SoapySDR.ArgInfo::description, SoapySDR.ArgInfo::FLOAT, SoapySDR.Device::getFrequencyRange(), info, SoapySDR.ArgInfo::key, SoapySDR.Device::listFrequencies(), SoapySDR.ArgInfo::name, SoapySDR.ArgInfo::optionNames, SoapySDR.ArgInfo::options, SoapySDR.ArgInfo::range, SoapySDR.ArgInfo::type, SoapySDR.ArgInfo::units, and SoapySDR.ArgInfo::value.
def SoapySDR.Device.getFrequencyArgsInfo (self, args)
Definition at line 815 of file SoapySDR.py.
Referenced by SoapyLMS7.getFrequencyArgsInfo(), probeChannel(), and SoapySDRDevice_getFrequencyArgsInfo().
double SoapySDR.Device::getFrequencyCorrection (const int direction, const size_t channel) const virtual
Get the frontend frequency correction value.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the correction value in PPM
Definition at line 238 of file Device.cpp.
References SoapySDR.Device::getFrequency(), and SoapySDR.Device::listFrequencies().
def SoapySDR.Device.getFrequencyCorrection (self, args)
Definition at line 803 of file SoapySDR.py.
Referenced by SoapySDRDevice_getFrequencyCorrection().
SoapySDR::RangeList SoapySDR.Device::getFrequencyRange (const int direction, const size_t channel) const virtual
Get the range of overall frequency values.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of frequency ranges in Hz
Reimplemented in SoapyLMS7.
Definition at line 409 of file Device.cpp.
References bw, SoapySDR.Device::getBandwidth(), SoapySDR.Device::getFrequencyRange(), SoapySDR.Device::listFrequencies(), SoapySDR.Range::maximum(), SoapySDR.Range::minimum(), and range.
SoapySDR::RangeList SoapySDR.Device::getFrequencyRange (const int direction, const size_t channel, const std::string & name) const virtual
Get the range of tunable values for the specified element.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of a tunable element
Returns
a list of frequency ranges in Hz
Reimplemented in SoapyLMS7.
Definition at line 445 of file Device.cpp.
def SoapySDR.Device.getFrequencyRange (self, args)
Definition at line 814 of file SoapySDR.py.
Referenced by SoapySDR.Device.getFrequencyArgsInfo(), SoapySDR.Device.getFrequencyRange(), probeChannel(), SoapySDRDevice_getFrequencyRange(), and SoapySDRDevice_getFrequencyRangeComponent().
std::string SoapySDR.Device::getFrontendMapping (const int direction) const virtual
Get the mapping configuration string.
Parameters
direction the channel direction RX or TX
Returns
the vendor-specific mapping string
Definition at line 41 of file Device.cpp.
def SoapySDR.Device.getFrontendMapping (self, args)
Definition at line 768 of file SoapySDR.py.
Referenced by SoapySDRDevice_getFrontendMapping().
bool SoapySDR.Device::getFullDuplex (const int direction, const size_t channel) const virtual
Find out if the specified channel is full or half duplex.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true for full duplex, false for half duplex
Reimplemented in SoapyLMS7.
Definition at line 56 of file Device.cpp.
def SoapySDR.Device.getFullDuplex (self, args)
Definition at line 771 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_getFullDuplex().
double SoapySDR.Device::getGain (const int direction, const size_t channel) const virtual
Get the overall value of the gain elements in a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the value of the gain in dB
Reimplemented in SoapyLMS7.
Definition at line 303 of file Device.cpp.
References gain, SoapySDR.Device::getGain(), SoapySDR.Device::getGainRange(), SoapySDR.Device::listGains(), and calc_fmcw_peaks::r.
double SoapySDR.Device::getGain (const int direction, const size_t channel, const std::string & name) const virtual
Get the value of an individual amplification element in a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an amplification element
Returns
the value of the gain in dB
Reimplemented in SoapyLMS7.
Definition at line 315 of file Device.cpp.
def SoapySDR.Device.getGain (self, args)
Definition at line 809 of file SoapySDR.py.
Referenced by SoapySDR.Device.getGain(), gr::radar::soapysdr_echotimer_stretch_impl.set_rx_gain(), gr::radar::soapysdr_echotimer_impl.set_rx_gain(), gr::radar::soapysdr_echotimer_stretch_impl.set_tx_gain(), gr::radar::soapysdr_echotimer_impl.set_tx_gain(), SoapySDR.Device.setGain(), SoapySDRDevice_getGain(), and SoapySDRDevice_getGainElement().
bool SoapySDR.Device::getGainMode (const int direction, const size_t channel) const virtual
Get the automatic gain mode on the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true for automatic gain setting
Definition at line 267 of file Device.cpp.
def SoapySDR.Device.getGainMode (self, args)
Definition at line 807 of file SoapySDR.py.
Referenced by SoapySDRDevice_getGainMode().
SoapySDR::Range SoapySDR.Device::getGainRange (const int direction, const size_t channel) const virtual
Get the overall range of possible gain values.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of gain ranges in dB
Reimplemented in SoapyLMS7.
Definition at line 325 of file Device.cpp.
References gain, SoapySDR.Device::getGainRange(), SoapySDR.Device::listGains(), and calc_fmcw_peaks::r.
SoapySDR::Range SoapySDR.Device::getGainRange (const int direction, const size_t channel, const std::string & name) const virtual
Get the range of possible gain values for a specific element.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an amplification element
Returns
a list of gain ranges in dB
Reimplemented in SoapyLMS7.
Definition at line 320 of file Device.cpp.
def SoapySDR.Device.getGainRange (self, args)
Definition at line 810 of file SoapySDR.py.
Referenced by SoapySDR.Device.getGain(), SoapySDR.Device.getGainRange(), probeChannel(), SoapySDR.Device.setGain(), SoapySDRDevice_getGainElementRange(), and SoapySDRDevice_getGainRange().
SoapySDR::Kwargs SoapySDR.Device::getHardwareInfo (void) const virtual
Query a dictionary of available device information. This dictionary can any number of values like vendor name, product name, revisions, serials... This information can be displayed to the user to help identify the instantiated device.
Reimplemented in SoapyLMS7.
Definition at line 28 of file Device.cpp.
Referenced by SoapySDR.Device::getHardwareInfo().
def SoapySDR.Device.getHardwareInfo (self)
Definition at line 766 of file SoapySDR.py.
References SoapySDR.Device.getHardwareInfo().
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_getHardwareInfo(), and SoapySDRDeviceProbe().
std::string SoapySDR.Device::getHardwareKey (void) const virtual
A key that uniquely identifies the hardware. This key should be meaningful to the user to optimize for the underlying hardware.
Reimplemented in SoapyLMS7, and NullDevice.
Definition at line 23 of file Device.cpp.
Referenced by SoapySDR.Device::getHardwareKey().
def SoapySDR.Device.getHardwareKey (self)
Definition at line 765 of file SoapySDR.py.
References SoapySDR.Device.getHardwareKey().
Referenced by SoapySDR.Device.__str__(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_getHardwareKey(), and SoapySDRDeviceProbe().
def SoapySDR.Device.getHardwareTime (self, what = "")
Definition at line 834 of file SoapySDR.py.
Referenced by SoapySDRDevice_getHardwareTime(), gr::radar::soapysdr_echotimer_stretch_impl.work(), and gr::radar::soapysdr_echotimer_impl.work().
long long SoapySDR.Device::getHardwareTime (const std::string & what = "") const virtual
Read the time from the hardware clock on the device. The what argument can refer to a specific time counter.
Parameters
what optional argument
Returns
the time in nanoseconds
Reimplemented in SoapyLMS7.
Definition at line 608 of file Device.cpp.
std::complex< double > SoapySDR.Device::getIQBalance (const int direction, const size_t channel) const virtual
Get the frontend IQ balance correction.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the relative correction (1.0 max)
Definition at line 216 of file Device.cpp.
def SoapySDR.Device.getIQBalance (self, args)
Definition at line 800 of file SoapySDR.py.
Referenced by SoapySDRDevice_getIQBalance().
def SoapySDR.Device.getMasterClockRate (self)
Definition at line 825 of file SoapySDR.py.
References SoapySDR.Device.getMasterClockRate().
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_getMasterClockRate().
double SoapySDR.Device::getMasterClockRate (void) const virtual
Get the master clock rate of the device.
Returns
the clock rate in Hz
Reimplemented in SoapyLMS7.
Definition at line 559 of file Device.cpp.
Referenced by SoapySDR.Device::getMasterClockRate().
def SoapySDR.Device.getMasterClockRates (self)
Definition at line 826 of file SoapySDR.py.
References SoapySDR.Device.getMasterClockRates().
Referenced by SoapySDRDevice_getMasterClockRates().
SoapySDR::RangeList SoapySDR.Device::getMasterClockRates (void) const virtual
Get the range of available master clock rates.
Returns
a list of clock rate ranges in Hz
Reimplemented in SoapyLMS7.
Definition at line 564 of file Device.cpp.
Referenced by SoapySDR.Device::getMasterClockRates().
std::string SoapySDR.Device::getNativeStreamFormat (const int direction, const size_t channel, double & fullScale) const virtual
Get the hardware's native stream format for this channel. This is the format used by the underlying transport layer, and the direct buffer access API calls (when available).
Parameters
direction the channel direction RX or TX
channel an available channel on the device
[out] fullScale the maximum possible value
Returns
the native stream buffer format string
Reimplemented in SoapyLMS7.
Definition at line 69 of file Device.cpp.
References SoapySDR::SOAPY_SDR_CS16.
def SoapySDR.Device.getNativeStreamFormat (self, args)
Definition at line 773 of file SoapySDR.py.
Referenced by probeChannel(), SoapySDRDevice_getNativeStreamFormat(), and SoapySDRRateTest().
size_t SoapySDR.Device::getNumChannels (const int direction) const virtual
Get a number of channels given the streaming direction
Reimplemented in SoapyLMS7.
Definition at line 46 of file Device.cpp.
def SoapySDR.Device.getNumChannels (self, args)
Definition at line 769 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_getNumChannels(), and SoapySDRDeviceProbe().
size_t SoapySDR.Device::getNumDirectAccessBuffers (Stream * stream) virtual
How many direct access buffers can the stream provide? This is the number of times the user can call acquire() on a stream without making subsequent calls to release(). A return value of 0 means that direct access is not supported.
Parameters
stream the opaque pointer to a stream handle
Returns
the number of direct access buffers or 0
Definition at line 124 of file Device.cpp.
def SoapySDR.Device.getNumDirectAccessBuffers (self, args)
Definition at line 783 of file SoapySDR.py.
Referenced by SoapySDRDevice_getNumDirectAccessBuffers().
def SoapySDR.Device.getSampleRate (self, args)
Definition at line 817 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_getSampleRate().
double SoapySDR.Device::getSampleRate (const int direction, const size_t channel) const virtual
Get the baseband sample rate of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
the sample rate in samples per second
Reimplemented in SoapyLMS7.
Definition at line 501 of file Device.cpp.
def SoapySDR.Device.getSampleRateRange (self, args)
Definition at line 819 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_getSampleRateRange().
SoapySDR::RangeList SoapySDR.Device::getSampleRateRange (const int direction, const size_t channel) const virtual
Get the range of possible baseband sample rates.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of sample rate ranges in samples per second
Reimplemented in SoapyLMS7.
Definition at line 511 of file Device.cpp.
References bw, and SoapySDR.Device::listSampleRates().
def SoapySDR.Device.getSensorInfo (self, args)
Definition at line 838 of file SoapySDR.py.
Referenced by SoapySDRDevice_getChannelSensorInfo(), and SoapySDRDevice_getSensorInfo().
SoapySDR::ArgInfo SoapySDR.Device::getSensorInfo (const std::string & key) const virtual
Get meta-information about a sensor. Example: displayable name, type, range.
Parameters
key the ID name of an available sensor
Returns
meta-information about a sensor
Reimplemented in SoapyLMS7.
Definition at line 631 of file Device.cpp.
SoapySDR::ArgInfo SoapySDR.Device::getSensorInfo (const int direction, const size_t channel, const std::string & key) const virtual
Get meta-information about a channel sensor. Example: displayable name, type, range.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the ID name of an available sensor
Returns
meta-information about a sensor
Reimplemented in SoapyLMS7.
Definition at line 646 of file Device.cpp.
def SoapySDR.Device.getSettingInfo (self, args)
Definition at line 845 of file SoapySDR.py.
References SoapySDR.Device.getSettingInfo().
Referenced by probeChannel(), SoapySDRDevice_getChannelSettingInfo(), SoapySDRDevice_getSettingInfo(), and SoapySDRDeviceProbe().
SoapySDR::ArgInfoList SoapySDR.Device::getSettingInfo (void) const virtual
Describe the allowed keys and values used for settings.
Returns
a list of argument info structures
Reimplemented in SoapyLMS7.
Definition at line 697 of file Device.cpp.
Referenced by SoapySDR.Device::getSettingInfo().
SoapySDR::ArgInfoList SoapySDR.Device::getSettingInfo (const int direction, const size_t channel) const virtual
Describe the allowed keys and values used for channel settings.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of argument info structures
Reimplemented in SoapyLMS7.
Definition at line 712 of file Device.cpp.
SoapySDR::ArgInfoList SoapySDR.Device::getStreamArgsInfo (const int direction, const size_t channel) const virtual
Query the argument info description for stream args.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of argument info structures
Reimplemented in SoapyLMS7.
Definition at line 75 of file Device.cpp.
def SoapySDR.Device.getStreamArgsInfo (self, args)
Definition at line 774 of file SoapySDR.py.
Referenced by probeChannel(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_getStreamArgsInfo().
std::vector< std::string > SoapySDR.Device::getStreamFormats (const int direction, const size_t channel) const virtual
Query a list of the available stream formats.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of allowed format strings. See setupStream() for the format syntax.
Reimplemented in SoapyLMS7.
Definition at line 64 of file Device.cpp.
def SoapySDR.Device.getStreamFormats (self, args)
Definition at line 772 of file SoapySDR.py.
Referenced by probeChannel(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_getStreamFormats().
size_t SoapySDR.Device::getStreamMTU (Stream * stream) const virtual
Get the stream's maximum transmission unit (MTU) in number of elements. The MTU specifies the maximum payload transfer in a stream operation. This value can be used as a stream buffer allocation size that can best optimize throughput given the underlying stream implementation.
Parameters
stream the opaque pointer to a stream handle
Returns
the MTU in number of stream elements (never zero)
Definition at line 90 of file Device.cpp.
def SoapySDR.Device.getStreamMTU (self, args)
Definition at line 777 of file SoapySDR.py.
Referenced by runRateTestStreamLoop(), and SoapySDRDevice_getStreamMTU().
def SoapySDR.Device.getTimeSource (self)
Definition at line 832 of file SoapySDR.py.
References SoapySDR.Device.getTimeSource().
Referenced by SoapySDRDevice_getTimeSource().
std::string SoapySDR.Device::getTimeSource (void) const virtual
Get the time source of the device
Returns
the name of a time source
Definition at line 598 of file Device.cpp.
Referenced by SoapySDR.Device::getTimeSource().
bool SoapySDR.Device::hasDCOffset (const int direction, const size_t channel) const virtual
Does the device support frontend DC offset correction?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true if DC offset corrections are supported
Reimplemented in SoapyLMS7.
Definition at line 191 of file Device.cpp.
def SoapySDR.Device.hasDCOffset (self, args)
Definition at line 795 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_hasDCOffset().
bool SoapySDR.Device::hasDCOffsetMode (const int direction, const size_t channel) const virtual
Does the device support automatic DC offset corrections?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true if automatic corrections are supported
Reimplemented in SoapyLMS7.
Definition at line 176 of file Device.cpp.
def SoapySDR.Device.hasDCOffsetMode (self, args)
Definition at line 792 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_hasDCOffsetMode().
bool SoapySDR.Device::hasFrequencyCorrection (const int direction, const size_t channel) const virtual
Does the device support frontend frequency correction?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true if frequency corrections are supported
Definition at line 221 of file Device.cpp.
References SoapySDR.Device::listFrequencies().
def SoapySDR.Device.hasFrequencyCorrection (self, args)
Definition at line 801 of file SoapySDR.py.
Referenced by SoapySDRDevice_hasFrequencyCorrection().
bool SoapySDR.Device::hasGainMode (const int direction, const size_t channel) const virtual
Does the device support automatic gain control?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true for automatic gain control
Definition at line 257 of file Device.cpp.
def SoapySDR.Device.hasGainMode (self, args)
Definition at line 805 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_hasGainMode().
def SoapySDR.Device.hasHardwareTime (self, what = "")
Definition at line 833 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_hasHardwareTime(), and SoapySDRDeviceProbe().
bool SoapySDR.Device::hasHardwareTime (const std::string & what = "") const virtual
Does this device have a hardware clock?
Parameters
what optional argument
Returns
true if the hardware clock exists
Reimplemented in SoapyLMS7.
Definition at line 603 of file Device.cpp.
bool SoapySDR.Device::hasIQBalance (const int direction, const size_t channel) const virtual
Does the device support frontend IQ balance correction?
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
true if IQ balance corrections are supported
Reimplemented in SoapyLMS7.
Definition at line 206 of file Device.cpp.
def SoapySDR.Device.hasIQBalance (self, args)
Definition at line 798 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_hasIQBalance().
std::vector< std::string > SoapySDR.Device::listAntennas (const int direction, const size_t channel) const virtual
Get a list of available antennas to select on a given chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of available antenna names
Reimplemented in SoapyLMS7.
Definition at line 157 of file Device.cpp.
def SoapySDR.Device.listAntennas (self, args)
Definition at line 789 of file SoapySDR.py.
Referenced by probeChannel(), and SoapySDRDevice_listAntennas().
def SoapySDR.Device.listBandwidths (self, args)
Definition at line 822 of file SoapySDR.py.
Referenced by SoapySDR.Device.getBandwidthRange(), and SoapySDRDevice_listBandwidths().
std::vector< double > SoapySDR.Device::listBandwidths (const int direction, const size_t channel) const virtual
Get the range of possible baseband filter widths.
Deprecated:
replaced by getBandwidthRange()
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of possible bandwidths in Hz
Definition at line 535 of file Device.cpp.
def SoapySDR.Device.listClockSources (self)
Definition at line 827 of file SoapySDR.py.
References SoapySDR.Device.listClockSources().
Referenced by SoapySDRDevice_listClockSources(), and SoapySDRDeviceProbe().
std::vector< std::string > SoapySDR.Device::listClockSources (void) const virtual
Get the list of available clock sources.
Returns
a list of clock source names
Definition at line 569 of file Device.cpp.
Referenced by SoapySDR.Device::listClockSources().
std::vector< std::string > SoapySDR.Device::listFrequencies (const int direction, const size_t channel) const virtual
List available tunable elements in the chain. Elements should be in order RF to baseband.
Parameters
direction the channel direction RX or TX
channel an available channel
Returns
a list of tunable elements by name
Reimplemented in SoapyLMS7.
Definition at line 404 of file Device.cpp.
def SoapySDR.Device.listFrequencies (self, args)
Definition at line 813 of file SoapySDR.py.
Referenced by SoapySDR.Device.getFrequency(), SoapySDR.Device.getFrequencyArgsInfo(), SoapySDR.Device.getFrequencyCorrection(), SoapySDR.Device.getFrequencyRange(), SoapySDR.Device.hasFrequencyCorrection(), probeChannel(), SoapySDR.Device.setFrequency(), SoapySDR.Device.setFrequencyCorrection(), and SoapySDRDevice_listFrequencies().
std::vector< std::string > SoapySDR.Device::listGains (const int direction, const size_t channel) const virtual
List available amplification elements. Elements should be in order RF to baseband.
Parameters
direction the channel direction RX or TX
channel an available channel
Returns
a list of gain string names
Reimplemented in SoapyLMS7.
Definition at line 252 of file Device.cpp.
def SoapySDR.Device.listGains (self, args)
Definition at line 804 of file SoapySDR.py.
Referenced by SoapySDR.Device.getGain(), SoapySDR.Device.getGainRange(), probeChannel(), SoapySDR.Device.setGain(), and SoapySDRDevice_listGains().
def SoapySDR.Device.listGPIOBanks (self)
Definition at line 848 of file SoapySDR.py.
References SoapySDR.Device.listGPIOBanks().
Referenced by gr::radar::gpio_source_s_impl.gpio_source_s_impl(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_listGPIOBanks(), and SoapySDRDeviceProbe().
std::vector< std::string > SoapySDR.Device::listGPIOBanks (void) const virtual
Get a list of available GPIO banks by name.
Reimplemented in SoapyLMS7.
Definition at line 730 of file Device.cpp.
Referenced by SoapySDR.Device::listGPIOBanks().
def SoapySDR.Device.listRegisterInterfaces (self)
Definition at line 840 of file SoapySDR.py.
References SoapySDR.Device.listRegisterInterfaces().
Referenced by gr::radar::gpio_source_s_impl.gpio_source_s_impl(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_listRegisterInterfaces(), and SoapySDRDeviceProbe().
std::vector< std::string > SoapySDR.Device::listRegisterInterfaces (void) const virtual
Get a list of available register interfaces by name.
Returns
a list of available register interfaces
Reimplemented in SoapyLMS7.
Definition at line 659 of file Device.cpp.
Referenced by SoapySDR.Device::listRegisterInterfaces().
def SoapySDR.Device.listSampleRates (self, args)
Definition at line 818 of file SoapySDR.py.
Referenced by SoapySDR.Device.getSampleRateRange(), and SoapySDRDevice_listSampleRates().
std::vector< double > SoapySDR.Device::listSampleRates (const int direction, const size_t channel) const virtual
Get the range of possible baseband sample rates.
Deprecated:
replaced by getSampleRateRange()
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of possible rates in samples per second
Reimplemented in SoapyLMS7.
Definition at line 506 of file Device.cpp.
def SoapySDR.Device.listSensors (self, args)
Definition at line 837 of file SoapySDR.py.
References SoapySDR.Device.listSensors().
Referenced by probeChannel(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_listChannelSensors(), SoapySDRDevice_listSensors(), and SoapySDRDeviceProbe().
std::vector< std::string > SoapySDR.Device::listSensors (void) const virtual
List the available global readback sensors. A sensor can represent a reference lock, RSSI, temperature.
Returns
a list of available sensor string names
Reimplemented in SoapyLMS7.
Definition at line 626 of file Device.cpp.
Referenced by SoapySDR.Device::listSensors().
std::vector< std::string > SoapySDR.Device::listSensors (const int direction, const size_t channel) const virtual
List the available channel readback sensors. A sensor can represent a reference lock, RSSI, temperature.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
Returns
a list of available sensor string names
Reimplemented in SoapyLMS7.
Definition at line 641 of file Device.cpp.
def SoapySDR.Device.listTimeSources (self)
Definition at line 830 of file SoapySDR.py.
References SoapySDR.Device.listTimeSources().
Referenced by SoapySDRDevice_listTimeSources(), and SoapySDRDeviceProbe().
std::vector< std::string > SoapySDR.Device::listTimeSources (void) const virtual
Get the list of available time sources.
Returns
a list of time source names
Definition at line 588 of file Device.cpp.
Referenced by SoapySDR.Device::listTimeSources().
def SoapySDR.Device.listUARTs (self)
Definition at line 856 of file SoapySDR.py.
References SoapySDR.Device.listUARTs().
Referenced by SoapySDRDevice_listUARTs(), and SoapySDRDeviceProbe().
std::vector< std::string > SoapySDR.Device::listUARTs (void) const virtual
Enumerate the available UART devices.
Returns
a list of names of available UARTs
Definition at line 796 of file Device.cpp.
Referenced by SoapySDR.Device::listUARTs().
static Device* SoapySDR.Device.make (const Kwargs & args = Kwargs()) static
Make a new Device object given device construction args. The device pointer will be stored in a table so subsequent calls with the same arguments will produce the same device. For every call to make, there should be a matched call to unmake.
Parameters
args device construction key/value argument map
Returns
a pointer to a new Device object
static Device* SoapySDR.Device.make (const std::string & args) static
Make a new Device object given device construction args. The device pointer will be stored in a table so subsequent calls with the same arguments will produce the same device. For every call to make, there should be a matched call to unmake.
Parameters
args a markup string of key/value arguments
Returns
a pointer to a new Device object
def SoapySDR.Device.readGPIO (self, args)
Definition at line 850 of file SoapySDR.py.
Referenced by gr::radar::gpio_source_s_impl.readGPIO(), SoapySDRDevice_readGPIO(), gr::radar::soapysdr_echotimer_stretch_impl.work(), gr::radar::soapysdr_echotimer_impl.work(), and SoapySDR.Device.writeGPIO().
unsigned SoapySDR.Device::readGPIO (const std::string & bank) const virtual
Readback the value of a GPIO bank.
Parameters
bank the name of an available bank
Returns
an integer representing GPIO bits
Reimplemented in SoapyLMS7.
Definition at line 748 of file Device.cpp.
def SoapySDR.Device.readGPIODir (self, args)
Definition at line 852 of file SoapySDR.py.
Referenced by SoapySDRDevice_readGPIODir(), and SoapySDR.Device.writeGPIODir().
unsigned SoapySDR.Device::readGPIODir (const std::string & bank) const virtual
Read the data direction of a GPIO bank. 1 bits represent outputs, 0 bits represent inputs.
Parameters
bank the name of an available bank
Returns
an integer representing data direction bits
Reimplemented in SoapyLMS7.
Definition at line 766 of file Device.cpp.
def SoapySDR.Device.readI2C (self, args)
Definition at line 854 of file SoapySDR.py.
Referenced by SoapySDRDevice_readI2C().
std::string SoapySDR.Device::readI2C (const int addr, const size_t numBytes) virtual
Read from an available I2C slave. If the device contains multiple I2C masters, the address bits can encode which master.
Parameters
addr the address of the slave
numBytes the number of bytes to read
Returns
an array of bytes read from the slave
Definition at line 780 of file Device.cpp.
def SoapySDR.Device.readRegister (self, args)
Definition at line 842 of file SoapySDR.py.
Referenced by gr::radar::gpio_source_s_impl.gpio_source_s_impl(), SoapySDR.Device.readRegister(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_readRegister().
unsigned SoapySDR.Device::readRegister (const std::string & name, const unsigned addr) const virtual
Read a register on the device given the interface name.
Parameters
name the name of a available register interface
addr the register address
Returns
the register value
Reimplemented in SoapyLMS7.
Definition at line 669 of file Device.cpp.
References SoapySDR.Device::readRegister().
unsigned SoapySDR.Device::readRegister (const unsigned addr) const virtual
Read a register on the device.
Deprecated:
replaced by readRegister(name)
Parameters
addr the register address
Returns
the register value
Reimplemented in SoapyLMS7.
Definition at line 679 of file Device.cpp.
def SoapySDR.Device.readRegisters (self, args)
Definition at line 844 of file SoapySDR.py.
Referenced by SoapySDRDevice_readRegisters().
std::vector< unsigned > SoapySDR.Device::readRegisters (const std::string & name, const unsigned addr, const size_t length) const virtual
Read a memory block on the device given the interface name.
Parameters
name the name of a available memory block interface
addr the memory block start address
length number of words to be read from memory block
Returns
the memory block content
Definition at line 689 of file Device.cpp.
def SoapySDR.Device.readSensor (self, args)
Definition at line 839 of file SoapySDR.py.
Referenced by SoapySDRDevice_readChannelSensor(), SoapySDRDevice_readSensor(), gr::radar::soapysdr_echotimer_stretch_impl.work(), and gr::radar::soapysdr_echotimer_impl.work().
std::string SoapySDR.Device::readSensor (const std::string & key) const virtual
Readback a global sensor given the name. The value returned is a string which can represent a boolean ("true"/"false"), an integer, or float.
Parameters
key the ID name of an available sensor
Returns
the current value of the sensor
Reimplemented in SoapyLMS7.
Definition at line 636 of file Device.cpp.
std::string SoapySDR.Device::readSensor (const int direction, const size_t channel, const std::string & key) const virtual
Readback a channel sensor given the name. The value returned is a string which can represent a boolean ("true"/"false"), an integer, or float.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the ID name of an available sensor
Returns
the current value of the sensor
Reimplemented in SoapyLMS7.
Definition at line 651 of file Device.cpp.
def SoapySDR.Device.readSetting (self, args)
Definition at line 847 of file SoapySDR.py.
Referenced by SoapySDRDevice_readChannelSetting(), and SoapySDRDevice_readSetting().
std::string SoapySDR.Device::readSetting (const std::string & key) const virtual
Read an arbitrary setting on the device.
Parameters
key the setting identifier
Returns
the setting value
Reimplemented in SoapyLMS7.
Definition at line 707 of file Device.cpp.
std::string SoapySDR.Device::readSetting (const int direction, const size_t channel, const std::string & key) const virtual
Read an arbitrary channel setting on the device.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the setting identifier
Returns
the setting value
Reimplemented in SoapyLMS7.
Definition at line 722 of file Device.cpp.
int SoapySDR.Device::readStream (Stream * stream, void *const * buffs, const size_t numElems, int & flags, long long & timeNs, const long timeoutUs = 100000) virtual
Read elements from a stream for reception. This is a multi-channel call, and buffs should be an array of void *, where each pointer will be filled with data from a different channel.
Client code compatibility: The readStream() call should be well defined at all times, including prior to activation and after deactivation. When inactive, readStream() should implement the timeout specified by the caller and return SOAPY_SDR_TIMEOUT.
Parameters
stream the opaque pointer to a stream handle
buffs an array of void* buffers num chans in size
numElems the number of elements in each buffer
flags optional flag indicators about the result
timeNs the buffer's timestamp in nanoseconds
timeoutUs the timeout in microseconds
Returns
the number of elements read per buffer or error code
Definition at line 106 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.readStream (self, args)
Definition at line 780 of file SoapySDR.py.
Referenced by SoapySDR.Device.readStream(), gr::radar::soapysdr_echotimer_stretch_impl.receive(), gr::radar::soapysdr_echotimer_impl.receive(), runRateTestStreamLoop(), and SoapySDRDevice_readStream().
def SoapySDR.Device.readStream (self, stream, buffs, numElems, flags = 0, timeoutUs = 100000)
Definition at line 869 of file SoapySDR.py.
References SoapySDR.extractBuffPointer(), SoapySDR.Device.readStream(), and SoapySDR.Device.readStream__().
def SoapySDR.Device.readStream__ (self, args)
Definition at line 859 of file SoapySDR.py.
Referenced by SoapySDR.Device.readStream().
int SoapySDR.Device::readStreamStatus (Stream * stream, size_t & chanMask, int & flags, long long & timeNs, const long timeoutUs = 100000) virtual
Readback status information about a stream. This call is typically used on a transmit stream to report time errors, underflows, and burst completion.
Client code compatibility: Client code may continually poll readStreamStatus() in a loop. Implementations of readStreamStatus() should wait in the call for a status change event or until the timeout expiration. When stream status is not implemented on a particular stream, readStreamStatus() should return SOAPY_SDR_NOT_SUPPORTED. Client code may use this indication to disable a polling loop.
Parameters
stream the opaque pointer to a stream handle
chanMask to which channels this status applies
flags optional input flags and output flags
timeNs the buffer's timestamp in nanoseconds
timeoutUs the timeout in microseconds
Returns
0 for success or error code like timeout
Definition at line 116 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.readStreamStatus (self, args)
Definition at line 782 of file SoapySDR.py.
Referenced by SoapySDR.Device.readStreamStatus(), runRateTestStreamLoop(), and SoapySDRDevice_readStreamStatus().
def SoapySDR.Device.readStreamStatus (self, stream, timeoutUs = 100000)
Definition at line 877 of file SoapySDR.py.
References SoapySDR.Device.readStreamStatus(), and SoapySDR.Device.readStreamStatus__().
def SoapySDR.Device.readStreamStatus__ (self, args)
Definition at line 861 of file SoapySDR.py.
Referenced by SoapySDR.Device.readStreamStatus().
def SoapySDR.Device.readUART (self, args)
Definition at line 858 of file SoapySDR.py.
Referenced by SoapySDRDevice_readUART().
std::string SoapySDR.Device::readUART (const std::string & which, const long timeoutUs = 100000) const virtual
Read bytes from a UART until timeout or newline. Its up to the implementation to set the baud rate, carriage return settings, flushing on newline.
Parameters
which the name of an available UART
timeoutUs a timeout in microseconds
Returns
an array of bytes read from the UART
Definition at line 806 of file Device.cpp.
void SoapySDR.Device::releaseReadBuffer (Stream * stream, const size_t handle) virtual
Release an acquired buffer back to the receive stream. This call is part of the direct buffer access API.
Parameters
stream the opaque pointer to a stream handle
handle the opaque handle from the acquire() call
Definition at line 139 of file Device.cpp.
def SoapySDR.Device.releaseReadBuffer (self, args)
Definition at line 786 of file SoapySDR.py.
Referenced by SoapySDRDevice_releaseReadBuffer().
void SoapySDR.Device::releaseWriteBuffer (Stream * stream, const size_t handle, const size_t numElems, int & flags, const long long timeNs = 0) virtual
Release an acquired buffer back to the transmit stream. This call is part of the direct buffer access API.
Stream meta-data is provided as part of the release call, and not the acquire call so that the caller may acquire buffers without committing to the contents of the meta-data, which can be determined by the user as the buffers are filled.
Parameters
stream the opaque pointer to a stream handle
handle the opaque handle from the acquire() call
numElems the number of elements written to each buffer
flags optional input flags and output flags
timeNs the buffer's timestamp in nanoseconds
Definition at line 149 of file Device.cpp.
def SoapySDR.Device.releaseWriteBuffer (self, args)
Definition at line 788 of file SoapySDR.py.
Referenced by SoapySDRDevice_releaseWriteBuffer().
void SoapySDR.Device::setAntenna (const int direction, const size_t channel, const std::string & name) virtual
Set the selected antenna on a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an available antenna
Reimplemented in SoapyLMS7.
Definition at line 162 of file Device.cpp.
def SoapySDR.Device.setAntenna (self, args)
Definition at line 790 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_setAntenna().
def SoapySDR.Device.setBandwidth (self, args)
Definition at line 820 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_setBandwidth().
void SoapySDR.Device::setBandwidth (const int direction, const size_t channel, const double bw) virtual
Set the baseband filter width of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
bw the baseband filter width in Hz
Reimplemented in SoapyLMS7.
Definition at line 525 of file Device.cpp.
def SoapySDR.Device.setClockSource (self, args)
Definition at line 828 of file SoapySDR.py.
Referenced by SoapySDRDevice_setClockSource().
void SoapySDR.Device::setClockSource (const std::string & source) virtual
Set the clock source on the device
Parameters
source the name of a clock source
Definition at line 574 of file Device.cpp.
def SoapySDR.Device.setCommandTime (self, args)
Definition at line 836 of file SoapySDR.py.
Referenced by SoapySDR.Device.setHardwareTime(), and SoapySDRDevice_setCommandTime().
void SoapySDR.Device::setCommandTime (const long long timeNs, const std::string & what = "") virtual
Set the time of subsequent configuration calls. The what argument can refer to a specific command queue. Implementations may use a time of 0 to clear.
Deprecated:
replaced by setHardwareTime()
Parameters
timeNs time in nanoseconds
what optional argument
Definition at line 618 of file Device.cpp.
void SoapySDR.Device::setDCOffset (const int direction, const size_t channel, const std::complex< double > & offset) virtual
Set the frontend DC offset correction.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
offset the relative correction (1.0 max)
Definition at line 196 of file Device.cpp.
def SoapySDR.Device.setDCOffset (self, args)
Definition at line 796 of file SoapySDR.py.
Referenced by SoapySDRDevice_setDCOffset(), and SoapySDRDevice_setIQBalance().
void SoapySDR.Device::setDCOffsetMode (const int direction, const size_t channel, const bool automatic) virtual
Set the automatic DC offset corrections mode.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
automatic true for automatic offset correction
Reimplemented in SoapyLMS7.
Definition at line 181 of file Device.cpp.
def SoapySDR.Device.setDCOffsetMode (self, args)
Definition at line 793 of file SoapySDR.py.
Referenced by SoapySDRDevice_setDCOffsetMode().
void SoapySDR.Device::setFrequency (const int direction, const size_t channel, const double frequency, const Kwargs & args = Kwargs()) virtual
Set the center frequency of the chain.
For RX, this specifies the down-conversion frequency.
For TX, this specifies the up-conversion frequency.
The default implementation of setFrequency() will tune the "RF" component as close as possible to the requested center frequency. Tuning inaccuracies will be compensated for with the "BB" component.
The args can be used to augment the tuning algorithm.
Use "OFFSET" to specify an "RF" tuning offset, usually with the intention of moving the LO out of the passband. The offset will be compensated for using the "BB" component.
Use the name of a component for the key and a frequency in Hz as the value (any format) to enforce a specific frequency. The other components will be tuned with compensation to achieve the specified overall frequency.
Use the name of a component for the key and the value "IGNORE" so that the tuning algorithm will avoid altering the component.
Vendor specific implementations can also use the same args to augment tuning in other ways such as specifying fractional vs integer N tuning.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
frequency the center frequency in Hz
args optional tuner arguments
Definition at line 340 of file Device.cpp.
References SoapySDR.Device::getFrequency(), SoapySDR.Device::listFrequencies(), SoapySDR.Device::setFrequency(), and string().
void SoapySDR.Device::setFrequency (const int direction, const size_t channel, const std::string & name, const double frequency, const Kwargs & args = Kwargs()) virtual
Tune the center frequency of the specified element.
For RX, this specifies the down-conversion frequency.
For TX, this specifies the up-conversion frequency.
Recommended names used to represent tunable components:
"CORR" - freq error correction in PPM
"RF" - frequency of the RF frontend
"BB" - frequency of the baseband DSP
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of a tunable element
frequency the center frequency in Hz
args optional tuner arguments
Definition at line 380 of file Device.cpp.
def SoapySDR.Device.setFrequency (self, args)
Definition at line 811 of file SoapySDR.py.
Referenced by SoapySDR.Device.setFrequency(), SoapySDR.Device.setFrequencyCorrection(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_setFrequency(), and SoapySDRDevice_setFrequencyComponent().
void SoapySDR.Device::setFrequencyCorrection (const int direction, const size_t channel, const double value) virtual
Fine tune the frontend frequency correction.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
value the correction in PPM
Definition at line 228 of file Device.cpp.
References SoapySDR.Device::listFrequencies(), and SoapySDR.Device::setFrequency().
def SoapySDR.Device.setFrequencyCorrection (self, args)
Definition at line 802 of file SoapySDR.py.
Referenced by SoapySDRDevice_setFrequencyCorrection().
void SoapySDR.Device::setFrontendMapping (const int direction, const std::string & mapping) virtual
Set the frontend mapping of available DSP units to RF frontends. This mapping controls channel mapping and channel availability.
Parameters
direction the channel direction RX or TX
mapping a vendor-specific mapping string
Definition at line 36 of file Device.cpp.
def SoapySDR.Device.setFrontendMapping (self, args)
Definition at line 767 of file SoapySDR.py.
Referenced by SoapySDRDevice_setFrontendMapping().
void SoapySDR.Device::setGain (const int direction, const size_t channel, const double value) virtual
Set the overall amplification in a chain. The gain will be distributed automatically across available element.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
value the new amplification value in dB
Reimplemented in SoapyLMS7.
Definition at line 272 of file Device.cpp.
References SoapySDR.Device::getGain(), SoapySDR.Device::getGainRange(), i, SoapySDR.Device::listGains(), calc_fmcw_peaks::r, SoapySDR.Device::setGain(), SoapySDR::SOAPY_SDR_RX, and SoapySDR::SOAPY_SDR_TX.
void SoapySDR.Device::setGain (const int direction, const size_t channel, const std::string & name, const double value) virtual
Set the value of a amplification element in a chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
name the name of an amplification element
value the new amplification value in dB
Reimplemented in SoapyLMS7.
Definition at line 298 of file Device.cpp.
def SoapySDR.Device.setGain (self, args)
Definition at line 808 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_stretch_impl.set_rx_gain(), gr::radar::soapysdr_echotimer_impl.set_rx_gain(), gr::radar::soapysdr_echotimer_stretch_impl.set_tx_gain(), gr::radar::soapysdr_echotimer_impl.set_tx_gain(), SoapySDR.Device.setGain(), SoapySDRDevice_setGain(), and SoapySDRDevice_setGainElement().
void SoapySDR.Device::setGainMode (const int direction, const size_t channel, const bool automatic) virtual
Set the automatic gain mode on the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
automatic true for automatic gain setting
Definition at line 262 of file Device.cpp.
def SoapySDR.Device.setGainMode (self, args)
Definition at line 806 of file SoapySDR.py.
Referenced by SoapySDRDevice_setGainMode().
def SoapySDR.Device.setHardwareTime (self, args)
Definition at line 835 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), and SoapySDRDevice_setHardwareTime().
void SoapySDR.Device::setHardwareTime (const long long timeNs, const std::string & what = "") virtual
Write the time to the hardware clock on the device. The what argument can refer to a specific time counter.
Parameters
timeNs time in nanoseconds
what optional argument
Reimplemented in SoapyLMS7.
Definition at line 613 of file Device.cpp.
References SoapySDR.Device::setCommandTime().
void SoapySDR.Device::setIQBalance (const int direction, const size_t channel, const std::complex< double > & balance) virtual
Set the frontend IQ balance correction.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
balance the relative correction (1.0 max)
Definition at line 211 of file Device.cpp.
def SoapySDR.Device.setIQBalance (self, args)
Definition at line 799 of file SoapySDR.py.
def SoapySDR.Device.setMasterClockRate (self, args)
Definition at line 824 of file SoapySDR.py.
Referenced by SoapySDRDevice_setMasterClockRate().
void SoapySDR.Device::setMasterClockRate (const double rate) virtual
Set the master clock rate of the device.
Parameters
rate the clock rate in Hz
Reimplemented in SoapyLMS7.
Definition at line 554 of file Device.cpp.
def SoapySDR.Device.setSampleRate (self, args)
Definition at line 816 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_setSampleRate(), and SoapySDRRateTest().
void SoapySDR.Device::setSampleRate (const int direction, const size_t channel, const double rate) virtual
Set the baseband sample rate of the chain.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
rate the sample rate in samples per second
Reimplemented in SoapyLMS7.
Definition at line 496 of file Device.cpp.
def SoapySDR.Device.setTimeSource (self, args)
Definition at line 831 of file SoapySDR.py.
Referenced by SoapySDRDevice_setTimeSource().
void SoapySDR.Device::setTimeSource (const std::string & source) virtual
Set the time source on the device
Parameters
source the name of a time source
Definition at line 593 of file Device.cpp.
SoapySDR::Stream * SoapySDR.Device::setupStream (const int direction, const std::string & format, const std::vector< size_t > & channels = std::vector<size_t>(), const Kwargs & args = Kwargs()) virtual
Initialize a stream given a list of channels and stream arguments. The implementation may change switches or power-up components. All stream API calls should be usable with the new stream object after setupStream() is complete, regardless of the activity state.
The API allows any number of simultaneous TX and RX streams, but many dual-channel devices are limited to one stream in each direction, using either one or both channels. This call will throw an exception if an unsupported combination is requested, or if a requested channel in this direction is already in use by another stream.
When multiple channels are added to a stream, they are typically expected to have the same sample rate. See setSampleRate().
Parameters
direction the channel direction (SOAPY_SDR_RX or SOAPY_SDR_TX)
format A string representing the desired buffer format in read/writeStream()
The first character selects the number type:
"C" means complex
"F" means floating point
"S" means signed integer
"U" means unsigned integer
The type character is followed by the number of bits per number (complex is 2x this size per sample)
Example format strings:
"CF32" - complex float32 (8 bytes per element)
"CS16" - complex int16 (4 bytes per element)
"CS12" - complex int12 (3 bytes per element)
"CS4" - complex int4 (1 byte per element)
"S32" - int32 (4 bytes per element)
"U8" - uint8 (1 byte per element)
channels a list of channels or empty for automatic.
args stream args or empty for defaults.
Recommended keys to use in the args dictionary:
"WIRE" - format of the samples between device and host
Returns
an opaque pointer to a stream handle.
The returned stream is not required to have internal locking, and may not be used concurrently from multiple threads.
Definition at line 80 of file Device.cpp.
def SoapySDR.Device.setupStream (self, args)
Definition at line 775 of file SoapySDR.py.
Referenced by gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_setupStream(), and SoapySDRRateTest().
def SoapySDR.Device.transactSPI (self, args)
Definition at line 855 of file SoapySDR.py.
Referenced by SoapySDRDevice_transactSPI().
unsigned SoapySDR.Device::transactSPI (const int addr, const unsigned data, const size_t numBits) virtual
Perform a SPI transaction and return the result. Its up to the implementation to set the clock rate, and read edge, and the write edge of the SPI core. SPI slaves without a readback pin will return 0.
If the device contains multiple SPI masters, the address bits can encode which master.
Parameters
addr an address of an available SPI slave
data the SPI data, numBits-1 is first out
numBits the number of bits to clock out
Returns
the readback data, numBits-1 is first in
Definition at line 788 of file Device.cpp.
static void SoapySDR.Device.unmake (Device * device) static
Unmake or release a device object handle.
Parameters
device a pointer to a device object
def SoapySDR.Device.writeGPIO (self, args)
Definition at line 849 of file SoapySDR.py.
Referenced by gr::radar::gpio_source_s_impl.gpio_source_s_impl(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_writeGPIO(), SoapySDRDevice_writeGPIOMasked(), and SoapySDR.Device.writeGPIO().
void SoapySDR.Device::writeGPIO (const std::string & bank, const unsigned value) virtual
Write the value of a GPIO bank.
Parameters
bank the name of an available bank
value an integer representing GPIO bits
Reimplemented in SoapyLMS7.
Definition at line 735 of file Device.cpp.
void SoapySDR.Device::writeGPIO (const std::string & bank, const unsigned value, const unsigned mask) virtual
Write the value of a GPIO bank with modification mask.
Parameters
bank the name of an available bank
value an integer representing GPIO bits
mask a modification mask where 1 = modify
Definition at line 740 of file Device.cpp.
References SoapySDR.Device::readGPIO(), and SoapySDR.Device::writeGPIO().
def SoapySDR.Device.writeGPIODir (self, args)
Definition at line 851 of file SoapySDR.py.
Referenced by gr::radar::gpio_source_s_impl.gpio_source_s_impl(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_writeGPIODir(), SoapySDRDevice_writeGPIODirMasked(), and SoapySDR.Device.writeGPIODir().
void SoapySDR.Device::writeGPIODir (const std::string & bank, const unsigned dir) virtual
Write the data direction of a GPIO bank. 1 bits represent outputs, 0 bits represent inputs.
Parameters
bank the name of an available bank
dir an integer representing data direction bits
Reimplemented in SoapyLMS7.
Definition at line 753 of file Device.cpp.
void SoapySDR.Device::writeGPIODir (const std::string & bank, const unsigned dir, const unsigned mask) virtual
Write the data direction of a GPIO bank with modification mask. 1 bits represent outputs, 0 bits represent inputs.
Parameters
bank the name of an available bank
dir an integer representing data direction bits
mask a modification mask where 1 = modify
Definition at line 758 of file Device.cpp.
References SoapySDR.Device::readGPIODir(), and SoapySDR.Device::writeGPIODir().
def SoapySDR.Device.writeI2C (self, args)
Definition at line 853 of file SoapySDR.py.
Referenced by SoapySDRDevice_writeI2C().
void SoapySDR.Device::writeI2C (const int addr, const std::string & data) virtual
Write to an available I2C slave. If the device contains multiple I2C masters, the address bits can encode which master.
Parameters
addr the address of the slave
data an array of bytes write out
Definition at line 775 of file Device.cpp.
def SoapySDR.Device.writeRegister (self, args)
Definition at line 841 of file SoapySDR.py.
Referenced by gr::radar::gpio_source_s_impl.gpio_source_s_impl(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_writeRegister(), SoapySDR.Device.writeRegister(), gr::radar::gpio_source_s_impl.~gpio_source_s_impl(), gr::radar::soapysdr_echotimer_impl.~soapysdr_echotimer_impl(), and gr::radar::soapysdr_echotimer_stretch_impl.~soapysdr_echotimer_stretch_impl().
void SoapySDR.Device::writeRegister (const std::string & name, const unsigned addr, const unsigned value) virtual
Write a register on the device given the interface name. This can represent a register on a soft CPU, FPGA, IC; the interpretation is up the implementation to decide.
Parameters
name the name of a available register interface
addr the register address
value the register value
Reimplemented in SoapyLMS7.
Definition at line 664 of file Device.cpp.
References SoapySDR.Device::writeRegister().
void SoapySDR.Device::writeRegister (const unsigned addr, const unsigned value) virtual
Write a register on the device. This can represent a register on a soft CPU, FPGA, IC; the interpretation is up the implementation to decide.
Deprecated:
replaced by writeRegister(name)
Parameters
addr the register address
value the register value
Reimplemented in SoapyLMS7.
Definition at line 674 of file Device.cpp.
def SoapySDR.Device.writeRegisters (self, args)
Definition at line 843 of file SoapySDR.py.
Referenced by SoapySDRDevice_writeRegisters().
void SoapySDR.Device::writeRegisters (const std::string & name, const unsigned addr, const std::vector< unsigned > & value) virtual
Write a memory block on the device given the interface name. This can represent a memory block on a soft CPU, FPGA, IC; the interpretation is up the implementation to decide.
Parameters
name the name of a available memory block interface
addr the memory block start address
value the memory block content
Definition at line 684 of file Device.cpp.
def SoapySDR.Device.writeSetting (self, args)
Definition at line 846 of file SoapySDR.py.
Referenced by SoapySDRDevice_writeChannelSetting(), and SoapySDRDevice_writeSetting().
void SoapySDR.Device::writeSetting (const std::string & key, const std::string & value) virtual
Write an arbitrary setting on the device. The interpretation is up the implementation.
Parameters
key the setting identifier
value the setting value
Reimplemented in SoapyLMS7.
Definition at line 702 of file Device.cpp.
void SoapySDR.Device::writeSetting (const int direction, const size_t channel, const std::string & key, const std::string & value) virtual
Write an arbitrary channel setting on the device. The interpretation is up the implementation.
Parameters
direction the channel direction RX or TX
channel an available channel on the device
key the setting identifier
value the setting value
Reimplemented in SoapyLMS7.
Definition at line 717 of file Device.cpp.
int SoapySDR.Device::writeStream (Stream * stream, const void *const * buffs, const size_t numElems, int & flags, const long long timeNs = 0, const long timeoutUs = 100000) virtual
Write elements to a stream for transmission. This is a multi-channel call, and buffs should be an array of void *, where each pointer will be filled with data for a different channel.
Client code compatibility: Client code relies on writeStream() for proper back-pressure. The writeStream() implementation must enforce the timeout such that the call blocks until space becomes available or timeout expiration.
Parameters
stream the opaque pointer to a stream handle
buffs an array of void* buffers num chans in size
numElems the number of elements in each buffer
flags optional input flags and output flags
timeNs the buffer's timestamp in nanoseconds
timeoutUs the timeout in microseconds
Returns
the number of elements written per buffer or error
Definition at line 111 of file Device.cpp.
References SoapySDR::SOAPY_SDR_NOT_SUPPORTED.
def SoapySDR.Device.writeStream (self, args)
Definition at line 781 of file SoapySDR.py.
Referenced by runRateTestStreamLoop(), gr::radar::soapysdr_echotimer_stretch_impl.send(), gr::radar::soapysdr_echotimer_impl.send(), SoapySDRDevice_writeStream(), and SoapySDR.Device.writeStream().
def SoapySDR.Device.writeStream (self, stream, buffs, numElems, flags = 0, timeNs = 0, timeoutUs = 100000)
Definition at line 873 of file SoapySDR.py.
References SoapySDR.extractBuffPointer(), SoapySDR.Device.writeStream(), and SoapySDR.Device.writeStream__().
def SoapySDR.Device.writeStream__ (self, args)
Definition at line 860 of file SoapySDR.py.
Referenced by SoapySDR.Device.writeStream().
def SoapySDR.Device.writeUART (self, args)
Definition at line 857 of file SoapySDR.py.
Referenced by SoapySDRDevice_writeUART().
void SoapySDR.Device::writeUART (const std::string & which, const std::string & data) virtual
Write data to a UART device. Its up to the implementation to set the baud rate, carriage return settings, flushing on newline.
Parameters
which the name of an available UART
data an array of bytes to write out
Definition at line 801 of file Device.cpp.
Member Data Documentation
SoapySDR.Device.__del__ = lambdaself:None; static private
Definition at line 757 of file SoapySDR.py.
Referenced by SoapySDR.Device.__del__().
SoapySDR.Device.__getattr__ = lambdaself,name:_swig_getattr(self, Device, name) static private
Definition at line 753 of file SoapySDR.py.
SoapySDR.Device.__repr__ = _swig_repr static private
Definition at line 755 of file SoapySDR.py.
SoapySDR.Device.__setattr__ = lambdaself,name,value:_swig_setattr(self, Device, name, value) static private
Definition at line 751 of file SoapySDR.py.
SoapySDR.Device.__swig_destroy__ = _SoapySDR.delete_Device static private
Definition at line 756 of file SoapySDR.py.
dictionary SoapySDR.Device.__swig_getmethods__ = {} static private
Definition at line 752 of file SoapySDR.py.
dictionary SoapySDR.Device.__swig_setmethods__ = {} static private
Definition at line 750 of file SoapySDR.py.
SoapySDR.KwargsList SoapySDR.Device.enumerate static
Definition at line 759 of file SoapySDR.py.
Referenced by _wrap_Device_enumerate__SWIG_0(), _wrap_Device_enumerate__SWIG_1(), _wrap_Device_enumerate__SWIG_2(), findDevices(), getDeviceCounts(), getDeviceFromTable(), SoapySDRDevice_enumerate(), and SoapySDRDevice_enumerateStrArgs().
SoapySDR.Device * SoapySDR.Device.make static
Definition at line 761 of file SoapySDR.py.
Referenced by SoapySDR.Device.__new__(), _wrap_Device_make__SWIG_0(), _wrap_Device_make__SWIG_1(), _wrap_Device_make__SWIG_2(), getDeviceFromTable(), gr::radar::gpio_source_s_impl.gpio_source_s_impl(), makeDevice(), probeDevice(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRDevice_make(), SoapySDRDevice_makeStrArgs(), and SoapySDRRateTest().
void SoapySDR.Device.unmake static
Definition at line 763 of file SoapySDR.py.
Referenced by _wrap_Device_unmake(), getDeviceFromTable(), makeDevice(), probeDevice(), SoapySDRDevice_unmake(), and SoapySDRRateTest().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDR.py
/home/erik/prefix/default/src/soapysdr/include/SoapySDR/Device.hpp
/home/erik/prefix/default/src/soapysdr/lib/Device.cpp
/home/erik/prefix/default/src/soapysdr/lib/Factory.cpp