LimeSuite-UML: NumericSlider Class Reference
NumericSlider Class Reference
#include <numericSlider.h>
Public Member Functions
NumericSlider ()
NumericSlider (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &value=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxSP_ARROW_KEYS, int min=0, int max=100, int initial=0, const wxString &name="numericSlider")
~NumericSlider ()
void SetValue (int integer)
int GetValue ()
virtual void SetToolTip (const wxString &tipString)
Protected Member Functions
void OnSpinnerChangeEnter (wxSpinEvent &event)
void OnSpinnerChange (wxSpinEvent &event)
void OnScrollChange (wxScrollEvent &event)
Protected Attributes
wxSpinCtrl * mSpinner
wxScrollBar * mScroll
Detailed Description
Definition at line 16 of file numericSlider.h.
Constructor & Destructor Documentation
NumericSlider::NumericSlider ()
Definition at line 13 of file numericSlider.cpp.
NumericSlider::NumericSlider (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & value = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxSP_ARROW_KEYS, int min = 0, int max = 100, int initial = 0, const wxString & name = "numericSlider")
Definition at line 17 of file numericSlider.cpp.
References mScroll, mSpinner, OnScrollChange(), OnSpinnerChange(), and OnSpinnerChangeEnter().
NumericSlider::~NumericSlider ()
Definition at line 60 of file numericSlider.cpp.
Member Function Documentation
int NumericSlider::GetValue ()
Definition at line 108 of file numericSlider.cpp.
References mSpinner.
void NumericSlider::OnScrollChange (wxScrollEvent & event) protected
Definition at line 88 of file numericSlider.cpp.
References mSpinner.
Referenced by NumericSlider().
void NumericSlider::OnSpinnerChange (wxSpinEvent & event) protected
Definition at line 78 of file numericSlider.cpp.
References mScroll, and mSpinner.
Referenced by NumericSlider().
void NumericSlider::OnSpinnerChangeEnter (wxSpinEvent & event) protected
Definition at line 65 of file numericSlider.cpp.
References mScroll, mSpinner, and string().
Referenced by NumericSlider().
void NumericSlider::SetToolTip (const wxString & tipString) virtual
Definition at line 113 of file numericSlider.cpp.
References mScroll, and mSpinner.
Referenced by pnlRxTSP_view::pnlRxTSP_view().
void NumericSlider::SetValue (int integer)
Definition at line 98 of file numericSlider.cpp.
References mScroll, and mSpinner.
Referenced by lms7002_pnlCLKGEN_view::onbtnTuneClick(), lms7002_pnlRFE_view::UpdateGUI(), lms7002_pnlCalibrations_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateGUI(), lms7002_pnlRxTSP_view::UpdateGUI(), and lms7002_pnlR3_view::UpdateGUISlow().
Member Data Documentation
wxScrollBar* NumericSlider::mScroll protected
Definition at line 42 of file numericSlider.h.
Referenced by NumericSlider(), OnSpinnerChange(), OnSpinnerChangeEnter(), SetToolTip(), and SetValue().
wxSpinCtrl* NumericSlider::mSpinner protected
Definition at line 41 of file numericSlider.h.
Referenced by GetValue(), NumericSlider(), OnScrollChange(), OnSpinnerChange(), OnSpinnerChangeEnter(), SetToolTip(), and SetValue().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/numericSlider/numericSlider.h
/home/erik/prefix/default/src/limesuite-dev/src/numericSlider/numericSlider.cpp