LimeSuite-UML: swig_doc Namespace Reference
swig_doc Namespace Reference
Classes
class Block
Functions
def py_name (name)
def make_name (name)
def utoascii (text)
def combine_descriptions (obj)
def make_entry (obj, name=None, templ="{description}", description=None)
def make_func_entry (func, name=None, description=None, params=None)
def make_class_entry (klass, description=None)
def make_block_entry (di, block)
def make_swig_interface_file (di, swigdocfilename, custom_output=None)
Variables
string entry_templ = '%feature("docstring") {name} "{docstring}"'
string err_msg = "Execute using: python swig_doc.py xml_path outputfilename"
xml_path = sys.argv[1]
swigdocfilename = sys.argv[2]
di = DoxyIndex(xml_path)
list output = []
string custom_output = "\n\n"
Function Documentation
def swig_doc.combine_descriptions (obj)
Combines the brief and detailed descriptions of an object together.
Definition at line 73 of file swig_doc.py.
References utoascii().
Referenced by make_block_entry(), and make_entry().
def swig_doc.make_block_entry (di, block)
Create class and function docstrings of a gnuradio block for a
swig interface file.
Definition at line 148 of file swig_doc.py.
References combine_descriptions(), make_class_entry(), make_func_entry(), and make_name().
Referenced by make_swig_interface_file().
def swig_doc.make_class_entry (klass, description = None)
Create a class docstring for a swig interface file.
Definition at line 136 of file swig_doc.py.
References make_entry(), and make_func_entry().
Referenced by make_block_entry(), and make_swig_interface_file().
def swig_doc.make_entry (obj, name = None, templ = "{description}", description = None)
Create a docstring entry for a swig interface file.
obj - a doxyxml object from which documentation will be extracted.
name - the name of the C object (defaults to obj.name())
templ - an optional template for the docstring containing only one
        variable named 'description'.
description - if this optional variable is set then it's value is
        used as the description instead of extracting it from obj.
Definition at line 88 of file swig_doc.py.
References combine_descriptions().
Referenced by make_class_entry(), and make_func_entry().
def swig_doc.make_func_entry (func, name = None, description = None, params = None)
Create a function docstring entry for a swig interface file.
func - a doxyxml object from which documentation will be extracted.
name - the name of the C object (defaults to func.name())
description - if this optional variable is set then it's value is
        used as the description instead of extracting it from func.
params - a parameter list that overrides using func.params.
Definition at line 114 of file swig_doc.py.
References make_entry(), and utoascii().
Referenced by make_block_entry(), make_class_entry(), and make_swig_interface_file().
def swig_doc.make_name (name)
Definition at line 42 of file swig_doc.py.
Referenced by swig_doc.Block.includes(), make_block_entry(), and make_swig_interface_file().
def swig_doc.make_swig_interface_file (di, swigdocfilename, custom_output = None)
Definition at line 184 of file swig_doc.py.
References file(), make_block_entry(), make_class_entry(), make_func_entry(), make_name(), print(), and set().
def swig_doc.py_name (name)
Definition at line 38 of file swig_doc.py.
def swig_doc.utoascii (text)
Convert unicode text into ascii and escape quotes.
Definition at line 62 of file swig_doc.py.
Referenced by combine_descriptions(), and make_func_entry().
Variable Documentation
swig_doc.custom_output = "\n\n"
Definition at line 252 of file swig_doc.py.
swig_doc.di = DoxyIndex(xml_path)
Definition at line 242 of file swig_doc.py.
string swig_doc.entry_templ = '%feature("docstring") {name} "{docstring}"'
Definition at line 87 of file swig_doc.py.
string swig_doc.err_msg = "Execute using: python swig_doc.py xml_path outputfilename"
Definition at line 237 of file swig_doc.py.
list swig_doc.output = []
Definition at line 249 of file swig_doc.py.
Referenced by LimeSDRTest.RunTest().
swig_doc.swigdocfilename = sys.argv[2]
Definition at line 241 of file swig_doc.py.
swig_doc.xml_path = sys.argv[1]
Definition at line 240 of file swig_doc.py.