LimeSuite-UML: Si5351C_wxgui Class Reference
Si5351C_wxgui Class Reference
#include <Si5351C_wxgui.h>
Public Member Functions
Si5351C_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_(""), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int styles=wxDEFAULT_FRAME_STYLE, wxString idname="")
void Initialize (lms_device_t *pModule)
virtual ~Si5351C_wxgui ()
void ModifyClocksGUI (const std::string &board)
Public Attributes
wxCheckBox * chkEN_CLK5
wxCheckBox * chkInvert_CLK6
wxTextCtrl * txtFreq_CLK7
wxTextCtrl * txtFreq_CLK1
wxCheckBox * chkEN_CLK3
wxCheckBox * chkEN_CLK4
wxCheckBox * chkInvert_CLK3
wxTextCtrl * txtFreq_CLK5
wxStaticText * StaticText13
wxStaticText * StaticText2
wxButton * btnLoadFile
wxTextCtrl * txtFreq_CLK0
wxStaticText * lblCLK6
wxStaticText * lblCLK7
wxStaticText * lblCLK0
wxButton * btnResetToDefaults
wxStaticText * lblCLK5
wxStaticText * StaticText11
wxStaticText * StaticText1
wxButton * btnConfigure
wxCheckBox * chkEN_CLK6
wxStaticText * lblCLK4
wxStaticText * lblCLK2
wxTextCtrl * txtFreq_CLK3
wxButton * btnReadStatus
wxTextCtrl * txtFreq_CLK6
wxButton * btnClearStatus
wxTextCtrl * txtFreq_CLK2
wxCheckBox * chkInvert_CLK2
wxCheckBox * chkInvert_CLK0
wxCheckBox * chkEN_CLK1
wxStaticText * StaticText12
wxStaticText * lblStatus
wxStaticText * lblCLK3
wxCheckBox * chkEN_CLK7
wxCheckBox * chkInvert_CLK1
wxTextCtrl * txtFreq_CLK4
wxTextCtrl * txtCLKIN_MHz
wxStaticText * lblCLK1
wxCheckBox * chkInvert_CLK7
wxCheckBox * chkInvert_CLK5
wxCheckBox * chkEN_CLK2
wxCheckBox * chkEN_CLK0
wxCheckBox * chkInvert_CLK4
wxRadioBox * rgrClkSrc
wxRadioBox * rgrXTALfreq
Protected Member Functions
void ClockEnable (unsigned int i, bool enabled)
void BuildContent (wxWindow *parent, wxWindowID id, const wxPoint &pos, const wxSize &size)
Static Protected Attributes
static const long ID_BUTTON2 = wxNewId()
static const long ID_BUTTON4 = wxNewId()
static const long ID_STATICTEXT1 = wxNewId()
static const long ID_TEXTCTRL1 = wxNewId()
static const long ID_STATICTEXT14 = wxNewId()
static const long ID_BUTTON1 = wxNewId()
static const long ID_BUTTON5 = wxNewId()
static const long ID_STATICTEXT2 = wxNewId()
static const long ID_STATICTEXT11 = wxNewId()
static const long ID_STATICTEXT12 = wxNewId()
static const long ID_STATICTEXT13 = wxNewId()
static const long ID_STATICTEXT3 = wxNewId()
static const long ID_CHECKBOX1 = wxNewId()
static const long ID_TEXTCTRL2 = wxNewId()
static const long ID_CHECKBOX9 = wxNewId()
static const long ID_STATICTEXT4 = wxNewId()
static const long ID_CHECKBOX2 = wxNewId()
static const long ID_TEXTCTRL3 = wxNewId()
static const long ID_CHECKBOX10 = wxNewId()
static const long ID_STATICTEXT5 = wxNewId()
static const long ID_CHECKBOX3 = wxNewId()
static const long ID_TEXTCTRL4 = wxNewId()
static const long ID_CHECKBOX11 = wxNewId()
static const long ID_STATICTEXT6 = wxNewId()
static const long ID_CHECKBOX4 = wxNewId()
static const long ID_TEXTCTRL5 = wxNewId()
static const long ID_CHECKBOX12 = wxNewId()
static const long ID_STATICTEXT7 = wxNewId()
static const long ID_CHECKBOX5 = wxNewId()
static const long ID_TEXTCTRL6 = wxNewId()
static const long ID_CHECKBOX13 = wxNewId()
static const long ID_STATICTEXT8 = wxNewId()
static const long ID_CHECKBOX6 = wxNewId()
static const long ID_TEXTCTRL7 = wxNewId()
static const long ID_CHECKBOX14 = wxNewId()
static const long ID_STATICTEXT9 = wxNewId()
static const long ID_CHECKBOX7 = wxNewId()
static const long ID_TEXTCTRL8 = wxNewId()
static const long ID_CHECKBOX15 = wxNewId()
static const long ID_STATICTEXT10 = wxNewId()
static const long ID_CHECKBOX8 = wxNewId()
static const long ID_TEXTCTRL9 = wxNewId()
static const long ID_CHECKBOX16 = wxNewId()
static const long ID_BUTTON3 = wxNewId()
Private Member Functions
void OnbtnLoadFileClick (wxCommandEvent &event)
void OnbtnConfigureClockClick (wxCommandEvent &event)
void OnbtnResetToDefaultsClick (wxCommandEvent &event)
void OnButton1Click (wxCommandEvent &event)
void OnbtnReadStatusClick (wxCommandEvent &event)
void OnbtnClearStatusClick (wxCommandEvent &event)
bool LoadRegValuesFromFile (std::string FName)
Private Attributes
unsigned char m_newConfiguration [255]
lms_device_t * lmsControl
Detailed Description
Definition at line 19 of file Si5351C_wxgui.h.
Constructor & Destructor Documentation
Si5351C_wxgui::Si5351C_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = _(""), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int styles = wxDEFAULT_FRAME_STYLE, wxString idname = "")
Definition at line 75 of file Si5351C_wxgui.cpp.
References _T, lmsControl, OnbtnClearStatusClick(), OnbtnConfigureClockClick(), OnbtnLoadFileClick(), OnbtnReadStatusClick(), and OnbtnResetToDefaultsClick().
Si5351C_wxgui::~Si5351C_wxgui () virtual
Definition at line 238 of file Si5351C_wxgui.cpp.
Member Function Documentation
void Si5351C_wxgui::BuildContent (wxWindow * parent, wxWindowID id, const wxPoint & pos, const wxSize & size) protected
Definition at line 234 of file Si5351C_wxgui.cpp.
void Si5351C_wxgui::ClockEnable (unsigned int i, bool enabled) protected
Definition at line 352 of file Si5351C_wxgui.cpp.
void Si5351C_wxgui::Initialize (lms_device_t * pModule)
Definition at line 229 of file Si5351C_wxgui.cpp.
References lmsControl.
Referenced by LMS7SuiteAppFrame::OnShowSi5351C(), and LMS7SuiteAppFrame::UpdateConnections().
bool Si5351C_wxgui::LoadRegValuesFromFile (std::string FName) private
void Si5351C_wxgui::ModifyClocksGUI (const std::string & board)
Definition at line 318 of file Si5351C_wxgui.cpp.
References lime::GetDeviceName(), i, and lime::LMS_DEV_STREAM.
Referenced by LMS7SuiteAppFrame::OnControlBoardConnect(), and LMS7SuiteAppFrame::OnShowSi5351C().
void Si5351C_wxgui::OnbtnClearStatusClick (wxCommandEvent & event) private
Definition at line 422 of file Si5351C_wxgui.cpp.
References lime::Si5351C::ClearStatus(), lime::Si5351C::Initialize(), and lmsControl.
Referenced by Si5351C_wxgui().
void Si5351C_wxgui::OnbtnConfigureClockClick (wxCommandEvent & event) private
Definition at line 255 of file Si5351C_wxgui.cpp.
References lime::Si5351C::ConfigureClocks(), freq, i, lime::Si5351C::Initialize(), lmsControl, lime::Si5351C::SetClock(), lime::Si5351C::SetPLL(), and lime::Si5351C::UploadConfiguration().
Referenced by Si5351C_wxgui().
void Si5351C_wxgui::OnbtnLoadFileClick (wxCommandEvent & event) private
Definition at line 242 of file Si5351C_wxgui.cpp.
References lime::Si5351C::Initialize(), lmsControl, lime::Si5351C::LoadRegValuesFromFile(), string(), and lime::Si5351C::UploadConfiguration().
Referenced by Si5351C_wxgui().
void Si5351C_wxgui::OnbtnReadStatusClick (wxCommandEvent & event) private
Definition at line 409 of file Si5351C_wxgui.cpp.
References lime::Si5351C::GetStatusBits(), lime::Si5351C::Initialize(), lmsControl, lime::Si5351C::StatusBits::lol_a, lime::Si5351C::StatusBits::lol_a_stky, lime::Si5351C::StatusBits::lol_b, lime::Si5351C::StatusBits::lol_b_stky, lime::Si5351C::StatusBits::los, lime::Si5351C::StatusBits::los_stky, lime::Si5351C::StatusBits::sys_init, and lime::Si5351C::StatusBits::sys_init_stky.
Referenced by Si5351C_wxgui().
void Si5351C_wxgui::OnbtnResetToDefaultsClick (wxCommandEvent & event) private
Definition at line 310 of file Si5351C_wxgui.cpp.
References lime::Si5351C::Initialize(), lmsControl, lime::Si5351C::Reset(), and lime::Si5351C::UploadConfiguration().
Referenced by Si5351C_wxgui().
void Si5351C_wxgui::OnButton1Click (wxCommandEvent & event) private
Member Data Documentation
wxButton* Si5351C_wxgui::btnClearStatus
Definition at line 55 of file Si5351C_wxgui.h.
wxButton* Si5351C_wxgui::btnConfigure
Definition at line 48 of file Si5351C_wxgui.h.
wxButton* Si5351C_wxgui::btnLoadFile
Definition at line 39 of file Si5351C_wxgui.h.
wxButton* Si5351C_wxgui::btnReadStatus
Definition at line 53 of file Si5351C_wxgui.h.
wxButton* Si5351C_wxgui::btnResetToDefaults
Definition at line 44 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK0
Definition at line 71 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK1
Definition at line 59 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK2
Definition at line 70 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK3
Definition at line 33 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK4
Definition at line 34 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK5
Definition at line 29 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK6
Definition at line 49 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkEN_CLK7
Definition at line 63 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK0
Definition at line 58 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK1
Definition at line 64 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK2
Definition at line 57 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK3
Definition at line 35 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK4
Definition at line 72 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK5
Definition at line 69 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK6
Definition at line 30 of file Si5351C_wxgui.h.
wxCheckBox* Si5351C_wxgui::chkInvert_CLK7
Definition at line 68 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_BUTTON1 = wxNewId() static protected
Definition at line 85 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_BUTTON2 = wxNewId() static protected
Definition at line 80 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_BUTTON3 = wxNewId() static protected
Definition at line 123 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_BUTTON4 = wxNewId() static protected
Definition at line 81 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_BUTTON5 = wxNewId() static protected
Definition at line 86 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX1 = wxNewId() static protected
Definition at line 92 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX10 = wxNewId() static protected
Definition at line 98 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX11 = wxNewId() static protected
Definition at line 102 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX12 = wxNewId() static protected
Definition at line 106 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX13 = wxNewId() static protected
Definition at line 110 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX14 = wxNewId() static protected
Definition at line 114 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX15 = wxNewId() static protected
Definition at line 118 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX16 = wxNewId() static protected
Definition at line 122 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX2 = wxNewId() static protected
Definition at line 96 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX3 = wxNewId() static protected
Definition at line 100 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX4 = wxNewId() static protected
Definition at line 104 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX5 = wxNewId() static protected
Definition at line 108 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX6 = wxNewId() static protected
Definition at line 112 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX7 = wxNewId() static protected
Definition at line 116 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX8 = wxNewId() static protected
Definition at line 120 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_CHECKBOX9 = wxNewId() static protected
Definition at line 94 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT1 = wxNewId() static protected
Definition at line 82 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT10 = wxNewId() static protected
Definition at line 119 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT11 = wxNewId() static protected
Definition at line 88 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT12 = wxNewId() static protected
Definition at line 89 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT13 = wxNewId() static protected
Definition at line 90 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT14 = wxNewId() static protected
Definition at line 84 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT2 = wxNewId() static protected
Definition at line 87 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT3 = wxNewId() static protected
Definition at line 91 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT4 = wxNewId() static protected
Definition at line 95 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT5 = wxNewId() static protected
Definition at line 99 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT6 = wxNewId() static protected
Definition at line 103 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT7 = wxNewId() static protected
Definition at line 107 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT8 = wxNewId() static protected
Definition at line 111 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_STATICTEXT9 = wxNewId() static protected
Definition at line 115 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL1 = wxNewId() static protected
Definition at line 83 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL2 = wxNewId() static protected
Definition at line 93 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL3 = wxNewId() static protected
Definition at line 97 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL4 = wxNewId() static protected
Definition at line 101 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL5 = wxNewId() static protected
Definition at line 105 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL6 = wxNewId() static protected
Definition at line 109 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL7 = wxNewId() static protected
Definition at line 113 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL8 = wxNewId() static protected
Definition at line 117 of file Si5351C_wxgui.h.
const long Si5351C_wxgui::ID_TEXTCTRL9 = wxNewId() static protected
Definition at line 121 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK0
Definition at line 43 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK1
Definition at line 67 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK2
Definition at line 51 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK3
Definition at line 62 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK4
Definition at line 50 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK5
Definition at line 45 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK6
Definition at line 41 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblCLK7
Definition at line 42 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::lblStatus
Definition at line 61 of file Si5351C_wxgui.h.
lms_device_t* Si5351C_wxgui::lmsControl private
Definition at line 136 of file Si5351C_wxgui.h.
unsigned char Si5351C_wxgui::m_newConfiguration[255] private
Definition at line 135 of file Si5351C_wxgui.h.
wxRadioBox* Si5351C_wxgui::rgrClkSrc
Definition at line 73 of file Si5351C_wxgui.h.
wxRadioBox* Si5351C_wxgui::rgrXTALfreq
Definition at line 74 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::StaticText1
Definition at line 47 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::StaticText11
Definition at line 46 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::StaticText12
Definition at line 60 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::StaticText13
Definition at line 37 of file Si5351C_wxgui.h.
wxStaticText* Si5351C_wxgui::StaticText2
Definition at line 38 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtCLKIN_MHz
Definition at line 66 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK0
Definition at line 40 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK1
Definition at line 32 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK2
Definition at line 56 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK3
Definition at line 52 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK4
Definition at line 65 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK5
Definition at line 36 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK6
Definition at line 54 of file Si5351C_wxgui.h.
wxTextCtrl* Si5351C_wxgui::txtFreq_CLK7
Definition at line 31 of file Si5351C_wxgui.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/Si5351C/Si5351C_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/Si5351C/Si5351C_wxgui.cpp