LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/ModulesC.cpp File Reference
ModulesC.cpp File Reference
#include "TypeHelpers.hpp"
#include <SoapySDR/Modules.h>
#include <SoapySDR/Modules.hpp>
#include <cstdlib>
#include <cstring>
Functions
const char * SoapySDR_getRootPath (void)
Query the root installation path.
char ** SoapySDR_listSearchPaths (size_t *length)
char ** SoapySDR_listModules (size_t *length)
char ** SoapySDR_listModulesPath (const char *path, size_t *length)
char * SoapySDR_loadModule (const char *path)
SoapySDRKwargs SoapySDR_getLoaderResult (const char *path)
char * SoapySDR_getModuleVersion (const char *path)
char * SoapySDR_unloadModule (const char *path)
void SoapySDR_loadModules (void)
Function Documentation
SoapySDRKwargs SoapySDR_getLoaderResult (const char * path)
List all registration loader errors for a given module path. The resulting dictionary contains all registry entry names provided by the specified module. The value of each entry is an error message string or empty on successful load.
Parameters
path the path to a specific module file
Returns
a dictionary of registry names to error messages
Definition at line 38 of file ModulesC.cpp.
References SoapySDR::getLoaderResult, and toKwargs().
char* SoapySDR_getModuleVersion (const char * path)
Get a version string for the specified module. Modules may optionally provide version strings.
Parameters
path the path to a specific module file
Returns
a version string or empty if no version provided
Definition at line 43 of file ModulesC.cpp.
References SoapySDR::getModuleVersion.
const char* SoapySDR_getRootPath (void)
Query the root installation path.
Definition at line 12 of file ModulesC.cpp.
References SoapySDR::getRootPath, and string().
char** SoapySDR_listModules (size_t * length)
List all modules found in default path. The result is an array of strings owned by the caller.
Parameters
[out] length the number of elements in the result.
Returns
a list of file paths to loadable modules
Definition at line 23 of file ModulesC.cpp.
References SoapySDR::listModules, and toStrArray().
char** SoapySDR_listModulesPath (const char * path, size_t * length)
List all modules found in the given path. The result is an array of strings owned by the caller.
Parameters
path a directory on the system
[out] length the number of elements in the result.
Returns
a list of file paths to loadable modules
Definition at line 28 of file ModulesC.cpp.
References SoapySDR::listModules, and toStrArray().
char** SoapySDR_listSearchPaths (size_t * length)
The list of paths automatically searched by loadModules().
Parameters
[out] length the number of elements in the result.
Returns
a list of automatically searched file paths
Definition at line 18 of file ModulesC.cpp.
References SoapySDR::listSearchPaths, and toStrArray().
char* SoapySDR_loadModule (const char * path)
Load a single module given its file system path. The caller must free the result error string.
Parameters
path the path to a specific module file
Returns
an error message, empty on success
Definition at line 33 of file ModulesC.cpp.
References SoapySDR::loadModule.
void SoapySDR_loadModules (void)
Load the support modules installed on this system. This call will only actually perform the load once. Subsequent calls are a NOP.
Definition at line 53 of file ModulesC.cpp.
References SoapySDR::loadModules.
char* SoapySDR_unloadModule (const char * path)
Unload a module that was loaded with loadModule(). The caller must free the result error string.
Parameters
path the path to a specific module file
Returns
an error message, empty on success
Definition at line 48 of file ModulesC.cpp.
References SoapySDR::unloadModule.