LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/examples/dualRXTX.cpp File Reference
dualRXTX.cpp File Reference
Dual channel RX/TX example.
#include "lime/LimeSuite.h"
#include <iostream>
#include <chrono>
Functions
int error ()
int main (int argc, char **argv)
Variables
lms_device_t * device = NULL
Detailed Description
Dual channel RX/TX example.
Author
Lime Microsystems (www.limemicro.com)
Definition in file dualRXTX.cpp.
Function Documentation
int error ()
Definition at line 18 of file dualRXTX.cpp.
References device, and LMS_Close().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 25 of file dualRXTX.cpp.
References lms_stream_t::channel, chCount, lms_stream_t::dataFmt, device, error(), lms_stream_status_t::fifoFilledCount, lms_stream_t::fifoSize, lms_stream_status_t::fifoSize, GNUPlotPipe::flush(), lms_stream_meta_t::flushPartialPacket, i, lms_stream_t::isTx, lms_stream_status_t::linkRate, list, LMS_CH_RX, LMS_CH_TX, LMS_Close(), LMS_DestroyStream(), LMS_EnableChannel(), lms_stream_t::LMS_FMT_I12, LMS_GetDeviceList(), LMS_GetNumChannels(), LMS_GetStreamStatus(), LMS_Init(), LMS_Open(), LMS_RecvStream(), LMS_SendStream(), LMS_SetLOFrequency(), LMS_SetNormalizedGain(), LMS_SetSampleRate(), LMS_SetTestSignal(), LMS_SetupStream(), LMS_StartStream(), LMS_StopStream(), LMS_TESTSIG_NCODIV4, LMS_TESTSIG_NCODIV8F, status, t1, t2, lms_stream_t::throughputVsLatency, lms_stream_meta_t::timestamp, lms_stream_meta_t::waitForTimestamp, GNUPlotPipe::write(), and GNUPlotPipe::writef().
Variable Documentation
lms_device_t* device = NULL
Definition at line 16 of file dualRXTX.cpp.
Referenced by error(), and main().