LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/LimeUtil/LimeUtilTiming.cpp File Reference
LimeUtilTiming.cpp File Reference
#include <VersionInfo.h>
#include <ConnectionRegistry.h>
#include <IConnection.h>
#include <LMS7002M.h>
#include <iostream>
#include <chrono>
Classes
struct LMS7002M_quiet
Functions
int deviceTestTiming (const std::string &argStr)
Function Documentation
int deviceTestTiming (const std::string & argStr)
Definition at line 25 of file LimeUtilTiming.cpp.
References lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::freeConnection(), i, lime::ConnectionRegistry::makeConnection(), lime::LMS7002M::SetConnection(), t1, and lime::LMS7002M::Tx.
Referenced by main().