LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/examples/basicTX.cpp File Reference
basicTX.cpp File Reference
minimal TX example
#include <iostream>
#include <chrono>
#include <math.h>
#include "lime/LimeSuite.h"
Functions
int error ()
int main (int argc, char **argv)
Variables
lms_device_t * device = NULL
Detailed Description
minimal TX example
Author
Lime Microsystems (www.limemicro.com)
Definition in file basicTX.cpp.
Function Documentation
int error ()
Definition at line 16 of file basicTX.cpp.
References device, and LMS_Close().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 23 of file basicTX.cpp.
References lms_stream_t::channel, lms_stream_t::dataFmt, device, error(), lms_stream_t::fifoSize, frequency, i, lms_stream_t::isTx, lms_stream_status_t::linkRate, list, LMS_CH_TX, LMS_Close(), LMS_DestroyStream(), LMS_EnableChannel(), lms_stream_t::LMS_FMT_F32, LMS_GetDeviceList(), LMS_GetStreamStatus(), LMS_Init(), LMS_Open(), LMS_PATH_TX1, LMS_SendStream(), LMS_SetAntenna(), LMS_SetLOFrequency(), LMS_SetNormalizedGain(), LMS_SetSampleRate(), LMS_SetupStream(), LMS_StartStream(), LMS_StopStream(), status, t1, t2, and lms_stream_t::throughputVsLatency.
Variable Documentation
lms_device_t* device = NULL
Definition at line 14 of file basicTX.cpp.
Referenced by error(), and main().