LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionEVB7COM/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionEVB7COM/CMakeLists.txt File Reference
Functions
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ConnectionEVB7COM) set(CONNECTION_EVB7_COM_SOURCES $
Function Documentation
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ ConnectionEVB7COM)
Definition at line 5 of file CMakeLists.txt.
References add_feature_info(), ENABLE_EVB7COM, endif(), include(), and target_sources().