LimeSuite-UML: lime::ConnectionEVB7COM Class Reference
lime::ConnectionEVB7COM Class Reference
#include <ConnectionEVB7COM.h>
Public Member Functions
ConnectionEVB7COM (const char *comName, int baudrate)
~ConnectionEVB7COM (void)
bool IsOpen (void)
Public Member Functions inherited from lime::LMS64CProtocol
LMS64CProtocol (void)
virtual ~LMS64CProtocol (void)
virtual DeviceInfo GetDeviceInfo (void)
int DeviceReset (int ind=0)
DeviceReset implemented by LMS64C.
int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size) override
TransactSPI implemented by LMS64C.
int WriteI2C (const int addr, const std::string &data)
WriteI2C implemented by LMS64C.
int ReadI2C (const int addr, const size_t numBytes, std::string &data)
ReadI2C implemented by LMS64C.
int WriteRegisters (const uint32_t *addrs, const uint32_t *data, const size_t size)
WriteRegisters (BRDSPI) implemented by LMS64C.
int ReadRegisters (const uint32_t *addrs, uint32_t *data, const size_t size)
ReadRegisters (BRDSPI) implemented by LMS64C.
virtual int TransferPacket (GenericPacket &pkt)
Transfers data between packet and connected device.
LMSinfo GetInfo ()
Returns connected device information.
FPGAinfo GetFPGAInfo ()
Returns information from FPGA gateware.
void VersionCheck ()
int ProgramUpdate (const bool download, IConnection::ProgrammingCallback callback) override
virtual int ProgramWrite (const char *buffer, const size_t length, const int programmingMode, const int device, ProgrammingCallback callback=nullptr)
Uploads program to selected device.
virtual int CustomParameterRead (const uint8_t *ids, double *values, const size_t count, std::string *units) override
Returns value of custom on board control.
virtual int CustomParameterWrite (const uint8_t *ids, const double *values, const size_t count, const std::string &units) override
Sets custom on board control to given value units.
virtual int GPIOWrite (const uint8_t *buffer, const size_t bufLength) override
Writes GPIO values to device.
virtual int GPIORead (uint8_t *buffer, const size_t bufLength) override
Reads GPIO values from device.
virtual int GPIODirWrite (const uint8_t *buffer, const size_t bufLength) override
Write GPIO direction control values to device.
virtual int GPIODirRead (uint8_t *buffer, const size_t bufLength) override
Read GPIO direction configuration from device.
int ProgramMCU (const uint8_t *buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback) override
Uploads program to MCU.
int WriteLMS7002MSPI (const uint32_t *writeData, size_t size, unsigned periphID=0) override
int ReadLMS7002MSPI (const uint32_t *writeData, uint32_t *readData, size_t size, unsigned periphID=0) override
Public Member Functions inherited from lime::IConnection
IConnection (void)
IConnection constructor.
virtual ~IConnection (void)
IConnection destructor.
const ConnectionHandle & GetHandle (void) const
Get the connection handle that was used to create this connection.
virtual int ResetStreamBuffers ()
Read raw stream data from device streaming port.
virtual int GetBuffersCount () const
virtual int CheckStreamSize (int size) const
virtual int ReceiveData (char *buffer, int length, int epIndex, int timeout=100)
virtual int SendData (const char *buffer, int length, int epIndex, int timeout=100)
virtual int BeginDataSending (const char *buffer, uint32_t length, int ep)
virtual bool WaitForSending (int contextHandle, uint32_t timeout_ms)
virtual int FinishDataSending (const char *buffer, uint32_t length, int contextHandle)
virtual void AbortSending (int ep)
virtual int BeginDataReading (char *buffer, uint32_t length, int ep)
virtual bool WaitForReading (int contextHandle, unsigned int timeout_ms)
virtual int FinishDataReading (char *buffer, uint32_t length, int contextHandle)
virtual void AbortReading (int ep)
int WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
template<typename ReadType >
int ReadRegister (const uint32_t addr, ReadType &data)
Read a single device register.
void SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Private Member Functions
int Open (const char *comName, int baudrate)
void Close (void)
eConnectionType GetType (void)
implement in base class
int Write (const unsigned char *buffer, int length, int timeout_ms=100)
Sends data through COM port.
int Read (unsigned char *buffer, int length, int timeout_ms=100)
Reads data from COM port.
Private Attributes
HANDLE hComm
COMMTIMEOUTS m_ctmoNew
COMMTIMEOUTS m_ctmoOld
OVERLAPPED m_osROverlap
OVERLAPPED m_osWOverlap
DCB m_dcbCommPort
Additional Inherited Members
Public Types inherited from lime::LMS64CProtocol
enum eConnectionType {
CONNECTION_UNDEFINED = -1, COM_PORT = 0, USB_PORT = 1, SPI_PORT = 2,
PCIE_PORT = 3, CONNECTION_TYPES_COUNT
}
Supported connection types.
enum eLMS_PROTOCOL { LMS_PROTOCOL_UNDEFINED = 0, LMS_PROTOCOL_DIGIC, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA }
enum ProgramWriteTarget { HPM, FX3, FPGA, PROGRAM_WRITE_TARGET_COUNT }
Public Types inherited from lime::IConnection
enum MCU_PROG_MODE { RESET = 0, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM }
typedef std::function< bool(int bsent, int btotal, const char *progressMsg)> ProgrammingCallback
Protected Attributes inherited from lime::IConnection
std::function< void(bool, const unsigned char *, const unsigned int)> callback_logData
Detailed Description
Definition at line 20 of file ConnectionEVB7COM.h.
Constructor & Destructor Documentation
ConnectionEVB7COM::ConnectionEVB7COM (const char * comName, int baudrate)
Definition at line 31 of file ConnectionEVB7COM.cpp.
References Close(), lime::error(), hComm, and Open().
ConnectionEVB7COM::~ConnectionEVB7COM (void)
Definition at line 46 of file ConnectionEVB7COM.cpp.
References Close().
Member Function Documentation
void ConnectionEVB7COM::Close (void) private
Definition at line 51 of file ConnectionEVB7COM.cpp.
References hComm, and m_ctmoOld.
Referenced by ConnectionEVB7COM(), and ~ConnectionEVB7COM().
eConnectionType lime::ConnectionEVB7COM::GetType (void) inline private virtual
implement in base class
Implements lime::LMS64CProtocol.
Definition at line 35 of file ConnectionEVB7COM.h.
References buffer, lime::LMS64CProtocol::COM_PORT, Read(), timeout_ms, and Write().
bool ConnectionEVB7COM::IsOpen (void) virtual
Is this connection open? The constructor should attempt to connect but may fail, or the connection may go down at a later time.
Returns
true when the connection is available
Reimplemented from lime::IConnection.
Definition at line 69 of file ConnectionEVB7COM.cpp.
References hComm.
Referenced by lime::ConnectionSTREAM_UNITE::ConnectionSTREAM_UNITE().
int ConnectionEVB7COM::Open (const char * comName, int baudrate) private
Definition at line 81 of file ConnectionEVB7COM.cpp.
References hComm, m_ctmoNew, m_ctmoOld, m_dcbCommPort, m_osROverlap, m_osWOverlap, lime::ReportError(), and string().
Referenced by ConnectionEVB7COM().
int ConnectionEVB7COM::Read (unsigned char * buffer, int length, int timeout_ms = 100) private virtual
Reads data from COM port.
Parameters
buffer pointer to data buffer for receiving
length number of bytes to read
timeout_ms timeout limit for operation in milliseconds
Returns
Number of bytes received
Implements lime::LMS64CProtocol.
Definition at line 278 of file ConnectionEVB7COM.cpp.
References COM_BUFFER_LENGTH, COM_RETRY_INTERVAL, COM_TOTAL_TIMEOUT, hComm, i, read(), and status.
Referenced by GetType().
int ConnectionEVB7COM::Write (const unsigned char * buffer, int length, int timeout_ms = 100) private virtual
Sends data through COM port.
Parameters
buffer data buffer to send
length size of data buffer
timeout_ms timeout limit for operation in milliseconds
Returns
Number of bytes sent
Implements lime::LMS64CProtocol.
Definition at line 223 of file ConnectionEVB7COM.cpp.
References COM_RETRY_INTERVAL, COM_TOTAL_TIMEOUT, hComm, i, m_osWOverlap, lime::ReportError(), and status.
Referenced by GetType().
Member Data Documentation
HANDLE lime::ConnectionEVB7COM::hComm private
Definition at line 44 of file ConnectionEVB7COM.h.
Referenced by Close(), ConnectionEVB7COM(), IsOpen(), Open(), Read(), and Write().
COMMTIMEOUTS lime::ConnectionEVB7COM::m_ctmoNew private
Definition at line 45 of file ConnectionEVB7COM.h.
Referenced by Open().
COMMTIMEOUTS lime::ConnectionEVB7COM::m_ctmoOld private
Definition at line 46 of file ConnectionEVB7COM.h.
Referenced by Close(), and Open().
DCB lime::ConnectionEVB7COM::m_dcbCommPort private
Definition at line 49 of file ConnectionEVB7COM.h.
Referenced by Open().
OVERLAPPED lime::ConnectionEVB7COM::m_osROverlap private
Definition at line 47 of file ConnectionEVB7COM.h.
Referenced by Open().
OVERLAPPED lime::ConnectionEVB7COM::m_osWOverlap private
Definition at line 48 of file ConnectionEVB7COM.h.
Referenced by Open(), and Write().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionEVB7COM/ConnectionEVB7COM.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionEVB7COM/ConnectionEVB7COM.cpp