LimeSuite-UML: lms7002_pnlR3_view Class Reference
lms7002_pnlR3_view Class Reference
#include <lms7002_pnlR3.h>
Public Member Functions
lms7002_pnlR3_view (wxWindow *parent)
lms7002_pnlR3_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~lms7002_pnlR3_view ()
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Protected Member Functions
void ParameterChangeHandler (wxSpinEvent &event)
void ParameterChangeHandler (wxCommandEvent &event)
void OnRSSICMPCFGChanged (wxCommandEvent &event)
void OnDCCMPCFGChanged (wxCommandEvent &event)
void OnReadRSSICMP (wxCommandEvent &event)
void OnReadDCCMP (wxCommandEvent &event)
void OnCalibrateAnalogRSSI (wxCommandEvent &event)
void OnWriteRxDC (wxCommandEvent &event)
void OnWriteTxDC (wxCommandEvent &event)
void OnDCCMPCFGRead ()
void OnReadDC (wxCommandEvent &event)
void UpdateGUISlow ()
void ParameterChangeHandlerCMPRead (wxCommandEvent &event)
void MCU_RunProcedure (uint8_t id)
uint8_t MCU_WaitForStatus (uint16_t timeout_ms)
Protected Attributes
wxComboBox * cmbISINK_SPIBUFF
wxButton * btnReadADC
wxStaticText * dccal_statuses [8]
wxStaticText * dccal_cmpstatuses [8]
wxCheckBox * dccal_cmpcfg [8]
wxCheckBox * dccal_start [8]
wxStaticText * rssi_vals [2]
wxStaticText * pdet_vals [2]
wxStaticText * tref_val
wxStaticText * tvptat_val
wxStaticText * rssidc_cmpstatus
NumericSlider * cmbRSSIDC_HYSCMP
wxCheckBox * chkRSSI_PD
NumericSlider * spinDCO1
NumericSlider * spinDCO2
wxComboBox * cmbRSEL
std::vector< NumericSlider * > cmbDCControlsRx
std::vector< NumericSlider * > cmbDCControlsTx
wxStaticText * rssiCMPSTATUS [6]
wxCheckBox * rssiCMPCFG [6]
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Detailed Description
Definition at line 17 of file lms7002_pnlR3.h.
Constructor & Destructor Documentation
lms7002_pnlR3_view::lms7002_pnlR3_view (wxWindow * parent)
Definition at line 17 of file lms7002_pnlR3.cpp.
lms7002_pnlR3_view::lms7002_pnlR3_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 23 of file lms7002_pnlR3.cpp.
References chkRSSI_PD, cmbDCControlsRx, cmbDCControlsTx, cmbRSEL, cmbRSSIDC_HYSCMP, dccal_cmpstatuses, dccal_statuses, i, LMS7_DAC_CLKDIV, LMS7_DC_RXAI, LMS7_DC_RXAQ, LMS7_DC_RXBI, LMS7_DC_RXBQ, LMS7_DC_RXCDIV, LMS7_DC_TXAI, LMS7_DC_TXAQ, LMS7_DC_TXBI, LMS7_DC_TXBQ, LMS7_DC_TXCDIV, LMS7_DCCAL_CALSTATUS_RXAI, LMS7_DCCAL_CALSTATUS_RXAQ, LMS7_DCCAL_CALSTATUS_RXBI, LMS7_DCCAL_CALSTATUS_RXBQ, LMS7_DCCAL_CALSTATUS_TXAQ, LMS7_DCCAL_CALSTATUS_TXBI, LMS7_DCCAL_CALSTATUS_TXBQ, LMS7_DCCAL_CMPCFG_RXAI, LMS7_DCCAL_CMPCFG_RXAQ, LMS7_DCCAL_CMPCFG_RXBI, LMS7_DCCAL_CMPCFG_RXBQ, LMS7_DCCAL_CMPCFG_TXAI, LMS7_DCCAL_CMPCFG_TXAQ, LMS7_DCCAL_CMPCFG_TXBI, LMS7_DCCAL_CMPCFG_TXBQ, LMS7_DCCAL_CMPSTATUS_RXAI, LMS7_DCCAL_CMPSTATUS_RXAQ, LMS7_DCCAL_CMPSTATUS_RXBI, LMS7_DCCAL_CMPSTATUS_RXBQ, LMS7_DCCAL_CMPSTATUS_TXAI, LMS7_DCCAL_CMPSTATUS_TXAQ, LMS7_DCCAL_CMPSTATUS_TXBI, LMS7_DCCAL_CMPSTATUS_TXBQ, LMS7_DCCAL_START_RXAI, LMS7_DCCAL_START_RXAQ, LMS7_DCCAL_START_RXBI, LMS7_DCCAL_START_RXBQ, LMS7_DCCAL_START_TXAI, LMS7_DCCAL_START_TXAQ, LMS7_DCCAL_START_TXBI, LMS7_DCCAL_START_TXBQ, LMS7_DCRD_RXAI, LMS7_DCRD_RXAQ, LMS7_DCRD_RXBI, LMS7_DCRD_RXBQ, LMS7_DCRD_TXAI, LMS7_DCRD_TXAQ, LMS7_DCRD_TXBI, LMS7_DCRD_TXBQ, LMS7_DCWR_RXAI, LMS7_DCWR_RXAQ, LMS7_DCWR_RXBI, LMS7_DCWR_RXBQ, LMS7_DCWR_TXAI, LMS7_DCWR_TXAQ, LMS7_DCWR_TXBI, LMS7_DCWR_TXBQ, LMS7_HYSCMP_RXA, LMS7_HYSCMP_RXB, LMS7_HYSCMP_TXA, LMS7_HYSCMP_TXB, LMS7_INTADC_CMPCFG_PDET1, LMS7_INTADC_CMPCFG_PDET2, LMS7_INTADC_CMPCFG_RSSI1, LMS7_INTADC_CMPCFG_RSSI2, LMS7_INTADC_CMPCFG_TEMPREF, LMS7_INTADC_CMPCFG_TEMPVPTAT, LMS7_INTADC_CMPSTATUS_PDET1, LMS7_INTADC_CMPSTATUS_PDET2, LMS7_INTADC_CMPSTATUS_RSSI1, LMS7_INTADC_CMPSTATUS_RSSI2, LMS7_INTADC_CMPSTATUS_TEMPREF, LMS7_INTADC_CMPSTATUS_TEMPVPTAT, LMS7_PD_DCCMP_RXA, LMS7_PD_DCCMP_RXB, LMS7_PD_DCCMP_TXA, LMS7_PD_DCCMP_TXB, LMS7_PD_DCDAC_RXA, LMS7_PD_DCDAC_RXB, LMS7_PD_DCDAC_TXA, LMS7_PD_DCDAC_TXB, LMS7_RSSI_BIAS, LMS7_RSSI_DAC_VAL, LMS7_RSSI_HYSCMP, LMS7_RSSI_PD, LMS7_RSSI_PDET1_VAL, LMS7_RSSI_PDET2_VAL, LMS7_RSSI_RSSI1_VAL, LMS7_RSSI_RSSI2_VAL, LMS7_RSSI_RSSIMODE, LMS7_RSSI_TREF_VAL, LMS7_RSSI_TVPTAT_VAL, LMS7_RSSIDC_DCO1, LMS7_RSSIDC_DCO2, LMS7_RSSIDC_HYSCMP, LMS7_RSSIDC_PD, LMS7_RSSIDC_RSEL, lmsControl, OnCalibrateAnalogRSSI(), OnReadDC(), OnReadDCCMP(), OnReadRSSICMP(), OnWriteRxDC(), OnWriteTxDC(), ParameterChangeHandler(), ParameterChangeHandlerCMPRead(), pdet_vals, rssi_vals, rssiCMPCFG, rssiCMPSTATUS, rssidc_cmpstatus, spinDCO1, spinDCO2, tref_val, tvptat_val, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
lms7002_pnlR3_view::~lms7002_pnlR3_view ()
Definition at line 364 of file lms7002_pnlR3.cpp.
Member Function Documentation
void lms7002_pnlR3_view::Initialize (lms_device_t * pControl)
Definition at line 368 of file lms7002_pnlR3.cpp.
References LMS7param, LMS_ReadParam(), lmsControl, and MASK.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlR3_view::MCU_RunProcedure (uint8_t id) protected
Definition at line 414 of file lms7002_pnlR3.cpp.
References i, LMS_ReadLMSReg(), LMS_WriteLMSReg(), lmsControl, and temp.
Referenced by ParameterChangeHandler(), and UpdateGUISlow().
uint8_t lms7002_pnlR3_view::MCU_WaitForStatus (uint16_t timeout_ms) protected
Definition at line 432 of file lms7002_pnlR3.cpp.
References LMS_ReadLMSReg(), LMS_WriteLMSReg(), lmsControl, t1, and t2.
Referenced by ParameterChangeHandler(), and UpdateGUISlow().
void lms7002_pnlR3_view::OnCalibrateAnalogRSSI (wxCommandEvent & event) protected
Definition at line 620 of file lms7002_pnlR3.cpp.
References lime::LMS7002M::CalibrateAnalogRSSI_DC_Offset(), lms(), lmsControl, and UpdateGUI().
Referenced by lms7002_pnlR3_view().
void lms7002_pnlR3_view::OnDCCMPCFGChanged (wxCommandEvent & event) protected
void lms7002_pnlR3_view::OnDCCMPCFGRead () protected
Definition at line 516 of file lms7002_pnlR3.cpp.
References UpdateGUI().
void lms7002_pnlR3_view::OnReadDC (wxCommandEvent & event) protected
Definition at line 587 of file lms7002_pnlR3.cpp.
References UpdateGUI().
Referenced by lms7002_pnlR3_view().
void lms7002_pnlR3_view::OnReadDCCMP (wxCommandEvent & event) protected
Definition at line 526 of file lms7002_pnlR3.cpp.
References UpdateGUI().
Referenced by lms7002_pnlR3_view().
void lms7002_pnlR3_view::OnReadRSSICMP (wxCommandEvent & event) protected
Definition at line 521 of file lms7002_pnlR3.cpp.
References UpdateGUI().
Referenced by lms7002_pnlR3_view().
void lms7002_pnlR3_view::OnRSSICMPCFGChanged (wxCommandEvent & event) protected
void lms7002_pnlR3_view::OnWriteRxDC (wxCommandEvent & event) protected
Definition at line 559 of file lms7002_pnlR3.cpp.
References LMS7Parameter::address, LMS_ReadLMSReg(), LMS_WriteLMSReg(), lmsControl, and wndId2Enum.
Referenced by lms7002_pnlR3_view().
void lms7002_pnlR3_view::OnWriteTxDC (wxCommandEvent & event) protected
Definition at line 531 of file lms7002_pnlR3.cpp.
References LMS7Parameter::address, LMS_ReadLMSReg(), LMS_WriteLMSReg(), lmsControl, and wndId2Enum.
Referenced by lms7002_pnlR3_view().
void lms7002_pnlR3_view::ParameterChangeHandler (wxSpinEvent & event) protected
Definition at line 507 of file lms7002_pnlR3.cpp.
Referenced by lms7002_pnlR3_view(), and ParameterChangeHandlerCMPRead().
void lms7002_pnlR3_view::ParameterChangeHandler (wxCommandEvent & event) protected
Definition at line 452 of file lms7002_pnlR3.cpp.
References LMS7Parameter::address, LMS_Program(), LMS_ReadLMSReg(), LMS_WriteLMSReg(), LMS_WriteParam(), lmsControl, LMS7Parameter::lsb, MCU_FUNCTION_GET_PROGRAM_ID, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, mcu_program_lms7_dc_iq_calibration_bin, MCU_RunProcedure(), MCU_WaitForStatus(), lime::program_mode::mcuRAM, LMS7Parameter::msb, and wndId2Enum.
void lms7002_pnlR3_view::ParameterChangeHandlerCMPRead (wxCommandEvent & event) protected
Definition at line 592 of file lms7002_pnlR3.cpp.
References ParameterChangeHandler(), and UpdateGUISlow().
Referenced by lms7002_pnlR3_view().
void lms7002_pnlR3_view::UpdateGUI ()
Definition at line 377 of file lms7002_pnlR3.cpp.
References cmbDCControlsRx, cmbDCControlsTx, i, LMS_ReadParam(), LMS_Synchronize(), LMS_WriteLMSReg(), lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), UpdateGUISlow(), and wndId2Enum.
Referenced by OnCalibrateAnalogRSSI(), OnDCCMPCFGRead(), OnReadDC(), OnReadDCCMP(), OnReadRSSICMP(), and lms7002_mainPanel::UpdateVisiblePanel().
void lms7002_pnlR3_view::UpdateGUISlow () protected
Definition at line 598 of file lms7002_pnlR3.cpp.
References chkRSSI_PD, cmbRSEL, cmbRSSIDC_HYSCMP, i, LMS_ReadLMSReg(), LMS_WriteLMSReg(), lmsControl, MCU_RunProcedure(), MCU_WaitForStatus(), rssidc_cmpstatus, NumericSlider::SetValue(), spinDCO1, and spinDCO2.
Referenced by ParameterChangeHandlerCMPRead(), and UpdateGUI().
Member Data Documentation
wxButton* lms7002_pnlR3_view::btnReadADC protected
Definition at line 21 of file lms7002_pnlR3.h.
wxCheckBox* lms7002_pnlR3_view::chkRSSI_PD protected
Definition at line 32 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUISlow().
std::vector<NumericSlider*> lms7002_pnlR3_view::cmbDCControlsRx protected
Definition at line 36 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUI().
std::vector<NumericSlider*> lms7002_pnlR3_view::cmbDCControlsTx protected
Definition at line 37 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUI().
wxComboBox* lms7002_pnlR3_view::cmbISINK_SPIBUFF protected
Definition at line 20 of file lms7002_pnlR3.h.
wxComboBox* lms7002_pnlR3_view::cmbRSEL protected
Definition at line 35 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUISlow().
NumericSlider* lms7002_pnlR3_view::cmbRSSIDC_HYSCMP protected
Definition at line 31 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUISlow().
wxCheckBox* lms7002_pnlR3_view::dccal_cmpcfg[8] protected
Definition at line 24 of file lms7002_pnlR3.h.
wxStaticText* lms7002_pnlR3_view::dccal_cmpstatuses[8] protected
Definition at line 23 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
wxCheckBox* lms7002_pnlR3_view::dccal_start[8] protected
Definition at line 25 of file lms7002_pnlR3.h.
wxStaticText* lms7002_pnlR3_view::dccal_statuses[8] protected
Definition at line 22 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
lms_device_t* lms7002_pnlR3_view::lmsControl protected
Definition at line 66 of file lms7002_pnlR3.h.
Referenced by Initialize(), lms7002_pnlR3_view(), MCU_RunProcedure(), MCU_WaitForStatus(), OnCalibrateAnalogRSSI(), OnWriteRxDC(), OnWriteTxDC(), ParameterChangeHandler(), UpdateGUI(), and UpdateGUISlow().
wxStaticText* lms7002_pnlR3_view::pdet_vals[2] protected
Definition at line 27 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
wxStaticText* lms7002_pnlR3_view::rssi_vals[2] protected
Definition at line 26 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
wxCheckBox* lms7002_pnlR3_view::rssiCMPCFG[6] protected
Definition at line 40 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
wxStaticText* lms7002_pnlR3_view::rssiCMPSTATUS[6] protected
Definition at line 39 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
wxStaticText* lms7002_pnlR3_view::rssidc_cmpstatus protected
Definition at line 30 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUISlow().
NumericSlider* lms7002_pnlR3_view::spinDCO1 protected
Definition at line 33 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUISlow().
NumericSlider* lms7002_pnlR3_view::spinDCO2 protected
Definition at line 34 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), and UpdateGUISlow().
wxStaticText* lms7002_pnlR3_view::tref_val protected
Definition at line 28 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
wxStaticText* lms7002_pnlR3_view::tvptat_val protected
Definition at line 29 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlR3_view::wndId2Enum protected
Definition at line 67 of file lms7002_pnlR3.h.
Referenced by lms7002_pnlR3_view(), OnWriteRxDC(), OnWriteTxDC(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlR3.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlR3.cpp