LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/API/lms7_api.cpp File Reference
lms7_api.cpp File Reference
#include "IConnection.h"
#include "ConnectionRegistry.h"
#include "lime/LimeSuite.h"
#include "lms7_device.h"
#include "errno.h"
#include <cmath>
#include "VersionInfo.h"
#include <assert.h>
#include "Logger.h"
#include "LMS64CProtocol.h"
#include "Streamer.h"
Functions
API_EXPORT int CALL_CONV LMS_GetDeviceList (lms_info_str_t *dev_list)
API_EXPORT int CALL_CONV LMS_Open (lms_device_t **device, const lms_info_str_t info, void *args)
API_EXPORT int CALL_CONV LMS_Close (lms_device_t *device)
API_EXPORT int CALL_CONV LMS_Disconnect (lms_device_t *device)
API_EXPORT bool CALL_CONV LMS_IsOpen (lms_device_t *device, int port)
API_EXPORT int CALL_CONV LMS_Reset (lms_device_t *device)
API_EXPORT int CALL_CONV LMS_EnableChannel (lms_device_t *device, bool dir_tx, size_t chan, bool enabled)
API_EXPORT int CALL_CONV LMS_SetSampleRate (lms_device_t *device, float_type rate, size_t oversample)
API_EXPORT int CALL_CONV LMS_SetSampleRateDir (lms_device_t *device, bool dir_tx, float_type rate, size_t oversample)
API_EXPORT int CALL_CONV LMS_GetSampleRate (lms_device_t *device, bool dir_tx, size_t chan, float_type *host_Hz, float_type *rf_Hz)
API_EXPORT int CALL_CONV LMS_GetSampleRateRange (lms_device_t *device, bool dir_tx, lms_range_t *range)
API_EXPORT int CALL_CONV LMS_Init (lms_device_t *device)
API_EXPORT int CALL_CONV LMS_ReadCustomBoardParam (lms_device_t *device, uint8_t param_id, float_type *val, lms_name_t units)
API_EXPORT int CALL_CONV LMS_WriteCustomBoardParam (lms_device_t *device, uint8_t param_id, float_type val, const lms_name_t units)
API_EXPORT int CALL_CONV LMS_VCTCXOWrite (lms_device_t *device, uint16_t val)
API_EXPORT int CALL_CONV LMS_VCTCXORead (lms_device_t *device, uint16_t *val)
API_EXPORT int CALL_CONV LMS_GetClockFreq (lms_device_t *device, size_t clk_id, float_type *freq)
API_EXPORT int CALL_CONV LMS_SetClockFreq (lms_device_t *device, size_t clk_id, float_type freq)
API_EXPORT int CALL_CONV LMS_Synchronize (lms_device_t *dev, bool toChip)
API_EXPORT int CALL_CONV LMS_GPIORead (lms_device_t *dev, uint8_t *buffer, size_t len)
API_EXPORT int CALL_CONV LMS_GPIOWrite (lms_device_t *dev, const uint8_t *buffer, size_t len)
API_EXPORT int CALL_CONV LMS_GPIODirRead (lms_device_t *dev, uint8_t *buffer, size_t len)
API_EXPORT int CALL_CONV LMS_GPIODirWrite (lms_device_t *dev, const uint8_t *buffer, size_t len)
API_EXPORT int CALL_CONV LMS_EnableCalibCache (lms_device_t *dev, bool enable)
API_EXPORT int CALL_CONV LMS_GetChipTemperature (lms_device_t *dev, size_t ind, float_type *temp)
API_EXPORT int CALL_CONV LMS_GetNumChannels (lms_device_t *device, bool dir_tx)
API_EXPORT int CALL_CONV LMS_SetLOFrequency (lms_device_t *device, bool dir_tx, size_t chan, float_type frequency)
API_EXPORT int CALL_CONV LMS_GetLOFrequency (lms_device_t *device, bool dir_tx, size_t chan, float_type *frequency)
API_EXPORT int CALL_CONV LMS_GetLOFrequencyRange (lms_device_t *device, bool dir_tx, lms_range_t *range)
API_EXPORT int CALL_CONV LMS_GetAntennaList (lms_device_t *device, bool dir_tx, size_t chan, lms_name_t *list)
API_EXPORT int CALL_CONV LMS_SetAntenna (lms_device_t *device, bool dir_tx, size_t chan, size_t path)
API_EXPORT int CALL_CONV LMS_GetAntenna (lms_device_t *device, bool dir_tx, size_t chan)
API_EXPORT int CALL_CONV LMS_GetAntennaBW (lms_device_t *device, bool dir_tx, size_t chan, size_t path, lms_range_t *range)
API_EXPORT int CALL_CONV LMS_SetLPFBW (lms_device_t *device, bool dir_tx, size_t chan, float_type bandwidth)
API_EXPORT int CALL_CONV LMS_GetLPFBW (lms_device_t *device, bool dir_tx, size_t chan, float_type *bandwidth)
API_EXPORT int CALL_CONV LMS_SetLPF (lms_device_t *device, bool dir_tx, size_t chan, bool enabled)
API_EXPORT int CALL_CONV LMS_SetGFIRLPF (lms_device_t *device, bool dir_tx, size_t chan, bool enabled, float_type bandwidth)
API_EXPORT int CALL_CONV LMS_GetLPFBWRange (lms_device_t *device, bool dir_tx, lms_range_t *range)
API_EXPORT int CALL_CONV LMS_SetNormalizedGain (lms_device_t *device, bool dir_tx, size_t chan, float_type gain)
API_EXPORT int CALL_CONV LMS_SetGaindB (lms_device_t *device, bool dir_tx, size_t chan, unsigned gain)
API_EXPORT int CALL_CONV LMS_GetNormalizedGain (lms_device_t *device, bool dir_tx, size_t chan, float_type *gain)
API_EXPORT int CALL_CONV LMS_GetGaindB (lms_device_t *device, bool dir_tx, size_t chan, unsigned *gain)
API_EXPORT int CALL_CONV LMS_Calibrate (lms_device_t *device, bool dir_tx, size_t chan, double bw, unsigned flags)
API_EXPORT int CALL_CONV LMS_LoadConfig (lms_device_t *device, const char *filename)
API_EXPORT int CALL_CONV LMS_SaveConfig (lms_device_t *device, const char *filename)
API_EXPORT int CALL_CONV LMS_SetTestSignal (lms_device_t *device, bool dir_tx, size_t chan, lms_testsig_t sig, int16_t dc_i, int16_t dc_q)
API_EXPORT int CALL_CONV LMS_GetTestSignal (lms_device_t *device, bool dir_tx, size_t chan, lms_testsig_t *sig)
API_EXPORT int CALL_CONV LMS_SetNCOFrequency (lms_device_t *device, bool dir_tx, size_t ch, const float_type *freq, float_type pho)
API_EXPORT int CALL_CONV LMS_GetNCOFrequency (lms_device_t *device, bool dir_tx, size_t chan, float_type *freq, float_type *pho)
API_EXPORT int CALL_CONV LMS_SetNCOPhase (lms_device_t *device, bool dir_tx, size_t ch, const float_type *phase, float_type fcw)
API_EXPORT int CALL_CONV LMS_GetNCOPhase (lms_device_t *device, bool dir_tx, size_t ch, float_type *phase, float_type *fcw)
API_EXPORT int CALL_CONV LMS_SetNCOIndex (lms_device_t *device, bool dir_tx, size_t chan, int ind, bool down)
API_EXPORT int CALL_CONV LMS_GetNCOIndex (lms_device_t *device, bool dir_tx, size_t chan)
API_EXPORT int CALL_CONV LMS_ReadLMSReg (lms_device_t *device, uint32_t address, uint16_t *val)
API_EXPORT int CALL_CONV LMS_WriteLMSReg (lms_device_t *device, uint32_t address, uint16_t val)
API_EXPORT int CALL_CONV LMS_ReadFPGAReg (lms_device_t *device, uint32_t address, uint16_t *val)
API_EXPORT int CALL_CONV LMS_WriteFPGAReg (lms_device_t *device, uint32_t address, uint16_t val)
API_EXPORT int CALL_CONV LMS_ReadParam (lms_device_t *device, struct LMS7Parameter param, uint16_t *val)
API_EXPORT int CALL_CONV LMS_WriteParam (lms_device_t *device, struct LMS7Parameter param, uint16_t val)
API_EXPORT int CALL_CONV LMS_SetGFIRCoeff (lms_device_t *device, bool dir_tx, size_t chan, lms_gfir_t filt, const float_type *coef, size_t count)
API_EXPORT int CALL_CONV LMS_GetGFIRCoeff (lms_device_t *device, bool dir_tx, size_t chan, lms_gfir_t filt, float_type *coef)
API_EXPORT int CALL_CONV LMS_SetGFIR (lms_device_t *device, bool dir_tx, size_t chan, lms_gfir_t filt, bool enabled)
API_EXPORT int CALL_CONV LMS_SetupStream (lms_device_t *device, lms_stream_t *stream)
API_EXPORT int CALL_CONV LMS_DestroyStream (lms_device_t *device, lms_stream_t *stream)
API_EXPORT int CALL_CONV LMS_StartStream (lms_stream_t *stream)
API_EXPORT int CALL_CONV LMS_StopStream (lms_stream_t *stream)
API_EXPORT int CALL_CONV LMS_RecvStream (lms_stream_t *stream, void *samples, size_t sample_count, lms_stream_meta_t *meta, unsigned timeout_ms)
API_EXPORT int CALL_CONV LMS_SendStream (lms_stream_t *stream, const void *samples, size_t sample_count, const lms_stream_meta_t *meta, unsigned timeout_ms)
API_EXPORT int CALL_CONV LMS_UploadWFM (lms_device_t *device, const void **samples, uint8_t chCount, size_t sample_count, int format)
API_EXPORT int CALL_CONV LMS_EnableTxWFM (lms_device_t *device, unsigned ch, bool active)
API_EXPORT int CALL_CONV LMS_GetStreamStatus (lms_stream_t *stream, lms_stream_status_t *status)
API_EXPORT const lms_dev_info_t *CALL_CONV LMS_GetDeviceInfo (lms_device_t *device)
API_EXPORT int CALL_CONV LMS_GetProgramModes (lms_device_t *device, lms_name_t *list)
API_EXPORT int CALL_CONV LMS_Program (lms_device_t *device, const char *data, size_t size, const lms_name_t mode, lms_prog_callback_t callback)
API_EXPORT const char *CALL_CONV LMS_GetLastErrorMessage (void)
API_EXPORT const char * LMS_GetLibraryVersion ()
static void APIMsgHandler (const lime::LogLevel level, const char *message)
API_EXPORT void LMS_RegisterLogHandler (LMS_LogHandler handler)
API_EXPORT int CALL_CONV LMS_TransferLMS64C (lms_device_t *dev, int cmd, uint8_t *data, size_t *len)
Variables
static LMS_LogHandler api_msg_handler
Function Documentation
static void APIMsgHandler (const lime::LogLevel level, const char * message) static
Definition at line 1362 of file lms7_api.cpp.
References api_msg_handler.
Referenced by LMS_RegisterLogHandler().
API_EXPORT int CALL_CONV LMS_Calibrate (lms_device_t * device, bool dir_tx, size_t chan, double bw, unsigned flags)
Definition at line 727 of file lms7_api.cpp.
References lime::LMS7_Device::Calibrate(), lime::LMS7_Device::GetNumChannels(), lms(), lime::LMS7_Device::ReadLMSReg(), and lime::ReportError().
Referenced by deviceCalSweep(), main(), lms7002_pnlCalibrations_view::OnbtnCalibrateAll(), lms7002_pnlCalibrations_view::OnbtnCalibrateRx(), and lms7002_pnlCalibrations_view::OnbtnCalibrateTx().
API_EXPORT int CALL_CONV LMS_Close (lms_device_t * device)
Definition at line 64 of file lms7_api.cpp.
References lime::error(), lms(), and LMS_SUCCESS.
Referenced by deviceCalSweep(), error(), FreeResources(), main(), and LMS7SuiteAppFrame::~LMS7SuiteAppFrame().
API_EXPORT int CALL_CONV LMS_DestroyStream (lms_device_t * device, lms_stream_t * stream)
Definition at line 1170 of file lms7_api.cpp.
References lime::LMS7_Device::DestroyStream(), lms_stream_t::handle, lms(), and lime::ReportError().
Referenced by main(), StopStream(), and fftviewer_frFFTviewer::StreamingLoop().
API_EXPORT int CALL_CONV LMS_Disconnect (lms_device_t * device)
Definition at line 76 of file lms7_api.cpp.
References lime::ReportError(), and lime::warning().
API_EXPORT int CALL_CONV LMS_EnableCalibCache (lms_device_t * dev, bool enable)
Definition at line 363 of file lms7_api.cpp.
References lime::LMS7_Device::EnableCalibCache(), lms(), and lime::ReportError().
Referenced by deviceCalSweep(), LMS7SuiteAppFrame::OnChangeCacheSettings(), and LMS7SuiteAppFrame::OnControlBoardConnect().
API_EXPORT int CALL_CONV LMS_EnableChannel (lms_device_t * device, bool dir_tx, size_t chan, bool enabled)
Definition at line 115 of file lms7_api.cpp.
References lime::LMS7_Device::EnableChannel(), lms(), and lime::ReportError().
Referenced by deviceCalSweep(), main(), and lms7002_mainPanel::OnEnableMIMOchecked().
API_EXPORT int CALL_CONV LMS_EnableTxWFM (lms_device_t * device, unsigned ch, bool active)
Definition at line 1255 of file lms7_api.cpp.
References LMS_ReadFPGAReg(), LMS_WriteFPGAReg(), and status.
Referenced by DEFUN_DLD(), FreeResources(), FPGAcontrols_wxgui::OnbtnPlayWFMClick(), FPGAcontrols_wxgui::OnbtnStopWFMClick(), and FPGAcontrols_wxgui::UploadFile().
API_EXPORT int CALL_CONV LMS_GetAntenna (lms_device_t * device, bool dir_tx, size_t chan)
Definition at line 508 of file lms7_api.cpp.
References lime::LMS7_Device::GetPath(), lms(), and lime::ReportError().
Referenced by main().
API_EXPORT int CALL_CONV LMS_GetAntennaBW (lms_device_t * device, bool dir_tx, size_t chan, size_t path, lms_range_t * range)
Definition at line 521 of file lms7_api.cpp.
References lime::LMS7_Device::GetRxPathBand(), lime::LMS7_Device::GetTxPathBand(), lms(), LMS_SUCCESS, lime::LMS7_Device::Range::max, lms_range_t::max, lime::LMS7_Device::Range::min, lms_range_t::min, lime::ReportError(), and lms_range_t::step.
API_EXPORT int CALL_CONV LMS_GetAntennaList (lms_device_t * device, bool dir_tx, size_t chan, lms_name_t * list)
Definition at line 460 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lime::LMS7_Device::GetPathNames(), i, lms(), and lime::ReportError().
Referenced by main().
API_EXPORT int CALL_CONV LMS_GetChipTemperature (lms_device_t * dev, size_t ind, float_type * temp)
Definition at line 375 of file lms7_api.cpp.
References lime::LMS7_Device::GetChipTemperature(), lms(), lime::LMS7_Device::ReadLMSReg(), and lime::ReportError().
Referenced by lms7002_mainPanel::OnReadTemperature().
API_EXPORT int CALL_CONV LMS_GetClockFreq (lms_device_t * device, size_t clk_id, float_type * freq)
Definition at line 260 of file lms7_api.cpp.
References lime::LMS7_Device::GetClockFreq(), lms(), and lime::ReportError().
Referenced by ADF4002_wxgui::Initialize(), lms7002_pnlCLKGEN_view::Initialize(), lms7002_pnlSX_view::OnbtnChangeRefClkClick(), lms7002_pnlCalibrations_view::UpdateGUI(), lms7002_pnlCLKGEN_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateGUI(), lms7002_pnlSX_view::UpdateGUI(), and lms7002_pnlCLKGEN_view::UpdateInterfaceFrequencies().
API_EXPORT const lms_dev_info_t* CALL_CONV LMS_GetDeviceInfo (lms_device_t * device)
Definition at line 1291 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lime::LMS7_Device::GetInfo(), lms(), and lime::ReportError().
Referenced by pnlLimeSDR::Initialize(), pnlBoardControls::Initialize(), LMS_Programing_wxgui::OnbtnOpenClick(), LMS7SuiteAppFrame::OnControlBoardConnect(), dlgDeviceInfo::OnGetInfo(), LMS7SuiteAppFrame::OnShowSi5351C(), PrintDeviceInfo(), and Myriad7_wxgui::UpdatePanel().
API_EXPORT int CALL_CONV LMS_GetDeviceList (lms_info_str_t * dev_list)
Definition at line 15 of file lms7_api.cpp.
References lime::ConnectionRegistry::findConnections(), and i.
Referenced by DEFUN_DLD(), dlgConnectionSettings::GetDeviceList(), and main().
API_EXPORT int CALL_CONV LMS_GetGaindB (lms_device_t * device, bool dir_tx, size_t chan, unsigned * gain)
Definition at line 707 of file lms7_api.cpp.
References lime::LMS7_Device::GetGain(), lime::LMS7_Device::GetNumChannels(), lms(), LMS_SUCCESS, and lime::ReportError().
Referenced by main().
API_EXPORT int CALL_CONV LMS_GetGFIRCoeff (lms_device_t * device, bool dir_tx, size_t chan, lms_gfir_t filt, float_type * coef)
Definition at line 1103 of file lms7_api.cpp.
References lime::LMS7_Device::GetGFIRCoef(), lime::LMS7_Device::GetNumChannels(), lms(), and lime::ReportError().
Referenced by lms7002_pnlRxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR3Coef(), and lms7002_pnlTxTSP_view::onbtnGFIR3Coef().
API_EXPORT const char* CALL_CONV LMS_GetLastErrorMessage (void)
Definition at line 1349 of file lms7_api.cpp.
References lime::GetLastErrorMessage().
Referenced by DEFUN_DLD(), deviceCalSweep(), lms7002_pnlCalibrations_view::OnbtnCalibrateAll(), lms7002_pnlCalibrations_view::OnbtnCalibrateRx(), and lms7002_pnlCalibrations_view::OnbtnCalibrateTx().
API_EXPORT const char* LMS_GetLibraryVersion ()
Definition at line 1354 of file lms7_api.cpp.
References lime::GetLibraryVersion().
API_EXPORT int CALL_CONV LMS_GetLOFrequency (lms_device_t * device, bool dir_tx, size_t chan, float_type * frequency)
Definition at line 424 of file lms7_api.cpp.
References lime::LMS7_Device::GetFrequency(), lime::LMS7_Device::GetNumChannels(), lms(), LMS_SUCCESS, and lime::ReportError().
Referenced by main().
API_EXPORT int CALL_CONV LMS_GetLOFrequencyRange (lms_device_t * device, bool dir_tx, lms_range_t * range)
Definition at line 444 of file lms7_api.cpp.
References lime::LMS7_Device::GetFrequencyRange(), lms(), LMS_SUCCESS, lms_range_t::max, lms_range_t::min, lime::ReportError(), and lms_range_t::step.
API_EXPORT int CALL_CONV LMS_GetLPFBW (lms_device_t * device, bool dir_tx, size_t chan, float_type * bandwidth)
Definition at line 562 of file lms7_api.cpp.
References lime::LMS7_Device::GetLPFBW(), lime::LMS7_Device::GetNumChannels(), lms(), LMS_SUCCESS, and lime::ReportError().
API_EXPORT int CALL_CONV LMS_GetLPFBWRange (lms_device_t * device, bool dir_tx, lms_range_t * range)
Definition at line 623 of file lms7_api.cpp.
References lime::LMS7_Device::GetLPFRange(), lms(), LMS_SUCCESS, lms_range_t::max, lms_range_t::min, lime::ReportError(), and lms_range_t::step.
Referenced by main().
API_EXPORT int CALL_CONV LMS_GetNCOFrequency (lms_device_t * device, bool dir_tx, size_t chan, float_type * freq, float_type * pho)
Definition at line 856 of file lms7_api.cpp.
References lime::LMS7_Device::GetNCOFreq(), lime::LMS7_Device::GetNumChannels(), i, lms(), LMS_NCO_VAL_COUNT, lime::LMS7_Device::ReadLMSReg(), and lime::ReportError().
Referenced by lms7002_pnlSX_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateNCOinputs(), and lms7002_pnlRxTSP_view::UpdateNCOinputs().
API_EXPORT int CALL_CONV LMS_GetNCOIndex (lms_device_t * device, bool dir_tx, size_t chan)
Definition at line 971 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), LMS7_CMIX_BYP_RXTSP, LMS7_CMIX_BYP_TXTSP, LMS7_SEL_RX, LMS7_SEL_TX, lime::LMS7_Device::ReadParam(), and lime::ReportError().
API_EXPORT int CALL_CONV LMS_GetNCOPhase (lms_device_t * device, bool dir_tx, size_t ch, float_type * phase, float_type * fcw)
Definition at line 914 of file lms7_api.cpp.
References lime::LMS7_Device::GetNCOFreq(), lime::LMS7_Device::GetNCOPhase(), lime::LMS7_Device::GetNumChannels(), i, lms(), LMS_NCO_VAL_COUNT, and lime::ReportError().
Referenced by lms7002_pnlTxTSP_view::UpdateNCOinputs(), and lms7002_pnlRxTSP_view::UpdateNCOinputs().
API_EXPORT int CALL_CONV LMS_GetNormalizedGain (lms_device_t * device, bool dir_tx, size_t chan, float_type * gain)
Definition at line 685 of file lms7_api.cpp.
References lime::LMS7_Device::GetGain(), lime::LMS7_Device::GetGainRange(), lime::LMS7_Device::GetNumChannels(), lms(), LMS_SUCCESS, lms_range_t::max, lms_range_t::min, range, and lime::ReportError().
Referenced by main().
API_EXPORT int CALL_CONV LMS_GetNumChannels (lms_device_t * device, bool dir_tx)
Definition at line 393 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), and lime::ReportError().
Referenced by deviceCalSweep(), FPGAcontrols_wxgui::Initialize(), fftviewer_frFFTviewer::Initialize(), main(), lms7002_mainPanel::OnEnableMIMOchecked(), and fftviewer_frFFTviewer::StreamingLoop().
API_EXPORT int CALL_CONV LMS_GetProgramModes (lms_device_t * device, lms_name_t * list)
Definition at line 1315 of file lms7_api.cpp.
References lime::LMS7_Device::GetProgramModes(), i, lms(), and lime::ReportError().
Referenced by LMS_Programing_wxgui::SetConnection().
API_EXPORT int CALL_CONV LMS_GetSampleRate (lms_device_t * device, bool dir_tx, size_t chan, float_type * host_Hz, float_type * rf_Hz)
Definition at line 154 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lime::LMS7_Device::GetRate(), lms(), LMS_SUCCESS, rate, and lime::ReportError().
Referenced by pnlQSpark::Initialize(), main(), and fftviewer_frFFTviewer::SetNyquistFrequency().
API_EXPORT int CALL_CONV LMS_GetSampleRateRange (lms_device_t * device, bool dir_tx, lms_range_t * range)
Definition at line 178 of file lms7_api.cpp.
References lime::LMS7_Device::GetRateRange(), lms(), LMS_SUCCESS, lms_range_t::max, lms_range_t::min, and lime::ReportError().
API_EXPORT int CALL_CONV LMS_GetStreamStatus (lms_stream_t * stream, lms_stream_status_t * status)
Definition at line 1272 of file lms7_api.cpp.
References lime::StreamChannel::Info::active, lms_stream_status_t::active, lime::StreamChannel::Info::droppedPackets, lms_stream_status_t::droppedPackets, lms_stream_status_t::fifoFilledCount, lime::StreamChannel::Info::fifoItemsCount, lime::StreamChannel::Info::fifoSize, lms_stream_status_t::fifoSize, lime::StreamChannel::GetInfo(), lms_stream_t::handle, info, lime::StreamChannel::Info::linkRate, lms_stream_status_t::linkRate, lime::StreamChannel::Info::overrun, lms_stream_status_t::overrun, lime::StreamChannel::Info::timestamp, lms_stream_status_t::timestamp, lime::StreamChannel::Info::underrun, and lms_stream_status_t::underrun.
Referenced by main(), and fftviewer_frFFTviewer::OnUpdateStats().
API_EXPORT int CALL_CONV LMS_GetTestSignal (lms_device_t * device, bool dir_tx, size_t chan, lms_testsig_t * sig)
Definition at line 804 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lime::LMS7_Device::GetTestSignal(), lms(), LMS_SUCCESS, and lime::ReportError().
API_EXPORT int CALL_CONV LMS_GPIODirRead (lms_device_t * dev, uint8_t * buffer, size_t len)
Definition at line 329 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lms(), and lime::ReportError().
Referenced by pnlLimeSDR::UpdatePanel().
API_EXPORT int CALL_CONV LMS_GPIODirWrite (lms_device_t * dev, const uint8_t * buffer, size_t len)
Definition at line 346 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lms(), and lime::ReportError().
Referenced by main(), and pnlLimeSDR::OnUsrGPIODirChange().
API_EXPORT int CALL_CONV LMS_GPIORead (lms_device_t * dev, uint8_t * buffer, size_t len)
Definition at line 295 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lms(), and lime::ReportError().
Referenced by main(), RFSpark_wxgui::OnReadGPIO(), pnlBuffers::UpdatePanel(), Myriad7_wxgui::UpdatePanel(), and pnlLimeSDR::UpdatePanel().
API_EXPORT int CALL_CONV LMS_GPIOWrite (lms_device_t * dev, const uint8_t * buffer, size_t len)
Definition at line 312 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lms(), and lime::ReportError().
Referenced by main(), pnlBuffers::OnGPIOchanged(), pnlLimeSDR::OnUsrGPIOChange(), RFSpark_wxgui::OnWriteGPIO(), and Myriad7_wxgui::ParameterChangeHandler().
API_EXPORT int CALL_CONV LMS_Init (lms_device_t * device)
Definition at line 193 of file lms7_api.cpp.
References lime::LMS7_Device::Init(), lms(), and lime::ReportError().
Referenced by main(), and lms7002_mainPanel::OnLoadDefault().
API_EXPORT bool CALL_CONV LMS_IsOpen (lms_device_t * device, int port)
Definition at line 87 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lime::IConnection::IsOpen(), lms(), and lime::warning().
API_EXPORT int CALL_CONV LMS_LoadConfig (lms_device_t * device, const char * filename)
Definition at line 751 of file lms7_api.cpp.
References lms(), lime::LMS7_Device::LoadConfig(), and lime::ReportError().
Referenced by DEFUN_DLD(), and lms7002_mainPanel::OnOpenProject().
API_EXPORT int CALL_CONV LMS_Open (lms_device_t ** device, const lms_info_str_t info, void * args)
Definition at line 34 of file lms7_api.cpp.
References lime::LMS7_Device::CreateDevice(), lime::error(), lime::ConnectionRegistry::findConnections(), i, and LMS_SUCCESS.
Referenced by DEFUN_DLD(), deviceCalSweep(), and main().
API_EXPORT int CALL_CONV LMS_Program (lms_device_t * device, const char * data, size_t size, const lms_name_t mode, lms_prog_callback_t callback)
Definition at line 1336 of file lms7_api.cpp.
References lms(), lime::LMS7_Device::Program(), and lime::ReportError().
Referenced by LMS_Programing_wxgui::DoProgramming(), lms7002_pnlMCU_BD_view::OnbtnStartProgrammingClick(), lms7002_pnlMCU_BD_view::OnchkResetClick(), and lms7002_pnlR3_view::ParameterChangeHandler().
API_EXPORT int CALL_CONV LMS_ReadCustomBoardParam (lms_device_t * device, uint8_t param_id, float_type * val, lms_name_t units)
Definition at line 206 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lms(), and lime::ReportError().
Referenced by LMS_VCTCXORead(), pnlBoardControls::OnCustomRead(), pnlUltimateEVB::OnReadAll(), pnlBoardControls::OnReadAll(), and RFSpark_wxgui::OnRefreshAllADC().
API_EXPORT int CALL_CONV LMS_ReadFPGAReg (lms_device_t * device, uint32_t address, uint16_t * val)
Definition at line 1020 of file lms7_api.cpp.
References address, lime::LMS7_Device::GetConnection(), lms(), LMS_SUCCESS, lime::ReportError(), and val.
Referenced by LMS_EnableTxWFM(), SPI_wxgui::OnBoardRead(), pnlQSpark::OnbtnUpdateAll(), FPGAcontrols_wxgui::OnChkDigitalLoopbackEnableClick(), pnlQSpark::RegisterParameterChangeHandler(), pnluLimeSDR::UpdatePanel(), and pnlLimeSDR::UpdatePanel().
API_EXPORT int CALL_CONV LMS_ReadLMSReg (lms_device_t * device, uint32_t address, uint16_t * val)
Definition at line 995 of file lms7_api.cpp.
References lms(), lime::LMS7_Device::ReadLMSReg(), and lime::ReportError().
Referenced by lms7002_pnlR3_view::MCU_RunProcedure(), lms7002_pnlR3_view::MCU_WaitForStatus(), lms7002_pnlRxTSP_view::OnbtnReadBISTSignature(), lms7002_pnlRxTSP_view::OnbtnReadRSSI(), SPI_wxgui::onLMSread(), lms7002_pnlMCU_BD_view::OnRegWriteRead(), lms7002_pnlR3_view::OnWriteRxDC(), lms7002_pnlR3_view::OnWriteTxDC(), lms7002_pnlR3_view::ParameterChangeHandler(), lms7002_pnlMCU_BD_view::ReadOneByte(), lms7002_pnlR3_view::UpdateGUISlow(), LMS7002M_Novena_wxgui::UpdatePanel(), lms7002_mainPanel::UpdateVisiblePanel(), lms7002_pnlMCU_BD_view::Wait_CLK_Cycles(), and lms7002_pnlMCU_BD_view::WaitUntilWritten().
API_EXPORT int CALL_CONV LMS_ReadParam (lms_device_t * device, struct LMS7Parameter param, uint16_t * val)
Definition at line 1062 of file lms7_api.cpp.
References lms(), LMS_SUCCESS, lime::LMS7_Device::ReadParam(), and lime::ReportError().
Referenced by lms7002_pnlLDO_view::Initialize(), lms7002_pnlGains_view::Initialize(), lms7002_pnlLimeLightPAD_view::Initialize(), lms7002_pnlTBB_view::Initialize(), lms7002_pnlCalibrations_view::Initialize(), lms7002_pnlTxTSP_view::Initialize(), lms7002_pnlRxTSP_view::Initialize(), lms7002_pnlR3_view::Initialize(), lms7002_pnlSX_view::OnbtnCalculateClick(), lms7002_pnlCalibrations_view::OnbtnCalibrateAll(), lms7002_pnlCalibrations_view::OnbtnCalibrateRx(), lms7002_pnlCalibrations_view::OnbtnCalibrateTx(), lms7002_pnlSX_view::OnbtnChangeRefClkClick(), lms7002_pnlTxTSP_view::onbtnGFIR1Coef(), lms7002_pnlRxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR2Coef(), lms7002_pnlTxTSP_view::onbtnGFIR3Coef(), lms7002_pnlRxTSP_view::onbtnGFIR3Coef(), lms7002_pnlTxTSP_view::onbtnReadBISTSignature(), lms7002_pnlSX_view::OnbtnReadComparators(), lms7002_pnlCLKGEN_view::OnbtnReadComparators(), lms7002_pnlBIST_view::onbtnReadSignature(), lms7002_pnlLimeLightPAD_view::onbtnReadVerRevMask(), lms7002_pnlCLKGEN_view::onbtnTuneClick(), lms7002_pnlSX_view::OnbtnTuneClick(), lms7002_pnlTBB_view::OnbtnTuneFilter(), lms7002_pnlRBB_view::OnbtnTuneFilter(), lms7002_pnlTBB_view::OnbtnTuneTxGain(), lms7002_pnlCLKGEN_view::OnbtnUpdateCoarse(), lms7002_pnlTxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlRxTSP_view::OnbtnUploadNCOClick(), lms7002_mainPanel::OnEnableMIMOchecked(), lms7002_pnlSX_view::OnEnableRefSpurCancelation(), lms7002_pnlTxTSP_view::PHOinputChanged(), lms7002_pnlRxTSP_view::PHOinputChanged(), lms7002_pnlGains_view::UpdateGUI(), lms7002_pnlTRF_view::UpdateGUI(), lms7002_pnlLimeLightPAD_view::UpdateGUI(), lms7002_pnlRBB_view::UpdateGUI(), lms7002_pnlTBB_view::UpdateGUI(), lms7002_pnlRFE_view::UpdateGUI(), lms7002_pnlCalibrations_view::UpdateGUI(), lms7002_pnlCLKGEN_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateGUI(), lms7002_pnlSX_view::UpdateGUI(), lms7002_pnlRxTSP_view::UpdateGUI(), lms7002_mainPanel::UpdateGUI(), lms7002_pnlR3_view::UpdateGUI(), lms7002_pnlTxTSP_view::UpdateNCOinputs(), and lms7002_pnlRxTSP_view::UpdateNCOinputs().
API_EXPORT int CALL_CONV LMS_RecvStream (lms_stream_t * stream, void * samples, size_t sample_count, lms_stream_meta_t * meta, unsigned timeout_ms)
Definition at line 1193 of file lms7_api.cpp.
References lime::StreamChannel::Metadata::flags, lms_stream_t::handle, if(), lime::StreamChannel::Read(), status, lime::RingFIFO::SYNC_TIMESTAMP, lms_stream_meta_t::timestamp, and lms_stream_meta_t::waitForTimestamp.
Referenced by DEFUN_DLD(), main(), and fftviewer_frFFTviewer::StreamingLoop().
API_EXPORT void LMS_RegisterLogHandler (LMS_LogHandler handler)
Definition at line 1367 of file lms7_api.cpp.
References api_msg_handler, APIMsgHandler(), and lime::registerLogHandler().
API_EXPORT int CALL_CONV LMS_Reset (lms_device_t * device)
Definition at line 103 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::Reset().
Referenced by lms7002_mainPanel::OnNewProject(), and lms7002_mainPanel::OnResetChip().
API_EXPORT int CALL_CONV LMS_SaveConfig (lms_device_t * device, const char * filename)
Definition at line 764 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::SaveConfig().
Referenced by lms7002_mainPanel::OnSaveProject().
API_EXPORT int CALL_CONV LMS_SendStream (lms_stream_t * stream, const void * samples, size_t sample_count, const lms_stream_meta_t * meta, unsigned timeout_ms)
Definition at line 1213 of file lms7_api.cpp.
References lime::RingFIFO::END_BURST, lime::StreamChannel::Metadata::flags, lms_stream_meta_t::flushPartialPacket, lms_stream_t::handle, if(), lime::RingFIFO::SYNC_TIMESTAMP, lms_stream_meta_t::timestamp, lms_stream_meta_t::waitForTimestamp, and lime::StreamChannel::Write().
Referenced by DEFUN_DLD(), main(), and fftviewer_frFFTviewer::StreamingLoop().
API_EXPORT int CALL_CONV LMS_SetAntenna (lms_device_t * device, bool dir_tx, size_t chan, size_t path)
Definition at line 486 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), LMS_SUCCESS, lime::ReportError(), and lime::LMS7_Device::SetPath().
Referenced by deviceCalSweep(), and main().
API_EXPORT int CALL_CONV LMS_SetClockFreq (lms_device_t * device, size_t clk_id, float_type freq)
Definition at line 272 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::SetClockFreq().
Referenced by lms7002_pnlSX_view::OnbtnCalculateClick(), lms7002_pnlSX_view::OnbtnChangeRefClkClick(), and lms7002_pnlSX_view::OnbtnTuneClick().
API_EXPORT int CALL_CONV LMS_SetGaindB (lms_device_t * device, bool dir_tx, size_t chan, unsigned gain)
Definition at line 665 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), lime::ReportError(), and lime::LMS7_Device::SetGain().
API_EXPORT int CALL_CONV LMS_SetGFIR (lms_device_t * device, bool dir_tx, size_t chan, lms_gfir_t filt, bool enabled)
Definition at line 1120 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), lime::ReportError(), and lime::LMS7_Device::SetGFIR().
API_EXPORT int CALL_CONV LMS_SetGFIRCoeff (lms_device_t * device, bool dir_tx, size_t chan, lms_gfir_t filt, const float_type * coef, size_t count)
Definition at line 1086 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), lime::ReportError(), and lime::LMS7_Device::SetGFIRCoef().
Referenced by lms7002_pnlRxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR1Coef(), lms7002_pnlTxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR2Coef(), lms7002_pnlRxTSP_view::onbtnGFIR3Coef(), and lms7002_pnlTxTSP_view::onbtnGFIR3Coef().
API_EXPORT int CALL_CONV LMS_SetGFIRLPF (lms_device_t * device, bool dir_tx, size_t chan, bool enabled, float_type bandwidth)
Definition at line 599 of file lms7_api.cpp.
References lime::LMS7_Device::ConfigureGFIR(), lime::LMS7_Device::GetNumChannels(), lms(), and lime::ReportError().
API_EXPORT int CALL_CONV LMS_SetLOFrequency (lms_device_t * device, bool dir_tx, size_t chan, float_type frequency)
Definition at line 405 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), lime::ReportError(), and lime::LMS7_Device::SetFrequency().
Referenced by deviceCalSweep(), and main().
API_EXPORT int CALL_CONV LMS_SetLPF (lms_device_t * device, bool dir_tx, size_t chan, bool enabled)
Definition at line 581 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), lime::ReportError(), and lime::LMS7_Device::SetLPF().
API_EXPORT int CALL_CONV LMS_SetLPFBW (lms_device_t * device, bool dir_tx, size_t chan, float_type bandwidth)
Definition at line 543 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), lime::ReportError(), and lime::LMS7_Device::SetLPF().
Referenced by main(), lms7002_pnlTBB_view::OnbtnTuneFilter(), and lms7002_pnlRBB_view::OnbtnTuneFilter().
API_EXPORT int CALL_CONV LMS_SetNCOFrequency (lms_device_t * device, bool dir_tx, size_t ch, const float_type * freq, float_type pho)
Definition at line 828 of file lms7_api.cpp.
References lime::LMS7_Device::GetLMS(), lime::LMS7_Device::GetNumChannels(), i, lms(), LMS7_CMIX_BYP_RXTSP, LMS7_CMIX_BYP_TXTSP, LMS7_SEL_RX, LMS7_SEL_TX, LMS_NCO_VAL_COUNT, lime::ReportError(), lime::LMS7_Device::SetNCOFreq(), lime::LMS7002M::SetNCOPhaseOffsetForMode0(), and lime::LMS7_Device::WriteParam().
Referenced by lms7002_pnlRxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlTxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlTxTSP_view::PHOinputChanged(), and lms7002_pnlRxTSP_view::PHOinputChanged().
API_EXPORT int CALL_CONV LMS_SetNCOIndex (lms_device_t * device, bool dir_tx, size_t chan, int ind, bool down)
Definition at line 940 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), LMS7_CMIX_BYP_RXTSP, LMS7_CMIX_BYP_TXTSP, LMS7_CMIX_GAIN_RXTSP, LMS7_CMIX_GAIN_TXTSP, LMS7_CMIX_SC_RXTSP, LMS7_CMIX_SC_TXTSP, LMS7_SEL_RX, LMS7_SEL_TX, LMS_NCO_VAL_COUNT, lime::ReportError(), and lime::LMS7_Device::WriteParam().
API_EXPORT int CALL_CONV LMS_SetNCOPhase (lms_device_t * device, bool dir_tx, size_t ch, const float_type * phase, float_type fcw)
Definition at line 884 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), i, lms(), LMS7_SEL_RX, LMS7_SEL_TX, LMS_NCO_VAL_COUNT, lime::ReportError(), lime::LMS7_Device::SetNCOFreq(), lime::LMS7_Device::SetNCOPhase(), and lime::LMS7_Device::WriteParam().
Referenced by lms7002_pnlRxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlTxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlTxTSP_view::PHOinputChanged(), and lms7002_pnlRxTSP_view::PHOinputChanged().
API_EXPORT int CALL_CONV LMS_SetNormalizedGain (lms_device_t * device, bool dir_tx, size_t chan, float_type gain)
Definition at line 641 of file lms7_api.cpp.
References lime::LMS7_Device::GetGainRange(), lime::LMS7_Device::GetNumChannels(), lms(), lms_range_t::max, lms_range_t::min, range, lime::ReportError(), and lime::LMS7_Device::SetGain().
Referenced by main().
API_EXPORT int CALL_CONV LMS_SetSampleRate (lms_device_t * device, float_type rate, size_t oversample)
Definition at line 128 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::SetRate().
Referenced by main().
API_EXPORT int CALL_CONV LMS_SetSampleRateDir (lms_device_t * device, bool dir_tx, float_type rate, size_t oversample)
Definition at line 141 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::SetRate().
API_EXPORT int CALL_CONV LMS_SetTestSignal (lms_device_t * device, bool dir_tx, size_t chan, lms_testsig_t sig, int16_t dc_i, int16_t dc_q)
Definition at line 777 of file lms7_api.cpp.
References lime::LMS7_Device::GetNumChannels(), lms(), LMS_SUCCESS, LMS_TESTSIG_DC, lime::ReportError(), and lime::LMS7_Device::SetTestSignal().
Referenced by main().
API_EXPORT int CALL_CONV LMS_SetupStream (lms_device_t * device, lms_stream_t * stream)
Definition at line 1138 of file lms7_api.cpp.
References lime::StreamConfig::bufferLength, lms_stream_t::channel, lime::StreamConfig::channelID, lms_stream_t::dataFmt, lms_stream_t::fifoSize, lime::StreamConfig::FMT_FLOAT32, lime::StreamConfig::FMT_INT12, lime::StreamConfig::FMT_INT16, lime::StreamConfig::format, lms_stream_t::handle, lime::StreamConfig::isTx, lms_stream_t::isTx, lms(), lms_stream_t::LMS_FMT_F32, lms_stream_t::LMS_FMT_I12, lms_stream_t::LMS_FMT_I16, lime::StreamConfig::performanceLatency, lime::ReportError(), lime::LMS7_Device::SetupStream(), and lms_stream_t::throughputVsLatency.
Referenced by DEFUN_DLD(), main(), and fftviewer_frFFTviewer::StreamingLoop().
API_EXPORT int CALL_CONV LMS_StartStream (lms_stream_t * stream)
Definition at line 1179 of file lms7_api.cpp.
References lms_stream_t::handle.
Referenced by DEFUN_DLD(), main(), and fftviewer_frFFTviewer::StreamingLoop().
API_EXPORT int CALL_CONV LMS_StopStream (lms_stream_t * stream)
Definition at line 1186 of file lms7_api.cpp.
References lms_stream_t::handle.
Referenced by main(), StopStream(), and fftviewer_frFFTviewer::StreamingLoop().
API_EXPORT int CALL_CONV LMS_Synchronize (lms_device_t * dev, bool toChip)
Definition at line 283 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::Synchronize().
Referenced by DEFUN_DLD(), lms7002_pnlTBB_view::OnbtnTuneFilter(), lms7002_pnlRBB_view::OnbtnTuneFilter(), lms7002_pnlTBB_view::OnbtnTuneTxGain(), lms7002_mainPanel::OnDownloadAll(), lms7002_mainPanel::OnUploadAll(), and lms7002_pnlR3_view::UpdateGUI().
API_EXPORT int CALL_CONV LMS_TransferLMS64C (lms_device_t * dev, int cmd, uint8_t * data, size_t * len)
Definition at line 1373 of file lms7_api.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::LMS7_Device::GetConnection(), i, lime::LMS64CProtocol::GenericPacket::inBuffer, len, lms(), lime::LMS64CProtocol::GenericPacket::outBuffer, port, lime::ReportError(), lime::LMS64CProtocol::GenericPacket::status, lime::status2string(), lime::STATUS_COMPLETED_CMD, and lime::LMS64CProtocol::TransferPacket().
API_EXPORT int CALL_CONV LMS_UploadWFM (lms_device_t * device, const void ** samples, uint8_t chCount, size_t sample_count, int format)
Definition at line 1231 of file lms7_api.cpp.
References lms(), and lime::LMS7_Device::UploadWFM().
Referenced by DEFUN_DLD(), and FPGAcontrols_wxgui::UploadFile().
API_EXPORT int CALL_CONV LMS_VCTCXORead (lms_device_t * device, uint16_t * val)
Definition at line 251 of file lms7_api.cpp.
References LMS_ReadCustomBoardParam(), and units.
API_EXPORT int CALL_CONV LMS_VCTCXOWrite (lms_device_t * device, uint16_t val)
Definition at line 246 of file lms7_api.cpp.
References LMS_WriteCustomBoardParam().
API_EXPORT int CALL_CONV LMS_WriteCustomBoardParam (lms_device_t * device, uint8_t param_id, float_type val, const lms_name_t units)
Definition at line 227 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lms(), lime::ReportError(), and units.
Referenced by LMS_VCTCXOWrite(), pnlBoardControls::OnCustomWrite(), pnlBoardControls::OnSetDACvalues(), and pnlBoardControls::OnWriteAll().
API_EXPORT int CALL_CONV LMS_WriteFPGAReg (lms_device_t * device, uint32_t address, uint16_t val)
Definition at line 1044 of file lms7_api.cpp.
References lime::LMS7_Device::GetConnection(), lms(), and lime::ReportError().
Referenced by pnlQSpark::Initialize(), LMS_EnableTxWFM(), SPI_wxgui::onBoardWrite(), pnlQSpark::OnbtnUpdateAll(), FPGAcontrols_wxgui::OnChkDigitalLoopbackEnableClick(), pnlLimeSDR::OnGPIOChange(), pnluLimeSDR::OnLoopbackChange(), pnlQSpark::OnNcoFrequencyChanged(), pnlQSpark::OnSwitchToChannelA(), pnlQSpark::OnSwitchToChannelB(), and pnlQSpark::RegisterParameterChangeHandler().
API_EXPORT int CALL_CONV LMS_WriteLMSReg (lms_device_t * device, uint32_t address, uint16_t val)
Definition at line 1008 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::WriteLMSReg().
Referenced by lms7002_pnlMCU_BD_view::DebugModeExit_MCU(), lms7002_pnlMCU_BD_view::DebugModeSet_MCU(), lms7002_pnlR3_view::MCU_RunProcedure(), lms7002_pnlR3_view::MCU_WaitForStatus(), lms7002_pnlMCU_BD_view::One_byte_command(), SPI_wxgui::onLMSwrite(), lms7002_pnlMCU_BD_view::Onm_cCtrlBasebandSelect(), lms7002_pnlMCU_BD_view::Onm_cCtrlMCU_BDSelect(), lms7002_pnlMCU_BD_view::OnRegWriteRead(), lms7002_pnlR3_view::OnWriteRxDC(), lms7002_pnlR3_view::OnWriteTxDC(), LMS7002M_Novena_wxgui::ParameterChangeHandler(), lms7002_pnlR3_view::ParameterChangeHandler(), lms7002_pnlMCU_BD_view::RunTest_MCU(), lms7002_pnlMCU_BD_view::Three_byte_command(), lms7002_pnlR3_view::UpdateGUI(), and lms7002_pnlR3_view::UpdateGUISlow().
API_EXPORT int CALL_CONV LMS_WriteParam (lms_device_t * device, struct LMS7Parameter param, uint16_t val)
Definition at line 1074 of file lms7_api.cpp.
References lms(), lime::ReportError(), and lime::LMS7_Device::WriteParam().
Referenced by lms7002_pnlTRF_view::OnBandChange(), lms7002_pnlRxTSP_view::OnbtnLoadDCIClick(), lms7002_pnlTxTSP_view::OnbtnLoadDCIClick(), lms7002_pnlTxTSP_view::OnbtnLoadDCQClick(), lms7002_pnlRxTSP_view::OnbtnLoadDCQClick(), lms7002_pnlRxTSP_view::OnbtnReadBISTSignature(), lms7002_pnlRxTSP_view::OnbtnReadRSSI(), lms7002_pnlTxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlRxTSP_view::OnbtnUploadNCOClick(), lms7002_pnlRBB_view::OncmbBBLoopbackSelected(), LMS7SuiteAppFrame::OnControlBoardConnect(), lms7002_mainPanel::OnEnableMIMOchecked(), lms7002_pnlSX_view::OnEnableRefSpurCancelation(), lms7002_mainPanel::OnLmsDeviceSelect(), lms7002_pnlTxTSP_view::OnNCOSelectionChange(), lms7002_pnlRxTSP_view::OnNCOSelectionChange(), lms7002_mainPanel::OnNewProject(), lms7002_mainPanel::Onnotebook_modulesPageChanged(), lms7002_mainPanel::OnOpenProject(), lms7002_mainPanel::OnSwitchToChannelA(), lms7002_mainPanel::OnSwitchToChannelB(), lms7002_pnlTBB_view::ParameterChangeHandler(), lms7002_pnlLDO_view::ParameterChangeHandler(), lms7002_pnlAFE_view::ParameterChangeHandler(), lms7002_pnlRBB_view::ParameterChangeHandler(), lms7002_pnlCLKGEN_view::ParameterChangeHandler(), lms7002_pnlTRF_view::ParameterChangeHandler(), lms7002_pnlBIAS_view::ParameterChangeHandler(), lms7002_pnlSX_view::ParameterChangeHandler(), lms7002_pnlBIST_view::ParameterChangeHandler(), lms7002_pnlLimeLightPAD_view::ParameterChangeHandler(), lms7002_pnlCalibrations_view::ParameterChangeHandler(), lms7002_pnlGains_view::ParameterChangeHandler(), lms7002_pnlXBUF_view::ParameterChangeHandler(), lms7002_pnlRFE_view::ParameterChangeHandler(), lms7002_pnlRxTSP_view::ParameterChangeHandler(), lms7002_pnlTxTSP_view::ParameterChangeHandler(), lms7002_pnlCDS_view::ParameterChangeHandler(), lms7002_pnlR3_view::ParameterChangeHandler(), lms7002_pnlTRF_view::UpdateGUI(), lms7002_pnlRBB_view::UpdateGUI(), and lms7002_mainPanel::UpdateGUI().
Variable Documentation
LMS_LogHandler api_msg_handler static
Definition at line 1361 of file lms7_api.cpp.
Referenced by APIMsgHandler(), and LMS_RegisterLogHandler().