LimeSuite-UML: lime::IConnection Class Reference
lime::IConnection Class Reference abstract
#include <IConnection.h>
Public Types
enum MCU_PROG_MODE { RESET = 0, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM }
typedef std::function< bool(int bsent, int btotal, const char *progressMsg)> ProgrammingCallback
Public Member Functions
IConnection (void)
IConnection constructor.
virtual ~IConnection (void)
IConnection destructor.
const ConnectionHandle & GetHandle (void) const
Get the connection handle that was used to create this connection.
virtual bool IsOpen (void)
virtual DeviceInfo GetDeviceInfo (void)
virtual int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size)
Bulk SPI write/read transaction.
virtual int WriteLMS7002MSPI (const uint32_t *writeData, size_t size, unsigned periphID=0)=0
virtual int ReadLMS7002MSPI (const uint32_t *writeData, uint32_t *readData, size_t size, unsigned periphID=0)=0
virtual int WriteI2C (const int addr, const std::string &data)
virtual int ReadI2C (const int addr, const size_t numBytes, std::string &data)
virtual int DeviceReset (int ind=0)
virtual int ResetStreamBuffers ()
Read raw stream data from device streaming port.
virtual int GetBuffersCount () const
virtual int CheckStreamSize (int size) const
virtual int ReceiveData (char *buffer, int length, int epIndex, int timeout=100)
virtual int SendData (const char *buffer, int length, int epIndex, int timeout=100)
virtual int BeginDataSending (const char *buffer, uint32_t length, int ep)
virtual bool WaitForSending (int contextHandle, uint32_t timeout_ms)
virtual int FinishDataSending (const char *buffer, uint32_t length, int contextHandle)
virtual void AbortSending (int ep)
virtual int BeginDataReading (char *buffer, uint32_t length, int ep)
virtual bool WaitForReading (int contextHandle, unsigned int timeout_ms)
virtual int FinishDataReading (char *buffer, uint32_t length, int contextHandle)
virtual void AbortReading (int ep)
virtual int ProgramWrite (const char *buffer, const size_t length, const int programmingMode, const int index, ProgrammingCallback callback=0)
Uploads program to selected device.
virtual int ProgramMCU (const uint8_t *buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback=0)
Uploads program to MCU.
virtual int ProgramUpdate (const bool download=true, ProgrammingCallback callback=0)
virtual int GPIOWrite (const uint8_t *buffer, const size_t bufLength)
Writes GPIO values to device.
virtual int GPIORead (uint8_t *buffer, const size_t bufLength)
Reads GPIO values from device.
virtual int GPIODirWrite (const uint8_t *buffer, const size_t bufLength)
Write GPIO direction control values to device.
virtual int GPIODirRead (uint8_t *buffer, const size_t bufLength)
Read GPIO direction configuration from device.
virtual int WriteRegisters (const uint32_t *addrs, const uint32_t *data, const size_t size)
Bulk write device registers.
int WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
virtual int ReadRegisters (const uint32_t *addrs, uint32_t *data, const size_t size)
Bulk read device registers.
template<typename ReadType >
int ReadRegister (const uint32_t addr, ReadType &data)
Read a single device register.
virtual int CustomParameterWrite (const uint8_t *ids, const double *values, const size_t count, const std::string &units)
Sets custom on board control to given value units.
virtual int CustomParameterRead (const uint8_t *ids, double *values, const size_t count, std::string *units)
Returns value of custom on board control.
void SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Protected Attributes
std::function< void(bool, const unsigned char *, const unsigned int)> callback_logData
Private Attributes
ConnectionHandle _handle
Friends
class ConnectionRegistry
Detailed Description
IConnection is the interface class for a device with 1 or more Lime RFICs. The LMS7002M driver class calls into IConnection to interface with the hardware to implement high level functions on top of low-level SPI and GPIO. Device developers will implement a custom IConnection for their hardware as an abstraction for streaming and low-level SPI and configuration access.
Definition at line 67 of file IConnection.h.
Member Typedef Documentation
typedef std::function<bool(int bsent, int btotal, const char* progressMsg)> lime::IConnection::ProgrammingCallback
Callback from programming processes
Parameters
bsent number of bytes transferred
btotal total number of bytes to send
progressMsg string describing current progress state
Returns
0-continue programming, 1-abort operation
Definition at line 175 of file IConnection.h.
Member Enumeration Documentation
enum lime::IConnection::MCU_PROG_MODE
Enumerator
RESET
EEPROM_AND_SRAM
SRAM
BOOT_SRAM_FROM_EEPROM
Definition at line 203 of file IConnection.h.
Constructor & Destructor Documentation
IConnection::IConnection (void)
IConnection constructor.
Definition at line 13 of file IConnection.cpp.
References callback_logData.
IConnection::~IConnection (void) virtual
IConnection destructor.
Definition at line 18 of file IConnection.cpp.
Member Function Documentation
virtual void lime::IConnection::AbortReading (int ep) inline virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 175 of file IConnection.h.
Referenced by lime::Streamer::AlignRxTSP(), lime::Streamer::GetPhaseOffset(), lime::FPGA_Mini::ReadRawStreamData(), and lime::Streamer::ReceivePacketsLoop().
virtual void lime::IConnection::AbortSending (int ep) inline virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 170 of file IConnection.h.
Referenced by lime::Streamer::TransmitPacketsLoop().
int IConnection::BeginDataReading (char * buffer, uint32_t length, int ep) virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 97 of file IConnection.cpp.
Referenced by lime::FPGA_Mini::ReadRawStreamData(), and lime::Streamer::ReceivePacketsLoop().
int IConnection::BeginDataSending (const char * buffer, uint32_t length, int ep) virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 84 of file IConnection.cpp.
Referenced by lime::Streamer::TransmitPacketsLoop().
int IConnection::CheckStreamSize (int size) const virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 122 of file IConnection.cpp.
Referenced by lime::Streamer::ReceivePacketsLoop(), and lime::Streamer::TransmitPacketsLoop().
int IConnection::CustomParameterRead (const uint8_t * ids, double * values, const size_t count, std::string * units) virtual
Returns value of custom on board control.
Parameters
ids indexes of controls to read
values retrieved control values
count number of values to read
units (optional) when not null returns value units (e.g V, A, Ohm, C...)
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 212 of file IConnection.cpp.
References lime::ReportError().
Referenced by lime::LMS7_Device::SetClockFreq().
int IConnection::CustomParameterWrite (const uint8_t * ids, const double * values, const size_t count, const std::string & units) virtual
Sets custom on board control to given value units.
Parameters
ids indexes of selected controls
values new control values
count number of values to write
units (optional) when not null specifies value units (e.g V, A, Ohm, C...)
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 206 of file IConnection.cpp.
References lime::ReportError().
Referenced by lime::LMS7_Device::SetClockFreq().
int IConnection::DeviceReset (int ind = 0) virtual
Perform reset sequence on the device. Typically this will reset the RFIC using a GPIO, and possibly other ICs located on the device.
Reimplemented in lime::LMS64CProtocol, and lime::ConnectionSTREAM_UNITE.
Definition at line 66 of file IConnection.cpp.
References lime::ReportError().
Referenced by lime::LMS7002M::ResetChip().
int IConnection::FinishDataReading (char * buffer, uint32_t length, int contextHandle) virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 105 of file IConnection.cpp.
Referenced by lime::FPGA_Mini::ReadRawStreamData(), and lime::Streamer::ReceivePacketsLoop().
int IConnection::FinishDataSending (const char * buffer, uint32_t length, int contextHandle) virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 92 of file IConnection.cpp.
Referenced by lime::Streamer::TransmitPacketsLoop().
int IConnection::GetBuffersCount () const virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 117 of file IConnection.cpp.
Referenced by lime::Streamer::ReceivePacketsLoop(), and lime::Streamer::TransmitPacketsLoop().
DeviceInfo IConnection::GetDeviceInfo (void) virtual
Get information about a device for displaying helpful information or for making device-specific decisions.
Reimplemented in lime::ConnectionFT601, lime::LMS64CProtocol, and lime::ConnectionSTREAM_UNITE.
Definition at line 33 of file IConnection.cpp.
References lime::DeviceInfo::deviceName, lime::EXP_BOARD_UNKNOWN, lime::DeviceInfo::expansionName, lime::GetDeviceName(), lime::GetExpansionBoardName(), lime::info(), and lime::LMS_DEV_UNKNOWN.
Referenced by GetExtLoopPair(), lime::LMS7_Device::GetInfo(), main(), SetExtLoopback(), and StreamingFixture::StreamingFixture().
const ConnectionHandle & IConnection::GetHandle (void) const
Get the connection handle that was used to create this connection.
Definition at line 23 of file IConnection.cpp.
References _handle.
int IConnection::GPIODirRead (uint8_t * buffer, const size_t bufLength) virtual
Read GPIO direction configuration from device.
Parameters
buffer to put GPIO direction configuration (0 input, 1 output)
bufLength buffer length to read
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 175 of file IConnection.cpp.
References lime::ReportError().
Referenced by SoapyLMS7::readGPIODir().
int IConnection::GPIODirWrite (const uint8_t * buffer, const size_t bufLength) virtual
Write GPIO direction control values to device.
Parameters
buffer with GPIO direction configuration (0 input, 1 output)
bufLength buffer length
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 169 of file IConnection.cpp.
References lime::ReportError().
Referenced by SoapyLMS7::writeGPIODir().
int IConnection::GPIORead (uint8_t * buffer, const size_t bufLength) virtual
Reads GPIO values from device.
Parameters
buffer destination for GPIO values LSB first, each bit represent GPIO state
bufLength buffer length to read
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 163 of file IConnection.cpp.
References lime::ReportError().
Referenced by SoapyLMS7::readGPIO().
int IConnection::GPIOWrite (const uint8_t * buffer, const size_t bufLength) virtual
Writes GPIO values to device.
Parameters
buffer for source of GPIO values LSB first, each bit sets GPIO state
bufLength buffer length
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 157 of file IConnection.cpp.
References lime::ReportError().
Referenced by SoapyLMS7::writeGPIO().
bool IConnection::IsOpen (void) virtual
Is this connection open? The constructor should attempt to connect but may fail, or the connection may go down at a later time.
Returns
true when the connection is available
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, lime::ConnectionNovenaRF7, lime::ConnectionXillybus, and lime::ConnectionEVB7COM.
Definition at line 28 of file IConnection.cpp.
Referenced by lime::LMS64CProtocol::DeviceReset(), HPM7_wxgui::DownloadAll(), lime::LMS7002M::GetGFIRCoefficients(), lime::LMS7002M::IsSynced(), LMS_IsOpen(), main(), HPM7_wxgui::OnDACchange(), HPM7_wxgui::OnTunerSSC1change(), HPM7_wxgui::OnTunerSSC2change(), lime::LMS64CProtocol::ProgramWrite(), lime::LMS64CProtocol::ReadI2C(), StreamingFixture::SetUp(), StreamingFixture::StreamingFixture(), lime::LMS64CProtocol::TransactSPI(), lime::LMS64CProtocol::TransferPacket(), HPM7_wxgui::UploadGPIO(), and lime::LMS64CProtocol::WriteI2C().
int IConnection::ProgramMCU (const uint8_t * buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback = 0) virtual
Uploads program to MCU.
Parameters
buffer binary program data
length buffer length
mode MCU programing mode RESET, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM
callback callback for progress reporting or early termination
Returns
0-success
This could be a quite long operation, use callback to get progress info or to terminate early
Reimplemented in lime::LMS64CProtocol.
Definition at line 141 of file IConnection.cpp.
References lime::ReportError().
int IConnection::ProgramUpdate (const bool download = true, ProgrammingCallback callback = 0) virtual
Download up-to-date images files and flash the board when applicable.
Program update is an implementation specific function that may handle several different use cases depending upon what options are applicable:
If a board relies on certain firmware and gateware images, these images will be downloaded if not present on the system.
If the board has a programmable flash for firmware and gateware, then up-to-date images will be written to the flash on the board.
Parameters
download true to enable downloading missing images
callback callback for progress reporting or early termination
Returns
0-success
Reimplemented in lime::LMS64CProtocol.
Definition at line 147 of file IConnection.cpp.
References lime::ReportError().
Referenced by lime::LMS7_Device::Program().
int IConnection::ProgramWrite (const char * buffer, const size_t length, const int programmingMode, const int index, ProgrammingCallback callback = 0) virtual
Uploads program to selected device.
Parameters
buffer binary program data
length buffer length
programmingMode to RAM, to FLASH, to EEPROM, etc..
index target device number
callback callback for progress reporting or early termination
Returns
the operation success state
Can be used to program MCU, FPGA, write external on board memory. This could be a quite long operation, use callback to get progress info or to terminate early
Reimplemented in lime::LMS64CProtocol, lime::ConnectionFX3, and lime::ConnectionFT601.
Definition at line 135 of file IConnection.cpp.
References lime::ReportError().
Referenced by lime::LMS7_LimeSDR::Program(), and lime::LMS7_Device::Program().
int IConnection::ReadI2C (const int addr, const size_t numBytes, std::string & data) virtual
Read from an available I2C slave. The data parameter can be used to pass optional write data. Some implementations can combine a write + read transaction. If the device contains multiple I2C masters, the address bits can encode which master.
Parameters
addr the address of the slave
numBytes the number of bytes to read
[in,out] data an array of bytes read from the slave
Returns
the transaction success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 57 of file IConnection.cpp.
References lime::ReportError().
virtual int lime::IConnection::ReadLMS7002MSPI (const uint32_t * writeData, uint32_t * readData, size_t size, unsigned periphID = 0) pure virtual
Implemented in lime::LMS64CProtocol.
Referenced by lime::Streamer::AlignRxTSP(), lime::LMS7002M::IsSynced(), lime::Streamer::RstRxIQGen(), SetExtLoopback(), lime::FPGA_Mini::SetInterfaceFreq(), and lime::LMS7002M::SPI_read_batch().
template<typename ReadType > int lime::IConnection::ReadRegister (const uint32_t addr, ReadType & data)
Read a single device register.
Definition at line 336 of file IConnection.h.
Referenced by BoardLoopbackStore::BoardLoopbackStore(), computeGoertzel(), lime::LMS7_LimeSDR_mini::Init(), SoapyLMS7::readRegister(), lime::ConnectionNovenaRF7::ReceivePacketsLoop(), lime::Streamer::ReceivePacketsLoop(), SetExtLoopback(), lime::LMS7_LimeSDR_mini::SetPath(), and lime::Streamer::UpdateThreads().
int IConnection::ReadRegisters (const uint32_t * addrs, uint32_t * data, const size_t size) virtual
Bulk read device registers.
ReadRegisters() writes multiple registers and supports 32-bit addresses and data. ReadRegisters() can support multiple devices by dispatching based on the address.
Parameters
addrs an array of 32-bit register addresses
[out] data an array of 32-bit register data
size the number of entries in addrs and data
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 191 of file IConnection.cpp.
References lime::ReportError().
Referenced by lime::Streamer::AlignRxRF(), and readGoertzelValues().
int IConnection::ReceiveData (char * buffer, int length, int epIndex, int timeout = 100) virtual
Reimplemented in lime::ConnectionFX3, and lime::ConnectionXillybus.
Definition at line 75 of file IConnection.cpp.
Referenced by lime::Streamer::AlignRxTSP(), and lime::Streamer::GetPhaseOffset().
int IConnection::ResetStreamBuffers () virtual
Read raw stream data from device streaming port.
Parameters
buffer read buffer pointer
length number of bytes to read
epIndex endpoint identifier?
timeout_ms timeout in milliseconds
Reimplemented in lime::ConnectionFX3, and lime::ConnectionFT601.
Definition at line 127 of file IConnection.cpp.
Referenced by lime::Streamer::AlignRxTSP(), lime::Streamer::GetPhaseOffset(), lime::FPGA_Mini::ReadRawStreamData(), and lime::Streamer::UpdateThreads().
int IConnection::SendData (const char * buffer, int length, int epIndex, int timeout = 100) virtual
Reimplemented in lime::ConnectionFX3, and lime::ConnectionXillybus.
Definition at line 79 of file IConnection.cpp.
void IConnection::SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Definition at line 112 of file IConnection.cpp.
References callback, and callback_logData.
int IConnection::TransactSPI (const int addr, const uint32_t * writeData, uint32_t * readData, const size_t size) virtual
Bulk SPI write/read transaction.
The transactSPI function is capable of bulk writes and bulk reads of SPI registers in an arbitrary IC (up to 32-bits per transaction).
The readData parameter may be NULL to indicate a write-only operation, the underlying implementation may be able to optimize out the readback.
Parameters
addr the SPI device address
writeData SPI bits to write out
[out] readData stores readback data
size the number of SPI transactions
Returns
the transaction success state
Reimplemented in lime::LMS64CProtocol, and lime::ConnectionSTREAM_UNITE.
Definition at line 47 of file IConnection.cpp.
References lime::ReportError().
Referenced by lime::LMS7_Device::SetClockFreq(), SPI_read(), SPI_read_batch(), SPI_write(), and SPI_write_batch().
bool IConnection::WaitForReading (int contextHandle, unsigned int timeout_ms) virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 101 of file IConnection.cpp.
Referenced by lime::FPGA_Mini::ReadRawStreamData(), and lime::Streamer::ReceivePacketsLoop().
bool IConnection::WaitForSending (int contextHandle, uint32_t timeout_ms) virtual
Reimplemented in lime::ConnectionFX3, lime::ConnectionFT601, and lime::ConnectionXillybus.
Definition at line 88 of file IConnection.cpp.
Referenced by lime::Streamer::TransmitPacketsLoop().
int IConnection::WriteI2C (const int addr, const std::string & data) virtual
Write to an available I2C slave.
Parameters
addr the address of the slave
data an array of bytes write out
Returns
the transaction success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 52 of file IConnection.cpp.
References lime::ReportError().
virtual int lime::IConnection::WriteLMS7002MSPI (const uint32_t * writeData, size_t size, unsigned periphID = 0) pure virtual
Implemented in lime::LMS64CProtocol.
Referenced by lime::Streamer::AlignRxTSP(), lime::Streamer::RstRxIQGen(), lime::FPGA_Mini::SetInterfaceFreq(), and lime::LMS7002M::SPI_write_batch().
int IConnection::WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
Definition at line 197 of file IConnection.cpp.
References WriteRegisters().
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), lime::Streamer::AlignRxTSP(), lime::Streamer::GetChirpTimePeriod(), lime::Streamer::GetChirpTimeStamp(), lime::Streamer::GetHardwareTimestamp(), lime::FPGA_Mini::ReadRawStreamData(), lime::ConnectionNovenaRF7::ReceivePacketsLoop(), SetExtLoopback(), lime::FPGA_Mini::SetInterfaceFreq(), lime::LMS7_LimeSDR_mini::SetPath(), lime::Streamer::UpdateThreads(), and SoapyLMS7::writeRegister().
int IConnection::WriteRegisters (const uint32_t * addrs, const uint32_t * data, const size_t size) virtual
Bulk write device registers.
WriteRegisters() writes multiple registers and supports 32-bit addresses and data. WriteRegisters() can support multiple devices by dispatching based on the address.
Parameters
addrs an array of 32-bit register addresses
data an array of 32-bit register data
size the number of entries in addrs and data
Returns
the operation success state
Reimplemented in lime::LMS64CProtocol.
Definition at line 185 of file IConnection.cpp.
References lime::ReportError().
Referenced by computeGoertzel(), loadGoertzelCoefficients(), lime::Streamer::ReceivePacketsLoop(), lime::Streamer::UpdateThreads(), and WriteRegister().
Friends And Related Function Documentation
friend class ConnectionRegistry friend
Definition at line 331 of file IConnection.h.
Member Data Documentation
ConnectionHandle lime::IConnection::_handle private
Definition at line 332 of file IConnection.h.
Referenced by GetHandle().
std::function<void(bool, const unsigned char*, const unsigned int)> lime::IConnection::callback_logData protected
Definition at line 328 of file IConnection.h.
Referenced by IConnection(), SetDataLogCallback(), and lime::LMS64CProtocol::TransferPacket().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/IConnection.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/IConnection.cpp