LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/ConnectionRegistry.cpp File Reference
ConnectionRegistry.cpp File Reference
Implementation of connection registry.
#include "ConnectionRegistry.h"
#include "IConnection.h"
#include <mutex>
#include <map>
#include <memory>
#include <iostream>
#include <iso646.h>
Functions
void __loadAllConnections (void)
static std::mutex & registryMutex (void)
Variables
static std::map< std::string, ConnectionRegistryEntry * > registryEntries
Detailed Description
Implementation of connection registry.
Author
Lime Microsystems (www.limemicro.com)
Definition in file ConnectionRegistry.cpp.
Function Documentation
void __loadAllConnections (void)
Definition at line 20 of file BuiltinConnections.in.cpp.
References __loadConnectionEVB7COMEntry(), __loadConnectionFT601Entry(), __loadConnectionFX3Entry(), __loadConnectionNovenaRF7Entry(), __loadConnectionSTREAM_UNITEEntry(), and __loadConnectionXillybusEntry().
Referenced by lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::makeConnection(), and lime::ConnectionRegistry::moduleNames().
static std::mutex& registryMutex (void) static
Definition at line 21 of file ConnectionRegistry.cpp.
Referenced by lime::ConnectionRegistryEntry::ConnectionRegistryEntry(), lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::freeConnection(), lime::ConnectionRegistry::makeConnection(), lime::ConnectionRegistry::moduleNames(), and lime::ConnectionRegistryEntry::~ConnectionRegistryEntry().
Variable Documentation
std::map<std::string, ConnectionRegistryEntry *> registryEntries static
Definition at line 27 of file ConnectionRegistry.cpp.