LimeSuite-UML: LMS_Programing_wxgui Class Reference
LMS_Programing_wxgui Class Reference
#include <LMS_Programing_wxgui.h>
Public Member Functions
LMS_Programing_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_(""), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int style=0, wxString name=wxEmptyString)
virtual void SetConnection (lms_device_t *port)
virtual ~LMS_Programing_wxgui ()
Protected Member Functions
void DoProgramming ()
Static Protected Member Functions
static bool OnProgrammingCallback (int bsent, int btotal, const char *progressMsg)
static bool test (int bsent, int btotal, const char *progressMsg)
Protected Attributes
wxChoice * cmbDevice
wxStaticText * lblProgressPercent
wxStaticText * StaticText2
wxGauge * progressBar
wxStaticText * lblFilename
wxStaticText * StaticText1
wxStaticText * StaticText3
wxButton * btnStartStop
wxButton * btnOpen
bool btnOpenEnb
std::vector< char > mProgramData
lms_device_t * lmsControl
std::atomic< bool > mProgrammingInProgress
std::atomic< bool > mAbortProgramming
std::thread mWorkerThread
Static Protected Attributes
static LMS_Programing_wxgui * obj_ptr =nullptr
static const long ID_PROGRAMING_FINISHED_EVENT = wxNewId()
static const long ID_PROGRAMING_STATUS_EVENT = wxNewId()
static const long ID_BUTTON1 = wxNewId()
static const long ID_BUTTON2 = wxNewId()
static const long ID_GAUGE1 = wxNewId()
static const long ID_CHOICE2 = wxNewId()
static const long ID_CHOICE1 = wxNewId()
Private Member Functions
void OnbtnOpenClick (wxCommandEvent &event)
void OnbtnStartProgrammingClick (wxCommandEvent &event)
void OnAbortProgramming (wxCommandEvent &event)
void OnbtnProgFPGAClick (wxCommandEvent &event)
void OncmbDeviceSelect (wxCommandEvent &event)
Change programming modes according to selected device.
void OnProgramingStatusUpdate (wxCommandEvent &event)
Updates GUI elements with programming status.
void OnProgramingFinished (wxCommandEvent &event)
Detailed Description
Definition at line 21 of file LMS_Programing_wxgui.h.
Constructor & Destructor Documentation
LMS_Programing_wxgui::LMS_Programing_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = _(""), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int style = 0, wxString name = wxEmptyString)
Definition at line 32 of file LMS_Programing_wxgui.cpp.
References _T, OnbtnOpenClick(), OnbtnStartProgrammingClick(), OncmbDeviceSelect(), OnProgramingFinished(), and OnProgramingStatusUpdate().
LMS_Programing_wxgui::~LMS_Programing_wxgui () virtual
Definition at line 86 of file LMS_Programing_wxgui.cpp.
References mAbortProgramming, mProgrammingInProgress, and mWorkerThread.
Member Function Documentation
void LMS_Programing_wxgui::DoProgramming () protected
Definition at line 233 of file LMS_Programing_wxgui.cpp.
References cmbDevice, device, ID_PROGRAMING_FINISHED_EVENT, LMS_Program(), lmsControl, mProgramData, mProgrammingInProgress, obj_ptr, OnProgrammingCallback(), and status.
Referenced by OnbtnStartProgrammingClick().
void LMS_Programing_wxgui::OnAbortProgramming (wxCommandEvent & event) private
Definition at line 196 of file LMS_Programing_wxgui.cpp.
References mAbortProgramming.
Referenced by OnbtnStartProgrammingClick(), and OnProgramingFinished().
void LMS_Programing_wxgui::OnbtnOpenClick (wxCommandEvent & event) private
Definition at line 96 of file LMS_Programing_wxgui.cpp.
References cmbDevice, lime::GetDeviceName(), info, lblFilename, lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDR_QPCIE, lime::LMS_DEV_LIMESDRMINI, LMS_GetDeviceInfo(), and lmsControl.
Referenced by LMS_Programing_wxgui().
void LMS_Programing_wxgui::OnbtnProgFPGAClick (wxCommandEvent & event) private
void LMS_Programing_wxgui::OnbtnStartProgrammingClick (wxCommandEvent & event) private
Definition at line 128 of file LMS_Programing_wxgui.cpp.
References btnOpen, btnStartStop, cmbDevice, DoProgramming(), lblFilename, mAbortProgramming, mProgramData, mWorkerThread, and OnAbortProgramming().
Referenced by LMS_Programing_wxgui(), and OnProgramingFinished().
void LMS_Programing_wxgui::OncmbDeviceSelect (wxCommandEvent & event) private
Change programming modes according to selected device.
Definition at line 172 of file LMS_Programing_wxgui.cpp.
References btnOpen, btnOpenEnb, cmbDevice, lblFilename, and StaticText1.
Referenced by LMS_Programing_wxgui(), and SetConnection().
void LMS_Programing_wxgui::OnProgramingFinished (wxCommandEvent & event) private
Definition at line 186 of file LMS_Programing_wxgui.cpp.
References btnOpen, btnOpenEnb, btnStartStop, mWorkerThread, OnAbortProgramming(), and OnbtnStartProgrammingClick().
Referenced by LMS_Programing_wxgui().
void LMS_Programing_wxgui::OnProgramingStatusUpdate (wxCommandEvent & event) private
Updates GUI elements with programming status.
Definition at line 252 of file LMS_Programing_wxgui.cpp.
References lblProgressPercent, and progressBar.
Referenced by LMS_Programing_wxgui().
bool LMS_Programing_wxgui::OnProgrammingCallback (int bsent, int btotal, const char * progressMsg) static protected
Definition at line 220 of file LMS_Programing_wxgui.cpp.
References ID_PROGRAMING_STATUS_EVENT, mAbortProgramming, and obj_ptr.
Referenced by DoProgramming().
void LMS_Programing_wxgui::SetConnection (lms_device_t * port) virtual
Definition at line 201 of file LMS_Programing_wxgui.cpp.
References cmbDevice, i, LMS_GetProgramModes(), lmsControl, obj_ptr, OncmbDeviceSelect(), and port.
Referenced by LMS7SuiteAppFrame::OnShowPrograming(), and LMS7SuiteAppFrame::UpdateConnections().
static bool LMS_Programing_wxgui::test (int bsent, int btotal, const char * progressMsg) static protected
Member Data Documentation
wxButton* LMS_Programing_wxgui::btnOpen protected
Definition at line 37 of file LMS_Programing_wxgui.h.
Referenced by OnbtnStartProgrammingClick(), OncmbDeviceSelect(), and OnProgramingFinished().
bool LMS_Programing_wxgui::btnOpenEnb protected
Definition at line 38 of file LMS_Programing_wxgui.h.
Referenced by OncmbDeviceSelect(), and OnProgramingFinished().
wxButton* LMS_Programing_wxgui::btnStartStop protected
Definition at line 36 of file LMS_Programing_wxgui.h.
Referenced by OnbtnStartProgrammingClick(), and OnProgramingFinished().
wxChoice* LMS_Programing_wxgui::cmbDevice protected
Definition at line 29 of file LMS_Programing_wxgui.h.
Referenced by DoProgramming(), OnbtnOpenClick(), OnbtnStartProgrammingClick(), OncmbDeviceSelect(), and SetConnection().
const long LMS_Programing_wxgui::ID_BUTTON1 = wxNewId() static protected
Definition at line 51 of file LMS_Programing_wxgui.h.
const long LMS_Programing_wxgui::ID_BUTTON2 = wxNewId() static protected
Definition at line 52 of file LMS_Programing_wxgui.h.
const long LMS_Programing_wxgui::ID_CHOICE1 = wxNewId() static protected
Definition at line 55 of file LMS_Programing_wxgui.h.
const long LMS_Programing_wxgui::ID_CHOICE2 = wxNewId() static protected
Definition at line 54 of file LMS_Programing_wxgui.h.
const long LMS_Programing_wxgui::ID_GAUGE1 = wxNewId() static protected
Definition at line 53 of file LMS_Programing_wxgui.h.
const long LMS_Programing_wxgui::ID_PROGRAMING_FINISHED_EVENT = wxNewId() static protected
Definition at line 49 of file LMS_Programing_wxgui.h.
Referenced by DoProgramming().
const long LMS_Programing_wxgui::ID_PROGRAMING_STATUS_EVENT = wxNewId() static protected
Definition at line 50 of file LMS_Programing_wxgui.h.
Referenced by OnProgrammingCallback().
wxStaticText* LMS_Programing_wxgui::lblFilename protected
Definition at line 33 of file LMS_Programing_wxgui.h.
Referenced by OnbtnOpenClick(), OnbtnStartProgrammingClick(), and OncmbDeviceSelect().
wxStaticText* LMS_Programing_wxgui::lblProgressPercent protected
Definition at line 30 of file LMS_Programing_wxgui.h.
Referenced by OnProgramingStatusUpdate().
lms_device_t* LMS_Programing_wxgui::lmsControl protected
Definition at line 44 of file LMS_Programing_wxgui.h.
Referenced by DoProgramming(), OnbtnOpenClick(), and SetConnection().
std::atomic<bool> LMS_Programing_wxgui::mAbortProgramming protected
Definition at line 46 of file LMS_Programing_wxgui.h.
Referenced by OnAbortProgramming(), OnbtnStartProgrammingClick(), OnProgrammingCallback(), and ~LMS_Programing_wxgui().
std::vector<char> LMS_Programing_wxgui::mProgramData protected
Definition at line 43 of file LMS_Programing_wxgui.h.
Referenced by DoProgramming(), and OnbtnStartProgrammingClick().
std::atomic<bool> LMS_Programing_wxgui::mProgrammingInProgress protected
Definition at line 45 of file LMS_Programing_wxgui.h.
Referenced by DoProgramming(), and ~LMS_Programing_wxgui().
std::thread LMS_Programing_wxgui::mWorkerThread protected
Definition at line 47 of file LMS_Programing_wxgui.h.
Referenced by OnbtnStartProgrammingClick(), OnProgramingFinished(), and ~LMS_Programing_wxgui().
LMS_Programing_wxgui * LMS_Programing_wxgui::obj_ptr =nullptr static protected
Definition at line 48 of file LMS_Programing_wxgui.h.
Referenced by DoProgramming(), OnProgrammingCallback(), and SetConnection().
wxGauge* LMS_Programing_wxgui::progressBar protected
Definition at line 32 of file LMS_Programing_wxgui.h.
Referenced by OnProgramingStatusUpdate().
wxStaticText* LMS_Programing_wxgui::StaticText1 protected
Definition at line 34 of file LMS_Programing_wxgui.h.
Referenced by OncmbDeviceSelect().
wxStaticText* LMS_Programing_wxgui::StaticText2 protected
Definition at line 31 of file LMS_Programing_wxgui.h.
wxStaticText* LMS_Programing_wxgui::StaticText3 protected
Definition at line 35 of file LMS_Programing_wxgui.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/LMS_Programing/LMS_Programing_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/LMS_Programing/LMS_Programing_wxgui.cpp