LimeSuite-UML: lime::ConnectionFX3Entry Class Reference
lime::ConnectionFX3Entry Class Reference
#include <ConnectionFX3.h>
Public Member Functions
ConnectionFX3Entry (void)
virtual ~ConnectionFX3Entry (void)
std::vector< ConnectionHandle > enumerate (const ConnectionHandle &hint)
IConnection * make (const ConnectionHandle &handle)
Public Member Functions inherited from lime::ConnectionRegistryEntry
ConnectionRegistryEntry (const std::string &name)
virtual ~ConnectionRegistryEntry (void)
Unregister a connection type.
Protected Attributes
void * ctx
Detailed Description
Definition at line 157 of file ConnectionFX3.h.
Constructor & Destructor Documentation
ConnectionFX3Entry::ConnectionFX3Entry (void)
Definition at line 32 of file ConnectionFX3Entry.cpp.
References ctx, and lime::error().
ConnectionFX3Entry::~ConnectionFX3Entry (void) virtual
Definition at line 49 of file ConnectionFX3Entry.cpp.
References ctx.
Member Function Documentation
std::vector< ConnectionHandle > ConnectionFX3Entry::enumerate (const ConnectionHandle & hint) virtual
A discovery function takes a connection handle hint and returns a list of identifiers that can be used to create connection with makeConnection().
Parameters
hint an optional connection handle with some fields filled-in
Returns
a list of handles which can be used to make a connection
Implements lime::ConnectionRegistryEntry.
Reimplemented in lime::ConnectionSTREAM_UNITEEntry.
Definition at line 58 of file ConnectionFX3Entry.cpp.
References lime::ConnectionHandle::addr, ctx, device, lime::error(), i, lime::ConnectionHandle::index, lime::ConnectionHandle::media, lime::ConnectionHandle::name, lime::ConnectionHandle::serial, and string().
Referenced by lime::ConnectionSTREAM_UNITEEntry::enumerate().
IConnection * ConnectionFX3Entry::make (const ConnectionHandle & handle) virtual
A factory function creates a connection from a connection handle.
Parameters
handle a connection handle with fields filled-in
Returns
a pointer to a connection instance
Implements lime::ConnectionRegistryEntry.
Reimplemented in lime::ConnectionSTREAM_UNITEEntry.
Definition at line 165 of file ConnectionFX3Entry.cpp.
References lime::ConnectionHandle::addr, ctx, lime::ConnectionHandle::index, and lime::ConnectionHandle::serial.
Member Data Documentation
void* lime::ConnectionFX3Entry::ctx protected
Definition at line 166 of file ConnectionFX3.h.
Referenced by ConnectionFX3Entry(), enumerate(), lime::ConnectionSTREAM_UNITEEntry::make(), make(), and ~ConnectionFX3Entry().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFX3/ConnectionFX3.h
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFX3/ConnectionFX3Entry.cpp