LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/rounding.c File Reference
rounding.c File Reference
#include <math.h>
#include <stdio.h>
#include "rounding.h"
Functions
void int2csd (int a, int cprec, int csdprec, int *bincode, int *csdcode, int *csdcoder)
int csd2int (int cprec, int *code)
void round2int (double *a, double *b, int n, int cprec)
void round2csd (double *a, double *b, int n, int cprec, int csdprec, int **bincode, int **csdcode, int **csdcoder)
void printcode (int **code, int n, int cprec)
void print_cses_code (int **xpx, int **xmx, int **x, int n, int cprec)
void csesh (int **code, int n, int cprec, int **xpx, int **xmx, int **x)
Function Documentation
int csd2int (int cprec, int * code)
Definition at line 246 of file rounding.c.
References dfilter::a, and i.
Referenced by print_cses_code(), printcode(), and round2csd().
void csesh (int ** code, int n, int cprec, int ** xpx, int ** xmx, int ** x)
Definition at line 260 of file rounding.c.
References i, k, and dfilter::n.
void int2csd (int a, int cprec, int csdprec, int * bincode, int * csdcode, int * csdcoder)
Definition at line 197 of file rounding.c.
References i.
Referenced by round2csd().
void print_cses_code (int ** xpx, int ** xmx, int ** x, int n, int cprec)
Definition at line 121 of file rounding.c.
References csd2int(), h, i, and dfilter::n.
void printcode (int ** code, int n, int cprec)
Definition at line 53 of file rounding.c.
References csd2int(), h, i, and dfilter::n.
void round2csd (double * a, double * b, int n, int cprec, int csdprec, int ** bincode, int ** csdcode, int ** csdcoder)
Definition at line 35 of file rounding.c.
References csd2int(), i, int(), int2csd(), k, and dfilter::n.
Referenced by lms().
void round2int (double * a, double * b, int n, int cprec)
Definition at line 20 of file rounding.c.
References i, int(), k, and dfilter::n.
Referenced by lms().