LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/utilities/pll_sweep.cpp File Reference
pll_sweep.cpp File Reference
#include "lms7_device.h"
#include <iostream>
#include <iomanip>
#include <getopt.h>
#include <string>
#include <algorithm>
#include <cctype>
#include <fstream>
#include <chrono>
#include "FPGA_common.h"
#include "Logger.h"
Functions
bool ConfigureCGEN (LMS7_Device *device, double freqMHz)
int printHelp (void)
void log_func (const lime::LogLevel level, const char *message)
int main (int argc, char **argv)
Variables
auto t1 = chrono::high_resolution_clock::now()
auto t2 = chrono::high_resolution_clock::now()
int log_level = 3
Function Documentation
bool ConfigureCGEN (LMS7_Device * device, double freqMHz)
Definition at line 172 of file pll_sweep.cpp.
References lime::LMS7002M::Get_SPI_Reg_bits(), lime::LMS7002M::GetActiveChannelIndex(), lime::LMS7_Device::GetFPGA(), lime::LMS7_Device::GetLMS(), lime::LMS7002M::GetReferenceClk_TSP(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, lms(), LMS7param, MAC, lime::LMS7002M::Modify_SPI_Reg_bits(), lime::LMS7002M::Rx, lime::LMS7002M::SetInterfaceFrequency(), status, and lime::LMS7002M::Tx.
Referenced by main().
void log_func (const lime::LogLevel level, const char * message)
Definition at line 25 of file pll_sweep.cpp.
References log_level.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 31 of file pll_sweep.cpp.
References c, ConfigureCGEN(), lime::LMS7_Device::CreateDevice(), device, freq, lime::LMS7_Device::GetInfo(), getopt_long(), i, info, lime::LMS7_Device::Init(), lime::LMS7_Device::LoadConfig(), log_func(), log_level, no_argument, optarg, printHelp(), lime::registerLogHandler(), and required_argument.
int printHelp (void)
Definition at line 209 of file pll_sweep.cpp.
Referenced by main().
Variable Documentation
int log_level = 3
Definition at line 23 of file pll_sweep.cpp.
Referenced by log_func(), and main().
auto t1 = chrono::high_resolution_clock::now()
Definition at line 16 of file pll_sweep.cpp.
Referenced by computeGoertzel(), DCIQ(), Filters(), main(), MCU_UploadProgram(), MCU_WaitForStatus(), lms7002_pnlR3_view::MCU_WaitForStatus(), lms7suiteApp::OnInit(), lime::MCU_BD::Program_MCU(), lime::LMS64CProtocol::ProgramWrite(), lime::RingFIFO::push_samples(), lime::ConnectionXillybus::Read(), lime::ConnectionXillybus::ReceiveData(), lime::ConnectionNovenaRF7::ReceivePacketsLoop(), lime::Streamer::ReceivePacketsLoop(), lime::ConnectionXillybus::SendData(), lime::FPGA::SetPllClock(), lime::FPGA::SetPllFrequency(), lime::Streamer::TransmitPacketsLoop(), lms7002_mainPanel::UpdateGUI(), lms7002_mainPanel::UpdateVisiblePanel(), lime::MCU_BD::WaitForMCU(), lime::ConnectionFT601::WaitForReading(), lime::ConnectionFX3::WaitForReading(), lime::ConnectionFT601::WaitForSending(), lime::ConnectionFX3::WaitForSending(), and lime::ConnectionXillybus::Write().
auto t2 = chrono::high_resolution_clock::now()
Definition at line 17 of file pll_sweep.cpp.
Referenced by computeGoertzel(), DCIQ(), Filters(), main(), MCU_UploadProgram(), MCU_WaitForStatus(), lms7002_pnlR3_view::MCU_WaitForStatus(), lime::MCU_BD::Program_MCU(), lime::LMS64CProtocol::ProgramWrite(), lime::RingFIFO::push_samples(), lime::ConnectionNovenaRF7::ReceivePacketsLoop(), lime::Streamer::ReceivePacketsLoop(), lime::FPGA::SetPllClock(), lime::FPGA::SetPllFrequency(), TEST_F(), lime::Streamer::TransmitPacketsLoop(), lms7002_mainPanel::UpdateGUI(), lms7002_mainPanel::UpdateVisiblePanel(), lime::MCU_BD::WaitForMCU(), lime::ConnectionFT601::WaitForReading(), lime::ConnectionFX3::WaitForReading(), lime::ConnectionFT601::WaitForSending(), and lime::ConnectionFX3::WaitForSending().