LimeSuite-UML: lime::MCU_BD Class Reference
lime::MCU_BD Class Reference
#include <MCU_BD.h>
Classes
struct ProgressInfo
Public Types
enum MCU_ERROR_CODES {
MCU_NO_ERROR = 0, MCU_ERROR, MCU_CGEN_TUNE_FAILED, MCU_SXR_TUNE_FAILED,
MCU_SXT_TUNE_FAILED, MCU_LOOPBACK_SIGNAL_WEAK, MCU_INVALID_RX_PATH, MCU_INVALID_TX_BAND,
MCU_RX_LPF_OUT_OF_RANGE, MCU_RX_INVALID_TIA, MCU_TX_LPF_OUT_OF_RANGE, MCU_PROCEDURE_DISABLED,
MCU_R_CTL_LPF_LIMIT_REACHED, MCU_CFB_TIA_RFE_LIMIT_REACHED, MCU_RCAL_LPF_LIMIT_REACHED, MCU_ERROR_CODES_COUNT
}
enum OperationStatus { SUCCESS = 0, FAILURE, TIMEOUT }
enum MCU_Parameter { MCU_REF_CLK, MCU_BW, MCU_EXT_LOOPBACK_PAIR }
Public Member Functions
ProgressInfo GetProgressInfo () const
Returns information about programming or reading data progress.
MCU_BD ()
virtual ~MCU_BD ()
std::string GetProgramFilename () const
void RunProcedure (uint8_t id)
Starts algorithm in MCU.
void SetParameter (MCU_Parameter param, float value)
int WaitForMCU (uint32_t timeout_ms)
Waits for MCU to finish executing program.
uint8_t ReadMCUProgramID ()
OperationStatus SetDebugMode (bool enabled, IConnection::MCU_PROG_MODE mode)
Switches MCU into debug mode, MCU program execution is halted.
OperationStatus readIRAM (const uint8_t *addr, uint8_t *values, const uint8_t count)
OperationStatus writeIRAM (const uint8_t *addr, const uint8_t *values, const uint8_t count)
void Wait_CLK_Cycles (int data)
void mSPI_write (unsigned short addr_reg, unsigned short data_reg)
unsigned short mSPI_read (unsigned short addr_reg)
int Three_byte_command (unsigned char data1, unsigned char data2, unsigned char data3, unsigned char *rdata1, unsigned char *rdata2, unsigned char *rdata3)
int GetProgramCode (const char *inFileName, bool bin=false)
Read program code from file into memory.
int Change_MCUFrequency (unsigned char data)
int Read_IRAM ()
int Erase_IRAM ()
int Read_SFR ()
int Program_MCU (int m_iMode1, int m_iMode0)
Upload program code from memory into MCU.
int Program_MCU (const uint8_t *binArray, const IConnection::MCU_PROG_MODE mode)
void Reset_MCU ()
void RunTest_MCU (int m_iMode1, int m_iMode0, unsigned short test_code, int m_iDebug)
int RunProductionTest_MCU ()
void RunFabTest_MCU (int m_iMode1, int m_iMode0, int m_iDebug)
void DebugModeSet_MCU (int m_iMode1, int m_iMode0)
void DebugModeExit_MCU (int m_iMode1, int m_iMode0)
int ResetPC_MCU ()
int RunInstr_MCU (unsigned short *pPCVAL)
void Initialize (IConnection *pSerPort, unsigned chipID=0, unsigned rom_size=0)
Static Public Member Functions
static const char * MCUStatusMessage (const uint8_t code)
Public Attributes
int m_iLoopTries
unsigned char m_IRAM [256]
unsigned char m_SFR [256]
unsigned char byte_array [cMaxFWSize]
lime::IConnection::ProgrammingCallback callback
Static Public Attributes
static const int cMaxFWSize = 1024 * 16
Protected Member Functions
int WaitUntilWritten ()
int ReadOneByte (unsigned char *data)
int One_byte_command (unsigned short data1, unsigned char *rdata1)
unsigned int formREG2command (int m_iExt5, int m_iExt4, int m_iExt3, int m_iExt2, int m_iMode1, int m_iMode0)
Protected Attributes
std::string mLoadedProgramFilename
std::atomic_ushort stepsDone
std::atomic_ushort stepsTotal
std::atomic_bool aborted
IConnection * m_serPort
int m_bLoadedDebug
int m_bLoadedProd
int byte_array_size
unsigned mChipID
Detailed Description
Definition at line 19 of file MCU_BD.h.
Member Enumeration Documentation
enum lime::MCU_BD::MCU_ERROR_CODES
Enumerator
MCU_NO_ERROR
MCU_ERROR
MCU_CGEN_TUNE_FAILED
MCU_SXR_TUNE_FAILED
MCU_SXT_TUNE_FAILED
MCU_LOOPBACK_SIGNAL_WEAK
MCU_INVALID_RX_PATH
MCU_INVALID_TX_BAND
MCU_RX_LPF_OUT_OF_RANGE
MCU_RX_INVALID_TIA
MCU_TX_LPF_OUT_OF_RANGE
MCU_PROCEDURE_DISABLED
MCU_R_CTL_LPF_LIMIT_REACHED
MCU_CFB_TIA_RFE_LIMIT_REACHED
MCU_RCAL_LPF_LIMIT_REACHED
MCU_ERROR_CODES_COUNT
Definition at line 22 of file MCU_BD.h.
enum lime::MCU_BD::MCU_Parameter
Enumerator
MCU_REF_CLK
MCU_BW
MCU_EXT_LOOPBACK_PAIR
Definition at line 64 of file MCU_BD.h.
enum lime::MCU_BD::OperationStatus
Enumerator
SUCCESS
FAILURE
TIMEOUT
Definition at line 43 of file MCU_BD.h.
Constructor & Destructor Documentation
MCU_BD::MCU_BD ()
Definition at line 22 of file MCU_BD.cpp.
References callback, and i.
MCU_BD::~MCU_BD () virtual
Definition at line 49 of file MCU_BD.cpp.
Member Function Documentation
int MCU_BD::Change_MCUFrequency (unsigned char data)
Definition at line 249 of file MCU_BD.cpp.
void MCU_BD::DebugModeExit_MCU (int m_iMode1, int m_iMode0)
Definition at line 941 of file MCU_BD.cpp.
void MCU_BD::DebugModeSet_MCU (int m_iMode1, int m_iMode0)
Definition at line 927 of file MCU_BD.cpp.
int MCU_BD::Erase_IRAM ()
Definition at line 296 of file MCU_BD.cpp.
References i.
unsigned int MCU_BD::formREG2command (int m_iExt5, int m_iExt4, int m_iExt3, int m_iExt2, int m_iMode1, int m_iMode0) protected
Definition at line 983 of file MCU_BD.cpp.
int MCU_BD::GetProgramCode (const char * inFileName, bool bin = false)
Read program code from file into memory.
Parameters
inFileName source file path
bin binary or hex file
Returns
0:success, -1:file not found
Definition at line 67 of file MCU_BD.cpp.
References MCU_File::FileOpened(), MCU_File::GetByte(), i, and MCU_File::ReadHex().
std::string MCU_BD::GetProgramFilename () const
Definition at line 994 of file MCU_BD.cpp.
MCU_BD::ProgressInfo MCU_BD::GetProgressInfo () const
Returns information about programming or reading data progress.
Definition at line 974 of file MCU_BD.cpp.
References lime::MCU_BD::ProgressInfo::aborted, info, lime::MCU_BD::ProgressInfo::stepsDone, and lime::MCU_BD::ProgressInfo::stepsTotal.
void MCU_BD::Initialize (IConnection * pSerPort, unsigned chipID = 0, unsigned rom_size = 0)
Definition at line 54 of file MCU_BD.cpp.
Referenced by lime::LMS7002M::LMS7002M().
const char * MCU_BD::MCUStatusMessage (const uint8_t code) static
Definition at line 1165 of file MCU_BD.cpp.
References MCU_ERROR_CODES_COUNT, and MCU_ErrorMessages.
Referenced by lime::LMS7002M::TuneRxFilter(), and lime::LMS7002M::TuneTxFilter().
unsigned short MCU_BD::mSPI_read (unsigned short addr_reg)
Definition at line 128 of file MCU_BD.cpp.
void MCU_BD::mSPI_write (unsigned short addr_reg, unsigned short data_reg)
Definition at line 117 of file MCU_BD.cpp.
int MCU_BD::One_byte_command (unsigned short data1, unsigned char * rdata1) protected
Definition at line 193 of file MCU_BD.cpp.
int MCU_BD::Program_MCU (int m_iMode1, int m_iMode0)
Upload program code from memory into MCU.
Returns
0:success, -1:failed
Definition at line 567 of file MCU_BD.cpp.
References mode.
Referenced by lime::LMS7_Device::MCU_AGCStart(), lime::LMS7_Device::Program(), lime::LMS7002M::SPI_read(), lime::LMS7002M::SPI_write(), lime::LMS7002M::TuneRxFilter(), and lime::LMS7002M::TuneTxFilter().
int MCU_BD::Program_MCU (const uint8_t * binArray, const IConnection::MCU_PROG_MODE mode)
Definition at line 581 of file MCU_BD.cpp.
References callback, i, lime::ReportError(), status, t1, and t2.
int MCU_BD::Read_IRAM ()
Definition at line 259 of file MCU_BD.cpp.
References i.
int MCU_BD::Read_SFR ()
Definition at line 330 of file MCU_BD.cpp.
References i.
MCU_BD::OperationStatus MCU_BD::readIRAM (const uint8_t * addr, uint8_t * values, const uint8_t count)
Definition at line 1102 of file MCU_BD.cpp.
References i.
uint8_t MCU_BD::ReadMCUProgramID ()
Definition at line 1139 of file MCU_BD.cpp.
Referenced by lime::LMS7_Device::MCU_AGCStart(), lime::LMS7002M::TuneRxFilter(), and lime::LMS7002M::TuneTxFilter().
int MCU_BD::ReadOneByte (unsigned char * data) protected
Definition at line 161 of file MCU_BD.cpp.
void MCU_BD::Reset_MCU ()
Definition at line 664 of file MCU_BD.cpp.
int MCU_BD::ResetPC_MCU ()
Definition at line 954 of file MCU_BD.cpp.
void MCU_BD::RunFabTest_MCU (int m_iMode1, int m_iMode0, int m_iDebug)
Definition at line 899 of file MCU_BD.cpp.
int MCU_BD::RunInstr_MCU (unsigned short * pPCVAL)
Definition at line 962 of file MCU_BD.cpp.
void MCU_BD::RunProcedure (uint8_t id)
Starts algorithm in MCU.
Definition at line 1001 of file MCU_BD.cpp.
Referenced by lime::LMS7_Device::MCU_AGCStart(), lime::LMS7_Device::MCU_AGCStop(), lime::LMS7002M::SPI_read(), lime::LMS7002M::SPI_write(), lime::LMS7002M::TuneRxFilter(), and lime::LMS7002M::TuneTxFilter().
int MCU_BD::RunProductionTest_MCU ()
Definition at line 672 of file MCU_BD.cpp.
void MCU_BD::RunTest_MCU (int m_iMode1, int m_iMode0, unsigned short test_code, int m_iDebug)
Definition at line 826 of file MCU_BD.cpp.
References i.
MCU_BD::OperationStatus MCU_BD::SetDebugMode (bool enabled, IConnection::MCU_PROG_MODE mode)
Switches MCU into debug mode, MCU program execution is halted.
Parameters
mode MCU memory initialization mode
Returns
Operation status
Definition at line 1082 of file MCU_BD.cpp.
void MCU_BD::SetParameter (MCU_Parameter param, float value)
Definition at line 1038 of file MCU_BD.cpp.
References lime::debug(), i, inputRegs, int(), MCU_BW, MCU_EXT_LOOPBACK_PAIR, MCU_REF_CLK, and status.
Referenced by lime::LMS7_Device::MCU_AGCStart(), lime::LMS7002M::TuneRxFilter(), and lime::LMS7002M::TuneTxFilter().
int MCU_BD::Three_byte_command (unsigned char data1, unsigned char data2, unsigned char data3, unsigned char * rdata1, unsigned char * rdata2, unsigned char * rdata3)
Definition at line 215 of file MCU_BD.cpp.
void MCU_BD::Wait_CLK_Cycles (int data)
Definition at line 556 of file MCU_BD.cpp.
References i.
int MCU_BD::WaitForMCU (uint32_t timeout_ms)
Waits for MCU to finish executing program.
Returns
0 success, 255 idle, 244 running, else algorithm status
Definition at line 1019 of file MCU_BD.cpp.
References lime::debug(), t1, and t2.
Referenced by lime::LMS7002M::SPI_read(), lime::LMS7002M::SPI_write(), lime::LMS7002M::TuneRxFilter(), and lime::LMS7002M::TuneTxFilter().
int MCU_BD::WaitUntilWritten () protected
Definition at line 141 of file MCU_BD.cpp.
MCU_BD::OperationStatus MCU_BD::writeIRAM (const uint8_t * addr, const uint8_t * values, const uint8_t count)
Definition at line 1134 of file MCU_BD.cpp.
Member Data Documentation
std::atomic_bool lime::MCU_BD::aborted protected
Definition at line 80 of file MCU_BD.h.
unsigned char lime::MCU_BD::byte_array[cMaxFWSize]
Definition at line 103 of file MCU_BD.h.
int lime::MCU_BD::byte_array_size protected
Definition at line 88 of file MCU_BD.h.
lime::IConnection::ProgrammingCallback lime::MCU_BD::callback
Definition at line 126 of file MCU_BD.h.
Referenced by lime::LMS7_Device::Program().
const int lime::MCU_BD::cMaxFWSize = 1024 * 16 static
Definition at line 74 of file MCU_BD.h.
Referenced by lime::LMS7_Device::Program().
int lime::MCU_BD::m_bLoadedDebug protected
Definition at line 86 of file MCU_BD.h.
int lime::MCU_BD::m_bLoadedProd protected
Definition at line 87 of file MCU_BD.h.
int lime::MCU_BD::m_iLoopTries
Definition at line 60 of file MCU_BD.h.
unsigned char lime::MCU_BD::m_IRAM[256]
Definition at line 99 of file MCU_BD.h.
IConnection* lime::MCU_BD::m_serPort protected
Definition at line 85 of file MCU_BD.h.
unsigned char lime::MCU_BD::m_SFR[256]
Definition at line 101 of file MCU_BD.h.
unsigned lime::MCU_BD::mChipID protected
Definition at line 89 of file MCU_BD.h.
std::string lime::MCU_BD::mLoadedProgramFilename protected
Definition at line 77 of file MCU_BD.h.
std::atomic_ushort lime::MCU_BD::stepsDone protected
Definition at line 78 of file MCU_BD.h.
std::atomic_ushort lime::MCU_BD::stepsTotal protected
Definition at line 79 of file MCU_BD.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m_mcu/MCU_BD.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m_mcu/MCU_BD.cpp