LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionNovenaRF7/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionNovenaRF7/CMakeLists.txt File Reference
Functions
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ConnectionNovenaRF7) set(CONNECTION_NOVENARF7_SOURCES $
Function Documentation
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/ ConnectionNovenaRF7)
Definition at line 5 of file CMakeLists.txt.
References add_feature_info(), cmake_dependent_option(), ENABLE_NOVENARF7, endif(), include(), and target_sources().