LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/include/SoapySDR/Version.h File Reference
Version.h File Reference
Utility functions to query version information.
#include <SoapySDR/Config.h>
Macros
#define SOAPY_SDR_API_VERSION 0x00070000
#define SOAPY_SDR_ABI_VERSION "0.7"
#define SOAPY_SDR_API_HAS_MASKED_GPIO
#define SOAPY_SDR_API_HAS_CHANNEL_SENSORS
#define SOAPY_SDR_API_HAS_ERR_TO_STR
#define SOAPY_SDR_API_HAS_CORRECTIONS_QUERY
#define SOAPY_SDR_API_HAS_CLOCK_RATES_QUERY
#define SOAPY_SDR_API_HAS_AGC_MODE_QUERY
#define SOAPY_SDR_API_HAS_STREAM_ARG_INFO
#define SOAPY_SDR_API_HAS_SETTING_ARG_INFO
#define SOAPY_SDR_API_HAS_QUERY_SENSOR_INFO
#define SOAPY_SDR_API_HAS_QUERY_TUNE_ARG_INFO
#define SOAPY_SDR_API_HAS_NATIVE_STREAM_FORMAT
#define SOAPY_SDR_API_HAS_SET_LOG_LEVEL
#define SOAPY_SDR_API_HAS_FORMAT_DEFINES
#define SOAPY_SDR_API_HAS_CHANNEL_SETTINGS
#define SOAPY_SDR_API_HAS_GET_BANDWIDTH_RANGE
#define SOAPY_SDR_API_HAS_GET_CHANNEL_INFO
#define SOAPY_SDR_API_HAS_NAMED_REGISTER_API
#define SOAPY_SDR_API_HAS_NAMED_REGISTERS_API
#define SOAPY_SDR_API_HAS_RANGE_TYPE_STEP
#define SOAPY_SDR_API_HAS_GET_SAMPLE_RATE_RANGE
#define SOAPY_SDR_API_HAS_FREQUENCY_CORRECTION_API
Functions
SOAPY_SDR_API const char * SoapySDR_getAPIVersion (void)
SOAPY_SDR_API const char * SoapySDR_getABIVersion (void)
SOAPY_SDR_API const char * SoapySDR_getLibVersion (void)
Detailed Description
Utility functions to query version information.
Copyright
Copyright (c) 2014-2018 Josh Blum Copyright (c) 2016-2016 Bastille Networks SPDX-License-Identifier: BSL-1.0
Definition in file Version.h.
Macro Definition Documentation
#define SOAPY_SDR_ABI_VERSION "0.7"
ABI Version Information - incremented when the ABI is changed. The ABI version format is version[-extra]. The version comes from the associated library major.minor version. And extra is empty for releases but set on development branches. The ABI should remain constant across patch releases of the library.
Definition at line 38 of file Version.h.
Referenced by lateLoadNullDevice(), makeIConnection(), makeMyDevice(), SoapySDR::Registry::Registry(), and set().
#define SOAPY_SDR_API_HAS_AGC_MODE_QUERY
Compatibility define for AGC support check
Definition at line 68 of file Version.h.
#define SOAPY_SDR_API_HAS_CHANNEL_SENSORS
Compatibility define for channel sensors access API
Definition at line 48 of file Version.h.
#define SOAPY_SDR_API_HAS_CHANNEL_SETTINGS
Compatibility define for arbitrary channel settings
Definition at line 108 of file Version.h.
#define SOAPY_SDR_API_HAS_CLOCK_RATES_QUERY
Compatibility define for clock rates query API
Definition at line 63 of file Version.h.
#define SOAPY_SDR_API_HAS_CORRECTIONS_QUERY
Compatibility define for corrections support checks
Definition at line 58 of file Version.h.
#define SOAPY_SDR_API_HAS_ERR_TO_STR
Compatibility define for error to string function
Definition at line 53 of file Version.h.
#define SOAPY_SDR_API_HAS_FORMAT_DEFINES
Compatibility define for format header and defines
Definition at line 103 of file Version.h.
#define SOAPY_SDR_API_HAS_FREQUENCY_CORRECTION_API
Compatibility define for frequency correction API
Definition at line 143 of file Version.h.
#define SOAPY_SDR_API_HAS_GET_BANDWIDTH_RANGE
Compatibility define for get bandwidth range API
Definition at line 113 of file Version.h.
#define SOAPY_SDR_API_HAS_GET_CHANNEL_INFO
Compatibility define for get channel info API
Definition at line 118 of file Version.h.
#define SOAPY_SDR_API_HAS_GET_SAMPLE_RATE_RANGE
Compatibility define for get sample rate range API
Definition at line 138 of file Version.h.
#define SOAPY_SDR_API_HAS_MASKED_GPIO
Compatibility define for GPIO access API with masks
Definition at line 43 of file Version.h.
#define SOAPY_SDR_API_HAS_NAMED_REGISTER_API
Compatibility define for named register interface API
Definition at line 123 of file Version.h.
#define SOAPY_SDR_API_HAS_NAMED_REGISTERS_API
Compatibility define for named memory block interface API
Definition at line 128 of file Version.h.
#define SOAPY_SDR_API_HAS_NATIVE_STREAM_FORMAT
Compatibility define for querying native stream format
Definition at line 93 of file Version.h.
#define SOAPY_SDR_API_HAS_QUERY_SENSOR_INFO
Compatibility define for querying sensor info API
Definition at line 83 of file Version.h.
#define SOAPY_SDR_API_HAS_QUERY_TUNE_ARG_INFO
Compatibility define for querying tune args info
Definition at line 88 of file Version.h.
#define SOAPY_SDR_API_HAS_RANGE_TYPE_STEP
Compatibility define for step field in range type
Definition at line 133 of file Version.h.
#define SOAPY_SDR_API_HAS_SET_LOG_LEVEL
Compatibility define for setting the log level
Definition at line 98 of file Version.h.
#define SOAPY_SDR_API_HAS_SETTING_ARG_INFO
Compatibility define for querying setting argument info
Definition at line 78 of file Version.h.
#define SOAPY_SDR_API_HAS_STREAM_ARG_INFO
Compatibility define for querying stream argument info
Definition at line 73 of file Version.h.
#define SOAPY_SDR_API_VERSION 0x00070000
API version number which can be used as a preprocessor check. The format of the version number is encoded as follows: (major << 24) | (minor << 16) | (16 bit increment). Where the increment can be used to indicate implementation changes, fixes, or API additions within a minor release series.
The macro is typically used in an application as follows:
 #if defined(SOAPY_SDR_API_VERSION) && (SOAPY_SDR_API_VERSION >= 0x00001234)
 // Use a newer feature from the SoapySDR library API
 #endif
Definition at line 29 of file Version.h.
Function Documentation
SOAPY_SDR_API const char* SoapySDR_getABIVersion (void)
Get the ABI version string that the library was built against. A client can compare SOAPY_SDR_ABI_VERSION to getABIVersion() to check for ABI incompatibility before using the library. If the values are not equal then the client code was compiled against a different ABI than the library.
Definition at line 618 of file SoapySDR.py.
References SoapySDR::getABIVersion, SoapySDR::SoapySDR_getABIVersion(), and string().
Referenced by SoapySDR_getABIVersion().
SOAPY_SDR_API const char* SoapySDR_getAPIVersion (void)
Get the SoapySDR library API version as a string. The format of the version string is major.minor.increment, where the digits are taken directly from SOAPY_SDR_API_VERSION.
Definition at line 614 of file SoapySDR.py.
References SoapySDR::getAPIVersion, SoapySDR::SoapySDR_getAPIVersion(), and string().
Referenced by SoapySDR_getAPIVersion().
SOAPY_SDR_API const char* SoapySDR_getLibVersion (void)
Get the library version and build information string. The format of the version string is major.minor.patch-buildInfo. This function is commonly used to identify the software back-end to the user for command-line utilities and graphical applications.
Definition at line 622 of file SoapySDR.py.
References SoapySDR::getLibVersion, SoapySDR::SoapySDR_getLibVersion(), and string().
Referenced by SoapySDR_getLibVersion().