LimeSuite-UML: lms7002_pnlGains_view Class Reference
lms7002_pnlGains_view Class Reference
Implementing pnlGains_view.
#include <lms7002_pnlGains_view.h>
Public Member Functions
lms7002_pnlGains_view (wxWindow *parent)
Constructor.
lms7002_pnlGains_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
void OnAGCStateChange (wxCommandEvent &event)
Public Member Functions inherited from pnlGains_view
pnlGains_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxTAB_TRAVERSAL)
~pnlGains_view ()
Protected Member Functions
void ParameterChangeHandler (wxSpinEvent &event)
void ParameterChangeHandler (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlGains_view
wxCheckBox * chkTRX_GAIN_SRC
wxComboBox * cmbG_LNA_RFE
wxComboBox * cmbG_TIA_RFE
wxComboBox * cmbG_PGA_RBB
NumericSlider * cmbC_CTL_PGA_RBB
wxComboBox * cmbLOSS_LIN_TXPAD_TRF
wxComboBox * cmbLOSS_MAIN_TXPAD_TRF
NumericSlider * cmbCG_IAMP_TBB
wxCheckBox * chkAGC
wxStaticText * m_staticText360
wxTextCtrl * txtCrestFactor
Additional Inherited Members
Protected Types inherited from pnlGains_view
enum {
ID_EN_NEXTRX_RFE = 2048, ID_G_LNA_RFE, ID_G_TIA_RFE, ID_G_PGA_RBB,
ID_C_CTL_PGA_RBB, ID_LOSS_LIN_TXPAD_TRF, ID_LOSS_MAIN_TXPAD_TRF, ID_CG_IAMP_TBB
}
Detailed Description
Implementing pnlGains_view.
Definition at line 17 of file lms7002_pnlGains_view.h.
Constructor & Destructor Documentation
lms7002_pnlGains_view::lms7002_pnlGains_view (wxWindow * parent)
Constructor.
Definition at line 12 of file lms7002_pnlGains_view.cpp.
lms7002_pnlGains_view::lms7002_pnlGains_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 19 of file lms7002_pnlGains_view.cpp.
References CG_IAMP_TBB_R3, pnlGains_view::chkTRX_GAIN_SRC, pnlGains_view::cmbC_CTL_PGA_RBB, pnlGains_view::cmbCG_IAMP_TBB, pnlGains_view::cmbG_LNA_RFE, pnlGains_view::cmbG_PGA_RBB, pnlGains_view::cmbG_TIA_RFE, pnlGains_view::cmbLOSS_LIN_TXPAD_TRF, pnlGains_view::cmbLOSS_MAIN_TXPAD_TRF, g_lna_rfe_IndexValuePairs, G_LNA_RFE_R3, G_PGA_RBB_R3, g_tia_rfe_IndexValuePairs, G_TIA_RFE_R3, i, LMS7param, temp, TRX_GAIN_SRC, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlGains_view::Initialize (lms_device_t * pControl)
Definition at line 75 of file lms7002_pnlGains_view.cpp.
References pnlGains_view::chkTRX_GAIN_SRC, LMS7param, LMS_ReadParam(), lmsControl, and MASK.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlGains_view::OnAGCStateChange (wxCommandEvent & event) virtual
Reimplemented from pnlGains_view.
Definition at line 150 of file lms7002_pnlGains_view.cpp.
References pnlGains_view::chkAGC, lms(), lmsControl, lime::LMS7_Device::MCU_AGCStart(), lime::LMS7_Device::MCU_AGCStop(), and pnlGains_view::txtCrestFactor.
void lms7002_pnlGains_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlGains_view.
Definition at line 89 of file lms7002_pnlGains_view.cpp.
void lms7002_pnlGains_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlGains_view.
Definition at line 94 of file lms7002_pnlGains_view.cpp.
References pnlGains_view::chkTRX_GAIN_SRC, pnlGains_view::cmbC_CTL_PGA_RBB, pnlGains_view::cmbCG_IAMP_TBB, pnlGains_view::cmbG_LNA_RFE, pnlGains_view::cmbG_PGA_RBB, pnlGains_view::cmbG_TIA_RFE, pnlGains_view::cmbLOSS_LIN_TXPAD_TRF, pnlGains_view::cmbLOSS_MAIN_TXPAD_TRF, g_lna_rfe_IndexValuePairs, g_tia_rfe_IndexValuePairs, LMS7002_WXGUI::index2value(), LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlGains_view::UpdateGUI ()
Definition at line 129 of file lms7002_pnlGains_view.cpp.
References pnlGains_view::chkTRX_GAIN_SRC, pnlGains_view::cmbC_CTL_PGA_RBB, pnlGains_view::cmbCG_IAMP_TBB, pnlGains_view::cmbG_LNA_RFE, pnlGains_view::cmbG_PGA_RBB, pnlGains_view::cmbG_TIA_RFE, pnlGains_view::cmbLOSS_LIN_TXPAD_TRF, pnlGains_view::cmbLOSS_MAIN_TXPAD_TRF, g_lna_rfe_IndexValuePairs, G_LNA_RFE_R3, g_tia_rfe_IndexValuePairs, G_TIA_RFE_R3, LMS7param, LMS_ReadParam(), lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), LMS7002_WXGUI::value2index(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlGains_view::lmsControl protected
Definition at line 32 of file lms7002_pnlGains_view.h.
Referenced by Initialize(), OnAGCStateChange(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlGains_view::wndId2Enum protected
Definition at line 33 of file lms7002_pnlGains_view.h.
Referenced by lms7002_pnlGains_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlGains_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlGains_view.cpp