LimeSuite-UML: Parser Namespace Reference
Parser Namespace Reference
Functions
bool IsBlank (char)
bool IsDigit (char)
int getValue (FILE *, float *)
int getcoeffs (const char *, float *, int)
int getcoeffs2 (const char *, float *, float *, int)
void saveToFile (const char *, const float *, int)
Function Documentation
int Parser::getcoeffs (const char * filename, float * v, int max)
Definition at line 98 of file CoefficientFileParser.cpp.
References getValue(), and i.
Referenced by lms7002_dlgGFIR_Coefficients::OnLoadFromFile().
int Parser::getcoeffs2 (const char * filename, float * v1, float * v2, int max)
Definition at line 131 of file CoefficientFileParser.cpp.
References getValue(), and i.
int Parser::getValue (FILE * fp, float * v)
Definition at line 44 of file CoefficientFileParser.cpp.
References i, IsBlank(), and IsDigit().
Referenced by getcoeffs(), and getcoeffs2().
bool Parser::IsBlank (char c)
Definition at line 17 of file CoefficientFileParser.cpp.
References i.
Referenced by getValue().
bool Parser::IsDigit (char c)
Definition at line 29 of file CoefficientFileParser.cpp.
References i.
Referenced by getValue().
void Parser::saveToFile (const char * filename, const float * coefficients, int cCount)
Definition at line 170 of file CoefficientFileParser.cpp.
References i.
Referenced by lms7002_dlgGFIR_Coefficients::OnSaveToFile().