LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/lms7002m_calibrations.c File Reference
lms7002m_calibrations.c File Reference
#include "lms7002m_calibrations.h"
#include "LMS7002M_parameters_compact.h"
#include "spi.h"
#include "lms7002m_controls.h"
#include <math.h>
#include "mcu_defines.h"
#include "lms7002_regx51.h"
Classes
struct BinSearchParam
Macros
#define ENABLE_EXTERNAL_LOOPBACK 1
#define VERBOSE 0
#define PUSH_GMEASUREMENT_VALUES(value, rssi)
#define calibrationSXOffset_Hz 1e6
#define offsetNCO 0.1e6
#define calibUserBwDivider 5
Functions
int16_t clamp (int16_t value, int16_t minBound, int16_t maxBound)
static void FlipRisingEdge (const uint16_t addr, const uint8_t bits)
static bool IsPLLTuned ()
void LoadDC_REG_TX_IQ ()
void UpdateRSSIDelay ()
uint32_t GetRSSI ()
static void SetRxGFIR3Coefficients ()
int CheckSaturationTxRx (bool extLoopback)
void BinarySearch (BinSearchParam *args)
int16_t ReadAnalogDC (const uint16_t addr)
static void WriteAnalogDC (const uint16_t addr, int16_t value)
static void TxDcBinarySearch (BinSearchParam *args)
void AdjustAutoDC (const uint16_t address, bool tx)
void CalibrateRxDCAuto ()
void CalibrateTxDCAuto ()
void CalibrateIQImbalance (bool tx)
uint8_t SetupCGEN ()
uint8_t CalibrateTxSetup (bool extLoopback)
uint8_t CalibrateTx (bool extLoopback)
uint8_t CalibrateRxSetup (bool extLoopback)
uint8_t CheckSaturationRx (const float_type bandwidth_Hz, bool extLoopback)
uint8_t CalibrateRx (bool extLoopback, bool dcOnly)
Variables
float bandwidthRF = 5e6
uint16_t RSSIDelayCounter = 1
uint8_t extLoopbackPair = 0
float_type RefClk
Macro Definition Documentation
#define calibrationSXOffset_Hz 1e6
Definition at line 76 of file lms7002m_calibrations.c.
Referenced by CalibrateTx(), CalibrateTxSetup(), and CheckSaturationTxRx().
#define calibUserBwDivider 5
Definition at line 78 of file lms7002m_calibrations.c.
Referenced by CalibrateRx(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxSetup(), CheckSaturationRx(), and CheckSaturationTxRx().
#define ENABLE_EXTERNAL_LOOPBACK 1
Definition at line 12 of file lms7002m_calibrations.c.
#define offsetNCO 0.1e6
Definition at line 77 of file lms7002m_calibrations.c.
Referenced by CalibrateRx(), CalibrateRxSetup(), CalibrateTx(), CheckSaturationRx(), and CheckSaturationTxRx().
#define PUSH_GMEASUREMENT_VALUES (value, rssi)
Definition at line 71 of file lms7002m_calibrations.c.
Referenced by BinarySearch(), CheckSaturationRx(), CheckSaturationTxRx(), and TxDcBinarySearch().
#define VERBOSE 0
Definition at line 70 of file lms7002m_calibrations.c.
Function Documentation
void AdjustAutoDC (const uint16_t address, bool tx)
Definition at line 383 of file lms7002m_calibrations.c.
References clamp(), GetRSSI(), i, range, ReadAnalogDC(), and WriteAnalogDC().
Referenced by CalibrateRxDCAuto().
void BinarySearch (BinSearchParam * args)
Definition at line 275 of file lms7002m_calibrations.c.
References GetRSSI(), Modify_SPI_Reg_bits(), and PUSH_GMEASUREMENT_VALUES.
Referenced by CalibrateIQImbalance().
void CalibrateIQImbalance (bool tx)
Definition at line 570 of file lms7002m_calibrations.c.
References LMS7Parameter::address, BinarySearch(), dirName, GetRSSI(), BinSearchParam::maxValue, BinSearchParam::minValue, Modify_SPI_Reg_bits(), MSB_LSB, LMS7Parameter::msblsb, BinSearchParam::param, BinSearchParam::result, SPI_write(), GNUPlotPipe::write(), and GNUPlotPipe::writef().
Referenced by CalibrateRx(), and CalibrateTx().
uint8_t CalibrateRx (bool extLoopback, bool dcOnly)
Definition at line 1229 of file lms7002m_calibrations.c.
References bandwidthRF, CalibrateIQImbalance(), CalibrateRxDCAuto(), CalibrateRxSetup(), calibUserBwDivider, CheckSaturationRx(), CMIX_BYP_RXTSP, CMIX_SC_RXTSP, DCMODE, EN_INSHSW_LB1_RFE, EN_INSHSW_LB2_RFE, G_LNA_RFE, G_PGA_RBB, G_TIA_RFE, GCORRI_RXTSP, GCORRQ_RXTSP, Get_SPI_Reg_bits(), GetFrequencySX(), IQCORR_RXTSP, LMS7002M_Rx, MAC, MCU_NO_ERROR, MCU_PROCEDURE_DISABLED, Modify_SPI_Reg_bits(), MSB_LSB, offsetNCO, PD_DCDAC_RXA, PD_DCDAC_RXB, PD_LOCH_T2RBUF, PD_RLOOPB_1_RFE, PD_RLOOPB_2_RFE, PD_VCO, ReadAnalogDC(), SaveChipState(), SEL_PATH_RFE, SetNCOFrequency(), SPI_read(), SPI_write(), status, and UpdateRSSIDelay().
Referenced by DCIQ(), main(), and RunAGC().
void CalibrateRxDCAuto ()
Definition at line 412 of file lms7002m_calibrations.c.
References AdjustAutoDC(), DC_BYP_RXTSP, DCMODE, EN_G_TRF, GCORRQ_RXTSP, Get_SPI_Reg_bits(), GetRSSI(), MAC, Modify_SPI_Reg_bits(), PD_DCCMP_RXA, PD_DCCMP_RXB, PD_DCDAC_RXA, PD_DCDAC_RXB, ReadAnalogDC(), SPI_read(), and SPI_write().
Referenced by CalibrateRx(), and CalibrateTx().
uint8_t CalibrateRxSetup (bool extLoopback)
Definition at line 940 of file lms7002m_calibrations.c.
References bandwidthRF, calibUserBwDivider, EnableChannelPowerControls(), EnableMIMOBuffersIfNecessary(), extLoopbackPair, Get_SPI_Reg_bits(), GetFrequencySX(), IsPLLTuned(), LMS7002M_Rx, LMS7002M_Tx, LoadDC_REG_TX_IQ(), MAC, MCU_INVALID_RX_PATH, MCU_NO_ERROR, MCU_SXR_TUNE_FAILED, Modify_SPI_Reg_bits(), MSB_LSB, offsetNCO, PD_LOCH_T2RBUF, PD_TX_AFE1, PD_TX_AFE2, ROM, SEL_PATH_RFE, SetDefaultsSX(), SetFrequencySX(), SetNCOFrequency(), SetRxGFIR3Coefficients(), SetupCGEN(), SPI_read(), SPI_write(), status, and WriteMaskedRegs().
Referenced by CalibrateRx().
uint8_t CalibrateTx (bool extLoopback)
Definition at line 860 of file lms7002m_calibrations.c.
References bandwidthRF, CalibrateIQImbalance(), CalibrateRxDCAuto(), CalibrateTxDCAuto(), CalibrateTxSetup(), calibrationSXOffset_Hz, calibUserBwDivider, CG_IAMP_TBB, CheckSaturationTxRx(), DC_BYP_TXTSP, DCMODE, GCORRI_TXTSP, GCORRQ_TXTSP, Get_SPI_Reg_bits(), IQCORR_TXTSP, LMS7002M_Rx, LMS7002M_Tx, MCU_NO_ERROR, MCU_PROCEDURE_DISABLED, Modify_SPI_Reg_bits(), MSB_LSB, offsetNCO, PD_DCDAC_TXA, PD_DCDAC_TXB, ReadAnalogDC(), SaveChipState(), SEL_BAND1_TRF, SetNCOFrequency(), SPI_read(), SPI_write(), status, and UpdateRSSIDelay().
Referenced by DCIQ(), and main().
void CalibrateTxDCAuto ()
Definition at line 469 of file lms7002m_calibrations.c.
References LMS7Parameter::address, clamp(), CMIX_BYP_RXTSP, CMIX_BYP_TXTSP, DC_BYP_TXTSP, DCMODE, EN_G_TRF, Get_SPI_Reg_bits(), GetRSSI(), i, MAC, BinSearchParam::maxValue, BinSearchParam::minValue, Modify_SPI_Reg_bits(), LMS7Parameter::msblsb, BinSearchParam::param, PD_DCCMP_TXA, PD_DCCMP_TXB, PD_DCDAC_TXA, PD_DCDAC_TXB, ReadAnalogDC(), BinSearchParam::result, ROM, TxDcBinarySearch(), GNUPlotPipe::write(), WriteAnalogDC(), and GNUPlotPipe::writef().
Referenced by CalibrateTx().
uint8_t CalibrateTxSetup (bool extLoopback)
Definition at line 687 of file lms7002m_calibrations.c.
References bandwidthRF, calibrationSXOffset_Hz, calibUserBwDivider, EnableChannelPowerControls(), EnableMIMOBuffersIfNecessary(), extLoopbackPair, Get_SPI_Reg_bits(), GetFrequencySX(), IsPLLTuned(), LMS7002M_Rx, LMS7002M_Tx, LoadDC_REG_TX_IQ(), MAC, MCU_INVALID_TX_BAND, MCU_NO_ERROR, MCU_SXT_TUNE_FAILED, Modify_SPI_Reg_bits(), MSB_LSB, PD_LNA_RFE, PD_LOCH_T2RBUF, PD_RX_AFE1, PD_RX_AFE2, ROM, SEL_PATH_RFE, SetDefaultsSX(), SetFrequencySX(), SetNCOFrequency(), SetRxGFIR3Coefficients(), SetupCGEN(), SPI_read(), SPI_write(), status, and WriteMaskedRegs().
Referenced by CalibrateTx().
uint8_t CheckSaturationRx (const float_type bandwidth_Hz, bool extLoopback)
Definition at line 1118 of file lms7002m_calibrations.c.
References calibUserBwDivider, CG_IAMP_TBB, CMIX_BYP_RXTSP, CMIX_SC_RXTSP, GNUPlotPipe::flush(), G_RXLOOPB_RFE, Get_SPI_Reg_bits(), GetRSSI(), index, LMS7002M_Rx, LOSS_MAIN_TXPAD_TRF, MCU_LOOPBACK_SIGNAL_WEAK, MCU_NO_ERROR, Modify_SPI_Reg_bits(), offsetNCO, PUSH_GMEASUREMENT_VALUES, ROM, SetNCOFrequency(), GNUPlotPipe::write(), and GNUPlotPipe::writef().
Referenced by CalibrateRx().
int CheckSaturationTxRx (bool extLoopback)
Definition at line 167 of file lms7002m_calibrations.c.
References bandwidthRF, calibrationSXOffset_Hz, calibUserBwDivider, CMIX_BYP_RXTSP, DC_BYP_RXTSP, GNUPlotPipe::flush(), G_LNA_RFE, G_PGA_RBB, G_RXLOOPB_RFE, Get_SPI_Reg_bits(), GetRSSI(), index, LMS7002M_Rx, MCU_LOOPBACK_SIGNAL_WEAK, MCU_NO_ERROR, Modify_SPI_Reg_bits(), offsetNCO, PUSH_GMEASUREMENT_VALUES, SetNCOFrequency(), GNUPlotPipe::write(), and GNUPlotPipe::writef().
Referenced by CalibrateTx().
int16_t clamp (int16_t value, int16_t minBound, int16_t maxBound)
Definition at line 85 of file lms7002m_calibrations.c.
Referenced by AdjustAutoDC(), CalibrateTxDCAuto(), ConfigCGEN_ForLPF_IF(), RunAGC(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), SetupCGEN(), TuneRxFilter(), TuneRxFilterSetup(), and TuneTxFilterSetup().
static void FlipRisingEdge (const uint16_t addr, const uint8_t bits) static
Definition at line 94 of file lms7002m_calibrations.c.
References Modify_SPI_Reg_bits().
Referenced by GetRSSI(), and LoadDC_REG_TX_IQ().
uint32_t GetRSSI ()
Definition at line 131 of file lms7002m_calibrations.c.
References CAPTURE, FlipRisingEdge(), RefClk, RSSIDelayCounter, SPI_read(), TF0, TH0, TL0, and TR0.
Referenced by AdjustAutoDC(), BinarySearch(), CalibrateIQImbalance(), CalibrateRxDCAuto(), CalibrateTxDCAuto(), ChangeUntilReachRSSI(), CheckSaturationRx(), CheckSaturationTxRx(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), TuneRxFilter(), and TxDcBinarySearch().
static bool IsPLLTuned () static
Definition at line 100 of file lms7002m_calibrations.c.
References Get_SPI_Reg_bits(), MCU_NO_ERROR, MSB_LSB, and TuneVCO().
Referenced by CalibrateRxSetup(), and CalibrateTxSetup().
void LoadDC_REG_TX_IQ ()
Definition at line 107 of file lms7002m_calibrations.c.
References FlipRisingEdge(), RefClk, SPI_write(), TSGDCLDI_TXTSP, and TSGDCLDQ_TXTSP.
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), TuneRxFilterSetup(), and TuneTxFilterSetup().
int16_t ReadAnalogDC (const uint16_t addr)
Definition at line 314 of file lms7002m_calibrations.c.
References SPI_read(), and SPI_write().
Referenced by AdjustAutoDC(), CalibrateRx(), CalibrateRxDCAuto(), CalibrateTx(), and CalibrateTxDCAuto().
static void SetRxGFIR3Coefficients () static
Definition at line 150 of file lms7002m_calibrations.c.
References index, ROM, and SPI_write().
Referenced by CalibrateRxSetup(), and CalibrateTxSetup().
uint8_t SetupCGEN ()
Definition at line 665 of file lms7002m_calibrations.c.
References clamp(), CLKH_OV_CLKL_CGEN, EN_ADCCLKH_CLKGN, Get_SPI_Reg_bits(), GetFrequencyCGEN(), GFIR3_N_RXTSP, Modify_SPI_Reg_bits(), pow2(), and SetFrequencyCGEN().
Referenced by CalibrateRxSetup(), and CalibrateTxSetup().
static void TxDcBinarySearch (BinSearchParam * args) static
Definition at line 344 of file lms7002m_calibrations.c.
References LMS7Parameter::address, GetRSSI(), BinSearchParam::maxValue, BinSearchParam::minValue, BinSearchParam::param, PUSH_GMEASUREMENT_VALUES, BinSearchParam::result, and WriteAnalogDC().
Referenced by CalibrateTxDCAuto().
void UpdateRSSIDelay ()
Definition at line 117 of file lms7002m_calibrations.c.
References AGC_AVG_RXTSP, Get_SPI_Reg_bits(), GetReferenceClk_TSP_MHz(), HBD_OVR_RXTSP, RefClk, and RSSIDelayCounter.
Referenced by CalibrateRx(), CalibrateTx(), RunAGC(), TuneRxFilter(), and TuneTxFilter().
static void WriteAnalogDC (const uint16_t addr, int16_t value) static
Definition at line 329 of file lms7002m_calibrations.c.
References SPI_write().
Referenced by AdjustAutoDC(), CalibrateTxDCAuto(), and TxDcBinarySearch().
Variable Documentation
float bandwidthRF = 5e6
Definition at line 74 of file lms7002m_calibrations.c.
Referenced by CalibrateRx(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxSetup(), CheckSaturationTxRx(), main(), and UpdateFreq().
uint8_t extLoopbackPair = 0
Definition at line 83 of file lms7002m_calibrations.c.
Referenced by CalibrateRxSetup(), CalibrateTxSetup(), DCIQ(), and main().
float_type RefClk
Definition at line 22 of file lms7002m_controls.c.
Referenced by GetRSSI(), LoadDC_REG_TX_IQ(), and UpdateRSSIDelay().
uint16_t RSSIDelayCounter = 1
Definition at line 75 of file lms7002m_calibrations.c.
Referenced by GetRSSI(), and UpdateRSSIDelay().