LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/external/kissFFT/kiss_fft.c File Reference
kiss_fft.c File Reference
#include "_kiss_fft_guts.h"
Functions
static void kf_bfly2 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, int m)
static void kf_bfly4 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, const size_t m)
static void kf_bfly3 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, size_t m)
static void kf_bfly5 (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, int m)
static void kf_bfly_generic (kiss_fft_cpx *Fout, const size_t fstride, const kiss_fft_cfg st, int m, int p)
static void kf_work (kiss_fft_cpx *Fout, const kiss_fft_cpx *f, const size_t fstride, int in_stride, int *factors, const kiss_fft_cfg st)
static void kf_factor (int n, int *facbuf)
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void *mem, size_t *lenmem)
void kiss_fft_stride (kiss_fft_cfg st, const kiss_fft_cpx *fin, kiss_fft_cpx *fout, int in_stride)
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx *fin, kiss_fft_cpx *fout)
void kiss_fft_cleanup (void)
int kiss_fft_next_fast_size (int n)
Function Documentation
static void kf_bfly2 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, int m) static
Definition at line 21 of file kiss_fft.c.
References C_ADDTO, C_FIXDIV, C_MUL, C_SUB, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly3 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, size_t m) static
Definition at line 92 of file kiss_fft.c.
References C_ADD, C_ADDTO, C_FIXDIV, C_MUL, C_MULBYSCALAR, C_SUB, HALF_OF, i, kiss_fft_cpx::i, k, calc_fmcw_peaks::r, kiss_fft_cpx::r, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly4 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, const size_t m) static
Definition at line 44 of file kiss_fft.c.
References C_ADD, C_ADDTO, C_FIXDIV, C_MUL, C_SUB, kiss_fft_cpx::i, kiss_fft_state::inverse, k, kiss_fft_cpx::r, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly5 (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, int m) static
Definition at line 136 of file kiss_fft.c.
References C_ADD, C_FIXDIV, C_MUL, C_SUB, i, kiss_fft_cpx::i, calc_fmcw_peaks::r, kiss_fft_cpx::r, S_MUL, and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_bfly_generic (kiss_fft_cpx * Fout, const size_t fstride, const kiss_fft_cfg st, int m, int p) static
Definition at line 198 of file kiss_fft.c.
References C_ADDTO, C_FIXDIV, C_MUL, k, KISS_FFT_TMP_ALLOC, KISS_FFT_TMP_FREE, kiss_fft_state::nfft, p(), and kiss_fft_state::twiddles.
Referenced by kf_work().
static void kf_factor (int n, int * facbuf) static
Definition at line 309 of file kiss_fft.c.
References p().
Referenced by kiss_fft_alloc().
static void kf_work (kiss_fft_cpx * Fout, const kiss_fft_cpx * f, const size_t fstride, int in_stride, int * factors, const kiss_fft_cfg st) static
Definition at line 238 of file kiss_fft.c.
References k, kf_bfly2(), kf_bfly3(), kf_bfly4(), kf_bfly5(), kf_bfly_generic(), and p().
Referenced by kiss_fft_stride().
void kiss_fft (kiss_fft_cfg cfg, const kiss_fft_cpx * fin, kiss_fft_cpx * fout)
Definition at line 385 of file kiss_fft.c.
References kiss_fft_stride().
Referenced by endif(), LimeSDRTest::RunTest(), set(), and fftviewer_frFFTviewer::StreamingLoop().
kiss_fft_cfg kiss_fft_alloc (int nfft, int inverse_fft, void * mem, size_t * lenmem)
Definition at line 339 of file kiss_fft.c.
References kiss_fft_state::factors, i, kiss_fft_state::inverse, kf_cexp, kf_factor(), KISS_FFT_MALLOC, kiss_fft_state::nfft, phase, and kiss_fft_state::twiddles.
Referenced by LimeSDRTest::RunTest(), and fftviewer_frFFTviewer::StreamingLoop().
void kiss_fft_cleanup (void)
Definition at line 391 of file kiss_fft.c.
int kiss_fft_next_fast_size (int n)
Definition at line 396 of file kiss_fft.c.
void kiss_fft_stride (kiss_fft_cfg st, const kiss_fft_cpx * fin, kiss_fft_cpx * fout, int in_stride)
Definition at line 371 of file kiss_fft.c.
References kiss_fft_state::factors, kf_work(), KISS_FFT_TMP_ALLOC, KISS_FFT_TMP_FREE, and kiss_fft_state::nfft.
Referenced by kiss_fft().