LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/NullDevice.cpp File Reference
NullDevice.cpp File Reference
#include <SoapySDR/Device.hpp>
#include <SoapySDR/Registry.hpp>
Classes
class NullDevice
Functions
SoapySDR::KwargsList findNullDevice (const SoapySDR::Kwargs &args)
SoapySDR::Device * makeNullDevice (const SoapySDR::Kwargs &)
void lateLoadNullDevice (void)
Function Documentation
SoapySDR::KwargsList findNullDevice (const SoapySDR::Kwargs & args)
Definition at line 26 of file NullDevice.cpp.
Referenced by lateLoadNullDevice().
void lateLoadNullDevice (void)
lateLoadNullDevice() is called by loadModules() to load the null device on-demand/not statically. This works around an issue when a loading module is linked against an older copy of SoapySDR which also tries to load its null device into the running copy of the library.
Definition at line 54 of file NullDevice.cpp.
References findNullDevice(), makeNullDevice(), and SOAPY_SDR_ABI_VERSION.
Referenced by getModuleVersions().
SoapySDR::Device* makeNullDevice (const SoapySDR::Kwargs &)
Definition at line 41 of file NullDevice.cpp.
References NullDevice::NullDevice().
Referenced by lateLoadNullDevice().