LimeSuite-UML: pnlBoardControls Class Reference
pnlBoardControls Class Reference
#include <pnlBoardControls.h>
Classes
struct ADC_DAC
class Param_GUI
Public Member Functions
pnlBoardControls (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=_(""), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlBoardControls ()
void UpdatePanel ()
void Initialize (lms_device_t *controlPort)
void SetupControls (const std::string &boardID)
void OnSetDACvalues (wxSpinEvent &event)
void OnSetDACvaluesENTER (wxCommandEvent &event)
Public Attributes
lms_device_t * lmsControl
Protected Member Functions
void OnCustomRead (wxCommandEvent &event)
void OnCustomWrite (wxCommandEvent &event)
std::vector< ADC_DAC > getBoardParams (const std::string &boardID)
void OnUserChangedBoardType (wxCommandEvent &event)
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
Protected Attributes
wxPanel * pnlCustomControls
wxPanel * pnlReadControls
wxSpinCtrl * spinCustomChannelRd
wxStaticText * txtCustomValueRd
wxStaticText * txtCustomUnitsRd
wxStaticText * txtCustomPowerOf10Rd
wxSpinCtrl * spinCustomChannelWr
wxSpinCtrl * spinCustomValueWr
wxChoice * cmbCustomUnitsWr
wxChoice * cmbCustomPowerOf10Wr
wxButton * btnCustomRd
wxButton * btnCustomWr
wxFlexGridSizer * sizerAnalogRd
wxFlexGridSizer * sizerAdditionalControls
wxPanel * additionalControls
wxButton * btnReadAll
wxButton * btnWriteAll
wxStaticText * m_staticText349
wxChoice * cmbBoardSelection
std::vector< ADC_DAC > mParameters
std::vector< Param_GUI * > mGUI_widgets
Detailed Description
Definition at line 30 of file pnlBoardControls.h.
Constructor & Destructor Documentation
pnlBoardControls::pnlBoardControls (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = _(""), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 70 of file pnlBoardControls.cpp.
References lime::ADC_UNITS_COUNT, lime::adcUnits2string(), additionalControls, btnCustomRd, btnCustomWr, btnReadAll, btnWriteAll, cmbBoardSelection, cmbCustomPowerOf10Wr, cmbCustomUnitsWr, lime::GetDeviceName(), i, lime::LMS_DEV_COUNT, lime::LMS_DEV_UNKNOWN, m_staticText349, OnCustomRead(), OnCustomWrite(), OnReadAll(), OnSetDACvalues(), OnUserChangedBoardType(), OnWriteAll(), pnlCustomControls, pnlReadControls, power2unitsString(), SetupControls(), sizerAdditionalControls, sizerAnalogRd, spinCustomChannelRd, spinCustomChannelWr, spinCustomValueWr, txtCustomPowerOf10Rd, txtCustomUnitsRd, and txtCustomValueRd.
pnlBoardControls::~pnlBoardControls ()
Definition at line 197 of file pnlBoardControls.cpp.
References btnReadAll, btnWriteAll, cmbBoardSelection, OnReadAll(), OnUserChangedBoardType(), and OnWriteAll().
Member Function Documentation
std::vector< pnlBoardControls::ADC_DAC > pnlBoardControls::getBoardParams (const std::string & boardID) protected
Definition at line 305 of file pnlBoardControls.cpp.
References lime::adcUnits2string(), lime::GetDeviceName(), lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDR_PCIE, lime::LMS_DEV_LIMESDR_QPCIE, lime::LMS_DEV_LIMESDR_USB_SP, lime::LMS_DEV_LIMESDRMINI, lime::LMS_DEV_LMS7002M_ULTIMATE_EVB, lime::RAW, and lime::TEMPERATURE.
Referenced by SetupControls().
void pnlBoardControls::Initialize (lms_device_t * controlPort)
Definition at line 271 of file pnlBoardControls.cpp.
References lms_dev_info_t::deviceName, info, LMS_GetDeviceInfo(), lmsControl, OnReadAll(), and SetupControls().
Referenced by LMS7SuiteAppFrame::OnShowBoardControls(), and LMS7SuiteAppFrame::UpdateConnections().
void pnlBoardControls::OnCustomRead (wxCommandEvent & event) protected
Definition at line 473 of file pnlBoardControls.cpp.
References LMS_ReadCustomBoardParam(), lmsControl, spinCustomChannelRd, status, txtCustomUnitsRd, txtCustomValueRd, and units.
Referenced by pnlBoardControls().
void pnlBoardControls::OnCustomWrite (wxCommandEvent & event) protected
Definition at line 491 of file pnlBoardControls.cpp.
References lime::adcUnits2string(), cmbCustomPowerOf10Wr, cmbCustomUnitsWr, LMS_WriteCustomBoardParam(), lmsControl, spinCustomChannelWr, spinCustomValueWr, status, and units.
Referenced by pnlBoardControls().
void pnlBoardControls::OnReadAll (wxCommandEvent & event) protected
Definition at line 205 of file pnlBoardControls.cpp.
References additionalControls, i, LMS_ReadCustomBoardParam(), lmsControl, mParameters, status, units, and UpdatePanel().
Referenced by Initialize(), pnlBoardControls(), and ~pnlBoardControls().
void pnlBoardControls::OnSetDACvalues (wxSpinEvent & event)
Definition at line 446 of file pnlBoardControls.cpp.
References i, LMS_WriteCustomBoardParam(), lmsControl, mGUI_widgets, mParameters, status, and units.
Referenced by OnSetDACvaluesENTER(), pnlBoardControls(), and SetupControls().
void pnlBoardControls::OnSetDACvaluesENTER (wxCommandEvent & event)
Definition at line 439 of file pnlBoardControls.cpp.
References OnSetDACvalues().
Referenced by SetupControls().
void pnlBoardControls::OnUserChangedBoardType (wxCommandEvent & event) protected
Definition at line 468 of file pnlBoardControls.cpp.
References cmbBoardSelection, lime::GetDeviceName(), and SetupControls().
Referenced by pnlBoardControls(), and ~pnlBoardControls().
void pnlBoardControls::OnWriteAll (wxCommandEvent & event) protected
Definition at line 243 of file pnlBoardControls.cpp.
References additionalControls, i, LMS_WriteCustomBoardParam(), lmsControl, mParameters, and status.
Referenced by pnlBoardControls(), and ~pnlBoardControls().
void pnlBoardControls::SetupControls (const std::string & boardID)
Definition at line 324 of file pnlBoardControls.cpp.
References additionalControls, cmbBoardSelection, getBoardParams(), lime::GetDeviceName(), i, pnlBuffers::Initialize(), pnluLimeSDR::Initialize(), LMS7002M_Novena_wxgui::Initialize(), pnlLimeSDR::Initialize(), pnlQSpark::Initialize(), pnlUltimateEVB::Initialize(), RFSpark_wxgui::Initialize(), lime::LMS_DEV_COUNT, lime::LMS_DEV_EVB7, lime::LMS_DEV_EVB7V2, lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDR_PCIE, lime::LMS_DEV_LIMESDR_QPCIE, lime::LMS_DEV_LIMESDRMINI, lime::LMS_DEV_LMS7002M_ULTIMATE_EVB, lime::LMS_DEV_NOVENA, lime::LMS_DEV_RFESPARK, lime::LMS_DEV_RFSPARK, lime::LMS_DEV_UNKNOWN, lmsControl, mGUI_widgets, mParameters, OnSetDACvalues(), OnSetDACvaluesENTER(), pnlCustomControls, pnlReadControls, pnlBoardControls::Param_GUI::rValue, sizerAdditionalControls, sizerAnalogRd, pnlBoardControls::Param_GUI::title, pnlBoardControls::Param_GUI::units, units, and pnlBoardControls::Param_GUI::wValue.
Referenced by Initialize(), LMS7SuiteAppFrame::OnControlBoardConnect(), OnUserChangedBoardType(), and pnlBoardControls().
void pnlBoardControls::UpdatePanel ()
Definition at line 283 of file pnlBoardControls.cpp.
References additionalControls, i, mGUI_widgets, mParameters, and units.
Referenced by OnReadAll(), and LMS7SuiteAppFrame::OnShowBoardControls().
Member Data Documentation
wxPanel* pnlBoardControls::additionalControls protected
Definition at line 99 of file pnlBoardControls.h.
Referenced by OnReadAll(), OnWriteAll(), pnlBoardControls(), SetupControls(), and UpdatePanel().
wxButton* pnlBoardControls::btnCustomRd protected
Definition at line 91 of file pnlBoardControls.h.
Referenced by pnlBoardControls().
wxButton* pnlBoardControls::btnCustomWr protected
Definition at line 92 of file pnlBoardControls.h.
Referenced by pnlBoardControls().
wxButton* pnlBoardControls::btnReadAll protected
Definition at line 107 of file pnlBoardControls.h.
Referenced by pnlBoardControls(), and ~pnlBoardControls().
wxButton* pnlBoardControls::btnWriteAll protected
Definition at line 108 of file pnlBoardControls.h.
Referenced by pnlBoardControls(), and ~pnlBoardControls().
wxChoice* pnlBoardControls::cmbBoardSelection protected
Definition at line 110 of file pnlBoardControls.h.
Referenced by OnUserChangedBoardType(), pnlBoardControls(), SetupControls(), and ~pnlBoardControls().
wxChoice* pnlBoardControls::cmbCustomPowerOf10Wr protected
Definition at line 90 of file pnlBoardControls.h.
Referenced by OnCustomWrite(), and pnlBoardControls().
wxChoice* pnlBoardControls::cmbCustomUnitsWr protected
Definition at line 89 of file pnlBoardControls.h.
Referenced by OnCustomWrite(), and pnlBoardControls().
lms_device_t* pnlBoardControls::lmsControl
Definition at line 75 of file pnlBoardControls.h.
Referenced by Initialize(), OnCustomRead(), OnCustomWrite(), OnReadAll(), OnSetDACvalues(), OnWriteAll(), and SetupControls().
wxStaticText* pnlBoardControls::m_staticText349 protected
Definition at line 109 of file pnlBoardControls.h.
Referenced by pnlBoardControls().
std::vector<Param_GUI*> pnlBoardControls::mGUI_widgets protected
Definition at line 114 of file pnlBoardControls.h.
Referenced by OnSetDACvalues(), SetupControls(), and UpdatePanel().
std::vector<ADC_DAC> pnlBoardControls::mParameters protected
Definition at line 112 of file pnlBoardControls.h.
Referenced by OnReadAll(), OnSetDACvalues(), OnWriteAll(), SetupControls(), and UpdatePanel().
wxPanel* pnlBoardControls::pnlCustomControls protected
Definition at line 81 of file pnlBoardControls.h.
Referenced by pnlBoardControls(), and SetupControls().
wxPanel* pnlBoardControls::pnlReadControls protected
Definition at line 82 of file pnlBoardControls.h.
Referenced by pnlBoardControls(), and SetupControls().
wxFlexGridSizer* pnlBoardControls::sizerAdditionalControls protected
Definition at line 98 of file pnlBoardControls.h.
Referenced by pnlBoardControls(), and SetupControls().
wxFlexGridSizer* pnlBoardControls::sizerAnalogRd protected
Definition at line 96 of file pnlBoardControls.h.
Referenced by pnlBoardControls(), and SetupControls().
wxSpinCtrl* pnlBoardControls::spinCustomChannelRd protected
Definition at line 83 of file pnlBoardControls.h.
Referenced by OnCustomRead(), and pnlBoardControls().
wxSpinCtrl* pnlBoardControls::spinCustomChannelWr protected
Definition at line 87 of file pnlBoardControls.h.
Referenced by OnCustomWrite(), and pnlBoardControls().
wxSpinCtrl* pnlBoardControls::spinCustomValueWr protected
Definition at line 88 of file pnlBoardControls.h.
Referenced by OnCustomWrite(), and pnlBoardControls().
wxStaticText* pnlBoardControls::txtCustomPowerOf10Rd protected
Definition at line 86 of file pnlBoardControls.h.
Referenced by pnlBoardControls().
wxStaticText* pnlBoardControls::txtCustomUnitsRd protected
Definition at line 85 of file pnlBoardControls.h.
Referenced by OnCustomRead(), and pnlBoardControls().
wxStaticText* pnlBoardControls::txtCustomValueRd protected
Definition at line 84 of file pnlBoardControls.h.
Referenced by OnCustomRead(), and pnlBoardControls().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/pnlBoardControls.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/pnlBoardControls.cpp