LimeSuite-UML: lms7002_pnlTBB_view Class Reference
lms7002_pnlTBB_view Class Reference
Implementing pnlTBB_view.
#include <lms7002_pnlTBB_view.h>
Public Member Functions
lms7002_pnlTBB_view (wxWindow *parent)
Constructor.
lms7002_pnlTBB_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlTBB_view
pnlTBB_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlTBB_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void ParameterChangeHandler (wxSpinEvent &event)
virtual void OnbtnTuneFilter (wxCommandEvent &event)
virtual void OnbtnTuneTxGain (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlTBB_view
wxCheckBox * chkPD_LPFH_TBB
wxCheckBox * chkPD_LPFIAMP_TBB
wxCheckBox * chkPD_LPFLAD_TBB
wxCheckBox * chkPD_LPFS5_TBB
wxCheckBox * chkEN_G_TBB
wxCheckBox * chkEN_DIR_TBB
wxCheckBox * chkBYPLADDER_TBB
wxCheckBox * chkR5_LPF_BYP_TBB
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbLOOPB_TBB
wxStaticText * ID_STATICTEXT5
wxComboBox * cmbTSTIN_TBB
wxStaticText * ID_STATICTEXT2
NumericSlider * cmbCG_IAMP_TBB
wxStaticText * ID_STATICTEXT3
NumericSlider * cmbICT_IAMP_FRP_TBB
wxStaticText * ID_STATICTEXT4
NumericSlider * cmbICT_IAMP_GG_FRP_TBB
wxStaticText * ID_STATICTEXT6
wxComboBox * cmbICT_LPFS5_F_TBB
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbICT_LPFS5_PT_TBB
wxStaticText * ID_STATICTEXT8
wxComboBox * cmbICT_LPF_H_PT_TBB
wxStaticText * ID_STATICTEXT9
wxComboBox * cmbICT_LPFH_F_TBB
wxStaticText * ID_STATICTEXT10
wxComboBox * cmbICT_LPFLAD_F_TBB
wxStaticText * ID_STATICTEXT11
wxComboBox * cmbICT_LPFLAD_PT_TBB
wxStaticText * ID_STATICTEXT12
NumericSlider * cmbRCAL_LPFH_TBB
wxStaticText * ID_STATICTEXT13
NumericSlider * cmbRCAL_LPFLAD_TBB
wxStaticText * ID_STATICTEXT15
NumericSlider * cmbRCAL_LPFS5_TBB
wxStaticText * ID_STATICTEXT14
NumericSlider * cmbCCAL_LPFLAD_TBB
wxStaticText * lblFilterInputName
wxTextCtrl * txtFilterFrequency
wxButton * btnTuneFilter
wxButton * btnTuneTxGain
Additional Inherited Members
Protected Types inherited from pnlTBB_view
enum {
ID_PD_LPFH_TBB = 2048, ID_PD_LPFIAMP_TBB, ID_PD_LPFLAD_TBB, ID_PD_LPFS5_TBB,
ID_EN_G_TBB, ID_EN_DIR_TBB, ID_BYPLADDER_TBB, ID_LOOPB_TBB,
ID_TSTIN_TBB, ID_CG_IAMP_TBB, ID_ICT_IAMP_FRP_TBB, ID_ICT_IAMP_GG_FRP_TBB,
ID_ICT_LPFS5_F_TBB, ID_ICT_LPFS5_PT_TBB, ID_ICT_LPF_H_PT_TBB, ID_ICT_LPFH_F_TBB,
ID_ICT_LPFLAD_F_TBB, ID_ICT_LPFLAD_PT_TBB, ID_RCAL_LPFH_TBB, ID_RCAL_LPFLAD_TBB,
ID_RCAL_LPFS5_TBB, ID_CCAL_LPFLAD_TBB, ID_BTN_TUNE_FILTER
}
Detailed Description
Implementing pnlTBB_view.
Definition at line 17 of file lms7002_pnlTBB_view.h.
Constructor & Destructor Documentation
lms7002_pnlTBB_view::lms7002_pnlTBB_view (wxWindow * parent)
Constructor.
Definition at line 11 of file lms7002_pnlTBB_view.cpp.
lms7002_pnlTBB_view::lms7002_pnlTBB_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 18 of file lms7002_pnlTBB_view.cpp.
References BYPLADDER_TBB, CCAL_LPFLAD_TBB, CG_IAMP_TBB, pnlTBB_view::chkBYPLADDER_TBB, pnlTBB_view::chkEN_DIR_TBB, pnlTBB_view::chkEN_G_TBB, pnlTBB_view::chkPD_LPFH_TBB, pnlTBB_view::chkPD_LPFIAMP_TBB, pnlTBB_view::chkPD_LPFLAD_TBB, pnlTBB_view::chkPD_LPFS5_TBB, pnlTBB_view::chkR5_LPF_BYP_TBB, pnlTBB_view::cmbCCAL_LPFLAD_TBB, pnlTBB_view::cmbCG_IAMP_TBB, pnlTBB_view::cmbICT_IAMP_FRP_TBB, pnlTBB_view::cmbICT_IAMP_GG_FRP_TBB, pnlTBB_view::cmbICT_LPF_H_PT_TBB, pnlTBB_view::cmbICT_LPFH_F_TBB, pnlTBB_view::cmbICT_LPFLAD_F_TBB, pnlTBB_view::cmbICT_LPFLAD_PT_TBB, pnlTBB_view::cmbICT_LPFS5_F_TBB, pnlTBB_view::cmbICT_LPFS5_PT_TBB, pnlTBB_view::cmbLOOPB_TBB, pnlTBB_view::cmbRCAL_LPFH_TBB, pnlTBB_view::cmbRCAL_LPFLAD_TBB, pnlTBB_view::cmbRCAL_LPFS5_TBB, pnlTBB_view::cmbTSTIN_TBB, EN_DIR_TBB, EN_G_TBB, i, ICT_IAMP_FRP_TBB, ICT_IAMP_GG_FRP_TBB, ICT_LPF_H_PT_TBB, ICT_LPFH_F_TBB, ICT_LPFLAD_F_TBB, ICT_LPFLAD_PT_TBB, ICT_LPFS5_F_TBB, ICT_LPFS5_PT_TBB, LMS7param, LOOPB_TBB, PD_LPFH_TBB, PD_LPFIAMP_TBB, PD_LPFLAD_TBB, PD_LPFS5_TBB, R5_LPF_BYP_TBB, RCAL_LPFH_TBB, RCAL_LPFLAD_TBB, RCAL_LPFS5_TBB, temp, TSTIN_TBB, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlTBB_view::Initialize (lms_device_t * pControl)
Definition at line 78 of file lms7002_pnlTBB_view.cpp.
References pnlTBB_view::chkR5_LPF_BYP_TBB, LMS7param, LMS_ReadParam(), lmsControl, and MASK.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlTBB_view::OnbtnTuneFilter (wxCommandEvent & event) protected virtual
Reimplemented from pnlTBB_view.
Definition at line 129 of file lms7002_pnlTBB_view.cpp.
References LMS7param, LMS_CH_TX, LMS_ReadParam(), LMS_SetLPFBW(), LMS_Synchronize(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, status, pnlTBB_view::txtFilterFrequency, and UpdateGUI().
void lms7002_pnlTBB_view::OnbtnTuneTxGain (wxCommandEvent & event) protected virtual
Reimplemented from pnlTBB_view.
Definition at line 148 of file lms7002_pnlTBB_view.cpp.
References lime::LMS7002M::CalibrateTxGain(), lms(), LMS7param, LMS_ReadParam(), LMS_Synchronize(), lmsControl, MAC, status, pnlTBB_view::txtFilterFrequency, and UpdateGUI().
void lms7002_pnlTBB_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlTBB_view.
Definition at line 97 of file lms7002_pnlTBB_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
Referenced by ParameterChangeHandler().
void lms7002_pnlTBB_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlTBB_view.
Definition at line 88 of file lms7002_pnlTBB_view.cpp.
References ParameterChangeHandler().
void lms7002_pnlTBB_view::UpdateGUI ()
Definition at line 113 of file lms7002_pnlTBB_view.cpp.
References pnlTBB_view::cmbCG_IAMP_TBB, LMS7param, LMS_ReadParam(), lmsControl, MAC, MIMO_SISO, TRX_GAIN_SRC, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by OnbtnTuneFilter(), OnbtnTuneTxGain(), and lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlTBB_view::lmsControl protected
Definition at line 33 of file lms7002_pnlTBB_view.h.
Referenced by Initialize(), OnbtnTuneFilter(), OnbtnTuneTxGain(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlTBB_view::wndId2Enum protected
Definition at line 34 of file lms7002_pnlTBB_view.h.
Referenced by lms7002_pnlTBB_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlTBB_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlTBB_view.cpp