LimeSuite-UML: lime::LMS7002M Class Reference
lime::LMS7002M Class Reference
#include <LMS7002M.h>
Classes
struct CGEN_details
struct SX_details
Public Types
enum { Rx, Tx }
enum Channel {
ChA = 1, ChB = 2, ChAB = 3, ChSXR = 1,
ChSXT = 2
}
enum MemorySection {
LimeLight = 0, EN_DIR, AFE, BIAS,
XBUF, CGEN, LDO, BIST,
CDS, TRF, TBB, RFE,
RBB, SX, TRX_GAIN, TxTSP,
TxNCO, TxGFIR1, TxGFIR2, TxGFIR3a,
TxGFIR3b, TxGFIR3c, RxTSP, RxNCO,
RxGFIR1, RxGFIR2, RxGFIR3a, RxGFIR3b,
RxGFIR3c, RSSI_DC_CALIBRATION, RSSI_PDET_TEMP_CONFIG, RSSI_DC_CONFIG,
MEMORY_SECTIONS_COUNT
}
enumeration to indicate module registers intervals
enum LogType { LOG_INFO, LOG_WARNING, LOG_ERROR, LOG_DATA }
Public Member Functions
LMS7002M ()
Creates LMS7002M main control object.
void SetConnection (IConnection *port, const size_t devIndex=0)
Sets connection which is used for data communication with chip.
IConnection * GetConnection (void) const
virtual ~LMS7002M ()
void SetActiveChannel (const Channel ch)
Channel GetActiveChannel (bool fromChip=true)
size_t GetActiveChannelIndex (bool fromChip=true)
int EnableChannel (const bool isTx, const bool enable)
int SetInterfaceFrequency (float_type cgen_freq_Hz, const uint8_t interpolation, const uint8_t decimation)
Configures interfaces for desired frequency.
float_type GetSampleRate (bool tx, Channel ch)
Get the sample rate in Hz.
int SetRxDCRemoval (const bool enable)
bool GetRxDCRemoval (void)
int EnableSXTDD (bool enable)
int SetTxDCOffset (const float_type I, const float_type Q)
void GetTxDCOffset (float_type &I, float_type &Q)
int SetIQBalance (const bool tx, const float_type phase, const float_type gainI, const float_type gainQ)
void GetIQBalance (const bool tx, float_type &phase, float_type &gainI, float_type &gainQ)
virtual int SetDefaults (MemorySection module)
Sets given module registers to default values.
void EnableValuesCache (bool enabled=true)
bool IsValuesCacheEnabled ()
MCU_BD * GetMCUControls () const
void EnableCalibrationByMCU (bool enabled)
float_type GetTemperature ()
void SetLogCallback (std::function< void(const char *, int)> callback)
LMS7002M_RegistersMap * BackupRegisterMap (void)
void RestoreRegisterMap (LMS7002M_RegistersMap *backup)
Transmitter, Receiver calibrations
int CalibrateRx (float_type bandwidth, const bool useExtLoopback=false)
Calibrates Receiver.
int CalibrateTx (float_type bandwidth, const bool useExtLoopback=false)
Calibrates Transmitter.
Filters tuning
int TuneTxFilter (const float_type bandwidth)
int TuneRxFilter (const float_type rx_lpf_freq_RF)
int TuneTxFilterWithCaching (const float_type bandwidth)
int TuneRxFilterWithCaching (const float_type rx_lpf_freq_RF)
Internal calibrations
int CalibrateInternalADC (int clkDiv=32)
int CalibrateRP_BIAS ()
int CalibrateTxGain (float maxGainOffset_dBFS, float *actualGain_dBFS)
int CalibrateAnalogRSSI_DC_Offset ()
High level gain configuration
int SetRBBPGA_dB (const float_type gain)
float_type GetRBBPGA_dB (void)
Get the actual RX PGA gain in dB.
int SetRFELNA_dB (const float_type gain)
float_type GetRFELNA_dB (void)
Get the actual RX LNA gain in dB.
int SetRFELoopbackLNA_dB (const float_type gain)
float_type GetRFELoopbackLNA_dB (void)
Get the actual RX loopback LNA gain in dB.
int SetRFETIA_dB (const float_type gain)
float_type GetRFETIA_dB (void)
Get the actual RX TIA gain in dB.
int SetTRFPAD_dB (const float_type gain)
float_type GetTRFPAD_dB (void)
Get the actual TX PAD gain in dB.
int SetTBBIAMP_dB (const float_type gain)
float_type GetTBBIAMP_dB (void)
Get the TBB frontend gain in dB.
int SetTRFLoopbackPAD_dB (const float_type gain)
float_type GetTRFLoopbackPAD_dB (void)
Get the actual TX loopback PAD gain in dB.
TSP
int LoadDC_REG_IQ (bool tx, int16_t I, int16_t Q)
Loads given DC_REG values into registers.
int SetNCOFrequency (bool tx, uint8_t index, float_type freq_Hz)
Sets chosen NCO's frequency.
float_type GetNCOFrequency (bool tx, uint8_t index, bool fromChip=true)
Returns chosen NCO's frequency in Hz.
int SetNCOPhaseOffsetForMode0 (bool tx, float_type angle_Deg)
Sets chosen NCO phase offset angle when memory table MODE is 0.
int SetNCOPhaseOffset (bool tx, uint8_t index, float_type angle_Deg)
Sets chosen NCO's phase offset angle.
float_type GetNCOPhaseOffset_Deg (bool tx, uint8_t index)
Returns chosen NCO's phase offset angle in radians.
int SetGFIRCoefficients (bool tx, uint8_t GFIR_index, const int16_t *coef, uint8_t coefCount)
Uploads given FIR coefficients to chip.
int GetGFIRCoefficients (bool tx, uint8_t GFIR_index, int16_t *coef, uint8_t coefCount)
Returns currently loaded FIR coefficients.
float_type GetReferenceClk_TSP (bool tx)
Returns TSP reference frequency.
Static Public Attributes
static float_type gVCO_frequency_table [3][2] = { { 3800e6, 5222e6 }, { 4961e6, 6754e6 }, {6306e6, 7714e6} }
static float_type gCGEN_VCO_frequencies [2] = {1930e6, 2940e6}
Protected Member Functions
virtual void Log (const char *text, LogType type)
Simple logging function to print status messages.
void Log (LogType type, const char *format,...)
void Log (LogType type, const char *format, va_list argList)
int LoadConfigLegacyFile (const char *filename)
Algorithms functions
void BackupAllRegisters ()
void RestoreAllRegisters ()
uint32_t GetRSSI (RSSI_measurements *measurements=nullptr)
Flips the CAPTURE bit and returns digital RSSI value.
uint32_t GetAvgRSSI (const int avgCount)
void SetRxDCOFF (int8_t offsetI, int8_t offsetQ)
Sets Rx Dc offsets by converting two's complementary numbers to sign and magnitude.
void CalibrateRxDC ()
void AdjustAutoDC (const uint16_t address, bool tx)
void CalibrateRxDCAuto ()
void CalibrateTxDCAuto ()
void CalibrateTxDC (int16_t *dccorri, int16_t *dccorrq)
void CalibrateIQImbalance (const bool tx, uint16_t *gainI=nullptr, uint16_t *gainQ=nullptr, int16_t *phase=nullptr)
int CalibrateTxSetup (const float_type bandwidth_Hz, const bool useExtLoopback)
int CalibrateRxSetup (const float_type bandwidth_Hz, const bool useExtLoopback)
int CheckSaturationRx (const float_type bandwidth_Hz, const bool useExtLoopback)
int CheckSaturationTxRx (const float_type bandwidth_Hz, const bool useExtLoopback)
int CalibrateTxGainSetup ()
void BinarySearch (BinSearchParam *args)
void TxDcBinarySearch (BinSearchParam *args)
void GridSearch (GridSearchParam *args)
void CoarseSearch (const uint16_t addr, const uint8_t msb, const uint8_t lsb, int16_t &value, const uint8_t maxIterations)
void FineSearch (const uint16_t addrI, const uint8_t msbI, const uint8_t lsbI, int16_t &valueI, const uint16_t addrQ, const uint8_t msbQ, const uint8_t lsbQ, int16_t &valueQ, const uint8_t fieldSize)
int RxFilterSearch (const LMS7Parameter &param, const uint32_t rssi_3dB, uint8_t rssiAvgCnt, const int stepLimit)
int TxFilterSearch (const LMS7Parameter &param, const uint32_t rssi_3dB, uint8_t rssiAvgCnt, const int stepLimit)
int TxFilterSearch_S5 (const LMS7Parameter &param, const uint32_t rssi_3dB, uint8_t rssiAvgCnt, const int stepLimit)
int TuneRxFilterSetup (const float_type rx_lpf_IF)
int TuneTxFilterSetup (const float_type tx_lpf_IF)
int RegistersTestInterval (uint16_t startAddr, uint16_t endAddr, uint16_t pattern, std::stringstream &ss)
Performs registers test for given address interval by writing given pattern data.
int SPI_write_batch (const uint16_t *spiAddr, const uint16_t *spiData, uint16_t cnt, bool toChip=false)
Batches multiple register writes into least amount of transactions.
int SPI_read_batch (const uint16_t *spiAddr, uint16_t *spiData, uint16_t cnt)
Batches multiple register reads into least amount of transactions.
int Modify_SPI_Reg_mask (const uint16_t *addr, const uint16_t *masks, const uint16_t *values, uint8_t start, uint8_t stop)
Modifies given registers with values applied using masks.
Protected Attributes
bool mCalibrationByMCU
MCU_BD * mcuControl
bool useCache
LMS7002M_RegistersMap * mRegistersMap
uint16_t MemorySectionAddresses [MEMORY_SECTIONS_COUNT][2]
std::function< void(const char *, int)> log_callback
IConnection * controlPort
port used for communicating with LMS7002M
unsigned mdevIndex
size_t mSelfCalDepth
int opt_gain_tbb [2]
double _cachedRefClockRate
Static Protected Attributes
static const uint16_t readOnlyRegisters [] = { 0x002F, 0x008C, 0x00A8, 0x00A9, 0x00AA, 0x00AB, 0x00AC, 0x0123, 0x0209, 0x020A, 0x020B, 0x040E, 0x040F }
static const uint16_t readOnlyRegistersMasks [] = { 0x0000, 0x0FFF, 0x007F, 0x0000, 0x0000, 0x0000, 0x0000, 0x003F, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 }
Registers writing and reading
int UploadAll ()
Writes all registers from host to chip.
int DownloadAll ()
Reads all registers from the chip to host.
bool IsSynced ()
Reads all chip configuration and checks if it matches with local registers copy.
int CopyChannelRegisters (const Channel src, const Channel dest, bool copySX)
int ResetChip ()
Sends reset signal to chip, after reset enables B channel controls.
int SoftReset ()
int LoadConfig (const char *filename)
Reads configuration file and uploads registers to chip.
int SaveConfig (const char *filename)
Reads all registers from chip and saves to file.
uint16_t Get_SPI_Reg_bits (const LMS7Parameter &param, bool fromChip=false)
Returns given parameter value from chip register.
uint16_t Get_SPI_Reg_bits (uint16_t address, uint8_t msb, uint8_t lsb, bool fromChip=false)
Returns given parameter value from chip register.
int Modify_SPI_Reg_bits (const LMS7Parameter &param, const uint16_t value, bool fromChip=false)
Change given parameter value.
int Modify_SPI_Reg_bits (uint16_t address, uint8_t msb, uint8_t lsb, uint16_t value, bool fromChip=false)
Change given parameter value.
int SPI_write (uint16_t address, uint16_t data, bool toChip=false)
Write given data value to whole register.
uint16_t SPI_read (uint16_t address, bool fromChip=false, int *status=0)
Reads whole register value from given address.
int RegistersTest (const char *fileName="registersTest.txt")
Performs registers test by writing known data and confirming readback data.
static const LMS7Parameter * GetParam (const std::string &name)
Get parameter by name.
RF selection
enum PathRFE {
PATH_RFE_NONE = 0, PATH_RFE_LNAH, PATH_RFE_LNAL, PATH_RFE_LNAW,
PATH_RFE_LB1, PATH_RFE_LB2
}
int SetPathRFE (PathRFE path)
Set the RFE input path.
PathRFE GetPathRFE (void)
Get the currently set RFE path.
int SetBandTRF (const int band)
int GetBandTRF (void)
CGEN and PLL
enum VCO_Module { VCO_CGEN, VCO_SXR, VCO_SXT }
VCO modules available for tuning.
int SetReferenceClk_SX (bool tx, float_type freq_Hz)
float_type GetReferenceClk_SX (bool tx)
Returns reference clock in Hz used for SXT or SXR.
float_type GetFrequencyCGEN ()
int SetFrequencyCGEN (float_type freq_Hz, const bool retainNCOfrequencies=false, CGEN_details *output=nullptr)
Sets CLKGEN frequency, calculations use receiver'r reference clock.
bool GetCGENLocked (void)
float_type GetFrequencySX (bool tx)
Returns currently set SXR/SXT frequency.
int SetFrequencySX (bool tx, float_type freq_Hz, SX_details *output=nullptr)
Sets SX frequency.
int SetFrequencySXWithSpurCancelation (bool tx, float_type freq_Hz, float_type BW)
Sets SX frequency with Reference clock spur cancelation.
bool GetSXLocked (bool tx)
int TuneCGENVCO ()
Performs VCO tuning operations for CLKGEN.
int TuneVCO (VCO_Module module)
Performs VCO tuning operations for CLKGEN, SXR, SXT modules.
LML
enum LMLSampleSource { AI = 0, AQ = 1, BI = 2, BQ = 3 }
void ConfigureLML_RF2BB (const LMLSampleSource s0, const LMLSampleSource s1, const LMLSampleSource s2, const LMLSampleSource s3)
void ConfigureLML_BB2RF (const LMLSampleSource s0, const LMLSampleSource s1, const LMLSampleSource s2, const LMLSampleSource s3)
Detailed Description
Definition at line 41 of file LMS7002M.h.
Member Enumeration Documentation
anonymous enum
Enumerator
Rx
Tx
Definition at line 44 of file LMS7002M.h.
enum lime::LMS7002M::Channel
Enum for configuring the channel selection.
See also
MAC register
Enumerator
ChA
ChB
ChAB
ChSXR
ChSXT
Definition at line 95 of file LMS7002M.h.
enum lime::LMS7002M::LMLSampleSource
Enumerator
AI
AQ
BI
BQ
Definition at line 320 of file LMS7002M.h.
enum lime::LMS7002M::LogType
Enumerator
LOG_INFO
LOG_WARNING
LOG_ERROR
LOG_DATA
Definition at line 420 of file LMS7002M.h.
enum lime::LMS7002M::MemorySection
enumeration to indicate module registers intervals
Enumerator
LimeLight
EN_DIR
AFE
BIAS
XBUF
CGEN
LDO
BIST
CDS
TRF
TBB
RFE
RBB
SX
TRX_GAIN
TxTSP
TxNCO
TxGFIR1
TxGFIR2
TxGFIR3a
TxGFIR3b
TxGFIR3c
RxTSP
RxNCO
RxGFIR1
RxGFIR2
RxGFIR3a
RxGFIR3b
RxGFIR3c
RSSI_DC_CALIBRATION
RSSI_PDET_TEMP_CONFIG
RSSI_DC_CONFIG
MEMORY_SECTIONS_COUNT
Definition at line 400 of file LMS7002M.h.
enum lime::LMS7002M::PathRFE
Enumerator
PATH_RFE_NONE
PATH_RFE_LNAH
PATH_RFE_LNAL
PATH_RFE_LNAW
PATH_RFE_LB1
PATH_RFE_LB2
Definition at line 253 of file LMS7002M.h.
enum lime::LMS7002M::VCO_Module
VCO modules available for tuning.
Enumerator
VCO_CGEN
VCO_SXR
VCO_SXT
Definition at line 294 of file LMS7002M.h.
Constructor & Destructor Documentation
LMS7002M::LMS7002M ()
Creates LMS7002M main control object.
It requires IConnection to be set by SetConnection() to communicate with chip
Definition at line 122 of file LMS7002M.cpp.
References AFE, BIAS, BIST, CDS, CGEN, EN_DIR, lime::MCU_BD::Initialize(), lime::LMS7002M_RegistersMap::InitializeDefaultValues(), LDO, LimeLight, mCalibrationByMCU, mcuControl, MemorySectionAddresses, mRegistersMap, opt_gain_tbb, RBB, RFE, RSSI_DC_CALIBRATION, RSSI_DC_CONFIG, RSSI_PDET_TEMP_CONFIG, RxGFIR1, RxGFIR2, RxGFIR3a, RxGFIR3b, RxGFIR3c, RxNCO, RxTSP, SX, TBB, TRF, TRX_GAIN, TxGFIR1, TxGFIR2, TxGFIR3a, TxGFIR3b, TxGFIR3c, TxNCO, TxTSP, and XBUF.
LMS7002M::~LMS7002M () virtual
Definition at line 204 of file LMS7002M.cpp.
References mcuControl, and mRegistersMap.
Member Function Documentation
void lime::LMS7002M::AdjustAutoDC (const uint16_t address, bool tx) protected
void lime::LMS7002M::BackupAllRegisters () protected
LMS7002M_RegistersMap * LMS7002M::BackupRegisterMap (void)
Definition at line 33 of file LMS7002M_filtersCalibration.cpp.
References ChA, GetActiveChannel(), mRegistersMap, and SetActiveChannel().
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), and CalibrateTxGain().
void lime::LMS7002M::BinarySearch (BinSearchParam * args) protected
int LMS7002M::CalibrateAnalogRSSI_DC_Offset ()
Definition at line 2701 of file LMS7002M.cpp.
References CalibrateInternalADC(), lime::debug(), Get_SPI_Reg_bits(), LMS7_EN_INSHSW_W_RFE, LMS7param, Modify_SPI_Reg_bits(), PD_RSSI_RFE, PD_TIA_RFE, lime::ReportError(), and SPI_write().
Referenced by lms7002_pnlR3_view::OnCalibrateAnalogRSSI().
int LMS7002M::CalibrateInternalADC (int clkDiv = 32)
Definition at line 11 of file LMS7002M_BaseCalibrations.cpp.
References lime::error(), Get_SPI_Reg_bits(), LMS7_DAC_CLKDIV, LMS7_MASK, LMS7_MUX_BIAS_OUT, LMS7_RSSI_BIAS, LMS7_RSSI_DAC_VAL, LMS7_RSSI_PD, LMS7_RSSI_RSSIMODE, Modify_SPI_Reg_bits(), lime::ReportError(), SPI_read(), and SPI_write().
Referenced by CalibrateAnalogRSSI_DC_Offset(), GetTemperature(), and lms7002_mainPanel::OnCalibrateInternalADC().
void lime::LMS7002M::CalibrateIQImbalance (const bool tx, uint16_t * gainI = nullptr, uint16_t * gainQ = nullptr, int16_t * phase = nullptr) protected
int LMS7002M::CalibrateRP_BIAS ()
Definition at line 46 of file LMS7002M_BaseCalibrations.cpp.
References lime::error(), Get_SPI_Reg_bits(), LMS7_MASK, LMS7_MUX_BIAS_OUT, LMS7_RP_CALIB_BIAS, LMS7_RSSI_PD, LMS7_RSSI_RSSIMODE, Modify_SPI_Reg_bits(), lime::ReportError(), and SPI_read().
Referenced by lms7002_pnlBIAS_view::OnCalibrateRP_BIAS().
int LMS7002M::CalibrateRx (float_type bandwidth_Hz, const bool useExtLoopback = false)
Calibrates Receiver.
DC offset, IQ gains, IQ phase correction
Returns
0-success, other-failure
Definition at line 295 of file LMS7002M_RxTxCalibrations.cpp.
References Get_SPI_Reg_bits(), GetExtLoopPair(), GetFrequencySX(), info, LMS7_DC_RXAI, LMS7_DC_RXAQ, LMS7_DC_RXBI, LMS7_DC_RXBQ, LMS7_G_LNA_RFE, LMS7_G_PGA_RBB, LMS7_G_TIA_RFE, LMS7_GCORRI_RXTSP, LMS7_GCORRQ_RXTSP, LMS7_IQCORR_RXTSP, LMS7_MAC, LMS7_SEL_PATH_RFE, MCU_BW, MCU_EXT_LOOPBACK_PAIR, MCU_FUNCTION_CALIBRATE_RX, MCU_FUNCTION_CALIBRATE_RX_EXTLOOPB, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, MCU_NO_ERROR, mcu_program_lms7_dc_iq_calibration_bin, MCU_REF_CLK, ReadAnalogDC(), lime::ReportError(), SetExtLoopback(), signextIqCorr(), SPI_read(), status, TrxCalib_RF_LimitHigh, TrxCalib_RF_LimitLow, and verbose_printf.
Referenced by lime::LMS7_Device::Calibrate().
void lime::LMS7002M::CalibrateRxDC () protected
void lime::LMS7002M::CalibrateRxDCAuto () protected
int lime::LMS7002M::CalibrateRxSetup (const float_type bandwidth_Hz, const bool useExtLoopback) protected
int LMS7002M::CalibrateTx (float_type bandwidth_Hz, const bool useExtLoopback = false)
Calibrates Transmitter.
DC correction, IQ gains, IQ phase correction
Returns
0-success, other-failure
Definition at line 203 of file LMS7002M_RxTxCalibrations.cpp.
References Get_SPI_Reg_bits(), GetExtLoopPair(), GetFrequencySX(), info, LMS7_CG_IAMP_TBB, LMS7_DC_TXAI, LMS7_DC_TXAQ, LMS7_DC_TXBI, LMS7_DC_TXBQ, LMS7_GCORRI_TXTSP, LMS7_GCORRQ_TXTSP, LMS7_IQCORR_TXTSP, LMS7_MAC, LMS7_SEL_BAND1_TRF, MCU_BW, MCU_EXT_LOOPBACK_PAIR, MCU_FUNCTION_CALIBRATE_TX, MCU_FUNCTION_CALIBRATE_TX_EXTLOOPB, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, MCU_NO_ERROR, mcu_program_lms7_dc_iq_calibration_bin, MCU_REF_CLK, ReadAnalogDC(), lime::ReportError(), SetExtLoopback(), signextIqCorr(), SPI_read(), status, TrxCalib_RF_LimitHigh, TrxCalib_RF_LimitLow, and verbose_printf.
Referenced by lime::LMS7_Device::Calibrate().
void lime::LMS7002M::CalibrateTxDC (int16_t * dccorri, int16_t * dccorrq) protected
void lime::LMS7002M::CalibrateTxDCAuto () protected
int LMS7002M::CalibrateTxGain (float maxGainOffset_dBFS, float * actualGain_dBFS)
Definition at line 100 of file LMS7002M_gainCalibrations.cpp.
References BackupRegisterMap(), CalibrateTxGainSetup(), CG_IAMP_TBB, controlPort, lime::error(), Get_SPI_Reg_bits(), GetActiveChannelIndex(), GetRSSI(), ind, LMS7param, LRST_TX_A, Modify_SPI_Reg_bits(), opt_gain_tbb, RestoreRegisterMap(), and status.
Referenced by GetTBBIAMP_dB(), lms7002_pnlTBB_view::OnbtnTuneTxGain(), and SetTBBIAMP_dB().
int LMS7002M::CalibrateTxGainSetup () protected
Definition at line 5 of file LMS7002M_gainCalibrations.cpp.
References AFE, AGC_AVG_RXTSP, AGC_MODE_RXTSP, BIAS, CG_IAMP_TBB, CGEN, CMIX_BYP_RXTSP, CMIX_GAIN_TXTSP, CMIX_GAIN_TXTSP_R3, EN_G_RFE, EN_G_TRF, G_PGA_RBB, Get_SPI_Reg_bits(), HBD_OVR_RXTSP, INPUT_CTL_PGA_RBB, INSEL_TXTSP, ISEL_DAC_AFE, ISINC_BYP_TXTSP, LMS7param, LoadDC_REG_IQ(), LOOPB_TBB, MAC, Modify_SPI_Reg_bits(), PD_LPFL_RBB, PD_RX_AFE2, PD_TX_AFE2, PD_VCO, RBB, RCC_CTL_PGA_RBB, RP_CALIB_BIAS, RxNCO, RxTSP, SetDefaults(), SetFrequencyCGEN(), SetNCOFrequency(), SPI_read(), SPI_write(), status, TSGMODE_TXTSP, Tx, TxNCO, and TxTSP.
Referenced by CalibrateTxGain().
int lime::LMS7002M::CalibrateTxSetup (const float_type bandwidth_Hz, const bool useExtLoopback) protected
int lime::LMS7002M::CheckSaturationRx (const float_type bandwidth_Hz, const bool useExtLoopback) protected
int lime::LMS7002M::CheckSaturationTxRx (const float_type bandwidth_Hz, const bool useExtLoopback) protected
void lime::LMS7002M::CoarseSearch (const uint16_t addr, const uint8_t msb, const uint8_t lsb, int16_t & value, const uint8_t maxIterations) protected
void LMS7002M::ConfigureLML_BB2RF (const LMLSampleSource s0, const LMLSampleSource s1, const LMLSampleSource s2, const LMLSampleSource s3)
Set the LML sample positions in the baseband to RF direction.
Definition at line 2544 of file LMS7002M.cpp.
References AI, AQ, BI, BQ, LML1_AIP, LML1_AQP, LML1_BIP, LML1_BQP, LML2_AIP, LML2_AQP, LML2_BIP, LML2_BQP, LMS7param, and Modify_SPI_Reg_bits().
void LMS7002M::ConfigureLML_RF2BB (const LMLSampleSource s0, const LMLSampleSource s1, const LMLSampleSource s2, const LMLSampleSource s3)
Set the LML sample positions in the RF to baseband direction.
Definition at line 2518 of file LMS7002M.cpp.
References AI, AQ, BI, BQ, LML1_S0S, LML1_S1S, LML1_S2S, LML1_S3S, LML2_S0S, LML2_S1S, LML2_S2S, LML2_S3S, LMS7param, and Modify_SPI_Reg_bits().
int LMS7002M::CopyChannelRegisters (const Channel src, const Channel dest, bool copySX)
Definition at line 2679 of file LMS7002M.cpp.
References address, ChA, controlPort, GetActiveChannel(), lime::LMS7002M_RegistersMap::GetUsedAddresses(), lime::LMS7002M_RegistersMap::GetValue(), MemorySectionAddresses, mRegistersMap, SetActiveChannel(), lime::LMS7002M_RegistersMap::SetValue(), SX, and UploadAll().
int LMS7002M::DownloadAll ()
Reads all registers from the chip to host.
Definition at line 2382 of file LMS7002M.cpp.
References ChA, ChB, controlPort, lime::error(), GetActiveChannel(), lime::LMS7002M_RegistersMap::GetUsedAddresses(), i, mRegistersMap, SetActiveChannel(), lime::LMS7002M_RegistersMap::SetValue(), SPI_read_batch(), and status.
Referenced by lime::LMS7_Device::Synchronize().
void LMS7002M::EnableCalibrationByMCU (bool enabled)
Definition at line 2647 of file LMS7002M.cpp.
References enabled, and mCalibrationByMCU.
int LMS7002M::EnableChannel (const bool isTx, const bool enable)
Enable/disable the selected channel. This powers on or off all of the respective hardware for a given channel A or B: TSP, BB, and RF sections.
Parameters
isTx true for the transmit size, false for receive
enable true to enable, false to disable
Definition at line 231 of file LMS7002M.cpp.
References LMS7Parameter::address, AGC_BYP_RXTSP, AGC_MODE_RXTSP, ChA, ChB, ChSXR, ChSXT, CMIX_BYP_RXTSP, CMIX_BYP_TXTSP, DC_BYP_RXTSP, DC_BYP_TXTSP, EN_DIR_AFE, EN_DIR_RBB, EN_DIR_RFE, EN_DIR_SXRSXT, EN_DIR_TBB, EN_DIR_TRF, EN_G, EN_G_AFE, EN_G_RBB, EN_G_RFE, EN_G_TBB, EN_G_TRF, EN_NEXTRX_RFE, EN_NEXTTX_TRF, EN_RXTSP, EN_TXTSP, GC_BYP_RXTSP, GC_BYP_TXTSP, Get_SPI_Reg_bits(), GetActiveChannel(), GFIR1_BYP_RXTSP, GFIR1_BYP_TXTSP, GFIR2_BYP_RXTSP, GFIR2_BYP_TXTSP, GFIR3_BYP_RXTSP, GFIR3_BYP_TXTSP, ISINC_BYP_TXTSP, LMS7_PD_AFE, LMS7_PD_RX_AFE1, LMS7_PD_RX_AFE2, LMS7_PD_TX_AFE1, LMS7_PD_TX_AFE2, LMS7_RXEN_A, LMS7_RXEN_B, LMS7_TXEN_A, LMS7_TXEN_B, LMS7param, Modify_SPI_Reg_bits(), PD_AFE, PD_LNA_RFE, PD_LPFH_TBB, PD_LPFIAMP_TBB, PD_LPFL_RBB, PD_MXLOBUF_RFE, PD_PGA_RBB, PD_QGEN_RFE, PD_TIA_RFE, PD_TLOBUF_TRF, PD_TXPAD_TRF, PH_BYP_RXTSP, PH_BYP_TXTSP, RXEN_A, RXEN_B, SetActiveChannel(), TXEN_A, and TXEN_B.
Referenced by lime::LMS7_Device::EnableChannel(), lime::LMS7_LimeSDR_mini::Init(), and lime::LMS7_Device::Init().
int LMS7002M::EnableSXTDD (bool enable)
Enables/disables TDD mode
Parameters
enable true - use same pll for Tx and Rx, false - us seperate PLLs
Returns
0 for success for error condition
Definition at line 2577 of file LMS7002M.cpp.
References LMS7_MAC, LMS7_PD_LOCH_T2RBUF, LMS7_PD_VCO, and Modify_SPI_Reg_bits().
Referenced by lime::LMS7_LimeSDR_mini::SetFrequency(), and lime::LMS7_Device::SetFrequency().
void LMS7002M::EnableValuesCache (bool enabled = true)
Definition at line 2632 of file LMS7002M.cpp.
References enabled, and useCache.
void lime::LMS7002M::FineSearch (const uint16_t addrI, const uint8_t msbI, const uint8_t lsbI, int16_t & valueI, const uint16_t addrQ, const uint8_t msbQ, const uint8_t lsbQ, int16_t & valueQ, const uint8_t fieldSize) protected
uint16_t LMS7002M::Get_SPI_Reg_bits (const LMS7Parameter & param, bool fromChip = false)
Returns given parameter value from chip register.
Parameters
param LMS7002M control parameter
fromChip read directly from chip
Returns
parameter value
Definition at line 1370 of file LMS7002M.cpp.
References LMS7Parameter::address, LMS7Parameter::lsb, and LMS7Parameter::msb.
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), CalibrateAnalogRSSI_DC_Offset(), CalibrateTxGain(), CalibrateTxGainSetup(), ConfigureCGEN(), lime::LMS7_Device::ConfigureGFIR(), DCIQ(), EnableChannel(), Filters(), GetActiveChannel(), GetBandTRF(), GetCGENLocked(), GetExtLoopPair(), lime::LMS7_Device::GetFrequency(), GetFrequencyCGEN(), GetFrequencySX(), GetGFIRCoefficients(), GetIQBalance(), lime::LMS7_Device::GetNCOFreq(), GetPathRFE(), lime::LMS7_Device::GetRate(), GetRBBPGA_dB(), GetReferenceClk_TSP(), GetRFELNA_dB(), GetRFELoopbackLNA_dB(), GetRFETIA_dB(), GetRxDCRemoval(), GetSampleRate(), GetSXLocked(), GetTBBIAMP_dB(), GetTemperature(), lime::LMS7_Device::GetTestSignal(), GetTRFLoopbackPAD_dB(), GetTRFPAD_dB(), GetTxDCOffset(), lime::LMS7_Device::LoadConfig(), LoadConfigLegacyFile(), lms7002_pnlCLKGEN_view::onbtnCalculateClick(), lms7002_pnlCLKGEN_view::onbtnTuneClick(), SaveConfig(), lime::LMS7_Device::SetClockFreq(), SetFrequencyCGEN(), SetFrequencySX(), SetFrequencySXWithSpurCancelation(), lime::LMS7_Device::SetGFIR(), lime::LMS7_Device::SetGFIRCoef(), SetInterfaceFrequency(), lime::LMS7_Device::SetNCOFreq(), lime::LMS7_Device::SetRate(), lime::LMS7_Device::Synchronize(), TuneCGENVCO(), TuneRxFilter(), TuneVCO(), and lime::Streamer::UpdateThreads().
uint16_t LMS7002M::Get_SPI_Reg_bits (uint16_t address, uint8_t msb, uint8_t lsb, bool fromChip = false)
Returns given parameter value from chip register.
Parameters
address register address
msb most significant bit index
lsb least significant bit index
fromChip read directly from chip
Returns
register bits from selected interval, shifted to right by lsb bits
Definition at line 1382 of file LMS7002M.cpp.
References SPI_read().
LMS7002M::Channel LMS7002M::GetActiveChannel (bool fromChip = true)
Get the selected channel (MAC). The API calls will reflect this channel.
Definition at line 216 of file LMS7002M.cpp.
References Get_SPI_Reg_bits(), LMS7param, and MAC.
Referenced by BackupRegisterMap(), CopyChannelRegisters(), DownloadAll(), EnableChannel(), GetActiveChannelIndex(), GetFrequencySX(), GetSampleRate(), IsSynced(), LoadConfig(), LoadConfigLegacyFile(), RegistersTest(), RestoreRegisterMap(), SaveConfig(), SetActiveChannel(), SetFrequencyCGEN(), SetFrequencySX(), TuneVCO(), and UploadAll().
size_t LMS7002M::GetActiveChannelIndex (bool fromChip = true)
Get the channel selected by the RFIC index (devIndex), and by the currently selected RF channel A/B (MAC). Example when devIndex == 0, return 0 for chA, 1 for chB.
Definition at line 222 of file LMS7002M.cpp.
References ChB, GetActiveChannel(), and mdevIndex.
Referenced by CalibrateTxGain(), ConfigureCGEN(), GetTBBIAMP_dB(), SetTBBIAMP_dB(), TEST_F(), and TuneTxFilter().
uint32_t lime::LMS7002M::GetAvgRSSI (const int avgCount) protected
int LMS7002M::GetBandTRF (void)
Get the TRF Band selection.
Returns
the band 1 or 2
Definition at line 1022 of file LMS7002M.cpp.
References Get_SPI_Reg_bits(), LMS7param, SEL_BAND1_TRF, and SEL_BAND2_TRF.
Referenced by lime::LMS7_Device::GetPath().
bool LMS7002M::GetCGENLocked (void)
Definition at line 1159 of file LMS7002M.cpp.
References address, Get_SPI_Reg_bits(), LMS7param, and VCO_CMPHO_CGEN.
Referenced by SoapyLMS7::readSensor().
IConnection* lime::LMS7002M::GetConnection (void) const inline
Definition at line 84 of file LMS7002M.h.
Referenced by DCIQ(), and GetExtLoopPair().
float_type LMS7002M::GetFrequencyCGEN ()
Returns
Current CLKGEN frequency in Hz Returned frequency depends on reference clock used for Receiver
Definition at line 1047 of file LMS7002M.cpp.
References DIV_OUTCH_CGEN, Get_SPI_Reg_bits(), GetReferenceClk_SX(), LMS7param, and Rx.
Referenced by GetReferenceClk_TSP(), lime::LMS7_Device::LoadConfig(), lms7002_pnlCLKGEN_view::onbtnCalculateClick(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_Device::SetRate(), and lime::LMS7_Device::Synchronize().
float_type LMS7002M::GetFrequencySX (bool tx)
Returns currently set SXR/SXT frequency.
Returns
SX frequency Hz
Definition at line 1676 of file LMS7002M.cpp.
References ChSXR, ChSXT, DIV_LOCH, EN_DIV2_DIVPROG, Get_SPI_Reg_bits(), GetActiveChannel(), GetReferenceClk_SX(), LMS7param, and SetActiveChannel().
Referenced by lime::Streamer::AlignQuadrature(), and lime::LMS7_Device::GetFrequency().
int LMS7002M::GetGFIRCoefficients (bool tx, uint8_t GFIR_index, int16_t * coef, uint8_t coefCount)
Returns currently loaded FIR coefficients.
Parameters
tx Transmitter or receiver selection
GFIR_index GIR index from 0 to 2
coef array of returned coefficients
coefCount number of coefficients to read
Returns
0-success, other-failure
Definition at line 1817 of file LMS7002M.cpp.
References controlPort, Get_SPI_Reg_bits(), lime::LMS7002M_RegistersMap::GetValue(), index, lime::IConnection::IsOpen(), LMS7param, MAC, mRegistersMap, lime::ReportError(), SPI_read_batch(), and status.
Referenced by lime::LMS7_Device::GetGFIRCoef().
void LMS7002M::GetIQBalance (const bool tx, float_type & phase, float_type & gainI, float_type & gainQ)
Get the IQ imbalance correction.
Parameters
tx true for tx, false for rx
[out] phase the phase adjustment [+pi, -pi]
[out] gainI the real gain adjustment [+1.0, 0.0]
[out] gainQ the imaginary gain adjustment [+1.0, 0.0]
Definition at line 2621 of file LMS7002M.cpp.
References GCORRI_RXTSP, GCORRI_TXTSP, GCORRQ_RXTSP, GCORRQ_TXTSP, Get_SPI_Reg_bits(), IQCORR_RXTSP, IQCORR_TXTSP, and LMS7param.
MCU_BD * LMS7002M::GetMCUControls () const
Definition at line 2642 of file LMS7002M.cpp.
References mcuControl.
Referenced by SPI_read(), and SPI_write().
float_type LMS7002M::GetNCOFrequency (bool tx, uint8_t index, bool fromChip = true)
Returns chosen NCO's frequency in Hz.
Parameters
tx transmitter or receiver selection
index NCO index from 0 to 15
fromChip read frequency directly from chip or local registers
Returns
NCO frequency in Hz
Definition at line 1718 of file LMS7002M.cpp.
References fcw, GetReferenceClk_TSP(), lime::ReportError(), and SPI_read().
Referenced by lime::LMS7_Device::GetNCOFreq(), and SetFrequencyCGEN().
float_type LMS7002M::GetNCOPhaseOffset_Deg (bool tx, uint8_t index)
Returns chosen NCO's phase offset angle in radians.
Parameters
tx transmitter or receiver selection
index PHO index from 0 to 15
Returns
phase offset angle in degrees
Definition at line 1764 of file LMS7002M.cpp.
References pho, lime::ReportError(), and SPI_read().
Referenced by lime::LMS7_Device::GetNCOPhase().
const LMS7Parameter * LMS7002M::GetParam (const std::string & name) static
Get parameter by name.
Parameters
name parameter name
Definition at line 1441 of file LMS7002M.cpp.
References string().
Referenced by lime::LMS7_Device::ReadParam(), and lime::LMS7_Device::WriteParam().
LMS7002M::PathRFE LMS7002M::GetPathRFE (void)
Get the currently set RFE path.
Definition at line 1003 of file LMS7002M.cpp.
References EN_INSHSW_L_RFE, EN_INSHSW_LB1_RFE, EN_INSHSW_LB2_RFE, EN_INSHSW_W_RFE, Get_SPI_Reg_bits(), LMS7param, PATH_RFE_LB1, PATH_RFE_LB2, PATH_RFE_LNAH, PATH_RFE_LNAL, PATH_RFE_LNAW, PATH_RFE_NONE, and SEL_PATH_RFE.
Referenced by lime::LMS7_Device::GetPath().
float_type LMS7002M::GetRBBPGA_dB (void)
Get the actual RX PGA gain in dB.
Definition at line 754 of file LMS7002M.cpp.
References G_PGA_RBB, Get_SPI_Reg_bits(), and LMS7param.
Referenced by lime::LMS7_Device::GetGain().
float_type LMS7002M::GetReferenceClk_SX (bool tx)
Returns reference clock in Hz used for SXT or SXR.
Parameters
Tx transmitter or receiver selection
Definition at line 1039 of file LMS7002M.cpp.
References _cachedRefClockRate.
Referenced by GetFrequencyCGEN(), GetFrequencySX(), main(), LMS7SuiteAppFrame::OnControlBoardConnect(), SaveConfig(), lime::LMS7_Device::SetClockFreq(), SetFrequencyCGEN(), SetFrequencySX(), SetFrequencySXWithSpurCancelation(), TuneRxFilter(), and TuneTxFilter().
float_type LMS7002M::GetReferenceClk_TSP (bool tx)
Returns TSP reference frequency.
Parameters
tx TxTSP or RxTSP selection
Returns
TSP reference frequency in Hz
Definition at line 1059 of file LMS7002M.cpp.
References CLKH_OV_CLKL_CGEN, EN_ADCCLKH_CLKGN, Get_SPI_Reg_bits(), GetFrequencyCGEN(), and LMS7param.
Referenced by ConfigureCGEN(), lime::LMS7_Device::ConfigureGFIR(), GetNCOFrequency(), lime::LMS7_Device::GetRate(), GetSampleRate(), lime::LMS7_Device::LoadConfig(), lime::LMS7_Device::SetGFIRCoef(), SetNCOFrequency(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_Device::SetRate(), lime::LMS7_Device::Synchronize(), and lms7002_pnlRxTSP_view::UpdateGUI().
float_type LMS7002M::GetRFELNA_dB (void)
Get the actual RX LNA gain in dB.
Definition at line 785 of file LMS7002M.cpp.
References G_LNA_RFE, Get_SPI_Reg_bits(), and LMS7param.
Referenced by lime::LMS7_Device::GetGain().
float_type LMS7002M::GetRFELoopbackLNA_dB (void)
Get the actual RX loopback LNA gain in dB.
Definition at line 836 of file LMS7002M.cpp.
References G_RXLOOPB_RFE, Get_SPI_Reg_bits(), and LMS7param.
Referenced by lime::LMS7_Device::GetGain().
float_type LMS7002M::GetRFETIA_dB (void)
Get the actual RX TIA gain in dB.
Definition at line 874 of file LMS7002M.cpp.
References G_TIA_RFE, Get_SPI_Reg_bits(), and LMS7param.
Referenced by lime::LMS7_Device::GetGain().
uint32_t LMS7002M::GetRSSI (RSSI_measurements * measurements = nullptr) protected
Flips the CAPTURE bit and returns digital RSSI value.
Definition at line 190 of file LMS7002M_RxTxCalibrations.cpp.
References Get_SPI_Reg_bits(), LMS7_CAPTURE, and Modify_SPI_Reg_bits().
Referenced by CalibrateTxGain().
bool LMS7002M::GetRxDCRemoval (void)
Get the RX DC removal filter enabled.
Definition at line 2585 of file LMS7002M.cpp.
References DC_BYP_RXTSP, Get_SPI_Reg_bits(), and LMS7param.
float_type LMS7002M::GetSampleRate (bool tx, Channel ch)
Get the sample rate in Hz.
Definition at line 2495 of file LMS7002M.cpp.
References Get_SPI_Reg_bits(), GetActiveChannel(), GetReferenceClk_TSP(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, LMS7param, Rx, SetActiveChannel(), and Tx.
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), lime::Streamer::SetupStream(), and TEST_F().
bool LMS7002M::GetSXLocked (bool tx)
Definition at line 1164 of file LMS7002M.cpp.
References address, ChSXR, ChSXT, Get_SPI_Reg_bits(), LMS7param, SetActiveChannel(), and VCO_CMPHO.
Referenced by SoapyLMS7::readSensor().
float_type LMS7002M::GetTBBIAMP_dB (void)
Get the TBB frontend gain in dB.
Definition at line 954 of file LMS7002M.cpp.
References CalibrateTxGain(), CG_IAMP_TBB, Get_SPI_Reg_bits(), GetActiveChannelIndex(), ind, LMS7param, Modify_SPI_Reg_bits(), and opt_gain_tbb.
Referenced by lime::LMS7_Device::GetGain(), and lime::LMS7_Device::SetLPF().
float_type LMS7002M::GetTemperature ()
Definition at line 2652 of file LMS7002M.cpp.
References CalibrateInternalADC(), lime::debug(), Get_SPI_Reg_bits(), LMS7_MUX_BIAS_OUT, LMS7_RSSI_PD, LMS7_RSSI_RSSIMODE, Modify_SPI_Reg_bits(), and SPI_read().
float_type LMS7002M::GetTRFLoopbackPAD_dB (void)
Get the actual TX loopback PAD gain in dB.
Definition at line 925 of file LMS7002M.cpp.
References Get_SPI_Reg_bits(), L_LOOPB_TXPAD_TRF, and LMS7param.
Referenced by lime::LMS7_Device::GetGain().
float_type LMS7002M::GetTRFPAD_dB (void)
Get the actual TX PAD gain in dB.
Definition at line 905 of file LMS7002M.cpp.
References Get_SPI_Reg_bits(), LMS7param, and LOSS_LIN_TXPAD_TRF.
Referenced by lime::LMS7_Device::GetGain(), and lime::LMS7_Device::SetGain().
void LMS7002M::GetTxDCOffset (float_type & I, float_type & Q)
Readback the TX DC offset adjustment.
Parameters
[out] I the real adjustment [+1.0, -1.0]
[out] Q the imaginary adjustment [+1.0, -1.0]
Definition at line 2599 of file LMS7002M.cpp.
References DCCORRI_TXTSP, DCCORRQ_TXTSP, Get_SPI_Reg_bits(), and LMS7param.
void lime::LMS7002M::GridSearch (GridSearchParam * args) protected
bool LMS7002M::IsSynced ()
Reads all chip configuration and checks if it matches with local registers copy.
Definition at line 2233 of file LMS7002M.cpp.
References ChA, ChB, controlPort, lime::debug(), GetActiveChannel(), lime::LMS7002M_RegistersMap::GetUsedAddresses(), lime::LMS7002M_RegistersMap::GetValue(), i, lime::IConnection::IsOpen(), mdevIndex, mRegistersMap, lime::IConnection::ReadLMS7002MSPI(), readOnlyRegisters, readOnlyRegistersMasks, SetActiveChannel(), and status.
bool LMS7002M::IsValuesCacheEnabled ()
Definition at line 2637 of file LMS7002M.cpp.
References useCache.
int LMS7002M::LoadConfig (const char * filename)
Reads configuration file and uploads registers to chip.
Parameters
filename Configuration source file
Returns
0-success, other-failure
Definition at line 576 of file LMS7002M.cpp.
References ChA, ChB, controlPort, GetActiveChannel(), LMS7param, LoadConfigLegacyFile(), MAC, top_block::parser, lime::ReportError(), Rx, SetActiveChannel(), SetReferenceClk_SX(), SPI_write(), SPI_write_batch(), status, and Tx.
Referenced by lime::LMS7_Device::LoadConfig(), and main().
int LMS7002M::LoadConfigLegacyFile (const char * filename) protected
Definition at line 392 of file LMS7002M.cpp.
References ChA, ChB, controlPort, Get_SPI_Reg_bits(), GetActiveChannel(), i, LMS7param, MAC, mode, MODE_RX, MODE_TX, top_block::parser, lime::ReportError(), Rx, SetActiveChannel(), SetNCOFrequency(), SetNCOPhaseOffset(), SetReferenceClk_SX(), SPI_write(), SPI_write_batch(), status, and Tx.
Referenced by LoadConfig().
int LMS7002M::LoadDC_REG_IQ (bool tx, int16_t I, int16_t Q)
Loads given DC_REG values into registers.
Parameters
tx TxTSP or RxTSP selection
I DC_REG I value
Q DC_REG Q value
Definition at line 399 of file LMS7002M_RxTxCalibrations.cpp.
References LMS7_DC_REG_RXTSP, LMS7_DC_REG_TXTSP, LMS7_TSGDCLDI_RXTSP, LMS7_TSGDCLDI_TXTSP, LMS7_TSGDCLDQ_RXTSP, LMS7_TSGDCLDQ_TXTSP, and Modify_SPI_Reg_bits().
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), CalibrateTxGainSetup(), DCIQ(), Filters(), and lime::LMS7_Device::SetTestSignal().
void LMS7002M::Log (const char * text, LogType type) protected virtual
Simple logging function to print status messages.
Parameters
text message to print
type message type for filtering specific information
Definition at line 49 of file LMS7002M.cpp.
References ap, lime::debug(), lime::error(), lime::info(), calc_fmcw_peaks::r, and lime::warning().
Referenced by TuneRxFilter(), and TuneTxFilter().
void lime::LMS7002M::Log (LogType type, const char * format, ...) inline protected
Definition at line 483 of file LMS7002M.h.
void LMS7002M::Log (LogType type, const char * format, va_list argList) protected
Definition at line 87 of file LMS7002M.cpp.
References message().
int LMS7002M::Modify_SPI_Reg_bits (const LMS7Parameter & param, const uint16_t value, bool fromChip = false)
Change given parameter value.
Parameters
param LMS7002M control parameter
fromChip read initial value directly from chip
value new parameter value
Definition at line 1392 of file LMS7002M.cpp.
References LMS7Parameter::address, LMS7Parameter::lsb, and LMS7Parameter::msb.
Referenced by lime::Streamer::AlignRxRF(), CalibrateAnalogRSSI_DC_Offset(), CalibrateTxGain(), CalibrateTxGainSetup(), ConfigureCGEN(), lime::LMS7_Device::ConfigureGFIR(), ConfigureLML_BB2RF(), ConfigureLML_RF2BB(), lime::LMS7_Device::ConfigureTXLPF(), DCIQ(), EnableChannel(), EnableSXTDD(), Filters(), lime::LMS7_Device::GetFrequency(), GetTBBIAMP_dB(), GetTemperature(), lime::LMS7_LimeSDR_mini::Init(), lime::LMS7_Device::Init(), lime::LMS7_Device::LoadConfig(), main(), lms7002_pnlCLKGEN_view::onbtnCalculateClick(), lms7002_pnlCLKGEN_view::onbtnTuneClick(), RegistersTest(), ResetChip(), lime::LMS7_Device::SelectChannel(), SetActiveChannel(), SetBandTRF(), lime::LMS7_Device::SetClockFreq(), SetFrequencyCGEN(), SetFrequencySX(), SetFrequencySXWithSpurCancelation(), lime::LMS7_Device::SetGain(), lime::LMS7_Device::SetGFIR(), lime::LMS7_Device::SetGFIRCoef(), SetInterfaceFrequency(), SetIQBalance(), lime::LMS7_Device::SetNCOFreq(), lime::LMS7_Device::SetNCOPhase(), lime::LMS7_LimeSDR_mini::SetPath(), SetPathRFE(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_Device::SetRate(), SetRBBPGA_dB(), SetRFELNA_dB(), SetRFELoopbackLNA_dB(), SetRFETIA_dB(), SetRxDCRemoval(), SetTBBIAMP_dB(), lime::LMS7_Device::SetTestSignal(), SetTRFLoopbackPAD_dB(), SetTRFPAD_dB(), SetTxDCOffset(), lime::LMS7_Device::Synchronize(), TEST_F(), TuneCGENVCO(), and TuneVCO().
int LMS7002M::Modify_SPI_Reg_bits (uint16_t address, uint8_t msb, uint8_t lsb, uint16_t value, bool fromChip = false)
Change given parameter value.
Parameters
address register address
value new bits value, the value is shifted left by lsb bits
fromChip read initial value directly from chip
Definition at line 1402 of file LMS7002M.cpp.
References SPI_read(), and SPI_write().
int LMS7002M::Modify_SPI_Reg_mask (const uint16_t * addr, const uint16_t * masks, const uint16_t * values, uint8_t start, uint8_t stop) protected
Modifies given registers with values applied using masks.
Parameters
addr array of register addresses
masks array of applied masks
values array of values to be written
start starting index of given arrays
stop end index of given arrays
Definition at line 1417 of file LMS7002M.cpp.
References SPI_read(), SPI_write_batch(), and status.
int LMS7002M::RegistersTest (const char * fileName = "registersTest.txt")
Performs registers test by writing known data and confirming readback data.
Returns
0-registers test passed, other-failure
Definition at line 2026 of file LMS7002M.cpp.
References AFE, BIAS, BIST, CDS, CGEN, ChA, ChB, controlPort, lime::error(), GetActiveChannel(), i, LDO, LimeLight, LMS7param, MAC, MEMORY_SECTIONS_COUNT, MemorySectionAddresses, MIMO_SISO, Modify_SPI_Reg_bits(), p(), PD_RX_AFE2, PD_TX_AFE2, RBB, RegistersTestInterval(), ResetChip(), RFE, RxGFIR1, RxGFIR2, RxGFIR3a, RxGFIR3b, RxGFIR3c, RxNCO, RxTSP, SetActiveChannel(), SPI_read_batch(), SPI_write_batch(), status, SX, TBB, TRF, TxGFIR1, TxGFIR2, TxGFIR3a, TxGFIR3b, TxGFIR3c, TxNCO, TxTSP, and XBUF.
Referenced by LimeSDRTest::LMS7002mTest().
int LMS7002M::RegistersTestInterval (uint16_t startAddr, uint16_t endAddr, uint16_t pattern, std::stringstream & ss) protected
Performs registers test for given address interval by writing given pattern data.
Parameters
startAddr first register address
endAddr last reigster address
pattern data to be written into registers
Returns
0-register test passed, other-failure
Definition at line 2136 of file LMS7002M.cpp.
References k, readOnlyRegisters, readOnlyRegistersMasks, lime::ReportError(), SPI_read_batch(), SPI_write_batch(), and status.
Referenced by RegistersTest().
int LMS7002M::ResetChip ()
Sends reset signal to chip, after reset enables B channel controls.
Returns
0-success, other-failure
Definition at line 370 of file LMS7002M.cpp.
References controlPort, lime::IConnection::DeviceReset(), lime::LMS7002M_RegistersMap::InitializeDefaultValues(), LMS7param, mdevIndex, MIMO_SISO, Modify_SPI_Reg_bits(), mRegistersMap, status, and lime::warning().
Referenced by lime::LMS7_LimeSDR_mini::Init(), lime::LMS7_Device::Init(), LimeSDRTest::LMS7002mTest(), RegistersTest(), lime::LMS7_Device::Reset(), and TEST_F().
void lime::LMS7002M::RestoreAllRegisters () protected
void LMS7002M::RestoreRegisterMap (LMS7002M_RegistersMap * backup)
Definition at line 44 of file LMS7002M_filtersCalibration.cpp.
References ChA, ChB, GetActiveChannel(), lime::LMS7002M_RegistersMap::GetUsedAddresses(), lime::LMS7002M_RegistersMap::GetValue(), mRegistersMap, SetActiveChannel(), lime::LMS7002M_RegistersMap::SetValue(), and SPI_write_batch().
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), and CalibrateTxGain().
int lime::LMS7002M::RxFilterSearch (const LMS7Parameter & param, const uint32_t rssi_3dB, uint8_t rssiAvgCnt, const int stepLimit) protected
int LMS7002M::SaveConfig (const char * filename)
Reads all registers from chip and saves to file.
Parameters
filename destination filename
Returns
0-success, other failure
Definition at line 678 of file LMS7002M.cpp.
References ChA, ChB, Get_SPI_Reg_bits(), GetActiveChannel(), GetReferenceClk_SX(), i, MEMORY_SECTIONS_COUNT, MemorySectionAddresses, RSSI_DC_CALIBRATION, Rx, SetActiveChannel(), and Tx.
void LMS7002M::SetActiveChannel (const Channel ch)
Set the selected channel (MAC). The API calls will reflect this channel.
Definition at line 210 of file LMS7002M.cpp.
References GetActiveChannel(), LMS7param, MAC, and Modify_SPI_Reg_bits().
Referenced by BackupRegisterMap(), CopyChannelRegisters(), DownloadAll(), EnableChannel(), GetFrequencySX(), GetSampleRate(), GetSXLocked(), IsSynced(), LoadConfig(), LoadConfigLegacyFile(), RegistersTest(), RestoreRegisterMap(), SaveConfig(), SetFrequencyCGEN(), SetFrequencySX(), TEST_F(), TuneVCO(), and UploadAll().
int LMS7002M::SetBandTRF (const int band)
Set the TRF Band selection.
Parameters
band 1 or 2
Definition at line 1014 of file LMS7002M.cpp.
References LMS7param, Modify_SPI_Reg_bits(), SEL_BAND1_TRF, and SEL_BAND2_TRF.
Referenced by lime::LMS7_Device::SetPath().
void LMS7002M::SetConnection (IConnection * port, const size_t devIndex = 0)
Sets connection which is used for data communication with chip.
Set the connection for the LMS7002M driver.
Parameters
port the connection interface
devIndex which RFIC index (default 0 for most devices)
dataPort connection used to get samples data when calibrating with FFT
Definition at line 99 of file LMS7002M.cpp.
References Get_SPI_Reg_bits(), LMS7_MASK, and port.
Referenced by main(), and TEST_F().
int LMS7002M::SetDefaults (MemorySection module) virtual
Sets given module registers to default values.
Returns
0-success, other-failure
Definition at line 2217 of file LMS7002M.cpp.
References address, lime::LMS7002M_RegistersMap::GetDefaultValue(), MemorySectionAddresses, mRegistersMap, SPI_write_batch(), and status.
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), and CalibrateTxGainSetup().
int LMS7002M::SetFrequencyCGEN (float_type freq_Hz, const bool retainNCOfrequencies = false, CGEN_details * output = nullptr)
Sets CLKGEN frequency, calculations use receiver'r reference clock.
Parameters
freq_Hz desired frequency in Hz
retainNCOfrequencies recalculate NCO coefficients to keep currently set frequencies
output if not null outputs calculated CGEN parameters
Returns
0-succes, other-cannot deliver desired frequency
Definition at line 1075 of file LMS7002M.cpp.
References ChA, ChB, lime::LMS7002M::CGEN_details::csw, CSW_VCO_CGEN, lime::debug(), lime::LMS7002M::CGEN_details::div_outch_cgen, DIV_OUTCH_CGEN, lime::LMS7002M::CGEN_details::FRAC, lime::LMS7002M::CGEN_details::frequency, lime::LMS7002M::CGEN_details::frequencyVCO, gCGEN_VCO_frequencies, Get_SPI_Reg_bits(), GetActiveChannel(), GetNCOFrequency(), GetReferenceClk_SX(), i, lime::LMS7002M::CGEN_details::INT, INT_SDM_CGEN, LMS7param, MODE_RX, MODE_TX, Modify_SPI_Reg_bits(), lime::LMS7002M::CGEN_details::referenceClock, lime::ReportError(), Rx, SetActiveChannel(), SetNCOFrequency(), lime::LMS7002M::CGEN_details::success, TuneVCO(), Tx, and VCO_CGEN.
Referenced by CalibrateTxGainSetup(), SetInterfaceFrequency(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), and lime::LMS7_Device::SetRate().
int LMS7002M::SetFrequencySX (bool tx, float_type freq_Hz, SX_details * output = nullptr)
Sets SX frequency.
Parameters
Tx Rx/Tx module selection
freq_Hz desired frequency in Hz
output if not null outputs intermediate calculation values
Returns
0-success, other-cannot deliver requested frequency
Definition at line 1455 of file LMS7002M.cpp.
References address, ChSXR, ChSXT, lime::LMS7002M::SX_details::csw, CSW_VCO, lime::debug(), lime::LMS7002M::SX_details::div_loch, DIV_LOCH, lime::LMS7002M::SX_details::en_div2_divprog, EN_DIV2_DIVPROG, EN_INTONLY_SDM, lime::LMS7002M::SX_details::FRAC, lime::LMS7002M::SX_details::frequency, lime::LMS7002M::SX_details::frequencyVCO, Get_SPI_Reg_bits(), GetActiveChannel(), GetReferenceClk_SX(), gVCO_frequency_table, lime::info(), lime::LMS7002M::SX_details::INT, INT_SDM, LMS7param, Modify_SPI_Reg_bits(), PD_VCO, PD_VCO_COMP, lime::LMS7002M::SX_details::referenceClock, lime::ReportError(), lime::LMS7002M::SX_details::sel_vco, SEL_VCO, SetActiveChannel(), status, lime::LMS7002M::SX_details::success, TuneVCO(), useCache, VCO_CMPHO, VCO_SXR, and VCO_SXT.
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), lms7002_pnlSX_view::OnbtnCalculateClick(), lime::LMS7_Device::SetClockFreq(), lime::LMS7_LimeSDR_mini::SetFrequency(), lime::LMS7_Device::SetFrequency(), SetFrequencySXWithSpurCancelation(), and TEST_F().
int LMS7002M::SetFrequencySXWithSpurCancelation (bool tx, float_type freq_Hz, float_type BW)
Sets SX frequency with Reference clock spur cancelation.
Parameters
Tx Rx/Tx module selection
freq_Hz desired frequency in Hz
Returns
0-success, other-cannot deliver requested frequency
Definition at line 1606 of file LMS7002M.cpp.
References CMIX_BYP_RXTSP, CMIX_GAIN_RXTSP, CMIX_SC_RXTSP, EN_INTONLY_SDM, Get_SPI_Reg_bits(), GetReferenceClk_SX(), i, int(), LMS7param, MAC, Modify_SPI_Reg_bits(), Rx, SEL_RX, SetFrequencySX(), SetNCOFrequency(), status, and TuneRxFilter().
Referenced by lms7002_pnlSX_view::OnbtnCalculateClick().
int LMS7002M::SetGFIRCoefficients (bool tx, uint8_t GFIR_index, const int16_t * coef, uint8_t coefCount)
Uploads given FIR coefficients to chip.
Parameters
tx Transmitter or receiver selection
GFIR_index GIR index from 0 to 2
coef array of coefficients
coefCount number of coefficients
Returns
0-success, other-failure
This function does not change GFIR*_L or GFIR*_N parameters, they have to be set manually
Definition at line 1783 of file LMS7002M.cpp.
References index, lime::ReportError(), and SPI_write_batch().
Referenced by lime::LMS7_Device::ConfigureGFIR(), and lime::LMS7_Device::SetGFIRCoef().
int LMS7002M::SetInterfaceFrequency (float_type cgen_freq_Hz, const uint8_t interpolation, const uint8_t decimation)
Configures interfaces for desired frequency.
Returns
0-success, other-failure Sets interpolation and decimation, changes MCLK sources and TSP clock dividers accordingly to selected interpolation and decimation
Definition at line 2424 of file LMS7002M.cpp.
References Get_SPI_Reg_bits(), HBD_OVR_RXTSP, HBI_OVR_TXTSP, LMS7_LML1_SISODDR, LMS7_LML2_SISODDR, LMS7param, MCLK1SRC, MCLK2SRC, Modify_SPI_Reg_bits(), RX_MUX, RXDIVEN, RXRDCLK_MUX, RXTSPCLKA_DIV, RXWRCLK_MUX, SetFrequencyCGEN(), status, TX_MUX, TXDIVEN, TXRDCLK_MUX, TXTSPCLKA_DIV, and TXWRCLK_MUX.
Referenced by ConfigureCGEN(), lime::LMS7_Device::LoadConfig(), lms7002_pnlCLKGEN_view::onbtnCalculateClick(), lime::LMS7_Device::SetClockFreq(), lime::LMS7_LimeSDR::SetRate(), lime::LMS7_LimeSDR_mini::SetRate(), lime::LMS7_Device::SetRate(), lime::LMS7_Device::Synchronize(), and TEST_F().
int LMS7002M::SetIQBalance (const bool tx, const float_type phase, const float_type gainI, const float_type gainQ)
Set the IQ imbalance correction.
Parameters
tx true for tx, false for rx
phase the phase adjustment [+pi, -pi]
gainI the real gain adjustment [+1.0, 0.0]
gainQ the imaginary gain adjustment [+1.0, 0.0]
Definition at line 2605 of file LMS7002M.cpp.
References GC_BYP_RXTSP, GC_BYP_TXTSP, GCORRI_RXTSP, GCORRI_TXTSP, GCORRQ_RXTSP, GCORRQ_TXTSP, IQCORR_RXTSP, IQCORR_TXTSP, LMS7param, Modify_SPI_Reg_bits(), PH_BYP_RXTSP, and PH_BYP_TXTSP.
void LMS7002M::SetLogCallback (std::function< void(const char *, int)> callback)
Definition at line 2674 of file LMS7002M.cpp.
References callback, and log_callback.
int LMS7002M::SetNCOFrequency (bool tx, uint8_t index, float_type freq_Hz)
Sets chosen NCO's frequency.
Parameters
tx transmitter or receiver selection
index NCO index from 0 to 15
freq_Hz desired NCO frequency
Returns
0-success, other-failure
Definition at line 1698 of file LMS7002M.cpp.
References fcw, GetReferenceClk_TSP(), lime::ReportError(), and SPI_write().
Referenced by CalibrateTxGainSetup(), LoadConfigLegacyFile(), SetFrequencyCGEN(), SetFrequencySXWithSpurCancelation(), and lime::LMS7_Device::SetNCOFreq().
int LMS7002M::SetNCOPhaseOffset (bool tx, uint8_t index, float_type angle_deg)
Sets chosen NCO's phase offset angle.
Parameters
tx transmitter or receiver selection
index PHO index from 0 to 15
angle_deg phase offset angle in degrees
Returns
0-success, other-failure
Definition at line 1749 of file LMS7002M.cpp.
References pho, lime::ReportError(), and SPI_write().
Referenced by LoadConfigLegacyFile(), and lime::LMS7_Device::SetNCOPhase().
int LMS7002M::SetNCOPhaseOffsetForMode0 (bool tx, float_type angle_deg)
Sets chosen NCO phase offset angle when memory table MODE is 0.
Parameters
tx transmitter or receiver selection
angle_deg phase offset angle in degrees
Returns
0-success, other-failure
Definition at line 1735 of file LMS7002M.cpp.
References pho, and SPI_write().
Referenced by LMS_SetNCOFrequency().
int LMS7002M::SetPathRFE (PathRFE path)
Set the RFE input path.
Definition at line 969 of file LMS7002M.cpp.
References EN_INSHSW_L_RFE, EN_INSHSW_LB1_RFE, EN_INSHSW_LB2_RFE, EN_INSHSW_W_RFE, EN_LOOPB_TXPAD_TRF, LMS7param, Modify_SPI_Reg_bits(), PATH_RFE_LB1, PATH_RFE_LB2, PATH_RFE_LNAH, PATH_RFE_LNAL, PATH_RFE_LNAW, PD_LNA_RFE, PD_RLOOPB_1_RFE, PD_RLOOPB_2_RFE, and SEL_PATH_RFE.
Referenced by lime::LMS7_Device::SetPath().
int LMS7002M::SetRBBPGA_dB (const float_type gain)
Set the RX PGA gain in dB
Parameters
gain in dB range -12.0, 19.0 dB
Returns
0 for success, else error
Definition at line 734 of file LMS7002M.cpp.
References C_CTL_PGA_RBB, G_PGA_RBB, int(), LMS7param, Modify_SPI_Reg_bits(), and RCC_CTL_PGA_RBB.
Referenced by lime::LMS7_Device::SetGain().
int LMS7002M::SetReferenceClk_SX (bool tx, float_type freq_Hz)
Definition at line 1030 of file LMS7002M.cpp.
References _cachedRefClockRate.
Referenced by LoadConfig(), LoadConfigLegacyFile(), and lime::LMS7_Device::SetClockFreq().
int LMS7002M::SetRFELNA_dB (const float_type gain)
Set the RX LNA gain in dB
Parameters
gain in dB range 0.0, 30.0 dB
Returns
0 for success, else error
Definition at line 760 of file LMS7002M.cpp.
References G_LNA_RFE, LMS7param, Modify_SPI_Reg_bits(), and val.
Referenced by lime::LMS7_Device::SetGain().
int LMS7002M::SetRFELoopbackLNA_dB (const float_type gain)
Set the RX loopback LNA gain in dB
Parameters
gain in dB range 0.0, 40.0 dB
Returns
0 for success, else error
Definition at line 810 of file LMS7002M.cpp.
References G_RXLOOPB_RFE, LMS7param, Modify_SPI_Reg_bits(), and val.
Referenced by lime::LMS7_Device::SetGain().
int LMS7002M::SetRFETIA_dB (const float_type gain)
Set the RX TIA gain in dB
Parameters
gain in dB range 0.0, 12.0 dB
Returns
0 for success, else error
Definition at line 861 of file LMS7002M.cpp.
References G_TIA_RFE, LMS7param, Modify_SPI_Reg_bits(), and val.
Referenced by lime::LMS7_Device::SetGain().
void LMS7002M::SetRxDCOFF (int8_t offsetI, int8_t offsetQ) protected
Sets Rx Dc offsets by converting two's complementary numbers to sign and magnitude.
Definition at line 2201 of file LMS7002M.cpp.
References SPI_write().
int LMS7002M::SetRxDCRemoval (const bool enable)
Set enable for the RX DC removal filter.
Parameters
enable true to enable DC removal
Returns
0 for success for error condition
Definition at line 2570 of file LMS7002M.cpp.
References DC_BYP_RXTSP, DCCORR_AVG_RXTSP, LMS7param, and Modify_SPI_Reg_bits().
int LMS7002M::SetTBBIAMP_dB (const float_type gain)
Set the TBB frontend gain in dB
Parameters
gain in dB relative to optimal gain (0 - optimal gain, >0 may cause saturation)
Returns
0 for success, else error
Definition at line 937 of file LMS7002M.cpp.
References CalibrateTxGain(), CG_IAMP_TBB, GetActiveChannelIndex(), ind, LMS7param, Modify_SPI_Reg_bits(), and opt_gain_tbb.
Referenced by lime::LMS7_Device::SetGain(), and lime::LMS7_Device::SetLPF().
int LMS7002M::SetTRFLoopbackPAD_dB (const float_type gain)
Set the TX loopback PAD gain in dB
Parameters
gain in dB range -4.3, 0.0 dB
Returns
0 for success, else error
Definition at line 913 of file LMS7002M.cpp.
References L_LOOPB_TXPAD_TRF, LMS7param, Modify_SPI_Reg_bits(), and val.
Referenced by lime::LMS7_Device::SetGain().
int LMS7002M::SetTRFPAD_dB (const float_type gain)
Set the TX PAD gain in dB
Parameters
gain in dB range -52.0, 0.0 dB
Returns
0 for success, else error
Definition at line 887 of file LMS7002M.cpp.
References LMS7param, LOSS_LIN_TXPAD_TRF, LOSS_MAIN_TXPAD_TRF, and Modify_SPI_Reg_bits().
Referenced by lime::LMS7_Device::SetGain().
int LMS7002M::SetTxDCOffset (const float_type I, const float_type Q)
Set the TX DC offset adjustment.
Parameters
I the real adjustment [+1.0, -1.0]
Q the imaginary adjustment [+1.0, -1.0]
Returns
0 for success for error condition
Definition at line 2590 of file LMS7002M.cpp.
References DC_BYP_TXTSP, DCCORRI_TXTSP, DCCORRQ_TXTSP, LMS7param, and Modify_SPI_Reg_bits().
int LMS7002M::SoftReset ()
Perform soft-reset sequence over SPI
Definition at line 382 of file LMS7002M.cpp.
References SPI_read(), and SPI_write().
uint16_t LMS7002M::SPI_read (uint16_t address, bool fromChip = false, int * status = 0)
Reads whole register value from given address.
Parameters
address SPI address
status operation status(optional)
fromChip read value directly from chip
Returns
register value
Definition at line 1890 of file LMS7002M.cpp.
References controlPort, GetMCUControls(), lime::LMS7002M_RegistersMap::GetValue(), i, LMS7param, MAC, MCU_FUNCTION_GET_PROGRAM_ID, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, mcu_program_lms7_dc_iq_calibration_bin, mRegistersMap, lime::MCU_BD::Program_MCU(), lime::ReportError(), lime::MCU_BD::RunProcedure(), SPI_read_batch(), SPI_write(), useCache, and lime::MCU_BD::WaitForMCU().
Referenced by lime::Streamer::AlignRxRF(), lime::LMS7_Device::Calibrate(), CalibrateTxGainSetup(), Get_SPI_Reg_bits(), GetNCOFrequency(), GetNCOPhaseOffset_Deg(), GetTemperature(), LimeSDRTest::LMS7002mTest(), Modify_SPI_Reg_bits(), Modify_SPI_Reg_mask(), ReadAnalogDC(), SoftReset(), SPI_write(), TuneRxFilter(), and TuneTxFilter().
int LMS7002M::SPI_read_batch (const uint16_t * spiAddr, uint16_t * spiData, uint16_t cnt) protected
Batches multiple register reads into least amount of transactions.
Parameters
spiAddr SPI addresses to read
spiData array for read data
cnt number of registers to read
Returns
0-success, other-failure
Definition at line 1987 of file LMS7002M.cpp.
References address, controlPort, lime::error(), lime::LMS7002M_RegistersMap::GetValue(), i, LMS7param, MAC, mdevIndex, mRegistersMap, lime::IConnection::ReadLMS7002MSPI(), lime::LMS7002M_RegistersMap::SetValue(), and status.
Referenced by DownloadAll(), GetGFIRCoefficients(), RegistersTest(), RegistersTestInterval(), and SPI_read().
int LMS7002M::SPI_write (uint16_t address, uint16_t data, bool toChip = false)
Write given data value to whole register.
Parameters
address SPI address
data new register value
Returns
0-succes, other-failure
Definition at line 1866 of file LMS7002M.cpp.
References GetMCUControls(), MCU_FUNCTION_GET_PROGRAM_ID, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, mcu_program_lms7_dc_iq_calibration_bin, lime::MCU_BD::Program_MCU(), lime::MCU_BD::RunProcedure(), SPI_read(), SPI_write_batch(), and lime::MCU_BD::WaitForMCU().
Referenced by lime::Streamer::AlignQuadrature(), lime::Streamer::AlignRxRF(), lime::LMS7_Device::Calibrate(), CalibrateAnalogRSSI_DC_Offset(), CalibrateTxGainSetup(), lime::LMS7_LimeSDR_mini::Init(), lime::LMS7_Device::Init(), LimeSDRTest::LMS7002mTest(), LoadConfig(), LoadConfigLegacyFile(), main(), Modify_SPI_Reg_bits(), ReadAnalogDC(), SetNCOFrequency(), SetNCOPhaseOffset(), SetNCOPhaseOffsetForMode0(), SetRxDCOFF(), SoftReset(), SPI_read(), UploadAll(), and WriteAnalogDC().
int LMS7002M::SPI_write_batch (const uint16_t * spiAddr, const uint16_t * spiData, uint16_t cnt, bool toChip = false) protected
Batches multiple register writes into least amount of transactions.
Parameters
spiAddr spi register addresses to be written
spiData registers data to be written
cnt number of registers to write
toChip force write to chip
Returns
0-success, other-failure
Definition at line 1941 of file LMS7002M.cpp.
References address, controlPort, lime::error(), lime::LMS7002M_RegistersMap::GetValue(), i, LMS7param, MAC, mdevIndex, mRegistersMap, lime::LMS7002M_RegistersMap::SetValue(), useCache, and lime::IConnection::WriteLMS7002MSPI().
Referenced by LoadConfig(), LoadConfigLegacyFile(), Modify_SPI_Reg_mask(), RegistersTest(), RegistersTestInterval(), RestoreRegisterMap(), SetDefaults(), SetGFIRCoefficients(), SPI_write(), and UploadAll().
int LMS7002M::TuneCGENVCO ()
Performs VCO tuning operations for CLKGEN.
Returns
0-success, other-failure
Definition at line 1173 of file LMS7002M.cpp.
References LMS7Parameter::address, lime::debug(), lime::error(), Get_SPI_Reg_bits(), ICT_VCO_CGEN, LMS7_CSW_VCO_CGEN, LMS7_PD_VCO_CGEN, LMS7_VCO_CMPHO_CGEN, LMS7param, Modify_SPI_Reg_bits(), and status.
Referenced by TuneVCO().
int LMS7002M::TuneRxFilter (const float_type rx_lpf_freq_RF)
Definition at line 77 of file LMS7002M_filtersCalibration.cpp.
References lime::debug(), lime::error(), G_TIA_RFE, Get_SPI_Reg_bits(), GetReferenceClk_SX(), LMS7param, Log(), LOG_WARNING, lime::MCU_BD::MCU_BW, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, lime::MCU_BD::MCU_NO_ERROR, mcu_program_lms7_dc_iq_calibration_bin, lime::MCU_BD::MCU_REF_CLK, mcuControl, lime::MCU_BD::MCUStatusMessage(), lime::MCU_BD::Program_MCU(), lime::MCU_BD::ReadMCUProgramID(), lime::ReportError(), lime::MCU_BD::RunProcedure(), RxLPF_RF_LimitHigh, RxLPF_RF_LimitLow, lime::MCU_BD::SetParameter(), SPI_read(), status, and lime::MCU_BD::WaitForMCU().
Referenced by SetFrequencySXWithSpurCancelation(), and lime::LMS7_Device::SetLPF().
int lime::LMS7002M::TuneRxFilterSetup (const float_type rx_lpf_IF) protected
int lime::LMS7002M::TuneRxFilterWithCaching (const float_type rx_lpf_freq_RF)
int LMS7002M::TuneTxFilter (const float_type bandwidth)
Definition at line 118 of file LMS7002M_filtersCalibration.cpp.
References controlPort, lime::debug(), lime::error(), GetActiveChannelIndex(), GetReferenceClk_SX(), ind, Log(), LOG_INFO, LOG_WARNING, lime::MCU_BD::MCU_BW, MCU_ID_CALIBRATIONS_SINGLE_IMAGE, lime::MCU_BD::MCU_NO_ERROR, mcu_program_lms7_dc_iq_calibration_bin, lime::MCU_BD::MCU_REF_CLK, mcuControl, lime::MCU_BD::MCUStatusMessage(), opt_gain_tbb, lime::MCU_BD::Program_MCU(), lime::MCU_BD::ReadMCUProgramID(), lime::ReportError(), lime::MCU_BD::RunProcedure(), lime::MCU_BD::SetParameter(), SPI_read(), status, TxLPF_RF_LimitHigh, TxLPF_RF_LimitLow, TxLPF_RF_LimitLowMid, TxLPF_RF_LimitMidHigh, and lime::MCU_BD::WaitForMCU().
Referenced by lime::LMS7_Device::ConfigureTXLPF(), and lime::LMS7_Device::SetLPF().
int lime::LMS7002M::TuneTxFilterSetup (const float_type tx_lpf_IF) protected
int lime::LMS7002M::TuneTxFilterWithCaching (const float_type bandwidth)
int LMS7002M::TuneVCO (VCO_Module module)
Performs VCO tuning operations for CLKGEN, SXR, SXT modules.
Parameters
module module selection for tuning 0-cgen, 1-SXR, 2-SXT
Returns
0-success, other-failure
Definition at line 1221 of file LMS7002M.cpp.
References CSW_VCO, CSW_VCO_CGEN, lime::debug(), Get_SPI_Reg_bits(), GetActiveChannel(), i, ICT_VCO, ICT_VCO_CGEN, LMS7param, Modify_SPI_Reg_bits(), PD_VCO, PD_VCO_CGEN, lime::ReportError(), SetActiveChannel(), status, TuneCGENVCO(), VCO_CGEN, VCO_CMPHO, VCO_CMPHO_CGEN, and VCO_SXR.
Referenced by lms7002_pnlCLKGEN_view::onbtnTuneClick(), lime::LMS7_Device::SetClockFreq(), SetFrequencyCGEN(), and SetFrequencySX().
void lime::LMS7002M::TxDcBinarySearch (BinSearchParam * args) protected
int lime::LMS7002M::TxFilterSearch (const LMS7Parameter & param, const uint32_t rssi_3dB, uint8_t rssiAvgCnt, const int stepLimit) protected
int lime::LMS7002M::TxFilterSearch_S5 (const LMS7Parameter & param, const uint32_t rssi_3dB, uint8_t rssiAvgCnt, const int stepLimit) protected
int LMS7002M::UploadAll ()
Writes all registers from host to chip.
Definition at line 2330 of file LMS7002M.cpp.
References address, ChA, ChB, controlPort, lime::error(), GetActiveChannel(), lime::LMS7002M_RegistersMap::GetUsedAddresses(), lime::LMS7002M_RegistersMap::GetValue(), mRegistersMap, SetActiveChannel(), SPI_write(), SPI_write_batch(), and status.
Referenced by CopyChannelRegisters(), main(), lime::LMS7_Device::Synchronize(), and TEST_F().
Member Data Documentation
double lime::LMS7002M::_cachedRefClockRate protected
Definition at line 499 of file LMS7002M.h.
Referenced by GetReferenceClk_SX(), and SetReferenceClk_SX().
IConnection* lime::LMS7002M::controlPort protected
port used for communicating with LMS7002M
Definition at line 495 of file LMS7002M.h.
Referenced by CalibrateTxGain(), CopyChannelRegisters(), DownloadAll(), GetGFIRCoefficients(), IsSynced(), LoadConfig(), LoadConfigLegacyFile(), RegistersTest(), ResetChip(), SPI_read(), SPI_read_batch(), SPI_write_batch(), TuneTxFilter(), and UploadAll().
float_type LMS7002M::gCGEN_VCO_frequencies = {1930e6, 2940e6} static
Definition at line 412 of file LMS7002M.h.
Referenced by lms7002_dlgVCOfrequencies::lms7002_dlgVCOfrequencies(), lms7002_dlgVCOfrequencies::OnBtnOkClick(), and SetFrequencyCGEN().
float_type LMS7002M::gVCO_frequency_table = { { 3800e6, 5222e6 }, { 4961e6, 6754e6 }, {6306e6, 7714e6} } static
Definition at line 411 of file LMS7002M.h.
Referenced by lms7002_dlgVCOfrequencies::lms7002_dlgVCOfrequencies(), lms7002_dlgVCOfrequencies::OnBtnOkClick(), and SetFrequencySX().
std::function<void(const char*, int)> lime::LMS7002M::log_callback protected
Definition at line 491 of file LMS7002M.h.
Referenced by SetLogCallback().
bool lime::LMS7002M::mCalibrationByMCU protected
Definition at line 432 of file LMS7002M.h.
Referenced by EnableCalibrationByMCU(), and LMS7002M().
MCU_BD* lime::LMS7002M::mcuControl protected
Definition at line 433 of file LMS7002M.h.
Referenced by GetMCUControls(), LMS7002M(), TuneRxFilter(), TuneTxFilter(), and ~LMS7002M().
unsigned lime::LMS7002M::mdevIndex protected
Definition at line 496 of file LMS7002M.h.
Referenced by GetActiveChannelIndex(), IsSynced(), ResetChip(), SPI_read_batch(), and SPI_write_batch().
uint16_t lime::LMS7002M::MemorySectionAddresses[MEMORY_SECTIONS_COUNT][2] protected
Definition at line 441 of file LMS7002M.h.
Referenced by CopyChannelRegisters(), LMS7002M(), RegistersTest(), SaveConfig(), and SetDefaults().
LMS7002M_RegistersMap* lime::LMS7002M::mRegistersMap protected
Definition at line 435 of file LMS7002M.h.
Referenced by BackupRegisterMap(), CopyChannelRegisters(), DownloadAll(), GetGFIRCoefficients(), IsSynced(), LMS7002M(), ResetChip(), RestoreRegisterMap(), SetDefaults(), SPI_read(), SPI_read_batch(), SPI_write_batch(), UploadAll(), and ~LMS7002M().
size_t lime::LMS7002M::mSelfCalDepth protected
Definition at line 497 of file LMS7002M.h.
int lime::LMS7002M::opt_gain_tbb[2] protected
Definition at line 498 of file LMS7002M.h.
Referenced by CalibrateTxGain(), GetTBBIAMP_dB(), LMS7002M(), SetTBBIAMP_dB(), and TuneTxFilter().
const uint16_t LMS7002M::readOnlyRegisters = { 0x002F, 0x008C, 0x00A8, 0x00A9, 0x00AA, 0x00AB, 0x00AC, 0x0123, 0x0209, 0x020A, 0x020B, 0x040E, 0x040F } static protected
Definition at line 437 of file LMS7002M.h.
Referenced by IsSynced(), and RegistersTestInterval().
const uint16_t LMS7002M::readOnlyRegistersMasks = { 0x0000, 0x0FFF, 0x007F, 0x0000, 0x0000, 0x0000, 0x0000, 0x003F, 0x0000, 0x0000, 0x0000, 0x0000, 0x0000 } static protected
Definition at line 438 of file LMS7002M.h.
Referenced by IsSynced(), and RegistersTestInterval().
bool lime::LMS7002M::useCache protected
Definition at line 434 of file LMS7002M.h.
Referenced by EnableValuesCache(), IsValuesCacheEnabled(), SetFrequencySX(), SPI_read(), and SPI_write_batch().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M.cpp
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_BaseCalibrations.cpp
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_filtersCalibration.cpp
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_gainCalibrations.cpp
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_RxTxCalibrations.cpp