LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/GFIR/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/GFIR/CMakeLists.txt File Reference
Functions
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}) set(lms_gfir_src_files $
Function Documentation
set (THIS_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR})
Definition at line 2 of file CMakeLists.txt.
References gfir_lms(), include_directories(), lms(), and target_sources().