LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/ExampleDriver/MyDeviceSupport.cpp File Reference
MyDeviceSupport.cpp File Reference
#include <SoapySDR/Device.hpp>
#include <SoapySDR/Registry.hpp>
Classes
class MyDevice
Functions
SoapySDR::KwargsList findMyDevice (const SoapySDR::Kwargs &args)
SoapySDR::Device * makeMyDevice (const SoapySDR::Kwargs &args)
Variables
static SoapySDR::Registry registerMyDevice ("my_device",&findMyDevice,&makeMyDevice, SOAPY_SDR_ABI_VERSION)
Function Documentation
SoapySDR::KwargsList findMyDevice (const SoapySDR::Kwargs & args)
Definition at line 17 of file MyDeviceSupport.cpp.
Referenced by makeMyDevice().
SoapySDR::Device* makeMyDevice (const SoapySDR::Kwargs & args)
Definition at line 26 of file MyDeviceSupport.cpp.
References findMyDevice(), registerMyDevice, and SOAPY_SDR_ABI_VERSION.
Variable Documentation
SoapySDR::Registry registerMyDevice("my_device",&findMyDevice,&makeMyDevice, SOAPY_SDR_ABI_VERSION) static
Referenced by makeMyDevice().