LimeSuite-UML: dlgConnectionSettings_view Class Reference
dlgConnectionSettings_view Class Reference
Class dlgConnectionSettings_view.
#include <utilities_gui.h>
Public Member Functions
dlgConnectionSettings_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("Connection Settings"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)
~dlgConnectionSettings_view ()
Protected Member Functions
virtual void GetDeviceList (wxInitDialogEvent &event)
virtual void OnConnect (wxCommandEvent &event)
virtual void OnCancel (wxCommandEvent &event)
virtual void OnDisconnect (wxCommandEvent &event)
Protected Attributes
wxStaticText * m_staticText472
wxListBox * mListLMS7ports
wxButton * btnConnect
wxButton * btnCancel
wxButton * btnDisconnect
Detailed Description
Class dlgConnectionSettings_view.
Definition at line 35 of file utilities_gui.h.
Constructor & Destructor Documentation
dlgConnectionSettings_view::dlgConnectionSettings_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxT("Connection Settings"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)
Definition at line 12 of file utilities_gui.cpp.
References btnCancel, btnConnect, btnDisconnect, GetDeviceList(), m_staticText472, mListLMS7ports, OnCancel(), OnConnect(), and OnDisconnect().
Referenced by OnDisconnect().
dlgConnectionSettings_view::~dlgConnectionSettings_view ()
Definition at line 76 of file utilities_gui.cpp.
References btnCancel, btnConnect, btnDisconnect, GetDeviceList(), OnCancel(), OnConnect(), and OnDisconnect().
Referenced by OnDisconnect().
Member Function Documentation
virtual void dlgConnectionSettings_view::GetDeviceList (wxInitDialogEvent & event) inline protected virtual
Reimplemented in dlgConnectionSettings.
Definition at line 47 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
virtual void dlgConnectionSettings_view::OnCancel (wxCommandEvent & event) inline protected virtual
Reimplemented in dlgConnectionSettings.
Definition at line 49 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
virtual void dlgConnectionSettings_view::OnConnect (wxCommandEvent & event) inline protected virtual
Reimplemented in dlgConnectionSettings.
Definition at line 48 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
virtual void dlgConnectionSettings_view::OnDisconnect (wxCommandEvent & event) inline protected virtual
Reimplemented in dlgConnectionSettings.
Definition at line 50 of file utilities_gui.h.
References dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
Referenced by dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
Member Data Documentation
wxButton* dlgConnectionSettings_view::btnCancel protected
Definition at line 43 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
wxButton* dlgConnectionSettings_view::btnConnect protected
Definition at line 42 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
wxButton* dlgConnectionSettings_view::btnDisconnect protected
Definition at line 44 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view(), and ~dlgConnectionSettings_view().
wxStaticText* dlgConnectionSettings_view::m_staticText472 protected
Definition at line 40 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view().
wxListBox* dlgConnectionSettings_view::mListLMS7ports protected
Definition at line 41 of file utilities_gui.h.
Referenced by dlgConnectionSettings_view(), dlgConnectionSettings::GetDeviceList(), dlgConnectionSettings::OnConnect(), and dlgConnectionSettings::OnDisconnect().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/utilities_gui.h
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/utilities_gui.cpp