LimeSuite-UML: pnlMCU_BD_view Class Reference
pnlMCU_BD_view Class Reference
Class pnlMCU_BD_view.
#include <lms7002_wxgui.h>
Public Member Functions
pnlMCU_BD_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxTAB_TRAVERSAL)
~pnlMCU_BD_view ()
Protected Types
enum {
ID_CHECKBOX_RESETMCU = 2048, ID_TESTNO, ID_DEBUGMODE, ID_RUNINSTR,
ID_INSTRNO, ID_RESETPC, ID_SELDIV, ID_RADIOBUTTON4,
ID_RADIOBUTTON5
}
Protected Member Functions
virtual void OnButton_LOADHexClick (wxCommandEvent &event)
virtual void OnchkResetClick (wxCommandEvent &event)
virtual void OnbtnStartProgrammingClick (wxCommandEvent &event)
virtual void OnbtnRunTestClick (wxCommandEvent &event)
virtual void OnbtnRunProductionTestClicked (wxCommandEvent &event)
virtual void OnDebugModeClick (wxCommandEvent &event)
virtual void OnRunInstruction (wxCommandEvent &event)
virtual void OnResetPCClick (wxCommandEvent &event)
virtual void OnViewSFRsClick (wxCommandEvent &event)
virtual void OnViewIRAMClick (wxCommandEvent &event)
virtual void OnEraseIRAMClick (wxCommandEvent &event)
virtual void OnSelDivSelect (wxCommandEvent &event)
virtual void Onm_cCtrlBasebandSelect (wxCommandEvent &event)
virtual void Onm_cCtrlMCU_BDSelect (wxCommandEvent &event)
virtual void OnRegWriteRead (wxCommandEvent &event)
Protected Attributes
wxStaticText * ID_STATICTEXT1
wxButton * Button_LOADHEX
wxCheckBox * chkReset
wxRadioBox * rgrMode
wxButton * btnStartProgramming
wxStaticText * ID_S_PROGFINISHED
wxStaticText * ID_STATICTEXT3
wxButton * btnRunTest
wxStaticText * ID_STATICTEXT4
wxTextCtrl * m_sTestNo
wxButton * btnRunProductionTest
wxCheckBox * DebugMode
wxButton * RunInstr
wxStaticText * ID_STATICTEXT6
wxTextCtrl * InstrNo
wxButton * ResetPC
wxStaticText * ID_STATICTEXT7
wxStaticText * PCValue
wxButton * ViewSFRs
wxButton * ViewIRAM
wxButton * EraseIRAM
wxStaticText * ID_STATICTEXT10
wxChoice * SelDiv
wxRadioButton * m_cCtrlBaseband
wxRadioButton * m_cCtrlMCU_BD
wxStaticText * ID_STATICTEXT5
wxChoice * cmbRegAddr
wxRadioButton * rbtnRegWrite
wxStaticText * ID_STATICTEXT11
wxTextCtrl * txtRegValueWr
wxRadioButton * rbtnRegRead
wxStaticText * ReadResult
wxButton * btnRdWr
wxStaticText * ID_STATICTEXT2
wxGauge * progressBar
wxStaticText * lblProgCodeFile
wxStaticText * lblTestResultsFile
Detailed Description
Class pnlMCU_BD_view.
Definition at line 2024 of file lms7002_wxgui.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
ID_CHECKBOX_RESETMCU
ID_TESTNO
ID_DEBUGMODE
ID_RUNINSTR
ID_INSTRNO
ID_RESETPC
ID_SELDIV
ID_RADIOBUTTON4
ID_RADIOBUTTON5
Definition at line 2029 of file lms7002_wxgui.h.
Constructor & Destructor Documentation
pnlMCU_BD_view::pnlMCU_BD_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxSize(-1,-1), long style = wxTAB_TRAVERSAL)
Definition at line 8876 of file lms7002_wxgui.cpp.
References btnRdWr, btnRunProductionTest, btnRunTest, btnStartProgramming, Button_LOADHEX, chkReset, cmbRegAddr, DebugMode, EraseIRAM, ID_CHECKBOX_RESETMCU, ID_DEBUGMODE, ID_INSTRNO, ID_RADIOBUTTON4, ID_RADIOBUTTON5, ID_RESETPC, ID_RUNINSTR, ID_S_PROGFINISHED, ID_SELDIV, ID_STATICTEXT1, ID_STATICTEXT10, ID_STATICTEXT11, ID_STATICTEXT2, ID_STATICTEXT3, ID_STATICTEXT4, ID_STATICTEXT5, ID_STATICTEXT6, ID_STATICTEXT7, ID_TESTNO, InstrNo, lblProgCodeFile, lblTestResultsFile, m_cCtrlBaseband, m_cCtrlMCU_BD, m_sTestNo, OnbtnRunProductionTestClicked(), OnbtnRunTestClick(), OnbtnStartProgrammingClick(), OnButton_LOADHexClick(), OnchkResetClick(), OnDebugModeClick(), OnEraseIRAMClick(), Onm_cCtrlBasebandSelect(), Onm_cCtrlMCU_BDSelect(), OnRegWriteRead(), OnResetPCClick(), OnRunInstruction(), OnSelDivSelect(), OnViewIRAMClick(), OnViewSFRsClick(), PCValue, progressBar, rbtnRegRead, rbtnRegWrite, ReadResult, ResetPC, rgrMode, RunInstr, SelDiv, txtRegValueWr, ViewIRAM, and ViewSFRs.
pnlMCU_BD_view::~pnlMCU_BD_view ()
Definition at line 9219 of file lms7002_wxgui.cpp.
References btnRdWr, btnRunProductionTest, btnRunTest, btnStartProgramming, Button_LOADHEX, chkReset, DebugMode, EraseIRAM, m_cCtrlBaseband, m_cCtrlMCU_BD, OnbtnRunProductionTestClicked(), OnbtnRunTestClick(), OnbtnStartProgrammingClick(), OnButton_LOADHexClick(), OnchkResetClick(), OnDebugModeClick(), OnEraseIRAMClick(), Onm_cCtrlBasebandSelect(), Onm_cCtrlMCU_BDSelect(), OnRegWriteRead(), OnResetPCClick(), OnRunInstruction(), OnSelDivSelect(), OnViewIRAMClick(), OnViewSFRsClick(), ResetPC, RunInstr, SelDiv, ViewIRAM, and ViewSFRs.
Member Function Documentation
virtual void pnlMCU_BD_view::OnbtnRunProductionTestClicked (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2085 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnbtnRunTestClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2084 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnbtnStartProgrammingClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2083 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnButton_LOADHexClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2081 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnchkResetClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2082 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnDebugModeClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2086 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnEraseIRAMClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2091 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::Onm_cCtrlBasebandSelect (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2093 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::Onm_cCtrlMCU_BDSelect (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2094 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnRegWriteRead (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2095 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnResetPCClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2088 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnRunInstruction (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2087 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnSelDivSelect (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2092 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnViewIRAMClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2090 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
virtual void pnlMCU_BD_view::OnViewSFRsClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_pnlMCU_BD_view.
Definition at line 2089 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
Member Data Documentation
wxButton* pnlMCU_BD_view::btnRdWr protected
Definition at line 2074 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::btnRunProductionTest protected
Definition at line 2052 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::btnRunTest protected
Definition at line 2049 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::btnStartProgramming protected
Definition at line 2046 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnProgrammingfinished(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::Button_LOADHEX protected
Definition at line 2043 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxCheckBox* pnlMCU_BD_view::chkReset protected
Definition at line 2044 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnbtnStartProgrammingClick(), lms7002_pnlMCU_BD_view::OnchkResetClick(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxChoice* pnlMCU_BD_view::cmbRegAddr protected
Definition at line 2068 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnRegWriteRead(), and pnlMCU_BD_view().
wxCheckBox* pnlMCU_BD_view::DebugMode protected
Definition at line 2053 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnbtnStartProgrammingClick(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::EraseIRAM protected
Definition at line 2062 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_S_PROGFINISHED protected
Definition at line 2047 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT1 protected
Definition at line 2042 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT10 protected
Definition at line 2063 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT11 protected
Definition at line 2070 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT2 protected
Definition at line 2075 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT3 protected
Definition at line 2048 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT4 protected
Definition at line 2050 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT5 protected
Definition at line 2067 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT6 protected
Definition at line 2055 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ID_STATICTEXT7 protected
Definition at line 2058 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxTextCtrl* pnlMCU_BD_view::InstrNo protected
Definition at line 2056 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), lms7002_pnlMCU_BD_view::OnRunInstruction(), and pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::lblProgCodeFile protected
Definition at line 2077 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnButton_LOADHexClick(), and pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::lblTestResultsFile protected
Definition at line 2078 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnbtnLoadTestFileClick(), lms7002_pnlMCU_BD_view::OnbtnRunTestClick(), and pnlMCU_BD_view().
wxRadioButton* pnlMCU_BD_view::m_cCtrlBaseband protected
Definition at line 2065 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxRadioButton* pnlMCU_BD_view::m_cCtrlMCU_BD protected
Definition at line 2066 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxTextCtrl* pnlMCU_BD_view::m_sTestNo protected
Definition at line 2051 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnbtnRunTestClick(), and pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::PCValue protected
Definition at line 2059 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnRunInstruction(), and pnlMCU_BD_view().
wxGauge* pnlMCU_BD_view::progressBar protected
Definition at line 2076 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnbtnStartProgrammingClick(), lms7002_pnlMCU_BD_view::OnEraseIRAMClick(), lms7002_pnlMCU_BD_view::OnEraseIRAMfinished(), lms7002_pnlMCU_BD_view::OnProgramingStatusUpdate(), lms7002_pnlMCU_BD_view::OnProgrammingfinished(), lms7002_pnlMCU_BD_view::OnReadIRAMfinished(), lms7002_pnlMCU_BD_view::OnReadSFRfinished(), lms7002_pnlMCU_BD_view::OnViewIRAMClick(), lms7002_pnlMCU_BD_view::OnViewSFRsClick(), and pnlMCU_BD_view().
wxRadioButton* pnlMCU_BD_view::rbtnRegRead protected
Definition at line 2072 of file lms7002_wxgui.h.
Referenced by pnlMCU_BD_view().
wxRadioButton* pnlMCU_BD_view::rbtnRegWrite protected
Definition at line 2069 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnRegWriteRead(), and pnlMCU_BD_view().
wxStaticText* pnlMCU_BD_view::ReadResult protected
Definition at line 2073 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnRegWriteRead(), and pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::ResetPC protected
Definition at line 2057 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxRadioBox* pnlMCU_BD_view::rgrMode protected
Definition at line 2045 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnbtnStartProgrammingClick(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnProgrammingfinished(), and pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::RunInstr protected
Definition at line 2054 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxChoice* pnlMCU_BD_view::SelDiv protected
Definition at line 2064 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), lms7002_pnlMCU_BD_view::OnSelDivSelect(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxTextCtrl* pnlMCU_BD_view::txtRegValueWr protected
Definition at line 2071 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::OnRegWriteRead(), and pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::ViewIRAM protected
Definition at line 2061 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
wxButton* pnlMCU_BD_view::ViewSFRs protected
Definition at line 2060 of file lms7002_wxgui.h.
Referenced by lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view(), lms7002_pnlMCU_BD_view::OnchkResetClick(), lms7002_pnlMCU_BD_view::OnDebugModeClick(), pnlMCU_BD_view(), and ~pnlMCU_BD_view().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_wxgui.cpp