LimeSuite-UML: swig::traits< Type * > Struct Template Reference
swig::traits< Type * > Struct Template Reference
Public Types
typedef pointer_category category
typedef pointer_category category
Static Public Member Functions
static std::string make_ptr_name (const char *name)
static const char * type_name ()
static std::string make_ptr_name (const char *name)
static const char * type_name ()
Detailed Description
template<class Type>
struct swig::traits< Type * >
Definition at line 3712 of file SoapySDRPYTHON_wrap.cxx.
Member Typedef Documentation
template<class Type > typedef pointer_category swig::traits< Type * >::category
Definition at line 3351 of file radar_swigPYTHON_wrap.cxx.
template<class Type > typedef pointer_category swig::traits< Type * >::category
Definition at line 3713 of file SoapySDRPYTHON_wrap.cxx.
Member Function Documentation
template<class Type > static std::string swig::traits< Type * >::make_ptr_name (const char * name) inline static
Definition at line 3352 of file radar_swigPYTHON_wrap.cxx.
References string().
template<class Type > static std::string swig::traits< Type * >::make_ptr_name (const char * name) inline static
Definition at line 3714 of file SoapySDRPYTHON_wrap.cxx.
References string().
template<class Type > static const char* swig::traits< Type * >::type_name () inline static
Definition at line 3357 of file radar_swigPYTHON_wrap.cxx.
References string().
template<class Type > static const char* swig::traits< Type * >::type_name () inline static
Definition at line 3719 of file SoapySDRPYTHON_wrap.cxx.
References string().
The documentation for this struct was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDRPYTHON_wrap.cxx
/home/erik/prefix/default/src/gr-radar-dev/build/swig/radar_swigPYTHON_wrap.cxx