LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionRegistry/ConnectionHandle.h File Reference
ConnectionHandle.h File Reference
Represent a connection to a device.
#include "LimeSuiteConfig.h"
#include <string>
Classes
class lime::ConnectionHandle
Namespaces
lime
GUI for writing and reading analog controls.
Functions
bool operator== (const lime::ConnectionHandle &lhs, const lime::ConnectionHandle &rhs)
Check two connection handles for equality.
Detailed Description
Represent a connection to a device.
Author
Lime Microsystems
Definition in file ConnectionHandle.h.
Function Documentation
bool operator== (const lime::ConnectionHandle & lhs, const lime::ConnectionHandle & rhs)
Check two connection handles for equality.
Definition at line 112 of file ConnectionHandle.cpp.
References lime::ConnectionHandle::serialize().
Referenced by swig::SwigPyIterator::operator!=(), and swig::SwigPySequence_InputIterator< T, Reference >::operator!=().