LimeSuite-UML: SoapySDR::ConverterRegistry Class Reference
SoapySDR::ConverterRegistry Class Reference
#include <ConverterRegistry.hpp>
Public Types
enum FunctionPriority { GENERIC = 0, VECTORIZED = 3, CUSTOM = 5 }
typedef void(* ConverterFunction) (const void *, void *, const size_t, const double)
typedef std::map< FunctionPriority, ConverterFunction > TargetFormatConverterPriority
typedef std::map< std::string, TargetFormatConverterPriority > TargetFormatConverters
typedef std::map< std::string, TargetFormatConverters > FormatConverters
Public Member Functions
ConverterRegistry (const std::string &sourceFormat, const std::string &targetFormat, const FunctionPriority &priority, ConverterFunction converter)
Static Public Member Functions
static std::vector< std::string > listTargetFormats (const std::string &sourceFormat)
static std::vector< std::string > listSourceFormats (const std::string &targetFormat)
static std::vector< FunctionPriority > listPriorities (const std::string &sourceFormat, const std::string &targetFormat)
static ConverterFunction getFunction (const std::string &sourceFormat, const std::string &targetFormat)
static ConverterFunction getFunction (const std::string &sourceFormat, const std::string &targetFormat, const FunctionPriority &priority)
static std::vector< std::string > listAvailableSourceFormats (void)
Detailed Description
Definition at line 23 of file ConverterRegistry.hpp.
Member Typedef Documentation
typedef void(* SoapySDR::ConverterRegistry::ConverterFunction) (const void *, void *, const size_t, const double)
A typedef for a conversion function pointer. A conversion function converts an input buffer into an output buffer. The parameters are (input pointer, output pointer, number of elements, optional scalar)
Definition at line 31 of file ConverterRegistry.hpp.
typedef std::map<std::string, TargetFormatConverters> SoapySDR::ConverterRegistry::FormatConverters
FormatConverters: a map of possible conversion functions for a given Source/Target Format.
Definition at line 55 of file ConverterRegistry.hpp.
typedef std::map<FunctionPriority, ConverterFunction> SoapySDR::ConverterRegistry::TargetFormatConverterPriority
TargetFormatConverterPriority: a map of possible conversion functions for a given Priority.
Definition at line 45 of file ConverterRegistry.hpp.
typedef std::map<std::string, TargetFormatConverterPriority> SoapySDR::ConverterRegistry::TargetFormatConverters
TargetFormatConverters: a map of possible conversion functions for a given Target/Priority Format.
Definition at line 50 of file ConverterRegistry.hpp.
Member Enumeration Documentation
enum SoapySDR::ConverterRegistry::FunctionPriority
FormatConverterPriority: allow selection of a converter function with a given source and target format
Enumerator
GENERIC
VECTORIZED
CUSTOM
Definition at line 36 of file ConverterRegistry.hpp.
Constructor & Destructor Documentation
SoapySDR::ConverterRegistry::ConverterRegistry (const std::string & sourceFormat, const std::string & targetFormat, const FunctionPriority & priority, ConverterFunction converter)
Class constructor for managing the Converter Registry. refuses to register converter and logs error if a source/target/priority entry already exists
Parameters
sourceFormat the source format markup string
targetFormat the target format markup string
priority the FunctionPriority of the converter to register
converter function to register
Definition at line 10 of file ConverterRegistry.cpp.
References formatConverters, SoapySDR::logf(), and SoapySDR::SOAPY_SDR_ERROR.
Member Function Documentation
SoapySDR::ConverterRegistry::ConverterFunction SoapySDR::ConverterRegistry::getFunction (const std::string & sourceFormat, const std::string & targetFormat) static
Get a converter between a source and target format.
Exceptions
invalid_argument when the conversion does not exist and logs error
Parameters
sourceFormat the source format markup string
targetFormat the target format markup string
Returns
a conversion function pointer
Definition at line 82 of file ConverterRegistry.cpp.
References formatConverters.
SoapySDR::ConverterRegistry::ConverterFunction SoapySDR::ConverterRegistry::getFunction (const std::string & sourceFormat, const std::string & targetFormat, const FunctionPriority & priority) static
Definition at line 105 of file ConverterRegistry.cpp.
References formatConverters.
std::vector< std::string > SoapySDR::ConverterRegistry::listAvailableSourceFormats (void) static
Get a list of known source formats in the registry.
Definition at line 128 of file ConverterRegistry.cpp.
References formatConverters.
Referenced by printInfo().
std::vector< SoapySDR::ConverterRegistry::FunctionPriority > SoapySDR::ConverterRegistry::listPriorities (const std::string & sourceFormat, const std::string & targetFormat) static
Get a list of available converter priorities for a given source and target format.
Parameters
sourceFormat the source format markup string
targetFormat the target format markup string
Returns
a vector of priorities or an empty vector if none found
Definition at line 59 of file ConverterRegistry.cpp.
References formatConverters.
std::vector< std::string > SoapySDR::ConverterRegistry::listSourceFormats (const std::string & targetFormat) static
Get a list of formats to which we can convert the target format from. There is a registered conversion function from every source format returned in the result vector to the specified target format.
Parameters
targetFormat the target format markup string
Returns
a vector of source formats or an empty vector if none found
Definition at line 44 of file ConverterRegistry.cpp.
References formatConverters, and string().
std::vector< std::string > SoapySDR::ConverterRegistry::listTargetFormats (const std::string & sourceFormat) static
Get a list of formats to which we can convert the source format into. There is a registered conversion function from the specified source format to every target format returned in the result vector.
Parameters
sourceFormat the source format markup string
Returns
a vector of target formats or an empty vector if none found
Definition at line 27 of file ConverterRegistry.cpp.
References formatConverters, and string().
Referenced by printInfo().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/soapysdr/include/SoapySDR/ConverterRegistry.hpp
/home/erik/prefix/default/src/soapysdr/lib/ConverterRegistry.cpp