LimeSuite-UML: HPM7_wxgui Class Reference
HPM7_wxgui Class Reference
#include <HPM7_wxgui.h>
Public Member Functions
HPM7_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long styles=0)
virtual void Initialize (lms_device_t *serPort)
virtual ~HPM7_wxgui ()
void SelectBand (unsigned int i)
void SelectRxPath (unsigned int i)
bool UploadGPIO ()
Protected Attributes
wxComboBox * cmbActivePath
wxComboBox * cmbBand
wxComboBox * cmbLNA
wxComboBox * cmbPAdriver
std::vector< long > tunerIds
std::vector< wxCheckBox * > chkEB
std::vector< wxCheckBox * > chkTP
std::vector< wxComboBox * > cmbSSC1
std::vector< wxComboBox * > cmbSSC2
wxButton * btnUpdateAll
wxComboBox * cmbDAC_A
wxComboBox * cmbDAC_B
lime::LMS64CProtocol * m_serPort
Private Member Functions
void DownloadAll (wxCommandEvent &event)
void OnGPIOchange (wxCommandEvent &event)
void OnTunerSSC1change (wxCommandEvent &event)
void OnTunerSSC2change (wxCommandEvent &event)
void OnDACchange (wxCommandEvent &event)
Private Attributes
std::vector< long > chEBids
std::vector< long > chTPids
std::vector< long > cmbSSC1ids
std::vector< long > cmbSSC2ids
Detailed Description
Definition at line 22 of file HPM7_wxgui.h.
Constructor & Destructor Documentation
HPM7_wxgui::HPM7_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long styles = 0)
Definition at line 27 of file HPM7_wxgui.cpp.
References _T, DownloadAll(), i, OnDACchange(), OnGPIOchange(), OnTunerSSC1change(), and OnTunerSSC2change().
HPM7_wxgui::~HPM7_wxgui () virtual
Definition at line 159 of file HPM7_wxgui.cpp.
Member Function Documentation
void HPM7_wxgui::DownloadAll (wxCommandEvent & event) private
Definition at line 232 of file HPM7_wxgui.cpp.
References chkEB, chkTP, cmbActivePath, cmbBand, cmbDAC_A, cmbDAC_B, cmbLNA, cmbPAdriver, cmbSSC1, cmbSSC2, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_MYRIAD_RD, i, lime::LMS64CProtocol::GenericPacket::inBuffer, index, lime::IConnection::IsOpen(), m_serPort, lime::LMS64CProtocol::GenericPacket::outBuffer, and lime::LMS64CProtocol::TransferPacket().
Referenced by HPM7_wxgui().
void HPM7_wxgui::Initialize (lms_device_t * serPort) virtual
Definition at line 153 of file HPM7_wxgui.cpp.
References lime::LMS7_Device::GetConnection(), lms(), and m_serPort.
Referenced by LMS7SuiteAppFrame::OnShowHPM7(), and LMS7SuiteAppFrame::UpdateConnections().
void HPM7_wxgui::OnDACchange (wxCommandEvent & event) private
Definition at line 275 of file HPM7_wxgui.cpp.
References cmbDAC_A, cmbDAC_B, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_MYRIAD_WR, lime::IConnection::IsOpen(), m_serPort, lime::LMS64CProtocol::GenericPacket::outBuffer, and lime::LMS64CProtocol::TransferPacket().
Referenced by HPM7_wxgui().
void HPM7_wxgui::OnGPIOchange (wxCommandEvent & event) private
Definition at line 211 of file HPM7_wxgui.cpp.
References cmbActivePath, cmbBand, and UploadGPIO().
Referenced by HPM7_wxgui().
void HPM7_wxgui::OnTunerSSC1change (wxCommandEvent & event) private
Definition at line 164 of file HPM7_wxgui.cpp.
References cmbSSC1, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_MYRIAD_WR, lime::IConnection::IsOpen(), m_serPort, lime::LMS64CProtocol::GenericPacket::outBuffer, and lime::LMS64CProtocol::TransferPacket().
Referenced by HPM7_wxgui().
void HPM7_wxgui::OnTunerSSC2change (wxCommandEvent & event) private
Definition at line 186 of file HPM7_wxgui.cpp.
References chkEB, chkTP, cmbSSC2, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_MYRIAD_WR, lime::IConnection::IsOpen(), m_serPort, lime::LMS64CProtocol::GenericPacket::outBuffer, lime::LMS64CProtocol::TransferPacket(), and tunerIds.
Referenced by HPM7_wxgui().
void HPM7_wxgui::SelectBand (unsigned int i)
Definition at line 298 of file HPM7_wxgui.cpp.
References cmbBand, and UploadGPIO().
void HPM7_wxgui::SelectRxPath (unsigned int i)
Definition at line 305 of file HPM7_wxgui.cpp.
References cmbActivePath, and UploadGPIO().
bool HPM7_wxgui::UploadGPIO ()
Definition at line 312 of file HPM7_wxgui.cpp.
References cmbActivePath, cmbBand, cmbLNA, cmbPAdriver, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_MYRIAD_WR, lime::IConnection::IsOpen(), m_serPort, lime::LMS64CProtocol::GenericPacket::outBuffer, and lime::LMS64CProtocol::TransferPacket().
Referenced by OnGPIOchange(), SelectBand(), and SelectRxPath().
Member Data Documentation
wxButton* HPM7_wxgui::btnUpdateAll protected
Definition at line 42 of file HPM7_wxgui.h.
std::vector<long> HPM7_wxgui::chEBids private
Definition at line 52 of file HPM7_wxgui.h.
std::vector<wxCheckBox*> HPM7_wxgui::chkEB protected
Definition at line 38 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and OnTunerSSC2change().
std::vector<wxCheckBox*> HPM7_wxgui::chkTP protected
Definition at line 39 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and OnTunerSSC2change().
std::vector<long> HPM7_wxgui::chTPids private
Definition at line 53 of file HPM7_wxgui.h.
wxComboBox* HPM7_wxgui::cmbActivePath protected
Definition at line 33 of file HPM7_wxgui.h.
Referenced by DownloadAll(), OnGPIOchange(), SelectRxPath(), and UploadGPIO().
wxComboBox* HPM7_wxgui::cmbBand protected
Definition at line 34 of file HPM7_wxgui.h.
Referenced by DownloadAll(), OnGPIOchange(), SelectBand(), and UploadGPIO().
wxComboBox* HPM7_wxgui::cmbDAC_A protected
Definition at line 43 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and OnDACchange().
wxComboBox* HPM7_wxgui::cmbDAC_B protected
Definition at line 44 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and OnDACchange().
wxComboBox* HPM7_wxgui::cmbLNA protected
Definition at line 35 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and UploadGPIO().
wxComboBox* HPM7_wxgui::cmbPAdriver protected
Definition at line 36 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and UploadGPIO().
std::vector<wxComboBox*> HPM7_wxgui::cmbSSC1 protected
Definition at line 40 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and OnTunerSSC1change().
std::vector<long> HPM7_wxgui::cmbSSC1ids private
Definition at line 54 of file HPM7_wxgui.h.
std::vector<wxComboBox*> HPM7_wxgui::cmbSSC2 protected
Definition at line 41 of file HPM7_wxgui.h.
Referenced by DownloadAll(), and OnTunerSSC2change().
std::vector<long> HPM7_wxgui::cmbSSC2ids private
Definition at line 55 of file HPM7_wxgui.h.
lime::LMS64CProtocol* HPM7_wxgui::m_serPort protected
Definition at line 58 of file HPM7_wxgui.h.
Referenced by DownloadAll(), Initialize(), OnDACchange(), OnTunerSSC1change(), OnTunerSSC2change(), and UploadGPIO().
std::vector<long> HPM7_wxgui::tunerIds protected
Definition at line 37 of file HPM7_wxgui.h.
Referenced by OnTunerSSC2change().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/HPM7/HPM7_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/HPM7/HPM7_wxgui.cpp