LimeSuite-UML: swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper > Class Template Reference
swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper > Class Template Reference
Public Types
typedef OutIterator out_iterator
typedef ValueType value_type
typedef SwigPyIterator_T< out_iterator > base
typedef SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper > self_type
typedef OutIterator out_iterator
typedef ValueType value_type
typedef SwigPyIterator_T< out_iterator > base
typedef SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper > self_type
Public Types inherited from swig::SwigPyIterator_T< OutIterator >
typedef OutIterator out_iterator
typedef std::iterator_traits< out_iterator >::value_type value_type
typedef SwigPyIterator_T< out_iterator > self_type
typedef OutIterator out_iterator
typedef std::iterator_traits< out_iterator >::value_type value_type
typedef SwigPyIterator_T< out_iterator > self_type
Public Member Functions
SwigPyIteratorOpen_T (out_iterator curr, PyObject *seq)
PyObject * value () const
SwigPyIterator * copy () const
SwigPyIterator * incr (size_t n=1)
SwigPyIterator * decr (size_t n=1)
SwigPyIteratorOpen_T (out_iterator curr, PyObject *seq)
PyObject * value () const
SwigPyIterator * copy () const
SwigPyIterator * incr (size_t n=1)
SwigPyIterator * decr (size_t n=1)
Public Member Functions inherited from swig::SwigPyIterator_T< OutIterator >
SwigPyIterator_T (out_iterator curr, PyObject *seq)
const out_iterator & get_current () const
bool equal (const SwigPyIterator &iter) const
ptrdiff_t distance (const SwigPyIterator &iter) const
SwigPyIterator_T (out_iterator curr, PyObject *seq)
const out_iterator & get_current () const
bool equal (const SwigPyIterator &iter) const
ptrdiff_t distance (const SwigPyIterator &iter) const
Public Member Functions inherited from swig::SwigPyIterator
virtual ~SwigPyIterator ()
PyObject * next ()
PyObject * __next__ ()
PyObject * previous ()
SwigPyIterator * advance (ptrdiff_t n)
bool operator== (const SwigPyIterator &x) const
bool operator!= (const SwigPyIterator &x) const
SwigPyIterator & operator+= (ptrdiff_t n)
SwigPyIterator & operator-= (ptrdiff_t n)
SwigPyIterator * operator+ (ptrdiff_t n) const
SwigPyIterator * operator- (ptrdiff_t n) const
ptrdiff_t operator- (const SwigPyIterator &x) const
virtual ~SwigPyIterator ()
PyObject * next ()
PyObject * __next__ ()
PyObject * previous ()
SwigPyIterator * advance (ptrdiff_t n)
bool operator== (const SwigPyIterator &x) const
bool operator!= (const SwigPyIterator &x) const
SwigPyIterator & operator+= (ptrdiff_t n)
SwigPyIterator & operator-= (ptrdiff_t n)
SwigPyIterator * operator+ (ptrdiff_t n) const
SwigPyIterator * operator- (ptrdiff_t n) const
ptrdiff_t operator- (const SwigPyIterator &x) const
Public Attributes
FromOper from
Additional Inherited Members
Static Public Member Functions inherited from swig::SwigPyIterator
static swig_type_info * descriptor ()
static swig_type_info * descriptor ()
Protected Member Functions inherited from swig::SwigPyIterator
SwigPyIterator (PyObject *seq)
SwigPyIterator (PyObject *seq)
Protected Attributes inherited from swig::SwigPyIterator_T< OutIterator >
out_iterator current
Detailed Description
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>>
class swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >
Definition at line 4325 of file SoapySDRPYTHON_wrap.cxx.
Member Typedef Documentation
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef SwigPyIterator_T<out_iterator> swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::base
Definition at line 3969 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef SwigPyIterator_T<out_iterator> swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::base
Definition at line 4331 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef OutIterator swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::out_iterator
Definition at line 3967 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef OutIterator swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::out_iterator
Definition at line 4329 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef SwigPyIteratorOpen_T<OutIterator, ValueType, FromOper> swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::self_type
Definition at line 3970 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef SwigPyIteratorOpen_T<OutIterator, ValueType, FromOper> swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::self_type
Definition at line 4332 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef ValueType swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::value_type
Definition at line 3968 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> typedef ValueType swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::value_type
Definition at line 4330 of file SoapySDRPYTHON_wrap.cxx.
Constructor & Destructor Documentation
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::SwigPyIteratorOpen_T (out_iterator curr, PyObject * seq) inline
Definition at line 4334 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::SwigPyIteratorOpen_T (out_iterator curr, PyObject * seq) inline
Definition at line 3972 of file radar_swigPYTHON_wrap.cxx.
Member Function Documentation
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> SwigPyIterator* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::copy () const inline virtual
Implements swig::SwigPyIterator.
Definition at line 3981 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> SwigPyIterator* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::copy () const inline virtual
Implements swig::SwigPyIterator.
Definition at line 4343 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> SwigPyIterator* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::decr (size_t n = 1) inline virtual
Reimplemented from swig::SwigPyIterator.
Definition at line 3994 of file radar_swigPYTHON_wrap.cxx.
References swig::from().
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> SwigPyIterator* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::decr (size_t n = 1) inline virtual
Reimplemented from swig::SwigPyIterator.
Definition at line 4356 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> SwigPyIterator* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::incr (size_t n = 1) inline virtual
Implements swig::SwigPyIterator.
Definition at line 3986 of file radar_swigPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> SwigPyIterator* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::incr (size_t n = 1) inline virtual
Implements swig::SwigPyIterator.
Definition at line 4348 of file SoapySDRPYTHON_wrap.cxx.
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> PyObject* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::value () const inline virtual
Implements swig::SwigPyIterator.
Definition at line 3977 of file radar_swigPYTHON_wrap.cxx.
References swig::from().
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> PyObject* swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::value () const inline virtual
Implements swig::SwigPyIterator.
Definition at line 4339 of file SoapySDRPYTHON_wrap.cxx.
References swig::from().
Member Data Documentation
template<typename OutIterator, typename ValueType = typename std::iterator_traits<OutIterator>::value_type, typename FromOper = from_oper<ValueType>> FromOper swig::SwigPyIteratorOpen_T< OutIterator, ValueType, FromOper >::from
Definition at line 4328 of file SoapySDRPYTHON_wrap.cxx.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/soapysdr/build/python/SoapySDRPYTHON_wrap.cxx
/home/erik/prefix/default/src/gr-radar-dev/build/swig/radar_swigPYTHON_wrap.cxx