LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/external/cpp-feather-ini-parser/example/example.cpp File Reference
example.cpp File Reference
#include <iostream>
#include <cstring>
#include <stdint.h>
#include "../INI.h"
Functions
void centerString (string str)
std::string getStringFromFile (const std::string &path)
int main ()
Function Documentation
void centerString (string str)
Definition at line 115 of file example.cpp.
References i, int(), and get_pic::s.
Referenced by main().
std::string getStringFromFile (const std::string & path)
Definition at line 125 of file example.cpp.
Referenced by main().
int main (void)
Declare
Manipulate and access contents
Iterate through sections and keys for both C++11 and C++98
Example with different data types
Wide char support example (please define FINI_WIDE_SUPPORT in project)
Load from memory
Merge contents and keep values
Definition at line 11 of file example.cpp.
References centerString(), getStringFromFile(), i, and string().