LimeSuite-UML: lime::LMS64CProtocol Class Reference
lime::LMS64CProtocol Class Reference abstract
#include <LMS64CProtocol.h>
Classes
struct FPGAinfo
struct GenericPacket
struct LMSinfo
struct ProtocolDIGIC
struct ProtocolLMS64C
struct ProtocolNovena
Public Types
enum eConnectionType {
CONNECTION_UNDEFINED = -1, COM_PORT = 0, USB_PORT = 1, SPI_PORT = 2,
PCIE_PORT = 3, CONNECTION_TYPES_COUNT
}
Supported connection types.
enum eLMS_PROTOCOL { LMS_PROTOCOL_UNDEFINED = 0, LMS_PROTOCOL_DIGIC, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA }
enum ProgramWriteTarget { HPM, FX3, FPGA, PROGRAM_WRITE_TARGET_COUNT }
Public Types inherited from lime::IConnection
enum MCU_PROG_MODE { RESET = 0, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM }
typedef std::function< bool(int bsent, int btotal, const char *progressMsg)> ProgrammingCallback
Public Member Functions
LMS64CProtocol (void)
virtual ~LMS64CProtocol (void)
virtual DeviceInfo GetDeviceInfo (void)
int DeviceReset (int ind=0)
DeviceReset implemented by LMS64C.
int TransactSPI (const int addr, const uint32_t *writeData, uint32_t *readData, const size_t size) override
TransactSPI implemented by LMS64C.
int WriteI2C (const int addr, const std::string &data)
WriteI2C implemented by LMS64C.
int ReadI2C (const int addr, const size_t numBytes, std::string &data)
ReadI2C implemented by LMS64C.
int WriteRegisters (const uint32_t *addrs, const uint32_t *data, const size_t size)
WriteRegisters (BRDSPI) implemented by LMS64C.
int ReadRegisters (const uint32_t *addrs, uint32_t *data, const size_t size)
ReadRegisters (BRDSPI) implemented by LMS64C.
virtual int TransferPacket (GenericPacket &pkt)
Transfers data between packet and connected device.
LMSinfo GetInfo ()
Returns connected device information.
FPGAinfo GetFPGAInfo ()
Returns information from FPGA gateware.
void VersionCheck ()
int ProgramUpdate (const bool download, IConnection::ProgrammingCallback callback) override
virtual eConnectionType GetType (void)=0
implement in base class
virtual int Write (const unsigned char *buffer, int length, int timeout_ms=100)=0
virtual write function to be implemented by the base class
virtual int Read (unsigned char *buffer, int length, int timeout_ms=100)=0
virtual read function to be implemented by the base class
virtual int ProgramWrite (const char *buffer, const size_t length, const int programmingMode, const int device, ProgrammingCallback callback=nullptr)
Uploads program to selected device.
virtual int CustomParameterRead (const uint8_t *ids, double *values, const size_t count, std::string *units) override
Returns value of custom on board control.
virtual int CustomParameterWrite (const uint8_t *ids, const double *values, const size_t count, const std::string &units) override
Sets custom on board control to given value units.
virtual int GPIOWrite (const uint8_t *buffer, const size_t bufLength) override
Writes GPIO values to device.
virtual int GPIORead (uint8_t *buffer, const size_t bufLength) override
Reads GPIO values from device.
virtual int GPIODirWrite (const uint8_t *buffer, const size_t bufLength) override
Write GPIO direction control values to device.
virtual int GPIODirRead (uint8_t *buffer, const size_t bufLength) override
Read GPIO direction configuration from device.
int ProgramMCU (const uint8_t *buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback) override
Uploads program to MCU.
int WriteLMS7002MSPI (const uint32_t *writeData, size_t size, unsigned periphID=0) override
int ReadLMS7002MSPI (const uint32_t *writeData, uint32_t *readData, size_t size, unsigned periphID=0) override
Public Member Functions inherited from lime::IConnection
IConnection (void)
IConnection constructor.
virtual ~IConnection (void)
IConnection destructor.
const ConnectionHandle & GetHandle (void) const
Get the connection handle that was used to create this connection.
virtual bool IsOpen (void)
virtual int ResetStreamBuffers ()
Read raw stream data from device streaming port.
virtual int GetBuffersCount () const
virtual int CheckStreamSize (int size) const
virtual int ReceiveData (char *buffer, int length, int epIndex, int timeout=100)
virtual int SendData (const char *buffer, int length, int epIndex, int timeout=100)
virtual int BeginDataSending (const char *buffer, uint32_t length, int ep)
virtual bool WaitForSending (int contextHandle, uint32_t timeout_ms)
virtual int FinishDataSending (const char *buffer, uint32_t length, int contextHandle)
virtual void AbortSending (int ep)
virtual int BeginDataReading (char *buffer, uint32_t length, int ep)
virtual bool WaitForReading (int contextHandle, unsigned int timeout_ms)
virtual int FinishDataReading (char *buffer, uint32_t length, int contextHandle)
virtual void AbortReading (int ep)
int WriteRegister (const uint32_t addr, const uint32_t data)
Write a single device register.
template<typename ReadType >
int ReadRegister (const uint32_t addr, ReadType &data)
Read a single device register.
void SetDataLogCallback (std::function< void(bool, const unsigned char *, const unsigned int)> callback)
Sets callback function which gets called each time data is sent or received.
Private Member Functions
int WriteSi5351I2C (const std::string &data)
int ReadSi5351I2C (const size_t numBytes, std::string &data)
int WriteADF4002SPI (const uint32_t *writeData, const size_t size)
int ReadADF4002SPI (const uint32_t *writeData, uint32_t *readData, const size_t size)
unsigned char * PreparePacket (const GenericPacket &pkt, int &length, const eLMS_PROTOCOL protocol)
Takes generic packet and converts to specific protocol buffer.
int ParsePacket (GenericPacket &pkt, const unsigned char *buffer, const int length, const eLMS_PROTOCOL protocol)
Parses given data buffer into generic packet.
Private Attributes
std::mutex mControlPortLock
double _cachedRefClockRate
Additional Inherited Members
Protected Attributes inherited from lime::IConnection
std::function< void(bool, const unsigned char *, const unsigned int)> callback_logData
Detailed Description
Implement the LMS64CProtocol. The LMS64CProtocol is an IConnection that implements configuration and spi access over the LMS64C Protocol. Connections using LMS64C may inherit from LMS64C.
Definition at line 21 of file LMS64CProtocol.h.
Member Enumeration Documentation
enum lime::LMS64CProtocol::eConnectionType
Supported connection types.
Enumerator
CONNECTION_UNDEFINED
COM_PORT
USB_PORT
SPI_PORT
PCIE_PORT
CONNECTION_TYPES_COUNT
Definition at line 49 of file LMS64CProtocol.h.
enum lime::LMS64CProtocol::eLMS_PROTOCOL
Enumerator
LMS_PROTOCOL_UNDEFINED
LMS_PROTOCOL_DIGIC
LMS_PROTOCOL_LMS64C
LMS_PROTOCOL_NOVENA
Definition at line 60 of file LMS64CProtocol.h.
enum lime::LMS64CProtocol::ProgramWriteTarget
Enumerator
HPM
FX3
FPGA
PROGRAM_WRITE_TARGET_COUNT
Definition at line 165 of file LMS64CProtocol.h.
Constructor & Destructor Documentation
LMS64CProtocol::LMS64CProtocol (void)
Definition at line 42 of file LMS64CProtocol.cpp.
References _cachedRefClockRate.
LMS64CProtocol::~LMS64CProtocol (void) virtual
Definition at line 48 of file LMS64CProtocol.cpp.
Member Function Documentation
int LMS64CProtocol::CustomParameterRead (const uint8_t * ids, double * values, const size_t count, std::string * units) override virtual
Returns value of custom on board control.
Parameters
ids indexes of controls to read
values retrieved control values
count number of values to read
units (optional) when not null returns value units (e.g V, A, Ohm, C...)
Returns
the operation success state
Reimplemented from lime::IConnection.
Definition at line 753 of file LMS64CProtocol.cpp.
References lime::adcUnits2string(), lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_ANALOG_VAL_RD, i, lime::LMS64CProtocol::GenericPacket::inBuffer, lime::LMS64CProtocol::GenericPacket::outBuffer, status, lime::TEMPERATURE, and TransferPacket().
int LMS64CProtocol::CustomParameterWrite (const uint8_t * ids, const double * values, const size_t count, const std::string & units) override virtual
Sets custom on board control to given value units.
Parameters
ids indexes of selected controls
values new control values
count number of values to write
units (optional) when not null specifies value units (e.g V, A, Ohm, C...)
Returns
the operation success state
Reimplemented from lime::IConnection.
Definition at line 786 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_ANALOG_VAL_WR, i, lime::LMS64CProtocol::GenericPacket::outBuffer, and TransferPacket().
int LMS64CProtocol::DeviceReset (int ind = 0) virtual
DeviceReset implemented by LMS64C.
Reimplemented from lime::IConnection.
Definition at line 53 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_LMS7002_RST, convertStatus(), ind, lime::IConnection::IsOpen(), LMS_RST_PULSE, lime::LMS64CProtocol::GenericPacket::outBuffer, lime::LMS64CProtocol::GenericPacket::periphID, lime::ReportError(), status, and TransferPacket().
Referenced by lime::ConnectionSTREAM_UNITE::DeviceReset().
DeviceInfo LMS64CProtocol::GetDeviceInfo (void) virtual
Get information about a device for displaying helpful information or for making device-specific decisions.
Reimplemented from lime::IConnection.
Reimplemented in lime::ConnectionFT601, and lime::ConnectionSTREAM_UNITE.
Definition at line 273 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::FPGAinfo::boardID, lime::DeviceInfo::boardSerialNumber, lime::LMS64CProtocol::LMSinfo::boardSerialNumber, lime::LMS64CProtocol::LMSinfo::device, lime::DeviceInfo::deviceName, lime::LMS64CProtocol::LMSinfo::expansion, lime::DeviceInfo::expansionName, lime::LMS64CProtocol::LMSinfo::firmware, lime::DeviceInfo::firmwareVersion, lime::DeviceInfo::gatewareRevision, lime::LMS64CProtocol::FPGAinfo::gatewareRevision, lime::DeviceInfo::gatewareTargetBoard, lime::DeviceInfo::gatewareVersion, lime::LMS64CProtocol::FPGAinfo::gatewareVersion, lime::GetDeviceName(), lime::GetExpansionBoardName(), GetFPGAInfo(), GetInfo(), lime::LMS64CProtocol::LMSinfo::hardware, lime::DeviceInfo::hardwareVersion, lime::LMS64CProtocol::FPGAinfo::hwVersion, lime::LMS64CProtocol::LMSinfo::protocol, and lime::DeviceInfo::protocolVersion.
Referenced by lime::ConnectionSTREAM_UNITE::GetDeviceInfo().
LMS64CProtocol::FPGAinfo LMS64CProtocol::GetFPGAInfo ()
Returns information from FPGA gateware.
Definition at line 326 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::FPGAinfo::boardID, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_BRDSPI_RD, lime::LMS64CProtocol::FPGAinfo::gatewareRevision, lime::LMS64CProtocol::FPGAinfo::gatewareVersion, lime::LMS64CProtocol::FPGAinfo::hwVersion, i, lime::LMS64CProtocol::GenericPacket::inBuffer, lime::info(), lime::LMS64CProtocol::GenericPacket::outBuffer, status, and TransferPacket().
Referenced by GetDeviceInfo().
LMS64CProtocol::LMSinfo LMS64CProtocol::GetInfo ()
Returns connected device information.
Definition at line 295 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::LMSinfo::boardSerialNumber, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_GET_INFO, lime::LMS64CProtocol::LMSinfo::device, lime::EXP_BOARD_COUNT, lime::EXP_BOARD_UNKNOWN, lime::LMS64CProtocol::LMSinfo::expansion, lime::LMS64CProtocol::LMSinfo::firmware, lime::LMS64CProtocol::LMSinfo::hardware, i, lime::LMS64CProtocol::GenericPacket::inBuffer, lime::info(), lime::LMS_DEV_COUNT, lime::LMS_DEV_UNKNOWN, lime::LMS64CProtocol::LMSinfo::protocol, status, and TransferPacket().
Referenced by GetDeviceInfo().
virtual eConnectionType lime::LMS64CProtocol::GetType (void) pure virtual
implement in base class
Implemented in lime::ConnectionFX3, lime::ConnectionFT601, lime::ConnectionXillybus, lime::ConnectionNovenaRF7, and lime::ConnectionEVB7COM.
Referenced by TransferPacket().
int LMS64CProtocol::GPIODirRead (uint8_t * buffer, const size_t bufLength) override virtual
Read GPIO direction configuration from device.
Parameters
buffer to put GPIO direction configuration (0 input, 1 output)
bufLength buffer length to read
Returns
the operation success state
Reimplemented from lime::IConnection.
Definition at line 839 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_GPIO_DIR_RD, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::inBuffer, status, and TransferPacket().
int LMS64CProtocol::GPIODirWrite (const uint8_t * buffer, const size_t bufLength) override virtual
Write GPIO direction control values to device.
Parameters
buffer with GPIO direction configuration (0 input, 1 output)
bufLength buffer length
Returns
the operation success state
Reimplemented from lime::IConnection.
Definition at line 830 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_GPIO_DIR_WR, i, lime::LMS64CProtocol::GenericPacket::outBuffer, and TransferPacket().
int LMS64CProtocol::GPIORead (uint8_t * buffer, const size_t bufLength) override virtual
Reads GPIO values from device.
Parameters
buffer destination for GPIO values LSB first, each bit represent GPIO state
bufLength buffer length to read
Returns
the operation success state
Reimplemented from lime::IConnection.
Definition at line 817 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_GPIO_RD, i, lime::LMS64CProtocol::GenericPacket::inBuffer, status, and TransferPacket().
int LMS64CProtocol::GPIOWrite (const uint8_t * buffer, const size_t bufLength) override virtual
Writes GPIO values to device.
Parameters
buffer for source of GPIO values LSB first, each bit sets GPIO state
bufLength buffer length
Returns
the operation success state
Reimplemented from lime::IConnection.
Definition at line 808 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_GPIO_WR, i, lime::LMS64CProtocol::GenericPacket::outBuffer, and TransferPacket().
int LMS64CProtocol::ParsePacket (GenericPacket & pkt, const unsigned char * buffer, const int length, const eLMS_PROTOCOL protocol) private
Parses given data buffer into generic packet.
Parameters
pkt destination packet
buffer received data from board
length received buffer length
protocol which protocol to use for data parsing
Returns
1:success, 0:failure
Definition at line 586 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_LMS7002_RD, i, lime::LMS64CProtocol::GenericPacket::inBuffer, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA, LMS_PROTOCOL_UNDEFINED, lime::LMS64CProtocol::ProtocolLMS64C::maxDataLength, lime::LMS64CProtocol::ProtocolLMS64C::pktLength, lime::LMS64CProtocol::GenericPacket::status, and lime::STATUS_COMPLETED_CMD.
Referenced by TransferPacket().
unsigned char * LMS64CProtocol::PreparePacket (const GenericPacket & pkt, int & length, const eLMS_PROTOCOL protocol) private
Takes generic packet and converts to specific protocol buffer.
Parameters
pkt generic data packet to convert
length returns length of returned buffer
protocol which protocol to use for data
Returns
pointer to data buffer, must be manually deleted after use
Definition at line 474 of file LMS64CProtocol.cpp.
References buffer, lime::LMS64CProtocol::GenericPacket::cmd, lime::LMS64CProtocol::ProtocolLMS64C::cmd, lime::CMD_ADF4002_WR, lime::CMD_ANALOG_VAL_RD, lime::CMD_ANALOG_VAL_WR, lime::CMD_BRDSPI8_RD, lime::CMD_BRDSPI_RD, lime::CMD_BRDSPI_WR, lime::CMD_GET_INFO, lime::CMD_LMS7002_RD, lime::CMD_LMS7002_RST, lime::CMD_LMS7002_WR, lime::CMD_PROG_MCU, lime::CMD_SI5351_RD, lime::CMD_SI5351_WR, lime::CMD_SI5356_RD, lime::CMD_SI5356_WR, i, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA, LMS_PROTOCOL_UNDEFINED, lime::LMS64CProtocol::ProtocolLMS64C::maxDataLength, lime::LMS64CProtocol::GenericPacket::outBuffer, lime::LMS64CProtocol::GenericPacket::periphID, lime::LMS64CProtocol::ProtocolLMS64C::periphID, lime::LMS64CProtocol::ProtocolLMS64C::pktLength, lime::LMS64CProtocol::ProtocolLMS64C::reserved, lime::LMS64CProtocol::GenericPacket::status, and lime::LMS64CProtocol::ProtocolLMS64C::status.
Referenced by TransferPacket().
int LMS64CProtocol::ProgramMCU (const uint8_t * buffer, const size_t length, const MCU_PROG_MODE mode, ProgrammingCallback callback) override virtual
Uploads program to MCU.
Parameters
buffer binary program data
length buffer length
mode MCU programing mode RESET, EEPROM_AND_SRAM, SRAM, BOOT_SRAM_FROM_EEPROM
callback callback for progress reporting or early termination
Returns
0-success
This could be a quite long operation, use callback to get progress info or to terminate early
Reimplemented from lime::IConnection.
Definition at line 852 of file LMS64CProtocol.cpp.
References callback, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_PROG_MCU, i, lime::LMS64CProtocol::GenericPacket::outBuffer, lime::LMS64CProtocol::GenericPacket::status, status, lime::STATUS_COMPLETED_CMD, lime::STATUS_UNDEFINED, and TransferPacket().
int LMS64CProtocol::ProgramUpdate (const bool download, IConnection::ProgrammingCallback callback) override virtual
Download up-to-date images files and flash the board when applicable.
Program update is an implementation specific function that may handle several different use cases depending upon what options are applicable:
If a board relies on certain firmware and gateware images, these images will be downloaded if not present on the system.
If the board has a programmable flash for firmware and gateware, then up-to-date images will be written to the flash on the board.
Parameters
download true to enable downloading missing images
callback callback for progress reporting or early termination
Returns
0-success
Reimplemented from lime::IConnection.
Definition at line 104 of file ConnectionImages.cpp.
References callback, device, lime::downloadImageResource(), FPGA, FX3, lime::GetDeviceName(), lime::info(), lime::LMS_DEV_UNKNOWN, lime::locateImageResource(), lookupImageEntry(), programmingCallbackStream(), lime::ReportError(), and status.
int LMS64CProtocol::ProgramWrite (const char * buffer, const size_t length, const int programmingMode, const int index, ProgrammingCallback callback = nullptr) virtual
Uploads program to selected device.
Parameters
buffer binary program data
length buffer length
programmingMode to RAM, to FLASH, to EEPROM, etc..
index target device number
callback callback for progress reporting or early termination
Returns
the operation success state
Can be used to program MCU, FPGA, write external on board memory. This could be a quite long operation, use callback to get progress info or to terminate early
Reimplemented from lime::IConnection.
Reimplemented in lime::ConnectionFX3, and lime::ConnectionFT601.
Definition at line 622 of file LMS64CProtocol.cpp.
References callback, lime::CMD_ALTERA_FPGA_GW_WR, lime::CMD_MEMORY_WR, FX3, lime::IConnection::IsOpen(), Read(), lime::ReportError(), status, lime::status2string(), lime::STATUS_COMPLETED_CMD, t1, t2, and Write().
virtual int lime::LMS64CProtocol::Read (unsigned char * buffer, int length, int timeout_ms = 100) pure virtual
virtual read function to be implemented by the base class
Implemented in lime::ConnectionFX3, lime::ConnectionFT601, lime::ConnectionNovenaRF7, lime::ConnectionEVB7COM, and lime::ConnectionXillybus.
Referenced by ProgramWrite(), and TransferPacket().
int LMS64CProtocol::ReadADF4002SPI (const uint32_t * writeData, uint32_t * readData, const size_t size) private
Definition at line 221 of file LMS64CProtocol.cpp.
References lime::ReportError().
Referenced by TransactSPI().
int LMS64CProtocol::ReadI2C (const int addr, const size_t numBytes, std::string & data) virtual
ReadI2C implemented by LMS64C.
Reimplemented from lime::IConnection.
Definition at line 107 of file LMS64CProtocol.cpp.
References lime::IConnection::IsOpen(), ReadSi5351I2C(), and lime::ReportError().
int LMS64CProtocol::ReadLMS7002MSPI (const uint32_t * writeData, uint32_t * readData, size_t size, unsigned periphID = 0) override virtual
Implements lime::IConnection.
Definition at line 139 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_LMS7002_RD, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::inBuffer, lime::LMS64CProtocol::GenericPacket::outBuffer, lime::LMS64CProtocol::GenericPacket::periphID, status, and TransferPacket().
Referenced by TransactSPI().
int LMS64CProtocol::ReadRegisters (const uint32_t * addrs, uint32_t * data, const size_t size) virtual
ReadRegisters (BRDSPI) implemented by LMS64C.
Reimplemented from lime::IConnection.
Definition at line 247 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_BRDSPI_RD, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::inBuffer, lime::LMS64CProtocol::GenericPacket::outBuffer, status, and TransferPacket().
int LMS64CProtocol::ReadSi5351I2C (const size_t numBytes, std::string & data) private
Definition at line 181 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_SI5351_RD, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::inBuffer, lime::LMS64CProtocol::GenericPacket::outBuffer, status, and TransferPacket().
Referenced by ReadI2C().
int LMS64CProtocol::TransactSPI (const int addr, const uint32_t * writeData, uint32_t * readData, const size_t size) override virtual
TransactSPI implemented by LMS64C.
TODO For multi-LMS7002M, RFIC # could be encoded with the slave number And the index would need to be encoded into the packet as well
Reimplemented from lime::IConnection.
Definition at line 69 of file LMS64CProtocol.cpp.
References ADF4002_SPI_INDEX, lime::IConnection::IsOpen(), LMS7002M_SPI_INDEX, ReadADF4002SPI(), ReadLMS7002MSPI(), lime::ReportError(), WriteADF4002SPI(), and WriteLMS7002MSPI().
Referenced by lime::ConnectionSTREAM_UNITE::TransactSPI().
int LMS64CProtocol::TransferPacket (GenericPacket & pkt) virtual
Transfers data between packet and connected device.
Transfer a packet over the underlying transport layer. TransferPacket performs a request/response using the GenericPacket data structure. Some implementations will cast to LMS64CProtocol and directly use the TransferPacket() API call.
Parameters
pkt packet containing output data and to receive incomming data
Returns
0: success, other: failure
Reimplemented in lime::ConnectionSTREAM_UNITE.
Definition at line 356 of file LMS64CProtocol.cpp.
References lime::IConnection::callback_logData, lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_GET_INFO, lime::CMD_LMS7002_RD, convertStatus(), lime::EXP_BOARD_UNSUPPORTED, GetType(), i, lime::LMS64CProtocol::GenericPacket::inBuffer, lime::IConnection::IsOpen(), lime::LMS_DEV_NOVENA, LMS_PROTOCOL_LMS64C, LMS_PROTOCOL_NOVENA, LMS_PROTOCOL_UNDEFINED, mControlPortLock, lime::LMS64CProtocol::GenericPacket::outBuffer, ParsePacket(), lime::LMS64CProtocol::ProtocolLMS64C::pktLength, lime::LMS64CProtocol::ProtocolNovena::pktLength, PreparePacket(), Read(), lime::ReportError(), SPI_PORT, lime::LMS64CProtocol::GenericPacket::status, status, lime::STATUS_COMPLETED_CMD, and Write().
Referenced by CustomParameterRead(), CustomParameterWrite(), DeviceReset(), HPM7_wxgui::DownloadAll(), GetFPGAInfo(), GetInfo(), GPIODirRead(), GPIODirWrite(), GPIORead(), GPIOWrite(), LMS_TransferLMS64C(), HPM7_wxgui::OnDACchange(), HPM7_wxgui::OnTunerSSC1change(), HPM7_wxgui::OnTunerSSC2change(), ProgramMCU(), ReadLMS7002MSPI(), ReadRegisters(), ReadSi5351I2C(), lime::ConnectionSTREAM_UNITE::TransferPacket(), HPM7_wxgui::UploadGPIO(), WriteADF4002SPI(), WriteLMS7002MSPI(), WriteRegisters(), and WriteSi5351I2C().
void LMS64CProtocol::VersionCheck (void)
Definition at line 59 of file ConnectionImages.cpp.
References lime::info(), lime::LMS_DEV_UNKNOWN, lookupImageEntry(), and lime::warning().
virtual int lime::LMS64CProtocol::Write (const unsigned char * buffer, int length, int timeout_ms = 100) pure virtual
virtual write function to be implemented by the base class
Implemented in lime::ConnectionFX3, lime::ConnectionFT601, lime::ConnectionNovenaRF7, lime::ConnectionEVB7COM, and lime::ConnectionXillybus.
Referenced by ProgramWrite(), and TransferPacket().
int LMS64CProtocol::WriteADF4002SPI (const uint32_t * writeData, const size_t size) private
Definition at line 205 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_ADF4002_WR, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::outBuffer, status, and TransferPacket().
Referenced by TransactSPI().
int LMS64CProtocol::WriteI2C (const int addr, const std::string & data) virtual
WriteI2C implemented by LMS64C.
Reimplemented from lime::IConnection.
Definition at line 98 of file LMS64CProtocol.cpp.
References lime::IConnection::IsOpen(), lime::ReportError(), and WriteSi5351I2C().
int LMS64CProtocol::WriteLMS7002MSPI (const uint32_t * writeData, size_t size, unsigned periphID = 0) override virtual
Implements lime::IConnection.
Definition at line 119 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_LMS7002_WR, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::outBuffer, lime::LMS64CProtocol::GenericPacket::periphID, status, and TransferPacket().
Referenced by TransactSPI().
int LMS64CProtocol::WriteRegisters (const uint32_t * addrs, const uint32_t * data, const size_t size) virtual
WriteRegisters (BRDSPI) implemented by LMS64C.
Reimplemented from lime::IConnection.
Definition at line 230 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_BRDSPI_WR, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::outBuffer, status, and TransferPacket().
int LMS64CProtocol::WriteSi5351I2C (const std::string & data) private
Definition at line 167 of file LMS64CProtocol.cpp.
References lime::LMS64CProtocol::GenericPacket::cmd, lime::CMD_SI5351_WR, convertStatus(), i, lime::LMS64CProtocol::GenericPacket::outBuffer, status, and TransferPacket().
Referenced by WriteI2C().
Member Data Documentation
double lime::LMS64CProtocol::_cachedRefClockRate private
Definition at line 198 of file LMS64CProtocol.h.
Referenced by LMS64CProtocol().
std::mutex lime::LMS64CProtocol::mControlPortLock private
Definition at line 197 of file LMS64CProtocol.h.
Referenced by TransferPacket().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/protocols/LMS64CProtocol.h
/home/erik/prefix/default/src/limesuite-dev/src/protocols/ConnectionImages.cpp
/home/erik/prefix/default/src/limesuite-dev/src/protocols/LMS64CProtocol.cpp