LimeSuite-UML: fftviewer_frFFTviewer Class Reference
fftviewer_frFFTviewer Class Reference
Implementing frFFTviewer.
#include <fftviewer_frFFTviewer.h>
Classes
struct DataToGUI
Public Member Functions
fftviewer_frFFTviewer (wxWindow *parent)
Constructor.
~fftviewer_frFFTviewer ()
void Initialize (lms_device_t *pDataPort)
void SetNyquistFrequency ()
void StartStreaming ()
void StopStreaming ()
void OnbtnCaptureClick (wxCommandEvent &event)
Public Member Functions inherited from frFFTviewer
frFFTviewer (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("FFT viewer"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxDEFAULT_FRAME_STYLE|wxTAB_TRAVERSAL)
~frFFTviewer ()
void mPlotsSplitterOnIdle (wxIdleEvent &)
Protected Member Functions
void OnWindowFunctionChanged (wxCommandEvent &event)
void OnbtnStartStop (wxCommandEvent &event)
void OnChannelVisibilityChange (wxCommandEvent &event)
void OnStreamChange (wxCommandEvent &event)
void OnEnTx (wxCommandEvent &event)
void OnEnPwr (wxCommandEvent &event)
void OnFmtChange (wxCommandEvent &event)
void OnAvgChange (wxSpinEvent &event)
void OnAvgChangeEnter (wxCommandEvent &event)
void OnWindowFunctionChange (wxCommandEvent &event)
void OnUpdateStats (wxTimerEvent &event)
void OnUpdatePlots (wxThreadEvent &event)
wxString printDataRate (float dataRate)
Protected Member Functions inherited from frFFTviewer
virtual void OnFFTsamplesCountChanged (wxSpinEvent &event)
Static Protected Member Functions
static void StreamingLoop (fftviewer_frFFTviewer *pthis, const unsigned int fftSize, const int channelsCount, const uint32_t format)
Protected Attributes
std::atomic< bool > enableTransmitter
std::atomic< int > windowFunctionID
std::atomic< bool > captureSamples
std::atomic< int > averageCount
std::atomic< bool > updateGUI
std::atomic< bool > enableFFT
std::string captureFilename
struct fftviewer_frFFTviewer::DataToGUI streamData
std::vector< float > fftFreqAxis
std::vector< float > timeXAxis
std::atomic< bool > mStreamRunning
std::atomic< bool > stopProcessing
std::thread threadProcessing
lms_stream_t rxStreams [cMaxChCount]
lms_stream_t txStreams [cMaxChCount]
lms_device_t * lmsControl
wxTimer * mGUIupdater
unsigned lmsIndex
Protected Attributes inherited from frFFTviewer
wxSplitterWindow * mPlotsSplitter
wxPanel * mTimeConstellationPanel
OpenGLGraph * mTimeDomainPanel
OpenGLGraph * mConstelationPanel
OpenGLGraph * mFFTpanel
wxStaticText * m_staticText6
wxTextCtrl * txtNyquistFreqMHz
wxStaticText * m_staticText7
wxSpinCtrl * spinFFTsize
wxChoice * cmbStreamType
wxChoice * cmbFmt
wxCheckBox * chkEnTx
wxCheckBox * chkEnSync
wxButton * btnStartStop
wxStaticText * m_staticText8
wxStaticText * lblRxDataRate
wxStaticText * m_staticText18
wxStaticText * lblTxDataRate
wxChoice * cmbWindowFunc
wxCheckBox * chkCaptureToFile
wxStaticText * m_staticText12
wxSpinCtrl * spinCaptureCount
wxCheckBox * chkFreezeTimeDomain
wxCheckBox * chkFreezeConstellation
wxCheckBox * chkFreezeFFT
wxStaticText * m_staticText11
wxChoice * cmbChannelVisibility
wxStaticText * m_staticText23
wxSpinCtrl * spinAvgCount
wxStaticText * m_staticText15
wxGauge * gaugeRxBuffer
wxStaticText * m_staticText16
wxGauge * gaugeTxBuffer
wxCheckBox * chkEnPwr
wxStaticText * m_staticText13
wxStaticText * m_staticText14
wxStaticText * m_staticText151
wxTextCtrl * txtCenterOffset1
wxTextCtrl * txtCenterOffset2
wxStaticText * m_staticText161
wxTextCtrl * txtBW1
wxTextCtrl * txtBW2
wxStaticText * m_staticText17
wxStaticText * lblPower1
wxStaticText * lblPower2
wxStaticText * m_staticText20
wxStaticText * lbldBc
Static Protected Attributes
static const int cMaxChCount = 2
Detailed Description
Implementing frFFTviewer.
Definition at line 18 of file fftviewer_frFFTviewer.h.
Constructor & Destructor Documentation
fftviewer_frFFTviewer::fftviewer_frFFTviewer (wxWindow * parent)
Constructor.
Definition at line 52 of file fftviewer_frFFTviewer.cpp.
References OpenGLGraph::AddSerie(), averageCount, captureSamples, GLG_LINE, GLG_POINTS, GLG_settings::gridXlines, GLG_settings::gridXprec, GLG_settings::gridYlines, GLG_settings::marginLeft, GLG_settings::markersEnabled, frFFTviewer::mConstelationPanel, frFFTviewer::mFFTpanel, mGUIupdater, frFFTviewer::mTimeDomainPanel, OnChannelVisibilityChange(), OnUpdatePlots(), OnUpdateStats(), OpenGLGraph::series, OpenGLGraph::SetDrawingMode(), OpenGLGraph::SetInitialDisplayArea(), OpenGLGraph::settings, frFFTviewer::spinAvgCount, GLG_settings::staticGrid, GLG_settings::title, GLG_settings::titleXaxis, GLG_settings::titleYaxis, updateGUI, GLG_settings::useVBO, and GLG_settings::xUnits.
fftviewer_frFFTviewer::~fftviewer_frFFTviewer ()
Definition at line 122 of file fftviewer_frFFTviewer.cpp.
References mStreamRunning, and StopStreaming().
Member Function Documentation
void fftviewer_frFFTviewer::Initialize (lms_device_t * pDataPort)
Definition at line 18 of file fftviewer_frFFTviewer.cpp.
References _T, i, LMS_GetNumChannels(), and lmsControl.
Referenced by LMS7SuiteAppFrame::OnShowFFTviewer(), and LMS7SuiteAppFrame::UpdateConnections().
void fftviewer_frFFTviewer::OnAvgChange (wxSpinEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 696 of file fftviewer_frFFTviewer.cpp.
References averageCount, and frFFTviewer::spinAvgCount.
void fftviewer_frFFTviewer::OnAvgChangeEnter (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 701 of file fftviewer_frFFTviewer.cpp.
References averageCount, and frFFTviewer::spinAvgCount.
void fftviewer_frFFTviewer::OnbtnCaptureClick (wxCommandEvent & event)
void fftviewer_frFFTviewer::OnbtnStartStop (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 133 of file fftviewer_frFFTviewer.cpp.
References StartStreaming(), StopStreaming(), and threadProcessing.
void fftviewer_frFFTviewer::OnChannelVisibilityChange (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 655 of file fftviewer_frFFTviewer.cpp.
References cMaxChCount, frFFTviewer::cmbStreamType, frFFTviewer::mConstelationPanel, frFFTviewer::mFFTpanel, frFFTviewer::mTimeDomainPanel, and OpenGLGraph::series.
Referenced by fftviewer_frFFTviewer().
void fftviewer_frFFTviewer::OnEnPwr (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 645 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::txtBW1, frFFTviewer::txtBW2, frFFTviewer::txtCenterOffset1, and frFFTviewer::txtCenterOffset2.
void fftviewer_frFFTviewer::OnEnTx (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 640 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::chkEnSync.
void fftviewer_frFFTviewer::OnFmtChange (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 633 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::mConstelationPanel, frFFTviewer::mTimeDomainPanel, and OpenGLGraph::SetInitialDisplayArea().
void fftviewer_frFFTviewer::OnStreamChange (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 617 of file fftviewer_frFFTviewer.cpp.
References _T, frFFTviewer::cmbChannelVisibility, frFFTviewer::cmbStreamType, and SetNyquistFrequency().
void fftviewer_frFFTviewer::OnUpdatePlots (wxThreadEvent & event) protected
Definition at line 255 of file fftviewer_frFFTviewer.cpp.
References bw, c, frFFTviewer::chkEnPwr, frFFTviewer::chkFreezeConstellation, frFFTviewer::chkFreezeFFT, frFFTviewer::chkFreezeTimeDomain, frFFTviewer::cmbFmt, OpenGLGraph::Draw(), enableFFT, fftviewer_frFFTviewer::DataToGUI::fftBins, fftFreqAxis, i, frFFTviewer::lbldBc, frFFTviewer::lblPower1, frFFTviewer::lblPower2, frFFTviewer::mConstelationPanel, frFFTviewer::mFFTpanel, mStreamRunning, frFFTviewer::mTimeDomainPanel, get_pic::s, fftviewer_frFFTviewer::DataToGUI::samplesI, fftviewer_frFFTviewer::DataToGUI::samplesQ, OpenGLGraph::series, streamData, timeXAxis, frFFTviewer::txtBW1, frFFTviewer::txtBW2, frFFTviewer::txtCenterOffset1, frFFTviewer::txtCenterOffset2, and updateGUI.
Referenced by fftviewer_frFFTviewer().
void fftviewer_frFFTviewer::OnUpdateStats (wxTimerEvent & event) protected
Definition at line 223 of file fftviewer_frFFTviewer.cpp.
References lms_stream_status_t::fifoFilledCount, lms_stream_status_t::fifoSize, frFFTviewer::gaugeRxBuffer, frFFTviewer::gaugeTxBuffer, frFFTviewer::lblRxDataRate, frFFTviewer::lblTxDataRate, lms_stream_status_t::linkRate, LMS_GetStreamStatus(), mStreamRunning, printDataRate(), rxStreams, and txStreams.
Referenced by fftviewer_frFFTviewer().
void fftviewer_frFFTviewer::OnWindowFunctionChange (wxCommandEvent & event) protected virtual
Reimplemented from frFFTviewer.
Definition at line 706 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::cmbWindowFunc, and windowFunctionID.
void fftviewer_frFFTviewer::OnWindowFunctionChanged (wxCommandEvent & event) protected
Definition at line 128 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::cmbWindowFunc, and windowFunctionID.
wxString fftviewer_frFFTviewer::printDataRate (float dataRate) protected
Definition at line 599 of file fftviewer_frFFTviewer.cpp.
Referenced by OnUpdateStats().
void fftviewer_frFFTviewer::SetNyquistFrequency ()
Definition at line 609 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::cmbStreamType, LMS_CH_RX, LMS_GetSampleRate(), lmsControl, frFFTviewer::mFFTpanel, OpenGLGraph::SetInitialDisplayArea(), and frFFTviewer::txtNyquistFreqMHz.
Referenced by OnStreamChange().
void fftviewer_frFFTviewer::StartStreaming ()
Definition at line 141 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::btnStartStop, captureFilename, captureSamples, frFFTviewer::chkCaptureToFile, frFFTviewer::chkEnSync, frFFTviewer::chkEnTx, frFFTviewer::cmbChannelVisibility, frFFTviewer::cmbFmt, frFFTviewer::cmbStreamType, fftFreqAxis, i, lmsControl, lmsIndex, mGUIupdater, mStreamRunning, frFFTviewer::spinCaptureCount, frFFTviewer::spinFFTsize, stopProcessing, StreamingLoop(), threadProcessing, timeXAxis, frFFTviewer::txtNyquistFreqMHz, and updateGUI.
Referenced by OnbtnStartStop().
void fftviewer_frFFTviewer::StopStreaming ()
Definition at line 204 of file fftviewer_frFFTviewer.cpp.
References frFFTviewer::btnStartStop, frFFTviewer::chkCaptureToFile, frFFTviewer::chkEnSync, frFFTviewer::chkEnTx, frFFTviewer::cmbChannelVisibility, frFFTviewer::cmbFmt, frFFTviewer::cmbStreamType, mGUIupdater, mStreamRunning, frFFTviewer::spinCaptureCount, frFFTviewer::spinFFTsize, stopProcessing, threadProcessing, and frFFTviewer::txtNyquistFreqMHz.
Referenced by OnbtnStartStop(), LMS7SuiteAppFrame::OnFFTviewerClose(), LMS7SuiteAppFrame::OnShowConnectionSettings(), and ~fftviewer_frFFTviewer().
void fftviewer_frFFTviewer::StreamingLoop (fftviewer_frFFTviewer * pthis, const unsigned int fftSize, const int channelsCount, const uint32_t format) static protected
Definition at line 346 of file fftviewer_frFFTviewer.cpp.
References averageCount, captureFilename, captureSamples, lms_stream_t::channel, frFFTviewer::chkEnSync, frFFTviewer::chkEnTx, cMaxChCount, frFFTviewer::cmbChannelVisibility, frFFTviewer::cmbFmt, lms_stream_t::dataFmt, enableFFT, fftviewer_frFFTviewer::DataToGUI::fftBins, lms_stream_t::fifoSize, filename, lms_stream_meta_t::flushPartialPacket, GenerateWindowCoefficients(), lms_stream_t::handle, i, lime::complex16_t::i, kiss_fft_cpx::i, lms_stream_t::isTx, kiss_fft(), kiss_fft_alloc(), kiss_fft_free, LMS_DestroyStream(), lms_stream_t::LMS_FMT_I12, lms_stream_t::LMS_FMT_I16, LMS_GetNumChannels(), LMS_RecvStream(), LMS_SendStream(), LMS_SetupStream(), LMS_StartStream(), LMS_StopStream(), lmsControl, lmsIndex, meta, mStreamRunning, fftviewer_frFFTviewer::DataToGUI::nyquist_Hz, lime::complex16_t::q, kiss_fft_cpx::r, rxStreams, get_pic::s, fftviewer_frFFTviewer::DataToGUI::samplesI, fftviewer_frFFTviewer::DataToGUI::samplesQ, frFFTviewer::spinAvgCount, frFFTviewer::spinCaptureCount, stopProcessing, streamData, lms_stream_t::throughputVsLatency, lms_stream_meta_t::timestamp, txStreams, updateGUI, lms_stream_meta_t::waitForTimestamp, and windowFunctionID.
Referenced by StartStreaming().
Member Data Documentation
std::atomic<int> fftviewer_frFFTviewer::averageCount protected
Definition at line 24 of file fftviewer_frFFTviewer.h.
Referenced by fftviewer_frFFTviewer(), OnAvgChange(), OnAvgChangeEnter(), and StreamingLoop().
std::string fftviewer_frFFTviewer::captureFilename protected
Definition at line 27 of file fftviewer_frFFTviewer.h.
Referenced by StartStreaming(), and StreamingLoop().
std::atomic<bool> fftviewer_frFFTviewer::captureSamples protected
Definition at line 23 of file fftviewer_frFFTviewer.h.
Referenced by fftviewer_frFFTviewer(), StartStreaming(), and StreamingLoop().
const int fftviewer_frFFTviewer::cMaxChCount = 2 static protected
Definition at line 56 of file fftviewer_frFFTviewer.h.
Referenced by OnChannelVisibilityChange(), fftviewer_frFFTviewer::DataToGUI::operator=(), and StreamingLoop().
std::atomic<bool> fftviewer_frFFTviewer::enableFFT protected
Definition at line 26 of file fftviewer_frFFTviewer.h.
Referenced by OnUpdatePlots(), and StreamingLoop().
std::atomic<bool> fftviewer_frFFTviewer::enableTransmitter protected
Definition at line 21 of file fftviewer_frFFTviewer.h.
std::vector<float> fftviewer_frFFTviewer::fftFreqAxis protected
Definition at line 87 of file fftviewer_frFFTviewer.h.
Referenced by OnUpdatePlots(), and StartStreaming().
lms_device_t* fftviewer_frFFTviewer::lmsControl protected
Definition at line 97 of file fftviewer_frFFTviewer.h.
Referenced by SetNyquistFrequency(), StartStreaming(), and StreamingLoop().
unsigned fftviewer_frFFTviewer::lmsIndex protected
Definition at line 99 of file fftviewer_frFFTviewer.h.
Referenced by StartStreaming(), and StreamingLoop().
wxTimer* fftviewer_frFFTviewer::mGUIupdater protected
Definition at line 98 of file fftviewer_frFFTviewer.h.
Referenced by fftviewer_frFFTviewer(), StartStreaming(), and StopStreaming().
std::atomic<bool> fftviewer_frFFTviewer::mStreamRunning protected
Definition at line 89 of file fftviewer_frFFTviewer.h.
Referenced by OnUpdatePlots(), OnUpdateStats(), StartStreaming(), StopStreaming(), StreamingLoop(), and ~fftviewer_frFFTviewer().
lms_stream_t fftviewer_frFFTviewer::rxStreams[cMaxChCount] protected
Definition at line 94 of file fftviewer_frFFTviewer.h.
Referenced by OnUpdateStats(), and StreamingLoop().
std::atomic<bool> fftviewer_frFFTviewer::stopProcessing protected
Definition at line 90 of file fftviewer_frFFTviewer.h.
Referenced by StartStreaming(), StopStreaming(), and StreamingLoop().
struct fftviewer_frFFTviewer::DataToGUI fftviewer_frFFTviewer::streamData protected
Referenced by OnUpdatePlots(), fftviewer_frFFTviewer::DataToGUI::operator=(), and StreamingLoop().
std::thread fftviewer_frFFTviewer::threadProcessing protected
Definition at line 91 of file fftviewer_frFFTviewer.h.
Referenced by OnbtnStartStop(), StartStreaming(), and StopStreaming().
std::vector<float> fftviewer_frFFTviewer::timeXAxis protected
Definition at line 88 of file fftviewer_frFFTviewer.h.
Referenced by OnUpdatePlots(), and StartStreaming().
lms_stream_t fftviewer_frFFTviewer::txStreams[cMaxChCount] protected
Definition at line 95 of file fftviewer_frFFTviewer.h.
Referenced by OnUpdateStats(), and StreamingLoop().
std::atomic<bool> fftviewer_frFFTviewer::updateGUI protected
Definition at line 25 of file fftviewer_frFFTviewer.h.
Referenced by fftviewer_frFFTviewer(), OnUpdatePlots(), StartStreaming(), and StreamingLoop().
std::atomic<int> fftviewer_frFFTviewer::windowFunctionID protected
Definition at line 22 of file fftviewer_frFFTviewer.h.
Referenced by OnWindowFunctionChange(), OnWindowFunctionChanged(), and StreamingLoop().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/fftviewer_wxgui/fftviewer_frFFTviewer.h
/home/erik/prefix/default/src/limesuite-dev/src/fftviewer_wxgui/fftviewer_frFFTviewer.cpp