LimeSuite-UML: SimpleSiggen Namespace Reference
SimpleSiggen Namespace Reference
Functions
def siggen_app (args, rate, ampl=0.7, freq=None, txBw=None, txChan=0, rxChan=0, txGain=None, txAnt=None, clockRate=None, waveFreq=None)
def main ()
Function Documentation
def SimpleSiggen.main (void)
Definition at line 86 of file SimpleSiggen.py.
References siggen_app().
def SimpleSiggen.siggen_app (args, rate, ampl = 0.7, freq = None, txBw = None, txChan = 0, rxChan = 0, txGain = None, txAnt = None, clockRate = None, waveFreq = None)
Definition at line 25 of file SimpleSiggen.py.
References print().
Referenced by main().