LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/boardEmulator.cpp File Reference
boardEmulator.cpp File Reference
#include <signal.h>
#include <stdlib.h>
#include <stdio.h>
#include <iostream>
#include <thread>
#include <unistd.h>
#include <fcntl.h>
#include <errno.h>
#include <string.h>
#include <vector>
#include <termios.h>
#include <map>
#include <ctime>
#include <LMS64CProtocol.h>
#include <LMSBoards.h>
Functions
int ProcessLMS64C (const uint8_t *input, uint8_t *output)
void ApplicationStopHandler (int s)
int main (int argc, char **argv)
void WriteRegister (const uint16_t addr, const uint16_t data)
uint16_t ReadRegister (const uint16_t addr)
Variables
bool stopApplication = false
map< uint16_t, uint16_t > channelA
map< uint16_t, uint16_t > channelB
map< uint16_t, uint16_t > fpgaRegisters
Function Documentation
void ApplicationStopHandler (int s)
Definition at line 24 of file boardEmulator.cpp.
References stopApplication.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 30 of file boardEmulator.cpp.
References ApplicationStopHandler(), i, ProcessLMS64C(), read(), stopApplication, system, and get_pic::tm.
int ProcessLMS64C (const uint8_t * input, uint8_t * output)
Definition at line 140 of file boardEmulator.cpp.
References lime::CMD_ALTERA_FPGA_GW_RD, lime::CMD_ALTERA_FPGA_GW_WR, lime::CMD_BRDSPI_RD, lime::CMD_BRDSPI_WR, lime::CMD_GET_INFO, lime::CMD_LMS7002_RD, lime::CMD_LMS7002_WR, lime::CMD_MEMORY_WR, lime::EXP_BOARD_UNSUPPORTED, i, lime::LMS_DEV_EVB7V2, ReadRegister(), lime::STATUS_COMPLETED_CMD, lime::STATUS_UNKNOWN_CMD, and WriteRegister().
Referenced by main().
uint16_t ReadRegister (const uint16_t addr)
Definition at line 130 of file boardEmulator.cpp.
Referenced by ProcessLMS64C(), and lime::ConnectionNovenaRF7::UpdateThreads().
void WriteRegister (const uint16_t addr, const uint16_t data)
Definition at line 123 of file boardEmulator.cpp.
Referenced by ProcessLMS64C(), and lime::ConnectionNovenaRF7::UpdateThreads().
Variable Documentation
map<uint16_t, uint16_t> channelA
Definition at line 117 of file boardEmulator.cpp.
map<uint16_t, uint16_t> channelB
Definition at line 118 of file boardEmulator.cpp.
map<uint16_t, uint16_t> fpgaRegisters
Definition at line 121 of file boardEmulator.cpp.
bool stopApplication = false
Definition at line 20 of file boardEmulator.cpp.
Referenced by ApplicationStopHandler(), and main().