LimeSuite-UML: lms7002_pnlBIST_view Class Reference
lms7002_pnlBIST_view Class Reference
Implementing pnlBIST_view.
#include <lms7002_pnlBIST_view.h>
Public Member Functions
lms7002_pnlBIST_view (wxWindow *parent)
Constructor.
lms7002_pnlBIST_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlBIST_view
pnlBIST_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlBIST_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void onbtnReadSignature (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlBIST_view
wxCheckBox * chkBENC
wxCheckBox * chkSDM_TSTO_CGEN
wxCheckBox * chkBENR
wxCheckBox * chkSDM_TSTO_SXR
wxCheckBox * chkBENT
wxCheckBox * chkSDM_TSTO_SXT
wxCheckBox * chkBSTART
wxStaticText * ID_STATICTEXT2
wxStaticText * lblBSTATE
wxStaticText * ID_STATICTEXT1
wxStaticText * lblBSIGT
wxStaticText * ID_STATICTEXT3
wxStaticText * lblBSIGR
wxStaticText * ID_STATICTEXT4
wxStaticText * lblBSIGC
wxButton * btnReadSignature
Additional Inherited Members
Protected Types inherited from pnlBIST_view
enum {
ID_BENC = 2048, ID_SDM_TSTO_CGEN, ID_BENR, ID_SDM_TSTO_SXR,
ID_BENT, ID_SDM_TSTO_SXT, ID_BSTART, ID_BSTATE,
ID_BSIGT, ID_BSIGR, ID_BSIGC, ID_BTN_READ_SIGNATURE
}
Detailed Description
Implementing pnlBIST_view.
Definition at line 18 of file lms7002_pnlBIST_view.h.
Constructor & Destructor Documentation
lms7002_pnlBIST_view::lms7002_pnlBIST_view (wxWindow * parent)
Constructor.
Definition at line 6 of file lms7002_pnlBIST_view.cpp.
lms7002_pnlBIST_view::lms7002_pnlBIST_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 13 of file lms7002_pnlBIST_view.cpp.
References BENC, BENR, BENT, BSTART, pnlBIST_view::chkBENC, pnlBIST_view::chkBENR, pnlBIST_view::chkBENT, pnlBIST_view::chkBSTART, pnlBIST_view::chkSDM_TSTO_CGEN, pnlBIST_view::chkSDM_TSTO_SXR, pnlBIST_view::chkSDM_TSTO_SXT, EN_SDM_TSTO_CGEN, EN_SDM_TSTO_SXR, EN_SDM_TSTO_SXT, LMS7param, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlBIST_view::Initialize (lms_device_t * pControl)
Definition at line 26 of file lms7002_pnlBIST_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlBIST_view::onbtnReadSignature (wxCommandEvent & event) protected virtual
Reimplemented from pnlBIST_view.
Definition at line 48 of file lms7002_pnlBIST_view.cpp.
References BSIGC, BSIGR, BSIGT, BSTATE, pnlBIST_view::lblBSIGC, pnlBIST_view::lblBSIGR, pnlBIST_view::lblBSIGT, pnlBIST_view::lblBSTATE, LMS7param, LMS_ReadParam(), and lmsControl.
void lms7002_pnlBIST_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlBIST_view.
Definition at line 32 of file lms7002_pnlBIST_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlBIST_view::UpdateGUI ()
Definition at line 62 of file lms7002_pnlBIST_view.cpp.
References lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlBIST_view::lmsControl protected
Definition at line 32 of file lms7002_pnlBIST_view.h.
Referenced by Initialize(), onbtnReadSignature(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlBIST_view::wndId2Enum protected
Definition at line 33 of file lms7002_pnlBIST_view.h.
Referenced by lms7002_pnlBIST_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlBIST_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlBIST_view.cpp