LimeSuite-UML: dlgGFIR_Coefficients Class Reference
dlgGFIR_Coefficients Class Reference
Class dlgGFIR_Coefficients.
#include <lms7002_wxgui.h>
Public Member Functions
dlgGFIR_Coefficients (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("Coefficients"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE)
~dlgGFIR_Coefficients ()
Protected Member Functions
virtual void OnLoadFromFile (wxCommandEvent &event)
virtual void OnSaveToFile (wxCommandEvent &event)
virtual void OnClearTable (wxCommandEvent &event)
virtual void OnspinCoefCountChange (wxSpinEvent &event)
virtual void OnBtnOkClick (wxCommandEvent &event)
virtual void OnBtnCancelClick (wxCommandEvent &event)
Protected Attributes
wxButton * btnLoadFromFile
wxButton * btnSaveToFile
wxButton * btnClearTable
wxStaticText * ID_STATICTEXT3
wxSpinCtrl * spinCoefCount
wxGrid * gridCoef
wxButton * btnOk
wxButton * btnCancel
Detailed Description
Class dlgGFIR_Coefficients.
Definition at line 2229 of file lms7002_wxgui.h.
Constructor & Destructor Documentation
dlgGFIR_Coefficients::dlgGFIR_Coefficients (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxT("Coefficients"), const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxDEFAULT_DIALOG_STYLE)
Definition at line 9764 of file lms7002_wxgui.cpp.
References btnCancel, btnClearTable, btnLoadFromFile, btnOk, btnSaveToFile, gridCoef, ID_STATICTEXT3, OnBtnCancelClick(), OnBtnOkClick(), OnClearTable(), OnLoadFromFile(), OnSaveToFile(), OnspinCoefCountChange(), and spinCoefCount.
dlgGFIR_Coefficients::~dlgGFIR_Coefficients ()
Definition at line 9868 of file lms7002_wxgui.cpp.
References btnCancel, btnClearTable, btnLoadFromFile, btnOk, btnSaveToFile, OnBtnCancelClick(), OnBtnOkClick(), OnClearTable(), OnLoadFromFile(), OnSaveToFile(), OnspinCoefCountChange(), and spinCoefCount.
Member Function Documentation
virtual void dlgGFIR_Coefficients::OnBtnCancelClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_dlgGFIR_Coefficients.
Definition at line 2249 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
virtual void dlgGFIR_Coefficients::OnBtnOkClick (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_dlgGFIR_Coefficients.
Definition at line 2248 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
virtual void dlgGFIR_Coefficients::OnClearTable (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_dlgGFIR_Coefficients.
Definition at line 2246 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
virtual void dlgGFIR_Coefficients::OnLoadFromFile (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_dlgGFIR_Coefficients.
Definition at line 2244 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
virtual void dlgGFIR_Coefficients::OnSaveToFile (wxCommandEvent & event) inline protected virtual
Reimplemented in lms7002_dlgGFIR_Coefficients.
Definition at line 2245 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
virtual void dlgGFIR_Coefficients::OnspinCoefCountChange (wxSpinEvent & event) inline protected virtual
Reimplemented in lms7002_dlgGFIR_Coefficients.
Definition at line 2247 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
Member Data Documentation
wxButton* dlgGFIR_Coefficients::btnCancel protected
Definition at line 2241 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
wxButton* dlgGFIR_Coefficients::btnClearTable protected
Definition at line 2236 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
wxButton* dlgGFIR_Coefficients::btnLoadFromFile protected
Definition at line 2234 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
wxButton* dlgGFIR_Coefficients::btnOk protected
Definition at line 2240 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
wxButton* dlgGFIR_Coefficients::btnSaveToFile protected
Definition at line 2235 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), and ~dlgGFIR_Coefficients().
wxGrid* dlgGFIR_Coefficients::gridCoef protected
Definition at line 2239 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), lms7002_dlgGFIR_Coefficients::GetCoefficients(), lms7002_dlgGFIR_Coefficients::OnClearTable(), lms7002_dlgGFIR_Coefficients::OnLoadFromFile(), lms7002_dlgGFIR_Coefficients::OnSaveToFile(), lms7002_dlgGFIR_Coefficients::OnspinCoefCountChange(), and lms7002_dlgGFIR_Coefficients::SetCoefficients().
wxStaticText* dlgGFIR_Coefficients::ID_STATICTEXT3 protected
Definition at line 2237 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients().
wxSpinCtrl* dlgGFIR_Coefficients::spinCoefCount protected
Definition at line 2238 of file lms7002_wxgui.h.
Referenced by dlgGFIR_Coefficients(), lms7002_dlgGFIR_Coefficients::GetCoefficients(), lms7002_dlgGFIR_Coefficients::OnClearTable(), lms7002_dlgGFIR_Coefficients::OnLoadFromFile(), lms7002_dlgGFIR_Coefficients::OnSaveToFile(), lms7002_dlgGFIR_Coefficients::OnspinCoefCountChange(), lms7002_dlgGFIR_Coefficients::SetCoefficients(), and ~dlgGFIR_Coefficients().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_wxgui.cpp