LimeSuite-UML: lms7002_pnlLDO_view Class Reference
lms7002_pnlLDO_view Class Reference
Implementing pnlLDO_view.
#include <lms7002_pnlLDO_view.h>
Public Member Functions
lms7002_pnlLDO_view (wxWindow *parent)
Constructor.
lms7002_pnlLDO_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlLDO_view
pnlLDO_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(1180, 550), long style=wxTAB_TRAVERSAL)
~pnlLDO_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlLDO_view
wxNotebook * ID_NOTEBOOK1
wxPanel * ID_PANEL3
wxCheckBox * chkEN_G_LDOP
wxCheckBox * chkEN_G_LDO
wxCheckBox * chkEN_LDO_DIVGN
wxCheckBox * chkEN_LDO_DIGGN
wxCheckBox * chkEN_LDO_CPGN
wxCheckBox * chkEN_LDO_VCOGN
wxCheckBox * chkEN_LDO_MXRFE
wxCheckBox * chkEN_LDO_LNA14
wxCheckBox * chkEN_LDO_LNA12
wxCheckBox * chkEN_LDO_TIA14
wxCheckBox * chkEN_LDO_DIVSXT
wxCheckBox * chkEN_LDO_DIGSXT
wxCheckBox * chkEN_LDO_CPSXT
wxCheckBox * chkEN_LDO_VCOSXT
wxCheckBox * chkEN_LDO_DIVSXR
wxCheckBox * chkEN_LDO_DIGSXR
wxCheckBox * chkEN_LDO_CPSXR
wxCheckBox * chkEN_LDO_VCOSXR
wxCheckBox * chkPD_LDO_DIGIp1
wxCheckBox * chkPD_LDO_DIGIp2
wxCheckBox * chkEN_LDO_TXBUF
wxCheckBox * chkEN_LDO_RXBUF
wxCheckBox * chkEN_LDO_TPAD
wxCheckBox * chkEN_LDO_TLOB
wxCheckBox * chkPD_LDO_SPIBUF
wxStaticText * m_staticText349
wxComboBox * cmbISINK_SPIBUFF
wxCheckBox * chkEN_LDO_AFE
wxCheckBox * chkEN_LDO_TBB
wxCheckBox * chkEN_LDO_RBB
wxCheckBox * chkEN_LDO_TIA12
wxCheckBox * chkEN_LDO_DIG
wxCheckBox * chkSPDUP_LDO_TBB
wxCheckBox * chkSPDUP_LDO_TIA12
wxCheckBox * chkSPDUP_LDO_TIA14
wxCheckBox * chkSPDUP_LDO_TLOB
wxCheckBox * chkSPDUP_LDO_TPAD
wxCheckBox * chkSPDUP_LDO_TXBUF
wxCheckBox * chkSPDUP_LDO_VCOGN
wxCheckBox * chkSPDUP_LDO_DIVSXR
wxCheckBox * chkSPDUP_LDO_DIVSXT
wxCheckBox * chkSPDUP_LDO_AFE
wxCheckBox * chkSPDUP_LDO_CPGN
wxCheckBox * chkSPDUP_LDO_VCOSXR
wxCheckBox * chkSPDUP_LDO_VCOSXT
wxCheckBox * chkSPDUP_LDO_DIG
wxCheckBox * chkSPDUP_LDO_DIGGN
wxCheckBox * chkSPDUP_LDO_DIGSXR
wxCheckBox * chkSPDUP_LDO_DIGSXT
wxCheckBox * chkSPDUP_LDO_DIVGN
wxCheckBox * chkSPDUP_LDO_CPSXR
wxCheckBox * chkSPDUP_LDO_CPSXT
wxCheckBox * chkSPDUP_LDO_LNA12
wxCheckBox * chkSPDUP_LDO_LNA14
wxCheckBox * chkSPDUP_LDO_MXRFE
wxCheckBox * chkSPDUP_LDO_RBB
wxCheckBox * chkSPDUP_LDO_RXBUF
wxCheckBox * chkSPDUP_LDO_SPIBUF
wxCheckBox * chkSPDUP_LDO_DIGIp2
wxCheckBox * chkSPDUP_LDO_DIGIp1
wxCheckBox * chkEN_LOADIMP_LDO_TBB
wxCheckBox * chkEN_LOADIMP_LDO_TIA12
wxCheckBox * chkEN_LOADIMP_LDO_TIA14
wxCheckBox * chkEN_LOADIMP_LDO_TLOB
wxCheckBox * chkEN_LOADIMP_LDO_TPAD
wxCheckBox * chkEN_LOADIMP_LDO_TXBUF
wxCheckBox * chkEN_LOADIMP_LDO_VCOGN
wxCheckBox * chkEN_LOADIMP_LDO_VCOSXR
wxCheckBox * chkEN_LOADIMP_LDO_VCOSXT
wxCheckBox * chkEN_LOADIMP_LDO_AFE
wxCheckBox * chkEN_LOADIMP_LDO_CPGN
wxCheckBox * chkEN_LOADIMP_LDO_DIVSXR
wxCheckBox * chkEN_LOADIMP_LDO_DIVSXT
wxCheckBox * chkEN_LOADIMP_LDO_DIG
wxCheckBox * chkEN_LOADIMP_LDO_DIGGN
wxCheckBox * chkEN_LOADIMP_LDO_DIGSXR
wxCheckBox * chkEN_LOADIMP_LDO_DIGSXT
wxCheckBox * chkEN_LOADIMP_LDO_DIVGN
wxCheckBox * chkEN_LOADIMP_LDO_CPSXR
wxCheckBox * chkEN_LOADIMP_LDO_CPSXT
wxCheckBox * chkEN_LOADIMP_LDO_LNA12
wxCheckBox * chkEN_LOADIMP_LDO_LNA14
wxCheckBox * chkEN_LOADIMP_LDO_MXRFE
wxCheckBox * chkEN_LOADIMP_LDO_RBB
wxCheckBox * chkEN_LOADIMP_LDO_RXBUF
wxCheckBox * chkEN_LOADIMP_LDO_SPIBUF
wxCheckBox * chkEN_LOADIMP_LDO_DIGIp2
wxCheckBox * chkEN_LOADIMP_LDO_DIGIp1
wxPanel * ID_PANEL2
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbRDIV_VCOSXR
wxStaticText * ID_STATICTEXT2
wxComboBox * cmbRDIV_VCOSXT
wxStaticText * ID_STATICTEXT3
wxComboBox * cmbRDIV_TXBUF
wxStaticText * ID_STATICTEXT4
wxComboBox * cmbRDIV_VCOGN
wxStaticText * ID_STATICTEXT5
wxComboBox * cmbRDIV_TLOB
wxStaticText * ID_STATICTEXT6
wxComboBox * cmbRDIV_TPAD
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbRDIV_TIA12
wxStaticText * ID_STATICTEXT8
wxComboBox * cmbRDIV_TIA14
wxStaticText * ID_STATICTEXT9
wxComboBox * cmbRDIV_RXBUF
wxStaticText * ID_STATICTEXT10
wxComboBox * cmbRDIV_TBB
wxStaticText * ID_STATICTEXT11
wxComboBox * cmbRDIV_MXRFE
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbRDIV_RBB
wxStaticText * ID_STATICTEXT13
wxComboBox * cmbRDIV_LNA12
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbRDIV_LNA14
wxStaticText * ID_STATICTEXT15
wxComboBox * cmbRDIV_DIVSXR
wxStaticText * ID_STATICTEXT16
wxComboBox * cmbRDIV_DIVSXT
wxStaticText * ID_STATICTEXT17
wxComboBox * cmbRDIV_DIGSXT
wxStaticText * ID_STATICTEXT18
wxComboBox * cmbRDIV_DIVGN
wxStaticText * ID_STATICTEXT19
wxComboBox * cmbRDIV_DIGGN
wxStaticText * ID_STATICTEXT20
wxComboBox * cmbRDIV_DIGSXR
wxStaticText * ID_STATICTEXT21
wxComboBox * cmbRDIV_CPSXT
wxStaticText * ID_STATICTEXT22
wxComboBox * cmbRDIV_DIG
wxStaticText * ID_STATICTEXT23
wxComboBox * cmbRDIV_CPGN
wxStaticText * ID_STATICTEXT24
wxComboBox * cmbRDIV_CPSXR
wxStaticText * ID_STATICTEXT25
wxComboBox * cmbRDIV_SPIBUF
wxStaticText * ID_STATICTEXT26
wxComboBox * cmbRDIV_AFE
wxStaticText * ID_STATICTEXT27
wxComboBox * cmbRDIV_DIGIp2
wxStaticText * ID_STATICTEXT28
wxComboBox * cmbRDIV_DIGIp1
Additional Inherited Members
Protected Types inherited from pnlLDO_view
enum {
ID_EN_G_LDOP = 2048, ID_EN_G_LDO, ID_EN_LDO_DIVGN, ID_EN_LDO_DIGGN,
ID_EN_LDO_CPGN, ID_EN_LDO_VCOGN, ID_EN_LDO_MXRFE, ID_EN_LDO_LNA14,
ID_EN_LDO_LNA12, ID_EN_LDO_TIA14, ID_EN_LDO_DIVSXT, ID_EN_LDO_DIGSXT,
ID_EN_LDO_CPSXT, ID_EN_LDO_VCOSXT, ID_EN_LDO_DIVSXR, ID_EN_LDO_DIGSXR,
ID_EN_LDO_CPSXR, ID_EN_LDO_VCOSXR, ID_PD_LDO_DIGIp1, ID_PD_LDO_DIGIp2,
ID_EN_LDO_TXBUF, ID_EN_LDO_RXBUF, ID_EN_LDO_TPAD, ID_EN_LDO_TLOB,
ID_PD_LDO_SPIBUF, ID_RDIV_TXBUF, ID_EN_LDO_AFE, ID_EN_LDO_TBB,
ID_EN_LDO_RBB, ID_EN_LDO_TIA12, ID_EN_LDO_DIG, ID_SPDUP_LDO_TBB,
ID_SPDUP_LDO_TIA12, ID_SPDUP_LDO_TIA14, ID_SPDUP_LDO_TLOB, ID_SPDUP_LDO_TPAD,
ID_SPDUP_LDO_TXBUF, ID_SPDUP_LDO_VCOGN, ID_SPDUP_LDO_DIVSXR, ID_SPDUP_LDO_DIVSXT,
ID_SPDUP_LDO_AFE, ID_SPDUP_LDO_CPGN, ID_SPDUP_LDO_VCOSXR, ID_SPDUP_LDO_VCOSXT,
ID_SPDUP_LDO_DIG, ID_SPDUP_LDO_DIGGN, ID_SPDUP_LDO_DIGSXR, ID_SPDUP_LDO_DIGSXT,
ID_SPDUP_LDO_DIVGN, ID_SPDUP_LDO_CPSXR, ID_SPDUP_LDO_CPSXT, ID_SPDUP_LDO_LNA12,
ID_SPDUP_LDO_LNA14, ID_SPDUP_LDO_MXRFE, ID_SPDUP_LDO_RBB, ID_SPDUP_LDO_RXBUF,
ID_SPDUP_LDO_SPIBUF, ID_SPDUP_LDO_DIGIp2, ID_SPDUP_LDO_DIGIp1, ID_EN_LOADIMP_LDO_TBB,
ID_EN_LOADIMP_LDO_TIA12, ID_EN_LOADIMP_LDO_TIA14, ID_EN_LOADIMP_LDO_TLOB, ID_EN_LOADIMP_LDO_TPAD,
ID_EN_LOADIMP_LDO_TXBUF, ID_EN_LOADIMP_LDO_VCOGN, ID_EN_LOADIMP_LDO_VCOSXR, ID_EN_LOADIMP_LDO_VCOSXT,
ID_EN_LOADIMP_LDO_AFE, ID_EN_LOADIMP_LDO_CPGN, ID_EN_LOADIMP_LDO_DIVSXR, ID_EN_LOADIMP_LDO_DIVSXT,
ID_EN_LOADIMP_LDO_DIG, ID_EN_LOADIMP_LDO_DIGGN, ID_EN_LOADIMP_LDO_DIGSXR, ID_EN_LOADIMP_LDO_DIGSXT,
ID_EN_LOADIMP_LDO_DIVGN, ID_EN_LOADIMP_LDO_CPSXR, ID_EN_LOADIMP_LDO_CPSXT, ID_EN_LOADIMP_LDO_LNA12,
ID_EN_LOADIMP_LDO_LNA14, ID_EN_LOADIMP_LDO_MXRFE, ID_EN_LOADIMP_LDO_RBB, ID_EN_LOADIMP_LDO_RXBUF,
ID_EN_LOADIMP_LDO_SPIBUF, ID_EN_LOADIMP_LDO_DIGIp2, ID_EN_LOADIMP_LDO_DIGIp1, ID_RDIV_VCOSXR,
ID_RDIV_VCOSXT, ID_RDIV_VCOGN, ID_RDIV_TLOB, ID_RDIV_TPAD,
ID_RDIV_TIA12, ID_RDIV_TIA14, ID_RDIV_RXBUF, ID_RDIV_TBB,
ID_RDIV_MXRFE, ID_RDIV_RBB, ID_RDIV_LNA12, ID_RDIV_LNA14,
ID_RDIV_DIVSXR, ID_RDIV_DIVSXT, ID_RDIV_DIGSXT, ID_RDIV_DIVGN,
ID_RDIV_DIGGN, ID_RDIV_DIGSXR, ID_RDIV_CPSXT, ID_RDIV_DIG,
ID_RDIV_CPGN, ID_RDIV_CPSXR, ID_RDIV_SPIBUF, ID_RDIV_AFE,
ID_RDIV_DIGIp2, ID_RDIV_DIGIp1
}
Detailed Description
Implementing pnlLDO_view.
Definition at line 17 of file lms7002_pnlLDO_view.h.
Constructor & Destructor Documentation
lms7002_pnlLDO_view::lms7002_pnlLDO_view (wxWindow * parent)
Constructor.
Definition at line 6 of file lms7002_pnlLDO_view.cpp.
lms7002_pnlLDO_view::lms7002_pnlLDO_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 13 of file lms7002_pnlLDO_view.cpp.
References pnlLDO_view::chkEN_G_LDO, pnlLDO_view::chkEN_G_LDOP, pnlLDO_view::chkEN_LDO_AFE, pnlLDO_view::chkEN_LDO_CPGN, pnlLDO_view::chkEN_LDO_CPSXR, pnlLDO_view::chkEN_LDO_CPSXT, pnlLDO_view::chkEN_LDO_DIG, pnlLDO_view::chkEN_LDO_DIGGN, pnlLDO_view::chkEN_LDO_DIGSXR, pnlLDO_view::chkEN_LDO_DIGSXT, pnlLDO_view::chkEN_LDO_DIVGN, pnlLDO_view::chkEN_LDO_DIVSXR, pnlLDO_view::chkEN_LDO_DIVSXT, pnlLDO_view::chkEN_LDO_LNA12, pnlLDO_view::chkEN_LDO_LNA14, pnlLDO_view::chkEN_LDO_MXRFE, pnlLDO_view::chkEN_LDO_RBB, pnlLDO_view::chkEN_LDO_RXBUF, pnlLDO_view::chkEN_LDO_TBB, pnlLDO_view::chkEN_LDO_TIA12, pnlLDO_view::chkEN_LDO_TIA14, pnlLDO_view::chkEN_LDO_TLOB, pnlLDO_view::chkEN_LDO_TPAD, pnlLDO_view::chkEN_LDO_TXBUF, pnlLDO_view::chkEN_LDO_VCOGN, pnlLDO_view::chkEN_LDO_VCOSXR, pnlLDO_view::chkEN_LDO_VCOSXT, pnlLDO_view::chkEN_LOADIMP_LDO_AFE, pnlLDO_view::chkEN_LOADIMP_LDO_CPGN, pnlLDO_view::chkEN_LOADIMP_LDO_CPSXR, pnlLDO_view::chkEN_LOADIMP_LDO_CPSXT, pnlLDO_view::chkEN_LOADIMP_LDO_DIG, pnlLDO_view::chkEN_LOADIMP_LDO_DIGGN, pnlLDO_view::chkEN_LOADIMP_LDO_DIGIp1, pnlLDO_view::chkEN_LOADIMP_LDO_DIGIp2, pnlLDO_view::chkEN_LOADIMP_LDO_DIGSXR, pnlLDO_view::chkEN_LOADIMP_LDO_DIGSXT, pnlLDO_view::chkEN_LOADIMP_LDO_DIVGN, pnlLDO_view::chkEN_LOADIMP_LDO_DIVSXR, pnlLDO_view::chkEN_LOADIMP_LDO_DIVSXT, pnlLDO_view::chkEN_LOADIMP_LDO_LNA12, pnlLDO_view::chkEN_LOADIMP_LDO_LNA14, pnlLDO_view::chkEN_LOADIMP_LDO_MXRFE, pnlLDO_view::chkEN_LOADIMP_LDO_RBB, pnlLDO_view::chkEN_LOADIMP_LDO_RXBUF, pnlLDO_view::chkEN_LOADIMP_LDO_SPIBUF, pnlLDO_view::chkEN_LOADIMP_LDO_TBB, pnlLDO_view::chkEN_LOADIMP_LDO_TIA12, pnlLDO_view::chkEN_LOADIMP_LDO_TIA14, pnlLDO_view::chkEN_LOADIMP_LDO_TLOB, pnlLDO_view::chkEN_LOADIMP_LDO_TPAD, pnlLDO_view::chkEN_LOADIMP_LDO_TXBUF, pnlLDO_view::chkEN_LOADIMP_LDO_VCOGN, pnlLDO_view::chkEN_LOADIMP_LDO_VCOSXR, pnlLDO_view::chkEN_LOADIMP_LDO_VCOSXT, pnlLDO_view::chkPD_LDO_DIGIp1, pnlLDO_view::chkPD_LDO_DIGIp2, pnlLDO_view::chkPD_LDO_SPIBUF, pnlLDO_view::chkSPDUP_LDO_AFE, pnlLDO_view::chkSPDUP_LDO_CPGN, pnlLDO_view::chkSPDUP_LDO_CPSXR, pnlLDO_view::chkSPDUP_LDO_CPSXT, pnlLDO_view::chkSPDUP_LDO_DIG, pnlLDO_view::chkSPDUP_LDO_DIGGN, pnlLDO_view::chkSPDUP_LDO_DIGIp1, pnlLDO_view::chkSPDUP_LDO_DIGIp2, pnlLDO_view::chkSPDUP_LDO_DIGSXR, pnlLDO_view::chkSPDUP_LDO_DIGSXT, pnlLDO_view::chkSPDUP_LDO_DIVGN, pnlLDO_view::chkSPDUP_LDO_DIVSXR, pnlLDO_view::chkSPDUP_LDO_DIVSXT, pnlLDO_view::chkSPDUP_LDO_LNA12, pnlLDO_view::chkSPDUP_LDO_LNA14, pnlLDO_view::chkSPDUP_LDO_MXRFE, pnlLDO_view::chkSPDUP_LDO_RBB, pnlLDO_view::chkSPDUP_LDO_RXBUF, pnlLDO_view::chkSPDUP_LDO_SPIBUF, pnlLDO_view::chkSPDUP_LDO_TBB, pnlLDO_view::chkSPDUP_LDO_TIA12, pnlLDO_view::chkSPDUP_LDO_TIA14, pnlLDO_view::chkSPDUP_LDO_TLOB, pnlLDO_view::chkSPDUP_LDO_TPAD, pnlLDO_view::chkSPDUP_LDO_TXBUF, pnlLDO_view::chkSPDUP_LDO_VCOGN, pnlLDO_view::chkSPDUP_LDO_VCOSXR, pnlLDO_view::chkSPDUP_LDO_VCOSXT, pnlLDO_view::cmbISINK_SPIBUFF, pnlLDO_view::cmbRDIV_AFE, pnlLDO_view::cmbRDIV_CPGN, pnlLDO_view::cmbRDIV_CPSXR, pnlLDO_view::cmbRDIV_CPSXT, pnlLDO_view::cmbRDIV_DIG, pnlLDO_view::cmbRDIV_DIGGN, pnlLDO_view::cmbRDIV_DIGIp1, pnlLDO_view::cmbRDIV_DIGIp2, pnlLDO_view::cmbRDIV_DIGSXR, pnlLDO_view::cmbRDIV_DIGSXT, pnlLDO_view::cmbRDIV_DIVGN, pnlLDO_view::cmbRDIV_DIVSXR, pnlLDO_view::cmbRDIV_DIVSXT, pnlLDO_view::cmbRDIV_LNA12, pnlLDO_view::cmbRDIV_LNA14, pnlLDO_view::cmbRDIV_MXRFE, pnlLDO_view::cmbRDIV_RBB, pnlLDO_view::cmbRDIV_RXBUF, pnlLDO_view::cmbRDIV_SPIBUF, pnlLDO_view::cmbRDIV_TBB, pnlLDO_view::cmbRDIV_TIA12, pnlLDO_view::cmbRDIV_TIA14, pnlLDO_view::cmbRDIV_TLOB, pnlLDO_view::cmbRDIV_TPAD, pnlLDO_view::cmbRDIV_TXBUF, pnlLDO_view::cmbRDIV_VCOGN, pnlLDO_view::cmbRDIV_VCOSXR, pnlLDO_view::cmbRDIV_VCOSXT, EN_G_LDO, EN_G_LDOP, EN_LDO_AFE, EN_LDO_CPGN, EN_LDO_CPSXR, EN_LDO_CPSXT, EN_LDO_DIG, EN_LDO_DIGGN, EN_LDO_DIGSXR, EN_LDO_DIGSXT, EN_LDO_DIVGN, EN_LDO_DIVSXR, EN_LDO_DIVSXT, EN_LDO_LNA12, EN_LDO_LNA14, EN_LDO_MXRFE, EN_LDO_RBB, EN_LDO_RXBUF, EN_LDO_TBB, EN_LDO_TIA12, EN_LDO_TIA14, EN_LDO_TLOB, EN_LDO_TPAD, EN_LDO_TXBUF, EN_LDO_VCOGN, EN_LDO_VCOSXR, EN_LDO_VCOSXT, EN_LOADIMP_LDO_AFE, EN_LOADIMP_LDO_CPGN, EN_LOADIMP_LDO_CPSXR, EN_LOADIMP_LDO_CPSXT, EN_LOADIMP_LDO_DIG, EN_LOADIMP_LDO_DIGGN, EN_LOADIMP_LDO_DIGIp1, EN_LOADIMP_LDO_DIGIp2, EN_LOADIMP_LDO_DIGSXR, EN_LOADIMP_LDO_DIGSXT, EN_LOADIMP_LDO_DIVGN, EN_LOADIMP_LDO_DIVSXR, EN_LOADIMP_LDO_DIVSXT, EN_LOADIMP_LDO_LNA12, EN_LOADIMP_LDO_LNA14, EN_LOADIMP_LDO_MXRFE, EN_LOADIMP_LDO_RBB, EN_LOADIMP_LDO_RXBUF, EN_LOADIMP_LDO_SPIBUF, EN_LOADIMP_LDO_TBB, EN_LOADIMP_LDO_TIA12, EN_LOADIMP_LDO_TIA14, EN_LOADIMP_LDO_TLOB, EN_LOADIMP_LDO_TPAD, EN_LOADIMP_LDO_TXBUF, EN_LOADIMP_LDO_VCOGN, EN_LOADIMP_LDO_VCOSXR, EN_LOADIMP_LDO_VCOSXT, i, LMS7param, PD_LDO_DIGIp1, PD_LDO_DIGIp2, PD_LDO_SPIBUF, RDIV_AFE, RDIV_CPGN, RDIV_CPSXR, RDIV_CPSXT, RDIV_DIG, RDIV_DIGGN, RDIV_DIGIp1, RDIV_DIGIp2, RDIV_DIGSXR, RDIV_DIGSXT, RDIV_DIVGN, RDIV_DIVSXR, RDIV_DIVSXT, RDIV_LNA12, RDIV_LNA14, RDIV_MXRFE, RDIV_RBB, RDIV_RXBUF, RDIV_SPIBUF, RDIV_TBB, RDIV_TIA12, RDIV_TIA14, RDIV_TLOB, RDIV_TPAD, RDIV_TXBUF, RDIV_VCOGN, RDIV_VCOSXR, RDIV_VCOSXT, SPDUP_LDO_AFE, SPDUP_LDO_CPGN, SPDUP_LDO_CPSXR, SPDUP_LDO_CPSXT, SPDUP_LDO_DIG, SPDUP_LDO_DIGGN, SPDUP_LDO_DIGIp1, SPDUP_LDO_DIGIp2, SPDUP_LDO_DIGSXR, SPDUP_LDO_DIGSXT, SPDUP_LDO_DIVGN, SPDUP_LDO_DIVSXR, SPDUP_LDO_DIVSXT, SPDUP_LDO_LNA12, SPDUP_LDO_LNA14, SPDUP_LDO_MXRFE, SPDUP_LDO_RBB, SPDUP_LDO_RXBUF, SPDUP_LDO_SPIBUF, SPDUP_LDO_TBB, SPDUP_LDO_TIA12, SPDUP_LDO_TIA14, SPDUP_LDO_TLOB, SPDUP_LDO_TPAD, SPDUP_LDO_TXBUF, SPDUP_LDO_VCOGN, SPDUP_LDO_VCOSXR, SPDUP_LDO_VCOSXT, temp, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlLDO_view::Initialize (lms_device_t * pControl)
Definition at line 197 of file lms7002_pnlLDO_view.cpp.
References pnlLDO_view::cmbISINK_SPIBUFF, LMS7param, LMS_ReadParam(), lmsControl, and MASK.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlLDO_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlLDO_view.
Definition at line 207 of file lms7002_pnlLDO_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlLDO_view::UpdateGUI ()
Definition at line 223 of file lms7002_pnlLDO_view.cpp.
References lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlLDO_view::lmsControl protected
Definition at line 30 of file lms7002_pnlLDO_view.h.
Referenced by Initialize(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlLDO_view::wndId2Enum protected
Definition at line 31 of file lms7002_pnlLDO_view.h.
Referenced by lms7002_pnlLDO_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlLDO_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlLDO_view.cpp