LimeSuite-UML: lime::LMS7002M_RegistersMap Class Reference
lime::LMS7002M_RegistersMap Class Reference
#include <LMS7002M_RegistersMap.h>
Classes
struct Register
Public Member Functions
LMS7002M_RegistersMap ()
~LMS7002M_RegistersMap ()
uint16_t GetValue (uint8_t channel, uint16_t address) const
void SetValue (uint8_t channel, const uint16_t address, const uint16_t value)
void InitializeDefaultValues (const std::vector< const LMS7Parameter * > parameterList)
uint16_t GetDefaultValue (uint16_t address) const
std::vector< uint16_t > GetUsedAddresses (const uint8_t channel) const
LMS7002M_RegistersMap & operator= (const LMS7002M_RegistersMap &other)
Protected Attributes
std::map< const uint16_t, Register > mChannelA
std::map< const uint16_t, Register > mChannelB
Detailed Description
Definition at line 12 of file LMS7002M_RegistersMap.h.
Constructor & Destructor Documentation
LMS7002M_RegistersMap::LMS7002M_RegistersMap ()
Definition at line 5 of file LMS7002M_RegistersMap.cpp.
LMS7002M_RegistersMap::~LMS7002M_RegistersMap ()
Definition at line 10 of file LMS7002M_RegistersMap.cpp.
Member Function Documentation
uint16_t LMS7002M_RegistersMap::GetDefaultValue (uint16_t address) const
Definition at line 15 of file LMS7002M_RegistersMap.cpp.
References mChannelA.
Referenced by lime::LMS7002M::SetDefaults().
std::vector< uint16_t > LMS7002M_RegistersMap::GetUsedAddresses (const uint8_t channel) const
Definition at line 98 of file LMS7002M_RegistersMap.cpp.
References mChannelA, and mChannelB.
Referenced by lime::LMS7002M::CopyChannelRegisters(), lime::LMS7002M::DownloadAll(), lime::LMS7002M::IsSynced(), lime::LMS7002M::RestoreRegisterMap(), and lime::LMS7002M::UploadAll().
uint16_t LMS7002M_RegistersMap::GetValue (uint8_t channel, uint16_t address) const
Definition at line 81 of file LMS7002M_RegistersMap.cpp.
References mChannelA, and mChannelB.
Referenced by lime::LMS7002M::CopyChannelRegisters(), lime::LMS7002M::GetGFIRCoefficients(), lime::LMS7002M::IsSynced(), lime::LMS7002M::RestoreRegisterMap(), lime::LMS7002M::SPI_read(), lime::LMS7002M::SPI_read_batch(), lime::LMS7002M::SPI_write_batch(), and lime::LMS7002M::UploadAll().
void LMS7002M_RegistersMap::InitializeDefaultValues (const std::vector< const LMS7Parameter * > parameterList)
Definition at line 24 of file LMS7002M_RegistersMap.cpp.
References i, mChannelA, mChannelB, and range.
Referenced by lime::LMS7002M::LMS7002M(), and lime::LMS7002M::ResetChip().
LMS7002M_RegistersMap& lime::LMS7002M_RegistersMap::operator= (const LMS7002M_RegistersMap & other) inline
Definition at line 32 of file LMS7002M_RegistersMap.h.
References mChannelA, and mChannelB.
void LMS7002M_RegistersMap::SetValue (uint8_t channel, const uint16_t address, const uint16_t value)
Definition at line 73 of file LMS7002M_RegistersMap.cpp.
References address, mChannelA, and mChannelB.
Referenced by lime::LMS7002M::CopyChannelRegisters(), lime::LMS7002M::DownloadAll(), lime::LMS7002M::RestoreRegisterMap(), lime::LMS7002M::SPI_read_batch(), and lime::LMS7002M::SPI_write_batch().
Member Data Documentation
std::map<const uint16_t, Register> lime::LMS7002M_RegistersMap::mChannelA protected
Definition at line 40 of file LMS7002M_RegistersMap.h.
Referenced by GetDefaultValue(), GetUsedAddresses(), GetValue(), InitializeDefaultValues(), operator=(), and SetValue().
std::map<const uint16_t, Register> lime::LMS7002M_RegistersMap::mChannelB protected
Definition at line 41 of file LMS7002M_RegistersMap.h.
Referenced by GetUsedAddresses(), GetValue(), InitializeDefaultValues(), operator=(), and SetValue().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_RegistersMap.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002m/LMS7002M_RegistersMap.cpp