LimeSuite-UML: SoapySDR Namespace Reference
SoapySDR Namespace Reference
Classes
class _object
class ArgInfo
class ConverterRegistry
class Device
class ModuleVersion
class Range
class Registry
class SoapySDRArgInfoList
class SoapySDRDoubleList
class SoapySDRKwargs
class SoapySDRKwargsList
class SoapySDRRangeList
class SoapySDRSizeList
class SoapySDRStringList
class SoapySDRUnsignedList
class StreamResult
class SwigPyIterator
Typedefs
typedef SoapySDRLogLevel LogLevel
typedef SoapySDRLogHandler LogHandler
typedef KwargsList(* FindFunction) (const Kwargs &)
typedef for a device enumeration function
typedef Device *(* MakeFunction) (const Kwargs &)
typedef for a device factory function
typedef std::map< std::string, FindFunction > FindFunctions
typedef for a dictionary of find functions
typedef std::map< std::string, MakeFunction > MakeFunctions
typedef for a dictionary of make functions
typedef std::map< std::string, std::string > Kwargs
Typedef for a dictionary of key-value string arguments.
typedef std::vector< Kwargs > KwargsList
Typedef for a list of key-word dictionaries.
typedef std::vector< Range > RangeList
typedef std::vector< ArgInfo > ArgInfoList
Functions
def swig_import_helper ()
def _swig_setattr_nondynamic (self, class_type, name, value, static=1)
def _swig_setattr (self, class_type, name, value)
def _swig_getattr (self, class_type, name)
def _swig_repr (self)
def KwargsFromString (args)
def KwargsToString (args)
def SoapySDR_errToStr (args)
def SoapySDR_getAPIVersion ()
def SoapySDR_getABIVersion ()
def SoapySDR_getLibVersion ()
def SoapySDR_formatToSize (args)
def SoapySDR_log (args)
def SoapySDR_setLogLevel (args)
def errToStr (args)
def getAPIVersion ()
def getABIVersion ()
def getLibVersion ()
def getRootPath (void)
Query the root installation path.
def listSearchPaths ()
def listModules (args)
def loadModule (args)
def getLoaderResult (args)
def getModuleVersion (args)
def unloadModule (args)
def loadModules ()
def formatToSize (args)
def ticksToTimeNs (args)
def timeNsToTicks (args)
def log (args)
def setLogLevel (args)
def Device_enumerate (args)
def Device_make (args)
def Device_unmake (args)
def extractBuffPointer (buff)
int32_t F32toS32 (float from)
float S32toF32 (int32_t from)
int16_t F32toS16 (float from)
float S16toF32 (int16_t from)
int8_t F32toS8 (float from)
float S8toF32 (int8_t from)
int32_t U32toS32 (uint32_t from)
uint32_t S32toU32 (int32_t from)
int16_t U16toS16 (uint16_t from)
uint16_t S16toU16 (int16_t from)
int8_t U8toS8 (uint8_t from)
uint8_t S8toU8 (int8_t from)
int16_t S32toS16 (int32_t from)
int32_t S16toS32 (int16_t from)
int8_t S16toS8 (int16_t from)
int16_t S8toS16 (int8_t from)
uint32_t F32toU32 (float from)
float U32toF32 (uint32_t from)
uint16_t F32toU16 (float from)
float U16toF32 (uint16_t from)
uint8_t F32toU8 (float from)
float U8toF32 (uint8_t from)
uint16_t S32toU16 (int32_t from)
int32_t U16toS32 (uint16_t from)
uint8_t S32toU8 (int32_t from)
int32_t U8toS32 (uint8_t from)
uint8_t S16toU8 (int16_t from)
int16_t U8toS16 (uint8_t from)
uint16_t S8toU16 (int8_t from)
int8_t U16toS8 (uint16_t from)
SOAPY_SDR_API const char * errToStr (const int errorCode)
SOAPY_SDR_API size_t formatToSize (const std::string &format)
SOAPY_SDR_API void log (const LogLevel logLevel, const std::string &message)
SOAPY_SDR_API void vlogf (const SoapySDRLogLevel logLevel, const char *format, va_list argList)
static void logf (const SoapySDRLogLevel logLevel, const char *format,...)
SOAPY_SDR_API void registerLogHandler (const LogHandler &handler)
SOAPY_SDR_API void setLogLevel (const LogLevel logLevel)
SOAPY_SDR_API std::vector< std::string > listModules (void)
SOAPY_SDR_API std::vector< std::string > listModules (const std::string &path)
SOAPY_SDR_API std::string loadModule (const std::string &path)
SOAPY_SDR_API Kwargs getLoaderResult (const std::string &path)
SOAPY_SDR_API std::string getModuleVersion (const std::string &path)
SOAPY_SDR_API std::string unloadModule (const std::string &path)
static long long ticksToTimeNs (const long long ticks, const double rate)
static long long timeNsToTicks (const long long timeNs, const double rate)
SOAPY_SDR_API Kwargs KwargsFromString (const std::string &markup)
SOAPY_SDR_API std::string KwargsToString (const Kwargs &args)
Variables
_SoapySDR = swig_import_helper()
int _newclass = 0
SwigPyIterator_swigregister = _SoapySDR.SwigPyIterator_swigregister
KwargsFromString = _SoapySDR.KwargsFromString
KwargsToString = _SoapySDR.KwargsToString
Range_swigregister = _SoapySDR.Range_swigregister
ArgInfo_swigregister = _SoapySDR.ArgInfo_swigregister
SoapySDRUnsignedList_swigregister = _SoapySDR.SoapySDRUnsignedList_swigregister
SoapySDRKwargs_swigregister = _SoapySDR.SoapySDRKwargs_swigregister
SoapySDRKwargsList_swigregister = _SoapySDR.SoapySDRKwargsList_swigregister
SoapySDRArgInfoList_swigregister = _SoapySDR.SoapySDRArgInfoList_swigregister
SoapySDRStringList_swigregister = _SoapySDR.SoapySDRStringList_swigregister
SoapySDRRangeList_swigregister = _SoapySDR.SoapySDRRangeList_swigregister
SoapySDRSizeList_swigregister = _SoapySDR.SoapySDRSizeList_swigregister
SoapySDRDoubleList_swigregister = _SoapySDR.SoapySDRDoubleList_swigregister
StreamResult_swigregister = _SoapySDR.StreamResult_swigregister
SOAPY_SDR_TX = _SoapySDR.SOAPY_SDR_TX
SOAPY_SDR_RX = _SoapySDR.SOAPY_SDR_RX
SOAPY_SDR_END_BURST = _SoapySDR.SOAPY_SDR_END_BURST
SOAPY_SDR_HAS_TIME = _SoapySDR.SOAPY_SDR_HAS_TIME
SOAPY_SDR_END_ABRUPT = _SoapySDR.SOAPY_SDR_END_ABRUPT
SOAPY_SDR_ONE_PACKET = _SoapySDR.SOAPY_SDR_ONE_PACKET
SOAPY_SDR_MORE_FRAGMENTS = _SoapySDR.SOAPY_SDR_MORE_FRAGMENTS
SOAPY_SDR_WAIT_TRIGGER = _SoapySDR.SOAPY_SDR_WAIT_TRIGGER
SoapySDR_errToStr = _SoapySDR.SoapySDR_errToStr
SOAPY_SDR_TIMEOUT = _SoapySDR.SOAPY_SDR_TIMEOUT
SOAPY_SDR_STREAM_ERROR = _SoapySDR.SOAPY_SDR_STREAM_ERROR
SOAPY_SDR_CORRUPTION = _SoapySDR.SOAPY_SDR_CORRUPTION
SOAPY_SDR_OVERFLOW = _SoapySDR.SOAPY_SDR_OVERFLOW
SOAPY_SDR_NOT_SUPPORTED = _SoapySDR.SOAPY_SDR_NOT_SUPPORTED
SOAPY_SDR_TIME_ERROR = _SoapySDR.SOAPY_SDR_TIME_ERROR
SOAPY_SDR_UNDERFLOW = _SoapySDR.SOAPY_SDR_UNDERFLOW
SOAPY_SDR_API_VERSION = _SoapySDR.SOAPY_SDR_API_VERSION
SOAPY_SDR_ABI_VERSION = _SoapySDR.SOAPY_SDR_ABI_VERSION
SoapySDR_getAPIVersion = _SoapySDR.SoapySDR_getAPIVersion
SoapySDR_getABIVersion = _SoapySDR.SoapySDR_getABIVersion
SoapySDR_getLibVersion = _SoapySDR.SoapySDR_getLibVersion
SOAPY_SDR_CF64 = _SoapySDR.SOAPY_SDR_CF64
SOAPY_SDR_CF32 = _SoapySDR.SOAPY_SDR_CF32
SOAPY_SDR_CS32 = _SoapySDR.SOAPY_SDR_CS32
SOAPY_SDR_CU32 = _SoapySDR.SOAPY_SDR_CU32
SOAPY_SDR_CS16 = _SoapySDR.SOAPY_SDR_CS16
SOAPY_SDR_CU16 = _SoapySDR.SOAPY_SDR_CU16
SOAPY_SDR_CS12 = _SoapySDR.SOAPY_SDR_CS12
SOAPY_SDR_CU12 = _SoapySDR.SOAPY_SDR_CU12
SOAPY_SDR_CS8 = _SoapySDR.SOAPY_SDR_CS8
SOAPY_SDR_CU8 = _SoapySDR.SOAPY_SDR_CU8
SOAPY_SDR_CS4 = _SoapySDR.SOAPY_SDR_CS4
SOAPY_SDR_CU4 = _SoapySDR.SOAPY_SDR_CU4
SOAPY_SDR_F64 = _SoapySDR.SOAPY_SDR_F64
SOAPY_SDR_F32 = _SoapySDR.SOAPY_SDR_F32
SOAPY_SDR_S32 = _SoapySDR.SOAPY_SDR_S32
SOAPY_SDR_U32 = _SoapySDR.SOAPY_SDR_U32
SOAPY_SDR_S16 = _SoapySDR.SOAPY_SDR_S16
SOAPY_SDR_U16 = _SoapySDR.SOAPY_SDR_U16
SOAPY_SDR_S8 = _SoapySDR.SOAPY_SDR_S8
SOAPY_SDR_U8 = _SoapySDR.SOAPY_SDR_U8
SoapySDR_formatToSize = _SoapySDR.SoapySDR_formatToSize
SOAPY_SDR_FATAL = _SoapySDR.SOAPY_SDR_FATAL
SOAPY_SDR_CRITICAL = _SoapySDR.SOAPY_SDR_CRITICAL
SOAPY_SDR_ERROR = _SoapySDR.SOAPY_SDR_ERROR
SOAPY_SDR_WARNING = _SoapySDR.SOAPY_SDR_WARNING
SOAPY_SDR_NOTICE = _SoapySDR.SOAPY_SDR_NOTICE
SOAPY_SDR_INFO = _SoapySDR.SOAPY_SDR_INFO
SOAPY_SDR_DEBUG = _SoapySDR.SOAPY_SDR_DEBUG
SOAPY_SDR_TRACE = _SoapySDR.SOAPY_SDR_TRACE
SOAPY_SDR_SSI = _SoapySDR.SOAPY_SDR_SSI
SoapySDR_log = _SoapySDR.SoapySDR_log
SoapySDR_setLogLevel = _SoapySDR.SoapySDR_setLogLevel
errToStr = _SoapySDR.errToStr
getAPIVersion = _SoapySDR.getAPIVersion
getABIVersion = _SoapySDR.getABIVersion
getLibVersion = _SoapySDR.getLibVersion
getRootPath = _SoapySDR.getRootPath
Query the root installation path.
listSearchPaths = _SoapySDR.listSearchPaths
listModules = _SoapySDR.listModules
loadModule = _SoapySDR.loadModule
getLoaderResult = _SoapySDR.getLoaderResult
getModuleVersion = _SoapySDR.getModuleVersion
unloadModule = _SoapySDR.unloadModule
loadModules = _SoapySDR.loadModules
ModuleVersion_swigregister = _SoapySDR.ModuleVersion_swigregister
formatToSize = _SoapySDR.formatToSize
ticksToTimeNs = _SoapySDR.ticksToTimeNs
timeNsToTicks = _SoapySDR.timeNsToTicks
log = _SoapySDR.log
setLogLevel = _SoapySDR.setLogLevel
Device_swigregister = _SoapySDR.Device_swigregister
Device_enumerate = _SoapySDR.Device_enumerate
Device_make = _SoapySDR.Device_make
Device_unmake = _SoapySDR.Device_unmake
__all__ = list()
_Device = Device
const uint32_t U32_ZERO_OFFSET = uint32_t(1<<31)
const uint16_t U16_ZERO_OFFSET = uint16_t(1<<15)
const uint8_t U8_ZERO_OFFSET = uint8_t(1<<7)
const uint32_t S32_FULL_SCALE = (U32_ZERO_OFFSET-1)
const uint16_t S16_FULL_SCALE = (U16_ZERO_OFFSET-1)
const uint8_t S8_FULL_SCALE = (U8_ZERO_OFFSET-1)
Typedef Documentation
typedef std::vector<ArgInfo> SoapySDR.ArgInfoList
Typedef for a list of Argument infos.
Definition at line 127 of file Types.hpp.
typedef KwargsList(* SoapySDR.FindFunction) (const Kwargs &)
typedef for a device enumeration function
Definition at line 26 of file Registry.hpp.
typedef std::map<std::string, FindFunction> SoapySDR.FindFunctions
typedef for a dictionary of find functions
Definition at line 32 of file Registry.hpp.
typedef std::map<std::string, std::string> SoapySDR.Kwargs
Typedef for a dictionary of key-value string arguments.
Definition at line 22 of file Types.hpp.
typedef std::vector<Kwargs> SoapySDR.KwargsList
Typedef for a list of key-word dictionaries.
Definition at line 37 of file Types.hpp.
typedef SoapySDRLogHandler SoapySDR.LogHandler
Typedef for the registered log handler function.
Definition at line 54 of file Logger.hpp.
typedef SoapySDRLogLevel SoapySDR.LogLevel
Definition at line 21 of file Logger.hpp.
typedef Device*(* SoapySDR.MakeFunction) (const Kwargs &)
typedef for a device factory function
Definition at line 29 of file Registry.hpp.
typedef std::map<std::string, MakeFunction> SoapySDR.MakeFunctions
typedef for a dictionary of make functions
Definition at line 35 of file Registry.hpp.
typedef std::vector<Range> SoapySDR.RangeList
Typedef for a list of min/max range pairs. Overall minimum: rl.front().minimum(); Overall maximum: rl.back().maximum();
Definition at line 70 of file Types.hpp.
Function Documentation
def SoapySDR._swig_getattr (self, class_type, name) private
Definition at line 53 of file SoapySDR.py.
def SoapySDR._swig_repr (self) private
Definition at line 59 of file SoapySDR.py.
def SoapySDR._swig_setattr (self, class_type, name, value) private
Definition at line 50 of file SoapySDR.py.
References _swig_setattr_nondynamic().
def SoapySDR._swig_setattr_nondynamic (self, class_type, name, value, static = 1) private
Definition at line 37 of file SoapySDR.py.
Referenced by _swig_setattr().
def SoapySDR.Device_enumerate (args)
Definition at line 883 of file SoapySDR.py.
References Device_enumerate.
def SoapySDR.Device_make (args)
Definition at line 887 of file SoapySDR.py.
References Device_make.
def SoapySDR.Device_unmake (args)
Definition at line 891 of file SoapySDR.py.
References Device_unmake.
SOAPY_SDR_API const char* SoapySDR::errToStr (const int errorCode)
Convert a error code to a string for printing purposes. If the error code is unrecognized, errToStr returns "UNKNOWN".
Parameters
errorCode a negative integer return code
Returns
a pointer to a string representing the error
def SoapySDR.errToStr (args)
Definition at line 667 of file SoapySDR.py.
References errToStr.
def SoapySDR.extractBuffPointer (buff)
Definition at line 905 of file SoapySDR.py.
References int().
Referenced by SoapySDR.Device.readStream(), and SoapySDR.Device.writeStream().
int16_t SoapySDR::F32toS16 (float from) inline
Definition at line 40 of file ConverterPrimatives.hpp.
Referenced by F32toU16(), genericCF32toCS16(), and genericF32toS16().
int32_t SoapySDR::F32toS32 (float from) inline
Conversion primatives for converting real values between Soapy Formats.
Parameters
from the value to convert from
Returns
the converted value
Definition at line 33 of file ConverterPrimatives.hpp.
Referenced by F32toU32().
int8_t SoapySDR::F32toS8 (float from) inline
Definition at line 47 of file ConverterPrimatives.hpp.
Referenced by F32toU8(), genericCF32toCS8(), and genericF32toS8().
uint16_t SoapySDR::F32toU16 (float from) inline
Definition at line 108 of file ConverterPrimatives.hpp.
References F32toS16(), and S16toU16().
Referenced by genericCF32toCU16(), and genericF32toU16().
uint32_t SoapySDR::F32toU32 (float from) inline
Definition at line 101 of file ConverterPrimatives.hpp.
References F32toS32(), and S32toU32().
uint8_t SoapySDR::F32toU8 (float from) inline
Definition at line 115 of file ConverterPrimatives.hpp.
References F32toS8(), and S8toU8().
Referenced by genericCF32toCU8(), and genericF32toU8().
SOAPY_SDR_API size_t SoapySDR::formatToSize (const std::string & format)
Get the size of a single element in the specified format.
Parameters
format a supported format string
Returns
the size of an element in bytes
def SoapySDR.formatToSize (args)
Definition at line 730 of file SoapySDR.py.
References formatToSize.
def SoapySDR.getABIVersion (void)
Get the ABI version string that the library was built against. A client can compare SOAPY_SDR_ABI_VERSION to getABIVersion() to check for ABI incompatibility before using the library. If the values are not equal then the client code was compiled against a different ABI than the library.
Definition at line 675 of file SoapySDR.py.
References getABIVersion.
def SoapySDR.getAPIVersion (void)
Get the SoapySDR library API version as a string. The format of the version string is major.minor.increment, where the digits are taken directly from SOAPY_SDR_API_VERSION.
Definition at line 671 of file SoapySDR.py.
References getAPIVersion.
def SoapySDR.getLibVersion (void)
Get the library version and build information string. The format of the version string is major.minor.patch-buildInfo. This function is commonly used to identify the software back-end to the user for command-line utilities and graphical applications.
Definition at line 679 of file SoapySDR.py.
References getLibVersion.
SOAPY_SDR_API Kwargs SoapySDR::getLoaderResult (const std::string & path)
List all registration loader errors for a given module path. The resulting dictionary contains all registry entry names provided by the specified module. The value of each entry is an error message string or empty on successful load.
Parameters
path the path to a specific module file
Returns
a dictionary of registry names to error messages
def SoapySDR.getLoaderResult (args)
Definition at line 699 of file SoapySDR.py.
References getLoaderResult.
SOAPY_SDR_API std::string SoapySDR::getModuleVersion (const std::string & path)
Get a version string for the specified module. Modules may optionally provide version strings.
Parameters
path the path to a specific module file
Returns
a version string or empty if no version provided
def SoapySDR.getModuleVersion (args)
Definition at line 703 of file SoapySDR.py.
References getModuleVersion.
def SoapySDR.getRootPath ()
Query the root installation path.
Definition at line 683 of file SoapySDR.py.
References getRootPath.
SOAPY_SDR_API Kwargs SoapySDR::KwargsFromString (const std::string & markup)
Convert a markup string to a key-value map. The markup format is: "key0=value0, key1=value1"
def SoapySDR.KwargsFromString (args)
Definition at line 102 of file SoapySDR.py.
References KwargsFromString.
SOAPY_SDR_API std::string SoapySDR::KwargsToString (const Kwargs & args)
Convert a key-value map to a markup string. The markup format is: "key0=value0, key1=value1"
def SoapySDR.KwargsToString (args)
Definition at line 106 of file SoapySDR.py.
References KwargsToString.
SOAPY_SDR_API std::vector<std::string> SoapySDR::listModules (void)
List all modules found in default path.
Returns
a list of file paths to loadable modules
SOAPY_SDR_API std::vector<std::string> SoapySDR::listModules (const std::string & path)
List all modules found in the given path.
Parameters
path a directory on the system
Returns
a list of file paths to loadable modules
def SoapySDR.listModules (args)
Definition at line 691 of file SoapySDR.py.
References listModules.
def SoapySDR.listSearchPaths (void)
The list of paths automatically searched by loadModules().
Returns
a list of automatically searched file paths
Definition at line 687 of file SoapySDR.py.
References listSearchPaths.
SOAPY_SDR_API std::string SoapySDR::loadModule (const std::string & path)
Load a single module given its file system path.
Parameters
path the path to a specific module file
Returns
an error message, empty on success
def SoapySDR.loadModule (args)
Definition at line 695 of file SoapySDR.py.
References loadModule.
def SoapySDR.loadModules (void)
Load the support modules installed on this system. This call will only actually perform the load once. Subsequent calls are a NOP.
Definition at line 711 of file SoapySDR.py.
References loadModules.
SOAPY_SDR_API void SoapySDR::log (const LogLevel logLevel, const std::string & message)
Send a message to the registered logger.
Parameters
logLevel a possible logging level
message a logger message string
def SoapySDR.log (args)
Definition at line 742 of file SoapySDR.py.
References log.
static void SoapySDR::logf (const SoapySDRLogLevel logLevel, const char * format, ...) inline static
Send a message to the registered logger.
Parameters
logLevel a possible logging level
format a printf style format string
Definition at line 43 of file Logger.hpp.
References vlogf().
Referenced by SoapySDR::ConverterRegistry::ConverterRegistry(), SoapyLMS7::getFrequencyArgsInfo(), getModuleVersions(), SoapyLMS7::readStream(), searchModulePath(), SoapyLMS7::setAntenna(), SoapyLMS7::setBandwidth(), SoapyLMS7::setGain(), SoapyLMS7::SoapyLMS7(), SoapyLMS7::writeSetting(), and SoapyLMS7::writeStream().
void SoapySDR::registerLogHandler (const LogHandler & handler)
Register a new system log handler. Platforms should call this to replace the default stdio handler.
Definition at line 16 of file Logger.cpp.
References setLogLevel, SoapySDR_registerLogHandler(), and SoapySDR_setLogLevel.
float SoapySDR::S16toF32 (int16_t from) inline
Definition at line 43 of file ConverterPrimatives.hpp.
References S16_FULL_SCALE.
Referenced by genericCS16toCF32(), genericS16toF32(), and U16toF32().
int32_t SoapySDR::S16toS32 (int16_t from) inline
Definition at line 86 of file ConverterPrimatives.hpp.
Referenced by U16toS32(), and U8toS32().
int8_t SoapySDR::S16toS8 (int16_t from) inline
Definition at line 90 of file ConverterPrimatives.hpp.
Referenced by genericCS16toCS8(), genericS16toS8(), S16toU8(), S32toU8(), and U16toS8().
uint16_t SoapySDR::S16toU16 (int16_t from) inline
Definition at line 69 of file ConverterPrimatives.hpp.
References U16_ZERO_OFFSET.
Referenced by F32toU16(), genericCS16toCU16(), genericS16toU16(), S32toU16(), and S8toU16().
uint8_t SoapySDR::S16toU8 (int16_t from) inline
Definition at line 138 of file ConverterPrimatives.hpp.
References S16toS8(), and S8toU8().
Referenced by genericCS16toCU8(), and genericS16toU8().
float SoapySDR::S32toF32 (int32_t from) inline
Definition at line 36 of file ConverterPrimatives.hpp.
References S32_FULL_SCALE.
Referenced by U32toF32().
int16_t SoapySDR::S32toS16 (int32_t from) inline
Definition at line 83 of file ConverterPrimatives.hpp.
Referenced by S32toU16(), and S32toU8().
uint16_t SoapySDR::S32toU16 (int32_t from) inline
Definition at line 124 of file ConverterPrimatives.hpp.
References S16toU16(), and S32toS16().
uint32_t SoapySDR::S32toU32 (int32_t from) inline
Definition at line 61 of file ConverterPrimatives.hpp.
References U32_ZERO_OFFSET.
Referenced by F32toU32().
uint8_t SoapySDR::S32toU8 (int32_t from) inline
Definition at line 131 of file ConverterPrimatives.hpp.
References S16toS8(), S32toS16(), and S8toU8().
float SoapySDR::S8toF32 (int8_t from) inline
Definition at line 50 of file ConverterPrimatives.hpp.
References S8_FULL_SCALE.
Referenced by genericCS8toCF32(), genericS8toF32(), and U8toF32().
int16_t SoapySDR::S8toS16 (int8_t from) inline
Definition at line 93 of file ConverterPrimatives.hpp.
Referenced by genericCS8toCS16(), genericS8toS16(), S8toU16(), U8toS16(), and U8toS32().
uint16_t SoapySDR::S8toU16 (int8_t from) inline
Definition at line 145 of file ConverterPrimatives.hpp.
References S16toU16(), and S8toS16().
Referenced by genericCS8toCU16(), and genericS8toU16().
uint8_t SoapySDR::S8toU8 (int8_t from) inline
Definition at line 77 of file ConverterPrimatives.hpp.
References U8_ZERO_OFFSET.
Referenced by F32toU8(), genericCS8toCU8(), genericS8toU8(), S16toU8(), and S32toU8().
SOAPY_SDR_API void SoapySDR::setLogLevel (const LogLevel logLevel)
Set the log level threshold. Log messages with lower priority are dropped.
def SoapySDR.setLogLevel (args)
Definition at line 746 of file SoapySDR.py.
References setLogLevel.
def SoapySDR.SoapySDR_errToStr (args)
Definition at line 601 of file SoapySDR.py.
References SoapySDR_errToStr.
def SoapySDR.SoapySDR_formatToSize (args)
Definition at line 646 of file SoapySDR.py.
References SoapySDR_formatToSize.
def SoapySDR.SoapySDR_getABIVersion (void)
Get the ABI version string that the library was built against. A client can compare SOAPY_SDR_ABI_VERSION to getABIVersion() to check for ABI incompatibility before using the library. If the values are not equal then the client code was compiled against a different ABI than the library.
Definition at line 618 of file SoapySDR.py.
Referenced by SoapySDR_getABIVersion().
def SoapySDR.SoapySDR_getAPIVersion (void)
Get the SoapySDR library API version as a string. The format of the version string is major.minor.increment, where the digits are taken directly from SOAPY_SDR_API_VERSION.
Definition at line 614 of file SoapySDR.py.
Referenced by SoapySDR_getAPIVersion().
def SoapySDR.SoapySDR_getLibVersion (void)
Get the library version and build information string. The format of the version string is major.minor.patch-buildInfo. This function is commonly used to identify the software back-end to the user for command-line utilities and graphical applications.
Definition at line 622 of file SoapySDR.py.
Referenced by SoapySDR_getLibVersion().
def SoapySDR.SoapySDR_log (args)
Definition at line 659 of file SoapySDR.py.
References SoapySDR_log.
def SoapySDR.SoapySDR_setLogLevel (args)
Definition at line 663 of file SoapySDR.py.
References SoapySDR_setLogLevel.
def SoapySDR.swig_import_helper ()
Definition at line 13 of file SoapySDR.py.
static long long SoapySDR::ticksToTimeNs (const long long ticks, const double rate) inline static
Convert a tick count into a time in nanoseconds using the tick rate.
Parameters
ticks a integer tick count
rate the ticks per second
Returns
the time in nanoseconds
def SoapySDR.ticksToTimeNs (args)
Definition at line 734 of file SoapySDR.py.
References ticksToTimeNs.
static long long SoapySDR::timeNsToTicks (const long long timeNs, const double rate) inline static
Convert a time in nanoseconds into a tick count using the tick rate.
Parameters
timeNs time in nanoseconds
rate the ticks per second
Returns
the integer tick count
def SoapySDR.timeNsToTicks (args)
Definition at line 738 of file SoapySDR.py.
References timeNsToTicks.
float SoapySDR::U16toF32 (uint16_t from) inline
Definition at line 111 of file ConverterPrimatives.hpp.
References S16toF32(), and U16toS16().
Referenced by genericCU16toCF32(), and genericU16toF32().
int16_t SoapySDR::U16toS16 (uint16_t from) inline
Definition at line 65 of file ConverterPrimatives.hpp.
Referenced by genericCU16toCS16(), genericU16toS16(), U16toF32(), U16toS32(), and U16toS8().
int32_t SoapySDR::U16toS32 (uint16_t from) inline
Definition at line 127 of file ConverterPrimatives.hpp.
References S16toS32(), and U16toS16().
int8_t SoapySDR::U16toS8 (uint16_t from) inline
Definition at line 148 of file ConverterPrimatives.hpp.
References S16toS8(), and U16toS16().
Referenced by genericCU16toCS8(), and genericU16toS8().
float SoapySDR::U32toF32 (uint32_t from) inline
Definition at line 104 of file ConverterPrimatives.hpp.
References S32toF32(), and U32toS32().
int32_t SoapySDR::U32toS32 (uint32_t from) inline
Definition at line 57 of file ConverterPrimatives.hpp.
Referenced by U32toF32().
float SoapySDR::U8toF32 (uint8_t from) inline
Definition at line 118 of file ConverterPrimatives.hpp.
References S8toF32(), and U8toS8().
Referenced by genericCU8toCF32(), and genericU8toF32().
int16_t SoapySDR::U8toS16 (uint8_t from) inline
Definition at line 141 of file ConverterPrimatives.hpp.
References S8toS16(), and U8toS8().
Referenced by genericCU8toCS16(), and genericU8toS16().
int32_t SoapySDR::U8toS32 (uint8_t from) inline
Definition at line 134 of file ConverterPrimatives.hpp.
References S16toS32(), S8toS16(), and U8toS8().
int8_t SoapySDR::U8toS8 (uint8_t from) inline
Definition at line 73 of file ConverterPrimatives.hpp.
Referenced by genericCU8toCS8(), genericU8toS8(), U8toF32(), U8toS16(), and U8toS32().
SOAPY_SDR_API std::string SoapySDR::unloadModule (const std::string & path)
Unload a module that was loaded with loadModule().
Parameters
path the path to a specific module file
Returns
an error message, empty on success
def SoapySDR.unloadModule (args)
Definition at line 707 of file SoapySDR.py.
References unloadModule.
void SoapySDR::vlogf (const SoapySDRLogLevel logLevel, const char * format, va_list argList)
Send a message to the registered logger.
Parameters
logLevel a possible logging level
format a printf style format string
argList an argument list for the formatter
Definition at line 11 of file Logger.cpp.
References SoapySDR_vlogf().
Referenced by logf().
Variable Documentation
SoapySDR.__all__ = list() private
Definition at line 895 of file SoapySDR.py.
SoapySDR._Device = Device private
Definition at line 900 of file SoapySDR.py.
int SoapySDR._newclass = 0 private
Definition at line 69 of file SoapySDR.py.
SoapySDR._SoapySDR = swig_import_helper() private
Definition at line 28 of file SoapySDR.py.
SoapySDR.ArgInfo_swigregister = _SoapySDR.ArgInfo_swigregister
Definition at line 175 of file SoapySDR.py.
SoapySDR.Device_enumerate = _SoapySDR.Device_enumerate
Definition at line 885 of file SoapySDR.py.
Referenced by Device_enumerate().
SoapySDR.Device_make = _SoapySDR.Device_make
Definition at line 889 of file SoapySDR.py.
Referenced by Device_make().
SoapySDR.Device_swigregister = _SoapySDR.Device_swigregister
Definition at line 880 of file SoapySDR.py.
SoapySDR.Device_unmake = _SoapySDR.Device_unmake
Definition at line 893 of file SoapySDR.py.
Referenced by Device_unmake().
const char * SoapySDR.errToStr = _SoapySDR.errToStr
Definition at line 669 of file SoapySDR.py.
Referenced by _wrap_errToStr(), errToStr(), and runRateTestStreamLoop().
size_t SoapySDR.formatToSize = _SoapySDR.formatToSize
Definition at line 732 of file SoapySDR.py.
Referenced by _wrap_formatToSize(), formatToSize(), SoapyLMS7.setupStream(), and SoapySDRRateTest().
std.string SoapySDR.getABIVersion = _SoapySDR.getABIVersion
Get the ABI version string that the library was built against. A client can compare SOAPY_SDR_ABI_VERSION to getABIVersion() to check for ABI incompatibility before using the library. If the values are not equal then the client code was compiled against a different ABI than the library.
Definition at line 677 of file SoapySDR.py.
Referenced by _wrap_getABIVersion(), getABIVersion(), printInfo(), searchModulePath(), and SoapySDR_getABIVersion().
std.string SoapySDR.getAPIVersion = _SoapySDR.getAPIVersion
Get the SoapySDR library API version as a string. The format of the version string is major.minor.increment, where the digits are taken directly from SOAPY_SDR_API_VERSION.
Definition at line 673 of file SoapySDR.py.
Referenced by _wrap_getAPIVersion(), getAPIVersion(), printInfo(), and SoapySDR_getAPIVersion().
std.string SoapySDR.getLibVersion = _SoapySDR.getLibVersion
Get the library version and build information string. The format of the version string is major.minor.patch-buildInfo. This function is commonly used to identify the software back-end to the user for command-line utilities and graphical applications.
Definition at line 681 of file SoapySDR.py.
Referenced by _wrap_getLibVersion(), getLibVersion(), printInfo(), and SoapySDR_getLibVersion().
SoapySDR.Kwargs SoapySDR.getLoaderResult = _SoapySDR.getLoaderResult
Definition at line 701 of file SoapySDR.py.
Referenced by _wrap_getLoaderResult(), getLoaderResult(), getModuleVersions(), and SoapySDR_getLoaderResult().
std.string SoapySDR.getModuleVersion = _SoapySDR.getModuleVersion
Definition at line 705 of file SoapySDR.py.
Referenced by _wrap_getModuleVersion(), getModuleVersion(), getModuleVersions(), printInfo(), and SoapySDR_getModuleVersion().
std.string SoapySDR.getRootPath = _SoapySDR.getRootPath
Query the root installation path.
Definition at line 685 of file SoapySDR.py.
Referenced by _wrap_getRootPath(), getEnvImpl(), getRootPath(), printInfo(), searchModulePath(), set(), and SoapySDR_getRootPath().
SoapySDR.Kwargs SoapySDR.KwargsFromString = _SoapySDR.KwargsFromString
Definition at line 104 of file SoapySDR.py.
Referenced by _wrap_KwargsFromString(), getDeviceCounts(), getDeviceFromTable(), gr::radar::gpio_source_s_impl.gpio_source_s_impl(), KwargsFromString(), main(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRKwargs_fromString(), SoapySDRRateTest(), and trim().
std.string SoapySDR.KwargsToString = _SoapySDR.KwargsToString
Definition at line 108 of file SoapySDR.py.
Referenced by _wrap_KwargsToString(), checkArgsInLhs__(), findDevices(), KwargsToString(), main(), gr::radar::soapysdr_echotimer_impl.soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl.soapysdr_echotimer_stretch_impl(), SoapySDRKwargs_toString(), and trim().
std.vector< std.string > SoapySDR.listModules = _SoapySDR.listModules
Definition at line 693 of file SoapySDR.py.
Referenced by _wrap_listModules__SWIG_0(), _wrap_listModules__SWIG_1(), getModuleVersions(), listModules(), printInfo(), searchModulePath(), SoapySDR_listModules(), and SoapySDR_listModulesPath().
std.vector< std.string > SoapySDR.listSearchPaths = _SoapySDR.listSearchPaths
The list of paths automatically searched by loadModules().
Returns
a list of automatically searched file paths
Definition at line 689 of file SoapySDR.py.
Referenced by _wrap_listSearchPaths(), listSearchPaths(), printInfo(), searchModulePath(), and SoapySDR_listSearchPaths().
std.string SoapySDR.loadModule = _SoapySDR.loadModule
Definition at line 697 of file SoapySDR.py.
Referenced by _wrap_loadModule(), getModuleVersions(), loadModule(), printInfo(), and SoapySDR_loadModule().
void SoapySDR.loadModules = _SoapySDR.loadModules
Load the support modules installed on this system. This call will only actually perform the load once. Subsequent calls are a NOP.
Definition at line 713 of file SoapySDR.py.
Referenced by _wrap_loadModules(), checkDriver(), getDeviceCounts(), getModuleVersions(), loadModules(), and SoapySDR_loadModules().
void SoapySDR.log = _SoapySDR.log
Definition at line 744 of file SoapySDR.py.
Referenced by SoapyLMS7._readStreamAligned(), _wrap_log(), limeSuiteLogHandler(), log(), and gr::radar::tracking_singletarget_impl.random_normal().
SoapySDR.ModuleVersion_swigregister = _SoapySDR.ModuleVersion_swigregister
Definition at line 726 of file SoapySDR.py.
SoapySDR.Range_swigregister = _SoapySDR.Range_swigregister
Definition at line 129 of file SoapySDR.py.
const uint16_t SoapySDR.S16_FULL_SCALE = (U16_ZERO_OFFSET-1)
Definition at line 22 of file ConverterPrimatives.hpp.
Referenced by S16toF32().
const uint32_t SoapySDR.S32_FULL_SCALE = (U32_ZERO_OFFSET-1)
Definition at line 21 of file ConverterPrimatives.hpp.
Referenced by S32toF32().
const uint8_t SoapySDR.S8_FULL_SCALE = (U8_ZERO_OFFSET-1)
Definition at line 23 of file ConverterPrimatives.hpp.
Referenced by S8toF32().
void SoapySDR.setLogLevel = _SoapySDR.setLogLevel
Definition at line 748 of file SoapySDR.py.
Referenced by _wrap_setLogLevel(), registerLogHandler(), and setLogLevel().
SoapySDR.SOAPY_SDR_ABI_VERSION = _SoapySDR.SOAPY_SDR_ABI_VERSION
Definition at line 612 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_API_VERSION = _SoapySDR.SOAPY_SDR_API_VERSION
Definition at line 611 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CF32 = _SoapySDR.SOAPY_SDR_CF32
Definition at line 626 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CF64 = _SoapySDR.SOAPY_SDR_CF64
Definition at line 625 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CORRUPTION = _SoapySDR.SOAPY_SDR_CORRUPTION
Definition at line 606 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CRITICAL = _SoapySDR.SOAPY_SDR_CRITICAL
Definition at line 650 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CS12 = _SoapySDR.SOAPY_SDR_CS12
Definition at line 631 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CS16 = _SoapySDR.SOAPY_SDR_CS16
Definition at line 629 of file SoapySDR.py.
Referenced by SoapySDR.Device.getNativeStreamFormat().
SoapySDR.SOAPY_SDR_CS32 = _SoapySDR.SOAPY_SDR_CS32
Definition at line 627 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CS4 = _SoapySDR.SOAPY_SDR_CS4
Definition at line 635 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CS8 = _SoapySDR.SOAPY_SDR_CS8
Definition at line 633 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CU12 = _SoapySDR.SOAPY_SDR_CU12
Definition at line 632 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CU16 = _SoapySDR.SOAPY_SDR_CU16
Definition at line 630 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CU32 = _SoapySDR.SOAPY_SDR_CU32
Definition at line 628 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CU4 = _SoapySDR.SOAPY_SDR_CU4
Definition at line 636 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_CU8 = _SoapySDR.SOAPY_SDR_CU8
Definition at line 634 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_DEBUG = _SoapySDR.SOAPY_SDR_DEBUG
Definition at line 655 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_END_ABRUPT = _SoapySDR.SOAPY_SDR_END_ABRUPT
Definition at line 596 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_END_BURST = _SoapySDR.SOAPY_SDR_END_BURST
Definition at line 594 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_ERROR = _SoapySDR.SOAPY_SDR_ERROR
Definition at line 651 of file SoapySDR.py.
Referenced by SoapySDR::ConverterRegistry.ConverterRegistry(), and getModuleVersions().
SoapySDR.SOAPY_SDR_F32 = _SoapySDR.SOAPY_SDR_F32
Definition at line 638 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_F64 = _SoapySDR.SOAPY_SDR_F64
Definition at line 637 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_FATAL = _SoapySDR.SOAPY_SDR_FATAL
Definition at line 649 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_HAS_TIME = _SoapySDR.SOAPY_SDR_HAS_TIME
Definition at line 595 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_INFO = _SoapySDR.SOAPY_SDR_INFO
Definition at line 654 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_MORE_FRAGMENTS = _SoapySDR.SOAPY_SDR_MORE_FRAGMENTS
Definition at line 598 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_NOT_SUPPORTED = _SoapySDR.SOAPY_SDR_NOT_SUPPORTED
Definition at line 608 of file SoapySDR.py.
Referenced by SoapySDR.Device.acquireReadBuffer(), SoapySDR.Device.acquireWriteBuffer(), SoapySDR.Device.activateStream(), SoapySDR.Device.deactivateStream(), SoapySDR.Device.getDirectAccessBufferAddrs(), SoapySDR.Device.readStream(), SoapySDR.Device.readStreamStatus(), and SoapySDR.Device.writeStream().
SoapySDR.SOAPY_SDR_NOTICE = _SoapySDR.SOAPY_SDR_NOTICE
Definition at line 653 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_ONE_PACKET = _SoapySDR.SOAPY_SDR_ONE_PACKET
Definition at line 597 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_OVERFLOW = _SoapySDR.SOAPY_SDR_OVERFLOW
Definition at line 607 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_RX = _SoapySDR.SOAPY_SDR_RX
Definition at line 593 of file SoapySDR.py.
Referenced by SoapySDR.Device.setGain().
SoapySDR.SOAPY_SDR_S16 = _SoapySDR.SOAPY_SDR_S16
Definition at line 641 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_S32 = _SoapySDR.SOAPY_SDR_S32
Definition at line 639 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_S8 = _SoapySDR.SOAPY_SDR_S8
Definition at line 643 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_SSI = _SoapySDR.SOAPY_SDR_SSI
Definition at line 657 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_STREAM_ERROR = _SoapySDR.SOAPY_SDR_STREAM_ERROR
Definition at line 605 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_TIME_ERROR = _SoapySDR.SOAPY_SDR_TIME_ERROR
Definition at line 609 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_TIMEOUT = _SoapySDR.SOAPY_SDR_TIMEOUT
Definition at line 604 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_TRACE = _SoapySDR.SOAPY_SDR_TRACE
Definition at line 656 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_TX = _SoapySDR.SOAPY_SDR_TX
Definition at line 592 of file SoapySDR.py.
Referenced by SoapySDR.Device.setGain().
SoapySDR.SOAPY_SDR_U16 = _SoapySDR.SOAPY_SDR_U16
Definition at line 642 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_U32 = _SoapySDR.SOAPY_SDR_U32
Definition at line 640 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_U8 = _SoapySDR.SOAPY_SDR_U8
Definition at line 644 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_UNDERFLOW = _SoapySDR.SOAPY_SDR_UNDERFLOW
Definition at line 610 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_WAIT_TRIGGER = _SoapySDR.SOAPY_SDR_WAIT_TRIGGER
Definition at line 599 of file SoapySDR.py.
SoapySDR.SOAPY_SDR_WARNING = _SoapySDR.SOAPY_SDR_WARNING
Definition at line 652 of file SoapySDR.py.
SoapySDR.SoapySDR_errToStr = _SoapySDR.SoapySDR_errToStr
Definition at line 603 of file SoapySDR.py.
Referenced by _wrap_SoapySDR_errToStr(), and SoapySDR_errToStr().
SoapySDR.SoapySDR_formatToSize = _SoapySDR.SoapySDR_formatToSize
Definition at line 648 of file SoapySDR.py.
Referenced by _wrap_SoapySDR_formatToSize(), and SoapySDR_formatToSize().
SoapySDR.SoapySDR_getABIVersion = _SoapySDR.SoapySDR_getABIVersion
Definition at line 620 of file SoapySDR.py.
Referenced by _wrap_SoapySDR_getABIVersion().
SoapySDR.SoapySDR_getAPIVersion = _SoapySDR.SoapySDR_getAPIVersion
Definition at line 616 of file SoapySDR.py.
Referenced by _wrap_SoapySDR_getAPIVersion().
SoapySDR.SoapySDR_getLibVersion = _SoapySDR.SoapySDR_getLibVersion
Definition at line 624 of file SoapySDR.py.
Referenced by _wrap_SoapySDR_getLibVersion().
SoapySDR.SoapySDR_log = _SoapySDR.SoapySDR_log
Definition at line 661 of file SoapySDR.py.
Referenced by _wrap_SoapySDR_log(), and SoapySDR_log().
SoapySDR.SoapySDR_setLogLevel = _SoapySDR.SoapySDR_setLogLevel
Definition at line 665 of file SoapySDR.py.
Referenced by _wrap_SoapySDR_setLogLevel(), registerLogHandler(), and SoapySDR_setLogLevel().
SoapySDR.SoapySDRArgInfoList_swigregister = _SoapySDR.SoapySDRArgInfoList_swigregister
Definition at line 371 of file SoapySDR.py.
SoapySDR.SoapySDRDoubleList_swigregister = _SoapySDR.SoapySDRDoubleList_swigregister
Definition at line 559 of file SoapySDR.py.
SoapySDR.SoapySDRKwargs_swigregister = _SoapySDR.SoapySDRKwargs_swigregister
Definition at line 277 of file SoapySDR.py.
SoapySDR.SoapySDRKwargsList_swigregister = _SoapySDR.SoapySDRKwargsList_swigregister
Definition at line 324 of file SoapySDR.py.
SoapySDR.SoapySDRRangeList_swigregister = _SoapySDR.SoapySDRRangeList_swigregister
Definition at line 465 of file SoapySDR.py.
SoapySDR.SoapySDRSizeList_swigregister = _SoapySDR.SoapySDRSizeList_swigregister
Definition at line 512 of file SoapySDR.py.
SoapySDR.SoapySDRStringList_swigregister = _SoapySDR.SoapySDRStringList_swigregister
Definition at line 418 of file SoapySDR.py.
SoapySDR.SoapySDRUnsignedList_swigregister = _SoapySDR.SoapySDRUnsignedList_swigregister
Definition at line 222 of file SoapySDR.py.
SoapySDR.StreamResult_swigregister = _SoapySDR.StreamResult_swigregister
Definition at line 589 of file SoapySDR.py.
SoapySDR.SwigPyIterator_swigregister = _SoapySDR.SwigPyIterator_swigregister
Definition at line 98 of file SoapySDR.py.
static long long SoapySDR.ticksToTimeNs = _SoapySDR.ticksToTimeNs inline
Definition at line 736 of file SoapySDR.py.
Referenced by _wrap_ticksToTimeNs(), SoapyLMS7.getHardwareTime(), loopbackTicksToTime(), loopbackTimeToTicks(), SoapyLMS7.readSensor(), SoapyLMS7.readStream(), SoapyLMS7.readStreamStatus(), and ticksToTimeNs().
static long long SoapySDR.timeNsToTicks = _SoapySDR.timeNsToTicks inline
Definition at line 740 of file SoapySDR.py.
Referenced by _wrap_timeNsToTicks(), loopbackTicksToTime(), loopbackTimeToTicks(), SoapyLMS7.readStream(), SoapyLMS7.setHardwareTime(), timeNsToTicks(), and SoapyLMS7.writeStream().
const uint16_t SoapySDR.U16_ZERO_OFFSET = uint16_t(1<<15)
Definition at line 18 of file ConverterPrimatives.hpp.
Referenced by S16toU16().
const uint32_t SoapySDR.U32_ZERO_OFFSET = uint32_t(1<<31)
Definition at line 17 of file ConverterPrimatives.hpp.
Referenced by S32toU32().
const uint8_t SoapySDR.U8_ZERO_OFFSET = uint8_t(1<<7)
Definition at line 19 of file ConverterPrimatives.hpp.
Referenced by S8toU8().
std.string SoapySDR.unloadModule = _SoapySDR.unloadModule
Definition at line 709 of file SoapySDR.py.
Referenced by _wrap_unloadModule(), getModuleVersions(), SoapySDR_unloadModule(), and unloadModule().