LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/protocols/ConnectionImages.cpp File Reference
ConnectionImages.cpp File Reference
#include "SystemResources.h"
#include "LMS64CProtocol.h"
#include "LMSBoards.h"
#include "Logger.h"
#include <fstream>
#include <ciso646>
Classes
struct ConnectionImageEntry
Functions
static const ConnectionImageEntry & lookupImageEntry (const LMS64CProtocol::LMSinfo &info)
static bool programmingCallbackStream (int bsent, int btotal, const char *progressMsg, const std::string &image, IConnection::ProgrammingCallback callback)
Function Documentation
static const ConnectionImageEntry& lookupImageEntry (const LMS64CProtocol::LMSinfo & info) static
Lookup the board information given hardware type and revision. Edit each entry for supported hardware and image updates.
Definition at line 36 of file ConnectionImages.cpp.
References lime::LMS64CProtocol::LMSinfo::device, lime::LMS64CProtocol::LMSinfo::hardware, lime::LMS_DEV_LIMESDR, lime::LMS_DEV_LIMESDRMINI, lime::LMS_DEV_STREAM, and lime::LMS_DEV_UNKNOWN.
Referenced by lime::LMS64CProtocol::ProgramUpdate(), and lime::LMS64CProtocol::VersionCheck().
static bool programmingCallbackStream (int bsent, int btotal, const char * progressMsg, const std::string & image, IConnection::ProgrammingCallback callback) static
Definition at line 95 of file ConnectionImages.cpp.
References callback, and string().
Referenced by lime::LMS64CProtocol::ProgramUpdate().