LimeSuite-UML: lms7002_pnlXBUF_view Class Reference
lms7002_pnlXBUF_view Class Reference
Implementing pnlXBUF_view.
#include <lms7002_pnlXBUF_view.h>
Public Member Functions
lms7002_pnlXBUF_view (wxWindow *parent)
Constructor.
lms7002_pnlXBUF_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlXBUF_view
pnlXBUF_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlXBUF_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlXBUF_view
wxCheckBox * chkPD_XBUF_RX
wxCheckBox * chkPD_XBUF_TX
wxCheckBox * chkEN_G_XBUF
wxCheckBox * chkSLFB_XBUF_RX
wxCheckBox * chkSLFB_XBUF_TX
wxCheckBox * chkBYP_XBUF_RX
wxCheckBox * chkBYP_XBUF_TX
wxCheckBox * chkEN_OUT2_XBUF_TX
wxCheckBox * chkEN_TBUFIN_XBUF_RX
Additional Inherited Members
Protected Types inherited from pnlXBUF_view
enum {
ID_PD_XBUF_RX = 2048, ID_PD_XBUF_TX, ID_EN_G_XBUF, ID_SLFB_XBUF_RX,
ID_SLFB_XBUF_TX, ID_BYP_XBUF_RX, ID_BYP_XBUF_TX, ID_EN_OUT2_XBUF_TX,
ID_EN_TBUFIN_XBUF_RX
}
Detailed Description
Implementing pnlXBUF_view.
Definition at line 19 of file lms7002_pnlXBUF_view.h.
Constructor & Destructor Documentation
lms7002_pnlXBUF_view::lms7002_pnlXBUF_view (wxWindow * parent)
Constructor.
Definition at line 7 of file lms7002_pnlXBUF_view.cpp.
lms7002_pnlXBUF_view::lms7002_pnlXBUF_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 14 of file lms7002_pnlXBUF_view.cpp.
References BYP_XBUF_RX, BYP_XBUF_TX, pnlXBUF_view::chkBYP_XBUF_RX, pnlXBUF_view::chkBYP_XBUF_TX, pnlXBUF_view::chkEN_G_XBUF, pnlXBUF_view::chkEN_OUT2_XBUF_TX, pnlXBUF_view::chkEN_TBUFIN_XBUF_RX, pnlXBUF_view::chkPD_XBUF_RX, pnlXBUF_view::chkPD_XBUF_TX, pnlXBUF_view::chkSLFB_XBUF_RX, pnlXBUF_view::chkSLFB_XBUF_TX, EN_G_XBUF, EN_OUT2_XBUF_TX, EN_TBUFIN_XBUF_RX, LMS7param, PD_XBUF_RX, PD_XBUF_TX, SLFB_XBUF_RX, SLFB_XBUF_TX, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlXBUF_view::Initialize (lms_device_t * pControl)
Definition at line 30 of file lms7002_pnlXBUF_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlXBUF_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlXBUF_view.
Definition at line 36 of file lms7002_pnlXBUF_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlXBUF_view::UpdateGUI ()
Definition at line 52 of file lms7002_pnlXBUF_view.cpp.
References lmsControl, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlXBUF_view::lmsControl protected
Definition at line 32 of file lms7002_pnlXBUF_view.h.
Referenced by Initialize(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlXBUF_view::wndId2Enum protected
Definition at line 33 of file lms7002_pnlXBUF_view.h.
Referenced by lms7002_pnlXBUF_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlXBUF_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlXBUF_view.cpp