LimeSuite-UML: lms7002_pnlTRF_view Class Reference
lms7002_pnlTRF_view Class Reference
Implementing pnlTRF_view.
#include <lms7002_pnlTRF_view.h>
Public Member Functions
lms7002_pnlTRF_view (wxWindow *parent)
Constructor.
lms7002_pnlTRF_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlTRF_view
pnlTRF_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlTRF_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void OnBandChange (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlTRF_view
wxCheckBox * chkPD_PDET_TRF
wxCheckBox * chkPD_TLOBUF_TRF
wxCheckBox * chkPD_TXPAD_TRF
wxCheckBox * chkEN_G_TRF
wxCheckBox * chkEN_DIR_TRF
wxStaticText * ID_STATICTEXT11
wxComboBox * cmbLOADR_PDET_TRF
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbICT_LIN_TXPAD_TRF
wxStaticText * ID_STATICTEXT13
wxComboBox * cmbICT_MAIN_TXPAD_TRF
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbCDC_I_TRF
wxStaticText * ID_STATICTEXT15
wxComboBox * cmbCDC_Q_TRF
wxRadioBox * rgrGCAS_GNDREF_TXPAD_TRF
wxCheckBox * chkEN_NEXTTX_TRF
wxCheckBox * chkEN_LOOPB_TXPAD_TRF
wxStaticText * ID_STATICTEXT16
wxComboBox * cmbTXFEoutput
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbEN_LOWBWLOMX_TMX_TRF
wxStaticText * ID_STATICTEXT3
wxComboBox * cmbEN_AMPHF_PDET_TRF
wxStaticText * ID_STATICTEXT4
wxComboBox * cmbF_TXPAD_TRF
wxStaticText * ID_STATICTEXT5
wxComboBox * cmbL_LOOPB_TXPAD_TRF
wxStaticText * ID_STATICTEXT6
wxComboBox * cmbLOSS_LIN_TXPAD_TRF
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbLOSS_MAIN_TXPAD_TRF
wxStaticText * ID_STATICTEXT8
wxComboBox * cmbVGCAS_TXPAD_TRF
wxStaticText * ID_STATICTEXT9
wxComboBox * cmbLOBIASN_TXM_TRF
wxStaticText * ID_STATICTEXT10
wxComboBox * cmbLOBIASP_TXX_TRF
Additional Inherited Members
Protected Types inherited from pnlTRF_view
enum {
ID_PD_PDET_TRF = 2048, ID_PD_TLOBUF_TRF, ID_PD_TXPAD_TRF, ID_EN_G_TRF,
ID_EN_DIR_TRF, ID_LOADR_PDET_TRF, ID_ICT_LIN_TXPAD_TRF, ID_ICT_MAIN_TXPAD_TRF,
ID_CDC_I_TRF, ID_CDC_Q_TRF, ID_GCAS_GNDREF_TXPAD_TRF, ID_EN_NEXTTX_TRF,
ID_EN_LOOPB_TXPAD_TRF, ID_TXFEoutput, ID_EN_LOWBWLOMX_TMX_TRF, ID_EN_AMPHF_PDET_TRF,
ID_F_TXPAD_TRF, ID_L_LOOPB_TXPAD_TRF, ID_LOSS_LIN_TXPAD_TRF, ID_LOSS_MAIN_TXPAD_TRF,
ID_VGCAS_TXPAD_TRF, ID_LOBIASN_TXM_TRF, ID_LOBIASP_TXX_TRF
}
Detailed Description
Implementing pnlTRF_view.
Definition at line 18 of file lms7002_pnlTRF_view.h.
Constructor & Destructor Documentation
lms7002_pnlTRF_view::lms7002_pnlTRF_view (wxWindow * parent)
Constructor.
Definition at line 11 of file lms7002_pnlTRF_view.cpp.
lms7002_pnlTRF_view::lms7002_pnlTRF_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 18 of file lms7002_pnlTRF_view.cpp.
References CDC_I_TRF, CDC_Q_TRF, pnlTRF_view::chkEN_DIR_TRF, pnlTRF_view::chkEN_G_TRF, pnlTRF_view::chkEN_LOOPB_TXPAD_TRF, pnlTRF_view::chkEN_NEXTTX_TRF, pnlTRF_view::chkPD_PDET_TRF, pnlTRF_view::chkPD_TLOBUF_TRF, pnlTRF_view::chkPD_TXPAD_TRF, pnlTRF_view::cmbCDC_I_TRF, pnlTRF_view::cmbCDC_Q_TRF, pnlTRF_view::cmbEN_AMPHF_PDET_TRF, pnlTRF_view::cmbEN_LOWBWLOMX_TMX_TRF, pnlTRF_view::cmbF_TXPAD_TRF, pnlTRF_view::cmbICT_LIN_TXPAD_TRF, pnlTRF_view::cmbICT_MAIN_TXPAD_TRF, pnlTRF_view::cmbL_LOOPB_TXPAD_TRF, pnlTRF_view::cmbLOADR_PDET_TRF, pnlTRF_view::cmbLOBIASN_TXM_TRF, pnlTRF_view::cmbLOBIASP_TXX_TRF, pnlTRF_view::cmbLOSS_LIN_TXPAD_TRF, pnlTRF_view::cmbLOSS_MAIN_TXPAD_TRF, pnlTRF_view::cmbVGCAS_TXPAD_TRF, EN_AMPHF_PDET_TRF, en_amphf_pdet_trfIndexValuePairs, EN_DIR_TRF, EN_G_TRF, EN_LOOPB_TXPAD_TRF, EN_LOWBWLOMX_TMX_TRF, EN_NEXTTX_TRF, F_TXPAD_TRF, GCAS_GNDREF_TXPAD_TRF, i, ICT_LIN_TXPAD_TRF, ICT_MAIN_TXPAD_TRF, L_LOOPB_TXPAD_TRF, LMS7param, LOADR_PDET_TRF, LOBIASN_TXM_TRF, LOBIASP_TXX_TRF, LOSS_LIN_TXPAD_TRF, LOSS_MAIN_TXPAD_TRF, PD_PDET_TRF, PD_TLOBUF_TRF, PD_TXPAD_TRF, pnlTRF_view::rgrGCAS_GNDREF_TXPAD_TRF, temp, LMS7002_WXGUI::UpdateTooltips(), VGCAS_TXPAD_TRF, and wndId2Enum.
Member Function Documentation
void lms7002_pnlTRF_view::Initialize (lms_device_t * pControl)
Definition at line 84 of file lms7002_pnlTRF_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlTRF_view::OnBandChange (wxCommandEvent & event) protected virtual
Reimplemented from pnlTRF_view.
Definition at line 110 of file lms7002_pnlTRF_view.cpp.
References pnlTRF_view::cmbTXFEoutput, LMS7param, LMS_WriteParam(), lmsControl, SEL_BAND1_TRF, and SEL_BAND2_TRF.
void lms7002_pnlTRF_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlTRF_view.
Definition at line 90 of file lms7002_pnlTRF_view.cpp.
References pnlTRF_view::cmbEN_AMPHF_PDET_TRF, en_amphf_pdet_trfIndexValuePairs, LMS7002_WXGUI::index2value(), LMS_WriteParam(), lmsControl, and wndId2Enum.
void lms7002_pnlTRF_view::UpdateGUI ()
Definition at line 137 of file lms7002_pnlTRF_view.cpp.
References pnlTRF_view::chkEN_NEXTTX_TRF, pnlTRF_view::cmbEN_AMPHF_PDET_TRF, pnlTRF_view::cmbLOSS_LIN_TXPAD_TRF, pnlTRF_view::cmbLOSS_MAIN_TXPAD_TRF, pnlTRF_view::cmbTXFEoutput, EN_AMPHF_PDET_TRF, en_amphf_pdet_trfIndexValuePairs, LMS7param, LMS_ReadParam(), LMS_WriteParam(), lmsControl, MAC, SEL_BAND1_TRF, SEL_BAND2_TRF, TRX_GAIN_SRC, LMS7002_WXGUI::UpdateControlsByMap(), LMS7002_WXGUI::value2index(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlTRF_view::lmsControl protected
Definition at line 32 of file lms7002_pnlTRF_view.h.
Referenced by Initialize(), OnBandChange(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlTRF_view::wndId2Enum protected
Definition at line 33 of file lms7002_pnlTRF_view.h.
Referenced by lms7002_pnlTRF_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlTRF_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlTRF_view.cpp