LimeSuite-UML: lime::FPGA_Q Class Reference
lime::FPGA_Q Class Reference
#include <FPGA_Q.h>
Public Member Functions
FPGA_Q ()
virtual ~FPGA_Q ()
int SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, double txPhase, double rxPhase, int ch=0) override
Configures FPGA PLLs to LimeLight interface frequency.
Public Member Functions inherited from lime::FPGA
FPGA ()
virtual ~FPGA ()
void SetConnection (IConnection *conn)
IConnection * GetConnection () const
int StartStreaming ()
int StopStreaming ()
int ResetTimestamp ()
virtual int UploadWFM (const void *const *samples, uint8_t chCount, size_t sample_count, StreamConfig::StreamDataFormat format, int epIndex)
virtual int SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, int ch=0)
Configures FPGA PLLs to LimeLight interface frequency.
double DetectRefClk (double fx3Clk=100e6)
Additional Inherited Members
Static Public Member Functions inherited from lime::FPGA
static int FPGAPacketPayload2Samples (const uint8_t *buffer, int bufLen, bool mimo, bool compressed, complex16_t **samples)
Parses FPGA packet payload into samples.
static int Samples2FPGAPacketPayload (const complex16_t *const *samples, int samplesCount, bool mimo, bool compressed, uint8_t *buffer)
Protected Member Functions inherited from lime::FPGA
int SetPllFrequency (uint8_t pllIndex, double inputFreq, FPGA_PLL_clock *outputs, uint8_t clockCount)
Configures board FPGA clocks.
int SetDirectClocking (int clockIndex)
Protected Attributes inherited from lime::FPGA
IConnection * connection
Detailed Description
Definition at line 15 of file FPGA_Q.h.
Constructor & Destructor Documentation
lime::FPGA_Q::FPGA_Q ()
Definition at line 13 of file FPGA_Q.cpp.
virtual lime::FPGA_Q::~FPGA_Q () inline virtual
Definition at line 19 of file FPGA_Q.h.
References SetInterfaceFreq().
Member Function Documentation
int lime::FPGA_Q::SetInterfaceFreq (double f_Tx_Hz, double f_Rx_Hz, double txPhase, double rxPhase, int ch = 0) override virtual
Configures FPGA PLLs to LimeLight interface frequency.
Reimplemented from lime::FPGA.
Definition at line 16 of file FPGA_Q.cpp.
References lime::FPGA::FPGA_PLL_clock::index, lime::FPGA::FPGA_PLL_clock::outFrequency, lime::FPGA::FPGA_PLL_clock::phaseShift_deg, and lime::FPGA::SetPllFrequency().
Referenced by ~FPGA_Q().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/FPGA_common/FPGA_Q.h
/home/erik/prefix/default/src/limesuite-dev/src/FPGA_common/FPGA_Q.cpp