LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/host_src/mcu.h File Reference
mcu.h File Reference
#include "typedefs.h"
Enumerations
enum MCU_Parameter { MCU_REF_CLK, MCU_BW, MCU_EXT_LOOPBACK_PAIR }
Functions
void MCU_RunProcedure (uint8_t id)
uint8_t MCU_WaitForStatus (uint16_t timeout_ms)
uint8_t MCU_UploadProgram (const uint8_t *binImage, const uint16_t len)
uint8_t MCU_SetParameter (MCU_Parameter param, float value)
Enumeration Type Documentation
enum MCU_Parameter
Enumerator
MCU_REF_CLK
MCU_BW
MCU_EXT_LOOPBACK_PAIR
Definition at line 15 of file mcu.h.
Function Documentation
void MCU_RunProcedure (uint8_t id)
Definition at line 12 of file mcu.c.
References SPI_read(), and SPI_write_batch().
Referenced by DCIQ(), Filters(), and MCU_SetParameter().
uint8_t MCU_SetParameter (MCU_Parameter param, float value)
Definition at line 44 of file mcu.c.
References i, inputRegs, int(), MCU_BW, MCU_EXT_LOOPBACK_PAIR, MCU_REF_CLK, MCU_RunProcedure(), MCU_WaitForStatus(), SPI_read(), SPI_write(), and status.
Referenced by DCIQ(), and UploadMCUParameters().
uint8_t MCU_UploadProgram (const uint8_t * binImage, const uint16_t len)
Definition at line 87 of file mcu.c.
References i, len, SPI_read(), SPI_write(), SPI_write_batch(), t1, and t2.
Referenced by main().
uint8_t MCU_WaitForStatus (uint16_t timeout_ms)
Definition at line 27 of file mcu.c.
References SPI_read(), SPI_write(), t1, and t2.
Referenced by DCIQ(), Filters(), and MCU_SetParameter().