LimeSuite-UML: LMS7002M_Novena_wxgui Class Reference
LMS7002M_Novena_wxgui Class Reference
#include <lms7002m_novena_wxgui.h>
Public Member Functions
LMS7002M_Novena_wxgui (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxEmptyString, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long styles=0)
void Initialize (lms_device_t *serPort, const size_t devIndex=0)
virtual ~LMS7002M_Novena_wxgui ()
virtual void UpdatePanel ()
Public Attributes
wxCheckBox * lms_reset
wxCheckBox * lms_rxen
wxCheckBox * lms_txen
wxCheckBox * lms_gpio2
wxCheckBox * lms_gpio1
wxCheckBox * lms_gpio0
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
RX active paths lms_gpio0 | lms_gpio1 RX_A RX_B 0 0 => no active path 1 0 => LNAW_A LNAW_B 0 1 => LNAH_A LNAH_B 1 1 => LNAL_A LNAL_B.
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
DECLARE_EVENT_TABLE ()
Protected Attributes
lms_device_t * lmsControl
int m_rficSpiAddr
Detailed Description
Definition at line 14 of file lms7002m_novena_wxgui.h.
Constructor & Destructor Documentation
LMS7002M_Novena_wxgui::LMS7002M_Novena_wxgui (wxWindow * parent, wxWindowID id = wxID_ANY, const wxString & title = wxEmptyString, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long styles = 0)
Definition at line 7 of file lms7002m_novena_wxgui.cpp.
References OnReadAll(), OnWriteAll(), and ParameterChangeHandler().
LMS7002M_Novena_wxgui::~LMS7002M_Novena_wxgui () virtual
Definition at line 51 of file lms7002m_novena_wxgui.cpp.
Member Function Documentation
LMS7002M_Novena_wxgui::DECLARE_EVENT_TABLE () protected
void LMS7002M_Novena_wxgui::Initialize (lms_device_t * serPort, const size_t devIndex = 0)
Definition at line 81 of file lms7002m_novena_wxgui.cpp.
References lmsControl, and serPort.
Referenced by pnlBoardControls::SetupControls().
void LMS7002M_Novena_wxgui::OnReadAll (wxCommandEvent & event) protected
Definition at line 130 of file lms7002m_novena_wxgui.cpp.
References UpdatePanel().
Referenced by LMS7002M_Novena_wxgui().
void LMS7002M_Novena_wxgui::OnWriteAll (wxCommandEvent & event) protected
Definition at line 135 of file lms7002m_novena_wxgui.cpp.
References ParameterChangeHandler().
Referenced by LMS7002M_Novena_wxgui().
void LMS7002M_Novena_wxgui::ParameterChangeHandler (wxCommandEvent & event) protected
RX active paths lms_gpio0 | lms_gpio1 RX_A RX_B 0 0 => no active path 1 0 => LNAW_A LNAW_B 0 1 => LNAH_A LNAH_B 1 1 => LNAL_A LNAL_B.
lms_gpio2 - tx output selection: 0 - TX1_A and TX1_B (Band 1) 1 - TX2_A and TX2_B (Band 2)
Definition at line 102 of file lms7002m_novena_wxgui.cpp.
References lms_gpio0, lms_gpio1, lms_gpio2, lms_reset, lms_rxen, lms_txen, LMS_WriteLMSReg(), lmsControl, and status.
Referenced by LMS7002M_Novena_wxgui(), and OnWriteAll().
void LMS7002M_Novena_wxgui::UpdatePanel () virtual
Definition at line 56 of file lms7002m_novena_wxgui.cpp.
References lms_gpio0, lms_gpio1, lms_gpio2, LMS_ReadLMSReg(), lms_reset, lms_rxen, lms_txen, lmsControl, and status.
Referenced by OnReadAll().
Member Data Documentation
wxCheckBox * LMS7002M_Novena_wxgui::lms_gpio0
Definition at line 22 of file lms7002m_novena_wxgui.h.
Referenced by ParameterChangeHandler(), and UpdatePanel().
wxCheckBox * LMS7002M_Novena_wxgui::lms_gpio1
Definition at line 22 of file lms7002m_novena_wxgui.h.
Referenced by ParameterChangeHandler(), and UpdatePanel().
wxCheckBox * LMS7002M_Novena_wxgui::lms_gpio2
Definition at line 22 of file lms7002m_novena_wxgui.h.
Referenced by ParameterChangeHandler(), and UpdatePanel().
wxCheckBox* LMS7002M_Novena_wxgui::lms_reset
Definition at line 22 of file lms7002m_novena_wxgui.h.
Referenced by ParameterChangeHandler(), and UpdatePanel().
wxCheckBox * LMS7002M_Novena_wxgui::lms_rxen
Definition at line 22 of file lms7002m_novena_wxgui.h.
Referenced by ParameterChangeHandler(), and UpdatePanel().
wxCheckBox * LMS7002M_Novena_wxgui::lms_txen
Definition at line 22 of file lms7002m_novena_wxgui.h.
Referenced by ParameterChangeHandler(), and UpdatePanel().
lms_device_t* LMS7002M_Novena_wxgui::lmsControl protected
Definition at line 27 of file lms7002m_novena_wxgui.h.
Referenced by Initialize(), ParameterChangeHandler(), and UpdatePanel().
int LMS7002M_Novena_wxgui::m_rficSpiAddr protected
Definition at line 28 of file lms7002m_novena_wxgui.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/lms7002m_novena_wxgui.h
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/lms7002m_novena_wxgui.cpp