LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/octave/tx.m File Reference
tx.m File Reference
Functions
LimeInitialize ()
open device LimeLoadConfig ('trxTest.ini')
fifoSize,"tx0" LimeStartStreaming ()
send samples to TX channel end sleep (1)
LimeStopStreaming ()
stop streaming Waveform playback from device RAM LimeLoopWFMStart (src)
Load samples to device for looping to TX sleep (10)
LimeLoopWFMStop ()
stop looping TX samples from device RAM LimeDestroy ()
Variables
clear all
LoadLimeSuite generate test signal phase = pi/6
phase step periods = 3000
periods to generate src = 0.7*complex(sin(phase:phase:periods*2*pi), cos(phase:phase:periods*2*pi))
start TX to channel for i
Load samples to device RAM
Function Documentation
stop looping TX samples from device RAM LimeDestroy ()
LimeInitialize ()
open device LimeLoadConfig ('trxTest.ini')
stop streaming Waveform playback from device RAM LimeLoopWFMStart (src)
LimeLoopWFMStop ()
fifoSize,"tx0" LimeStartStreaming () virtual
LimeStopStreaming ()
send samples to TX channel end sleep (1)
Referenced by gr::radar::soapysdr_echotimer_impl::soapysdr_echotimer_impl(), gr::radar::soapysdr_echotimer_stretch_impl::soapysdr_echotimer_stretch_impl(), python.qa_trigger_command.qa_trigger_command::test_001_t(), python.qa_estimator_cw.qa_estimator_cw::test_001_t(), python.qa_os_cfar_c.qa_os_cfar_c::test_001_t(), python.qa_msg_manipulator.qa_msg_manipulator::test_001_t(), python.qa_find_max_peak_c.qa_find_max_peak_c::test_001_t(), python.qa_estimator_fsk.qa_estimator_fsk::test_001_t(), python.qa_msg_gate.qa_msg_gate::test_001_t(), python.qa_estimator_ofdm.qa_estimator_ofdm::test_001_t(), python.qa_estimator_rcs.qa_estimator_rcs::test_001_t(), python.qa_estimator_fmcw.qa_estimator_fmcw::test_001_t(), python.qa_tracking_singletarget.qa_tracking_singletarget::test_001_t(), python.qa_find_max_peak_c.qa_find_max_peak_c::test_002_t(), python.qa_os_cfar_c.qa_os_cfar_c::test_002_t(), python.qa_find_max_peak_c.qa_find_max_peak_c::test_003_t(), python.qa_find_max_peak_c.qa_find_max_peak_c::test_004t(), and gr::radar::usrp_echotimer_cc_impl::usrp_echotimer_cc_impl().
Load samples to device for looping to TX sleep (10)
Variable Documentation
clear all
Definition at line 1 of file tx.m.
start TX to channel for i
Initial value:
=1:100
    LimeTransmitSamples(src,0)
Definition at line 17 of file tx.m.
phase step periods = 3000
Definition at line 7 of file tx.m.
LoadLimeSuite generate test signal phase = pi/6
Definition at line 6 of file tx.m.
Referenced by kiss_fft_alloc(), lms7002_pnlTxTSP_view::UpdateNCOinputs(), and lms7002_pnlRxTSP_view::UpdateNCOinputs().
Load samples to device RAM
Definition at line 24 of file tx.m.
Referenced by lime::ConnectionFX3::ProgramWrite().
periods to generate src = 0.7*complex(sin(phase:phase:periods*2*pi), cos(phase:phase:periods*2*pi))
Definition at line 8 of file tx.m.
Referenced by genericCF32toCF32(), genericCF32toCS16(), genericCF32toCS8(), genericCF32toCU16(), genericCF32toCU8(), genericCS16toCF32(), genericCS16toCS16(), genericCS16toCS8(), genericCS16toCU16(), genericCS16toCU8(), genericCS32toCS32(), genericCS8toCF32(), genericCS8toCS16(), genericCS8toCS8(), genericCS8toCU16(), genericCS8toCU8(), genericCU16toCF32(), genericCU16toCS16(), genericCU16toCS8(), genericCU8toCF32(), genericCU8toCS16(), genericCU8toCS8(), genericF32toF32(), genericF32toS16(), genericF32toS8(), genericF32toU16(), genericF32toU8(), genericS16toF32(), genericS16toS16(), genericS16toS8(), genericS16toU16(), genericS16toU8(), genericS32toS32(), genericS8toF32(), genericS8toS16(), genericS8toS8(), genericS8toU16(), genericS8toU8(), genericU16toF32(), genericU16toS16(), genericU16toS8(), genericU8toF32(), genericU8toS16(), genericU8toS8(), lime::FPGA::Samples2FPGAPacketPayload(), setbit(), toggleInherit(), toggleVisibility(), lime::Streamer::TransmitPacketsLoop(), FPGAcontrols_wxgui::UploadFile(), and lime::FPGA::UploadWFM().