LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/tests/streaming.cpp File Reference
streaming.cpp File Reference
#include "gtest/gtest.h"
#include "streamingFixture.h"
#include "IConnection.h"
#include "LMS7002M.h"
#include "math.h"
#include <thread>
#include <chrono>
#include "dataTypes.h"
Classes
struct complexFloat32_t
Macros
#define DRAW_GNU_PLOTS 0
Functions
TEST_F (StreamingFixture, channelsRxAB)
TEST_F (StreamingFixture, channelsRxA)
TEST_F (StreamingFixture, channelsRxB)
TEST_F (StreamingFixture, channelsRxAB_TxAB)
TEST_F (StreamingFixture, DISABLED_Rx2TxLoopback)
TEST_F (StreamingFixture, channelsRxAB_Float)
Macro Definition Documentation
#define DRAW_GNU_PLOTS 0
Definition at line 11 of file streaming.cpp.
Function Documentation
TEST_F (StreamingFixture , channelsRxAB)
Definition at line 23 of file streaming.cpp.
References AGC_BYP_RXTSP, lime::StreamConfig::channelID, chCount, CLKH_OV_CLKL_CGEN, CMIX_BYP_RXTSP, EN_ADCCLKH_CLKGN, GNUPlotPipe::flush(), lime::StreamConfig::format, lime::LMS7002M::GetActiveChannelIndex(), lime::LMS7002M::GetSampleRate(), GFIR1_BYP_RXTSP, GFIR2_BYP_RXTSP, GFIR3_BYP_RXTSP, i, lime::complex16_t::i, INSEL_RXTSP, lime::StreamConfig::isTx, LML1_MODE, LML2_MODE, LMS7param, lmsControl, lime::LMS7002M::Modify_SPI_Reg_bits(), PD_RX_AFE2, lime::complex16_t::q, lime::LMS7002M::ResetChip(), serPort, lime::LMS7002M::SetActiveChannel(), lime::LMS7002M::SetConnection(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetInterfaceFrequency(), status, TSGFC_RXTSP, TSGFCW_RXTSP, lime::LMS7002M::UploadAll(), GNUPlotPipe::write(), and GNUPlotPipe::writef().
TEST_F (StreamingFixture , channelsRxA)
Definition at line 140 of file streaming.cpp.
References AGC_BYP_RXTSP, buffer, lime::StreamConfig::channelID, CLKH_OV_CLKL_CGEN, CMIX_BYP_RXTSP, EN_ADCCLKH_CLKGN, GNUPlotPipe::flush(), lime::StreamConfig::format, lime::LMS7002M::GetSampleRate(), GFIR1_BYP_RXTSP, GFIR2_BYP_RXTSP, GFIR3_BYP_RXTSP, i, lime::complex16_t::i, INSEL_RXTSP, lime::StreamConfig::isTx, LML1_MODE, LML2_MODE, LMS7param, lmsControl, lime::LMS7002M::Modify_SPI_Reg_bits(), PD_RX_AFE2, lime::complex16_t::q, lime::LMS7002M::ResetChip(), serPort, lime::LMS7002M::SetActiveChannel(), lime::LMS7002M::SetConnection(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetInterfaceFrequency(), status, TSGFC_RXTSP, TSGFCW_RXTSP, lime::LMS7002M::UploadAll(), GNUPlotPipe::write(), and GNUPlotPipe::writef().
TEST_F (StreamingFixture , channelsRxB)
Definition at line 228 of file streaming.cpp.
References AGC_BYP_RXTSP, buffer, lime::StreamConfig::channelID, CLKH_OV_CLKL_CGEN, CMIX_BYP_RXTSP, EN_ADCCLKH_CLKGN, GNUPlotPipe::flush(), lime::StreamConfig::format, lime::LMS7002M::GetSampleRate(), GFIR1_BYP_RXTSP, GFIR2_BYP_RXTSP, GFIR3_BYP_RXTSP, i, lime::complex16_t::i, INSEL_RXTSP, lime::StreamConfig::isTx, LML1_MODE, LML2_MODE, LMS7param, lmsControl, lime::LMS7002M::Modify_SPI_Reg_bits(), PD_RX_AFE2, lime::complex16_t::q, lime::LMS7002M::ResetChip(), serPort, lime::LMS7002M::SetActiveChannel(), lime::LMS7002M::SetConnection(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetInterfaceFrequency(), status, TSGFC_RXTSP, TSGFCW_RXTSP, lime::LMS7002M::UploadAll(), GNUPlotPipe::write(), and GNUPlotPipe::writef().
TEST_F (StreamingFixture , channelsRxAB_TxAB)
Definition at line 316 of file streaming.cpp.
References AGC_BYP_RXTSP, lime::StreamConfig::channelID, chCount, CLKH_OV_CLKL_CGEN, CMIX_BYP_RXTSP, EN_ADCCLKH_CLKGN, GNUPlotPipe::flush(), lime::StreamConfig::format, lime::LMS7002M::GetActiveChannelIndex(), lime::LMS7002M::GetSampleRate(), GFIR1_BYP_RXTSP, GFIR2_BYP_RXTSP, GFIR3_BYP_RXTSP, i, lime::complex16_t::i, INSEL_RXTSP, lime::StreamConfig::isTx, LML1_MODE, LML2_MODE, LMS7param, lmsControl, lime::LMS7002M::Modify_SPI_Reg_bits(), PD_RX_AFE2, lime::complex16_t::q, lime::LMS7002M::ResetChip(), serPort, lime::LMS7002M::SetActiveChannel(), lime::LMS7002M::SetConnection(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetInterfaceFrequency(), status, TSGFC_RXTSP, TSGFCW_RXTSP, lime::LMS7002M::UploadAll(), GNUPlotPipe::write(), and GNUPlotPipe::writef().
TEST_F (StreamingFixture , DISABLED_Rx2TxLoopback)
Definition at line 456 of file streaming.cpp.
References AGC_BYP_RXTSP, lime::StreamConfig::channelID, CLKH_OV_CLKL_CGEN, CMIX_BYP_RXTSP, EN_ADCCLKH_CLKGN, lime::StreamConfig::format, lime::LMS7002M::GetSampleRate(), GFIR1_BYP_RXTSP, GFIR2_BYP_RXTSP, GFIR3_BYP_RXTSP, INSEL_RXTSP, lime::StreamConfig::isTx, LML1_MODE, LML2_MODE, LMS7param, lmsControl, lime::LMS7002M::Modify_SPI_Reg_bits(), PD_RX_AFE2, lime::LMS7002M::ResetChip(), lime::samples12InPkt, serPort, lime::LMS7002M::SetActiveChannel(), lime::LMS7002M::SetConnection(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetInterfaceFrequency(), status, t2, TSGFC_RXTSP, TSGFCW_RXTSP, and lime::LMS7002M::UploadAll().
TEST_F (StreamingFixture , channelsRxAB_Float)
Definition at line 550 of file streaming.cpp.
References AGC_BYP_RXTSP, lime::StreamConfig::channelID, chCount, CLKH_OV_CLKL_CGEN, CMIX_BYP_RXTSP, EN_ADCCLKH_CLKGN, GNUPlotPipe::flush(), lime::StreamConfig::format, lime::LMS7002M::GetActiveChannelIndex(), lime::LMS7002M::GetSampleRate(), GFIR1_BYP_RXTSP, GFIR2_BYP_RXTSP, GFIR3_BYP_RXTSP, complexFloat32_t::i, i, INSEL_RXTSP, lime::StreamConfig::isTx, LML1_MODE, LML2_MODE, LMS7param, lmsControl, lime::LMS7002M::Modify_SPI_Reg_bits(), PD_RX_AFE2, complexFloat32_t::q, lime::LMS7002M::ResetChip(), serPort, lime::LMS7002M::SetActiveChannel(), lime::LMS7002M::SetConnection(), lime::LMS7002M::SetFrequencySX(), lime::LMS7002M::SetInterfaceFrequency(), status, TSGFC_RXTSP, TSGFCW_RXTSP, lime::LMS7002M::UploadAll(), GNUPlotPipe::write(), and GNUPlotPipe::writef().