LimeSuite-UML: StreamingFixture Class Reference
StreamingFixture Class Reference
#include <streamingFixture.h>
Public Member Functions
StreamingFixture ()
void SetUp ()
void TearDown ()
~StreamingFixture ()
Public Attributes
lime::IConnection * serPort
bool initialized
Detailed Description
Definition at line 9 of file streamingFixture.h.
Constructor & Destructor Documentation
StreamingFixture::StreamingFixture () inline
Definition at line 12 of file streamingFixture.h.
References lime::ConnectionRegistry::findConnections(), lime::ConnectionRegistry::freeConnection(), lime::IConnection::GetDeviceInfo(), info, initialized, lime::IConnection::IsOpen(), lime::ConnectionRegistry::makeConnection(), and serPort.
StreamingFixture::~StreamingFixture () inline
Definition at line 46 of file streamingFixture.h.
References lime::ConnectionRegistry::freeConnection(), and serPort.
Member Function Documentation
void StreamingFixture::SetUp () inline
Definition at line 33 of file streamingFixture.h.
References initialized, lime::IConnection::IsOpen(), and serPort.
void StreamingFixture::TearDown () inline
Definition at line 40 of file streamingFixture.h.
Member Data Documentation
bool StreamingFixture::initialized
Definition at line 52 of file streamingFixture.h.
Referenced by SetUp(), and StreamingFixture().
lime::IConnection* StreamingFixture::serPort
Definition at line 51 of file streamingFixture.h.
Referenced by SetUp(), StreamingFixture(), and ~StreamingFixture().
The documentation for this class was generated from the following file:
/home/erik/prefix/default/src/limesuite-dev/src/tests/streamingFixture.h