LimeSuite-UML: pnlBuffers Class Reference
pnlBuffers Class Reference
#include <pnlBuffers.h>
Public Member Functions
pnlBuffers (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int style=0, wxString name=wxEmptyString)
void Initialize (lms_device_t *pControl)
virtual ~pnlBuffers ()
virtual void UpdatePanel ()
void OnGPIOchanged (wxCommandEvent &event)
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
Protected Member Functions
DECLARE_EVENT_TABLE ()
Protected Attributes
wxCheckBox * chkDIO_DIR_CTRL1
wxCheckBox * chkDIO_DIR_CTRL2
wxCheckBox * chkDIO_BUFF_OE
wxCheckBox * chkIQ_SEL1_DIR
wxCheckBox * chkIQ_SEL2_DIR
wxCheckBox * chkG_PWR_DWN
lms_device_t * lmsControl
Detailed Description
Definition at line 8 of file pnlBuffers.h.
Constructor & Destructor Documentation
pnlBuffers::pnlBuffers (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int style = 0, wxString name = wxEmptyString)
Definition at line 19 of file pnlBuffers.cpp.
References lmsControl, OnGPIOchanged(), OnReadAll(), and OnWriteAll().
pnlBuffers::~pnlBuffers () virtual
Definition at line 77 of file pnlBuffers.cpp.
References OnGPIOchanged().
Member Function Documentation
pnlBuffers::DECLARE_EVENT_TABLE () protected
void pnlBuffers::Initialize (lms_device_t * pControl)
Definition at line 72 of file pnlBuffers.cpp.
References lmsControl.
Referenced by pnlBoardControls::SetupControls().
void pnlBuffers::OnGPIOchanged (wxCommandEvent & event)
Definition at line 96 of file pnlBuffers.cpp.
References LMS_GPIOWrite(), lmsControl, and setbit().
Referenced by pnlBuffers(), and ~pnlBuffers().
void pnlBuffers::OnReadAll (wxCommandEvent & event)
Definition at line 132 of file pnlBuffers.cpp.
Referenced by pnlBuffers().
void pnlBuffers::OnWriteAll (wxCommandEvent & event)
Definition at line 137 of file pnlBuffers.cpp.
Referenced by pnlBuffers().
void pnlBuffers::UpdatePanel () virtual
Definition at line 117 of file pnlBuffers.cpp.
References getbit(), LMS_GPIORead(), and lmsControl.
Member Data Documentation
wxCheckBox* pnlBuffers::chkDIO_BUFF_OE protected
Definition at line 23 of file pnlBuffers.h.
wxCheckBox* pnlBuffers::chkDIO_DIR_CTRL1 protected
Definition at line 21 of file pnlBuffers.h.
wxCheckBox* pnlBuffers::chkDIO_DIR_CTRL2 protected
Definition at line 22 of file pnlBuffers.h.
wxCheckBox* pnlBuffers::chkG_PWR_DWN protected
Definition at line 26 of file pnlBuffers.h.
wxCheckBox* pnlBuffers::chkIQ_SEL1_DIR protected
Definition at line 24 of file pnlBuffers.h.
wxCheckBox* pnlBuffers::chkIQ_SEL2_DIR protected
Definition at line 25 of file pnlBuffers.h.
lms_device_t* pnlBuffers::lmsControl protected
Definition at line 27 of file pnlBuffers.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlBuffers.h
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlBuffers.cpp