LimeSuite-UML: lms7002_pnlRFE_view Class Reference
lms7002_pnlRFE_view Class Reference
Implementing pnlRFE_view.
#include <lms7002_pnlRFE_view.h>
Public Member Functions
lms7002_pnlRFE_view (wxWindow *parent)
Constructor.
lms7002_pnlRFE_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlRFE_view
pnlRFE_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlRFE_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void ParameterChangeHandler (wxSpinEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlRFE_view
wxCheckBox * chkPD_LNA_RFE
wxCheckBox * chkPD_RLOOPB_1_RFE
wxCheckBox * chkPD_RLOOPB_2_RFE
wxCheckBox * chkPD_MXLOBUF_RFE
wxCheckBox * chkPD_QGEN_RFE
wxCheckBox * chkPD_RSSI_RFE
wxCheckBox * chkPD_TIA_RFE
wxCheckBox * chkEN_G_RFE
wxCheckBox * chkEN_DIR_RFE
wxCheckBox * chkEN_INSHSW_LB1_RFE
wxCheckBox * chkEN_INSHSW_LB2_RFE
wxCheckBox * chkEN_INSHSW_L_RFE
wxCheckBox * chkEN_INSHSW_W_RFE
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbSEL_PATH_RFE
wxStaticText * ID_STATICTEXT2
wxComboBox * cmbCAP_RXMXO_RFE
wxStaticText * ID_STATICTEXT3
wxComboBox * cmbCGSIN_LNA_RFE
wxStaticText * ID_STATICTEXT4
wxComboBox * cmbRCOMP_TIA_RFE
wxStaticText * ID_STATICTEXT5
wxComboBox * cmbRFB_TIA_RFE
wxCheckBox * chkEN_NEXTRX_RFE
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbICT_LNACMO_RFE
wxStaticText * ID_STATICTEXT13
wxComboBox * cmbICT_LNA_RFE
wxStaticText * ID_STATICTEXT6
NumericSlider * cmbDCOFFI_RFE
wxStaticText * ID_STATICTEXT7
NumericSlider * cmbDCOFFQ_RFE
wxStaticText * ID_STATICTEXT8
wxComboBox * cmbICT_LODC_RFE
wxCheckBox * chkEN_DCOFF_RXFE_RFE
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbCCOMP_TIA_RFE
wxStaticText * ID_STATICTEXT15
NumericSlider * cmbCFB_TIA_RFE
wxStaticText * ID_STATICTEXT16
wxComboBox * cmbG_LNA_RFE
wxStaticText * ID_STATICTEXT17
wxComboBox * cmbG_RXLOOPB_RFE
wxStaticText * ID_STATICTEXT18
wxComboBox * cmbG_TIA_RFE
wxStaticText * ID_STATICTEXT9
wxComboBox * cmbICT_LOOPB_RFE
wxStaticText * ID_STATICTEXT10
NumericSlider * cmbICT_TIAMAIN_RFE
wxStaticText * ID_STATICTEXT11
NumericSlider * cmbICT_TIAOUT_RFE
wxStaticText * ID_STATICTEXT19
wxComboBox * cmbCDC_I_RFE
wxStaticText * ID_STATICTEXT20
wxComboBox * cmbCDC_Q_RFE
Additional Inherited Members
Protected Types inherited from pnlRFE_view
enum {
ID_PD_LNA_RFE = 2048, ID_PD_RLOOPB_1_RFE, ID_PD_RLOOPB_2_RFE, ID_PD_MXLOBUF_RFE,
ID_PD_QGEN_RFE, ID_PD_RSSI_RFE, ID_PD_TIA_RFE, ID_EN_G_RFE,
ID_EN_DIR_RFE, ID_EN_INSHSW_LB1_RFE, ID_EN_INSHSW_LB2_RFE, ID_EN_INSHSW_L_RFE,
ID_EN_INSHSW_W_RFE, ID_SEL_PATH_RFE, ID_CAP_RXMXO_RFE, ID_CGSIN_LNA_RFE,
ID_RCOMP_TIA_RFE, ID_RFB_TIA_RFE, ID_EN_NEXTRX_RFE, ID_ICT_LNACMO_RFE,
ID_ICT_LNA_RFE, ID_DCOFFI_RFE, ID_DCOFFQ_RFE, ID_ICT_LODC_RFE,
ID_EN_DCOFF_RXFE_RFE, ID_CCOMP_TIA_RFE, ID_CFB_TIA_RFE, ID_G_LNA_RFE,
ID_G_RXLOOPB_RFE, ID_G_TIA_RFE, ID_ICT_LOOPB_RFE, ID_ICT_TIAMAIN_RFE,
ID_ICT_TIAOUT_RFE, ID_CDC_I_RFE, ID_CDC_Q_RFE
}
Detailed Description
Implementing pnlRFE_view.
Definition at line 19 of file lms7002_pnlRFE_view.h.
Constructor & Destructor Documentation
lms7002_pnlRFE_view::lms7002_pnlRFE_view (wxWindow * parent)
Constructor.
Definition at line 17 of file lms7002_pnlRFE_view.cpp.
lms7002_pnlRFE_view::lms7002_pnlRFE_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 23 of file lms7002_pnlRFE_view.cpp.
References CAP_RXMXO_RFE, CCOMP_TIA_RFE, CDC_I_RFE, CDC_Q_RFE, CFB_TIA_RFE, CGSIN_LNA_RFE, pnlRFE_view::chkEN_DCOFF_RXFE_RFE, pnlRFE_view::chkEN_DIR_RFE, pnlRFE_view::chkEN_G_RFE, pnlRFE_view::chkEN_INSHSW_L_RFE, pnlRFE_view::chkEN_INSHSW_LB1_RFE, pnlRFE_view::chkEN_INSHSW_LB2_RFE, pnlRFE_view::chkEN_INSHSW_W_RFE, pnlRFE_view::chkEN_NEXTRX_RFE, pnlRFE_view::chkPD_LNA_RFE, pnlRFE_view::chkPD_MXLOBUF_RFE, pnlRFE_view::chkPD_QGEN_RFE, pnlRFE_view::chkPD_RLOOPB_1_RFE, pnlRFE_view::chkPD_RLOOPB_2_RFE, pnlRFE_view::chkPD_RSSI_RFE, pnlRFE_view::chkPD_TIA_RFE, pnlRFE_view::cmbCAP_RXMXO_RFE, pnlRFE_view::cmbCCOMP_TIA_RFE, pnlRFE_view::cmbCDC_I_RFE, pnlRFE_view::cmbCDC_Q_RFE, pnlRFE_view::cmbCFB_TIA_RFE, pnlRFE_view::cmbCGSIN_LNA_RFE, pnlRFE_view::cmbDCOFFI_RFE, pnlRFE_view::cmbDCOFFQ_RFE, pnlRFE_view::cmbG_LNA_RFE, pnlRFE_view::cmbG_RXLOOPB_RFE, pnlRFE_view::cmbG_TIA_RFE, pnlRFE_view::cmbICT_LNA_RFE, pnlRFE_view::cmbICT_LNACMO_RFE, pnlRFE_view::cmbICT_LODC_RFE, pnlRFE_view::cmbICT_LOOPB_RFE, pnlRFE_view::cmbICT_TIAMAIN_RFE, pnlRFE_view::cmbICT_TIAOUT_RFE, pnlRFE_view::cmbRCOMP_TIA_RFE, pnlRFE_view::cmbRFB_TIA_RFE, pnlRFE_view::cmbSEL_PATH_RFE, DCOFFI_RFE, DCOFFQ_RFE, EN_DCOFF_RXFE_RFE, EN_DIR_RFE, EN_G_RFE, EN_INSHSW_L_RFE, EN_INSHSW_LB1_RFE, EN_INSHSW_LB2_RFE, EN_INSHSW_W_RFE, EN_NEXTRX_RFE, G_LNA_RFE, g_lna_rfe_IndexValuePairs, G_RXLOOPB_RFE, G_TIA_RFE, g_tia_rfe_IndexValuePairs, i, ICT_LNA_RFE, ICT_LNACMO_RFE, ICT_LODC_RFE, ICT_LOOPB_RFE, ICT_TIAMAIN_RFE, ICT_TIAOUT_RFE, LMS7param, PD_LNA_RFE, PD_MXLOBUF_RFE, PD_QGEN_RFE, PD_RLOOPB_1_RFE, PD_RLOOPB_2_RFE, PD_RSSI_RFE, PD_TIA_RFE, RCOMP_TIA_RFE, RFB_TIA_RFE, SEL_PATH_RFE, temp, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlRFE_view::Initialize (lms_device_t * pControl)
Definition at line 153 of file lms7002_pnlRFE_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlRFE_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlRFE_view.
Definition at line 203 of file lms7002_pnlRFE_view.cpp.
References pnlRFE_view::cmbDCOFFI_RFE, pnlRFE_view::cmbDCOFFQ_RFE, pnlRFE_view::cmbG_LNA_RFE, pnlRFE_view::cmbG_TIA_RFE, pnlRFE_view::cmbSEL_PATH_RFE, g_lna_rfe_IndexValuePairs, g_tia_rfe_IndexValuePairs, LMS7002_WXGUI::index2value(), LMS_WriteParam(), lmsControl, and wndId2Enum.
Referenced by ParameterChangeHandler().
void lms7002_pnlRFE_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlRFE_view.
Definition at line 194 of file lms7002_pnlRFE_view.cpp.
References ParameterChangeHandler().
void lms7002_pnlRFE_view::UpdateGUI ()
Definition at line 159 of file lms7002_pnlRFE_view.cpp.
References pnlRFE_view::chkEN_NEXTRX_RFE, pnlRFE_view::cmbDCOFFI_RFE, pnlRFE_view::cmbDCOFFQ_RFE, pnlRFE_view::cmbG_LNA_RFE, pnlRFE_view::cmbG_TIA_RFE, DCOFFI_RFE, DCOFFQ_RFE, G_LNA_RFE, g_lna_rfe_IndexValuePairs, G_TIA_RFE, g_tia_rfe_IndexValuePairs, LMS7param, LMS_ReadParam(), lmsControl, MAC, NumericSlider::SetValue(), TRX_GAIN_SRC, LMS7002_WXGUI::UpdateControlsByMap(), LMS7002_WXGUI::value2index(), and wndId2Enum.
Referenced by lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlRFE_view::lmsControl protected
Definition at line 33 of file lms7002_pnlRFE_view.h.
Referenced by Initialize(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlRFE_view::wndId2Enum protected
Definition at line 34 of file lms7002_pnlRFE_view.h.
Referenced by lms7002_pnlRFE_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlRFE_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlRFE_view.cpp