LimeSuite-UML: lms7002_pnlRBB_view Class Reference
lms7002_pnlRBB_view Class Reference
Implementing pnlRBB_view.
#include <lms7002_pnlRBB_view.h>
Public Member Functions
lms7002_pnlRBB_view (wxWindow *parent)
Constructor.
lms7002_pnlRBB_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
Public Member Functions inherited from pnlRBB_view
pnlRBB_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlRBB_view ()
Protected Member Functions
void ParameterChangeHandler (wxCommandEvent &event)
void ParameterChangeHandler (wxSpinEvent &event)
void OncmbBBLoopbackSelected (wxCommandEvent &event)
void OnbtnTuneFilter (wxCommandEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
Protected Attributes inherited from pnlRBB_view
wxCheckBox * chkPD_LPFH_RBB
wxCheckBox * chkPD_LPFL_RBB
wxCheckBox * chkPD_PGA_RBB
wxCheckBox * chkEN_G_RBB
wxCheckBox * chkEN_DIR_RBB
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbBBLoopback
wxStaticText * ID_STATICTEXT1
wxComboBox * cmbINPUT_CTL_PGA_RBB
wxStaticText * ID_STATICTEXT2
wxComboBox * cmbG_PGA_RBB
wxStaticText * ID_STATICTEXT3
NumericSlider * cmbC_CTL_PGA_RBB
wxRadioBox * rgrOSW_PGA_RBB
wxStaticText * ID_STATICTEXT4
wxComboBox * cmbR_CTL_LPF_RBB
wxStaticText * ID_STATICTEXT5
NumericSlider * cmbC_CTL_LPFH_RBB
wxStaticText * ID_STATICTEXT6
NumericSlider * cmbC_CTL_LPFL_RBB
wxStaticText * m_staticText309
wxTextCtrl * txtLowBW_MHz
wxButton * btnTuneFilter
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbRCC_CTL_LPFH_RBB
wxStaticText * ID_STATICTEXT8
wxComboBox * cmbRCC_CTL_LPFL_RBB
wxStaticText * ID_STATICTEXT9
wxComboBox * cmbICT_LPF_IN_RBB
wxStaticText * ID_STATICTEXT10
wxComboBox * cmbICT_LPF_OUT_RBB
wxStaticText * ID_STATICTEXT11
wxComboBox * cmbICT_PGA_OUT_RBB
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbICT_PGA_IN_RBB
wxStaticText * ID_STATICTEXT13
wxComboBox * cmbRCC_CTL_PGA_RBB
Additional Inherited Members
Protected Types inherited from pnlRBB_view
enum {
ID_PD_LPFH_RBB = 2048, ID_PD_LPFL_RBB, ID_PD_PGA_RBB, ID_EN_G_RBB,
ID_EN_DIR_RBB, ID_BBLoopback, ID_INPUT_CTL_PGA_RBB, ID_G_PGA_RBB,
ID_C_CTL_PGA_RBB, ID_OSW_PGA_RBB, ID_R_CTL_LPF_RBB, ID_C_CTL_LPFH_RBB,
ID_C_CTL_LPFL_RBB, ID_TXT_LOWBW, ID_BTN_TUNE_FILTER, ID_RCC_CTL_LPFH_RBB,
ID_RCC_CTL_LPFL_RBB, ID_ICT_LPF_IN_RBB, ID_ICT_LPF_OUT_RBB, ID_ICT_PGA_OUT_RBB,
ID_ICT_PGA_IN_RBB, ID_RCC_CTL_PGA_RBB
}
Detailed Description
Implementing pnlRBB_view.
Definition at line 17 of file lms7002_pnlRBB_view.h.
Constructor & Destructor Documentation
lms7002_pnlRBB_view::lms7002_pnlRBB_view (wxWindow * parent)
Constructor.
Definition at line 10 of file lms7002_pnlRBB_view.cpp.
lms7002_pnlRBB_view::lms7002_pnlRBB_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 17 of file lms7002_pnlRBB_view.cpp.
References C_CTL_LPFH_RBB, C_CTL_LPFL_RBB, C_CTL_PGA_RBB, pnlRBB_view::chkEN_DIR_RBB, pnlRBB_view::chkEN_G_RBB, pnlRBB_view::chkPD_LPFH_RBB, pnlRBB_view::chkPD_LPFL_RBB, pnlRBB_view::chkPD_PGA_RBB, pnlRBB_view::cmbC_CTL_LPFH_RBB, pnlRBB_view::cmbC_CTL_LPFL_RBB, pnlRBB_view::cmbC_CTL_PGA_RBB, pnlRBB_view::cmbG_PGA_RBB, pnlRBB_view::cmbICT_LPF_IN_RBB, pnlRBB_view::cmbICT_LPF_OUT_RBB, pnlRBB_view::cmbICT_PGA_IN_RBB, pnlRBB_view::cmbICT_PGA_OUT_RBB, pnlRBB_view::cmbINPUT_CTL_PGA_RBB, pnlRBB_view::cmbR_CTL_LPF_RBB, pnlRBB_view::cmbRCC_CTL_LPFH_RBB, pnlRBB_view::cmbRCC_CTL_LPFL_RBB, pnlRBB_view::cmbRCC_CTL_PGA_RBB, EN_DIR_RBB, EN_G_RBB, G_PGA_RBB, i, ICT_LPF_IN_RBB, ICT_LPF_OUT_RBB, ICT_PGA_IN_RBB, ICT_PGA_OUT_RBB, INPUT_CTL_PGA_RBB, LMS7param, OSW_PGA_RBB, PD_LPFH_RBB, PD_LPFL_RBB, PD_PGA_RBB, R_CTL_LPF_RBB, RCC_CTL_LPFH_RBB, RCC_CTL_LPFL_RBB, RCC_CTL_PGA_RBB, pnlRBB_view::rgrOSW_PGA_RBB, temp, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlRBB_view::Initialize (lms_device_t * pControl)
Definition at line 87 of file lms7002_pnlRBB_view.cpp.
References lmsControl.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlRBB_view::OnbtnTuneFilter (wxCommandEvent & event) protected virtual
Reimplemented from pnlRBB_view.
Definition at line 181 of file lms7002_pnlRBB_view.cpp.
References LMS7param, LMS_CH_RX, LMS_ReadParam(), LMS_SetLPFBW(), LMS_Synchronize(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, status, pnlRBB_view::txtLowBW_MHz, and UpdateGUI().
void lms7002_pnlRBB_view::OncmbBBLoopbackSelected (wxCommandEvent & event) protected virtual
Reimplemented from pnlRBB_view.
Definition at line 118 of file lms7002_pnlRBB_view.cpp.
References pnlRBB_view::cmbBBLoopback, EN_LB_LPFH_RBB, EN_LB_LPFL_RBB, LMS7param, LMS_WriteParam(), and lmsControl.
void lms7002_pnlRBB_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlRBB_view.
Definition at line 102 of file lms7002_pnlRBB_view.cpp.
References LMS_WriteParam(), lmsControl, and wndId2Enum.
Referenced by ParameterChangeHandler().
void lms7002_pnlRBB_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlRBB_view.
Definition at line 93 of file lms7002_pnlRBB_view.cpp.
References ParameterChangeHandler().
void lms7002_pnlRBB_view::UpdateGUI ()
Definition at line 140 of file lms7002_pnlRBB_view.cpp.
References pnlRBB_view::cmbBBLoopback, pnlRBB_view::cmbC_CTL_PGA_RBB, pnlRBB_view::cmbG_PGA_RBB, EN_LB_LPFH_RBB, EN_LB_LPFL_RBB, LMS7param, LMS_ReadParam(), LMS_WriteParam(), lmsControl, MAC, MIMO_SISO, TRX_GAIN_SRC, LMS7002_WXGUI::UpdateControlsByMap(), and wndId2Enum.
Referenced by OnbtnTuneFilter(), and lms7002_mainPanel::UpdateVisiblePanel().
Member Data Documentation
lms_device_t* lms7002_pnlRBB_view::lmsControl protected
Definition at line 33 of file lms7002_pnlRBB_view.h.
Referenced by Initialize(), OnbtnTuneFilter(), OncmbBBLoopbackSelected(), ParameterChangeHandler(), and UpdateGUI().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlRBB_view::wndId2Enum protected
Definition at line 34 of file lms7002_pnlRBB_view.h.
Referenced by lms7002_pnlRBB_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlRBB_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlRBB_view.cpp