LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/mcu_program/common_src/spi.h File Reference
spi.h File Reference
#include "typedefs.h"
Functions
void SPI_write_slow (uint16_t spiAddrReg, uint16_t spiDataReg)
uint16_t SPI_read_slow (uint16_t spiAddrReg)
void SPI_write (uint16_t spiAddrReg, uint16_t spiDataReg)
uint16_t SPI_read (uint16_t spiAddrReg)
void SPI_writeSlow (uint16_t spiAddrReg, uint16_t spiDataReg)
uint16_t SPI_readSlow (uint16_t spiAddrReg)
void Modify_SPI_Reg_bits_WrOnly (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data, const uint16_t initialValue)
void Modify_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data)
uint16_t Get_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits)
void SPI_read_batch (const uint16_t *addr, uint16_t *values, uint8_t cnt)
void SPI_write_batch (const uint16_t *addr, const uint16_t *values, uint8_t cnt)
void Modify_SPI_Reg_mask (const uint16_t *addr, const uint16_t *values, const uint16_t *masks, uint8_t cnt)
Modifies given registers with values applied using masks.
int BeginBatch (const char *name)
void EndBatch ()
Function Documentation
int BeginBatch (const char * name)
Definition at line 142 of file spi.cpp.
References batchActive, and bName.
Referenced by TuneRxFilterSetup(), and TuneTxFilterSetup().
void EndBatch ()
Definition at line 154 of file spi.cpp.
References bName, i, temp, and val.
Referenced by TuneRxFilterSetup(), and TuneTxFilterSetup().
uint16_t Get_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits)
Definition at line 94 of file spi.cpp.
References SPI_read().
Referenced by lime::LMS7002M::CalibrateInternalADC(), lime::LMS7002M::CalibrateRP_BIAS(), CalibrateRx(), lime::LMS7002M::CalibrateRx(), CalibrateRxDCAuto(), CalibrateRxSetup(), CalibrateTx(), lime::LMS7002M::CalibrateTx(), CalibrateTxDCAuto(), CalibrateTxSetup(), ChangeUntilReachRSSI(), CheckSaturationRx(), CheckSaturationTxRx(), GetFrequencyCGEN(), GetFrequencySX(), GetReferenceClk_TSP_MHz(), lime::LMS7002M::GetRSSI(), IsPLLTuned(), ReadCMP(), RunAGC(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), lime::LMS7002M::SetConnection(), SetFrequencySX(), SetupCGEN(), TuneRxFilter(), TuneRxFilterSetup(), TuneTxFilter(), TuneTxFilterSetup(), and UpdateRSSIDelay().
void Modify_SPI_Reg_bits (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data)
Definition at line 65 of file spi.cpp.
References batchActive, i, SPI_read(), and SPI_write().
Referenced by BinarySearch(), lime::LMS7002M::CalibrateInternalADC(), CalibrateIQImbalance(), lime::LMS7002M::CalibrateRP_BIAS(), CalibrateRx(), CalibrateRxDCAuto(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxDCAuto(), CalibrateTxSetup(), ChangeUntilReachRSSI(), CheckSaturationRx(), CheckSaturationTxRx(), EnableMIMOBuffersIfNecessary(), FlipRisingEdge(), GetFrequencySX(), lime::LMS7002M::GetRSSI(), lime::LMS7002M::LoadDC_REG_IQ(), RunAGC(), RxFilterSearch(), SearchTxFilterCCAL_RCAL(), SetDefaultsSX(), SetFrequencyCGEN(), SetFrequencySX(), SetTxLPF_PDs(), SetupCGEN(), TuneRxFilter(), TuneRxFilterSetup(), TuneTxFilter(), TuneTxFilterSetup(), and TuneVCO().
void Modify_SPI_Reg_bits_WrOnly (const uint16_t SPI_reg_addr, const uint8_t bits, const uint16_t new_bits_data, const uint16_t initialValue)
Definition at line 37 of file spi.cpp.
References batchActive, i, and SPI_write().
void Modify_SPI_Reg_mask (const uint16_t * addr, const uint16_t * values, const uint16_t * masks, uint8_t cnt)
Modifies given registers with values applied using masks.
Parameters
addr array of register addresses
masks array of applied masks
values array of values to be written
start starting index of given arrays
stop end index of given arrays
Definition at line 244 of file spi.cpp.
References i, SPI_read(), and SPI_write().
uint16_t SPI_read (uint16_t spiAddrReg)
Referenced by lime::LMS7002M::CalibrateInternalADC(), lime::LMS7002M::CalibrateRP_BIAS(), CalibrateRx(), lime::LMS7002M::CalibrateRx(), CalibrateRxDCAuto(), CalibrateRxSetup(), CalibrateTx(), lime::LMS7002M::CalibrateTx(), CalibrateTxSetup(), ClockLogicResets(), EnableChannelPowerControls(), EnableMIMOBuffersIfNecessary(), GetFrequencySX(), GetRSSI(), main(), MCU_RunProcedure(), MCU_SetParameter(), MCU_UploadProgram(), MCU_WaitForStatus(), ProxyRead(), ProxyWrite(), ReadAnalogDC(), ReadDCCorrector(), RunAGC(), SaveChipState(), SetFrequencySX(), SetTxLPF_PDs(), StoreState(), TuneRxFilter(), TuneRxFilterSetup(), TuneTxFilter(), TuneTxFilterSetup(), and WriteMaskedRegs().
void SPI_read_batch (const uint16_t * addr, uint16_t * values, uint8_t cnt)
Definition at line 100 of file spi.cpp.
References i, readCnt, and lime::IConnection::TransactSPI().
uint16_t SPI_read_slow (uint16_t spiAddrReg)
Referenced by ProxyRead().
uint16_t SPI_readSlow (uint16_t spiAddrReg)
void SPI_write (uint16_t spiAddrReg, uint16_t spiDataReg)
Referenced by lime::LMS7002M::CalibrateInternalADC(), CalibrateIQImbalance(), CalibrateRx(), CalibrateRxDCAuto(), CalibrateRxSetup(), CalibrateTx(), CalibrateTxSetup(), ClockLogicResets(), EnableChannelPowerControls(), EnableMIMOBuffersIfNecessary(), GetFrequencySX(), LoadDC_REG_TX_IQ(), MCU_SetParameter(), MCU_UploadProgram(), MCU_WaitForStatus(), ProxyRead(), ReadAnalogDC(), ReadDCCorrector(), RunAGC(), SaveChipState(), SetDefaultsSX(), SetFrequencySX(), SetNCOFrequency(), SetRxGFIR3Coefficients(), SetTxLPF_PDs(), StoreState(), TuneRxFilter(), TuneRxFilterSetup(), TuneTxFilter(), TuneTxFilterSetup(), WriteAnalogDC(), and WriteMaskedRegs().
void SPI_write_batch (const uint16_t * addr, const uint16_t * values, uint8_t cnt)
Definition at line 111 of file spi.cpp.
References batchActive, i, lime::IConnection::TransactSPI(), and writeCnt.
Referenced by MCU_RunProcedure(), MCU_UploadProgram(), and SaveChipState().
void SPI_write_slow (uint16_t spiAddrReg, uint16_t spiDataReg)
Referenced by ProxyWrite().
void SPI_writeSlow (uint16_t spiAddrReg, uint16_t spiDataReg)