LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/python/CMakeLists.txt File Reference
/home/erik/prefix/default/src/soapysdr/python/CMakeLists.txt File Reference
Functions
cmake_minimum_required (VERSION 2.8) project(SoapySDRPython CXX) enable_testing() find_package(SoapySDR NO_MODULE REQUIRED) find_package(SWIG) message(STATUS"SWIG_FOUND
print (get_python_lib(plat_specific=True, prefix=''))" OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE PYTHON_INSTALL_DIR_SYSCONF) set(PYTHON_INSTALL_DIR "$
CACHE STRING python install prefix message (STATUS"PYTHON_INSTALL_DIR: \${prefix}/${PYTHON_INSTALL_DIR}") set(PYTHON_CONFIG_EXECUTABLE $
config CACHE FILEPATH Path to python config executable if (USE_PYTHON_CONFIG AND EXISTS ${PYTHON_CONFIG_EXECUTABLE}) execute_process(COMMAND $
includes OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE PYTHON_INCLUDE_DIRS string (REGEX REPLACE"^[-I]"""PYTHON_INCLUDE_DIRS"${PYTHON_INCLUDE_DIRS}") string(REGEX REPLACE"[ ]-I"" "PYTHON_INCLUDE_DIRS"$
separate_arguments (PYTHON_INCLUDE_DIRS) execute_process(COMMAND $
ldflags OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE PYTHON_LIBRARIES string (STRIP"${PYTHON_LIBRARIES}"PYTHON_LIBRARIES) set(PYTHONLIBS_VERSION_STRING $
set (PYTHONLIBS_FOUND TRUE) else() find_package(PythonLibs) endif() message(STATUS"PYTHONLIBS_FOUND
PYTHON_VERSION_MATCH OFF add_feature_info (Python ENABLE_PYTHON"python bindings v${PYTHON_VERSION_STRING}") if(NOT ENABLE_PYTHON) return() endif() include(UseSWIG) include_directories($
Variables
SWIG_FOUND
PYTHONINTERP_FOUND
PYTHONLIBS_FOUND
PYTHON_DEBUG_OK
Function Documentation
PYTHON_VERSION_MATCH OFF add_feature_info (Python ENABLE_PYTHON"python bindings v${PYTHON_VERSION_STRING}")
Definition at line 125 of file CMakeLists.txt.
cmake_minimum_required (VERSION 2. 8)
Definition at line 4 of file CMakeLists.txt.
References PYTHONINTERP_FOUND, and SWIG_VERSION.
config CACHE FILEPATH Path to python config executable if (USE_PYTHON_CONFIG AND EXISTS ${PYTHON_CONFIG_EXECUTABLE})
Definition at line 45 of file CMakeLists.txt.
CACHE STRING python install prefix message (STATUS"PYTHON_INSTALL_DIR: \${prefix}/${PYTHON_INSTALL_DIR}")
Definition at line 38 of file CMakeLists.txt.
print (get_python_lib(plat_specific=True, prefix=''))
Definition at line 33 of file CMakeLists.txt.
References install().
Referenced by swig_doc::make_swig_interface_file(), MeasureDelay::measure_delay(), SimpleSiggen::siggen_app(), BasicStreamTests.TestBasicStreaming::testRxBurstAtTime(), BasicStreamTests.TestBasicStreaming::testRxBurstNow(), BasicStreamTests.TestBasicStreaming::testRxContinuous(), BasicStreamTests.TestBasicStreaming::testRxLateBurst(), BasicStreamTests.TestBasicStreaming::testTime(), and BasicStreamTests.TestBasicStreaming::testTxLate().
separate_arguments (PYTHON_INCLUDE_DIRS)
Definition at line 52 of file CMakeLists.txt.
set (PYTHONLIBS_FOUND TRUE)
Definition at line 59 of file CMakeLists.txt.
includes OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE PYTHON_INCLUDE_DIRS string (REGEX REPLACE"^"""PYTHON_INCLUDE_DIRS"${PYTHON_INCLUDE_DIRS}" [-I])
Definition at line 50 of file CMakeLists.txt.
ldflags OUTPUT_STRIP_TRAILING_WHITESPACE OUTPUT_VARIABLE PYTHON_LIBRARIES string (STRIP"${PYTHON_LIBRARIES}" PYTHON_LIBRARIES)
Definition at line 57 of file CMakeLists.txt.
Variable Documentation
PYTHON_DEBUG_OK
Definition at line 124 of file CMakeLists.txt.
PYTHONINTERP_FOUND
Definition at line 124 of file CMakeLists.txt.
Referenced by cmake_minimum_required().
PYTHONLIBS_FOUND
Definition at line 124 of file CMakeLists.txt.
SWIG_FOUND
Definition at line 64 of file CMakeLists.txt.