LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/apps/SoapySDRUtil.cpp File Reference
SoapySDRUtil.cpp File Reference
#include <SoapySDR/Version.hpp>
#include <SoapySDR/Modules.hpp>
#include <SoapySDR/Registry.hpp>
#include <SoapySDR/Device.hpp>
#include <SoapySDR/ConverterRegistry.hpp>
#include <algorithm>
#include <cstdlib>
#include <cstddef>
#include <iostream>
#include <iomanip>
#include <getopt.h>
Functions
std::string SoapySDRDeviceProbe (SoapySDR::Device *)
int SoapySDRRateTest (const std::string &argStr, const double sampleRate, const std::string &channelStr, const std::string &directionStr)
static void printBanner (void)
static int printHelp (void)
static int printInfo (void)
static int findDevices (const std::string &argStr, const bool sparse)
static int makeDevice (const std::string &argStr)
static int probeDevice (const std::string &argStr)
static int checkDriver (const std::string &driverName)
int main (int argc, char *argv[])
Function Documentation
static int checkDriver (const std::string & driverName) static
Definition at line 205 of file SoapySDRUtil.cpp.
References SoapySDR::Registry::listFindFunctions(), and SoapySDR::loadModules.
Referenced by main().
static int findDevices (const std::string & argStr, const bool sparse) static
Definition at line 120 of file SoapySDRUtil.cpp.
References SoapySDR.Device::enumerate, i, and SoapySDR::KwargsToString.
Referenced by main().
int main (int argc, char * argv[])
Definition at line 229 of file SoapySDRUtil.cpp.
References checkDriver(), findDevices(), getopt_long_only(), makeDevice(), no_argument, optarg, optional_argument, printBanner(), printHelp(), printInfo(), probeDevice(), SoapySDRRateTest(), and string().
static int makeDevice (const std::string & argStr) static
Definition at line 158 of file SoapySDRUtil.cpp.
References device, SoapySDR.Device::make, and SoapySDR.Device::unmake.
Referenced by main().
static void printBanner (void) static
Definition at line 26 of file SoapySDRUtil.cpp.
Referenced by main().
static int printHelp (void) static
Definition at line 37 of file SoapySDRUtil.cpp.
Referenced by main().
static int printInfo (void) static
Definition at line 65 of file SoapySDRUtil.cpp.
References SoapySDR::getABIVersion, SoapySDR::getAPIVersion, SoapySDR::getLibVersion, SoapySDR::getModuleVersion, SoapySDR::getRootPath, SoapySDR::ConverterRegistry::listAvailableSourceFormats(), SoapySDR::Registry::listFindFunctions(), SoapySDR::listModules, SoapySDR::listSearchPaths, SoapySDR::ConverterRegistry::listTargetFormats(), SoapySDR::loadModule, modules, and string().
Referenced by main().
static int probeDevice (const std::string & argStr) static
Definition at line 184 of file SoapySDRUtil.cpp.
References device, SoapySDR.Device::make, SoapySDRDeviceProbe(), and SoapySDR.Device::unmake.
Referenced by main().
std::string SoapySDRDeviceProbe (SoapySDR::Device *)
Definition at line 208 of file SoapySDRProbe.cpp.
References chan, SoapySDR.Device::getDriverKey(), SoapySDR.Device::getHardwareInfo(), SoapySDR.Device::getHardwareKey(), SoapySDR.Device::getNumChannels(), SoapySDR.Device::getSettingInfo(), SoapySDR.Device::hasHardwareTime(), SoapySDR.Device::listClockSources(), SoapySDR.Device::listGPIOBanks(), SoapySDR.Device::listRegisterInterfaces(), SoapySDR.Device::listSensors(), SoapySDR.Device::listTimeSources(), SoapySDR.Device::listUARTs(), probeChannel(), SOAPY_SDR_RX, SOAPY_SDR_TX, string(), and toString().
Referenced by probeDevice().
int SoapySDRRateTest (const std::string & argStr, const double sampleRate, const std::string & channelStr, const std::string & directionStr)
Definition at line 117 of file SoapyRateTest.cpp.
References chan, SoapySDR.Device::closeStream(), device, format, SoapySDR::formatToSize, SoapySDR.Device::getNativeStreamFormat(), SoapySDR::KwargsFromString, SoapySDR.Device::make, runRateTestStreamLoop(), SoapySDR.Device::setSampleRate(), SoapySDR.Device::setupStream(), SOAPY_SDR_RX, SOAPY_SDR_TX, stream, and SoapySDR.Device::unmake.
Referenced by main().