LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/LoggerC.cpp File Reference
LoggerC.cpp File Reference
#include <SoapySDR/Logger.h>
#include <cstdio>
#include <cstdlib>
#include <string>
#include <iostream>
Macros
#define checkLogLevelEnvStr(level) if (logLevelEnvStr == #level) return SOAPY_SDR_ ## level
#define ANSI_COLOR_RED "\x1b[31m"
#define ANSI_COLOR_GREEN "\x1b[32m"
#define ANSI_COLOR_YELLOW "\x1b[33m"
#define ANSI_COLOR_BLUE "\x1b[34m"
#define ANSI_COLOR_MAGENTA "\x1b[35m"
#define ANSI_COLOR_CYAN "\x1b[36m"
#define ANSI_COLOR_RESET "\x1b[0m"
#define ANSI_COLOR_BOLD "\x1b[1m"
Functions
std::string getEnvImpl (const char *name)
static SoapySDRLogLevel getDefaultLogLevel (void)
void defaultLogHandler (const SoapySDRLogLevel logLevel, const char *message)
void SoapySDR_log (const SoapySDRLogLevel logLevel, const char *message)
void SoapySDR_vlogf (const SoapySDRLogLevel logLevel, const char *format, va_list argList)
void SoapySDR_registerLogHandler (const SoapySDRLogHandler handler)
void SoapySDR_setLogLevel (const SoapySDRLogLevel logLevel)
Variables
static SoapySDRLogHandler registeredLogHandler = &defaultLogHandler
static SoapySDRLogLevel registeredLogLevel = getDefaultLogLevel()
Macro Definition Documentation
#define ANSI_COLOR_BLUE "\x1b[34m"
Definition at line 58 of file LoggerC.cpp.
#define ANSI_COLOR_BOLD "\x1b[1m"
Definition at line 62 of file LoggerC.cpp.
Referenced by defaultLogHandler().
#define ANSI_COLOR_CYAN "\x1b[36m"
Definition at line 60 of file LoggerC.cpp.
#define ANSI_COLOR_GREEN "\x1b[32m"
Definition at line 56 of file LoggerC.cpp.
Referenced by defaultLogHandler().
#define ANSI_COLOR_MAGENTA "\x1b[35m"
Definition at line 59 of file LoggerC.cpp.
#define ANSI_COLOR_RED "\x1b[31m"
Definition at line 55 of file LoggerC.cpp.
Referenced by defaultLogHandler().
#define ANSI_COLOR_RESET "\x1b[0m"
Definition at line 61 of file LoggerC.cpp.
Referenced by defaultLogHandler().
#define ANSI_COLOR_YELLOW "\x1b[33m"
Definition at line 57 of file LoggerC.cpp.
Referenced by defaultLogHandler().
#define checkLogLevelEnvStr (level) if (logLevelEnvStr == #level) return SOAPY_SDR_ ## level
Referenced by getDefaultLogLevel().
Function Documentation
void defaultLogHandler (const SoapySDRLogLevel logLevel, const char * message)
Definition at line 67 of file LoggerC.cpp.
References ANSI_COLOR_BOLD, ANSI_COLOR_GREEN, ANSI_COLOR_RED, ANSI_COLOR_RESET, ANSI_COLOR_YELLOW, SOAPY_SDR_CRITICAL, SOAPY_SDR_DEBUG, SOAPY_SDR_ERROR, SOAPY_SDR_FATAL, SOAPY_SDR_INFO, SOAPY_SDR_NOTICE, SOAPY_SDR_SSI, SOAPY_SDR_TRACE, and SOAPY_SDR_WARNING.
static SoapySDRLogLevel getDefaultLogLevel (void) static
Definition at line 15 of file LoggerC.cpp.
References ap, checkLogLevelEnvStr, ERROR, getEnvImpl(), calc_fmcw_peaks::r, SOAPY_SDR_FATAL, SOAPY_SDR_INFO, SOAPY_SDR_TRACE, and string().
std::string getEnvImpl (const char * name)
Definition at line 23 of file Modules.cpp.
References buffer, getEnvImpl(), SoapySDR::getRootPath, len, and string().
Referenced by getDefaultLogLevel(), getEnvImpl(), and searchModulePath().
void SoapySDR_log (const SoapySDRLogLevel logLevel, const char * message)
Send a message to the registered logger.
Parameters
logLevel a possible logging level
message a logger message string
Definition at line 88 of file LoggerC.cpp.
References registeredLogHandler, registeredLogLevel, and SOAPY_SDR_SSI.
Referenced by SoapySDR_vlogf().
void SoapySDR_registerLogHandler (const SoapySDRLogHandler handler)
Register a new system log handler. Platforms should call this to replace the default stdio handler.
Definition at line 105 of file LoggerC.cpp.
References registeredLogHandler.
Referenced by SoapySDR::registerLogHandler().
void SoapySDR_setLogLevel (const SoapySDRLogLevel logLevel)
Set the log level threshold. Log messages with lower priority are dropped.
Definition at line 110 of file LoggerC.cpp.
References registeredLogLevel.
void SoapySDR_vlogf (const SoapySDRLogLevel logLevel, const char * format, va_list argList)
Send a message to the registered logger.
Parameters
logLevel a possible logging level
format a printf style format string
argList an argument list for the formatter
Definition at line 94 of file LoggerC.cpp.
References message(), registeredLogLevel, and SoapySDR_log().
Referenced by SoapySDR_logf(), and SoapySDR::vlogf().
Variable Documentation
SoapySDRLogHandler registeredLogHandler = &defaultLogHandler static
Definition at line 83 of file LoggerC.cpp.
Referenced by SoapySDR_log(), and SoapySDR_registerLogHandler().
SoapySDRLogLevel registeredLogLevel = getDefaultLogLevel() static
Definition at line 84 of file LoggerC.cpp.
Referenced by SoapySDR_log(), SoapySDR_setLogLevel(), and SoapySDR_vlogf().