LimeSuite-UML: gr::radar::soapysdr_echotimer Class Reference
gr::radar::soapysdr_echotimer Class Reference abstract
<+description of block+>
#include <soapysdr_echotimer.h>
Public Types
typedef boost::shared_ptr< soapysdr_echotimer > sptr
Public Member Functions
virtual int num_delay_samps ()=0
virtual void set_num_delay_samps (int num_samps)=0
virtual float wait_rx ()=0
virtual float wait_tx ()=0
virtual void set_wait (float wait_rx, float wait_tx)=0
virtual void set_rx_gain (size_t chan, float gain)=0
virtual void set_tx_gain (size_t chan, float gain)=0
Static Public Member Functions
static sptr make (int samp_rate, float center_freq, int num_delay_samps, std::string args="device args", std::string antenna_tx="BAND2", float gain_tx=0, float bw_tx=0, float timeout_tx=.1, float wait_tx=.001, float lo_offset_tx=0, std::string antenna_rx="LNAH", float gain_rx=0, float bw_rx=0, float timeout_rx=.1, float wait_rx=.001, float lo_offset_rx=0, const std::string &len_key="packet_len")
Return a shared_ptr to a new instance of radar::soapysdr_echotimer.
Detailed Description
<+description of block+>
Definition at line 37 of file soapysdr_echotimer.h.
Member Typedef Documentation
typedef boost::shared_ptr<soapysdr_echotimer> gr::radar::soapysdr_echotimer::sptr
Definition at line 40 of file soapysdr_echotimer.h.
Member Function Documentation
soapysdr_echotimer::sptr gr::radar::soapysdr_echotimer::make (int samp_rate, float center_freq, int num_delay_samps, std::string args = "device args", std::string antenna_tx = "BAND2", float gain_tx = 0, float bw_tx = 0, float timeout_tx = .1, float wait_tx = .001, float lo_offset_tx = 0, std::string antenna_rx = "LNAH", float gain_rx = 0, float bw_rx = 0, float timeout_rx = .1, float wait_rx = .001, float lo_offset_rx = 0, const std::string & len_key = "packet_len") static
Return a shared_ptr to a new instance of radar::soapysdr_echotimer.
To avoid accidental use of raw pointers, radar::soapysdr_echotimer's constructor is in a private implementation class. radar::soapysdr_echotimer::make is the public interface for creating new instances.
Definition at line 33 of file soapysdr_echotimer_impl.cc.
Referenced by _wrap_soapysdr_echotimer_make().
virtual int gr::radar::soapysdr_echotimer::num_delay_samps () pure virtual
Implemented in gr::radar::soapysdr_echotimer_impl.
Referenced by _wrap_soapysdr_echotimer_num_delay_samps().
virtual void gr::radar::soapysdr_echotimer::set_num_delay_samps (int num_samps) pure virtual
Implemented in gr::radar::soapysdr_echotimer_impl.
virtual void gr::radar::soapysdr_echotimer::set_rx_gain (size_t chan, float gain) pure virtual
Implemented in gr::radar::soapysdr_echotimer_impl.
virtual void gr::radar::soapysdr_echotimer::set_tx_gain (size_t chan, float gain) pure virtual
Implemented in gr::radar::soapysdr_echotimer_impl.
virtual void gr::radar::soapysdr_echotimer::set_wait (float wait_rx, float wait_tx) pure virtual
Implemented in gr::radar::soapysdr_echotimer_impl.
virtual float gr::radar::soapysdr_echotimer::wait_rx () pure virtual
Implemented in gr::radar::soapysdr_echotimer_impl.
Referenced by _wrap_soapysdr_echotimer_wait_rx().
virtual float gr::radar::soapysdr_echotimer::wait_tx () pure virtual
Implemented in gr::radar::soapysdr_echotimer_impl.
Referenced by _wrap_soapysdr_echotimer_wait_tx().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/gr-radar-dev/include/radar/soapysdr_echotimer.h
/home/erik/prefix/default/src/gr-radar-dev/lib/soapysdr_echotimer_impl.cc