LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/examples/basicRX.cpp File Reference
basicRX.cpp File Reference
minimal RX example
#include "lime/LimeSuite.h"
#include <iostream>
#include <chrono>
Functions
int error ()
int main (int argc, char **argv)
Variables
lms_device_t * device = NULL
Detailed Description
minimal RX example
Author
Lime Microsystems (www.limemicro.com)
Definition in file basicRX.cpp.
Function Documentation
int error ()
Definition at line 18 of file basicRX.cpp.
References device, and LMS_Close().
Referenced by glewGetErrorString(), main(), and lime::FPGA::SetPllFrequency().
int main (int argc, char ** argv)
Definition at line 25 of file basicRX.cpp.
References buffer, lms_stream_t::channel, lms_stream_t::dataFmt, device, error(), lms_stream_t::fifoSize, GNUPlotPipe::flush(), lms_stream_t::isTx, list, LMS_CH_RX, LMS_Close(), LMS_DestroyStream(), LMS_EnableChannel(), lms_stream_t::LMS_FMT_I12, LMS_GetDeviceList(), LMS_Init(), LMS_Open(), LMS_RecvStream(), LMS_SetLOFrequency(), LMS_SetSampleRate(), LMS_SetTestSignal(), LMS_SetupStream(), LMS_StartStream(), LMS_StopStream(), LMS_TESTSIG_NCODIV8, t1, lms_stream_t::throughputVsLatency, GNUPlotPipe::write(), and GNUPlotPipe::writef().
Variable Documentation
lms_device_t* device = NULL
Definition at line 16 of file basicRX.cpp.
Referenced by LimeSDRTest_USB::ADF4002Test(), lime::Si5351C::ClearStatus(), lime::LMS7_Device::CreateDevice(), LMS_Programing_wxgui::DoProgramming(), lime::ConnectionFX3Entry::enumerate(), error(), getDeviceFromTable(), lime::GetDeviceName(), lime::Si5351C::GetStatusBits(), LimeSDRTest::GPIFClkTest(), LimeSDRTest::InitFPGATest(), lime::Si5351C::Initialize(), initResizable(), lime::ConnectionXillybus::IsOpen(), LimeSDRTest::LimeSDRTest(), LimeSDRTest::LMS7002mTest(), main(), makeDevice(), lms7002_pnlCLKGEN_view::onbtnCalculateClick(), lms7002_pnlCLKGEN_view::onbtnTuneClick(), lime::ConnectionFX3::Open(), probeDevice(), lime::LMS64CProtocol::ProgramUpdate(), lime::ConnectionFT601::ProgramWrite(), LimeSDRTest::Reg_read(), LimeSDRTest::Reg_write(), LimeSDRTest_Mini::RFTest(), LimeSDRTest_USB::RFTest(), LimeSDRTest::RunTest(), lime::Si5351C::Si5351C(), LimeSDRTest_USB::Si5351CTest(), SoapySDRRateTest(), LimeSDRTest::TransferLMS64C(), lime::Si5351C::UploadConfiguration(), LimeSDRTest::VCTCXOTest(), and LimeSDRTest::~LimeSDRTest().