LimeSuite-UML: lms7002_pnlRxTSP_view Class Reference
lms7002_pnlRxTSP_view Class Reference
Implementing pnlRxTSP_view.
#include <lms7002_pnlRxTSP_view.h>
Public Member Functions
lms7002_pnlRxTSP_view (wxWindow *parent)
Constructor.
lms7002_pnlRxTSP_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
void Initialize (lms_device_t *pControl)
void UpdateGUI ()
void UpdateNCOinputs ()
Public Member Functions inherited from pnlRxTSP_view
pnlRxTSP_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxTAB_TRAVERSAL)
~pnlRxTSP_view ()
Protected Member Functions
void ParameterChangeHandler (wxSpinEvent &event)
void ParameterChangeHandler (wxCommandEvent &event)
void OnNCOSelectionChange (wxCommandEvent &event)
void OnbtnReadBISTSignature (wxCommandEvent &event)
void OnbtnLoadDCIClick (wxCommandEvent &event)
void OnbtnLoadDCQClick (wxCommandEvent &event)
void onbtnGFIR1Coef (wxCommandEvent &event)
void onbtnGFIR2Coef (wxCommandEvent &event)
void onbtnGFIR3Coef (wxCommandEvent &event)
void OnbtnUploadNCOClick (wxCommandEvent &event)
void OnbtnReadRSSI (wxCommandEvent &event)
void PHOinputChanged (wxCommandEvent &event)
void txtFCWPHOmodeAdditional_OnMouseWheel (wxMouseEvent &event)
Protected Attributes
lms_device_t * lmsControl
std::map< wxWindow *, LMS7Parameter > wndId2Enum
std::vector< wxStaticText * > lblNCOangles
std::vector< wxRadioButton * > rgrNCOselections
std::vector< wxTextCtrl * > txtNCOinputs
Protected Attributes inherited from pnlRxTSP_view
wxCheckBox * chkEN_RXTSP
wxCheckBox * chkDC_BYP_RXTSP
wxCheckBox * chkDC_LOOP_RXTSP
wxCheckBox * chkGC_BYP_RXTSP
wxCheckBox * chkPH_BYP_RXTSP
wxCheckBox * chkCMIX_BYP_RXTSP
wxCheckBox * chkAGC_BYP_RXTSP
wxCheckBox * chkGFIR1_BYP_RXTSP
wxCheckBox * chkGFIR2_BYP_RXTSP
wxCheckBox * chkGFIR3_BYP_RXTSP
wxStaticText * ID_STATICTEXT29
wxStaticText * lblBISTI
wxStaticText * ID_STATICTEXT30
wxStaticText * lblBSTATE_I
wxStaticText * ID_STATICTEXT31
wxStaticText * lblBISTQ
wxStaticText * ID_STATICTEXT32
wxStaticText * lblBSTATE_Q
wxCheckBox * chkBSTART_RXTSP
wxButton * btnReadBIST
wxStaticText * ID_STATICTEXT71
wxStaticText * lblADCI
wxStaticText * ID_STATICTEXT28
wxStaticText * lblADCQ
wxStaticText * ID_STATICTEXT51
wxStaticText * lblRSSI
wxCheckBox * chkCAPSEL_ADC_RXTSP
wxButton * ID_BUTTON1
wxFlexGridSizer * sizerNCOgrid
wxStaticText * tableTitleCol1
wxStaticText * tableTitleCol2
wxRadioButton * rgrSEL0
wxTextCtrl * txtFCWPHO0
wxStaticText * txtAnglePHO0
wxRadioButton * rgrSEL01
wxTextCtrl * txtFCWPHO01
wxStaticText * txtAnglePHO01
wxRadioButton * rgrSEL02
wxTextCtrl * txtFCWPHO02
wxStaticText * txtAnglePHO02
wxRadioButton * rgrSEL03
wxTextCtrl * txtFCWPHO03
wxStaticText * txtAnglePHO03
wxRadioButton * rgrSEL04
wxTextCtrl * txtFCWPHO04
wxStaticText * txtAnglePHO04
wxRadioButton * rgrSEL05
wxTextCtrl * txtFCWPHO05
wxStaticText * txtAnglePHO05
wxRadioButton * rgrSEL06
wxTextCtrl * txtFCWPHO06
wxStaticText * txtAnglePHO06
wxRadioButton * rgrSEL07
wxTextCtrl * txtFCWPHO07
wxStaticText * txtAnglePHO07
wxRadioButton * rgrSEL08
wxTextCtrl * txtFCWPHO08
wxStaticText * txtAnglePHO08
wxRadioButton * rgrSEL09
wxTextCtrl * txtFCWPHO09
wxStaticText * txtAnglePHO09
wxRadioButton * rgrSEL10
wxTextCtrl * txtFCWPHO10
wxStaticText * txtAnglePHO10
wxRadioButton * rgrSEL11
wxTextCtrl * txtFCWPHO11
wxStaticText * txtAnglePHO11
wxRadioButton * rgrSEL12
wxTextCtrl * txtFCWPHO12
wxStaticText * txtAnglePHO12
wxRadioButton * rgrSEL13
wxTextCtrl * txtFCWPHO13
wxStaticText * txtAnglePHO13
wxRadioButton * rgrSEL14
wxTextCtrl * txtFCWPHO14
wxStaticText * txtAnglePHO14
wxRadioButton * rgrSEL15
wxTextCtrl * txtFCWPHO15
wxStaticText * txtAnglePHO15
wxStaticText * ID_STATICTEXT21
wxStaticText * lblRefClk
wxButton * btnUploadNCO
wxRadioBox * rgrMODE_RX
wxStaticText * lblFCWPHOmodeName
wxTextCtrl * txtFCWPHOmodeAdditional
wxStaticText * ID_STATICTEXT25
wxComboBox * cmbDTHBIT_RX
wxCheckBox * chkTSGSWAPIQ_RXTSP
wxRadioBox * rgrTSGFCW_RXTSP
wxRadioBox * rgrTSGMODE_RXTSP
wxRadioBox * rgrINSEL_RXTSP
wxRadioBox * rgrTSGFC_RXTSP
wxComboBox * cmbDCCORR_AVG
wxStaticText * ID_STATICTEXT23
wxTextCtrl * txtDC_REG_RXTSP
wxButton * btnLoadDCI
wxButton * btnLoadDCQ
wxComboBox * cmbCMIX_SC_RXTSP
wxStaticText * ID_STATICTEXT24
wxComboBox * cmbCMIX_GAIN_RXTSP
wxStaticText * ID_STATICTEXT7
wxComboBox * cmbHBD_OVR_RXTSP
wxStaticText * ID_STATICTEXT72
wxComboBox * cmbHBD_DLY
wxStaticText * ID_STATICTEXT10
wxComboBox * cmbGFIR1_L_RXTSP
wxStaticText * ID_STATICTEXT11
wxSpinCtrl * cmbGFIR1_N_RXTSP
wxButton * btnGFIR1Coef
wxStaticText * ID_STATICTEXT12
wxComboBox * cmbGFIR2_L_RXTSP
wxStaticText * ID_STATICTEXT13
wxSpinCtrl * cmbGFIR2_N_RXTSP
wxButton * btnGFIR2Coef
wxStaticText * ID_STATICTEXT14
wxComboBox * cmbGFIR3_L_RXTSP
wxStaticText * ID_STATICTEXT15
wxSpinCtrl * cmbGFIR3_N_RXTSP
wxButton * btnGFIR3Coef
NumericSlider * cmbIQCORR_RXTSP
wxStaticText * ID_STATICTEXT16
wxStaticText * txtPhaseAlpha
wxStaticText * ID_STATICTEXT5
NumericSlider * cmbGCORRI_RXTSP
wxStaticText * ID_STATICTEXT4
NumericSlider * cmbGCORRQ_RXTSP
wxButton * ID_BUTTON10
wxStaticText * ID_STATICTEXT91
wxComboBox * cmbAGC_MODE_RXTSP
wxStaticText * ID_STATICTEXT3
wxComboBox * cmbAGC_AVG_RXTSP
wxStaticText * ID_STATICTEXT1
NumericSlider * spinAGC_K_RXTSP
wxStaticText * ID_STATICTEXT2
NumericSlider * cmbAGC_ADESIRED_RXTSP
Additional Inherited Members
Protected Types inherited from pnlRxTSP_view
enum {
ID_EN_RXTSP = 2048, ID_DC_BYP_RXTSP, ID_GC_BYP_RXTSP, ID_PH_BYP_RXTSP,
ID_CMIX_BYP_RXTSP, ID_AGC_BYP_RXTSP, ID_GFIR1_BYP_RXTSP, ID_GFIR2_BYP_RXTSP,
ID_GFIR3_BYP_RXTSP, ID_BSTART_RXTSP, ID_MODE_RX, ID_DTHBIT_RX,
ID_TSGSWAPIQ_RXTSP, ID_TSGFCW_RXTSP, ID_TSGMODE_RXTSP, ID_INSEL_RXTSP,
ID_TSGFC_RXTSP, ID_DCCORR_AVG, ID_DC_REG_RXTSP, ID_CMIX_SC_RXTSP,
ID_CMIX_GAIN_RXTSP, ID_HBD_OVR_RXTSP, ID_GFIR1_L_RXTSP, ID_GFIR1_N_RXTSP,
ID_GFIR2_L_RXTSP, ID_GFIR2_N_RXTSP, ID_GFIR3_L_RXTSP, ID_GFIR3_N_RXTSP,
ID_IQCORR_RXTSP, ID_GCORRI_RXTSP, ID_GCORRQ_RXTSP, ID_AGC_MODE_RXTSP,
ID_AGC_AVG_RXTSP, ID_AGC_K_RXTSP, ID_AGC_ADESIRED_RXTSP
}
Detailed Description
Implementing pnlRxTSP_view.
Definition at line 18 of file lms7002_pnlRxTSP_view.h.
Constructor & Destructor Documentation
lms7002_pnlRxTSP_view::lms7002_pnlRxTSP_view (wxWindow * parent)
Constructor.
Definition at line 14 of file lms7002_pnlRxTSP_view.cpp.
lms7002_pnlRxTSP_view::lms7002_pnlRxTSP_view (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, long style = wxTAB_TRAVERSAL)
Definition at line 21 of file lms7002_pnlRxTSP_view.cpp.
References AGC_ADESIRED_RXTSP, AGC_AVG_RXTSP, AGC_BYP_RXTSP, AGC_K_RXTSP, AGC_MODE_RXTSP, BSTART_RXTSP, pnlRxTSP_view::chkAGC_BYP_RXTSP, pnlRxTSP_view::chkBSTART_RXTSP, pnlRxTSP_view::chkCAPSEL_ADC_RXTSP, pnlRxTSP_view::chkCMIX_BYP_RXTSP, pnlRxTSP_view::chkDC_BYP_RXTSP, pnlRxTSP_view::chkDC_LOOP_RXTSP, pnlRxTSP_view::chkEN_RXTSP, pnlRxTSP_view::chkGC_BYP_RXTSP, pnlRxTSP_view::chkGFIR1_BYP_RXTSP, pnlRxTSP_view::chkGFIR2_BYP_RXTSP, pnlRxTSP_view::chkGFIR3_BYP_RXTSP, pnlRxTSP_view::chkPH_BYP_RXTSP, pnlRxTSP_view::chkTSGSWAPIQ_RXTSP, pnlRxTSP_view::cmbAGC_ADESIRED_RXTSP, pnlRxTSP_view::cmbAGC_AVG_RXTSP, pnlRxTSP_view::cmbAGC_MODE_RXTSP, pnlRxTSP_view::cmbCMIX_GAIN_RXTSP, pnlRxTSP_view::cmbCMIX_SC_RXTSP, pnlRxTSP_view::cmbDCCORR_AVG, pnlRxTSP_view::cmbDTHBIT_RX, pnlRxTSP_view::cmbGCORRI_RXTSP, pnlRxTSP_view::cmbGCORRQ_RXTSP, pnlRxTSP_view::cmbGFIR1_L_RXTSP, pnlRxTSP_view::cmbGFIR1_N_RXTSP, pnlRxTSP_view::cmbGFIR2_L_RXTSP, pnlRxTSP_view::cmbGFIR2_N_RXTSP, pnlRxTSP_view::cmbGFIR3_L_RXTSP, pnlRxTSP_view::cmbGFIR3_N_RXTSP, pnlRxTSP_view::cmbHBD_DLY, pnlRxTSP_view::cmbHBD_OVR_RXTSP, pnlRxTSP_view::cmbIQCORR_RXTSP, CMIX_BYP_RXTSP, CMIX_GAIN_RXTSP, cmix_gain_rxtsp_IndexValuePairs, CMIX_SC_RXTSP, DC_BYP_RXTSP, DCCORR_AVG_RXTSP, DTHBIT_RX, EN_RXTSP, GC_BYP_RXTSP, GCORRI_RXTSP, GCORRQ_RXTSP, GFIR1_BYP_RXTSP, GFIR1_L_RXTSP, GFIR1_N_RXTSP, GFIR2_BYP_RXTSP, GFIR2_L_RXTSP, GFIR2_N_RXTSP, GFIR3_BYP_RXTSP, GFIR3_L_RXTSP, GFIR3_N_RXTSP, HBD_OVR_RXTSP, hbd_ovr_rxtsp_IndexValuePairs, i, INSEL_RXTSP, IQCORR_RXTSP, lblNCOangles, LMS7_CAPSEL_ADC, LMS7_DCLOOP_STOP, LMS7param, MODE_RX, PH_BYP_RXTSP, pnlRxTSP_view::rgrINSEL_RXTSP, pnlRxTSP_view::rgrMODE_RX, rgrNCOselections, pnlRxTSP_view::rgrSEL0, pnlRxTSP_view::rgrSEL01, pnlRxTSP_view::rgrSEL02, pnlRxTSP_view::rgrSEL03, pnlRxTSP_view::rgrSEL04, pnlRxTSP_view::rgrSEL05, pnlRxTSP_view::rgrSEL06, pnlRxTSP_view::rgrSEL07, pnlRxTSP_view::rgrSEL08, pnlRxTSP_view::rgrSEL09, pnlRxTSP_view::rgrSEL10, pnlRxTSP_view::rgrSEL11, pnlRxTSP_view::rgrSEL12, pnlRxTSP_view::rgrSEL13, pnlRxTSP_view::rgrSEL14, pnlRxTSP_view::rgrSEL15, pnlRxTSP_view::rgrTSGFC_RXTSP, pnlRxTSP_view::rgrTSGFCW_RXTSP, pnlRxTSP_view::rgrTSGMODE_RXTSP, SEL_RX, pnlRxTSP_view::spinAGC_K_RXTSP, temp, TSGFC_RXTSP, TSGFCW_RXTSP, tsgfcw_rxtsp_IndexValuePairs, TSGMODE_RXTSP, TSGSWAPIQ_RXTSP, pnlRxTSP_view::txtAnglePHO0, pnlRxTSP_view::txtAnglePHO01, pnlRxTSP_view::txtAnglePHO02, pnlRxTSP_view::txtAnglePHO03, pnlRxTSP_view::txtAnglePHO04, pnlRxTSP_view::txtAnglePHO05, pnlRxTSP_view::txtAnglePHO06, pnlRxTSP_view::txtAnglePHO07, pnlRxTSP_view::txtAnglePHO08, pnlRxTSP_view::txtAnglePHO09, pnlRxTSP_view::txtAnglePHO10, pnlRxTSP_view::txtAnglePHO11, pnlRxTSP_view::txtAnglePHO12, pnlRxTSP_view::txtAnglePHO13, pnlRxTSP_view::txtAnglePHO14, pnlRxTSP_view::txtAnglePHO15, pnlRxTSP_view::txtFCWPHO0, pnlRxTSP_view::txtFCWPHO01, pnlRxTSP_view::txtFCWPHO02, pnlRxTSP_view::txtFCWPHO03, pnlRxTSP_view::txtFCWPHO04, pnlRxTSP_view::txtFCWPHO05, pnlRxTSP_view::txtFCWPHO06, pnlRxTSP_view::txtFCWPHO07, pnlRxTSP_view::txtFCWPHO08, pnlRxTSP_view::txtFCWPHO09, pnlRxTSP_view::txtFCWPHO10, pnlRxTSP_view::txtFCWPHO11, pnlRxTSP_view::txtFCWPHO12, pnlRxTSP_view::txtFCWPHO13, pnlRxTSP_view::txtFCWPHO14, pnlRxTSP_view::txtFCWPHO15, txtNCOinputs, LMS7002_WXGUI::UpdateTooltips(), and wndId2Enum.
Member Function Documentation
void lms7002_pnlRxTSP_view::Initialize (lms_device_t * pControl)
Definition at line 263 of file lms7002_pnlRxTSP_view.cpp.
References pnlRxTSP_view::chkDC_LOOP_RXTSP, pnlRxTSP_view::cmbCMIX_GAIN_RXTSP, pnlRxTSP_view::cmbHBD_DLY, LMS7param, LMS_ReadParam(), lmsControl, MASK, and temp.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlRxTSP_view::onbtnGFIR1Coef (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 178 of file lms7002_pnlRxTSP_view.cpp.
References lms7002_dlgGFIR_Coefficients::GetCoefficients(), LMS7param, LMS_CH_RX, LMS_GetGFIRCoeff(), LMS_GFIR1, LMS_ReadParam(), LMS_SetGFIRCoeff(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, lms7002_dlgGFIR_Coefficients::SetCoefficients(), status, and UpdateGUI().
void lms7002_pnlRxTSP_view::onbtnGFIR2Coef (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 207 of file lms7002_pnlRxTSP_view.cpp.
References lms7002_dlgGFIR_Coefficients::GetCoefficients(), LMS7param, LMS_CH_RX, LMS_GetGFIRCoeff(), LMS_GFIR2, LMS_ReadParam(), LMS_SetGFIRCoeff(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, lms7002_dlgGFIR_Coefficients::SetCoefficients(), status, and UpdateGUI().
void lms7002_pnlRxTSP_view::onbtnGFIR3Coef (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 235 of file lms7002_pnlRxTSP_view.cpp.
References lms7002_dlgGFIR_Coefficients::GetCoefficients(), LMS7param, LMS_CH_RX, LMS_GetGFIRCoeff(), LMS_GFIR3, LMS_ReadParam(), LMS_SetGFIRCoeff(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, lms7002_dlgGFIR_Coefficients::SetCoefficients(), status, and UpdateGUI().
void lms7002_pnlRxTSP_view::OnbtnLoadDCIClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 405 of file lms7002_pnlRxTSP_view.cpp.
References DC_REG_RXTSP, LMS7param, LMS_WriteParam(), lmsControl, TSGDCLDI_RXTSP, and pnlRxTSP_view::txtDC_REG_RXTSP.
void lms7002_pnlRxTSP_view::OnbtnLoadDCQClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 415 of file lms7002_pnlRxTSP_view.cpp.
References DC_REG_RXTSP, LMS7param, LMS_WriteParam(), lmsControl, TSGDCLDQ_RXTSP, and pnlRxTSP_view::txtDC_REG_RXTSP.
void lms7002_pnlRxTSP_view::OnbtnReadBISTSignature (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 342 of file lms7002_pnlRxTSP_view.cpp.
References CAPSEL, CAPTURE, pnlRxTSP_view::lblBISTI, pnlRxTSP_view::lblBISTQ, pnlRxTSP_view::lblBSTATE_I, pnlRxTSP_view::lblBSTATE_Q, LMS7param, LMS_ReadLMSReg(), LMS_WriteParam(), and lmsControl.
void lms7002_pnlRxTSP_view::OnbtnReadRSSI (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 367 of file lms7002_pnlRxTSP_view.cpp.
References CAPSEL, CAPTURE, pnlRxTSP_view::chkCAPSEL_ADC_RXTSP, pnlRxTSP_view::lblADCI, pnlRxTSP_view::lblADCQ, pnlRxTSP_view::lblRSSI, LMS7param, LMS_ReadLMSReg(), LMS_WriteParam(), and lmsControl.
void lms7002_pnlRxTSP_view::OnbtnUploadNCOClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 425 of file lms7002_pnlRxTSP_view.cpp.
References i, LMS7param, LMS_CH_RX, LMS_ReadParam(), LMS_SetNCOFrequency(), LMS_SetNCOPhase(), LMS_WriteParam(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, MODE_RX, pnlRxTSP_view::rgrMODE_RX, pnlRxTSP_view::txtFCWPHOmodeAdditional, txtNCOinputs, and UpdateGUI().
void lms7002_pnlRxTSP_view::OnNCOSelectionChange (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 329 of file lms7002_pnlRxTSP_view.cpp.
References i, LMS7param, LMS_WriteParam(), lmsControl, rgrNCOselections, and SEL_RX.
void lms7002_pnlRxTSP_view::ParameterChangeHandler (wxSpinEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 282 of file lms7002_pnlRxTSP_view.cpp.
void lms7002_pnlRxTSP_view::ParameterChangeHandler (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 291 of file lms7002_pnlRxTSP_view.cpp.
References pnlRxTSP_view::cmbCMIX_GAIN_RXTSP, pnlRxTSP_view::cmbHBD_OVR_RXTSP, pnlRxTSP_view::cmbIQCORR_RXTSP, cmix_gain_rxtsp_IndexValuePairs, hbd_ovr_rxtsp_IndexValuePairs, LMS7002_WXGUI::index2value(), LMS7_CMIX_GAIN_RXTSP_R3, LMS_WriteParam(), lmsControl, pnlRxTSP_view::rgrMODE_RX, pnlRxTSP_view::rgrTSGFCW_RXTSP, tsgfcw_rxtsp_IndexValuePairs, pnlRxTSP_view::txtPhaseAlpha, UpdateNCOinputs(), and wndId2Enum.
void lms7002_pnlRxTSP_view::PHOinputChanged (wxCommandEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 542 of file lms7002_pnlRxTSP_view.cpp.
References freq, i, lblNCOangles, LMS7param, LMS_CH_RX, LMS_ReadParam(), LMS_SetNCOFrequency(), LMS_SetNCOPhase(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, pnlRxTSP_view::rgrMODE_RX, and pnlRxTSP_view::txtFCWPHOmodeAdditional.
void lms7002_pnlRxTSP_view::txtFCWPHOmodeAdditional_OnMouseWheel (wxMouseEvent & event) protected virtual
Reimplemented from pnlRxTSP_view.
Definition at line 581 of file lms7002_pnlRxTSP_view.cpp.
References pnlRxTSP_view::txtFCWPHOmodeAdditional.
void lms7002_pnlRxTSP_view::UpdateGUI ()
Definition at line 496 of file lms7002_pnlRxTSP_view.cpp.
References pnlRxTSP_view::cmbCMIX_GAIN_RXTSP, pnlRxTSP_view::cmbHBD_OVR_RXTSP, pnlRxTSP_view::cmbIQCORR_RXTSP, CMIX_GAIN_RXTSP, cmix_gain_rxtsp_IndexValuePairs, CMIX_GAIN_RXTSP_R3, freq, lime::LMS7002M::GetReferenceClk_TSP(), HBD_OVR_RXTSP, hbd_ovr_rxtsp_IndexValuePairs, IQCORR_RXTSP, pnlRxTSP_view::lblRefClk, lms(), LMS7param, LMS_ReadParam(), lmsControl, MAC, MIMO_SISO, rgrNCOselections, pnlRxTSP_view::rgrTSGFCW_RXTSP, SEL_RX, NumericSlider::SetValue(), TSGFCW_RXTSP, tsgfcw_rxtsp_IndexValuePairs, LMS7002_WXGUI::UpdateControlsByMap(), UpdateNCOinputs(), LMS7002_WXGUI::value2index(), and wndId2Enum.
Referenced by onbtnGFIR1Coef(), onbtnGFIR2Coef(), onbtnGFIR3Coef(), OnbtnUploadNCOClick(), and lms7002_mainPanel::UpdateVisiblePanel().
void lms7002_pnlRxTSP_view::UpdateNCOinputs ()
Definition at line 459 of file lms7002_pnlRxTSP_view.cpp.
References fcw, freq, i, pnlRxTSP_view::lblFCWPHOmodeName, LMS7param, LMS_CH_RX, LMS_GetNCOFrequency(), LMS_GetNCOPhase(), LMS_ReadParam(), lmsControl, LMS7SuiteAppFrame::m_lmsSelection, MAC, phase, pho, pnlRxTSP_view::rgrMODE_RX, pnlRxTSP_view::tableTitleCol1, pnlRxTSP_view::tableTitleCol2, pnlRxTSP_view::txtFCWPHOmodeAdditional, and txtNCOinputs.
Referenced by ParameterChangeHandler(), and UpdateGUI().
Member Data Documentation
std::vector<wxStaticText*> lms7002_pnlRxTSP_view::lblNCOangles protected
Definition at line 47 of file lms7002_pnlRxTSP_view.h.
Referenced by lms7002_pnlRxTSP_view(), and PHOinputChanged().
lms_device_t* lms7002_pnlRxTSP_view::lmsControl protected
Definition at line 44 of file lms7002_pnlRxTSP_view.h.
Referenced by Initialize(), onbtnGFIR1Coef(), onbtnGFIR2Coef(), onbtnGFIR3Coef(), OnbtnLoadDCIClick(), OnbtnLoadDCQClick(), OnbtnReadBISTSignature(), OnbtnReadRSSI(), OnbtnUploadNCOClick(), OnNCOSelectionChange(), ParameterChangeHandler(), PHOinputChanged(), UpdateGUI(), and UpdateNCOinputs().
std::vector<wxRadioButton*> lms7002_pnlRxTSP_view::rgrNCOselections protected
Definition at line 48 of file lms7002_pnlRxTSP_view.h.
Referenced by lms7002_pnlRxTSP_view(), OnNCOSelectionChange(), and UpdateGUI().
std::vector<wxTextCtrl*> lms7002_pnlRxTSP_view::txtNCOinputs protected
Definition at line 49 of file lms7002_pnlRxTSP_view.h.
Referenced by lms7002_pnlRxTSP_view(), OnbtnUploadNCOClick(), and UpdateNCOinputs().
std::map<wxWindow*, LMS7Parameter> lms7002_pnlRxTSP_view::wndId2Enum protected
Definition at line 45 of file lms7002_pnlRxTSP_view.h.
Referenced by lms7002_pnlRxTSP_view(), ParameterChangeHandler(), and UpdateGUI().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlRxTSP_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlRxTSP_view.cpp