LimeSuite-UML: GNUPlotPipe Class Reference
GNUPlotPipe Class Reference
#include <gnuPlotPipe.h>
Public Member Functions
GNUPlotPipe (bool persistent=true)
~GNUPlotPipe ()
void write (const char *str)
void writef (const char *format,...)
void flush ()
Protected Attributes
FILE * pipeHandle
Detailed Description
Definition at line 8 of file gnuPlotPipe.h.
Constructor & Destructor Documentation
GNUPlotPipe::GNUPlotPipe (bool persistent = true) inline
Definition at line 11 of file gnuPlotPipe.h.
References pipeHandle.
GNUPlotPipe::~GNUPlotPipe () inline
Definition at line 25 of file gnuPlotPipe.h.
References pipeHandle, and write().
Member Function Documentation
void GNUPlotPipe::flush () inline
Definition at line 51 of file gnuPlotPipe.h.
References pipeHandle.
Referenced by CheckSaturationRx(), CheckSaturationTxRx(), main(), and TEST_F().
void GNUPlotPipe::write (const char * str) inline
Definition at line 35 of file gnuPlotPipe.h.
References pipeHandle.
Referenced by CalibrateIQImbalance(), CalibrateTxDCAuto(), CheckSaturationRx(), CheckSaturationTxRx(), main(), TEST_F(), writef(), and ~GNUPlotPipe().
void GNUPlotPipe::writef (const char * format, ...) inline
Definition at line 41 of file gnuPlotPipe.h.
References temp, and write().
Referenced by CalibrateIQImbalance(), CalibrateTxDCAuto(), CheckSaturationRx(), CheckSaturationTxRx(), main(), and TEST_F().
Member Data Documentation
FILE* GNUPlotPipe::pipeHandle protected
Definition at line 56 of file gnuPlotPipe.h.
Referenced by flush(), GNUPlotPipe(), write(), and ~GNUPlotPipe().
The documentation for this class was generated from the following file:
/home/erik/prefix/default/src/limesuite-dev/src/gnuPlotPipe.h