LimeSuite-UML: dlgConnectionSettings Class Reference
dlgConnectionSettings Class Reference
Implementing dlgConnectionSettings.
#include <dlgConnectionSettings.h>
Public Member Functions
dlgConnectionSettings (wxWindow *parent)
Constructor.
void SetConnectionManagers (lms_device_t **lms)
Public Member Functions inherited from dlgConnectionSettings_view
dlgConnectionSettings_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxString &title=wxT("Connection Settings"), const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE|wxRESIZE_BORDER)
~dlgConnectionSettings_view ()
Protected Member Functions
void GetDeviceList (wxInitDialogEvent &event)
void OnConnect (wxCommandEvent &event)
void OnCancel (wxCommandEvent &event)
void OnDisconnect (wxCommandEvent &event)
Protected Attributes
lms_device_t ** lmsControl
int lmsOpenedIndex
Protected Attributes inherited from dlgConnectionSettings_view
wxStaticText * m_staticText472
wxListBox * mListLMS7ports
wxButton * btnConnect
wxButton * btnCancel
wxButton * btnDisconnect
Detailed Description
Implementing dlgConnectionSettings.
Definition at line 14 of file dlgConnectionSettings.h.
Constructor & Destructor Documentation
dlgConnectionSettings::dlgConnectionSettings (wxWindow * parent)
Constructor.
Definition at line 10 of file dlgConnectionSettings.cpp.
References lmsControl, and lmsOpenedIndex.
Member Function Documentation
void dlgConnectionSettings::GetDeviceList (wxInitDialogEvent & event) protected virtual
Reimplemented from dlgConnectionSettings_view.
Definition at line 22 of file dlgConnectionSettings.cpp.
References i, list, LMS_GetDeviceList(), lmsOpenedIndex, and dlgConnectionSettings_view::mListLMS7ports.
Referenced by OnDisconnect().
void dlgConnectionSettings::OnCancel (wxCommandEvent & event) protected virtual
Reimplemented from dlgConnectionSettings_view.
Definition at line 64 of file dlgConnectionSettings.cpp.
void dlgConnectionSettings::OnConnect (wxCommandEvent & event) protected virtual
Reimplemented from dlgConnectionSettings_view.
Definition at line 41 of file dlgConnectionSettings.cpp.
References lime::LMS7_Device::CreateDevice(), lime::LMS7_Device::GetDeviceList(), list, lmsControl, and dlgConnectionSettings_view::mListLMS7ports.
void dlgConnectionSettings::OnDisconnect (wxCommandEvent & event) protected virtual
Reimplemented from dlgConnectionSettings_view.
Definition at line 70 of file dlgConnectionSettings.cpp.
References GetDeviceList(), lime::LMS7_Device, lmsControl, and dlgConnectionSettings_view::mListLMS7ports.
void dlgConnectionSettings::SetConnectionManagers (lms_device_t ** lms)
Definition at line 17 of file dlgConnectionSettings.cpp.
References lms(), and lmsControl.
Referenced by LMS7SuiteAppFrame::OnShowConnectionSettings().
Member Data Documentation
lms_device_t** dlgConnectionSettings::lmsControl protected
Definition at line 28 of file dlgConnectionSettings.h.
Referenced by dlgConnectionSettings(), OnConnect(), OnDisconnect(), and SetConnectionManagers().
int dlgConnectionSettings::lmsOpenedIndex protected
Definition at line 29 of file dlgConnectionSettings.h.
Referenced by dlgConnectionSettings(), and GetDeviceList().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/dlgConnectionSettings.h
/home/erik/prefix/default/src/limesuite-dev/src/utilities_gui/dlgConnectionSettings.cpp