LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/octave/LimeSuite.cc File Reference
LimeSuite.cc File Reference
#include <octave/oct.h>
#include <octave/Cell.h>
#include <vector>
#include <string>
#include "LimeSuite.h"
Classes
struct complex16_t
class ResourceDeallocator
Functions
void FreeResources ()
void StopStream ()
void PrintDeviceInfo (lms_device_t *port)
DEFUN_DLD (LimeGetDeviceList, args, nargout,"LIST = LimeGetDeviceList() - Returns available device list")
DEFUN_DLD (LimeInitialize, args, nargout,"LimeInitialize(DEV) - connect to device and allocate buffer memory\n\ DEV [optional] - device name to connect, obtained via LimeGetDeviceList()")
DEFUN_DLD (LimeDestroy, args, nargout,"LimeDestroy() - Stop all streams, deallocate memory and disconnect device")
DEFUN_DLD (LimeLoadConfig, args, nargout,"LimeLoadConfig(FILENAME) - Load configuration from file FILENAME")
DEFUN_DLD (LimeStartStreaming, args, nargout,"LimeStartStreaming(FIFOSIZE, CHANNELS) - starts sample streaming from selected channels\n\ FIFOSIZE [optional] - buffer size in samples to be used by library (default: 4 MSamples)\ CHANNELS [optional] - array of channels to be used [rx0 ; rx1 ; tx0 ; tx1] (deafult: rx0)")
DEFUN_DLD (LimeStopStreaming, args, nargout,"LimeStopStreaming() - Stop Receiver and Transmitter threads")
DEFUN_DLD (LimeReceiveSamples, args,,"SIGNAL = LimeReceiveSamplesLarge(N, CH) - receive N samples from Rx channel CH.\n\ CH parameter is optional, valid values are 0 and 1")
DEFUN_DLD (LimeTransmitSamples, args,,"LimeTransmitSamples(SIGNAL, CH) - sends normalized complex SIGNAL to Tx cahnnel CH\n\ CH parameter is optional, valid values are 0 and 1")
DEFUN_DLD (LimeLoopWFMStart, args,,"LimeLoopWFMStart(SIGNAL) - upload SIGNAL to device RAM for repeated transmitting")
DEFUN_DLD (LimeLoopWFMStop, args,,"LimeTxLoopWFMStop() - stop transmitting samples from device RAM")
Variables
const int maxChCnt = 2
const float scaleFactor = 32768.0f
lms_device_t * lmsDev = NULL
lms_stream_t streamRx [maxChCnt]
lms_stream_t streamTx [maxChCnt]
bool WFMrunning = false
complex16_t * rxbuffers = NULL
complex16_t * txbuffers = NULL
ResourceDeallocator gResources
Function Documentation
DEFUN_DLD (LimeGetDeviceList , args , nargout)
Definition at line 63 of file LimeSuite.cc.
References args, c, i, and LMS_GetDeviceList().
DEFUN_DLD (LimeInitialize , args , nargout , "LimeInitialize(DEV) - connect to device and allocate buffer memory\n\DEV - device name to connect[optional], obtained via LimeGetDeviceList()")
Definition at line 85 of file LimeSuite.cc.
References args, FreeResources(), lms_stream_t::handle, i, LMS_GetLastErrorMessage(), LMS_Open(), LMS_Synchronize(), lmsDev, maxChCnt, PrintDeviceInfo(), and status.
DEFUN_DLD (LimeDestroy , args , nargout , "LimeDestroy() - Stop all streams, deallocate memory and disconnect device")
Definition at line 125 of file LimeSuite.cc.
References FreeResources().
DEFUN_DLD (LimeLoadConfig , args , nargout , "LimeLoadConfig(FILENAME) - Load configuration from file FILENAME")
Definition at line 132 of file LimeSuite.cc.
References args, filename, LMS_GetLastErrorMessage(), LMS_LoadConfig(), and lmsDev.
DEFUN_DLD (LimeStartStreaming , args , nargout , "LimeStartStreaming(FIFOSIZE, CHANNELS) - starts sample streaming from selected channels\n\ FIFOSIZE - buffer size in samples to be used by library (default: 4 MSamples)\ CHANNELS - array of channels to be used (deafult: rx0)" [optional][optional][rx0;rx1;tx0;tx1])
Definition at line 161 of file LimeSuite.cc.
References args, lms_stream_t::channel, lms_stream_t::dataFmt, lms_stream_t::fifoSize, i, lms_stream_t::isTx, lms_stream_t::LMS_FMT_I16, LMS_GetLastErrorMessage(), LMS_SetupStream(), LMS_StartStream(), lmsDev, maxChCnt, string(), lms_stream_t::throughputVsLatency, and tx.
DEFUN_DLD (LimeStopStreaming , args , nargout , "LimeStopStreaming() - Stop Receiver and Transmitter threads")
Definition at line 256 of file LimeSuite.cc.
References args, lmsDev, and StopStream().
DEFUN_DLD (LimeReceiveSamples , args , " SIGNAL = LimeReceiveSamplesLarge(N, CH) - receive N samples from Rx channel CH.\n\CH parameter is optional, valid values are 0 and 1")
Definition at line 270 of file LimeSuite.cc.
References args, lms_stream_t::fifoSize, i, LMS_RecvStream(), maxChCnt, meta, scaleFactor, timeout_ms, and val.
DEFUN_DLD (LimeTransmitSamples , args , "LimeTransmitSamples(SIGNAL, CH) - sends normalized complex SIGNAL to Tx cahnnel CH\n\CH parameter is optional, valid values are 0 and 1")
Definition at line 334 of file LimeSuite.cc.
References args, swig::check(), i, complex16_t::i, LMS_SendStream(), maxChCnt, meta, complex16_t::q, scaleFactor, timeout_ms, lms_stream_meta_t::timestamp, and lms_stream_meta_t::waitForTimestamp.
DEFUN_DLD (LimeLoopWFMStart , args , "LimeLoopWFMStart(SIGNAL) - upload SIGNAL to device RAM for repeated transmitting")
Definition at line 393 of file LimeSuite.cc.
References args, chCount, swig::check(), i, complex16_t::i, LMS_EnableTxWFM(), LMS_UploadWFM(), lmsDev, complex16_t::q, timeout_ms, and WFMrunning.
DEFUN_DLD (LimeLoopWFMStop , args , "LimeTxLoopWFMStop() - stop transmitting samples from device RAM")
Definition at line 441 of file LimeSuite.cc.
References LMS_EnableTxWFM(), lmsDev, and WFMrunning.
void FreeResources ()
Definition at line 455 of file LimeSuite.cc.
References LMS_Close(), LMS_EnableTxWFM(), lmsDev, rxbuffers, StopStream(), txbuffers, and WFMrunning.
Referenced by DEFUN_DLD(), and ResourceDeallocator::~ResourceDeallocator().
void PrintDeviceInfo (lms_device_t * port)
Definition at line 47 of file LimeSuite.cc.
References lms_dev_info_t::deviceName, lms_dev_info_t::firmwareVersion, lms_dev_info_t::gatewareVersion, lms_dev_info_t::hardwareVersion, info, LMS_GetDeviceInfo(), lmsDev, and lms_dev_info_t::protocolVersion.
Referenced by DEFUN_DLD().
void StopStream ()
Definition at line 30 of file LimeSuite.cc.
References lms_stream_t::handle, i, LMS_DestroyStream(), LMS_StopStream(), lmsDev, and maxChCnt.
Referenced by DEFUN_DLD(), and FreeResources().
Variable Documentation
ResourceDeallocator gResources
Definition at line 487 of file LimeSuite.cc.
lms_device_t* lmsDev = NULL
Definition at line 16 of file LimeSuite.cc.
Referenced by DEFUN_DLD(), FreeResources(), PrintDeviceInfo(), and StopStream().
const int maxChCnt = 2
Definition at line 13 of file LimeSuite.cc.
Referenced by DEFUN_DLD(), and StopStream().
complex16_t* rxbuffers = NULL
Definition at line 27 of file LimeSuite.cc.
Referenced by FreeResources().
const float scaleFactor = 32768.0f
Definition at line 14 of file LimeSuite.cc.
Referenced by DEFUN_DLD().
lms_stream_t streamRx[maxChCnt]
Definition at line 17 of file LimeSuite.cc.
lms_stream_t streamTx[maxChCnt]
Definition at line 18 of file LimeSuite.cc.
complex16_t* txbuffers = NULL
Definition at line 28 of file LimeSuite.cc.
Referenced by FreeResources().
bool WFMrunning = false
Definition at line 26 of file LimeSuite.cc.
Referenced by DEFUN_DLD(), and FreeResources().