LimeSuite-UML: pnlUltimateEVB Class Reference
pnlUltimateEVB Class Reference
#include <pnlUltimateEVB.h>
Classes
class ADCparam
Public Member Functions
pnlUltimateEVB (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxDefaultSize, int style=0, wxString name=wxEmptyString)
void Initialize (lms_device_t *pControl)
virtual ~pnlUltimateEVB ()
void OnReadAll (wxCommandEvent &event)
void OnWriteAll (wxCommandEvent &event)
Protected Attributes
std::vector< ADCparam > pwrParams
std::vector< ADCparam > vltgParams
wxStaticText * totalPwr
lms_device_t * lmsControl
Detailed Description
Definition at line 14 of file pnlUltimateEVB.h.
Constructor & Destructor Documentation
pnlUltimateEVB::pnlUltimateEVB (wxWindow * parent, wxWindowID id = wxID_ANY, const wxPoint & pos = wxDefaultPosition, const wxSize & size = wxDefaultSize, int style = 0, wxString name = wxEmptyString)
Definition at line 20 of file pnlUltimateEVB.cpp.
References i, lmsControl, and OnReadAll().
pnlUltimateEVB::~pnlUltimateEVB () virtual
Definition at line 115 of file pnlUltimateEVB.cpp.
Member Function Documentation
void pnlUltimateEVB::Initialize (lms_device_t * pControl)
Definition at line 110 of file pnlUltimateEVB.cpp.
References lmsControl.
Referenced by pnlBoardControls::SetupControls().
void pnlUltimateEVB::OnReadAll (wxCommandEvent & event)
Definition at line 119 of file pnlUltimateEVB.cpp.
References i, LMS_ReadCustomBoardParam(), lmsControl, status, and units.
Referenced by pnlUltimateEVB().
void pnlUltimateEVB::OnWriteAll (wxCommandEvent & event)
Definition at line 152 of file pnlUltimateEVB.cpp.
Member Data Documentation
lms_device_t* pnlUltimateEVB::lmsControl protected
Definition at line 46 of file pnlUltimateEVB.h.
std::vector<ADCparam> pnlUltimateEVB::pwrParams protected
Definition at line 43 of file pnlUltimateEVB.h.
wxStaticText* pnlUltimateEVB::totalPwr protected
Definition at line 45 of file pnlUltimateEVB.h.
std::vector<ADCparam> pnlUltimateEVB::vltgParams protected
Definition at line 44 of file pnlUltimateEVB.h.
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlUltimateEVB.h
/home/erik/prefix/default/src/limesuite-dev/src/boards_wxgui/pnlUltimateEVB.cpp