LimeSuite-UML: /home/erik/prefix/default/src/limesuite-dev/src/ConnectionFX3/CMakeLists.txt File Reference
/home/erik/prefix/default/src/limesuite-dev/src/ConnectionFX3/CMakeLists.txt File Reference
Functions
if (WIN32) find_package(CyAPI) set(USB_FOUND $
set (USB_INCLUDE_DIRS ${CYAPI_INCLUDE_DIRS}) set(USB_LIBRARIES $
SetupAPI elseif (UNIX) find_package(libusb-1.0) set(USB_FOUND $
set (USB_INCLUDE_DIRS ${LIBUSB_1_INCLUDE_DIRS}) set(USB_LIBRARIES $
endif () message(STATUS"USB_INCLUDE_DIRS
message (STATUS"USB_LIBRARIES: ${USB_LIBRARIES}") set(THIS_SOURCE_DIR $
ConnectionFX3 set (CONNECTION_FX3_SOURCES ${THIS_SOURCE_DIR}/ConnectionFX3Entry.cpp ${THIS_SOURCE_DIR}/ConnectionFX3.cpp) set(CONNECTION_FX3_LIBRARIES $
include (FeatureSummary) include(CMakeDependentOption) cmake_dependent_option(ENABLE_FX3"Enable FX3"ON"ENABLE_LIBRARY
USB_FOUND OFF add_feature_info (ConnectionFX3 ENABLE_FX3"FX3 Connection support") if(NOT ENABLE_FX3) return() endif() target_include_directories(LimeSuite PUBLIC $
target_sources (LimeSuite PRIVATE ${CONNECTION_FX3_SOURCES}) target_link_libraries(LimeSuite $
Function Documentation
USB_FOUND OFF add_feature_info (ConnectionFX3 ENABLE_FX3"FX3 Connection support")
Definition at line 37 of file CMakeLists.txt.
Referenced by set().
SetupAPI elseif (UNIX)
Definition at line 10 of file CMakeLists.txt.
Referenced by install(), and target_include_directories().
endif ()
Definition at line 15 of file CMakeLists.txt.
if (WIN32)
Definition at line 5 of file CMakeLists.txt.
include (FeatureSummary)
Definition at line 1 of file CMakeLists.txt.
Referenced by endif(), find_package(), and set().
message (STATUS"USB_LIBRARIES: ${USB_LIBRARIES}")
Definition at line 18 of file CMakeLists.txt.
set (USB_INCLUDE_DIRS ${CYAPI_INCLUDE_DIRS})
Definition at line 8 of file CMakeLists.txt.
set (USB_INCLUDE_DIRS ${LIBUSB_1_INCLUDE_DIRS})
Definition at line 13 of file CMakeLists.txt.
ConnectionFX3 set (CONNECTION_FX3_SOURCES ${THIS_SOURCE_DIR}/ConnectionFX3Entry.cpp ${THIS_SOURCE_DIR}/ConnectionFX3. cpp)
Definition at line 22 of file CMakeLists.txt.
target_sources (LimeSuite PRIVATE ${CONNECTION_FX3_SOURCES})
Definition at line 46 of file CMakeLists.txt.
Referenced by set().