LimeSuite-UML: /home/erik/prefix/default/src/soapysdr/lib/DefaultConverters.cpp File Reference
DefaultConverters.cpp File Reference
#include <SoapySDR/ConverterPrimatives.hpp>
#include <SoapySDR/ConverterRegistry.hpp>
#include <SoapySDR/Formats.hpp>
#include <cstring>
Functions
static void genericF32toF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericF32toF32 (SOAPY_SDR_F32, SOAPY_SDR_F32, SoapySDR::ConverterRegistry::GENERIC,&genericF32toF32)
static void genericS32toS32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericS32toS32 (SOAPY_SDR_S32, SOAPY_SDR_S32, SoapySDR::ConverterRegistry::GENERIC,&genericS32toS32)
static void genericS16toS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericS16toS16 (SOAPY_SDR_S16, SOAPY_SDR_S16, SoapySDR::ConverterRegistry::GENERIC,&genericS16toS16)
static void genericS8toS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericS8toS8 (SOAPY_SDR_S8, SOAPY_SDR_S8, SoapySDR::ConverterRegistry::GENERIC,&genericS8toS8)
static void genericF32toS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericS16toF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericF32toS16 (SOAPY_SDR_F32, SOAPY_SDR_S16, SoapySDR::ConverterRegistry::GENERIC,&genericF32toS16)
static SoapySDR::ConverterRegistry registerGenericS16toF32 (SOAPY_SDR_S16, SOAPY_SDR_F32, SoapySDR::ConverterRegistry::GENERIC,&genericS16toF32)
static void genericF32toU16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericU16toF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericF32toU16 (SOAPY_SDR_F32, SOAPY_SDR_U16, SoapySDR::ConverterRegistry::GENERIC,&genericF32toU16)
static SoapySDR::ConverterRegistry registerGenericU16toF32 (SOAPY_SDR_U16, SOAPY_SDR_F32, SoapySDR::ConverterRegistry::GENERIC,&genericU16toF32)
static void genericF32toS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericS8toF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericF32toS8 (SOAPY_SDR_F32, SOAPY_SDR_S8, SoapySDR::ConverterRegistry::GENERIC,&genericF32toS8)
static SoapySDR::ConverterRegistry registerGenericS8toF32 (SOAPY_SDR_S8, SOAPY_SDR_F32, SoapySDR::ConverterRegistry::GENERIC,&genericS8toF32)
static void genericF32toU8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericU8toF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericF32toU8 (SOAPY_SDR_F32, SOAPY_SDR_U8, SoapySDR::ConverterRegistry::GENERIC,&genericF32toU8)
static SoapySDR::ConverterRegistry registerGenericU8toF32 (SOAPY_SDR_U8, SOAPY_SDR_F32, SoapySDR::ConverterRegistry::GENERIC,&genericU8toF32)
static void genericS16toU16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericU16toS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericS16toU16 (SOAPY_SDR_S16, SOAPY_SDR_U16, SoapySDR::ConverterRegistry::GENERIC,&genericS16toU16)
static SoapySDR::ConverterRegistry registerGenericU16toS16 (SOAPY_SDR_U16, SOAPY_SDR_S16, SoapySDR::ConverterRegistry::GENERIC,&genericU16toS16)
static void genericS16toS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericS8toS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericS16toS8 (SOAPY_SDR_S16, SOAPY_SDR_S8, SoapySDR::ConverterRegistry::GENERIC,&genericS16toS8)
static SoapySDR::ConverterRegistry registerGenericS8toS16 (SOAPY_SDR_S8, SOAPY_SDR_S16, SoapySDR::ConverterRegistry::GENERIC,&genericS8toS16)
static void genericS16toU8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericU8toS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericS16toU8 (SOAPY_SDR_S16, SOAPY_SDR_U8, SoapySDR::ConverterRegistry::GENERIC,&genericS16toU8)
static SoapySDR::ConverterRegistry registerGenericU8toS16 (SOAPY_SDR_U8, SOAPY_SDR_S16, SoapySDR::ConverterRegistry::GENERIC,&genericU8toS16)
static void genericU16toS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericS8toU16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericU16toS8 (SOAPY_SDR_U16, SOAPY_SDR_S8, SoapySDR::ConverterRegistry::GENERIC,&genericU16toS8)
static SoapySDR::ConverterRegistry registerGenericS8toU16 (SOAPY_SDR_S8, SOAPY_SDR_U16, SoapySDR::ConverterRegistry::GENERIC,&genericS8toU16)
static void genericS8toU8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericU8toS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericS8toU8 (SOAPY_SDR_S8, SOAPY_SDR_U8, SoapySDR::ConverterRegistry::GENERIC,&genericS8toU8)
static SoapySDR::ConverterRegistry registerGenericU8toS8 (SOAPY_SDR_U8, SOAPY_SDR_S8, SoapySDR::ConverterRegistry::GENERIC,&genericU8toS8)
static void genericCF32toCF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCF32toCF32 (SOAPY_SDR_CF32, SOAPY_SDR_CF32, SoapySDR::ConverterRegistry::GENERIC,&genericCF32toCF32)
static void genericCS32toCS32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCS32toCS32 (SOAPY_SDR_CS32, SOAPY_SDR_CS32, SoapySDR::ConverterRegistry::GENERIC,&genericCS32toCS32)
static void genericCS16toCS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCS16toCS16 (SOAPY_SDR_CS16, SOAPY_SDR_CS16, SoapySDR::ConverterRegistry::GENERIC,&genericCS16toCS16)
static void genericCS8toCS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCS8toCS8 (SOAPY_SDR_CS8, SOAPY_SDR_CS8, SoapySDR::ConverterRegistry::GENERIC,&genericCS8toCS8)
static void genericCF32toCS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCS16toCF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCF32toCS16 (SOAPY_SDR_CF32, SOAPY_SDR_CS16, SoapySDR::ConverterRegistry::GENERIC,&genericCF32toCS16)
static SoapySDR::ConverterRegistry registerGenericCS16toCF32 (SOAPY_SDR_CS16, SOAPY_SDR_CF32, SoapySDR::ConverterRegistry::GENERIC,&genericCS16toCF32)
static void genericCF32toCU16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCU16toCF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCF32toCU16 (SOAPY_SDR_CF32, SOAPY_SDR_CU16, SoapySDR::ConverterRegistry::GENERIC,&genericCF32toCU16)
static SoapySDR::ConverterRegistry registerGenericCU16toCF32 (SOAPY_SDR_CU16, SOAPY_SDR_CF32, SoapySDR::ConverterRegistry::GENERIC,&genericCU16toCF32)
static void genericCF32toCS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCS8toCF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCF32toCS8 (SOAPY_SDR_CF32, SOAPY_SDR_CS8, SoapySDR::ConverterRegistry::GENERIC,&genericCF32toCS8)
static SoapySDR::ConverterRegistry registerGenericCS8toCF32 (SOAPY_SDR_CS8, SOAPY_SDR_CF32, SoapySDR::ConverterRegistry::GENERIC,&genericCS8toCF32)
static void genericCF32toCU8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCU8toCF32 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCF32toCU8 (SOAPY_SDR_CF32, SOAPY_SDR_CU8, SoapySDR::ConverterRegistry::GENERIC,&genericCF32toCU8)
static SoapySDR::ConverterRegistry registerGenericCU8toCF32 (SOAPY_SDR_CU8, SOAPY_SDR_CF32, SoapySDR::ConverterRegistry::GENERIC,&genericCU8toCF32)
static void genericCS16toCU16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCU16toCS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCS16toCU16 (SOAPY_SDR_CS16, SOAPY_SDR_CU16, SoapySDR::ConverterRegistry::GENERIC,&genericCS16toCU16)
static SoapySDR::ConverterRegistry registerGenericCU16toCS16 (SOAPY_SDR_CU16, SOAPY_SDR_CS16, SoapySDR::ConverterRegistry::GENERIC,&genericCU16toCS16)
static void genericCS16toCS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCS8toCS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCS16toCS8 (SOAPY_SDR_CS16, SOAPY_SDR_CS8, SoapySDR::ConverterRegistry::GENERIC,&genericCS16toCS8)
static SoapySDR::ConverterRegistry registerGenericCS8toCS16 (SOAPY_SDR_CS8, SOAPY_SDR_CS16, SoapySDR::ConverterRegistry::GENERIC,&genericCS8toCS16)
static void genericCS16toCU8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCU8toCS16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCS16toCU8 (SOAPY_SDR_CS16, SOAPY_SDR_CU8, SoapySDR::ConverterRegistry::GENERIC,&genericCS16toCU8)
static SoapySDR::ConverterRegistry registerGenericCU8toCS16 (SOAPY_SDR_CU8, SOAPY_SDR_CS16, SoapySDR::ConverterRegistry::GENERIC,&genericCU8toCS16)
static void genericCU16toCS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCS8toCU16 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCU16toCS8 (SOAPY_SDR_CU16, SOAPY_SDR_CS8, SoapySDR::ConverterRegistry::GENERIC,&genericCU16toCS8)
static SoapySDR::ConverterRegistry registerGenericCS8toCU16 (SOAPY_SDR_CS8, SOAPY_SDR_CU16, SoapySDR::ConverterRegistry::GENERIC,&genericCS8toCU16)
static void genericCS8toCU8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static void genericCU8toCS8 (const void *srcBuff, void *dstBuff, const size_t numElems, const double scaler)
static SoapySDR::ConverterRegistry registerGenericCS8toCU8 (SOAPY_SDR_CS8, SOAPY_SDR_CU8, SoapySDR::ConverterRegistry::GENERIC,&genericCS8toCU8)
static SoapySDR::ConverterRegistry registerGenericCU8toCS8 (SOAPY_SDR_CU8, SOAPY_SDR_CS8, SoapySDR::ConverterRegistry::GENERIC,&genericCU8toCS8)
Function Documentation
static void genericCF32toCF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 375 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericCF32toCF32(), SOAPY_SDR_CF32, and src.
static void genericCF32toCS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 470 of file DefaultConverters.cpp.
References SoapySDR::F32toS16(), i, and src.
Referenced by genericCS16toCF32().
static void genericCF32toCS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 528 of file DefaultConverters.cpp.
References SoapySDR::F32toS8(), i, and src.
Referenced by genericCS8toCF32().
static void genericCF32toCU16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 499 of file DefaultConverters.cpp.
References SoapySDR::F32toU16(), i, and src.
Referenced by genericCU16toCF32().
static void genericCF32toCU8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 557 of file DefaultConverters.cpp.
References SoapySDR::F32toU8(), i, and src.
Referenced by genericCU8toCF32().
static void genericCS16toCF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 482 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCF32toCS16(), i, registerGenericCF32toCS16(), registerGenericCS16toCF32(), SoapySDR::S16toF32(), SOAPY_SDR_CF32, SOAPY_SDR_CS16, and src.
static void genericCS16toCS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 421 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericCS16toCS16(), SOAPY_SDR_CS16, and src.
static void genericCS16toCS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 614 of file DefaultConverters.cpp.
References i, SoapySDR::S16toS8(), and src.
Referenced by genericCS8toCS16().
static void genericCS16toCU16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 585 of file DefaultConverters.cpp.
References i, SoapySDR::S16toU16(), and src.
Referenced by genericCU16toCS16().
static void genericCS16toCU8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 642 of file DefaultConverters.cpp.
References i, SoapySDR::S16toU8(), and src.
Referenced by genericCU8toCS16().
static void genericCS32toCS32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 398 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericCS32toCS32(), SOAPY_SDR_CS32, and src.
static void genericCS8toCF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 540 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCF32toCS8(), i, registerGenericCF32toCS8(), registerGenericCS8toCF32(), SoapySDR::S8toF32(), SOAPY_SDR_CF32, SOAPY_SDR_CS8, and src.
static void genericCS8toCS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 626 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCS16toCS8(), i, registerGenericCS16toCS8(), registerGenericCS8toCS16(), SoapySDR::S8toS16(), SOAPY_SDR_CS16, SOAPY_SDR_CS8, and src.
static void genericCS8toCS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 444 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericCS8toCS8(), SOAPY_SDR_CS8, and src.
static void genericCS8toCU16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 682 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCU16toCS8(), i, registerGenericCS8toCU16(), registerGenericCU16toCS8(), SoapySDR::S8toU16(), SOAPY_SDR_CS8, SOAPY_SDR_CU16, and src.
static void genericCS8toCU8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 698 of file DefaultConverters.cpp.
References i, SoapySDR::S8toU8(), and src.
Referenced by genericCU8toCS8().
static void genericCU16toCF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 511 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCF32toCU16(), i, registerGenericCF32toCU16(), registerGenericCU16toCF32(), SOAPY_SDR_CF32, SOAPY_SDR_CU16, src, and SoapySDR::U16toF32().
static void genericCU16toCS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 597 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCS16toCU16(), i, registerGenericCS16toCU16(), registerGenericCU16toCS16(), SOAPY_SDR_CS16, SOAPY_SDR_CU16, src, and SoapySDR::U16toS16().
static void genericCU16toCS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 670 of file DefaultConverters.cpp.
References i, src, and SoapySDR::U16toS8().
Referenced by genericCS8toCU16().
static void genericCU8toCF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 569 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCF32toCU8(), i, registerGenericCF32toCU8(), registerGenericCU8toCF32(), SOAPY_SDR_CF32, SOAPY_SDR_CU8, src, and SoapySDR::U8toF32().
static void genericCU8toCS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 654 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCS16toCU8(), i, registerGenericCS16toCU8(), registerGenericCU8toCS16(), SOAPY_SDR_CS16, SOAPY_SDR_CU8, src, and SoapySDR::U8toS16().
static void genericCU8toCS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 710 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericCS8toCU8(), i, registerGenericCS8toCU8(), registerGenericCU8toCS8(), SOAPY_SDR_CS8, SOAPY_SDR_CU8, src, and SoapySDR::U8toS8().
static void genericF32toF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 18 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericF32toF32(), SOAPY_SDR_F32, and src.
static void genericF32toS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 113 of file DefaultConverters.cpp.
References SoapySDR::F32toS16(), i, and src.
Referenced by genericS16toF32().
static void genericF32toS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 171 of file DefaultConverters.cpp.
References SoapySDR::F32toS8(), i, and src.
Referenced by genericS8toF32().
static void genericF32toU16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 142 of file DefaultConverters.cpp.
References SoapySDR::F32toU16(), i, and src.
Referenced by genericU16toF32().
static void genericF32toU8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 200 of file DefaultConverters.cpp.
References SoapySDR::F32toU8(), i, and src.
Referenced by genericU8toF32().
static void genericS16toF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 125 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericF32toS16(), i, registerGenericF32toS16(), registerGenericS16toF32(), SoapySDR::S16toF32(), SOAPY_SDR_F32, SOAPY_SDR_S16, and src.
static void genericS16toS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 64 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericS16toS16(), SOAPY_SDR_S16, and src.
static void genericS16toS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 257 of file DefaultConverters.cpp.
References i, SoapySDR::S16toS8(), and src.
Referenced by genericS8toS16().
static void genericS16toU16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 228 of file DefaultConverters.cpp.
References i, SoapySDR::S16toU16(), and src.
Referenced by genericU16toS16().
static void genericS16toU8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 285 of file DefaultConverters.cpp.
References i, SoapySDR::S16toU8(), and src.
Referenced by genericU8toS16().
static void genericS32toS32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 41 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericS32toS32(), SOAPY_SDR_S32, and src.
static void genericS8toF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 183 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericF32toS8(), i, registerGenericF32toS8(), registerGenericS8toF32(), SoapySDR::S8toF32(), SOAPY_SDR_F32, SOAPY_SDR_S8, and src.
static void genericS8toS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 269 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericS16toS8(), i, registerGenericS16toS8(), registerGenericS8toS16(), SoapySDR::S8toS16(), SOAPY_SDR_S16, SOAPY_SDR_S8, and src.
static void genericS8toS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 87 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, i, registerGenericS8toS8(), SOAPY_SDR_S8, and src.
static void genericS8toU16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 325 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericU16toS8(), i, registerGenericS8toU16(), registerGenericU16toS8(), SoapySDR::S8toU16(), SOAPY_SDR_S8, SOAPY_SDR_U16, and src.
static void genericS8toU8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 341 of file DefaultConverters.cpp.
References i, SoapySDR::S8toU8(), and src.
Referenced by genericU8toS8().
static void genericU16toF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 154 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericF32toU16(), i, registerGenericF32toU16(), registerGenericU16toF32(), SOAPY_SDR_F32, SOAPY_SDR_U16, src, and SoapySDR::U16toF32().
static void genericU16toS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 240 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericS16toU16(), i, registerGenericS16toU16(), registerGenericU16toS16(), SOAPY_SDR_S16, SOAPY_SDR_U16, src, and SoapySDR::U16toS16().
static void genericU16toS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 313 of file DefaultConverters.cpp.
References i, src, and SoapySDR::U16toS8().
Referenced by genericS8toU16().
static void genericU8toF32 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 212 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericF32toU8(), i, registerGenericF32toU8(), registerGenericU8toF32(), SOAPY_SDR_F32, SOAPY_SDR_U8, src, and SoapySDR::U8toF32().
static void genericU8toS16 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 297 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericS16toU8(), i, registerGenericS16toU8(), registerGenericU8toS16(), SOAPY_SDR_S16, SOAPY_SDR_U8, src, and SoapySDR::U8toS16().
static void genericU8toS8 (const void * srcBuff, void * dstBuff, const size_t numElems, const double scaler) static
Definition at line 353 of file DefaultConverters.cpp.
References SoapySDR::ConverterRegistry::GENERIC, genericS8toU8(), i, registerGenericS8toU8(), registerGenericU8toS8(), SOAPY_SDR_S8, SOAPY_SDR_U8, src, and SoapySDR::U8toS8().
static SoapySDR::ConverterRegistry registerGenericCF32toCF32 (SOAPY_SDR_CF32 , SOAPY_SDR_CF32 , SoapySDR::ConverterRegistry::GENERIC , & genericCF32toCF32) static
Referenced by genericCF32toCF32().
static SoapySDR::ConverterRegistry registerGenericCF32toCS16 (SOAPY_SDR_CF32 , SOAPY_SDR_CS16 , SoapySDR::ConverterRegistry::GENERIC , & genericCF32toCS16) static
Referenced by genericCS16toCF32().
static SoapySDR::ConverterRegistry registerGenericCF32toCS8 (SOAPY_SDR_CF32 , SOAPY_SDR_CS8 , SoapySDR::ConverterRegistry::GENERIC , & genericCF32toCS8) static
Referenced by genericCS8toCF32().
static SoapySDR::ConverterRegistry registerGenericCF32toCU16 (SOAPY_SDR_CF32 , SOAPY_SDR_CU16 , SoapySDR::ConverterRegistry::GENERIC , & genericCF32toCU16) static
Referenced by genericCU16toCF32().
static SoapySDR::ConverterRegistry registerGenericCF32toCU8 (SOAPY_SDR_CF32 , SOAPY_SDR_CU8 , SoapySDR::ConverterRegistry::GENERIC , & genericCF32toCU8) static
Referenced by genericCU8toCF32().
static SoapySDR::ConverterRegistry registerGenericCS16toCF32 (SOAPY_SDR_CS16 , SOAPY_SDR_CF32 , SoapySDR::ConverterRegistry::GENERIC , & genericCS16toCF32) static
Referenced by genericCS16toCF32().
static SoapySDR::ConverterRegistry registerGenericCS16toCS16 (SOAPY_SDR_CS16 , SOAPY_SDR_CS16 , SoapySDR::ConverterRegistry::GENERIC , & genericCS16toCS16) static
Referenced by genericCS16toCS16().
static SoapySDR::ConverterRegistry registerGenericCS16toCS8 (SOAPY_SDR_CS16 , SOAPY_SDR_CS8 , SoapySDR::ConverterRegistry::GENERIC , & genericCS16toCS8) static
Referenced by genericCS8toCS16().
static SoapySDR::ConverterRegistry registerGenericCS16toCU16 (SOAPY_SDR_CS16 , SOAPY_SDR_CU16 , SoapySDR::ConverterRegistry::GENERIC , & genericCS16toCU16) static
Referenced by genericCU16toCS16().
static SoapySDR::ConverterRegistry registerGenericCS16toCU8 (SOAPY_SDR_CS16 , SOAPY_SDR_CU8 , SoapySDR::ConverterRegistry::GENERIC , & genericCS16toCU8) static
Referenced by genericCU8toCS16().
static SoapySDR::ConverterRegistry registerGenericCS32toCS32 (SOAPY_SDR_CS32 , SOAPY_SDR_CS32 , SoapySDR::ConverterRegistry::GENERIC , & genericCS32toCS32) static
Referenced by genericCS32toCS32().
static SoapySDR::ConverterRegistry registerGenericCS8toCF32 (SOAPY_SDR_CS8 , SOAPY_SDR_CF32 , SoapySDR::ConverterRegistry::GENERIC , & genericCS8toCF32) static
Referenced by genericCS8toCF32().
static SoapySDR::ConverterRegistry registerGenericCS8toCS16 (SOAPY_SDR_CS8 , SOAPY_SDR_CS16 , SoapySDR::ConverterRegistry::GENERIC , & genericCS8toCS16) static
Referenced by genericCS8toCS16().
static SoapySDR::ConverterRegistry registerGenericCS8toCS8 (SOAPY_SDR_CS8 , SOAPY_SDR_CS8 , SoapySDR::ConverterRegistry::GENERIC , & genericCS8toCS8) static
Referenced by genericCS8toCS8().
static SoapySDR::ConverterRegistry registerGenericCS8toCU16 (SOAPY_SDR_CS8 , SOAPY_SDR_CU16 , SoapySDR::ConverterRegistry::GENERIC , & genericCS8toCU16) static
Referenced by genericCS8toCU16().
static SoapySDR::ConverterRegistry registerGenericCS8toCU8 (SOAPY_SDR_CS8 , SOAPY_SDR_CU8 , SoapySDR::ConverterRegistry::GENERIC , & genericCS8toCU8) static
Referenced by genericCU8toCS8().
static SoapySDR::ConverterRegistry registerGenericCU16toCF32 (SOAPY_SDR_CU16 , SOAPY_SDR_CF32 , SoapySDR::ConverterRegistry::GENERIC , & genericCU16toCF32) static
Referenced by genericCU16toCF32().
static SoapySDR::ConverterRegistry registerGenericCU16toCS16 (SOAPY_SDR_CU16 , SOAPY_SDR_CS16 , SoapySDR::ConverterRegistry::GENERIC , & genericCU16toCS16) static
Referenced by genericCU16toCS16().
static SoapySDR::ConverterRegistry registerGenericCU16toCS8 (SOAPY_SDR_CU16 , SOAPY_SDR_CS8 , SoapySDR::ConverterRegistry::GENERIC , & genericCU16toCS8) static
Referenced by genericCS8toCU16().
static SoapySDR::ConverterRegistry registerGenericCU8toCF32 (SOAPY_SDR_CU8 , SOAPY_SDR_CF32 , SoapySDR::ConverterRegistry::GENERIC , & genericCU8toCF32) static
Referenced by genericCU8toCF32().
static SoapySDR::ConverterRegistry registerGenericCU8toCS16 (SOAPY_SDR_CU8 , SOAPY_SDR_CS16 , SoapySDR::ConverterRegistry::GENERIC , & genericCU8toCS16) static
Referenced by genericCU8toCS16().
static SoapySDR::ConverterRegistry registerGenericCU8toCS8 (SOAPY_SDR_CU8 , SOAPY_SDR_CS8 , SoapySDR::ConverterRegistry::GENERIC , & genericCU8toCS8) static
Referenced by genericCU8toCS8().
static SoapySDR::ConverterRegistry registerGenericF32toF32 (SOAPY_SDR_F32 , SOAPY_SDR_F32 , SoapySDR::ConverterRegistry::GENERIC , & genericF32toF32) static
Referenced by genericF32toF32().
static SoapySDR::ConverterRegistry registerGenericF32toS16 (SOAPY_SDR_F32 , SOAPY_SDR_S16 , SoapySDR::ConverterRegistry::GENERIC , & genericF32toS16) static
Referenced by genericS16toF32().
static SoapySDR::ConverterRegistry registerGenericF32toS8 (SOAPY_SDR_F32 , SOAPY_SDR_S8 , SoapySDR::ConverterRegistry::GENERIC , & genericF32toS8) static
Referenced by genericS8toF32().
static SoapySDR::ConverterRegistry registerGenericF32toU16 (SOAPY_SDR_F32 , SOAPY_SDR_U16 , SoapySDR::ConverterRegistry::GENERIC , & genericF32toU16) static
Referenced by genericU16toF32().
static SoapySDR::ConverterRegistry registerGenericF32toU8 (SOAPY_SDR_F32 , SOAPY_SDR_U8 , SoapySDR::ConverterRegistry::GENERIC , & genericF32toU8) static
Referenced by genericU8toF32().
static SoapySDR::ConverterRegistry registerGenericS16toF32 (SOAPY_SDR_S16 , SOAPY_SDR_F32 , SoapySDR::ConverterRegistry::GENERIC , & genericS16toF32) static
Referenced by genericS16toF32().
static SoapySDR::ConverterRegistry registerGenericS16toS16 (SOAPY_SDR_S16 , SOAPY_SDR_S16 , SoapySDR::ConverterRegistry::GENERIC , & genericS16toS16) static
Referenced by genericS16toS16().
static SoapySDR::ConverterRegistry registerGenericS16toS8 (SOAPY_SDR_S16 , SOAPY_SDR_S8 , SoapySDR::ConverterRegistry::GENERIC , & genericS16toS8) static
Referenced by genericS8toS16().
static SoapySDR::ConverterRegistry registerGenericS16toU16 (SOAPY_SDR_S16 , SOAPY_SDR_U16 , SoapySDR::ConverterRegistry::GENERIC , & genericS16toU16) static
Referenced by genericU16toS16().
static SoapySDR::ConverterRegistry registerGenericS16toU8 (SOAPY_SDR_S16 , SOAPY_SDR_U8 , SoapySDR::ConverterRegistry::GENERIC , & genericS16toU8) static
Referenced by genericU8toS16().
static SoapySDR::ConverterRegistry registerGenericS32toS32 (SOAPY_SDR_S32 , SOAPY_SDR_S32 , SoapySDR::ConverterRegistry::GENERIC , & genericS32toS32) static
Referenced by genericS32toS32().
static SoapySDR::ConverterRegistry registerGenericS8toF32 (SOAPY_SDR_S8 , SOAPY_SDR_F32 , SoapySDR::ConverterRegistry::GENERIC , & genericS8toF32) static
Referenced by genericS8toF32().
static SoapySDR::ConverterRegistry registerGenericS8toS16 (SOAPY_SDR_S8 , SOAPY_SDR_S16 , SoapySDR::ConverterRegistry::GENERIC , & genericS8toS16) static
Referenced by genericS8toS16().
static SoapySDR::ConverterRegistry registerGenericS8toS8 (SOAPY_SDR_S8 , SOAPY_SDR_S8 , SoapySDR::ConverterRegistry::GENERIC , & genericS8toS8) static
Referenced by genericS8toS8().
static SoapySDR::ConverterRegistry registerGenericS8toU16 (SOAPY_SDR_S8 , SOAPY_SDR_U16 , SoapySDR::ConverterRegistry::GENERIC , & genericS8toU16) static
Referenced by genericS8toU16().
static SoapySDR::ConverterRegistry registerGenericS8toU8 (SOAPY_SDR_S8 , SOAPY_SDR_U8 , SoapySDR::ConverterRegistry::GENERIC , & genericS8toU8) static
Referenced by genericU8toS8().
static SoapySDR::ConverterRegistry registerGenericU16toF32 (SOAPY_SDR_U16 , SOAPY_SDR_F32 , SoapySDR::ConverterRegistry::GENERIC , & genericU16toF32) static
Referenced by genericU16toF32().
static SoapySDR::ConverterRegistry registerGenericU16toS16 (SOAPY_SDR_U16 , SOAPY_SDR_S16 , SoapySDR::ConverterRegistry::GENERIC , & genericU16toS16) static
Referenced by genericU16toS16().
static SoapySDR::ConverterRegistry registerGenericU16toS8 (SOAPY_SDR_U16 , SOAPY_SDR_S8 , SoapySDR::ConverterRegistry::GENERIC , & genericU16toS8) static
Referenced by genericS8toU16().
static SoapySDR::ConverterRegistry registerGenericU8toF32 (SOAPY_SDR_U8 , SOAPY_SDR_F32 , SoapySDR::ConverterRegistry::GENERIC , & genericU8toF32) static
Referenced by genericU8toF32().
static SoapySDR::ConverterRegistry registerGenericU8toS16 (SOAPY_SDR_U8 , SOAPY_SDR_S16 , SoapySDR::ConverterRegistry::GENERIC , & genericU8toS16) static
Referenced by genericU8toS16().
static SoapySDR::ConverterRegistry registerGenericU8toS8 (SOAPY_SDR_U8 , SOAPY_SDR_S8 , SoapySDR::ConverterRegistry::GENERIC , & genericU8toS8) static
Referenced by genericU8toS8().