LimeSuite-UML: lms7002_pnlMCU_BD_view Class Reference
lms7002_pnlMCU_BD_view Class Reference
Implementing pnlMCU_BD_view.
#include <lms7002_pnlMCU_BD_view.h>
Public Member Functions
lms7002_pnlMCU_BD_view (wxWindow *parent)
Constructor.
~lms7002_pnlMCU_BD_view ()
void Initialize (lms_device_t *ptr)
Public Member Functions inherited from pnlMCU_BD_view
pnlMCU_BD_view (wxWindow *parent, wxWindowID id=wxID_ANY, const wxPoint &pos=wxDefaultPosition, const wxSize &size=wxSize(-1,-1), long style=wxTAB_TRAVERSAL)
~pnlMCU_BD_view ()
Protected Member Functions
void OnButton_LOADHexClick (wxCommandEvent &event)
void OnchkResetClick (wxCommandEvent &event)
void OnbtnStartProgrammingClick (wxCommandEvent &event)
void OnbtnLoadTestFileClick (wxCommandEvent &event)
void OnbtnRunTestClick (wxCommandEvent &event)
void OnDebugModeClick (wxCommandEvent &event)
void OnRunInstruction (wxCommandEvent &event)
void OnResetPCClick (wxCommandEvent &event)
void OnViewSFRsClick (wxCommandEvent &event)
void OnViewIRAMClick (wxCommandEvent &event)
void OnEraseIRAMClick (wxCommandEvent &event)
void OnSelDivSelect (wxCommandEvent &event)
void Onm_cCtrlBasebandSelect (wxCommandEvent &event)
void Onm_cCtrlMCU_BDSelect (wxCommandEvent &event)
void OnRegWriteRead (wxCommandEvent &event)
void OnbtnRunProductionTestClicked (wxCommandEvent &event)
int GetProgramCode (const char *inFileName, bool bin)
Read program code from file into memory.
void RunTest_MCU (int m_iMode1, int m_iMode0, unsigned short test_code, int m_iDebug)
void Wait_CLK_Cycles (int delay)
void DebugModeSet_MCU (int m_iMode1, int m_iMode0)
void DebugModeExit_MCU (int m_iMode1, int m_iMode0)
int ResetPC_MCU ()
int Change_MCUFrequency (unsigned char data)
int One_byte_command (unsigned short data1, unsigned char *rdata1)
int Three_byte_command (unsigned char data1, unsigned char data2, unsigned char data3, unsigned char *rdata1, unsigned char *rdata2, unsigned char *rdata3)
void OnProgramingStatusUpdate (wxCommandEvent &event)
int WaitUntilWritten ()
int RunProductionTest_MCU ()
int Read_IRAM ()
int ReadOneByte (unsigned char *data)
int Read_SFR ()
int Erase_IRAM ()
int RunInstr_MCU (unsigned short *pPCVAL)
void OnReadIRAMfinished (wxThreadEvent &event)
void OnEraseIRAMfinished (wxThreadEvent &event)
void OnReadSFRfinished (wxThreadEvent &event)
void OnProgrammingfinished (wxThreadEvent &event)
Static Protected Member Functions
static bool OnProgrammingCallback (int bsent, int btotal, const char *progressMsg)
Protected Attributes
bool mThreadWorking
std::thread mWorkerThread
wxTimer * progressPooler
lms_device_t * lmsControl
int m_iTestNo
int m_iInstrNo
int m_iPCvalue
int m_iDebug
int m_iMode0
int m_iMode1
int m_iTestResultFileLine
int TestResultArray_code [256]
int TestResultArray_address [256]
int TestResultArray_value [256]
unsigned short m_iRegAddress
int m_iRegRead
unsigned short m_iRegData
int m_bLoadedProd
int m_bLoadedDebug
std::string mLoadedProgramFilename
unsigned char byte_array [max_array_size]
int m_iLoopTries
unsigned char m_IRAM [256]
unsigned char m_SFR [256]
Protected Attributes inherited from pnlMCU_BD_view
wxStaticText * ID_STATICTEXT1
wxButton * Button_LOADHEX
wxCheckBox * chkReset
wxRadioBox * rgrMode
wxButton * btnStartProgramming
wxStaticText * ID_S_PROGFINISHED
wxStaticText * ID_STATICTEXT3
wxButton * btnRunTest
wxStaticText * ID_STATICTEXT4
wxTextCtrl * m_sTestNo
wxButton * btnRunProductionTest
wxCheckBox * DebugMode
wxButton * RunInstr
wxStaticText * ID_STATICTEXT6
wxTextCtrl * InstrNo
wxButton * ResetPC
wxStaticText * ID_STATICTEXT7
wxStaticText * PCValue
wxButton * ViewSFRs
wxButton * ViewIRAM
wxButton * EraseIRAM
wxStaticText * ID_STATICTEXT10
wxChoice * SelDiv
wxRadioButton * m_cCtrlBaseband
wxRadioButton * m_cCtrlMCU_BD
wxStaticText * ID_STATICTEXT5
wxChoice * cmbRegAddr
wxRadioButton * rbtnRegWrite
wxStaticText * ID_STATICTEXT11
wxTextCtrl * txtRegValueWr
wxRadioButton * rbtnRegRead
wxStaticText * ReadResult
wxButton * btnRdWr
wxStaticText * ID_STATICTEXT2
wxGauge * progressBar
wxStaticText * lblProgCodeFile
wxStaticText * lblTestResultsFile
Static Protected Attributes
static const size_t max_array_size = 16 * 1024
static lms7002_pnlMCU_BD_view * obj_ptr =nullptr
static const long ID_PROGRAMING_STATUS_EVENT = wxNewId()
static const long ID_PROGRAMING_FINISH_EVENT = wxNewId()
Additional Inherited Members
Protected Types inherited from pnlMCU_BD_view
enum {
ID_CHECKBOX_RESETMCU = 2048, ID_TESTNO, ID_DEBUGMODE, ID_RUNINSTR,
ID_INSTRNO, ID_RESETPC, ID_SELDIV, ID_RADIOBUTTON4,
ID_RADIOBUTTON5
}
Detailed Description
Implementing pnlMCU_BD_view.
Definition at line 17 of file lms7002_pnlMCU_BD_view.h.
Constructor & Destructor Documentation
lms7002_pnlMCU_BD_view::lms7002_pnlMCU_BD_view (wxWindow * parent)
Constructor.
Definition at line 14 of file lms7002_pnlMCU_BD_view.cpp.
References pnlMCU_BD_view::chkReset, pnlMCU_BD_view::cmbRegAddr, pnlMCU_BD_view::EraseIRAM, pnlMCU_BD_view::InstrNo, m_bLoadedDebug, m_bLoadedProd, m_iDebug, m_iInstrNo, m_iLoopTries, m_iMode0, m_iMode1, m_iPCvalue, m_iRegAddress, m_iRegRead, m_iTestNo, pnlMCU_BD_view::m_sTestNo, mLoadedProgramFilename, mThreadWorking, obj_ptr, pnlMCU_BD_view::PCValue, progressPooler, pnlMCU_BD_view::ResetPC, pnlMCU_BD_view::RunInstr, pnlMCU_BD_view::SelDiv, pnlMCU_BD_view::ViewIRAM, and pnlMCU_BD_view::ViewSFRs.
lms7002_pnlMCU_BD_view::~lms7002_pnlMCU_BD_view ()
Definition at line 57 of file lms7002_pnlMCU_BD_view.cpp.
References mThreadWorking, and mWorkerThread.
Member Function Documentation
int lms7002_pnlMCU_BD_view::Change_MCUFrequency (unsigned char data) protected
Definition at line 1022 of file lms7002_pnlMCU_BD_view.cpp.
References Three_byte_command().
Referenced by OnSelDivSelect().
void lms7002_pnlMCU_BD_view::DebugModeExit_MCU (int m_iMode1, int m_iMode0) protected
Definition at line 376 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_WriteLMSReg(), and lmsControl.
Referenced by OnbtnRunTestClick(), and OnDebugModeClick().
void lms7002_pnlMCU_BD_view::DebugModeSet_MCU (int m_iMode1, int m_iMode0) protected
Definition at line 362 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_WriteLMSReg(), and lmsControl.
Referenced by OnbtnRunTestClick(), and OnDebugModeClick().
int lms7002_pnlMCU_BD_view::Erase_IRAM () protected
Definition at line 968 of file lms7002_pnlMCU_BD_view.cpp.
References i, m_IRAM, OnProgrammingCallback(), and Three_byte_command().
Referenced by OnEraseIRAMClick().
int lms7002_pnlMCU_BD_view::GetProgramCode (const char * inFileName, bool bin) protected
Read program code from file into memory.
Parameters
inFileName source file path
bin binary or hex file
Returns
0:success, -1:file not found
Definition at line 68 of file lms7002_pnlMCU_BD_view.cpp.
References byte_array, MCU_File::FileOpened(), MCU_File::GetByte(), i, max_array_size, mLoadedProgramFilename, and MCU_File::ReadHex().
Referenced by OnButton_LOADHexClick().
void lms7002_pnlMCU_BD_view::Initialize (lms_device_t * ptr)
Definition at line 1073 of file lms7002_pnlMCU_BD_view.cpp.
References lmsControl, and obj_ptr.
Referenced by lms7002_mainPanel::Initialize().
void lms7002_pnlMCU_BD_view::OnbtnLoadTestFileClick (wxCommandEvent & event) protected
Definition at line 218 of file lms7002_pnlMCU_BD_view.cpp.
References address, i, pnlMCU_BD_view::lblTestResultsFile, m_iTestResultFileLine, TestResultArray_address, TestResultArray_code, and TestResultArray_value.
void lms7002_pnlMCU_BD_view::OnbtnRunProductionTestClicked (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 1172 of file lms7002_pnlMCU_BD_view.cpp.
void lms7002_pnlMCU_BD_view::OnbtnRunTestClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 513 of file lms7002_pnlMCU_BD_view.cpp.
References address, DebugModeExit_MCU(), DebugModeSet_MCU(), i, pnlMCU_BD_view::lblTestResultsFile, m_iDebug, m_iMode0, m_iMode1, m_iTestNo, m_iTestResultFileLine, pnlMCU_BD_view::m_sTestNo, RunTest_MCU(), TestResultArray_address, TestResultArray_code, TestResultArray_value, and Three_byte_command().
void lms7002_pnlMCU_BD_view::OnbtnStartProgrammingClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 176 of file lms7002_pnlMCU_BD_view.cpp.
References byte_array, pnlMCU_BD_view::chkReset, pnlMCU_BD_view::DebugMode, ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, if(), LMS_Program(), lmsControl, m_iMode0, m_iMode1, max_array_size, lime::program_mode::mcuEEPROM, lime::program_mode::mcuRAM, lime::program_mode::mcuReset, mode, mThreadWorking, mWorkerThread, obj_ptr, OnProgramingStatusUpdate(), OnProgrammingCallback(), OnProgrammingfinished(), pnlMCU_BD_view::progressBar, progressPooler, and pnlMCU_BD_view::rgrMode.
void lms7002_pnlMCU_BD_view::OnButton_LOADHexClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 118 of file lms7002_pnlMCU_BD_view.cpp.
References GetProgramCode(), pnlMCU_BD_view::lblProgCodeFile, and status.
void lms7002_pnlMCU_BD_view::OnchkResetClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 143 of file lms7002_pnlMCU_BD_view.cpp.
References pnlMCU_BD_view::btnStartProgramming, pnlMCU_BD_view::chkReset, pnlMCU_BD_view::DebugMode, pnlMCU_BD_view::EraseIRAM, pnlMCU_BD_view::InstrNo, LMS_Program(), lmsControl, m_bLoadedDebug, m_bLoadedProd, m_iDebug, m_iMode0, m_iMode1, lime::program_mode::mcuReset, pnlMCU_BD_view::ResetPC, pnlMCU_BD_view::rgrMode, pnlMCU_BD_view::RunInstr, pnlMCU_BD_view::SelDiv, pnlMCU_BD_view::ViewIRAM, and pnlMCU_BD_view::ViewSFRs.
void lms7002_pnlMCU_BD_view::OnDebugModeClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 608 of file lms7002_pnlMCU_BD_view.cpp.
References pnlMCU_BD_view::DebugMode, DebugModeExit_MCU(), DebugModeSet_MCU(), pnlMCU_BD_view::EraseIRAM, pnlMCU_BD_view::InstrNo, m_iDebug, m_iMode0, m_iMode1, pnlMCU_BD_view::ResetPC, pnlMCU_BD_view::RunInstr, pnlMCU_BD_view::SelDiv, pnlMCU_BD_view::ViewIRAM, and pnlMCU_BD_view::ViewSFRs.
int lms7002_pnlMCU_BD_view::One_byte_command (unsigned short data1, unsigned char * rdata1) protected
Definition at line 441 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_WriteLMSReg(), lmsControl, ReadOneByte(), and WaitUntilWritten().
Referenced by ResetPC_MCU().
void lms7002_pnlMCU_BD_view::OnEraseIRAMClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 1001 of file lms7002_pnlMCU_BD_view.cpp.
References Erase_IRAM(), ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, mThreadWorking, mWorkerThread, OnEraseIRAMfinished(), OnProgramingStatusUpdate(), pnlMCU_BD_view::progressBar, and progressPooler.
void lms7002_pnlMCU_BD_view::OnEraseIRAMfinished (wxThreadEvent & event) protected
Definition at line 1116 of file lms7002_pnlMCU_BD_view.cpp.
References ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, mThreadWorking, mWorkerThread, OnProgramingStatusUpdate(), pnlMCU_BD_view::progressBar, and progressPooler.
Referenced by OnEraseIRAMClick().
void lms7002_pnlMCU_BD_view::Onm_cCtrlBasebandSelect (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 1045 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_WriteLMSReg(), and lmsControl.
void lms7002_pnlMCU_BD_view::Onm_cCtrlMCU_BDSelect (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 1050 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_WriteLMSReg(), and lmsControl.
void lms7002_pnlMCU_BD_view::OnProgramingStatusUpdate (wxCommandEvent & event) protected
Definition at line 1091 of file lms7002_pnlMCU_BD_view.cpp.
References pnlMCU_BD_view::progressBar.
Referenced by OnbtnStartProgrammingClick(), OnEraseIRAMClick(), OnEraseIRAMfinished(), OnProgrammingfinished(), OnReadIRAMfinished(), OnReadSFRfinished(), OnViewIRAMClick(), and OnViewSFRsClick().
bool lms7002_pnlMCU_BD_view::OnProgrammingCallback (int bsent, int btotal, const char * progressMsg) static protected
Definition at line 1080 of file lms7002_pnlMCU_BD_view.cpp.
References ID_PROGRAMING_STATUS_EVENT, and obj_ptr.
Referenced by Erase_IRAM(), OnbtnStartProgrammingClick(), Read_IRAM(), and Read_SFR().
void lms7002_pnlMCU_BD_view::OnProgrammingfinished (wxThreadEvent & event) protected
Definition at line 1150 of file lms7002_pnlMCU_BD_view.cpp.
References pnlMCU_BD_view::btnStartProgramming, ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, mThreadWorking, mWorkerThread, OnProgramingStatusUpdate(), pnlMCU_BD_view::progressBar, progressPooler, and pnlMCU_BD_view::rgrMode.
Referenced by OnbtnStartProgrammingClick().
void lms7002_pnlMCU_BD_view::OnReadIRAMfinished (wxThreadEvent & event) protected
Definition at line 1096 of file lms7002_pnlMCU_BD_view.cpp.
References ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, dlgViewIRAM::InitGridData(), m_IRAM, mThreadWorking, mWorkerThread, OnProgramingStatusUpdate(), pnlMCU_BD_view::progressBar, and progressPooler.
Referenced by OnViewIRAMClick().
void lms7002_pnlMCU_BD_view::OnReadSFRfinished (wxThreadEvent & event) protected
Definition at line 1130 of file lms7002_pnlMCU_BD_view.cpp.
References ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, dlgViewSFR::InitGridData(), m_SFR, mThreadWorking, mWorkerThread, OnProgramingStatusUpdate(), pnlMCU_BD_view::progressBar, and progressPooler.
Referenced by OnViewSFRsClick().
void lms7002_pnlMCU_BD_view::OnRegWriteRead (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 1055 of file lms7002_pnlMCU_BD_view.cpp.
References pnlMCU_BD_view::cmbRegAddr, LMS_ReadLMSReg(), LMS_WriteLMSReg(), lmsControl, pnlMCU_BD_view::rbtnRegWrite, pnlMCU_BD_view::ReadResult, and pnlMCU_BD_view::txtRegValueWr.
void lms7002_pnlMCU_BD_view::OnResetPCClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 671 of file lms7002_pnlMCU_BD_view.cpp.
References ResetPC_MCU().
void lms7002_pnlMCU_BD_view::OnRunInstruction (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 638 of file lms7002_pnlMCU_BD_view.cpp.
References i, pnlMCU_BD_view::InstrNo, m_iInstrNo, m_iPCvalue, pnlMCU_BD_view::PCValue, and RunInstr_MCU().
void lms7002_pnlMCU_BD_view::OnSelDivSelect (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 1032 of file lms7002_pnlMCU_BD_view.cpp.
References Change_MCUFrequency(), and pnlMCU_BD_view::SelDiv.
void lms7002_pnlMCU_BD_view::OnViewIRAMClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 947 of file lms7002_pnlMCU_BD_view.cpp.
References ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, mThreadWorking, mWorkerThread, OnProgramingStatusUpdate(), OnReadIRAMfinished(), pnlMCU_BD_view::progressBar, progressPooler, and Read_IRAM().
void lms7002_pnlMCU_BD_view::OnViewSFRsClick (wxCommandEvent & event) protected virtual
Reimplemented from pnlMCU_BD_view.
Definition at line 890 of file lms7002_pnlMCU_BD_view.cpp.
References ID_PROGRAMING_FINISH_EVENT, ID_PROGRAMING_STATUS_EVENT, mThreadWorking, mWorkerThread, OnProgramingStatusUpdate(), OnReadSFRfinished(), pnlMCU_BD_view::progressBar, progressPooler, and Read_SFR().
int lms7002_pnlMCU_BD_view::Read_IRAM () protected
Definition at line 912 of file lms7002_pnlMCU_BD_view.cpp.
References i, m_IRAM, OnProgrammingCallback(), Three_byte_command(), and Wait_CLK_Cycles().
Referenced by OnViewIRAMClick().
int lms7002_pnlMCU_BD_view::Read_SFR () protected
Definition at line 678 of file lms7002_pnlMCU_BD_view.cpp.
References i, m_SFR, OnProgrammingCallback(), and Three_byte_command().
Referenced by OnViewSFRsClick().
int lms7002_pnlMCU_BD_view::ReadOneByte (unsigned char * data) protected
Definition at line 409 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_ReadLMSReg(), lmsControl, and m_iLoopTries.
Referenced by One_byte_command(), and Three_byte_command().
int lms7002_pnlMCU_BD_view::ResetPC_MCU () protected
Definition at line 462 of file lms7002_pnlMCU_BD_view.cpp.
References One_byte_command().
Referenced by OnResetPCClick().
int lms7002_pnlMCU_BD_view::RunInstr_MCU (unsigned short * pPCVAL) protected
Definition at line 503 of file lms7002_pnlMCU_BD_view.cpp.
References Three_byte_command().
Referenced by OnRunInstruction().
int lms7002_pnlMCU_BD_view::RunProductionTest_MCU () protected
void lms7002_pnlMCU_BD_view::RunTest_MCU (int m_iMode1, int m_iMode0, unsigned short test_code, int m_iDebug) protected
Definition at line 290 of file lms7002_pnlMCU_BD_view.cpp.
References i, LMS_WriteLMSReg(), lmsControl, and Wait_CLK_Cycles().
Referenced by OnbtnRunTestClick().
int lms7002_pnlMCU_BD_view::Three_byte_command (unsigned char data1, unsigned char data2, unsigned char data3, unsigned char * rdata1, unsigned char * rdata2, unsigned char * rdata3) protected
Definition at line 470 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_WriteLMSReg(), lmsControl, ReadOneByte(), and WaitUntilWritten().
Referenced by Change_MCUFrequency(), Erase_IRAM(), OnbtnRunTestClick(), Read_IRAM(), Read_SFR(), and RunInstr_MCU().
void lms7002_pnlMCU_BD_view::Wait_CLK_Cycles (int delay) protected
Definition at line 281 of file lms7002_pnlMCU_BD_view.cpp.
References i, LMS_ReadLMSReg(), lmsControl, and val.
Referenced by Read_IRAM(), and RunTest_MCU().
int lms7002_pnlMCU_BD_view::WaitUntilWritten () protected
Definition at line 389 of file lms7002_pnlMCU_BD_view.cpp.
References LMS_ReadLMSReg(), lmsControl, and m_iLoopTries.
Referenced by One_byte_command(), and Three_byte_command().
Member Data Documentation
unsigned char lms7002_pnlMCU_BD_view::byte_array[max_array_size] protected
Definition at line 91 of file lms7002_pnlMCU_BD_view.h.
Referenced by GetProgramCode(), and OnbtnStartProgrammingClick().
const long lms7002_pnlMCU_BD_view::ID_PROGRAMING_FINISH_EVENT = wxNewId() static protected
Definition at line 97 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnbtnStartProgrammingClick(), OnEraseIRAMClick(), OnEraseIRAMfinished(), OnProgrammingfinished(), OnReadIRAMfinished(), OnReadSFRfinished(), OnViewIRAMClick(), and OnViewSFRsClick().
const long lms7002_pnlMCU_BD_view::ID_PROGRAMING_STATUS_EVENT = wxNewId() static protected
Definition at line 96 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnbtnStartProgrammingClick(), OnEraseIRAMClick(), OnEraseIRAMfinished(), OnProgrammingCallback(), OnProgrammingfinished(), OnReadIRAMfinished(), OnReadSFRfinished(), OnViewIRAMClick(), and OnViewSFRsClick().
lms_device_t* lms7002_pnlMCU_BD_view::lmsControl protected
Definition at line 71 of file lms7002_pnlMCU_BD_view.h.
Referenced by DebugModeExit_MCU(), DebugModeSet_MCU(), Initialize(), OnbtnStartProgrammingClick(), OnchkResetClick(), One_byte_command(), Onm_cCtrlBasebandSelect(), Onm_cCtrlMCU_BDSelect(), OnRegWriteRead(), ReadOneByte(), RunTest_MCU(), Three_byte_command(), Wait_CLK_Cycles(), and WaitUntilWritten().
int lms7002_pnlMCU_BD_view::m_bLoadedDebug protected
Definition at line 89 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), and OnchkResetClick().
int lms7002_pnlMCU_BD_view::m_bLoadedProd protected
Definition at line 88 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), and OnchkResetClick().
int lms7002_pnlMCU_BD_view::m_iDebug protected
Definition at line 75 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), OnbtnRunTestClick(), OnchkResetClick(), and OnDebugModeClick().
int lms7002_pnlMCU_BD_view::m_iInstrNo protected
Definition at line 73 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), and OnRunInstruction().
int lms7002_pnlMCU_BD_view::m_iLoopTries protected
Definition at line 92 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), ReadOneByte(), and WaitUntilWritten().
int lms7002_pnlMCU_BD_view::m_iMode0 protected
Definition at line 76 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), OnbtnRunTestClick(), OnbtnStartProgrammingClick(), OnchkResetClick(), and OnDebugModeClick().
int lms7002_pnlMCU_BD_view::m_iMode1 protected
Definition at line 77 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), OnbtnRunTestClick(), OnbtnStartProgrammingClick(), OnchkResetClick(), and OnDebugModeClick().
int lms7002_pnlMCU_BD_view::m_iPCvalue protected
Definition at line 74 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), and OnRunInstruction().
unsigned char lms7002_pnlMCU_BD_view::m_IRAM[256] protected
Definition at line 93 of file lms7002_pnlMCU_BD_view.h.
Referenced by Erase_IRAM(), OnReadIRAMfinished(), and Read_IRAM().
unsigned short lms7002_pnlMCU_BD_view::m_iRegAddress protected
Definition at line 84 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view().
unsigned short lms7002_pnlMCU_BD_view::m_iRegData protected
Definition at line 86 of file lms7002_pnlMCU_BD_view.h.
int lms7002_pnlMCU_BD_view::m_iRegRead protected
Definition at line 85 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view().
int lms7002_pnlMCU_BD_view::m_iTestNo protected
Definition at line 72 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), and OnbtnRunTestClick().
int lms7002_pnlMCU_BD_view::m_iTestResultFileLine protected
Definition at line 79 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnbtnLoadTestFileClick(), and OnbtnRunTestClick().
unsigned char lms7002_pnlMCU_BD_view::m_SFR[256] protected
Definition at line 94 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnReadSFRfinished(), and Read_SFR().
const size_t lms7002_pnlMCU_BD_view::max_array_size = 16 * 1024 static protected
Definition at line 44 of file lms7002_pnlMCU_BD_view.h.
Referenced by GetProgramCode(), and OnbtnStartProgrammingClick().
std::string lms7002_pnlMCU_BD_view::mLoadedProgramFilename protected
Definition at line 90 of file lms7002_pnlMCU_BD_view.h.
Referenced by GetProgramCode(), and lms7002_pnlMCU_BD_view().
bool lms7002_pnlMCU_BD_view::mThreadWorking protected
Definition at line 68 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), OnbtnStartProgrammingClick(), OnEraseIRAMClick(), OnEraseIRAMfinished(), OnProgrammingfinished(), OnReadIRAMfinished(), OnReadSFRfinished(), OnViewIRAMClick(), OnViewSFRsClick(), and ~lms7002_pnlMCU_BD_view().
std::thread lms7002_pnlMCU_BD_view::mWorkerThread protected
Definition at line 69 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnbtnStartProgrammingClick(), OnEraseIRAMClick(), OnEraseIRAMfinished(), OnProgrammingfinished(), OnReadIRAMfinished(), OnReadSFRfinished(), OnViewIRAMClick(), OnViewSFRsClick(), and ~lms7002_pnlMCU_BD_view().
lms7002_pnlMCU_BD_view * lms7002_pnlMCU_BD_view::obj_ptr =nullptr static protected
Definition at line 95 of file lms7002_pnlMCU_BD_view.h.
Referenced by Initialize(), lms7002_pnlMCU_BD_view(), OnbtnStartProgrammingClick(), and OnProgrammingCallback().
wxTimer* lms7002_pnlMCU_BD_view::progressPooler protected
Definition at line 70 of file lms7002_pnlMCU_BD_view.h.
Referenced by lms7002_pnlMCU_BD_view(), OnbtnStartProgrammingClick(), OnEraseIRAMClick(), OnEraseIRAMfinished(), OnProgrammingfinished(), OnReadIRAMfinished(), OnReadSFRfinished(), OnViewIRAMClick(), and OnViewSFRsClick().
int lms7002_pnlMCU_BD_view::TestResultArray_address[256] protected
Definition at line 81 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnbtnLoadTestFileClick(), and OnbtnRunTestClick().
int lms7002_pnlMCU_BD_view::TestResultArray_code[256] protected
Definition at line 80 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnbtnLoadTestFileClick(), and OnbtnRunTestClick().
int lms7002_pnlMCU_BD_view::TestResultArray_value[256] protected
Definition at line 82 of file lms7002_pnlMCU_BD_view.h.
Referenced by OnbtnLoadTestFileClick(), and OnbtnRunTestClick().
The documentation for this class was generated from the following files:
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlMCU_BD_view.h
/home/erik/prefix/default/src/limesuite-dev/src/lms7002_wxgui/lms7002_pnlMCU_BD_view.cpp